/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */
/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
// Translation of iterators.lskel-big-endian.h.  Declarations supplied by
// bpf/skel_internal.h remain external dependencies.

#[repr(C)]
pub struct iterators_bpf {
    pub ctx: bpf_loader_ctx,
    pub maps: iterators_bpf_maps,
    pub progs: iterators_bpf_progs,
    pub links: iterators_bpf_links,
}
#[repr(C)] pub struct iterators_bpf_maps { pub rodata: bpf_map_desc }
#[repr(C)] pub struct iterators_bpf_progs { pub dump_bpf_map: bpf_prog_desc, pub dump_bpf_prog: bpf_prog_desc }
#[repr(C)] pub struct iterators_bpf_links { pub dump_bpf_map_fd: i32, pub dump_bpf_prog_fd: i32 }

pub unsafe fn iterators_bpf__dump_bpf_map__attach(skel: *mut iterators_bpf) -> i32 {
    let prog_fd = (*skel).progs.dump_bpf_map.prog_fd;
    let fd = skel_link_create(prog_fd, 0, BPF_TRACE_ITER);
    if fd > 0 { (*skel).links.dump_bpf_map_fd = fd; }
    fd
}
pub unsafe fn iterators_bpf__dump_bpf_prog__attach(skel: *mut iterators_bpf) -> i32 {
    let prog_fd = (*skel).progs.dump_bpf_prog.prog_fd;
    let fd = skel_link_create(prog_fd, 0, BPF_TRACE_ITER);
    if fd > 0 { (*skel).links.dump_bpf_prog_fd = fd; }
    fd
}
pub unsafe fn iterators_bpf__attach(skel: *mut iterators_bpf) -> i32 {
    let mut ret = 0;
    ret = if ret < 0 { ret } else { iterators_bpf__dump_bpf_map__attach(skel) };
    ret = if ret < 0 { ret } else { iterators_bpf__dump_bpf_prog__attach(skel) };
    if ret < 0 { ret } else { 0 }
}
pub unsafe fn iterators_bpf__detach(skel: *mut iterators_bpf) {
    skel_closenz((*skel).links.dump_bpf_map_fd);
    skel_closenz((*skel).links.dump_bpf_prog_fd);
}
pub unsafe fn iterators_bpf__destroy(skel: *mut iterators_bpf) {
    if skel.is_null() { return; }
    iterators_bpf__detach(skel);
    skel_closenz((*skel).progs.dump_bpf_map.prog_fd);
    skel_closenz((*skel).progs.dump_bpf_prog.prog_fd);
    skel_closenz((*skel).maps.rodata.map_fd);
    skel_free(skel as *mut _);
}
pub unsafe fn iterators_bpf__open() -> *mut iterators_bpf {
    let skel = skel_alloc(core::mem::size_of::<iterators_bpf>()) as *mut iterators_bpf;
    if skel.is_null() { iterators_bpf__destroy(skel); return core::ptr::null_mut(); }
    (*skel).ctx.sz = (&(*skel).links as *const _ as usize - skel as usize);
    skel
}

// The generated loader payloads are opaque ELF/BPF byte strings.  Their
// external representation is retained here for the loader interface; the
// bytes are supplied by the generated object data in the surrounding build.
static OPTS_DATA: &[u8] = &[];
static OPTS_INSN: &[u8] = &[];

pub unsafe fn iterators_bpf__load(skel: *mut iterators_bpf) -> i32 {
    let mut opts: bpf_load_and_run_opts = core::mem::zeroed();
    opts.ctx = skel as *mut bpf_loader_ctx;
    opts.data_sz = OPTS_DATA.len(); opts.data = OPTS_DATA.as_ptr() as *mut _;
    opts.insns_sz = OPTS_INSN.len(); opts.insns = OPTS_INSN.as_ptr() as *mut _;
    let err = bpf_load_and_run(&mut opts);
    if err < 0 { return err; } 0
}
pub unsafe fn iterators_bpf__open_and_load() -> *mut iterators_bpf {
    let skel = iterators_bpf__open();
    if skel.is_null() { return core::ptr::null_mut(); }
    if iterators_bpf__load(skel) != 0 { iterators_bpf__destroy(skel); return core::ptr::null_mut(); }
    skel
}
pub unsafe fn iterators_bpf__assert(_s: *mut iterators_bpf) {}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
