/* SPDX-License-Identifier: GPL-2.0 */
/* Translation of kernel/lockdep_internals.h. */

/* LOCKDEP_STATE entries are generated by the external lockdep_states.h. */
#[repr(C)]
pub enum lock_usage_bit {
    LockUsed,
    LockUsedRead,
    LockUsageStates,
}

pub const LOCK_USAGE_READ_MASK: u32 = 1;
pub const LOCK_USAGE_DIR_MASK: u32 = 2;
pub const LOCK_USAGE_STATE_MASK: u32 = !(LOCK_USAGE_READ_MASK | LOCK_USAGE_DIR_MASK);

/* The generated LOCKF_* state constants come from lockdep_states.h. */
pub const LOCKF_USED: u64 = 1u64 << (lock_usage_bit::LockUsed as u32);
pub const LOCKF_USED_READ: u64 = 1u64 << (lock_usage_bit::LockUsedRead as u32);

/* Generated aggregate masks retain their source-level dependency on state definitions. */
extern "C" {
    pub static LOCKF_ENABLED_IRQ: u64;
    pub static LOCKF_USED_IN_IRQ: u64;
    pub static LOCKF_ENABLED_IRQ_READ: u64;
    pub static LOCKF_USED_IN_IRQ_READ: u64;
}

pub const LOCKF_ENABLED_IRQ_ALL: u64 = LOCKF_ENABLED_IRQ | LOCKF_ENABLED_IRQ_READ;
pub const LOCKF_USED_IN_IRQ_ALL: u64 = LOCKF_USED_IN_IRQ | LOCKF_USED_IN_IRQ_READ;
pub const LOCKF_IRQ: u64 = LOCKF_ENABLED_IRQ | LOCKF_USED_IN_IRQ;
pub const LOCKF_IRQ_READ: u64 = LOCKF_ENABLED_IRQ_READ | LOCKF_USED_IN_IRQ_READ;

#[cfg(CONFIG_LOCKDEP_SMALL)]
pub const MAX_LOCKDEP_ENTRIES: usize = 16384;
#[cfg(CONFIG_LOCKDEP_SMALL)]
pub const MAX_LOCKDEP_CHAINS_BITS: usize = 15;
#[cfg(CONFIG_LOCKDEP_SMALL)]
pub const MAX_STACK_TRACE_ENTRIES: usize = 262144;
#[cfg(CONFIG_LOCKDEP_SMALL)]
pub const STACK_TRACE_HASH_SIZE: usize = 8192;

#[cfg(not(CONFIG_LOCKDEP_SMALL))]
pub const MAX_LOCKDEP_ENTRIES: usize = 1usize << CONFIG_LOCKDEP_BITS;
#[cfg(not(CONFIG_LOCKDEP_SMALL))]
pub const MAX_LOCKDEP_CHAINS_BITS: usize = CONFIG_LOCKDEP_CHAINS_BITS;
#[cfg(not(CONFIG_LOCKDEP_SMALL))]
pub const MAX_STACK_TRACE_ENTRIES: usize = 1usize << CONFIG_LOCKDEP_STACK_TRACE_BITS;
#[cfg(not(CONFIG_LOCKDEP_SMALL))]
pub const STACK_TRACE_HASH_SIZE: usize = 1usize << CONFIG_LOCKDEP_STACK_TRACE_HASH_BITS;

pub const LOCK_CHAIN_SOFTIRQ_CONTEXT: u32 = 1 << 0;
pub const LOCK_CHAIN_HARDIRQ_CONTEXT: u32 = 1 << 1;
pub const MAX_LOCKDEP_CHAINS: usize = 1usize << MAX_LOCKDEP_CHAINS_BITS;
pub const AVG_LOCKDEP_CHAIN_DEPTH: usize = 5;
pub const MAX_LOCKDEP_CHAIN_HLOCKS: usize = MAX_LOCKDEP_CHAINS * AVG_LOCKDEP_CHAIN_DEPTH;
pub const LOCK_USAGE_CHARS: usize = 2 * XXX_LOCK_USAGE_STATES + 1;

pub enum lock_chain {}
pub enum lock_class {}
pub enum lockdep_subclass_key {}

extern "C" {
    pub static mut lock_chains: [lock_chain; 0];
    pub fn get_usage_chars(class: *mut lock_class, usage: *mut core::ffi::c_char);
    pub fn __get_key_name(key: *const lockdep_subclass_key, string: *mut core::ffi::c_char) -> *const core::ffi::c_char;
    pub fn lock_chain_get_class(chain: *mut lock_chain, i: core::ffi::c_int) -> *mut lock_class;
    pub static mut nr_lock_classes: core::ffi::c_ulong;
    pub static mut nr_zapped_classes: core::ffi::c_ulong;
    pub static mut nr_zapped_lock_chains: core::ffi::c_ulong;
    pub static mut nr_list_entries: core::ffi::c_ulong;
    pub static mut nr_dynamic_keys: core::ffi::c_ulong;
    pub fn lockdep_next_lockchain(i: core::ffi::c_long) -> core::ffi::c_long;
    pub fn lock_chain_count() -> core::ffi::c_ulong;
    pub static mut nr_stack_trace_entries: core::ffi::c_ulong;
    pub static mut nr_hardirq_chains: core::ffi::c_uint;
    pub static mut nr_softirq_chains: core::ffi::c_uint;
    pub static mut nr_process_chains: core::ffi::c_uint;
    pub static mut nr_free_chain_hlocks: core::ffi::c_uint;
    pub static mut nr_lost_chain_hlocks: core::ffi::c_uint;
    pub static mut nr_large_chain_blocks: core::ffi::c_uint;
    pub static mut max_lockdep_depth: core::ffi::c_uint;
    pub static mut max_bfs_queue_depth: core::ffi::c_uint;
    pub static mut max_lock_class_idx: core::ffi::c_ulong;
    pub static mut lock_classes: [lock_class; 0];
    pub static mut lock_classes_in_use: [core::ffi::c_ulong; 0];
}

#[cfg(not(CONFIG_PROVE_LOCKING))]
#[inline]
pub unsafe fn lockdep_count_forward_deps(_class: *mut lock_class) -> core::ffi::c_ulong { 0 }
#[cfg(not(CONFIG_PROVE_LOCKING))]
#[inline]
pub unsafe fn lockdep_count_backward_deps(_class: *mut lock_class) -> core::ffi::c_ulong { 0 }

#[cfg(CONFIG_PROVE_LOCKING)]
extern "C" {
    pub fn lockdep_count_forward_deps(class: *mut lock_class) -> core::ffi::c_ulong;
    pub fn lockdep_count_backward_deps(class: *mut lock_class) -> core::ffi::c_ulong;
}

#[cfg(all(CONFIG_PROVE_LOCKING, CONFIG_TRACE_IRQFLAGS))]
extern "C" {
    pub fn lockdep_stack_trace_count() -> u64;
    pub fn lockdep_stack_hash_count() -> u64;
}

#[cfg(CONFIG_DEBUG_LOCKDEP)]
#[repr(C)]
pub struct lockdep_stats {
    pub chain_lookup_hits: core::ffi::c_ulong,
    pub chain_lookup_misses: core::ffi::c_uint,
    pub hardirqs_on_events: core::ffi::c_ulong,
    pub hardirqs_off_events: core::ffi::c_ulong,
    pub redundant_hardirqs_on: core::ffi::c_ulong,
    pub redundant_hardirqs_off: core::ffi::c_ulong,
    pub softirqs_on_events: core::ffi::c_ulong,
    pub softirqs_off_events: core::ffi::c_ulong,
    pub redundant_softirqs_on: core::ffi::c_ulong,
    pub redundant_softirqs_off: core::ffi::c_ulong,
    pub nr_unused_locks: core::ffi::c_int,
    pub nr_redundant_checks: core::ffi::c_uint,
    pub nr_redundant: core::ffi::c_uint,
    pub nr_cyclic_checks: core::ffi::c_uint,
    pub nr_find_usage_forwards_checks: core::ffi::c_uint,
    pub nr_find_usage_backwards_checks: core::ffi::c_uint,
    pub lock_class_ops: [core::ffi::c_ulong; 0],
}

#[cfg(CONFIG_DEBUG_LOCKDEP)]
extern "C" {
    pub static mut lockdep_stats: lockdep_stats;
}

#[cfg(CONFIG_DEBUG_LOCKDEP)]
#[inline]
pub unsafe fn debug_class_ops_inc(class: *mut lock_class) {
    let idx = class.offset_from(lock_classes.as_mut_ptr()) as usize;
    let _ = idx;
    /* __debug_atomic_inc(lock_class_ops[idx]); */
}

#[cfg(CONFIG_DEBUG_LOCKDEP)]
#[inline]
pub unsafe fn debug_class_ops_read(class: *mut lock_class) -> core::ffi::c_ulong {
    let idx = class.offset_from(lock_classes.as_mut_ptr()) as usize;
    let _ = idx;
    /* Per-CPU summation is supplied by the external kernel infrastructure. */
    0
}

#[cfg(not(CONFIG_DEBUG_LOCKDEP))]
#[macro_export]
macro_rules! __debug_atomic_inc { ($ptr:expr) => {{ let _ = &$ptr; }} }
#[cfg(not(CONFIG_DEBUG_LOCKDEP))]
#[macro_export]
macro_rules! debug_atomic_inc { ($ptr:expr) => {{ let _ = &$ptr; }} }
#[cfg(not(CONFIG_DEBUG_LOCKDEP))]
#[macro_export]
macro_rules! debug_atomic_dec { ($ptr:expr) => {{ let _ = &$ptr; }} }
#[cfg(not(CONFIG_DEBUG_LOCKDEP))]
#[macro_export]
macro_rules! debug_atomic_read { ($ptr:expr) => {{ let _ = &$ptr; 0 }} }
#[cfg(not(CONFIG_DEBUG_LOCKDEP))]
#[macro_export]
macro_rules! debug_class_ops_inc { ($ptr:expr) => {{ let _ = &$ptr; }} }

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
