# SPDX-License-Identifier: GPL-2.0
hostprogs := elf-entry
elf-entry-rust := y
PHONY += elf-entry
elf-entry: $(obj)/elf-entry
	@:

hostprogs += loongson3-llsc-check
loongson3-llsc-check-rust := y
PHONY += loongson3-llsc-check
loongson3-llsc-check: $(obj)/loongson3-llsc-check
	@:
