/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * tegra30_ahub.h - Definitions for Tegra30 AHUB driver
 *
 * Copyright (c) 2011,2012, NVIDIA CORPORATION.  All rights reserved.
 */

/* Fields in *_CIF_RX/TX_CTRL; used by AHUB FIFOs, and all other audio modules */

pub const TEGRA30_AUDIOCIF_CTRL_FIFO_THRESHOLD_SHIFT: u32 = 28;
pub const TEGRA30_AUDIOCIF_CTRL_FIFO_THRESHOLD_MASK_US: u32 = 0xf;
pub const TEGRA30_AUDIOCIF_CTRL_FIFO_THRESHOLD_MASK: u32 =
    TEGRA30_AUDIOCIF_CTRL_FIFO_THRESHOLD_MASK_US << TEGRA30_AUDIOCIF_CTRL_FIFO_THRESHOLD_SHIFT;

pub const TEGRA124_AUDIOCIF_CTRL_FIFO_THRESHOLD_SHIFT: u32 = 24;
pub const TEGRA124_AUDIOCIF_CTRL_FIFO_THRESHOLD_MASK_US: u32 = 0x3f;
pub const TEGRA124_AUDIOCIF_CTRL_FIFO_THRESHOLD_MASK: u32 =
    TEGRA124_AUDIOCIF_CTRL_FIFO_THRESHOLD_MASK_US << TEGRA124_AUDIOCIF_CTRL_FIFO_THRESHOLD_SHIFT;

/* Channel count minus 1 */
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_CHANNELS_SHIFT: u32 = 24;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_CHANNELS_MASK_US: u32 = 7;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_CHANNELS_MASK: u32 =
    TEGRA30_AUDIOCIF_CTRL_AUDIO_CHANNELS_MASK_US << TEGRA30_AUDIOCIF_CTRL_AUDIO_CHANNELS_SHIFT;

/* Channel count minus 1 */
pub const TEGRA124_AUDIOCIF_CTRL_AUDIO_CHANNELS_SHIFT: u32 = 20;
pub const TEGRA124_AUDIOCIF_CTRL_AUDIO_CHANNELS_MASK_US: u32 = 0xf;
pub const TEGRA124_AUDIOCIF_CTRL_AUDIO_CHANNELS_MASK: u32 =
    TEGRA124_AUDIOCIF_CTRL_AUDIO_CHANNELS_MASK_US << TEGRA124_AUDIOCIF_CTRL_AUDIO_CHANNELS_SHIFT;

/* Channel count minus 1 */
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_CHANNELS_SHIFT: u32 = 16;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_CHANNELS_MASK_US: u32 = 7;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_CHANNELS_MASK: u32 =
    TEGRA30_AUDIOCIF_CTRL_CLIENT_CHANNELS_MASK_US << TEGRA30_AUDIOCIF_CTRL_CLIENT_CHANNELS_SHIFT;

/* Channel count minus 1 */
pub const TEGRA124_AUDIOCIF_CTRL_CLIENT_CHANNELS_SHIFT: u32 = 16;
pub const TEGRA124_AUDIOCIF_CTRL_CLIENT_CHANNELS_MASK_US: u32 = 0xf;
pub const TEGRA124_AUDIOCIF_CTRL_CLIENT_CHANNELS_MASK: u32 =
    TEGRA30_AUDIOCIF_CTRL_CLIENT_CHANNELS_MASK_US << TEGRA30_AUDIOCIF_CTRL_CLIENT_CHANNELS_SHIFT;

pub const TEGRA30_AUDIOCIF_BITS_4: u32 = 0;
pub const TEGRA30_AUDIOCIF_BITS_8: u32 = 1;
pub const TEGRA30_AUDIOCIF_BITS_12: u32 = 2;
pub const TEGRA30_AUDIOCIF_BITS_16: u32 = 3;
pub const TEGRA30_AUDIOCIF_BITS_20: u32 = 4;
pub const TEGRA30_AUDIOCIF_BITS_24: u32 = 5;
pub const TEGRA30_AUDIOCIF_BITS_28: u32 = 6;
pub const TEGRA30_AUDIOCIF_BITS_32: u32 = 7;

pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT: u32 = 12;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_MASK: u32 =
    7 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_4: u32 =
    TEGRA30_AUDIOCIF_BITS_4 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_8: u32 =
    TEGRA30_AUDIOCIF_BITS_8 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_12: u32 =
    TEGRA30_AUDIOCIF_BITS_12 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_16: u32 =
    TEGRA30_AUDIOCIF_BITS_16 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_20: u32 =
    TEGRA30_AUDIOCIF_BITS_20 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_24: u32 =
    TEGRA30_AUDIOCIF_BITS_24 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_28: u32 =
    TEGRA30_AUDIOCIF_BITS_28 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_32: u32 =
    TEGRA30_AUDIOCIF_BITS_32 << TEGRA30_AUDIOCIF_CTRL_AUDIO_BITS_SHIFT;

pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT: u32 = 8;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_MASK: u32 =
    7 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_4: u32 =
    TEGRA30_AUDIOCIF_BITS_4 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_8: u32 =
    TEGRA30_AUDIOCIF_BITS_8 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_12: u32 =
    TEGRA30_AUDIOCIF_BITS_12 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_16: u32 =
    TEGRA30_AUDIOCIF_BITS_16 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_20: u32 =
    TEGRA30_AUDIOCIF_BITS_20 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_24: u32 =
    TEGRA30_AUDIOCIF_BITS_24 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_28: u32 =
    TEGRA30_AUDIOCIF_BITS_28 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_32: u32 =
    TEGRA30_AUDIOCIF_BITS_32 << TEGRA30_AUDIOCIF_CTRL_CLIENT_BITS_SHIFT;

pub const TEGRA30_AUDIOCIF_EXPAND_ZERO: u32 = 0;
pub const TEGRA30_AUDIOCIF_EXPAND_ONE: u32 = 1;
pub const TEGRA30_AUDIOCIF_EXPAND_LFSR: u32 = 2;

pub const TEGRA30_AUDIOCIF_CTRL_EXPAND_SHIFT: u32 = 6;
pub const TEGRA30_AUDIOCIF_CTRL_EXPAND_MASK: u32 = 3 << TEGRA30_AUDIOCIF_CTRL_EXPAND_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_EXPAND_ZERO: u32 =
    TEGRA30_AUDIOCIF_EXPAND_ZERO << TEGRA30_AUDIOCIF_CTRL_EXPAND_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_EXPAND_ONE: u32 =
    TEGRA30_AUDIOCIF_EXPAND_ONE << TEGRA30_AUDIOCIF_CTRL_EXPAND_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_EXPAND_LFSR: u32 =
    TEGRA30_AUDIOCIF_EXPAND_LFSR << TEGRA30_AUDIOCIF_CTRL_EXPAND_SHIFT;

pub const TEGRA30_AUDIOCIF_STEREO_CONV_CH0: u32 = 0;
pub const TEGRA30_AUDIOCIF_STEREO_CONV_CH1: u32 = 1;
pub const TEGRA30_AUDIOCIF_STEREO_CONV_AVG: u32 = 2;

pub const TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_SHIFT: u32 = 4;
pub const TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_MASK: u32 =
    3 << TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_CH0: u32 =
    TEGRA30_AUDIOCIF_STEREO_CONV_CH0 << TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_CH1: u32 =
    TEGRA30_AUDIOCIF_STEREO_CONV_CH1 << TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_AVG: u32 =
    TEGRA30_AUDIOCIF_STEREO_CONV_AVG << TEGRA30_AUDIOCIF_CTRL_STEREO_CONV_SHIFT;

pub const TEGRA30_AUDIOCIF_CTRL_REPLICATE_SHIFT: u32 = 3;

pub const TEGRA30_AUDIOCIF_DIRECTION_TX: u32 = 0;
pub const TEGRA30_AUDIOCIF_DIRECTION_RX: u32 = 1;

pub const TEGRA30_AUDIOCIF_CTRL_DIRECTION_SHIFT: u32 = 2;
pub const TEGRA30_AUDIOCIF_CTRL_DIRECTION_MASK: u32 =
    1 << TEGRA30_AUDIOCIF_CTRL_DIRECTION_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_DIRECTION_TX: u32 =
    TEGRA30_AUDIOCIF_DIRECTION_TX << TEGRA30_AUDIOCIF_CTRL_DIRECTION_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_DIRECTION_RX: u32 =
    TEGRA30_AUDIOCIF_DIRECTION_RX << TEGRA30_AUDIOCIF_CTRL_DIRECTION_SHIFT;

pub const TEGRA30_AUDIOCIF_TRUNCATE_ROUND: u32 = 0;
pub const TEGRA30_AUDIOCIF_TRUNCATE_CHOP: u32 = 1;

pub const TEGRA30_AUDIOCIF_CTRL_TRUNCATE_SHIFT: u32 = 1;
pub const TEGRA30_AUDIOCIF_CTRL_TRUNCATE_MASK: u32 =
    1 << TEGRA30_AUDIOCIF_CTRL_TRUNCATE_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_TRUNCATE_ROUND: u32 =
    TEGRA30_AUDIOCIF_TRUNCATE_ROUND << TEGRA30_AUDIOCIF_CTRL_TRUNCATE_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_TRUNCATE_CHOP: u32 =
    TEGRA30_AUDIOCIF_TRUNCATE_CHOP << TEGRA30_AUDIOCIF_CTRL_TRUNCATE_SHIFT;

pub const TEGRA30_AUDIOCIF_MONO_CONV_ZERO: u32 = 0;
pub const TEGRA30_AUDIOCIF_MONO_CONV_COPY: u32 = 1;

pub const TEGRA30_AUDIOCIF_CTRL_MONO_CONV_SHIFT: u32 = 0;
pub const TEGRA30_AUDIOCIF_CTRL_MONO_CONV_MASK: u32 =
    1 << TEGRA30_AUDIOCIF_CTRL_MONO_CONV_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_MONO_CONV_ZERO: u32 =
    TEGRA30_AUDIOCIF_MONO_CONV_ZERO << TEGRA30_AUDIOCIF_CTRL_MONO_CONV_SHIFT;
pub const TEGRA30_AUDIOCIF_CTRL_MONO_CONV_COPY: u32 =
    TEGRA30_AUDIOCIF_MONO_CONV_COPY << TEGRA30_AUDIOCIF_CTRL_MONO_CONV_SHIFT;

/* Registers within TEGRA30_AUDIO_CLUSTER_BASE */

/* TEGRA30_AHUB_CHANNEL_CTRL */

pub const TEGRA30_AHUB_CHANNEL_CTRL: u32 = 0x0;
pub const TEGRA30_AHUB_CHANNEL_CTRL_STRIDE: u32 = 0x20;
pub const TEGRA30_AHUB_CHANNEL_CTRL_COUNT: usize = 4;
pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_EN: u32 = 1 << 31;
pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_EN: u32 = 1 << 30;
pub const TEGRA30_AHUB_CHANNEL_CTRL_LOOPBACK: u32 = 1 << 29;

pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_THRESHOLD_SHIFT: u32 = 16;
pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_THRESHOLD_MASK_US: u32 = 0xff;
pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_THRESHOLD_MASK: u32 =
    TEGRA30_AHUB_CHANNEL_CTRL_TX_THRESHOLD_MASK_US << TEGRA30_AHUB_CHANNEL_CTRL_TX_THRESHOLD_SHIFT;

pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_THRESHOLD_SHIFT: u32 = 8;
pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_THRESHOLD_MASK_US: u32 = 0xff;
pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_THRESHOLD_MASK: u32 =
    TEGRA30_AHUB_CHANNEL_CTRL_RX_THRESHOLD_MASK_US << TEGRA30_AHUB_CHANNEL_CTRL_RX_THRESHOLD_SHIFT;

pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_EN: u32 = 1 << 6;

pub const TEGRA30_PACK_8_4: u32 = 2;
pub const TEGRA30_PACK_16: u32 = 3;

pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_SHIFT: u32 = 4;
pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_MASK_US: u32 = 3;
pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_MASK: u32 =
    TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_MASK_US << TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_SHIFT;
pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_8_4: u32 =
    TEGRA30_PACK_8_4 << TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_SHIFT;
pub const TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_16: u32 =
    TEGRA30_PACK_16 << TEGRA30_AHUB_CHANNEL_CTRL_TX_PACK_SHIFT;

pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_EN: u32 = 1 << 2;

pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_SHIFT: u32 = 0;
pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_MASK_US: u32 = 3;
pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_MASK: u32 =
    TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_MASK_US << TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_SHIFT;
pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_8_4: u32 =
    TEGRA30_PACK_8_4 << TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_SHIFT;
pub const TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_16: u32 =
    TEGRA30_PACK_16 << TEGRA30_AHUB_CHANNEL_CTRL_RX_PACK_SHIFT;

/* TEGRA30_AHUB_CHANNEL_CLEAR */

pub const TEGRA30_AHUB_CHANNEL_CLEAR: u32 = 0x4;
pub const TEGRA30_AHUB_CHANNEL_CLEAR_STRIDE: u32 = 0x20;
pub const TEGRA30_AHUB_CHANNEL_CLEAR_COUNT: usize = 4;
pub const TEGRA30_AHUB_CHANNEL_CLEAR_TX_SOFT_RESET: u32 = 1 << 31;
pub const TEGRA30_AHUB_CHANNEL_CLEAR_RX_SOFT_RESET: u32 = 1 << 30;

/* TEGRA30_AHUB_CHANNEL_STATUS */

pub const TEGRA30_AHUB_CHANNEL_STATUS: u32 = 0x8;
pub const TEGRA30_AHUB_CHANNEL_STATUS_STRIDE: u32 = 0x20;
pub const TEGRA30_AHUB_CHANNEL_STATUS_COUNT: usize = 4;
pub const TEGRA30_AHUB_CHANNEL_STATUS_TX_FREE_SHIFT: u32 = 24;
pub const TEGRA30_AHUB_CHANNEL_STATUS_TX_FREE_MASK_US: u32 = 0xff;
pub const TEGRA30_AHUB_CHANNEL_STATUS_TX_FREE_MASK: u32 =
    TEGRA30_AHUB_CHANNEL_STATUS_TX_FREE_MASK_US << TEGRA30_AHUB_CHANNEL_STATUS_TX_FREE_SHIFT;
pub const TEGRA30_AHUB_CHANNEL_STATUS_RX_FREE_SHIFT: u32 = 16;
pub const TEGRA30_AHUB_CHANNEL_STATUS_RX_FREE_MASK_US: u32 = 0xff;
pub const TEGRA30_AHUB_CHANNEL_STATUS_RX_FREE_MASK: u32 =
    TEGRA30_AHUB_CHANNEL_STATUS_RX_FREE_MASK_US << TEGRA30_AHUB_CHANNEL_STATUS_RX_FREE_SHIFT;
pub const TEGRA30_AHUB_CHANNEL_STATUS_TX_TRIG: u32 = 1 << 1;
pub const TEGRA30_AHUB_CHANNEL_STATUS_RX_TRIG: u32 = 1 << 0;

/* TEGRA30_AHUB_CHANNEL_TXFIFO */

pub const TEGRA30_AHUB_CHANNEL_TXFIFO: u32 = 0xc;
pub const TEGRA30_AHUB_CHANNEL_TXFIFO_STRIDE: u32 = 0x20;
pub const TEGRA30_AHUB_CHANNEL_TXFIFO_COUNT: usize = 4;

/* TEGRA30_AHUB_CHANNEL_RXFIFO */

pub const TEGRA30_AHUB_CHANNEL_RXFIFO: u32 = 0x10;
pub const TEGRA30_AHUB_CHANNEL_RXFIFO_STRIDE: u32 = 0x20;
pub const TEGRA30_AHUB_CHANNEL_RXFIFO_COUNT: usize = 4;

/* TEGRA30_AHUB_CIF_TX_CTRL */

pub const TEGRA30_AHUB_CIF_TX_CTRL: u32 = 0x14;
pub const TEGRA30_AHUB_CIF_TX_CTRL_STRIDE: u32 = 0x20;
pub const TEGRA30_AHUB_CIF_TX_CTRL_COUNT: usize = 4;
/* Uses field from TEGRA30_AUDIOCIF_CTRL_* */

/* TEGRA30_AHUB_CIF_RX_CTRL */

pub const TEGRA30_AHUB_CIF_RX_CTRL: u32 = 0x18;
pub const TEGRA30_AHUB_CIF_RX_CTRL_STRIDE: u32 = 0x20;
pub const TEGRA30_AHUB_CIF_RX_CTRL_COUNT: usize = 4;
/* Uses field from TEGRA30_AUDIOCIF_CTRL_* */

/* TEGRA30_AHUB_CONFIG_LINK_CTRL */

pub const TEGRA30_AHUB_CONFIG_LINK_CTRL: u32 = 0x80;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_MASTER_FIFO_FULL_CNT_SHIFT: u32 = 28;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_MASTER_FIFO_FULL_CNT_MASK_US: u32 = 0xf;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_MASTER_FIFO_FULL_CNT_MASK: u32 =
    TEGRA30_AHUB_CONFIG_LINK_CTRL_MASTER_FIFO_FULL_CNT_MASK_US
        << TEGRA30_AHUB_CONFIG_LINK_CTRL_MASTER_FIFO_FULL_CNT_SHIFT;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_TIMEOUT_CNT_SHIFT: u32 = 16;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_TIMEOUT_CNT_MASK_US: u32 = 0xfff;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_TIMEOUT_CNT_MASK: u32 =
    TEGRA30_AHUB_CONFIG_LINK_CTRL_TIMEOUT_CNT_MASK_US
        << TEGRA30_AHUB_CONFIG_LINK_CTRL_TIMEOUT_CNT_SHIFT;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_IDLE_CNT_SHIFT: u32 = 4;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_IDLE_CNT_MASK_US: u32 = 0xfff;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_IDLE_CNT_MASK: u32 =
    TEGRA30_AHUB_CONFIG_LINK_CTRL_IDLE_CNT_MASK_US << TEGRA30_AHUB_CONFIG_LINK_CTRL_IDLE_CNT_SHIFT;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_CG_EN: u32 = 1 << 2;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_CLEAR_TIMEOUT_CNTR: u32 = 1 << 1;
pub const TEGRA30_AHUB_CONFIG_LINK_CTRL_SOFT_RESET: u32 = 1 << 0;

/* TEGRA30_AHUB_MISC_CTRL */

pub const TEGRA30_AHUB_MISC_CTRL: u32 = 0x84;
pub const TEGRA30_AHUB_MISC_CTRL_AUDIO_ACTIVE: u32 = 1 << 31;
pub const TEGRA30_AHUB_MISC_CTRL_AUDIO_CG_EN: u32 = 1 << 8;
pub const TEGRA30_AHUB_MISC_CTRL_AUDIO_OBS_SEL_SHIFT: u32 = 0;
pub const TEGRA30_AHUB_MISC_CTRL_AUDIO_OBS_SEL_MASK: u32 =
    0x1f << TEGRA30_AHUB_MISC_CTRL_AUDIO_OBS_SEL_SHIFT;

/* TEGRA30_AHUB_APBDMA_LIVE_STATUS */

pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS: u32 = 0x88;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH3_RX_CIF_FIFO_FULL: u32 = 1 << 31;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH3_TX_CIF_FIFO_FULL: u32 = 1 << 30;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH2_RX_CIF_FIFO_FULL: u32 = 1 << 29;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH2_TX_CIF_FIFO_FULL: u32 = 1 << 28;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH1_RX_CIF_FIFO_FULL: u32 = 1 << 27;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH1_TX_CIF_FIFO_FULL: u32 = 1 << 26;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH0_RX_CIF_FIFO_FULL: u32 = 1 << 25;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH0_TX_CIF_FIFO_FULL: u32 = 1 << 24;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH3_RX_CIF_FIFO_EMPTY: u32 = 1 << 23;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH3_TX_CIF_FIFO_EMPTY: u32 = 1 << 22;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH2_RX_CIF_FIFO_EMPTY: u32 = 1 << 21;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH2_TX_CIF_FIFO_EMPTY: u32 = 1 << 20;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH1_RX_CIF_FIFO_EMPTY: u32 = 1 << 19;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH1_TX_CIF_FIFO_EMPTY: u32 = 1 << 18;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH0_RX_CIF_FIFO_EMPTY: u32 = 1 << 17;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH0_TX_CIF_FIFO_EMPTY: u32 = 1 << 16;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH3_RX_DMA_FIFO_FULL: u32 = 1 << 15;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH3_TX_DMA_FIFO_FULL: u32 = 1 << 14;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH2_RX_DMA_FIFO_FULL: u32 = 1 << 13;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH2_TX_DMA_FIFO_FULL: u32 = 1 << 12;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH1_RX_DMA_FIFO_FULL: u32 = 1 << 11;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH1_TX_DMA_FIFO_FULL: u32 = 1 << 10;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH0_RX_DMA_FIFO_FULL: u32 = 1 << 9;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH0_TX_DMA_FIFO_FULL: u32 = 1 << 8;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH3_RX_DMA_FIFO_EMPTY: u32 = 1 << 7;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH3_TX_DMA_FIFO_EMPTY: u32 = 1 << 6;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH2_RX_DMA_FIFO_EMPTY: u32 = 1 << 5;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH2_TX_DMA_FIFO_EMPTY: u32 = 1 << 4;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH1_RX_DMA_FIFO_EMPTY: u32 = 1 << 3;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH1_TX_DMA_FIFO_EMPTY: u32 = 1 << 2;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH0_RX_DMA_FIFO_EMPTY: u32 = 1 << 1;
pub const TEGRA30_AHUB_APBDMA_LIVE_STATUS_CH0_TX_DMA_FIFO_EMPTY: u32 = 1 << 0;

/* TEGRA30_AHUB_I2S_LIVE_STATUS */

pub const TEGRA30_AHUB_I2S_LIVE_STATUS: u32 = 0x8c;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S4_RX_FIFO_FULL: u32 = 1 << 29;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S4_TX_FIFO_FULL: u32 = 1 << 28;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S3_RX_FIFO_FULL: u32 = 1 << 27;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S3_TX_FIFO_FULL: u32 = 1 << 26;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S2_RX_FIFO_FULL: u32 = 1 << 25;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S2_TX_FIFO_FULL: u32 = 1 << 24;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S1_RX_FIFO_FULL: u32 = 1 << 23;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S1_TX_FIFO_FULL: u32 = 1 << 22;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S0_RX_FIFO_FULL: u32 = 1 << 21;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S0_TX_FIFO_FULL: u32 = 1 << 20;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S4_RX_FIFO_ENABLED: u32 = 1 << 19;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S4_TX_FIFO_ENABLED: u32 = 1 << 18;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S3_RX_FIFO_ENABLED: u32 = 1 << 17;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S3_TX_FIFO_ENABLED: u32 = 1 << 16;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S2_RX_FIFO_ENABLED: u32 = 1 << 15;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S2_TX_FIFO_ENABLED: u32 = 1 << 14;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S1_RX_FIFO_ENABLED: u32 = 1 << 13;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S1_TX_FIFO_ENABLED: u32 = 1 << 12;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S0_RX_FIFO_ENABLED: u32 = 1 << 11;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S0_TX_FIFO_ENABLED: u32 = 1 << 10;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S4_RX_FIFO_EMPTY: u32 = 1 << 9;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S4_TX_FIFO_EMPTY: u32 = 1 << 8;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S3_RX_FIFO_EMPTY: u32 = 1 << 7;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S3_TX_FIFO_EMPTY: u32 = 1 << 6;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S2_RX_FIFO_EMPTY: u32 = 1 << 5;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S2_TX_FIFO_EMPTY: u32 = 1 << 4;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S1_RX_FIFO_EMPTY: u32 = 1 << 3;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S1_TX_FIFO_EMPTY: u32 = 1 << 2;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S0_RX_FIFO_EMPTY: u32 = 1 << 1;
pub const TEGRA30_AHUB_I2S_LIVE_STATUS_I2S0_TX_FIFO_EMPTY: u32 = 1 << 0;

/* TEGRA30_AHUB_DAM0_LIVE_STATUS */

pub const TEGRA30_AHUB_DAM_LIVE_STATUS: u32 = 0x90;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_STRIDE: u32 = 0x8;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_COUNT: usize = 3;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_TX_ENABLED: u32 = 1 << 26;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_RX1_ENABLED: u32 = 1 << 25;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_RX0_ENABLED: u32 = 1 << 24;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_TXFIFO_FULL: u32 = 1 << 15;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_RX1FIFO_FULL: u32 = 1 << 9;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_RX0FIFO_FULL: u32 = 1 << 8;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_TXFIFO_EMPTY: u32 = 1 << 7;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_RX1FIFO_EMPTY: u32 = 1 << 1;
pub const TEGRA30_AHUB_DAM_LIVE_STATUS_RX0FIFO_EMPTY: u32 = 1 << 0;

/* TEGRA30_AHUB_SPDIF_LIVE_STATUS */

pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS: u32 = 0xa8;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_USER_TX_ENABLED: u32 = 1 << 11;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_USER_RX_ENABLED: u32 = 1 << 10;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_DATA_TX_ENABLED: u32 = 1 << 9;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_DATA_RX_ENABLED: u32 = 1 << 8;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_USER_TXFIFO_FULL: u32 = 1 << 7;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_USER_RXFIFO_FULL: u32 = 1 << 6;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_DATA_TXFIFO_FULL: u32 = 1 << 5;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_DATA_RXFIFO_FULL: u32 = 1 << 4;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_USER_TXFIFO_EMPTY: u32 = 1 << 3;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_USER_RXFIFO_EMPTY: u32 = 1 << 2;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_DATA_TXFIFO_EMPTY: u32 = 1 << 1;
pub const TEGRA30_AHUB_SPDIF_LIVE_STATUS_DATA_RXFIFO_EMPTY: u32 = 1 << 0;

/* TEGRA30_AHUB_I2S_INT_MASK */

pub const TEGRA30_AHUB_I2S_INT_MASK: u32 = 0xb0;

/* TEGRA30_AHUB_DAM_INT_MASK */

pub const TEGRA30_AHUB_DAM_INT_MASK: u32 = 0xb4;

/* TEGRA30_AHUB_SPDIF_INT_MASK */

pub const TEGRA30_AHUB_SPDIF_INT_MASK: u32 = 0xbc;

/* TEGRA30_AHUB_APBIF_INT_MASK */

pub const TEGRA30_AHUB_APBIF_INT_MASK: u32 = 0xc0;

/* TEGRA30_AHUB_I2S_INT_STATUS */

pub const TEGRA30_AHUB_I2S_INT_STATUS: u32 = 0xc8;

/* TEGRA30_AHUB_DAM_INT_STATUS */

pub const TEGRA30_AHUB_DAM_INT_STATUS: u32 = 0xcc;

/* TEGRA30_AHUB_SPDIF_INT_STATUS */

pub const TEGRA30_AHUB_SPDIF_INT_STATUS: u32 = 0xd4;

/* TEGRA30_AHUB_APBIF_INT_STATUS */

pub const TEGRA30_AHUB_APBIF_INT_STATUS: u32 = 0xd8;

/* TEGRA30_AHUB_I2S_INT_SOURCE */

pub const TEGRA30_AHUB_I2S_INT_SOURCE: u32 = 0xe0;

/* TEGRA30_AHUB_DAM_INT_SOURCE */

pub const TEGRA30_AHUB_DAM_INT_SOURCE: u32 = 0xe4;

/* TEGRA30_AHUB_SPDIF_INT_SOURCE */

pub const TEGRA30_AHUB_SPDIF_INT_SOURCE: u32 = 0xec;

/* TEGRA30_AHUB_APBIF_INT_SOURCE */

pub const TEGRA30_AHUB_APBIF_INT_SOURCE: u32 = 0xf0;

/* TEGRA30_AHUB_I2S_INT_SET */

pub const TEGRA30_AHUB_I2S_INT_SET: u32 = 0xf8;

/* TEGRA30_AHUB_DAM_INT_SET */

pub const TEGRA30_AHUB_DAM_INT_SET: u32 = 0xfc;

/* TEGRA30_AHUB_SPDIF_INT_SET */

pub const TEGRA30_AHUB_SPDIF_INT_SET: u32 = 0x100;

/* TEGRA30_AHUB_APBIF_INT_SET */

pub const TEGRA30_AHUB_APBIF_INT_SET: u32 = 0x104;

/* Registers within TEGRA30_AHUB_BASE */

pub const TEGRA30_AHUB_AUDIO_RX: u32 = 0x0;
pub const TEGRA30_AHUB_AUDIO_RX_STRIDE: u32 = 0x4;
pub const TEGRA30_AHUB_AUDIO_RX_COUNT: usize = 17;
/* This register repeats once for each entry in enum tegra30_ahub_rxcif */
/* The fields in this register are 1 bit per entry in tegra30_ahub_txcif */

/*
 * Terminology:
 * AHUB: Audio Hub; a cross-bar switch between the audio devices: DMA FIFOs,
 *       I2S controllers, SPDIF controllers, and DAMs.
 * XBAR: The core cross-bar component of the AHUB.
 * CIF:  Client Interface; the HW module connecting an audio device to the
 *       XBAR.
 * DAM:  Digital Audio Mixer: A HW module that mixes multiple audio streams,
 *       possibly including sample-rate conversion.
 *
 * Each TX CIF transmits data into the XBAR. Each RX CIF can receive audio
 * transmitted by a particular TX CIF.
 *
 * This driver is currently very simplistic; many HW features are not
 * exposed; DAMs are not supported, only 16-bit stereo audio is supported,
 * etc.
 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum tegra30_ahub_txcif {
    TEGRA30_AHUB_TXCIF_APBIF_TX0,
    TEGRA30_AHUB_TXCIF_APBIF_TX1,
    TEGRA30_AHUB_TXCIF_APBIF_TX2,
    TEGRA30_AHUB_TXCIF_APBIF_TX3,
    TEGRA30_AHUB_TXCIF_I2S0_TX0,
    TEGRA30_AHUB_TXCIF_I2S1_TX0,
    TEGRA30_AHUB_TXCIF_I2S2_TX0,
    TEGRA30_AHUB_TXCIF_I2S3_TX0,
    TEGRA30_AHUB_TXCIF_I2S4_TX0,
    TEGRA30_AHUB_TXCIF_DAM0_TX0,
    TEGRA30_AHUB_TXCIF_DAM1_TX0,
    TEGRA30_AHUB_TXCIF_DAM2_TX0,
    TEGRA30_AHUB_TXCIF_SPDIF_TX0,
    TEGRA30_AHUB_TXCIF_SPDIF_TX1,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum tegra30_ahub_rxcif {
    TEGRA30_AHUB_RXCIF_APBIF_RX0,
    TEGRA30_AHUB_RXCIF_APBIF_RX1,
    TEGRA30_AHUB_RXcIF_APBIF_RX2,
    TEGRA30_AHUB_RXCIF_APBIF_RX3,
    TEGRA30_AHUB_RXCIF_I2S0_RX0,
    TEGRA30_AHUB_RXCIF_I2S1_RX0,
    TEGRA30_AHUB_RXCIF_I2S2_RX0,
    TEGRA30_AHUB_RXCIF_I2S3_RX0,
    TEGRA30_AHUB_RXCIF_I2S4_RX0,
    TEGRA30_AHUB_RXCIF_DAM0_RX0,
    TEGRA30_AHUB_RXCIF_DAM0_RX1,
    TEGRA30_AHUB_RXCIF_DAM1_RX0,
    TEGRA30_AHUB_RXCIF_DAM2_RX1,
    TEGRA30_AHUB_RXCIF_DAM3_RX0,
    TEGRA30_AHUB_RXCIF_DAM3_RX1,
    TEGRA30_AHUB_RXCIF_SPDIF_RX0,
    TEGRA30_AHUB_RXCIF_SPDIF_RX1,
}

unsafe extern "C" {
    pub fn tegra30_ahub_allocate_rx_fifo(
        rxcif: *mut tegra30_ahub_rxcif,
        dmachan: *mut core::ffi::c_char,
        dmachan_len: core::ffi::c_int,
        fiforeg: *mut dma_addr_t,
    ) -> core::ffi::c_int;
    pub fn tegra30_ahub_enable_rx_fifo(rxcif: tegra30_ahub_rxcif) -> core::ffi::c_int;
    pub fn tegra30_ahub_disable_rx_fifo(rxcif: tegra30_ahub_rxcif) -> core::ffi::c_int;
    pub fn tegra30_ahub_free_rx_fifo(rxcif: tegra30_ahub_rxcif) -> core::ffi::c_int;

    pub fn tegra30_ahub_allocate_tx_fifo(
        txcif: *mut tegra30_ahub_txcif,
        dmachan: *mut core::ffi::c_char,
        dmachan_len: core::ffi::c_int,
        fiforeg: *mut dma_addr_t,
    ) -> core::ffi::c_int;
    pub fn tegra30_ahub_enable_tx_fifo(txcif: tegra30_ahub_txcif) -> core::ffi::c_int;
    pub fn tegra30_ahub_disable_tx_fifo(txcif: tegra30_ahub_txcif) -> core::ffi::c_int;
    pub fn tegra30_ahub_free_tx_fifo(txcif: tegra30_ahub_txcif) -> core::ffi::c_int;

    pub fn tegra30_ahub_set_rx_cif_source(
        rxcif: tegra30_ahub_rxcif,
        txcif: tegra30_ahub_txcif,
    ) -> core::ffi::c_int;
    pub fn tegra30_ahub_unset_rx_cif_source(rxcif: tegra30_ahub_rxcif) -> core::ffi::c_int;
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct tegra30_ahub_cif_conf {
    pub threshold: core::ffi::c_uint,
    pub audio_channels: core::ffi::c_uint,
    pub client_channels: core::ffi::c_uint,
    pub audio_bits: core::ffi::c_uint,
    pub client_bits: core::ffi::c_uint,
    pub expand: core::ffi::c_uint,
    pub stereo_conv: core::ffi::c_uint,
    pub replicate: core::ffi::c_uint,
    pub direction: core::ffi::c_uint,
    pub truncate: core::ffi::c_uint,
    pub mono_conv: core::ffi::c_uint,
}

unsafe extern "C" {
    pub fn tegra30_ahub_set_cif(
        regmap: *mut regmap,
        reg: core::ffi::c_uint,
        conf: *mut tegra30_ahub_cif_conf,
    );
    pub fn tegra124_ahub_set_cif(
        regmap: *mut regmap,
        reg: core::ffi::c_uint,
        conf: *mut tegra30_ahub_cif_conf,
    );
}

#[repr(C)]
pub struct tegra30_ahub_soc_data {
    pub num_resets: core::ffi::c_uint,
    pub set_audio_cif: Option<
        unsafe extern "C" fn(
            regmap: *mut regmap,
            reg: core::ffi::c_uint,
            conf: *mut tegra30_ahub_cif_conf,
        ),
    >,
    /*
     * FIXME: There are many more differences in HW, such as:
     * - More APBIF channels.
     * - Extra separate chunks of register address space to represent
     *   the extra APBIF channels.
     * - More units connected to the AHUB, so that tegra30_ahub_[rt]xcif
     *   need expansion, coupled with there being more defined bits in
     *   the AHUB routing registers.
     * However, the driver doesn't support those new features yet, so we
     * don't represent them here yet.
     */
}

#[repr(C)]
pub struct tegra30_ahub {
    pub soc_data: *const tegra30_ahub_soc_data,
    pub dev: *mut device,
    pub resets: [reset_control_bulk_data; 21],
    pub nresets: core::ffi::c_uint,
    pub clocks: [clk_bulk_data; 2],
    pub nclocks: core::ffi::c_uint,
    pub apbif_addr: resource_size_t,
    pub regmap_apbif: *mut regmap,
    pub regmap_ahub: *mut regmap,
    pub rx_usage: [core::ffi::c_ulong; 1],
    pub tx_usage: [core::ffi::c_ulong; 1],
}

// SOURCE-COMMIT: 08dbfad3f5040f5bdb6c529da20d6d4e81fefd72
