/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Automatically generated by rvgen kunit.
 * May need manual intervention for function prototypes that couldn't be
 * found (e.g. are in another file) or variables to be exported.
 */

// C conditional: IS_ENABLED(CONFIG_RV_MONITORS_KUNIT_TEST)
// The declarations below are enabled when CONFIG_RV_MONITORS_KUNIT_TEST is enabled.

extern "C" {
    pub static rv_sleep_ops: rv_sleep_ops;
}

#[repr(C)]
pub struct rv_sleep_ops {
    pub mon: rv_kunit_mon,
    pub handle_sched_waking:
        Option<unsafe extern "C" fn(data: *mut core::ffi::c_void, task: *mut task_struct)>,
    pub handle_sched_exit:
        Option<unsafe extern "C" fn(data: *mut core::ffi::c_void, is_switch: bool)>,
    pub handle_sched_set_state: Option<unsafe extern "C" fn(
        data: *mut core::ffi::c_void,
        task: *mut task_struct,
        state: core::ffi::c_int,
    )>,
    pub handle_contention_begin: Option<unsafe extern "C" fn(
        data: *mut core::ffi::c_void,
        lock: *mut core::ffi::c_void,
        flags: core::ffi::c_uint,
    )>,
    pub handle_contention_end: Option<unsafe extern "C" fn(
        data: *mut core::ffi::c_void,
        lock: *mut core::ffi::c_void,
        ret: core::ffi::c_int,
    )>,
    pub handle_sys_enter: Option<unsafe extern "C" fn(
        data: *mut core::ffi::c_void,
        regs: *mut pt_regs,
        id: core::ffi::c_long,
    )>,
    pub handle_sys_exit: Option<unsafe extern "C" fn(
        data: *mut core::ffi::c_void,
        regs: *mut pt_regs,
        ret: core::ffi::c_long,
    )>,
    pub handle_task_newtask: Option<unsafe extern "C" fn(
        data: *mut core::ffi::c_void,
        task: *mut task_struct,
        flags: u64,
    )>,
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
