/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2018 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/* Auto-generated register masks translated from dma_ch_0_masks.h. */

macro_rules! mask_const {
    ($shift:ident, $mask:ident, $shift_value:expr, $mask_value:expr) => {
        pub const $shift: u32 = $shift_value;
        pub const $mask: u32 = $mask_value;
    };
}

/* DMA_CH_0_CFG0 */
mask_const!(DMA_CH_0_CFG0_RD_MAX_OUTSTAND_SHIFT, DMA_CH_0_CFG0_RD_MAX_OUTSTAND_MASK, 0, 0x3FF);
mask_const!(DMA_CH_0_CFG0_WR_MAX_OUTSTAND_SHIFT, DMA_CH_0_CFG0_WR_MAX_OUTSTAND_MASK, 16, 0xFFF0000);
/* DMA_CH_0_CFG1 */
mask_const!(DMA_CH_0_CFG1_RD_BUF_MAX_SIZE_SHIFT, DMA_CH_0_CFG1_RD_BUF_MAX_SIZE_MASK, 0, 0x3FF);

/* Single-value register fields. */
mask_const!(DMA_CH_0_ERRMSG_ADDR_LO_VAL_SHIFT, DMA_CH_0_ERRMSG_ADDR_LO_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_ERRMSG_ADDR_HI_VAL_SHIFT, DMA_CH_0_ERRMSG_ADDR_HI_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_ERRMSG_WDATA_VAL_SHIFT, DMA_CH_0_ERRMSG_WDATA_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_RD_COMP_ADDR_LO_VAL_SHIFT, DMA_CH_0_RD_COMP_ADDR_LO_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_RD_COMP_ADDR_HI_VAL_SHIFT, DMA_CH_0_RD_COMP_ADDR_HI_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_RD_COMP_WDATA_VAL_SHIFT, DMA_CH_0_RD_COMP_WDATA_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_WR_COMP_ADDR_LO_VAL_SHIFT, DMA_CH_0_WR_COMP_ADDR_LO_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_WR_COMP_ADDR_HI_VAL_SHIFT, DMA_CH_0_WR_COMP_ADDR_HI_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_WR_COMP_WDATA_VAL_SHIFT, DMA_CH_0_WR_COMP_WDATA_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_LDMA_SRC_ADDR_LO_VAL_SHIFT, DMA_CH_0_LDMA_SRC_ADDR_LO_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_LDMA_SRC_ADDR_HI_VAL_SHIFT, DMA_CH_0_LDMA_SRC_ADDR_HI_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_LDMA_DST_ADDR_LO_VAL_SHIFT, DMA_CH_0_LDMA_DST_ADDR_LO_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_LDMA_DST_ADDR_HI_VAL_SHIFT, DMA_CH_0_LDMA_DST_ADDR_HI_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_LDMA_TSIZE_VAL_SHIFT, DMA_CH_0_LDMA_TSIZE_VAL_MASK, 0, 0xFFFFFFFF);

/* DMA_CH_0_COMIT_TRANSFER */
mask_const!(DMA_CH_0_COMIT_TRANSFER_PCI_UPS_WKORDR_SHIFT, DMA_CH_0_COMIT_TRANSFER_PCI_UPS_WKORDR_MASK, 0, 0x1);
mask_const!(DMA_CH_0_COMIT_TRANSFER_RD_COMP_EN_SHIFT, DMA_CH_0_COMIT_TRANSFER_RD_COMP_EN_MASK, 1, 0x2);
mask_const!(DMA_CH_0_COMIT_TRANSFER_WR_COMP_EN_SHIFT, DMA_CH_0_COMIT_TRANSFER_WR_COMP_EN_MASK, 2, 0x4);
mask_const!(DMA_CH_0_COMIT_TRANSFER_NOSNOOP_SHIFT, DMA_CH_0_COMIT_TRANSFER_NOSNOOP_MASK, 3, 0x8);
mask_const!(DMA_CH_0_COMIT_TRANSFER_SRC_ADDR_INC_DIS_SHIFT, DMA_CH_0_COMIT_TRANSFER_SRC_ADDR_INC_DIS_MASK, 4, 0x10);
mask_const!(DMA_CH_0_COMIT_TRANSFER_DST_ADDR_INC_DIS_SHIFT, DMA_CH_0_COMIT_TRANSFER_DST_ADDR_INC_DIS_MASK, 5, 0x20);
mask_const!(DMA_CH_0_COMIT_TRANSFER_MEM_SET_SHIFT, DMA_CH_0_COMIT_TRANSFER_MEM_SET_MASK, 6, 0x40);
mask_const!(DMA_CH_0_COMIT_TRANSFER_MOD_TENSOR_SHIFT, DMA_CH_0_COMIT_TRANSFER_MOD_TENSOR_MASK, 15, 0x8000);
mask_const!(DMA_CH_0_COMIT_TRANSFER_CTL_SHIFT, DMA_CH_0_COMIT_TRANSFER_CTL_MASK, 16, 0xFFFF0000);

/* DMA_CH_0_STS0 */
mask_const!(DMA_CH_0_STS0_DMA_BUSY_SHIFT, DMA_CH_0_STS0_DMA_BUSY_MASK, 0, 0x1);
mask_const!(DMA_CH_0_STS0_RD_STS_CTX_FULL_SHIFT, DMA_CH_0_STS0_RD_STS_CTX_FULL_MASK, 1, 0x2);
mask_const!(DMA_CH_0_STS0_WR_STS_CTX_FULL_SHIFT, DMA_CH_0_STS0_WR_STS_CTX_FULL_MASK, 2, 0x4);
mask_const!(DMA_CH_0_STS1_RD_STS_CTX_CNT_SHIFT, DMA_CH_0_STS1_RD_STS_CTX_CNT_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_STS2_WR_STS_CTX_CNT_SHIFT, DMA_CH_0_STS2_WR_STS_CTX_CNT_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_STS3_RD_STS_TRN_CNT_SHIFT, DMA_CH_0_STS3_RD_STS_TRN_CNT_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_STS4_WR_STS_TRN_CNT_SHIFT, DMA_CH_0_STS4_WR_STS_TRN_CNT_MASK, 0, 0xFFFFFFFF);

/* Status and rate-limit fields. */
mask_const!(DMA_CH_0_SRC_ADDR_LO_STS_VAL_SHIFT, DMA_CH_0_SRC_ADDR_LO_STS_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_SRC_ADDR_HI_STS_VAL_SHIFT, DMA_CH_0_SRC_ADDR_HI_STS_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_SRC_TSIZE_STS_VAL_SHIFT, DMA_CH_0_SRC_TSIZE_STS_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_DST_ADDR_LO_STS_VAL_SHIFT, DMA_CH_0_DST_ADDR_LO_STS_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_DST_ADDR_HI_STS_VAL_SHIFT, DMA_CH_0_DST_ADDR_HI_STS_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_DST_TSIZE_STS_VAL_SHIFT, DMA_CH_0_DST_TSIZE_STS_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_RD_RATE_LIM_EN_VAL_SHIFT, DMA_CH_0_RD_RATE_LIM_EN_VAL_MASK, 0, 0x1);
mask_const!(DMA_CH_0_RD_RATE_LIM_RST_TOKEN_VAL_SHIFT, DMA_CH_0_RD_RATE_LIM_RST_TOKEN_VAL_MASK, 0, 0xFFFF);
mask_const!(DMA_CH_0_RD_RATE_LIM_SAT_VAL_SHIFT, DMA_CH_0_RD_RATE_LIM_SAT_VAL_MASK, 0, 0xFFFF);
mask_const!(DMA_CH_0_RD_RATE_LIM_TOUT_VAL_SHIFT, DMA_CH_0_RD_RATE_LIM_TOUT_VAL_MASK, 0, 0x7FFFFFFF);
mask_const!(DMA_CH_0_WR_RATE_LIM_EN_VAL_SHIFT, DMA_CH_0_WR_RATE_LIM_EN_VAL_MASK, 0, 0x1);
mask_const!(DMA_CH_0_WR_RATE_LIM_RST_TOKEN_VAL_SHIFT, DMA_CH_0_WR_RATE_LIM_RST_TOKEN_VAL_MASK, 0, 0xFFFF);
mask_const!(DMA_CH_0_WR_RATE_LIM_SAT_VAL_SHIFT, DMA_CH_0_WR_RATE_LIM_SAT_VAL_MASK, 0, 0xFFFF);
mask_const!(DMA_CH_0_WR_RATE_LIM_TOUT_VAL_SHIFT, DMA_CH_0_WR_RATE_LIM_TOUT_VAL_MASK, 0, 0x7FFFFFFF);
mask_const!(DMA_CH_0_CFG2_FORCE_WORD_SHIFT, DMA_CH_0_CFG2_FORCE_WORD_MASK, 0, 0x1);
mask_const!(DMA_CH_0_TDMA_CTL_DTYPE_SHIFT, DMA_CH_0_TDMA_CTL_DTYPE_MASK, 0, 0x7);

/* DMA_CH_0_TDMA source and destination fields (all are 32-bit values). */
mask_const!(DMA_CH_0_TDMA_SRC_BASE_ADDR_LO_VAL_SHIFT, DMA_CH_0_TDMA_SRC_BASE_ADDR_LO_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_BASE_ADDR_HI_VAL_SHIFT, DMA_CH_0_TDMA_SRC_BASE_ADDR_HI_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_BASE_ADDR_LO_VAL_SHIFT, DMA_CH_0_TDMA_DST_BASE_ADDR_LO_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_BASE_ADDR_HI_VAL_SHIFT, DMA_CH_0_TDMA_DST_BASE_ADDR_HI_VAL_MASK, 0, 0xFFFFFFFF);

/* The preprocessor-generated ROI fields are emitted explicitly below. */
mask_const!(DMA_CH_0_TDMA_SRC_ROI_BASE_0_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_BASE_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_SIZE_0_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_SIZE_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_0_VAL_SHIFT, DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_START_OFFSET_0_VAL_SHIFT, DMA_CH_0_TDMA_SRC_START_OFFSET_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_STRIDE_0_VAL_SHIFT, DMA_CH_0_TDMA_SRC_STRIDE_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_BASE_1_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_BASE_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_SIZE_1_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_SIZE_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_1_VAL_SHIFT, DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_START_OFFSET_1_VAL_SHIFT, DMA_CH_0_TDMA_SRC_START_OFFSET_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_STRIDE_1_VAL_SHIFT, DMA_CH_0_TDMA_SRC_STRIDE_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_BASE_2_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_BASE_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_SIZE_2_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_SIZE_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_2_VAL_SHIFT, DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_START_OFFSET_2_VAL_SHIFT, DMA_CH_0_TDMA_SRC_START_OFFSET_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_STRIDE_2_VAL_SHIFT, DMA_CH_0_TDMA_SRC_STRIDE_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_BASE_3_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_BASE_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_SIZE_3_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_SIZE_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_3_VAL_SHIFT, DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_START_OFFSET_3_VAL_SHIFT, DMA_CH_0_TDMA_SRC_START_OFFSET_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_STRIDE_3_VAL_SHIFT, DMA_CH_0_TDMA_SRC_STRIDE_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_BASE_4_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_BASE_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_ROI_SIZE_4_VAL_SHIFT, DMA_CH_0_TDMA_SRC_ROI_SIZE_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_4_VAL_SHIFT, DMA_CH_0_TDMA_SRC_VALID_ELEMENTS_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_START_OFFSET_4_VAL_SHIFT, DMA_CH_0_TDMA_SRC_START_OFFSET_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_SRC_STRIDE_4_VAL_SHIFT, DMA_CH_0_TDMA_SRC_STRIDE_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_BASE_0_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_BASE_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_SIZE_0_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_SIZE_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_VALID_ELEMENTS_0_VAL_SHIFT, DMA_CH_0_TDMA_DST_VALID_ELEMENTS_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_START_OFFSET_0_VAL_SHIFT, DMA_CH_0_TDMA_DST_START_OFFSET_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_STRIDE_0_VAL_SHIFT, DMA_CH_0_TDMA_DST_STRIDE_0_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_BASE_1_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_BASE_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_SIZE_1_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_SIZE_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_VALID_ELEMENTS_1_VAL_SHIFT, DMA_CH_0_TDMA_DST_VALID_ELEMENTS_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_START_OFFSET_1_VAL_SHIFT, DMA_CH_0_TDMA_DST_START_OFFSET_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_STRIDE_1_VAL_SHIFT, DMA_CH_0_TDMA_DST_STRIDE_1_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_BASE_2_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_BASE_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_SIZE_2_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_SIZE_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_VALID_ELEMENTS_2_VAL_SHIFT, DMA_CH_0_TDMA_DST_VALID_ELEMENTS_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_START_OFFSET_2_VAL_SHIFT, DMA_CH_0_TDMA_DST_START_OFFSET_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_STRIDE_2_VAL_SHIFT, DMA_CH_0_TDMA_DST_STRIDE_2_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_BASE_3_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_BASE_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_SIZE_3_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_SIZE_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_VALID_ELEMENTS_3_VAL_SHIFT, DMA_CH_0_TDMA_DST_VALID_ELEMENTS_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_START_OFFSET_3_VAL_SHIFT, DMA_CH_0_TDMA_DST_START_OFFSET_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_STRIDE_3_VAL_SHIFT, DMA_CH_0_TDMA_DST_STRIDE_3_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_BASE_4_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_BASE_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_ROI_SIZE_4_VAL_SHIFT, DMA_CH_0_TDMA_DST_ROI_SIZE_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_VALID_ELEMENTS_4_VAL_SHIFT, DMA_CH_0_TDMA_DST_VALID_ELEMENTS_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_START_OFFSET_4_VAL_SHIFT, DMA_CH_0_TDMA_DST_START_OFFSET_4_VAL_MASK, 0, 0xFFFFFFFF);
mask_const!(DMA_CH_0_TDMA_DST_STRIDE_4_VAL_SHIFT, DMA_CH_0_TDMA_DST_STRIDE_4_VAL_MASK, 0, 0xFFFFFFFF);

/* DMA_CH_0_MEM_INIT_BUSY */
mask_const!(DMA_CH_0_MEM_INIT_BUSY_SBC_DATA_SHIFT, DMA_CH_0_MEM_INIT_BUSY_SBC_DATA_MASK, 0, 0xFF);
mask_const!(DMA_CH_0_MEM_INIT_BUSY_SBC_MD_SHIFT, DMA_CH_0_MEM_INIT_BUSY_SBC_MD_MASK, 8, 0x100);

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
