/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2018 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

/*
 *****************************************
 *   DMA_MACRO (Prototype: DMA_MACRO)
 *****************************************
 */

/* DMA_MACRO_LBW_RANGE_HIT_BLOCK */
pub const DMA_MACRO_LBW_RANGE_HIT_BLOCK_R_SHIFT: u32 = 0;
pub const DMA_MACRO_LBW_RANGE_HIT_BLOCK_R_MASK: u32 = 0xFFFF;

/* DMA_MACRO_LBW_RANGE_MASK */
pub const DMA_MACRO_LBW_RANGE_MASK_R_SHIFT: u32 = 0;
pub const DMA_MACRO_LBW_RANGE_MASK_R_MASK: u32 = 0x3FFFFFF;

/* DMA_MACRO_LBW_RANGE_BASE */
pub const DMA_MACRO_LBW_RANGE_BASE_R_SHIFT: u32 = 0;
pub const DMA_MACRO_LBW_RANGE_BASE_R_MASK: u32 = 0x3FFFFFF;

/* DMA_MACRO_HBW_RANGE_HIT_BLOCK */
pub const DMA_MACRO_HBW_RANGE_HIT_BLOCK_R_SHIFT: u32 = 0;
pub const DMA_MACRO_HBW_RANGE_HIT_BLOCK_R_MASK: u32 = 0xFF;

/* DMA_MACRO_HBW_RANGE_MASK_49_32 */
pub const DMA_MACRO_HBW_RANGE_MASK_49_32_R_SHIFT: u32 = 0;
pub const DMA_MACRO_HBW_RANGE_MASK_49_32_R_MASK: u32 = 0x3FFFF;

/* DMA_MACRO_HBW_RANGE_MASK_31_0 */
pub const DMA_MACRO_HBW_RANGE_MASK_31_0_R_SHIFT: u32 = 0;
pub const DMA_MACRO_HBW_RANGE_MASK_31_0_R_MASK: u32 = 0xFFFFFFFF;

/* DMA_MACRO_HBW_RANGE_BASE_49_32 */
pub const DMA_MACRO_HBW_RANGE_BASE_49_32_R_SHIFT: u32 = 0;
pub const DMA_MACRO_HBW_RANGE_BASE_49_32_R_MASK: u32 = 0x3FFFF;

/* DMA_MACRO_HBW_RANGE_BASE_31_0 */
pub const DMA_MACRO_HBW_RANGE_BASE_31_0_R_SHIFT: u32 = 0;
pub const DMA_MACRO_HBW_RANGE_BASE_31_0_R_MASK: u32 = 0xFFFFFFFF;

/* DMA_MACRO_WRITE_EN */
pub const DMA_MACRO_WRITE_EN_R_SHIFT: u32 = 0;
pub const DMA_MACRO_WRITE_EN_R_MASK: u32 = 0x1;

/* DMA_MACRO_WRITE_CREDIT */
pub const DMA_MACRO_WRITE_CREDIT_R_SHIFT: u32 = 0;
pub const DMA_MACRO_WRITE_CREDIT_R_MASK: u32 = 0x3FF;

/* DMA_MACRO_READ_EN */
pub const DMA_MACRO_READ_EN_R_SHIFT: u32 = 0;
pub const DMA_MACRO_READ_EN_R_MASK: u32 = 0x1;

/* DMA_MACRO_READ_CREDIT */
pub const DMA_MACRO_READ_CREDIT_R_SHIFT: u32 = 0;
pub const DMA_MACRO_READ_CREDIT_R_MASK: u32 = 0x3FF;

/* DMA_MACRO_SRAM_BUSY */

/* DMA_MACRO_RAZWI_LBW_WT_VLD */
pub const DMA_MACRO_RAZWI_LBW_WT_VLD_R_SHIFT: u32 = 0;
pub const DMA_MACRO_RAZWI_LBW_WT_VLD_R_MASK: u32 = 0x1;

/* DMA_MACRO_RAZWI_LBW_WT_ID */
pub const DMA_MACRO_RAZWI_LBW_WT_ID_R_SHIFT: u32 = 0;
pub const DMA_MACRO_RAZWI_LBW_WT_ID_R_MASK: u32 = 0x7FFF;

/* DMA_MACRO_RAZWI_LBW_RD_VLD */
pub const DMA_MACRO_RAZWI_LBW_RD_VLD_R_SHIFT: u32 = 0;
pub const DMA_MACRO_RAZWI_LBW_RD_VLD_R_MASK: u32 = 0x1;

/* DMA_MACRO_RAZWI_LBW_RD_ID */
pub const DMA_MACRO_RAZWI_LBW_RD_ID_R_SHIFT: u32 = 0;
pub const DMA_MACRO_RAZWI_LBW_RD_ID_R_MASK: u32 = 0x7FFF;

/* DMA_MACRO_RAZWI_HBW_WT_VLD */
pub const DMA_MACRO_RAZWI_HBW_WT_VLD_R_SHIFT: u32 = 0;
pub const DMA_MACRO_RAZWI_HBW_WT_VLD_R_MASK: u32 = 0x1;

/* DMA_MACRO_RAZWI_HBW_WT_ID */
pub const DMA_MACRO_RAZWI_HBW_WT_ID_R_SHIFT: u32 = 0;
pub const DMA_MACRO_RAZWI_HBW_WT_ID_R_MASK: u32 = 0x1FFFFFFF;

/* DMA_MACRO_RAZWI_HBW_RD_VLD */
pub const DMA_MACRO_RAZWI_HBW_RD_VLD_R_SHIFT: u32 = 0;
pub const DMA_MACRO_RAZWI_HBW_RD_VLD_R_MASK: u32 = 0x1;

/* DMA_MACRO_RAZWI_HBW_RD_ID */
pub const DMA_MACRO_RAZWI_HBW_RD_ID_R_SHIFT: u32 = 0;
pub const DMA_MACRO_RAZWI_HBW_RD_ID_R_MASK: u32 = 0x1FFFFFFF;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
