/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2018 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

/*
 *****************************************
 *   TPC0_NRTR (Prototype: IF_NRTR)
 *****************************************
 */

/* TPC0_NRTR_HBW_MAX_CRED */
pub const TPC0_NRTR_HBW_MAX_CRED_WR_RQ_SHIFT: u32 = 0;
pub const TPC0_NRTR_HBW_MAX_CRED_WR_RQ_MASK: u32 = 0x3F;
pub const TPC0_NRTR_HBW_MAX_CRED_WR_RS_SHIFT: u32 = 8;
pub const TPC0_NRTR_HBW_MAX_CRED_WR_RS_MASK: u32 = 0x3F00;
pub const TPC0_NRTR_HBW_MAX_CRED_RD_RQ_SHIFT: u32 = 16;
pub const TPC0_NRTR_HBW_MAX_CRED_RD_RQ_MASK: u32 = 0x3F0000;
pub const TPC0_NRTR_HBW_MAX_CRED_RD_RS_SHIFT: u32 = 24;
pub const TPC0_NRTR_HBW_MAX_CRED_RD_RS_MASK: u32 = 0x3F000000;

/* TPC0_NRTR_LBW_MAX_CRED */
pub const TPC0_NRTR_LBW_MAX_CRED_WR_RQ_SHIFT: u32 = 0;
pub const TPC0_NRTR_LBW_MAX_CRED_WR_RQ_MASK: u32 = 0x3F;
pub const TPC0_NRTR_LBW_MAX_CRED_WR_RS_SHIFT: u32 = 8;
pub const TPC0_NRTR_LBW_MAX_CRED_WR_RS_MASK: u32 = 0x3F00;
pub const TPC0_NRTR_LBW_MAX_CRED_RD_RQ_SHIFT: u32 = 16;
pub const TPC0_NRTR_LBW_MAX_CRED_RD_RQ_MASK: u32 = 0x3F0000;
pub const TPC0_NRTR_LBW_MAX_CRED_RD_RS_SHIFT: u32 = 24;
pub const TPC0_NRTR_LBW_MAX_CRED_RD_RS_MASK: u32 = 0x3F000000;

/* TPC0_NRTR_DBG_E_ARB */
pub const TPC0_NRTR_DBG_E_ARB_W_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_E_ARB_W_MASK: u32 = 0x7;
pub const TPC0_NRTR_DBG_E_ARB_S_SHIFT: u32 = 8;
pub const TPC0_NRTR_DBG_E_ARB_S_MASK: u32 = 0x700;
pub const TPC0_NRTR_DBG_E_ARB_N_SHIFT: u32 = 16;
pub const TPC0_NRTR_DBG_E_ARB_N_MASK: u32 = 0x70000;
pub const TPC0_NRTR_DBG_E_ARB_L_SHIFT: u32 = 24;
pub const TPC0_NRTR_DBG_E_ARB_L_MASK: u32 = 0x7000000;

/* TPC0_NRTR_DBG_W_ARB */
pub const TPC0_NRTR_DBG_W_ARB_E_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_W_ARB_E_MASK: u32 = 0x7;
pub const TPC0_NRTR_DBG_W_ARB_S_SHIFT: u32 = 8;
pub const TPC0_NRTR_DBG_W_ARB_S_MASK: u32 = 0x700;
pub const TPC0_NRTR_DBG_W_ARB_N_SHIFT: u32 = 16;
pub const TPC0_NRTR_DBG_W_ARB_N_MASK: u32 = 0x70000;
pub const TPC0_NRTR_DBG_W_ARB_L_SHIFT: u32 = 24;
pub const TPC0_NRTR_DBG_W_ARB_L_MASK: u32 = 0x7000000;

/* TPC0_NRTR_DBG_N_ARB */
pub const TPC0_NRTR_DBG_N_ARB_W_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_N_ARB_W_MASK: u32 = 0x7;
pub const TPC0_NRTR_DBG_N_ARB_E_SHIFT: u32 = 8;
pub const TPC0_NRTR_DBG_N_ARB_E_MASK: u32 = 0x700;
pub const TPC0_NRTR_DBG_N_ARB_S_SHIFT: u32 = 16;
pub const TPC0_NRTR_DBG_N_ARB_S_MASK: u32 = 0x70000;
pub const TPC0_NRTR_DBG_N_ARB_L_SHIFT: u32 = 24;
pub const TPC0_NRTR_DBG_N_ARB_L_MASK: u32 = 0x7000000;

/* TPC0_NRTR_DBG_S_ARB */
pub const TPC0_NRTR_DBG_S_ARB_W_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_S_ARB_W_MASK: u32 = 0x7;
pub const TPC0_NRTR_DBG_S_ARB_E_SHIFT: u32 = 8;
pub const TPC0_NRTR_DBG_S_ARB_E_MASK: u32 = 0x700;
pub const TPC0_NRTR_DBG_S_ARB_N_SHIFT: u32 = 16;
pub const TPC0_NRTR_DBG_S_ARB_N_MASK: u32 = 0x70000;
pub const TPC0_NRTR_DBG_S_ARB_L_SHIFT: u32 = 24;
pub const TPC0_NRTR_DBG_S_ARB_L_MASK: u32 = 0x7000000;

/* TPC0_NRTR_DBG_L_ARB */
pub const TPC0_NRTR_DBG_L_ARB_W_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_L_ARB_W_MASK: u32 = 0x7;
pub const TPC0_NRTR_DBG_L_ARB_E_SHIFT: u32 = 8;
pub const TPC0_NRTR_DBG_L_ARB_E_MASK: u32 = 0x700;
pub const TPC0_NRTR_DBG_L_ARB_S_SHIFT: u32 = 16;
pub const TPC0_NRTR_DBG_L_ARB_S_MASK: u32 = 0x70000;
pub const TPC0_NRTR_DBG_L_ARB_N_SHIFT: u32 = 24;
pub const TPC0_NRTR_DBG_L_ARB_N_MASK: u32 = 0x7000000;

/* TPC0_NRTR_DBG_*_ARB_MAX */
pub const TPC0_NRTR_DBG_E_ARB_MAX_CREDIT_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_E_ARB_MAX_CREDIT_MASK: u32 = 0x3F;
pub const TPC0_NRTR_DBG_W_ARB_MAX_CREDIT_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_W_ARB_MAX_CREDIT_MASK: u32 = 0x3F;
pub const TPC0_NRTR_DBG_N_ARB_MAX_CREDIT_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_N_ARB_MAX_CREDIT_MASK: u32 = 0x3F;
pub const TPC0_NRTR_DBG_S_ARB_MAX_CREDIT_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_S_ARB_MAX_CREDIT_MASK: u32 = 0x3F;
pub const TPC0_NRTR_DBG_L_ARB_MAX_CREDIT_SHIFT: u32 = 0;
pub const TPC0_NRTR_DBG_L_ARB_MAX_CREDIT_MASK: u32 = 0x3F;

/* TPC0_NRTR_SPLIT_COEF */
pub const TPC0_NRTR_SPLIT_COEF_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_SPLIT_COEF_VAL_MASK: u32 = 0xFFFF;

/* TPC0_NRTR_SPLIT_CFG */
pub const TPC0_NRTR_SPLIT_CFG_FORCE_WAK_ORDER_SHIFT: u32 = 0;
pub const TPC0_NRTR_SPLIT_CFG_FORCE_WAK_ORDER_MASK: u32 = 0x1;
pub const TPC0_NRTR_SPLIT_CFG_FORCE_STRONG_ORDER_SHIFT: u32 = 1;
pub const TPC0_NRTR_SPLIT_CFG_FORCE_STRONG_ORDER_MASK: u32 = 0x2;
pub const TPC0_NRTR_SPLIT_CFG_DEFAULT_MESH_SHIFT: u32 = 2;
pub const TPC0_NRTR_SPLIT_CFG_DEFAULT_MESH_MASK: u32 = 0xC;
pub const TPC0_NRTR_SPLIT_CFG_RD_RATE_LIM_EN_SHIFT: u32 = 4;
pub const TPC0_NRTR_SPLIT_CFG_RD_RATE_LIM_EN_MASK: u32 = 0x10;
pub const TPC0_NRTR_SPLIT_CFG_WR_RATE_LIM_EN_SHIFT: u32 = 5;
pub const TPC0_NRTR_SPLIT_CFG_WR_RATE_LIM_EN_MASK: u32 = 0x20;
pub const TPC0_NRTR_SPLIT_CFG_B2B_OPT_SHIFT: u32 = 6;
pub const TPC0_NRTR_SPLIT_CFG_B2B_OPT_MASK: u32 = 0x1C0;

/* TPC0_NRTR_SPLIT_RD_SAT */
pub const TPC0_NRTR_SPLIT_RD_SAT_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_SPLIT_RD_SAT_VAL_MASK: u32 = 0xFFFF;
/* TPC0_NRTR_SPLIT_RD_RST_TOKEN */
pub const TPC0_NRTR_SPLIT_RD_RST_TOKEN_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_SPLIT_RD_RST_TOKEN_VAL_MASK: u32 = 0xFFFF;
/* TPC0_NRTR_SPLIT_RD_TIMEOUT */
pub const TPC0_NRTR_SPLIT_RD_TIMEOUT_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_SPLIT_RD_TIMEOUT_VAL_MASK: u32 = 0xFFFFFFFF;
/* TPC0_NRTR_SPLIT_WR_SAT */
pub const TPC0_NRTR_SPLIT_WR_SAT_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_SPLIT_WR_SAT_VAL_MASK: u32 = 0xFFFF;
/* TPC0_NRTR_WPLIT_WR_TST_TOLEN */
pub const TPC0_NRTR_WPLIT_WR_TST_TOLEN_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_WPLIT_WR_TST_TOLEN_VAL_MASK: u32 = 0xFFFF;
/* TPC0_NRTR_SPLIT_WR_TIMEOUT */
pub const TPC0_NRTR_SPLIT_WR_TIMEOUT_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_SPLIT_WR_TIMEOUT_VAL_MASK: u32 = 0xFFFFFFFF;

/* TPC0_NRTR_HBW_RANGE_HIT */
pub const TPC0_NRTR_HBW_RANGE_HIT_IND_SHIFT: u32 = 0;
pub const TPC0_NRTR_HBW_RANGE_HIT_IND_MASK: u32 = 0xFF;
/* TPC0_NRTR_HBW_RANGE_MASK_L */
pub const TPC0_NRTR_HBW_RANGE_MASK_L_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_HBW_RANGE_MASK_L_VAL_MASK: u32 = 0xFFFFFFFF;
/* TPC0_NRTR_HBW_RANGE_MASK_H */
pub const TPC0_NRTR_HBW_RANGE_MASK_H_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_HBW_RANGE_MASK_H_VAL_MASK: u32 = 0x3FFFF;
/* TPC0_NRTR_HBW_RANGE_BASE_L */
pub const TPC0_NRTR_HBW_RANGE_BASE_L_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_HBW_RANGE_BASE_L_VAL_MASK: u32 = 0xFFFFFFFF;
/* TPC0_NRTR_HBW_RANGE_BASE_H */
pub const TPC0_NRTR_HBW_RANGE_BASE_H_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_HBW_RANGE_BASE_H_VAL_MASK: u32 = 0x3FFFF;
/* TPC0_NRTR_LBW_RANGE_HIT */
pub const TPC0_NRTR_LBW_RANGE_HIT_IND_SHIFT: u32 = 0;
pub const TPC0_NRTR_LBW_RANGE_HIT_IND_MASK: u32 = 0xFFFF;
/* TPC0_NRTR_LBW_RANGE_MASK */
pub const TPC0_NRTR_LBW_RANGE_MASK_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_LBW_RANGE_MASK_VAL_MASK: u32 = 0x3FFFFFF;
/* TPC0_NRTR_LBW_RANGE_BASE */
pub const TPC0_NRTR_LBW_RANGE_BASE_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_LBW_RANGE_BASE_VAL_MASK: u32 = 0x3FFFFFF;

/* TPC0_NRTR_RGLTR */
pub const TPC0_NRTR_RGLTR_WR_EN_SHIFT: u32 = 0;
pub const TPC0_NRTR_RGLTR_WR_EN_MASK: u32 = 0x1;
pub const TPC0_NRTR_RGLTR_RD_EN_SHIFT: u32 = 4;
pub const TPC0_NRTR_RGLTR_RD_EN_MASK: u32 = 0x10;
/* TPC0_NRTR_RGLTR_WR_RESULT */
pub const TPC0_NRTR_RGLTR_WR_RESULT_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_RGLTR_WR_RESULT_VAL_MASK: u32 = 0xFF;
/* TPC0_NRTR_RGLTR_RD_RESULT */
pub const TPC0_NRTR_RGLTR_RD_RESULT_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_RGLTR_RD_RESULT_VAL_MASK: u32 = 0xFF;
/* TPC0_NRTR_SCRAMB_EN */
pub const TPC0_NRTR_SCRAMB_EN_VAL_SHIFT: u32 = 0;
pub const TPC0_NRTR_SCRAMB_EN_VAL_MASK: u32 = 0x1;
/* TPC0_NRTR_NON_LIN_SCRAMB */
pub const TPC0_NRTR_NON_LIN_SCRAMB_EN_SHIFT: u32 = 0;
pub const TPC0_NRTR_NON_LIN_SCRAMB_EN_MASK: u32 = 0x1;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
