// SPDX-License-Identifier: MIT
//
// Copyright 2024 Advanced Micro Devices, Inc.

// C dependencies: hw_translate_dcn401.h, dm_services.h, gpio_types.h,
// hw_translate.h, dcn_4_1_0_offset.h, and dcn_4_1_0_sh_mask.h.

const DCN_BASE_INST0_SEG2: u32 = 0x0000_34C0;

// Register-list expansion macros from the hardware object headers.
macro_rules! BASE_INNER {
    ($seg:ident) => { DCN_BASE__INST0_SEG_$seg };
}
macro_rules! BASE {
    ($seg:ident) => { BASE_INNER!($seg) };
}
macro_rules! REG {
    ($reg_name:ident) => { BASE!(reg_$reg_name##_BASE_IDX) + reg_$reg_name };
}

static GPIO_OFFSETS: [struct_gpio_id_offset_entry; 15] = [
    GPIO_MASK_ENTRY!(DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICA_A_MASK, GPIO_ID_GENERIC, GPIO_GENERIC_A),
    GPIO_MASK_ENTRY!(DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICB_A_MASK, GPIO_ID_GENERIC, GPIO_GENERIC_B),
    GPIO_MASK_ENTRY!(DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICC_A_MASK, GPIO_ID_GENERIC, GPIO_GENERIC_C),
    GPIO_MASK_ENTRY!(DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICD_A_MASK, GPIO_ID_GENERIC, GPIO_GENERIC_D),
    GPIO_MASK_ENTRY!(DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICE_A_MASK, GPIO_ID_GENERIC, GPIO_GENERIC_E),
    GPIO_MASK_ENTRY!(DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICF_A_MASK, GPIO_ID_GENERIC, GPIO_GENERIC_F),
    GPIO_MASK_ENTRY!(DC_GPIO_HPD_A, DC_GPIO_HPD_A__DC_GPIO_HPD1_A_MASK, GPIO_ID_HPD, GPIO_HPD_1),
    GPIO_MASK_ENTRY!(DC_GPIO_HPD_A, DC_GPIO_HPD_A__DC_GPIO_HPD2_A_MASK, GPIO_ID_HPD, GPIO_HPD_2),
    GPIO_MASK_ENTRY!(DC_GPIO_HPD_A, DC_GPIO_HPD_A__DC_GPIO_HPD3_A_MASK, GPIO_ID_HPD, GPIO_HPD_3),
    GPIO_MASK_ENTRY!(DC_GPIO_HPD_A, DC_GPIO_HPD_A__DC_GPIO_HPD4_A_MASK, GPIO_ID_HPD, GPIO_HPD_4),
    GPIO_MASK_ENTRY!(DC_GPIO_HPD_A, DC_GPIO_HPD_A__DC_GPIO_HPD5_A_MASK, GPIO_ID_HPD, GPIO_HPD_5),
    GPIO_MASK_ENTRY!(DC_GPIO_GENLK_A, DC_GPIO_GENLK_A__DC_GPIO_GENLK_CLK_A_MASK, GPIO_ID_GSL, GPIO_GSL_GENLOCK_CLOCK),
    GPIO_MASK_ENTRY!(DC_GPIO_GENLK_A, DC_GPIO_GENLK_A__DC_GPIO_GENLK_VSYNC_A_MASK, GPIO_ID_GSL, GPIO_GSL_GENLOCK_VSYNC),
    GPIO_MASK_ENTRY!(DC_GPIO_GENLK_A, DC_GPIO_GENLK_A__DC_GPIO_SWAPLOCK_A_A_MASK, GPIO_ID_GSL, GPIO_GSL_SWAPLOCK_A),
    GPIO_MASK_ENTRY!(DC_GPIO_GENLK_A, DC_GPIO_GENLK_A__DC_GPIO_SWAPLOCK_B_A_MASK, GPIO_ID_GSL, GPIO_GSL_SWAPLOCK_B),
];

static DDC_OFFSET_MAP: [struct_gpio_ddc_offset_entry; 5] = [
    { offset: REG!(DC_GPIO_DDC1_A), line: GPIO_DDC_LINE_DDC1 },
    { offset: REG!(DC_GPIO_DDC2_A), line: GPIO_DDC_LINE_DDC2 },
    { offset: REG!(DC_GPIO_DDC3_A), line: GPIO_DDC_LINE_DDC3 },
    { offset: REG!(DC_GPIO_DDC4_A), line: GPIO_DDC_LINE_DDC4 },
    { offset: REG!(DC_GPIO_DDCVGA_A), line: GPIO_DDC_LINE_DDC_VGA },
];

// GSL is intentionally omitted: id_to_offset() for GSL is not implemented on this ASIC.
static GPIO_PINS: [struct_gpio_pin_entry; 16] = [
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_DATA, GPIO_DDC_LINE_DDC1, DC_GPIO_DDC1_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1DATA_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_DATA, GPIO_DDC_LINE_DDC2, DC_GPIO_DDC2_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1DATA_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_DATA, GPIO_DDC_LINE_DDC3, DC_GPIO_DDC3_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1DATA_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_DATA, GPIO_DDC_LINE_DDC4, DC_GPIO_DDC4_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1DATA_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_DATA, GPIO_DDC_LINE_DDC_VGA, DC_GPIO_DDCVGA_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1DATA_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_CLOCK, GPIO_DDC_LINE_DDC1, DC_GPIO_DDC1_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1CLK_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_CLOCK, GPIO_DDC_LINE_DDC2, DC_GPIO_DDC2_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1CLK_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_CLOCK, GPIO_DDC_LINE_DDC3, DC_GPIO_DDC3_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1CLK_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_CLOCK, GPIO_DDC_LINE_DDC4, DC_GPIO_DDC4_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1CLK_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_DDC_CLOCK, GPIO_DDC_LINE_DDC_VGA, DC_GPIO_DDCVGA_A, DC_GPIO_DDC1_A__DC_GPIO_DDC1CLK_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_GENERIC, GPIO_GENERIC_A, DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICA_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_GENERIC, GPIO_GENERIC_B, DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICB_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_GENERIC, GPIO_GENERIC_C, DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICC_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_GENERIC, GPIO_GENERIC_D, DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICD_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_GENERIC, GPIO_GENERIC_E, DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICE_A_MASK),
    GPIO_PIN_ENTRY!(GPIO_ID_GENERIC, GPIO_GENERIC_F, DC_GPIO_GENERIC_A, DC_GPIO_GENERIC_A__DC_GPIO_GENERICF_A_MASK),
];

unsafe fn offset_to_id(offset: u32, mask: u32, id: *mut enum_gpio_id, en: *mut u32) -> bool {
    if dal_hw_translate_gpio_ddc_offset_to_id(DDC_OFFSET_MAP.as_ptr(), DDC_OFFSET_MAP.len(), offset, en) {
        return true;
    }
    if dal_hw_translate_gpio_offset_to_id(GPIO_OFFSETS.as_ptr(), GPIO_OFFSETS.len(), offset, mask, id, en) {
        return true;
    }
    ASSERT_CRITICAL!(false);
    false
}

unsafe fn id_to_offset(id: enum_gpio_id, en: u32, info: *mut struct_gpio_pin_info) -> bool {
    if dal_hw_translate_id_to_offset(GPIO_PINS.as_ptr(), GPIO_PINS.len(), id, en, info) {
        return true;
    }
    ASSERT_CRITICAL!(false);
    false
}

static FUNCS: struct_hw_translate_funcs = struct_hw_translate_funcs {
    offset_to_id: Some(offset_to_id),
    id_to_offset: Some(id_to_offset),
};

pub unsafe fn dal_hw_translate_dcn401_init(tr: *mut struct_hw_translate) {
    (*tr).funcs = &FUNCS;
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
