/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Automatically generated by rvgen kunit.
 * May need manual intervention for function prototypes that couldn't be
 * found (e.g. are in another file) or variables to be exported.
 */

/* C header guard removed: __TEST_DA_KUNIT_KUNIT_H */

/* C build condition preserved: IS_ENABLED(CONFIG_RV_MONITORS_KUNIT_TEST) */

/* C dependencies:
 * #include <linux/rv.h>
 * #include <rv/kunit.h>
 */

use core::ffi::c_void;

#[repr(C)]
pub struct rv_test_da_kunit_ops {
    pub mon: rv_kunit_mon,
    /*
     * Original generated C prototype contains an unresolved parameter after
     * `void *data`:
     * void (*handle_event_1)(void *data, /* XXX: fill header */);
     */
    pub handle_event_1: Option<unsafe extern "C" fn(data: *mut c_void)>,
    /*
     * Original generated C prototype contains an unresolved parameter after
     * `void *data`:
     * void (*handle_event_2)(void *data, /* XXX: fill header */);
     */
    pub handle_event_2: Option<unsafe extern "C" fn(data: *mut c_void)>,
}

unsafe extern "C" {
    pub static rv_test_da_kunit_ops: rv_test_da_kunit_ops;
}
