// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Linux/PA-RISC Project (http://www.parisc-linux.org/)
 *
 * Floating-point emulation code
 *  Copyright (C) 2001 Hewlett-Packard (Paul Bame) <bame@debian.org>
 */
/*
 * BEGIN_DESC
 *
 *  File:
 *	@(#)	pa/fp/decode_exc.c		$ Revision: $
 *
 *  Purpose:
 *	<<please update with a synopsis of the functionality provided by this file>>
 *
 *  External Interfaces:
 *	<<the following list was autogenerated, please review>>
 *	decode_fpu(Fpu_register, trap_counts)
 *
 *  Internal Interfaces:
 *	<<please update>>
 *
 *  Theory:
 *	<<please update with a overview of the operation of this file>>
 *
 * END_DESC
 */

const DOESTRAP: u32 = 1;
const NOTRAP: u32 = 0;
const COPROPBIT: u32 = 1 << (31 - 2);
const OPCLASS: u32 = 9;
const FMTBITS: u32 = 11;
const DF: u32 = 13;
const TWOBITS: u32 = 3;
const FIVEBITS: u32 = 31;
const MAX_EXCP_REG: usize = 7;

#[inline]
unsafe fn update_trap_counts(
    fpu_register: *mut u32,
    aflags: &mut u32,
    bflags: u32,
    _trap_counts: *mut u32,
) {
    *aflags = (*fpu_register >> 27);
    *fpu_register |= bflags;
}

pub unsafe fn decode_fpu(fpu_register: *mut u32, _trap_counts: *mut u32) -> u32 {
    let mut current_ir: u32;
    let mut excp: u32;
    let mut target: i32;
    let mut exception_index: usize = 1;
    let mut inexact: bool;
    let mut aflags: u32 = 0;
    let mut bflags: u32;
    let mut excptype: u32;

    bflags = *fpu_register & 0xf8000000;
    *fpu_register &= 0x07ffffff;

    if !Is_tbit_set() {
        update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
        return (SIGILL << 24) | ILL_COPROC;
    }

    for i in 1..=MAX_EXCP_REG {
        exception_index = i;
        current_ir = Excp_instr(i);
        excptype = Excp_type(i);
        if (excptype & UNIMPLEMENTEDEXCEPTION) != 0 {
            Clear_tbit();
            Clear_excp_register(i);
            excp = fpudispatch(current_ir, excptype, 0, fpu_register);
            if excp != 0 {
                Set_tbit();
                Set_exceptiontype_and_instr_field(excp, current_ir, *fpu_register.add(i));
                if excp == UNIMPLEMENTEDEXCEPTION {
                    excp = excptype;
                    update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                    return (SIGILL << 24) | ILL_COPROC;
                }
                excptype = excp;
            }
            if excp == NOEXCEPTION { break; }
        }

        if (excptype & UNDERFLOWEXCEPTION) != 0 {
            if Is_underflowtrap_enabled() {
                update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                return (SIGFPE << 24) | FPE_FLTUND;
            } else {
                target = (current_ir & FIVEBITS) as i32;
                inexact = Ibit(*fpu_register.add(exception_index));
                match Excp_format(current_ir) {
                    SGL => {
                        if Rabit(*fpu_register.add(exception_index)) { Sgl_decrement(fpu_register, target); }
                        sgl_denormalize(fpu_register, target, &mut inexact, Rounding_mode());
                    }
                    DBL => {
                        if Rabit(*fpu_register.add(exception_index)) { Dbl_decrement(fpu_register, target); }
                        dbl_denormalize(fpu_register, target, &mut inexact, Rounding_mode());
                    }
                    _ => {}
                }
                if inexact { Set_underflowflag(); }
                if inexact && Is_inexacttrap_enabled() {
                    Set_exceptiontype(*fpu_register.add(exception_index), INEXACTEXCEPTION);
                    Set_parmfield(*fpu_register.add(exception_index), 0);
                    update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                    return (SIGFPE << 24) | FPE_FLTRES;
                } else {
                    Clear_excp_register(exception_index);
                    if inexact { Set_inexactflag(); }
                }
            }
            continue;
        }

        match Excp_type(exception_index) {
            x if x == OVERFLOWEXCEPTION || x == (OVERFLOWEXCEPTION | INEXACTEXCEPTION) => {
                update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                if Is_overflowtrap_enabled() {
                    update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                    return (SIGFPE << 24) | FPE_FLTOVF;
                } else {
                    target = (current_ir & FIVEBITS) as i32;
                    match Excp_format(current_ir) {
                        SGL => Sgl_setoverflow(fpu_register, target),
                        DBL => Dbl_setoverflow(fpu_register, target),
                        _ => {}
                    }
                    Set_overflowflag();
                    if Is_inexacttrap_enabled() {
                        Set_exceptiontype(*fpu_register.add(exception_index), INEXACTEXCEPTION);
                        update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                        return (SIGFPE << 24) | FPE_FLTRES;
                    } else {
                        Clear_excp_register(exception_index);
                        Set_inexactflag();
                    }
                }
            }
            INVALIDEXCEPTION | OPC_2E_INVALIDEXCEPTION => {
                update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                return (SIGFPE << 24) | FPE_FLTINV;
            }
            DIVISIONBYZEROEXCEPTION => {
                update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                Clear_excp_register(exception_index);
                return (SIGFPE << 24) | FPE_FLTDIV;
            }
            INEXACTEXCEPTION => {
                update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                return (SIGFPE << 24) | FPE_FLTRES;
            }
            NOEXCEPTION => Clear_excp_register(exception_index),
            _ => {
                update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
                printk("%s(%d) Unknown FPU exception 0x%x\n", Excp_type(exception_index));
                return (SIGILL << 24) | ILL_COPROC;
            }
        }
    }

    Clear_tbit();
    update_trap_counts(fpu_register, &mut aflags, bflags, _trap_counts);
    NOTRAP
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
