// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Linux/PA-RISC Project (http://www.parisc-linux.org/)
 *
 * Floating-point emulation code
 *  Copyright (C) 2001 Hewlett-Packard (Paul Bame) <bame@debian.org>
 */
/*
 * BEGIN_DESC
 *
 *  File:
 *	@(#)	pa/fp/denormal.c		$ Revision: $
 *
 *  Purpose:
 *	<<please update with a synopsis of the functionality provided by this file>>
 *
 *  External Interfaces:
 *	<<the following list was autogenerated, please review>>
 *	dbl_denormalize(dbl_opndp1,dbl_opndp2,inexactflag,rmode)
 *	sgl_denormalize(sgl_opnd,inexactflag,rmode)
 *
 *  Internal Interfaces:
 *	<<please update>>
 *
 *  Theory:
 *	<<please update with a overview of the operation of this file>>
 *
 * END_DESC
 */

// Symbols from float.h, sgl_float.h, dbl_float.h, and hppa.h are supplied by
// the surrounding implementation.

pub unsafe fn sgl_denormalize(
    sgl_opnd: *mut u32,
    inexactflag: *mut bool,
    rmode: i32,
) {
    let mut opnd: u32;
    let mut sign: i32;
    let exponent: i32;
    let mut guardbit: bool = false;
    let stickybit: bool;
    let mut inexact: bool;

    opnd = *sgl_opnd;
    stickybit = *inexactflag;
    exponent = Sgl_exponent(opnd) - SGL_WRAP;
    sign = Sgl_sign(opnd);
    Sgl_denormalize(opnd, exponent, &mut guardbit, stickybit, &mut inexact);
    if inexact {
        match rmode {
            ROUNDPLUS => {
                if sign == 0 {
                    Sgl_increment(&mut opnd);
                }
            }
            ROUNDMINUS => {
                if sign != 0 {
                    Sgl_increment(&mut opnd);
                }
            }
            ROUNDNEAREST => {
                if guardbit && (stickybit || Sgl_isone_lowmantissa(opnd)) {
                    Sgl_increment(&mut opnd);
                }
            }
            _ => {}
        }
    }
    Sgl_set_sign(&mut opnd, sign);
    *sgl_opnd = opnd;
    *inexactflag = inexact;
}

pub unsafe fn dbl_denormalize(
    dbl_opndp1: *mut u32,
    dbl_opndp2: *mut u32,
    inexactflag: *mut bool,
    rmode: i32,
) {
    let mut opndp1: u32;
    let mut opndp2: u32;
    let mut sign: i32;
    let exponent: i32;
    let mut guardbit: bool = false;
    let stickybit: bool;
    let mut inexact: bool;

    opndp1 = *dbl_opndp1;
    opndp2 = *dbl_opndp2;
    stickybit = *inexactflag;
    exponent = Dbl_exponent(opndp1) - DBL_WRAP;
    sign = Dbl_sign(opndp1);
    Dbl_denormalize(
        opndp1,
        opndp2,
        exponent,
        &mut guardbit,
        stickybit,
        &mut inexact,
    );
    if inexact {
        match rmode {
            ROUNDPLUS => {
                if sign == 0 {
                    Dbl_increment(&mut opndp1, &mut opndp2);
                }
            }
            ROUNDMINUS => {
                if sign != 0 {
                    Dbl_increment(&mut opndp1, &mut opndp2);
                }
            }
            ROUNDNEAREST => {
                if guardbit && (stickybit || Dbl_isone_lowmantissap2(opndp2)) {
                    Dbl_increment(&mut opndp1, &mut opndp2);
                }
            }
            _ => {}
        }
    }
    Dbl_set_sign(&mut opndp1, sign);
    *dbl_opndp1 = opndp1;
    *dbl_opndp2 = opndp2;
    *inexactflag = inexact;
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
