/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * CRC constants generated by:
 *
 *     ./scripts/gen-crc-consts.py riscv_clmul crc16_msb_0x8bb7,crc32_msb_0x04c11db7,crc32_lsb_0xedb88320,crc32_lsb_0x82f63b78,crc64_msb_0x42f0e1eba9ea3693,crc64_lsb_0x9a6c9329ac4bc9b5
 *
 * Do not edit manually.
 */

#[repr(C)]
pub struct crc_clmul_consts {
    pub fold_across_2_longs_const_hi: usize,
    pub fold_across_2_longs_const_lo: usize,
    pub barrett_reduction_const_1: usize,
    pub barrett_reduction_const_2: usize,
}

/* Constants generated for most-significant-bit-first CRC-16 using
 * G(x) = x^16 + x^15 + x^11 + x^9 + x^8 + x^7 + x^5 + x^4 + x^2 + x^1 + x^0 */
#[cfg(target_pointer_width = "64")]
pub static crc16_msb_0x8bb7_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0x0000000000001faa,
    fold_across_2_longs_const_lo: 0x000000000000a010,
    barrett_reduction_const_1: 0xfb2d2bfc0e99d245,
    barrett_reduction_const_2: 0x0000000000008bb7,
};
#[cfg(not(target_pointer_width = "64"))]
pub static crc16_msb_0x8bb7_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0x00005890,
    fold_across_2_longs_const_lo: 0x0000f249,
    barrett_reduction_const_1: 0xfb2d2bfc,
    barrett_reduction_const_2: 0x00008bb7,
};

/* Constants generated for most-significant-bit-first CRC-32 using
 * G(x) = x^32 + x^26 + x^23 + x^22 + x^16 + x^12 + x^11 + x^10 + x^8 + x^7 +
 *        x^5 + x^4 + x^2 + x^1 + x^0 */
#[cfg(target_pointer_width = "64")]
pub static crc32_msb_0x04c11db7_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0x00000000c5b9cd4c,
    fold_across_2_longs_const_lo: 0x00000000e8a45605,
    barrett_reduction_const_1: 0x826880efa40da72d,
    barrett_reduction_const_2: 0x0000000004c11db7,
};
#[cfg(not(target_pointer_width = "64"))]
pub static crc32_msb_0x04c11db7_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0xf200aa66,
    fold_across_2_longs_const_lo: 0x490d678d,
    barrett_reduction_const_1: 0x826880ef,
    barrett_reduction_const_2: 0x04c11db7,
};

/* Constants generated for least-significant-bit-first CRC-32 using the polynomial
 * G(x) = x^32 + x^26 + x^23 + x^22 + x^16 + x^12 + x^11 + x^10 + x^8 + x^7 +
 *        x^5 + x^4 + x^2 + x^1 + x^0 */
#[cfg(target_pointer_width = "64")]
pub static crc32_lsb_0xedb88320_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0x65673b4600000000,
    fold_across_2_longs_const_lo: 0x9ba54c6f00000000,
    barrett_reduction_const_1: 0xb4e5b025f7011641,
    barrett_reduction_const_2: 0x00000000edb88320,
};
#[cfg(not(target_pointer_width = "64"))]
pub static crc32_lsb_0xedb88320_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0xccaa009e,
    fold_across_2_longs_const_lo: 0xb8bc6765,
    barrett_reduction_const_1: 0xf7011641,
    barrett_reduction_const_2: 0xedb88320,
};

/* Constants generated for least-significant-bit-first CRC-32 using
 * G(x) = x^32 + x^28 + x^27 + x^26 + x^25 + x^23 + x^22 + x^20 + x^19 + x^18 +
 *        x^14 + x^13 + x^11 + x^10 + x^9 + x^8 + x^6 + x^0 */
#[cfg(target_pointer_width = "64")]
pub static crc32_lsb_0x82f63b78_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0x3743f7bd00000000,
    fold_across_2_longs_const_lo: 0x3171d43000000000,
    barrett_reduction_const_1: 0x4869ec38dea713f1,
    barrett_reduction_const_2: 0x0000000082f63b78,
};
#[cfg(not(target_pointer_width = "64"))]
pub static crc32_lsb_0x82f63b78_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0x493c7d27,
    fold_across_2_longs_const_lo: 0xdd45aab8,
    barrett_reduction_const_1: 0xdea713f1,
    barrett_reduction_const_2: 0x82f63b78,
};

/* CRC-64 constants are present only for 64-bit builds, matching CONFIG_64BIT. */
#[cfg(target_pointer_width = "64")]
pub static crc64_msb_0x42f0e1eba9ea3693_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0x4eb938a7d257740e,
    fold_across_2_longs_const_lo: 0x05f5c3c7eb52fab6,
    barrett_reduction_const_1: 0xabc694e836627c39,
    barrett_reduction_const_2: 0x42f0e1eba9ea3693,
};
#[cfg(target_pointer_width = "64")]
pub static crc64_lsb_0x9a6c9329ac4bc9b5_consts: crc_clmul_consts = crc_clmul_consts {
    fold_across_2_longs_const_hi: 0xeadc41fd2ba3d420,
    fold_across_2_longs_const_lo: 0x21e9761e252621ac,
    barrett_reduction_const_1: 0x27ecfa329aef9f77,
    barrett_reduction_const_2: 0x9a6c9329ac4bc9b5,
};

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
