/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Please do not include this explicitly.
 * This is used by C files generated by modpost.
 */

/* Translated from linux/export-internal.h. */

/*
 * Relative references reduce the size by half on 64-bit architectures and
 * eliminate absolute relocations requiring runtime processing on relocatable
 * kernels.  The original values are assembler fragments selected by the
 * build-time configuration.
 */
#[cfg(CONFIG_HAVE_ARCH_PREL32_RELOCATIONS)]
pub const __KSYM_ALIGN: &str = ".balign 4";
#[cfg(CONFIG_HAVE_ARCH_PREL32_RELOCATIONS)]
#[macro_export]
macro_rules! __KSYM_REF {
    ($sym:ident) => { concat!(".long ", stringify!($sym), " - .") };
}

#[cfg(all(not(CONFIG_HAVE_ARCH_PREL32_RELOCATIONS), CONFIG_64BIT))]
pub const __KSYM_ALIGN: &str = ".balign 8";
#[cfg(all(not(CONFIG_HAVE_ARCH_PREL32_RELOCATIONS), CONFIG_64BIT))]
#[macro_export]
macro_rules! __KSYM_REF {
    ($sym:ident) => { concat!(".quad ", stringify!($sym)) };
}

#[cfg(all(not(CONFIG_HAVE_ARCH_PREL32_RELOCATIONS), not(CONFIG_64BIT)))]
pub const __KSYM_ALIGN: &str = ".balign 4";
#[cfg(all(not(CONFIG_HAVE_ARCH_PREL32_RELOCATIONS), not(CONFIG_64BIT)))]
#[macro_export]
macro_rules! __KSYM_REF {
    ($sym:ident) => { concat!(".long ", stringify!($sym)) };
}

/*
 * For every exported symbol, place its name and namespace in
 * __ksymtab_strings and a struct kernel_symbol entry in __ksymtab.
 * The assembler sections and references are preserved as inline assembly.
 */
#[macro_export]
macro_rules! __KSYMTAB {
    ($name:ident, $sym:ident, $ns:expr) => {
        core::arch::global_asm!(concat!(
            "\t.section \"__ksymtab_strings\",\"aMS\",%progbits,1\n",
            "__kstrtab_", stringify!($name), ":\n",
            "\t.asciz \"", stringify!($name), "\"\n",
            "__kstrtabns_", stringify!($name), ":\n",
            "\t.asciz \"", $ns, "\"\n",
            "\t.previous\n",
            "\t.section \"___ksymtab+", stringify!($name), "\", \"a\"\n",
            __KSYM_ALIGN, "\n",
            "__ksymtab_", stringify!($name), ":\n",
            __KSYM_REF!($sym), "\n",
            __KSYM_REF!(__kstrtab_ $name), "\n",
            __KSYM_REF!(__kstrtabns_ $name), "\n",
            "\t.previous\n"
        ));
    };
}

#[cfg(all(CONFIG_PARISC, CONFIG_64BIT))]
#[macro_export]
macro_rules! KSYM_FUNC {
    ($name:ident) => { concat!("P%", stringify!($name)) };
}
#[cfg(not(all(CONFIG_PARISC, CONFIG_64BIT)))]
#[macro_export]
macro_rules! KSYM_FUNC {
    ($name:ident) => { stringify!($name) };
}

#[macro_export]
macro_rules! KSYMTAB_FUNC {
    ($name:ident, $ns:expr) => { __KSYMTAB!($name, $name, $ns) };
}
#[macro_export]
macro_rules! KSYMTAB_DATA {
    ($name:ident, $ns:expr) => { __KSYMTAB!($name, $name, $ns) };
}

#[macro_export]
macro_rules! SYMBOL_CRC {
    ($sym:ident, $crc:expr) => {
        core::arch::global_asm!(concat!(
            "\t.section \"___kcrctab+", stringify!($sym), "\",\"a\"\n",
            "\t.balign 4\n",
            "__crc_", stringify!($sym), ":\n",
            "\t.long ", stringify!($crc), "\n",
            "\t.previous\n"
        ));
    };
}

#[macro_export]
macro_rules! SYMBOL_FLAGS {
    ($sym:ident, $flags:expr) => {
        core::arch::global_asm!(concat!(
            "\t.section \"___kflagstab+", stringify!($sym), "\",\"a\"\n",
            "__flags_", stringify!($sym), ":\n",
            "\t.byte ", stringify!($flags), "\n",
            "\t.previous\n"
        ));
    };
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
