/* SPDX-License-Identifier: GPL-2.0-only */
/* Rust translation of linux/scmi_protocol.h. */

#![allow(non_camel_case_types, non_snake_case, dead_code)]

pub const SCMI_MAX_STR_SIZE: usize = 64;
pub const SCMI_SHORT_NAME_MAX_SIZE: usize = 16;

use core::ffi::c_void;

pub type u8_t = u8; pub type u16_t = u16; pub type u32_t = u32; pub type u64_t = u64;
pub type ktime_t = i64;

#[repr(C)] pub struct device { _private: [u8; 0] }
#[repr(C)] pub struct device_driver { _private: [u8; 0] }
#[repr(C)] pub struct module { _private: [u8; 0] }
#[repr(C)] pub struct notifier_block { _private: [u8; 0] }
#[repr(C)] pub struct scmi_protocol_handle { _private: [u8; 0] }
#[repr(C)] pub struct scmi_fc_info { _private: [u8; 0] }

#[repr(C)] pub struct scmi_base_info { pub major_ver:u16, pub minor_ver:u16, pub num_protocols:u8, pub num_agents:u8, pub impl_ver:u32, pub vendor_id:[i8;SCMI_SHORT_NAME_MAX_SIZE], pub sub_vendor_id:[i8;SCMI_SHORT_NAME_MAX_SIZE] }
#[repr(C)] pub struct scmi_clock_rates { pub rate_discrete:bool, pub num_rates:usize, pub rates:*mut u64 }
#[repr(C)] pub struct scmi_clock_info { pub name:[i8;SCMI_MAX_STR_SIZE], pub enable_latency:usize, pub rate_changed_notifications:bool, pub rate_change_requested_notifications:bool, pub state_ctrl_forbidden:bool, pub rate_ctrl_forbidden:bool, pub parent_ctrl_forbidden:bool, pub extended_config:bool, pub min_rate:u64, pub max_rate:u64, pub num_parents:i32, pub parents:*mut u32 }

#[repr(u32)] pub enum scmi_power_scale { SCMI_POWER_BOGOWATTS, SCMI_POWER_MILLIWATTS, SCMI_POWER_MICROWATTS }
#[repr(C)] pub struct scmi_handle_forward; #[repr(C)] pub struct scmi_device_forward;
#[repr(u32)] pub enum scmi_clock_oem_config { SCMI_CLOCK_CFG_DUTY_CYCLE=1, SCMI_CLOCK_CFG_PHASE, SCMI_CLOCK_CFG_OEM_START=0x80, SCMI_CLOCK_CFG_OEM_END=0xff }

pub type ScmiResult = i32;
#[repr(C)] pub struct scmi_clk_proto_ops { pub count_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle)->i32>, pub info_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->*const scmi_clock_info>, pub rate_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u64)->i32>, pub rate_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u64)->i32>, pub determine_rate:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut usize)->i32>, pub all_rates_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->*const scmi_clock_rates>, pub enable:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,bool)->i32>, pub disable:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,bool)->i32>, pub state_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut bool,bool)->i32>, pub config_oem_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,scmi_clock_oem_config,*mut u32,*mut u32,bool)->i32>, pub config_oem_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,scmi_clock_oem_config,u32,bool)->i32>, pub parent_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32)->i32>, pub parent_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32)->i32> }
#[repr(C)] pub struct scmi_perf_domain_info { pub name:[i8;SCMI_MAX_STR_SIZE], pub set_perf:bool }
#[repr(C)] pub struct scmi_perf_proto_ops { pub num_domains_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle)->i32>, pub info_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->*const scmi_perf_domain_info>, pub limits_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32,u32)->i32>, pub limits_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32,*mut u32)->i32>, pub level_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32,bool)->i32>, pub level_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32,bool)->i32>, pub transition_latency_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->i32>, pub rate_limit_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32)->i32>, pub device_opps_add:Option<unsafe extern "C" fn(*const scmi_protocol_handle,*mut device,u32)->i32>, pub freq_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,usize,bool)->i32>, pub freq_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut usize,bool)->i32>, pub est_power_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut usize,*mut usize)->i32>, pub fast_switch_possible:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->bool>, pub fast_switch_rate_limit:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32)->i32>, pub power_scale_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle)->scmi_power_scale> }

#[repr(C)] pub struct scmi_power_proto_ops { pub num_domains_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle)->i32>, pub name_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->*const i8>, pub state_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32)->i32>, pub state_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32)->i32> }
pub const SCMI_POWER_STATE_TYPE_SHIFT:u32=30; pub const SCMI_POWER_STATE_ID_MASK:u32=(1<<28)-1; pub const SCMI_POWER_STATE_GENERIC_ON:u32=0; pub const SCMI_POWER_STATE_GENERIC_OFF:u32=1<<30;
#[inline] pub const fn SCMI_POWER_STATE_PARAM(ty:u32,id:u32)->u32 { ((ty&1)<<SCMI_POWER_STATE_TYPE_SHIFT)|(id&SCMI_POWER_STATE_ID_MASK) }

#[repr(C)] pub struct scmi_sensor_reading { pub value:i64, pub timestamp:u64 }
#[repr(C)] pub struct scmi_range_attrs { pub min_range:i64, pub max_range:i64 }
#[repr(C)] pub struct scmi_sensor_axis_info { pub id:usize,pub ty:usize,pub scale:i32,pub name:[i8;SCMI_MAX_STR_SIZE],pub extended_attrs:bool,pub resolution:usize,pub exponent:i32,pub attrs:scmi_range_attrs }
pub const SCMI_MAX_PREALLOC_POOL:usize=16;
#[repr(C)] pub struct scmi_sensor_intervals_info { pub segmented:bool,pub count:usize,pub desc:*mut u32,pub prealloc_pool:[u32;SCMI_MAX_PREALLOC_POOL] }
pub const SCMI_SENS_INTVL_SEGMENT_LOW:usize=0; pub const SCMI_SENS_INTVL_SEGMENT_HIGH:usize=1; pub const SCMI_SENS_INTVL_SEGMENT_STEP:usize=2;
#[inline] pub const fn SCMI_SENS_INTVL_GET_SECS(x:u32)->u32 {(x>>5)&0xffff}
#[inline] pub const fn SCMI_SENS_INTVL_GET_EXP(x:u32)->i32 { let v=(x&31) as i32; if v&16!=0 {v|!31} else {v} }
#[repr(C)] pub struct scmi_sensor_info { pub id:usize,pub ty:usize,pub scale:i32,pub num_trip_points:usize,pub r#async:bool,pub update:bool,pub timestamped:bool,pub tstamp_scale:i32,pub num_axis:usize,pub axis:*mut scmi_sensor_axis_info,pub intervals:scmi_sensor_intervals_info,pub sensor_config:u32,pub name:[i8;SCMI_MAX_STR_SIZE],pub extended_scalar_attrs:bool,pub sensor_power:usize,pub resolution:usize,pub exponent:i32,pub scalar_attrs:scmi_range_attrs }
pub const SCMI_SENS_CFG_UPDATE_SECS_MASK:u32=0xffff0000; pub const SCMI_SENS_CFG_UPDATE_EXP_MASK:u32=0x0000f800; pub const SCMI_SENS_CFG_ROUND_MASK:u32=0x600; pub const SCMI_SENS_CFG_ROUND_AUTO:u32=2; pub const SCMI_SENS_CFG_ROUND_UP:u32=1; pub const SCMI_SENS_CFG_ROUND_DOWN:u32=0; pub const SCMI_SENS_CFG_TSTAMP_ENABLED_MASK:u32=2; pub const SCMI_SENS_CFG_SENSOR_ENABLED_MASK:u32=1;
#[inline] pub const fn SCMI_SENS_CFG_GET_UPDATE_SECS(x:u32)->u32{(x>>16)&0xffff} #[inline] pub const fn SCMI_SENS_CFG_GET_UPDATE_EXP(x:u32)->i32{let v=((x>>11)&31)as i32;if v&16!=0{v|!31}else{v}} #[inline] pub const fn SCMI_SENS_CFG_IS_TSTAMP_ENABLED(x:u32)->u32{(x>>1)&1} #[inline] pub const fn SCMI_SENS_CFG_IS_ENABLED(x:u32)->u32{x&1}

#[repr(u32)] pub enum scmi_sensor_class { NONE=0, UNSPEC=1, TEMPERATURE_C=2, TEMPERATURE_F=3, TEMPERATURE_K=4, VOLTAGE=5, CURRENT=6, POWER=7, ENERGY=8, CHARGE=9, VOLTAMPERE=0xa, NITS=0xb, LUMENS=0xc, LUX=0xd, CANDELAS=0xe, KPA=0xf, PSI=0x10, NEWTON=0x11, CFM=0x12, RPM=0x13, HERTZ=0x14, SECS=0x15, MINS=0x16, HOURS=0x17, DAYS=0x18, WEEKS=0x19, MILS=0x1a, INCHES=0x1b, FEET=0x1c, CUBIC_INCHES=0x1d, CUBIC_FEET=0x1e, METERS=0x1f, CUBIC_CM=0x20, CUBIC_METERS=0x21, LITERS=0x22, FLUID_OUNCES=0x23, RADIANS=0x24, STERADIANS=0x25, REVOLUTIONS=0x26, CYCLES=0x27, GRAVITIES=0x28, OUNCES=0x29, POUNDS=0x2a, FOOT_POUNDS=0x2b, OUNCE_INCHES=0x2c, GAUSS=0x2d, GILBERTS=0x2e, HENRIES=0x2f, FARADS=0x30, OHMS=0x31, SIEMENS=0x32, MOLES=0x33, BECQUERELS=0x34, PPM=0x35, DECIBELS=0x36, DBA=0x37, DBC=0x38, GRAYS=0x39, SIEVERTS=0x3a, COLOR_TEMP_K=0x3b, BITS=0x3c, BYTES=0x3d, WORDS=0x3e, DWORDS=0x3f, QWORDS=0x40, PERCENTAGE=0x41, PASCALS=0x42, COUNTS=0x43, GRAMS=0x44, NEWTON_METERS=0x45, HITS=0x46, MISSES=0x47, RETRIES=0x48, OVERRUNS=0x49, UNDERRUNS=0x4a, COLLISIONS=0x4b, PACKETS=0x4c, MESSAGES=0x4d, CHARS=0x4e, ERRORS=0x4f, CORRECTED_ERRS=0x50, UNCORRECTABLE_ERRS=0x51, SQ_MILS=0x52, SQ_INCHES=0x53, SQ_FEET=0x54, SQ_CM=0x55, SQ_METERS=0x56, RADIANS_SEC=0x57, BPM=0x58, METERS_SEC_SQUARED=0x59, METERS_SEC=0x5a, CUBIC_METERS_SEC=0x5b, MM_MERCURY=0x5c, RADIANS_SEC_SQUARED=0x5d, OEM_UNIT=0xff }

#[repr(C)] pub struct scmi_sensor_proto_ops { pub count_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle)->i32>, pub info_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->*const scmi_sensor_info>, pub trip_point_config:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u8,u64)->i32>, pub reading_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u64)->i32>, pub reading_get_timestamped:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u8,*mut scmi_sensor_reading)->i32>, pub config_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32)->i32>, pub config_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32)->i32> }
#[repr(C)] pub struct scmi_reset_proto_ops { pub num_domains_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle)->i32>, pub name_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->*const i8>, pub latency_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->i32>, pub reset:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->i32>, pub assert:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->i32>, pub deassert:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->i32> }
#[repr(u32)] pub enum scmi_voltage_level_mode { SCMI_VOLTAGE_LEVEL_SET_AUTO, SCMI_VOLTAGE_LEVEL_SET_SYNC }
#[repr(C)] pub struct scmi_voltage_info { pub id:usize,pub segmented:bool,pub negative_volts_allowed:bool,pub async_level_set:bool,pub name:[i8;SCMI_MAX_STR_SIZE],pub num_levels:usize,pub levels_uv:*mut i32 }
pub const SCMI_VOLTAGE_SEGMENT_LOW:usize=0;pub const SCMI_VOLTAGE_SEGMENT_HIGH:usize=1;pub const SCMI_VOLTAGE_SEGMENT_STEP:usize=2;pub const SCMI_VOLTAGE_ARCH_STATE_OFF:u32=0;pub const SCMI_VOLTAGE_ARCH_STATE_ON:u32=7;
#[repr(C)] pub struct scmi_voltage_proto_ops { pub num_domains_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle)->i32>,pub info_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->*const scmi_voltage_info>,pub config_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32)->i32>,pub config_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32)->i32>,pub level_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,scmi_voltage_level_mode,i32)->i32>,pub level_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut i32)->i32> }
#[repr(C)] pub struct scmi_powercap_info { pub id:usize,pub notify_powercap_cap_change:bool,pub notify_powercap_measurement_change:bool,pub async_powercap_cap_set:bool,pub powercap_cap_config:bool,pub powercap_monitoring:bool,pub powercap_pai_config:bool,pub powercap_scale_mw:bool,pub powercap_scale_uw:bool,pub fastchannels:bool,pub name:[i8;SCMI_MAX_STR_SIZE],pub min_pai:usize,pub max_pai:usize,pub pai_step:usize,pub min_power_cap:usize,pub max_power_cap:usize,pub power_cap_step:usize,pub sustainable_power:usize,pub accuracy:usize,pub parent_id:usize,pub fc_info:*mut scmi_fc_info }
pub const SCMI_POWERCAP_ROOT_ZONE_ID:u32=0xffff_ffff;
#[repr(C)] pub struct scmi_powercap_proto_ops { pub num_domains_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle)->i32>,pub info_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->*const scmi_powercap_info>,pub cap_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32)->i32>,pub cap_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32,bool)->i32>,pub cap_enable_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,bool)->i32>,pub cap_enable_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut bool)->i32>,pub pai_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32)->i32>,pub pai_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32)->i32>,pub measurements_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32,*mut u32)->i32>,pub measurements_threshold_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32,u32)->i32>,pub measurements_threshold_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut u32,*mut u32)->i32> }

#[repr(u32)] pub enum scmi_pinctrl_selector_type { PIN_TYPE=0, GROUP_TYPE, FUNCTION_TYPE }
#[repr(u32)] pub enum scmi_pinctrl_conf_type { SCMI_PIN_DEFAULT=0, SCMI_PIN_BIAS_BUS_HOLD=1, SCMI_PIN_BIAS_DISABLE, SCMI_PIN_BIAS_HIGH_IMPEDANCE, SCMI_PIN_BIAS_PULL_UP, SCMI_PIN_BIAS_PULL_DEFAULT, SCMI_PIN_BIAS_PULL_DOWN, SCMI_PIN_DRIVE_OPEN_DRAIN, SCMI_PIN_DRIVE_OPEN_SOURCE, SCMI_PIN_DRIVE_PUSH_PULL, SCMI_PIN_DRIVE_STRENGTH, SCMI_PIN_INPUT_DEBOUNCE, SCMI_PIN_INPUT_MODE, SCMI_PIN_PULL_MODE, SCMI_PIN_INPUT_VALUE, SCMI_PIN_INPUT_SCHMITT, SCMI_PIN_LOW_POWER_MODE, SCMI_PIN_OUTPUT_MODE, SCMI_PIN_OUTPUT_VALUE, SCMI_PIN_POWER_SOURCE, SCMI_PIN_SLEW_RATE, SCMI_PIN_OEM_START=192, SCMI_PIN_OEM_END=255 }
#[repr(C)] pub struct scmi_pinctrl_proto_ops { pub count_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,scmi_pinctrl_selector_type)->i32>,pub name_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,scmi_pinctrl_selector_type,*mut *const i8)->i32>,pub group_pins_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut *const u32,*mut usize)->i32>,pub function_groups_get:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,*mut usize,*mut *const u32)->i32>,pub mux_set:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,u32)->i32>,pub settings_get_one:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,scmi_pinctrl_selector_type,scmi_pinctrl_conf_type,*mut u32)->i32>,pub settings_get_all:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,scmi_pinctrl_selector_type,*mut usize,*mut scmi_pinctrl_conf_type,*mut u32)->i32>,pub settings_conf:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32,scmi_pinctrl_selector_type,usize,*mut scmi_pinctrl_conf_type,*mut u32)->i32>,pub pin_request:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->i32>,pub pin_free:Option<unsafe extern "C" fn(*const scmi_protocol_handle,u32)->i32> }
#[repr(C)] pub struct scmi_notify_ops { pub devm_event_notifier_register:Option<unsafe extern "C" fn(*mut scmi_device,u8,u8,*const u32,*mut notifier_block)->i32>,pub devm_event_notifier_unregister:Option<unsafe extern "C" fn(*mut scmi_device,*mut notifier_block)->i32>,pub event_notifier_register:Option<unsafe extern "C" fn(*const scmi_handle,u8,u8,*const u32,*mut notifier_block)->i32>,pub event_notifier_unregister:Option<unsafe extern "C" fn(*const scmi_handle,u8,u8,*const u32,*mut notifier_block)->i32> }
#[repr(C)] pub struct scmi_handle { pub dev:*mut device,pub version:*mut scmi_base_info,pub devm_protocol_acquire:Option<unsafe extern "C" fn(*mut scmi_device,u8)->i32>,pub devm_protocol_get:Option<unsafe extern "C" fn(*mut scmi_device,u8,*mut *mut scmi_protocol_handle)->*const c_void>,pub devm_protocol_put:Option<unsafe extern "C" fn(*mut scmi_device,u8)>,pub is_transport_atomic:Option<unsafe extern "C" fn(*const scmi_handle,*mut usize)->bool>,pub notify_ops:*const scmi_notify_ops }
#[repr(u32)] pub enum scmi_std_protocol { SCMI_PROTOCOL_BASE=0x10,SCMI_PROTOCOL_POWER,SCMI_PROTOCOL_SYSTEM,SCMI_PROTOCOL_PERF,SCMI_PROTOCOL_CLOCK,SCMI_PROTOCOL_SENSOR,SCMI_PROTOCOL_RESET,SCMI_PROTOCOL_VOLTAGE,SCMI_PROTOCOL_POWERCAP,SCMI_PROTOCOL_PINCTRL }
#[repr(u32)] pub enum scmi_system_events { SCMI_SYSTEM_SHUTDOWN,SCMI_SYSTEM_COLDRESET,SCMI_SYSTEM_WARMRESET,SCMI_SYSTEM_POWERUP,SCMI_SYSTEM_SUSPEND,SCMI_SYSTEM_MAX }
#[repr(C)] pub struct scmi_device { pub id:u32,pub protocol_id:u8,pub name:*const i8,pub dev:device,pub handle:*mut scmi_handle }
#[repr(C)] pub struct scmi_device_id { pub protocol_id:u8,pub name:*const i8 }
#[repr(C)] pub struct scmi_driver { pub name:*const i8,pub probe:Option<unsafe extern "C" fn(*mut scmi_device)->i32>,pub remove:Option<unsafe extern "C" fn(*mut scmi_device)>,pub id_table:*const scmi_device_id,pub driver:device_driver }
extern "C" { pub fn scmi_driver_register(driver:*mut scmi_driver, owner:*mut module, mod_name:*const i8)->i32; pub fn scmi_driver_unregister(driver:*mut scmi_driver); }
#[repr(C)] pub struct scmi_protocol { _private:[u8;0] }
extern "C" { pub fn scmi_protocol_register(proto:*const scmi_protocol)->i32; pub fn scmi_protocol_unregister(proto:*const scmi_protocol); }
#[repr(u32)] pub enum scmi_notification_events { SCMI_EVENT_POWER_STATE_CHANGED=0,SCMI_EVENT_CLOCK_RATE_CHANGED=0,SCMI_EVENT_CLOCK_RATE_CHANGE_REQUESTED=1,SCMI_EVENT_PERFORMANCE_LIMITS_CHANGED=0,SCMI_EVENT_PERFORMANCE_LEVEL_CHANGED=1,SCMI_EVENT_SENSOR_TRIP_POINT_EVENT=0,SCMI_EVENT_SENSOR_UPDATE=1,SCMI_EVENT_RESET_ISSUED=0,SCMI_EVENT_BASE_ERROR_EVENT=0,SCMI_EVENT_SYSTEM_POWER_STATE_NOTIFIER=0,SCMI_EVENT_POWERCAP_CAP_CHANGED=0,SCMI_EVENT_POWERCAP_MEASUREMENTS_CHANGED=1 }
#[repr(C)] pub struct scmi_power_state_changed_report { pub timestamp:ktime_t,pub agent_id:usize,pub domain_id:usize,pub power_state:usize }
#[repr(C)] pub struct scmi_clock_rate_notif_report { pub timestamp:ktime_t,pub agent_id:usize,pub clock_id:usize,pub rate:u64 }
#[repr(C)] pub struct scmi_system_power_state_notifier_report { pub timestamp:ktime_t,pub agent_id:usize,pub flags:usize,pub system_state:usize,pub timeout:usize }
#[inline] pub const fn SCMI_SYSPOWER_IS_REQUEST_GRACEFUL(flags:usize)->usize{flags&1}
#[repr(C)] pub struct scmi_perf_limits_report { pub timestamp:ktime_t,pub agent_id:usize,pub domain_id:usize,pub range_max:usize,pub range_min:usize,pub range_max_freq:usize,pub range_min_freq:usize }
#[repr(C)] pub struct scmi_perf_level_report { pub timestamp:ktime_t,pub agent_id:usize,pub domain_id:usize,pub performance_level:usize,pub performance_level_freq:usize }
#[repr(C)] pub struct scmi_sensor_trip_point_report { pub timestamp:ktime_t,pub agent_id:usize,pub sensor_id:usize,pub trip_point_desc:usize }
#[repr(C)] pub struct scmi_sensor_update_report { pub timestamp:ktime_t,pub agent_id:usize,pub sensor_id:usize,pub readings_count:usize,pub readings:[scmi_sensor_reading;0] }
#[repr(C)] pub struct scmi_reset_issued_report { pub timestamp:ktime_t,pub agent_id:usize,pub domain_id:usize,pub reset_state:usize }
#[repr(C)] pub struct scmi_base_error_report { pub timestamp:ktime_t,pub agent_id:usize,pub fatal:bool,pub cmd_count:usize,pub reports:[u64;0] }
#[repr(C)] pub struct scmi_powercap_cap_changed_report { pub timestamp:ktime_t,pub agent_id:usize,pub domain_id:usize,pub power_cap:usize,pub pai:usize }
#[repr(C)] pub struct scmi_powercap_meas_changed_report { pub timestamp:ktime_t,pub agent_id:usize,pub domain_id:usize,pub power:usize }

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
