/* SPDX-License-Identifier: GPL-2.0 */

// CONFIG_ZONE_DMA controls inclusion of the DMA zone item.
// CONFIG_ZONE_DMA32 controls inclusion of the DMA32 zone item.
// CONFIG_HIGHMEM controls inclusion of the HIGH zone item.
// CONFIG_ZONE_DEVICE controls inclusion of the DEVICE zone item.

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum vm_event_item {
    PGPGIN,
    PGPGOUT,
    PSWPIN,
    PSWPOUT,
    #[cfg(CONFIG_ZONE_DMA)]
    PGALLOC_DMA,
    #[cfg(CONFIG_ZONE_DMA32)]
    PGALLOC_DMA32,
    PGALLOC_NORMAL,
    #[cfg(CONFIG_HIGHMEM)]
    PGALLOC_HIGH,
    PGALLOC_MOVABLE,
    #[cfg(CONFIG_ZONE_DEVICE)]
    PGALLOC_DEVICE,
    #[cfg(CONFIG_ZONE_DMA)]
    ALLOCSTALL_DMA,
    #[cfg(CONFIG_ZONE_DMA32)]
    ALLOCSTALL_DMA32,
    ALLOCSTALL_NORMAL,
    #[cfg(CONFIG_HIGHMEM)]
    ALLOCSTALL_HIGH,
    ALLOCSTALL_MOVABLE,
    #[cfg(CONFIG_ZONE_DEVICE)]
    ALLOCSTALL_DEVICE,
    #[cfg(CONFIG_ZONE_DMA)]
    PGSCAN_SKIP_DMA,
    #[cfg(CONFIG_ZONE_DMA32)]
    PGSCAN_SKIP_DMA32,
    PGSCAN_SKIP_NORMAL,
    #[cfg(CONFIG_HIGHMEM)]
    PGSCAN_SKIP_HIGH,
    PGSCAN_SKIP_MOVABLE,
    #[cfg(CONFIG_ZONE_DEVICE)]
    PGSCAN_SKIP_DEVICE,
    PGFREE,
    PGACTIVATE,
    PGDEACTIVATE,
    PGLAZYFREE,
    PGFAULT,
    PGMAJFAULT,
    PGLAZYFREED,
    PGREUSE,
    PGSCAN_DIRECT_THROTTLE,
    #[cfg(CONFIG_NUMA)]
    PGSCAN_ZONE_RECLAIM_SUCCESS,
    #[cfg(CONFIG_NUMA)]
    PGSCAN_ZONE_RECLAIM_FAILED,
    PGINODESTEAL,
    SLABS_SCANNED,
    KSWAPD_INODESTEAL,
    KSWAPD_LOW_WMARK_HIT_QUICKLY,
    KSWAPD_HIGH_WMARK_HIT_QUICKLY,
    PAGEOUTRUN,
    PGROTATED,
    DROP_PAGECACHE,
    DROP_SLAB,
    OOM_KILL,
    #[cfg(CONFIG_NUMA_BALANCING)]
    NUMA_PTE_UPDATES,
    #[cfg(CONFIG_NUMA_BALANCING)]
    NUMA_HUGE_PTE_UPDATES,
    #[cfg(CONFIG_NUMA_BALANCING)]
    NUMA_HINT_FAULTS,
    #[cfg(CONFIG_NUMA_BALANCING)]
    NUMA_HINT_FAULTS_LOCAL,
    #[cfg(CONFIG_NUMA_BALANCING)]
    NUMA_PAGE_MIGRATE,
    #[cfg(CONFIG_MIGRATION)]
    PGMIGRATE_SUCCESS,
    #[cfg(CONFIG_MIGRATION)]
    PGMIGRATE_FAIL,
    #[cfg(CONFIG_MIGRATION)]
    THP_MIGRATION_SUCCESS,
    #[cfg(CONFIG_MIGRATION)]
    THP_MIGRATION_FAIL,
    #[cfg(CONFIG_MIGRATION)]
    THP_MIGRATION_SPLIT,
    #[cfg(CONFIG_COMPACTION)]
    COMPACTMIGRATE_SCANNED,
    #[cfg(CONFIG_COMPACTION)]
    COMPACTFREE_SCANNED,
    #[cfg(CONFIG_COMPACTION)]
    COMPACTISOLATED,
    #[cfg(CONFIG_COMPACTION)]
    COMPACTSTALL,
    #[cfg(CONFIG_COMPACTION)]
    COMPACTFAIL,
    #[cfg(CONFIG_COMPACTION)]
    COMPACTSUCCESS,
    #[cfg(CONFIG_COMPACTION)]
    KCOMPACTD_WAKE,
    #[cfg(CONFIG_COMPACTION)]
    KCOMPACTD_MIGRATE_SCANNED,
    #[cfg(CONFIG_COMPACTION)]
    KCOMPACTD_FREE_SCANNED,
    #[cfg(CONFIG_HUGETLB_PAGE)]
    HTLB_BUDDY_PGALLOC,
    #[cfg(CONFIG_HUGETLB_PAGE)]
    HTLB_BUDDY_PGALLOC_FAIL,
    #[cfg(CONFIG_CMA)]
    CMA_ALLOC_SUCCESS,
    #[cfg(CONFIG_CMA)]
    CMA_ALLOC_FAIL,
    UNEVICTABLE_PGCULLED, // culled to noreclaim list
    UNEVICTABLE_PGSCANNED, // scanned for reclaimability
    UNEVICTABLE_PGRESCUED, // rescued from noreclaim list
    UNEVICTABLE_PGMLOCKED,
    UNEVICTABLE_PGMUNLOCKED,
    UNEVICTABLE_PGCLEARED, // on COW, page truncate
    UNEVICTABLE_PGSTRANDED, // unable to isolate on unlock
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_FAULT_ALLOC,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_FAULT_FALLBACK,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_FAULT_FALLBACK_CHARGE,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_COLLAPSE_ALLOC,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_COLLAPSE_ALLOC_FAILED,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_FILE_ALLOC,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_FILE_FALLBACK,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_FILE_FALLBACK_CHARGE,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_FILE_MAPPED,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_SPLIT_PAGE,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_SPLIT_PAGE_FAILED,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_DEFERRED_SPLIT_PAGE,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_UNDERUSED_SPLIT_PAGE,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_SPLIT_PMD,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_SCAN_EXCEED_NONE_PTE,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_SCAN_EXCEED_SWAP_PTE,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_SCAN_EXCEED_SHARED_PTE,
    #[cfg(all(CONFIG_TRANSPARENT_HUGEPAGE, CONFIG_HAVE_ARCH_TRANSPARENT_HUGEPAGE_PUD))]
    THP_SPLIT_PUD,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_ZERO_PAGE_ALLOC,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_ZERO_PAGE_ALLOC_FAILED,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_SWPOUT,
    #[cfg(CONFIG_TRANSPARENT_HUGEPAGE)]
    THP_SWPOUT_FALLBACK,
    #[cfg(CONFIG_BALLOON)]
    BALLOON_INFLATE,
    #[cfg(CONFIG_BALLOON)]
    BALLOON_DEFLATE,
    #[cfg(all(CONFIG_BALLOON, CONFIG_BALLOON_MIGRATION))]
    BALLOON_MIGRATE,
    #[cfg(CONFIG_DEBUG_TLBFLUSH)]
    NR_TLB_REMOTE_FLUSH, // cpu tried to flush others' tlbs
    #[cfg(CONFIG_DEBUG_TLBFLUSH)]
    NR_TLB_REMOTE_FLUSH_RECEIVED, // cpu received ipi for flush
    #[cfg(CONFIG_DEBUG_TLBFLUSH)]
    NR_TLB_LOCAL_FLUSH_ALL,
    #[cfg(CONFIG_DEBUG_TLBFLUSH)]
    NR_TLB_LOCAL_FLUSH_ONE,
    #[cfg(CONFIG_SWAP)]
    SWAP_RA,
    #[cfg(CONFIG_SWAP)]
    SWAP_RA_HIT,
    #[cfg(CONFIG_SWAP)]
    SWPIN_ZERO,
    #[cfg(CONFIG_SWAP)]
    SWPOUT_ZERO,
    #[cfg(all(CONFIG_SWAP, CONFIG_KSM))]
    KSM_SWPIN_COPY,
    #[cfg(CONFIG_KSM)]
    COW_KSM,
    #[cfg(CONFIG_ZSWAP)]
    ZSWPIN,
    #[cfg(CONFIG_ZSWAP)]
    ZSWPOUT,
    #[cfg(CONFIG_ZSWAP)]
    ZSWPWB,
    #[cfg(CONFIG_X86)]
    DIRECT_MAP_LEVEL2_SPLIT,
    #[cfg(CONFIG_X86)]
    DIRECT_MAP_LEVEL3_SPLIT,
    #[cfg(CONFIG_X86)]
    DIRECT_MAP_LEVEL2_COLLAPSE,
    #[cfg(CONFIG_X86)]
    DIRECT_MAP_LEVEL3_COLLAPSE,
    #[cfg(CONFIG_PER_VMA_LOCK_STATS)]
    VMA_LOCK_SUCCESS,
    #[cfg(CONFIG_PER_VMA_LOCK_STATS)]
    VMA_LOCK_ABORT,
    #[cfg(CONFIG_PER_VMA_LOCK_STATS)]
    VMA_LOCK_RETRY,
    #[cfg(CONFIG_PER_VMA_LOCK_STATS)]
    VMA_LOCK_MISS,
    #[cfg(CONFIG_DEBUG_STACK_USAGE)]
    KSTACK_1K,
    // THREAD_SIZE-dependent variants preserve the original preprocessor conditions.
    #[cfg(all(CONFIG_DEBUG_STACK_USAGE, THREAD_SIZE_GT_1024))]
    KSTACK_2K,
    #[cfg(all(CONFIG_DEBUG_STACK_USAGE, THREAD_SIZE_GT_2048))]
    KSTACK_4K,
    #[cfg(all(CONFIG_DEBUG_STACK_USAGE, THREAD_SIZE_GT_4096))]
    KSTACK_8K,
    #[cfg(all(CONFIG_DEBUG_STACK_USAGE, THREAD_SIZE_GT_8192))]
    KSTACK_16K,
    #[cfg(all(CONFIG_DEBUG_STACK_USAGE, THREAD_SIZE_GT_16384))]
    KSTACK_32K,
    #[cfg(all(CONFIG_DEBUG_STACK_USAGE, THREAD_SIZE_GT_32768))]
    KSTACK_64K,
    #[cfg(all(CONFIG_DEBUG_STACK_USAGE, THREAD_SIZE_GT_65536))]
    KSTACK_REST,
    #[cfg(CONFIG_SWAP)]
    NRSWPIN,
    #[cfg(CONFIG_SWAP)]
    NRSWPOUT,
    NR_VM_EVENT_ITEMS,
}

// When CONFIG_TRANSPARENT_HUGEPAGE is disabled, these C object-like macros
// invoke the external BUILD_BUG facility and evaluate to zero.
#[cfg(not(CONFIG_TRANSPARENT_HUGEPAGE))]
macro_rules! THP_FILE_ALLOC { () => {{ BUILD_BUG(); 0 }}; }
#[cfg(not(CONFIG_TRANSPARENT_HUGEPAGE))]
macro_rules! THP_FILE_FALLBACK { () => {{ BUILD_BUG(); 0 }}; }
#[cfg(not(CONFIG_TRANSPARENT_HUGEPAGE))]
macro_rules! THP_FILE_FALLBACK_CHARGE { () => {{ BUILD_BUG(); 0 }}; }
#[cfg(not(CONFIG_TRANSPARENT_HUGEPAGE))]
macro_rules! THP_FILE_MAPPED { () => {{ BUILD_BUG(); 0 }}; }

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
