// SPDX-License-Identifier: GPL-2.0
// COMPILE_OFFSETS
// External kernel definitions and the DEFINE mechanism are supplied by dependencies.

fn main() {
    DEFINE!(SIZE_usb_device_id, core::mem::size_of::<usb_device_id>());
    DEFINE!(OFF_usb_device_id_match_flags, core::mem::offset_of!(usb_device_id, match_flags));
    DEFINE!(OFF_usb_device_id_idVendor, core::mem::offset_of!(usb_device_id, idVendor));
    DEFINE!(OFF_usb_device_id_idProduct, core::mem::offset_of!(usb_device_id, idProduct));
    DEFINE!(OFF_usb_device_id_bcdDevice_lo, core::mem::offset_of!(usb_device_id, bcdDevice_lo));
    DEFINE!(OFF_usb_device_id_bcdDevice_hi, core::mem::offset_of!(usb_device_id, bcdDevice_hi));
    DEFINE!(OFF_usb_device_id_bDeviceClass, core::mem::offset_of!(usb_device_id, bDeviceClass));
    DEFINE!(OFF_usb_device_id_bDeviceSubClass, core::mem::offset_of!(usb_device_id, bDeviceSubClass));
    DEFINE!(OFF_usb_device_id_bDeviceProtocol, core::mem::offset_of!(usb_device_id, bDeviceProtocol));
    DEFINE!(OFF_usb_device_id_bInterfaceClass, core::mem::offset_of!(usb_device_id, bInterfaceClass));
    DEFINE!(OFF_usb_device_id_bInterfaceSubClass, core::mem::offset_of!(usb_device_id, bInterfaceSubClass));
    DEFINE!(OFF_usb_device_id_bInterfaceProtocol, core::mem::offset_of!(usb_device_id, bInterfaceProtocol));
    DEFINE!(OFF_usb_device_id_bInterfaceNumber, core::mem::offset_of!(usb_device_id, bInterfaceNumber));

    DEFINE!(SIZE_hid_device_id, core::mem::size_of::<hid_device_id>());
    DEFINE!(OFF_hid_device_id_bus, core::mem::offset_of!(hid_device_id, bus));
    DEFINE!(OFF_hid_device_id_group, core::mem::offset_of!(hid_device_id, group));
    DEFINE!(OFF_hid_device_id_vendor, core::mem::offset_of!(hid_device_id, vendor));
    DEFINE!(OFF_hid_device_id_product, core::mem::offset_of!(hid_device_id, product));

    DEFINE!(SIZE_ieee1394_device_id, core::mem::size_of::<ieee1394_device_id>());
    DEFINE!(OFF_ieee1394_device_id_match_flags, core::mem::offset_of!(ieee1394_device_id, match_flags));
    DEFINE!(OFF_ieee1394_device_id_vendor_id, core::mem::offset_of!(ieee1394_device_id, vendor_id));
    DEFINE!(OFF_ieee1394_device_id_model_id, core::mem::offset_of!(ieee1394_device_id, model_id));
    DEFINE!(OFF_ieee1394_device_id_specifier_id, core::mem::offset_of!(ieee1394_device_id, specifier_id));
    DEFINE!(OFF_ieee1394_device_id_version, core::mem::offset_of!(ieee1394_device_id, version));

    DEFINE!(SIZE_pci_device_id, core::mem::size_of::<pci_device_id>());
    DEFINE!(OFF_pci_device_id_vendor, core::mem::offset_of!(pci_device_id, vendor));
    DEFINE!(OFF_pci_device_id_device, core::mem::offset_of!(pci_device_id, device));
    DEFINE!(OFF_pci_device_id_subvendor, core::mem::offset_of!(pci_device_id, subvendor));
    DEFINE!(OFF_pci_device_id_subdevice, core::mem::offset_of!(pci_device_id, subdevice));
    DEFINE!(OFF_pci_device_id_class, core::mem::offset_of!(pci_device_id, class));
    DEFINE!(OFF_pci_device_id_class_mask, core::mem::offset_of!(pci_device_id, class_mask));
    DEFINE!(OFF_pci_device_id_override_only, core::mem::offset_of!(pci_device_id, override_only));

    DEFINE!(SIZE_ccw_device_id, core::mem::size_of::<ccw_device_id>());
    DEFINE!(OFF_ccw_device_id_match_flags, core::mem::offset_of!(ccw_device_id, match_flags));
    DEFINE!(OFF_ccw_device_id_cu_type, core::mem::offset_of!(ccw_device_id, cu_type));
    DEFINE!(OFF_ccw_device_id_cu_model, core::mem::offset_of!(ccw_device_id, cu_model));
    DEFINE!(OFF_ccw_device_id_dev_type, core::mem::offset_of!(ccw_device_id, dev_type));
    DEFINE!(OFF_ccw_device_id_dev_model, core::mem::offset_of!(ccw_device_id, dev_model));
    DEFINE!(SIZE_ap_device_id, core::mem::size_of::<ap_device_id>());
    DEFINE!(OFF_ap_device_id_dev_type, core::mem::offset_of!(ap_device_id, dev_type));
    DEFINE!(SIZE_css_device_id, core::mem::size_of::<css_device_id>());
    DEFINE!(OFF_css_device_id_type, core::mem::offset_of!(css_device_id, type));
    DEFINE!(SIZE_serio_device_id, core::mem::size_of::<serio_device_id>());
    DEFINE!(OFF_serio_device_id_type, core::mem::offset_of!(serio_device_id, type));
    DEFINE!(OFF_serio_device_id_proto, core::mem::offset_of!(serio_device_id, proto));
    DEFINE!(OFF_serio_device_id_id, core::mem::offset_of!(serio_device_id, id));
    DEFINE!(OFF_serio_device_id_extra, core::mem::offset_of!(serio_device_id, extra));
    DEFINE!(SIZE_acpi_device_id, core::mem::size_of::<acpi_device_id>());
    DEFINE!(OFF_acpi_device_id_id, core::mem::offset_of!(acpi_device_id, id));
    DEFINE!(OFF_acpi_device_id_cls, core::mem::offset_of!(acpi_device_id, cls));
    DEFINE!(OFF_acpi_device_id_cls_msk, core::mem::offset_of!(acpi_device_id, cls_msk));
    DEFINE!(SIZE_pnp_device_id, core::mem::size_of::<pnp_device_id>());
    DEFINE!(OFF_pnp_device_id_id, core::mem::offset_of!(pnp_device_id, id));
    DEFINE!(SIZE_pnp_card_device_id, core::mem::size_of::<pnp_card_device_id>());
    DEFINE!(OFF_pnp_card_device_id_devs, core::mem::offset_of!(pnp_card_device_id, devs));
    DEFINE!(SIZE_pcmcia_device_id, core::mem::size_of::<pcmcia_device_id>());
    DEFINE!(OFF_pcmcia_device_id_match_flags, core::mem::offset_of!(pcmcia_device_id, match_flags));
    DEFINE!(OFF_pcmcia_device_id_manf_id, core::mem::offset_of!(pcmcia_device_id, manf_id));
    DEFINE!(OFF_pcmcia_device_id_card_id, core::mem::offset_of!(pcmcia_device_id, card_id));
    DEFINE!(OFF_pcmcia_device_id_func_id, core::mem::offset_of!(pcmcia_device_id, func_id));
    DEFINE!(OFF_pcmcia_device_id_function, core::mem::offset_of!(pcmcia_device_id, function));
    DEFINE!(OFF_pcmcia_device_id_device_no, core::mem::offset_of!(pcmcia_device_id, device_no));
    DEFINE!(OFF_pcmcia_device_id_prod_id_hash, core::mem::offset_of!(pcmcia_device_id, prod_id_hash));
    DEFINE!(SIZE_of_device_id, core::mem::size_of::<of_device_id>());
    DEFINE!(OFF_of_device_id_name, core::mem::offset_of!(of_device_id, name));
    DEFINE!(OFF_of_device_id_type, core::mem::offset_of!(of_device_id, type));
    DEFINE!(OFF_of_device_id_compatible, core::mem::offset_of!(of_device_id, compatible));
    DEFINE!(SIZE_vio_device_id, core::mem::size_of::<vio_device_id>());
    DEFINE!(OFF_vio_device_id_type, core::mem::offset_of!(vio_device_id, type));
    DEFINE!(OFF_vio_device_id_compat, core::mem::offset_of!(vio_device_id, compat));
    DEFINE!(SIZE_input_device_id, core::mem::size_of::<input_device_id>());
    DEFINE!(OFF_input_device_id_flags, core::mem::offset_of!(input_device_id, flags));
    DEFINE!(OFF_input_device_id_bustype, core::mem::offset_of!(input_device_id, bustype));
    DEFINE!(OFF_input_device_id_vendor, core::mem::offset_of!(input_device_id, vendor));
    DEFINE!(OFF_input_device_id_product, core::mem::offset_of!(input_device_id, product));
    DEFINE!(OFF_input_device_id_version, core::mem::offset_of!(input_device_id, version));
    DEFINE!(OFF_input_device_id_evbit, core::mem::offset_of!(input_device_id, evbit));
    DEFINE!(OFF_input_device_id_keybit, core::mem::offset_of!(input_device_id, keybit));
    DEFINE!(OFF_input_device_id_relbit, core::mem::offset_of!(input_device_id, relbit));
    DEFINE!(OFF_input_device_id_absbit, core::mem::offset_of!(input_device_id, absbit));
    DEFINE!(OFF_input_device_id_mscbit, core::mem::offset_of!(input_device_id, mscbit));
    DEFINE!(OFF_input_device_id_ledbit, core::mem::offset_of!(input_device_id, ledbit));
    DEFINE!(OFF_input_device_id_sndbit, core::mem::offset_of!(input_device_id, sndbit));
    DEFINE!(OFF_input_device_id_ffbit, core::mem::offset_of!(input_device_id, ffbit));
    DEFINE!(OFF_input_device_id_swbit, core::mem::offset_of!(input_device_id, swbit));
    DEFINE!(SIZE_eisa_device_id, core::mem::size_of::<eisa_device_id>());
    DEFINE!(OFF_eisa_device_id_sig, core::mem::offset_of!(eisa_device_id, sig));
    DEFINE!(SIZE_parisc_device_id, core::mem::size_of::<parisc_device_id>());
    DEFINE!(OFF_parisc_device_id_hw_type, core::mem::offset_of!(parisc_device_id, hw_type));
    DEFINE!(OFF_parisc_device_id_hversion, core::mem::offset_of!(parisc_device_id, hversion));
    DEFINE!(OFF_parisc_device_id_hversion_rev, core::mem::offset_of!(parisc_device_id, hversion_rev));
    DEFINE!(OFF_parisc_device_id_sversion, core::mem::offset_of!(parisc_device_id, sversion));
    DEFINE!(SIZE_sdio_device_id, core::mem::size_of::<sdio_device_id>());
    DEFINE!(OFF_sdio_device_id_class, core::mem::offset_of!(sdio_device_id, class));
    DEFINE!(OFF_sdio_device_id_vendor, core::mem::offset_of!(sdio_device_id, vendor));
    DEFINE!(OFF_sdio_device_id_device, core::mem::offset_of!(sdio_device_id, device));
    DEFINE!(SIZE_ssb_device_id, core::mem::size_of::<ssb_device_id>());
    DEFINE!(OFF_ssb_device_id_vendor, core::mem::offset_of!(ssb_device_id, vendor));
    DEFINE!(OFF_ssb_device_id_coreid, core::mem::offset_of!(ssb_device_id, coreid));
    DEFINE!(OFF_ssb_device_id_revision, core::mem::offset_of!(ssb_device_id, revision));
    DEFINE!(SIZE_bcma_device_id, core::mem::size_of::<bcma_device_id>());
    DEFINE!(OFF_bcma_device_id_manuf, core::mem::offset_of!(bcma_device_id, manuf));
    DEFINE!(OFF_bcma_device_id_id, core::mem::offset_of!(bcma_device_id, id));
    DEFINE!(OFF_bcma_device_id_rev, core::mem::offset_of!(bcma_device_id, rev));
    DEFINE!(OFF_bcma_device_id_class, core::mem::offset_of!(bcma_device_id, class));
    DEFINE!(SIZE_virtio_device_id, core::mem::size_of::<virtio_device_id>());
    DEFINE!(OFF_virtio_device_id_device, core::mem::offset_of!(virtio_device_id, device));
    DEFINE!(OFF_virtio_device_id_vendor, core::mem::offset_of!(virtio_device_id, vendor));
    DEFINE!(SIZE_hv_vmbus_device_id, core::mem::size_of::<hv_vmbus_device_id>());
    DEFINE!(OFF_hv_vmbus_device_id_guid, core::mem::offset_of!(hv_vmbus_device_id, guid));
    DEFINE!(SIZE_rpmsg_device_id, core::mem::size_of::<rpmsg_device_id>());
    DEFINE!(OFF_rpmsg_device_id_name, core::mem::offset_of!(rpmsg_device_id, name));
    DEFINE!(SIZE_i2c_device_id, core::mem::size_of::<i2c_device_id>());
    DEFINE!(OFF_i2c_device_id_name, core::mem::offset_of!(i2c_device_id, name));
    DEFINE!(SIZE_i3c_device_id, core::mem::size_of::<i3c_device_id>());
    DEFINE!(OFF_i3c_device_id_match_flags, core::mem::offset_of!(i3c_device_id, match_flags));
    DEFINE!(OFF_i3c_device_id_dcr, core::mem::offset_of!(i3c_device_id, dcr));
    DEFINE!(OFF_i3c_device_id_manuf_id, core::mem::offset_of!(i3c_device_id, manuf_id));
    DEFINE!(OFF_i3c_device_id_part_id, core::mem::offset_of!(i3c_device_id, part_id));
    DEFINE!(OFF_i3c_device_id_extra_info, core::mem::offset_of!(i3c_device_id, extra_info));
    DEFINE!(SIZE_slim_device_id, core::mem::size_of::<slim_device_id>());
    DEFINE!(OFF_slim_device_id_manf_id, core::mem::offset_of!(slim_device_id, manf_id));
    DEFINE!(OFF_slim_device_id_prod_code, core::mem::offset_of!(slim_device_id, prod_code));
    DEFINE!(SIZE_spi_device_id, core::mem::size_of::<spi_device_id>());
    DEFINE!(OFF_spi_device_id_name, core::mem::offset_of!(spi_device_id, name));
    DEFINE!(SIZE_dmi_system_id, core::mem::size_of::<dmi_system_id>());
    DEFINE!(OFF_dmi_system_id_matches, core::mem::offset_of!(dmi_system_id, matches));
    DEFINE!(SIZE_platform_device_id, core::mem::size_of::<platform_device_id>());
    DEFINE!(OFF_platform_device_id_name, core::mem::offset_of!(platform_device_id, name));
    DEFINE!(SIZE_mdio_device_id, core::mem::size_of::<mdio_device_id>());
    DEFINE!(OFF_mdio_device_id_phy_id, core::mem::offset_of!(mdio_device_id, phy_id));
    DEFINE!(OFF_mdio_device_id_phy_id_mask, core::mem::offset_of!(mdio_device_id, phy_id_mask));
    DEFINE!(SIZE_zorro_device_id, core::mem::size_of::<zorro_device_id>());
    DEFINE!(OFF_zorro_device_id_id, core::mem::offset_of!(zorro_device_id, id));
    DEFINE!(SIZE_isapnp_device_id, core::mem::size_of::<isapnp_device_id>());
    DEFINE!(OFF_isapnp_device_id_vendor, core::mem::offset_of!(isapnp_device_id, vendor));
    DEFINE!(OFF_isapnp_device_id_function, core::mem::offset_of!(isapnp_device_id, function));
    DEFINE!(SIZE_ipack_device_id, core::mem::size_of::<ipack_device_id>());
    DEFINE!(OFF_ipack_device_id_format, core::mem::offset_of!(ipack_device_id, format));
    DEFINE!(OFF_ipack_device_id_vendor, core::mem::offset_of!(ipack_device_id, vendor));
    DEFINE!(OFF_ipack_device_id_device, core::mem::offset_of!(ipack_device_id, device));
    DEFINE!(SIZE_amba_id, core::mem::size_of::<amba_id>());
    DEFINE!(OFF_amba_id_id, core::mem::offset_of!(amba_id, id));
    DEFINE!(OFF_amba_id_mask, core::mem::offset_of!(amba_id, mask));
    DEFINE!(SIZE_mips_cdmm_device_id, core::mem::size_of::<mips_cdmm_device_id>());
    DEFINE!(OFF_mips_cdmm_device_id_type, core::mem::offset_of!(mips_cdmm_device_id, type));
    DEFINE!(SIZE_x86_cpu_id, core::mem::size_of::<x86_cpu_id>());
    DEFINE!(OFF_x86_cpu_id_feature, core::mem::offset_of!(x86_cpu_id, feature));
    DEFINE!(OFF_x86_cpu_id_family, core::mem::offset_of!(x86_cpu_id, family));
    DEFINE!(OFF_x86_cpu_id_model, core::mem::offset_of!(x86_cpu_id, model));
    DEFINE!(OFF_x86_cpu_id_vendor, core::mem::offset_of!(x86_cpu_id, vendor));
    DEFINE!(SIZE_cpu_feature, core::mem::size_of::<cpu_feature>());
    DEFINE!(OFF_cpu_feature_feature, core::mem::offset_of!(cpu_feature, feature));
    DEFINE!(SIZE_mcb_device_id, core::mem::size_of::<mcb_device_id>());
    DEFINE!(OFF_mcb_device_id_device, core::mem::offset_of!(mcb_device_id, device));
    DEFINE!(SIZE_mei_cl_device_id, core::mem::size_of::<mei_cl_device_id>());
    DEFINE!(OFF_mei_cl_device_id_name, core::mem::offset_of!(mei_cl_device_id, name));
    DEFINE!(OFF_mei_cl_device_id_uuid, core::mem::offset_of!(mei_cl_device_id, uuid));
    DEFINE!(OFF_mei_cl_device_id_version, core::mem::offset_of!(mei_cl_device_id, version));
    DEFINE!(SIZE_rio_device_id, core::mem::size_of::<rio_device_id>());
    DEFINE!(OFF_rio_device_id_did, core::mem::offset_of!(rio_device_id, did));
    DEFINE!(OFF_rio_device_id_vid, core::mem::offset_of!(rio_device_id, vid));
    DEFINE!(OFF_rio_device_id_asm_did, core::mem::offset_of!(rio_device_id, asm_did));
    DEFINE!(OFF_rio_device_id_asm_vid, core::mem::offset_of!(rio_device_id, asm_vid));
    DEFINE!(SIZE_ulpi_device_id, core::mem::size_of::<ulpi_device_id>());
    DEFINE!(OFF_ulpi_device_id_vendor, core::mem::offset_of!(ulpi_device_id, vendor));
    DEFINE!(OFF_ulpi_device_id_product, core::mem::offset_of!(ulpi_device_id, product));
    DEFINE!(SIZE_hda_device_id, core::mem::size_of::<hda_device_id>());
    DEFINE!(OFF_hda_device_id_vendor_id, core::mem::offset_of!(hda_device_id, vendor_id));
    DEFINE!(OFF_hda_device_id_rev_id, core::mem::offset_of!(hda_device_id, rev_id));
    DEFINE!(OFF_hda_device_id_api_version, core::mem::offset_of!(hda_device_id, api_version));
    DEFINE!(SIZE_sdw_device_id, core::mem::size_of::<sdw_device_id>());
    DEFINE!(OFF_sdw_device_id_mfg_id, core::mem::offset_of!(sdw_device_id, mfg_id));
    DEFINE!(OFF_sdw_device_id_part_id, core::mem::offset_of!(sdw_device_id, part_id));
    DEFINE!(OFF_sdw_device_id_sdw_version, core::mem::offset_of!(sdw_device_id, sdw_version));
    DEFINE!(OFF_sdw_device_id_class_id, core::mem::offset_of!(sdw_device_id, class_id));
    DEFINE!(SIZE_fsl_mc_device_id, core::mem::size_of::<fsl_mc_device_id>());
    DEFINE!(OFF_fsl_mc_device_id_vendor, core::mem::offset_of!(fsl_mc_device_id, vendor));
    DEFINE!(OFF_fsl_mc_device_id_obj_type, core::mem::offset_of!(fsl_mc_device_id, obj_type));
    DEFINE!(SIZE_tb_service_id, core::mem::size_of::<tb_service_id>());
    DEFINE!(OFF_tb_service_id_match_flags, core::mem::offset_of!(tb_service_id, match_flags));
    DEFINE!(OFF_tb_service_id_protocol_key, core::mem::offset_of!(tb_service_id, protocol_key));
    DEFINE!(OFF_tb_service_id_protocol_id, core::mem::offset_of!(tb_service_id, protocol_id));
    DEFINE!(OFF_tb_service_id_protocol_version, core::mem::offset_of!(tb_service_id, protocol_version));
    DEFINE!(OFF_tb_service_id_protocol_revision, core::mem::offset_of!(tb_service_id, protocol_revision));
    DEFINE!(SIZE_typec_device_id, core::mem::size_of::<typec_device_id>());
    DEFINE!(OFF_typec_device_id_svid, core::mem::offset_of!(typec_device_id, svid));
    DEFINE!(SIZE_tee_client_device_id, core::mem::size_of::<tee_client_device_id>());
    DEFINE!(OFF_tee_client_device_id_uuid, core::mem::offset_of!(tee_client_device_id, uuid));
    DEFINE!(SIZE_wmi_device_id, core::mem::size_of::<wmi_device_id>());
    DEFINE!(OFF_wmi_device_id_guid_string, core::mem::offset_of!(wmi_device_id, guid_string));
    DEFINE!(SIZE_mhi_device_id, core::mem::size_of::<mhi_device_id>());
    DEFINE!(OFF_mhi_device_id_chan, core::mem::offset_of!(mhi_device_id, chan));
    DEFINE!(SIZE_auxiliary_device_id, core::mem::size_of::<auxiliary_device_id>());
    DEFINE!(OFF_auxiliary_device_id_name, core::mem::offset_of!(auxiliary_device_id, name));
    DEFINE!(SIZE_ssam_device_id, core::mem::size_of::<ssam_device_id>());
    DEFINE!(OFF_ssam_device_id_match_flags, core::mem::offset_of!(ssam_device_id, match_flags));
    DEFINE!(OFF_ssam_device_id_domain, core::mem::offset_of!(ssam_device_id, domain));
    DEFINE!(OFF_ssam_device_id_category, core::mem::offset_of!(ssam_device_id, category));
    DEFINE!(OFF_ssam_device_id_target, core::mem::offset_of!(ssam_device_id, target));
    DEFINE!(OFF_ssam_device_id_instance, core::mem::offset_of!(ssam_device_id, instance));
    DEFINE!(OFF_ssam_device_id_function, core::mem::offset_of!(ssam_device_id, function));
    DEFINE!(SIZE_dfl_device_id, core::mem::size_of::<dfl_device_id>());
    DEFINE!(OFF_dfl_device_id_type, core::mem::offset_of!(dfl_device_id, type));
    DEFINE!(OFF_dfl_device_id_feature_id, core::mem::offset_of!(dfl_device_id, feature_id));
    DEFINE!(SIZE_ishtp_device_id, core::mem::size_of::<ishtp_device_id>());
    DEFINE!(OFF_ishtp_device_id_guid, core::mem::offset_of!(ishtp_device_id, guid));
    DEFINE!(SIZE_cdx_device_id, core::mem::size_of::<cdx_device_id>());
    DEFINE!(OFF_cdx_device_id_vendor, core::mem::offset_of!(cdx_device_id, vendor));
    DEFINE!(OFF_cdx_device_id_device, core::mem::offset_of!(cdx_device_id, device));
    DEFINE!(OFF_cdx_device_id_subvendor, core::mem::offset_of!(cdx_device_id, subvendor));
    DEFINE!(OFF_cdx_device_id_subdevice, core::mem::offset_of!(cdx_device_id, subdevice));
    DEFINE!(OFF_cdx_device_id_class, core::mem::offset_of!(cdx_device_id, class));
    DEFINE!(OFF_cdx_device_id_class_mask, core::mem::offset_of!(cdx_device_id, class_mask));
    DEFINE!(OFF_cdx_device_id_override_only, core::mem::offset_of!(cdx_device_id, override_only));
    DEFINE!(SIZE_vchiq_device_id, core::mem::size_of::<vchiq_device_id>());
    DEFINE!(OFF_vchiq_device_id_name, core::mem::offset_of!(vchiq_device_id, name));
    DEFINE!(SIZE_coreboot_device_id, core::mem::size_of::<coreboot_device_id>());
    DEFINE!(OFF_coreboot_device_id_tag, core::mem::offset_of!(coreboot_device_id, tag));
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
