// SPDX-License-Identifier: GPL-2.0
// Translated from trace/events/mce.h.
// The Linux tracepoint includes and tracepoint-generation macros are supplied
// by the surrounding kernel translation.

/// MCE event record entry generated by `TRACE_EVENT(mce_record)`.
#[repr(C)]
pub struct MceRecordEntry {
    pub mcgcap: u64,
    pub mcgstatus: u64,
    pub status: u64,
    pub addr: u64,
    pub misc: u64,
    pub synd: u64,
    pub ipid: u64,
    pub ip: u64,
    pub tsc: u64,
    pub ppin: u64,
    pub walltime: u64,
    pub cpu: u32,
    pub cpuid: u32,
    pub apicid: u32,
    pub socketid: u32,
    pub cs: u8,
    pub bank: u8,
    pub cpuvendor: u8,
    pub microcode: u32,
    // C's dynamic array: `u8 v_data[sizeof(err->vendor)]`.
    pub v_data: [u8; 0],
}

/// Direct translation of the `TP_fast_assign` portion of `mce_record`.
/// `crate::mce_hw_err` is supplied by the translated architecture dependency.
pub unsafe fn mce_record_fast_assign(
    entry: *mut MceRecordEntry,
    err: *const crate::mce_hw_err,
) {
    (*entry).mcgcap = (*err).m.mcgcap;
    (*entry).mcgstatus = (*err).m.mcgstatus;
    (*entry).status = (*err).m.status;
    (*entry).addr = (*err).m.addr;
    (*entry).misc = (*err).m.misc;
    (*entry).synd = (*err).m.synd;
    (*entry).ipid = (*err).m.ipid;
    (*entry).ip = (*err).m.ip;
    (*entry).tsc = (*err).m.tsc;
    (*entry).ppin = (*err).m.ppin;
    (*entry).walltime = (*err).m.time;
    (*entry).cpu = (*err).m.extcpu;
    (*entry).cpuid = (*err).m.cpuid;
    (*entry).apicid = (*err).m.apicid;
    (*entry).socketid = (*err).m.socketid;
    (*entry).cs = (*err).m.cs;
    (*entry).bank = (*err).m.bank;
    (*entry).cpuvendor = (*err).m.cpuvendor;
    (*entry).microcode = (*err).m.microcode;

    // C: memcpy(__get_dynamic_array(v_data), &err->vendor, sizeof(err->vendor));
    core::ptr::copy_nonoverlapping(
        core::ptr::addr_of!((*err).vendor).cast::<u8>(),
        (*entry).v_data.as_mut_ptr(),
        core::mem::size_of_val(&(*err).vendor),
    );
}

// TP_printk format preserved from the source:
// "CPU: %d, MCGc/s: %llx/%llx, MC%d: %016llx, IPID: %016llx, ADDR: %016llx,
//  MISC: %016llx, SYND: %016llx, RIP: %02x:<%016llx>, TSC: %llx, PPIN: %llx,
//  vendor: %u, CPUID: %x, time: %llu, socket: %u, APIC: %x, microcode: %x,
//  vendor data: %s"


// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
