// SPDX-License-Identifier: LGPL-2.1
/*
 * trace/beauty/x86_msr.c
 *
 *  Copyright (C) 2019, Red Hat Inc, Arnaldo Carvalho de Melo <acme@redhat.com>
 */

/* Depends on trace/beauty/beauty.h. */
/* Depends on trace/beauty/generated/x86_arch_MSRs_array.c. */

use core::ffi::{c_char, c_ulong};

#[repr(C)]
pub struct strarray {
    _private: [u8; 0],
}

#[repr(C)]
pub struct strarrays {
    _private: [u8; 0],
}

#[repr(C)]
pub struct syscall_arg {
    pub val: c_ulong,
    pub show_string_prefix: bool,
}

pub type size_t = usize;
pub type u64 = core::ffi::c_ulonglong;

unsafe extern "C" {
    /*
     * Generated by DEFINE_STRARRAY(x86_MSRs, "MSR_") and
     * DEFINE_STRARRAY_OFFSET(..., "MSR_", ...), using data from
     * trace/beauty/generated/x86_arch_MSRs_array.c.
     */
    static mut strarray__x86_MSRs: strarray;
    static mut strarray__x86_64_specific_MSRs: strarray;
    static mut strarray__x86_AMD_V_KVM_MSRs: strarray;

    fn strarrays__scnprintf(
        sas: *const strarrays,
        bf: *mut c_char,
        size: size_t,
        fmt: *const c_char,
        show_prefix: bool,
        val: c_ulong,
    ) -> size_t;

    fn strarrays__strtoul(
        sas: *const strarrays,
        bf: *mut c_char,
        size: size_t,
        ret: *mut u64,
    ) -> bool;
}

static mut x86_MSRs_tables: [*mut strarray; 3] = [
    unsafe { &raw mut strarray__x86_MSRs },
    unsafe { &raw mut strarray__x86_64_specific_MSRs },
    unsafe { &raw mut strarray__x86_AMD_V_KVM_MSRs },
];

/*
 * Generated by DEFINE_STRARRAYS(x86_MSRs_tables), backed by the local
 * x86_MSRs_tables array above.
 */
unsafe extern "C" {
    static strarrays__x86_MSRs_tables: strarrays;
}

unsafe fn x86_MSR__scnprintf(
    msr: c_ulong,
    bf: *mut c_char,
    size: size_t,
    show_prefix: bool,
) -> size_t {
    unsafe {
        strarrays__scnprintf(
            &raw const strarrays__x86_MSRs_tables,
            bf,
            size,
            c"%#x".as_ptr(),
            show_prefix,
            msr,
        )
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn syscall_arg__scnprintf_x86_MSR(
    bf: *mut c_char,
    size: size_t,
    arg: *mut syscall_arg,
) -> size_t {
    let flags: c_ulong = unsafe { (*arg).val };

    unsafe { x86_MSR__scnprintf(flags, bf, size, (*arg).show_string_prefix) }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn syscall_arg__strtoul_x86_MSR(
    bf: *mut c_char,
    size: size_t,
    _arg: *mut syscall_arg,
    ret: *mut u64,
) -> bool {
    unsafe { strarrays__strtoul(&raw const strarrays__x86_MSRs_tables, bf, size, ret) }
}

// SOURCE-COMMIT: 08dbfad3f5040f5bdb6c529da20d6d4e81fefd72
