/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Defines for Mobile Industry Processor Interface (MIPI(R))
 * Display Working Group standards: DSI, DCS, DBI, DPI
 *
 * Copyright (C) 2010 Guennadi Liakhovetski <g.liakhovetski@gmx.de>
 * Copyright (C) 2006 Nokia Corporation
 * Author: Imre Deak <imre.deak@nokia.com>
 */

/* MIPI DSI Processor-to-Peripheral transaction types */
pub const MIPI_DSI_V_SYNC_START: i32 = 0x01;
pub const MIPI_DSI_V_SYNC_END: i32 = 0x11;
pub const MIPI_DSI_H_SYNC_START: i32 = 0x21;
pub const MIPI_DSI_H_SYNC_END: i32 = 0x31;
pub const MIPI_DSI_COMPRESSION_MODE: i32 = 0x07;
pub const MIPI_DSI_END_OF_TRANSMISSION: i32 = 0x08;
pub const MIPI_DSI_COLOR_MODE_OFF: i32 = 0x02;
pub const MIPI_DSI_COLOR_MODE_ON: i32 = 0x12;
pub const MIPI_DSI_SHUTDOWN_PERIPHERAL: i32 = 0x22;
pub const MIPI_DSI_TURN_ON_PERIPHERAL: i32 = 0x32;
pub const MIPI_DSI_GENERIC_SHORT_WRITE_0_PARAM: i32 = 0x03;
pub const MIPI_DSI_GENERIC_SHORT_WRITE_1_PARAM: i32 = 0x13;
pub const MIPI_DSI_GENERIC_SHORT_WRITE_2_PARAM: i32 = 0x23;
pub const MIPI_DSI_GENERIC_READ_REQUEST_0_PARAM: i32 = 0x04;
pub const MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM: i32 = 0x14;
pub const MIPI_DSI_GENERIC_READ_REQUEST_2_PARAM: i32 = 0x24;
pub const MIPI_DSI_DCS_SHORT_WRITE: i32 = 0x05;
pub const MIPI_DSI_DCS_SHORT_WRITE_PARAM: i32 = 0x15;
pub const MIPI_DSI_DCS_READ: i32 = 0x06;
pub const MIPI_DSI_EXECUTE_QUEUE: i32 = 0x16;
pub const MIPI_DSI_SET_MAXIMUM_RETURN_PACKET_SIZE: i32 = 0x37;
pub const MIPI_DSI_NULL_PACKET: i32 = 0x09;
pub const MIPI_DSI_BLANKING_PACKET: i32 = 0x19;
pub const MIPI_DSI_GENERIC_LONG_WRITE: i32 = 0x29;
pub const MIPI_DSI_DCS_LONG_WRITE: i32 = 0x39;
pub const MIPI_DSI_PICTURE_PARAMETER_SET: i32 = 0x0a;
pub const MIPI_DSI_COMPRESSED_PIXEL_STREAM: i32 = 0x0b;
pub const MIPI_DSI_LOOSELY_PACKED_PIXEL_STREAM_YCBCR20: i32 = 0x0c;
pub const MIPI_DSI_PACKED_PIXEL_STREAM_YCBCR24: i32 = 0x1c;
pub const MIPI_DSI_PACKED_PIXEL_STREAM_YCBCR16: i32 = 0x2c;
pub const MIPI_DSI_PACKED_PIXEL_STREAM_30: i32 = 0x0d;
pub const MIPI_DSI_PACKED_PIXEL_STREAM_36: i32 = 0x1d;
pub const MIPI_DSI_PACKED_PIXEL_STREAM_YCBCR12: i32 = 0x3d;
pub const MIPI_DSI_PACKED_PIXEL_STREAM_16: i32 = 0x0e;
pub const MIPI_DSI_PACKED_PIXEL_STREAM_18: i32 = 0x1e;
pub const MIPI_DSI_PIXEL_STREAM_3BYTE_18: i32 = 0x2e;
pub const MIPI_DSI_PACKED_PIXEL_STREAM_24: i32 = 0x3e;

/* MIPI DSI Peripheral-to-Processor transaction types */
pub const MIPI_DSI_RX_ACKNOWLEDGE_AND_ERROR_REPORT: i32 = 0x02;
pub const MIPI_DSI_RX_END_OF_TRANSMISSION: i32 = 0x08;
pub const MIPI_DSI_RX_GENERIC_SHORT_READ_RESPONSE_1BYTE: i32 = 0x11;
pub const MIPI_DSI_RX_GENERIC_SHORT_READ_RESPONSE_2BYTE: i32 = 0x12;
pub const MIPI_DSI_RX_GENERIC_LONG_READ_RESPONSE: i32 = 0x1a;
pub const MIPI_DSI_RX_DCS_LONG_READ_RESPONSE: i32 = 0x1c;
pub const MIPI_DSI_RX_DCS_SHORT_READ_RESPONSE_1BYTE: i32 = 0x21;
pub const MIPI_DSI_RX_DCS_SHORT_READ_RESPONSE_2BYTE: i32 = 0x22;

/* MIPI DCS commands */
pub const MIPI_DCS_NOP: i32 = 0x00;
pub const MIPI_DCS_SOFT_RESET: i32 = 0x01;
pub const MIPI_DCS_GET_COMPRESSION_MODE: i32 = 0x03;
pub const MIPI_DCS_GET_DISPLAY_ID: i32 = 0x04;
pub const MIPI_DCS_GET_ERROR_COUNT_ON_DSI: i32 = 0x05;
pub const MIPI_DCS_GET_RED_CHANNEL: i32 = 0x06;
pub const MIPI_DCS_GET_GREEN_CHANNEL: i32 = 0x07;
pub const MIPI_DCS_GET_BLUE_CHANNEL: i32 = 0x08;
pub const MIPI_DCS_GET_DISPLAY_STATUS: i32 = 0x09;
pub const MIPI_DCS_GET_POWER_MODE: i32 = 0x0A;
pub const MIPI_DCS_GET_ADDRESS_MODE: i32 = 0x0B;
pub const MIPI_DCS_GET_PIXEL_FORMAT: i32 = 0x0C;
pub const MIPI_DCS_GET_DISPLAY_MODE: i32 = 0x0D;
pub const MIPI_DCS_GET_SIGNAL_MODE: i32 = 0x0E;
pub const MIPI_DCS_GET_DIAGNOSTIC_RESULT: i32 = 0x0F;
pub const MIPI_DCS_ENTER_SLEEP_MODE: i32 = 0x10;
pub const MIPI_DCS_EXIT_SLEEP_MODE: i32 = 0x11;
pub const MIPI_DCS_ENTER_PARTIAL_MODE: i32 = 0x12;
pub const MIPI_DCS_ENTER_NORMAL_MODE: i32 = 0x13;
pub const MIPI_DCS_GET_IMAGE_CHECKSUM_RGB: i32 = 0x14;
pub const MIPI_DCS_GET_IMAGE_CHECKSUM_CT: i32 = 0x15;
pub const MIPI_DCS_EXIT_INVERT_MODE: i32 = 0x20;
pub const MIPI_DCS_ENTER_INVERT_MODE: i32 = 0x21;
pub const MIPI_DCS_SET_GAMMA_CURVE: i32 = 0x26;
pub const MIPI_DCS_SET_DISPLAY_OFF: i32 = 0x28;
pub const MIPI_DCS_SET_DISPLAY_ON: i32 = 0x29;
pub const MIPI_DCS_SET_COLUMN_ADDRESS: i32 = 0x2A;
pub const MIPI_DCS_SET_PAGE_ADDRESS: i32 = 0x2B;
pub const MIPI_DCS_WRITE_MEMORY_START: i32 = 0x2C;
pub const MIPI_DCS_WRITE_LUT: i32 = 0x2D;
pub const MIPI_DCS_READ_MEMORY_START: i32 = 0x2E;
/* MIPI DCS 1.02 - MIPI_DCS_SET_PARTIAL_AREA before that */
pub const MIPI_DCS_SET_PARTIAL_ROWS: i32 = 0x30;
pub const MIPI_DCS_SET_PARTIAL_COLUMNS: i32 = 0x31;
pub const MIPI_DCS_SET_SCROLL_AREA: i32 = 0x33;
pub const MIPI_DCS_SET_TEAR_OFF: i32 = 0x34;
pub const MIPI_DCS_SET_TEAR_ON: i32 = 0x35;
pub const MIPI_DCS_SET_ADDRESS_MODE: i32 = 0x36;
pub const MIPI_DCS_SET_SCROLL_START: i32 = 0x37;
pub const MIPI_DCS_EXIT_IDLE_MODE: i32 = 0x38;
pub const MIPI_DCS_ENTER_IDLE_MODE: i32 = 0x39;
pub const MIPI_DCS_SET_PIXEL_FORMAT: i32 = 0x3A;
pub const MIPI_DCS_WRITE_MEMORY_CONTINUE: i32 = 0x3C;
pub const MIPI_DCS_SET_3D_CONTROL: i32 = 0x3D;
pub const MIPI_DCS_READ_MEMORY_CONTINUE: i32 = 0x3E;
pub const MIPI_DCS_GET_3D_CONTROL: i32 = 0x3F;
pub const MIPI_DCS_SET_VSYNC_TIMING: i32 = 0x40;
pub const MIPI_DCS_SET_TEAR_SCANLINE: i32 = 0x44;
pub const MIPI_DCS_GET_SCANLINE: i32 = 0x45;
/* MIPI DCS 1.3 */
pub const MIPI_DCS_SET_DISPLAY_BRIGHTNESS: i32 = 0x51;
/* MIPI DCS 1.3 */
pub const MIPI_DCS_GET_DISPLAY_BRIGHTNESS: i32 = 0x52;
/* MIPI DCS 1.3 */
pub const MIPI_DCS_WRITE_CONTROL_DISPLAY: i32 = 0x53;
/* MIPI DCS 1.3 */
pub const MIPI_DCS_GET_CONTROL_DISPLAY: i32 = 0x54;
/* MIPI DCS 1.3 */
pub const MIPI_DCS_WRITE_POWER_SAVE: i32 = 0x55;
/* MIPI DCS 1.3 */
pub const MIPI_DCS_GET_POWER_SAVE: i32 = 0x56;
/* MIPI DCS 1.3 */
pub const MIPI_DCS_SET_CABC_MIN_BRIGHTNESS: i32 = 0x5E;
/* MIPI DCS 1.3 */
pub const MIPI_DCS_GET_CABC_MIN_BRIGHTNESS: i32 = 0x5F;
pub const MIPI_DCS_READ_DDB_START: i32 = 0xA1;
pub const MIPI_DCS_READ_PPS_START: i32 = 0xA2;
pub const MIPI_DCS_READ_DDB_CONTINUE: i32 = 0xA8;
pub const MIPI_DCS_READ_PPS_CONTINUE: i32 = 0xA9;

/* MIPI DCS pixel formats */
pub const MIPI_DCS_PIXEL_FMT_24BIT: i32 = 7;
pub const MIPI_DCS_PIXEL_FMT_18BIT: i32 = 6;
pub const MIPI_DCS_PIXEL_FMT_16BIT: i32 = 5;
pub const MIPI_DCS_PIXEL_FMT_12BIT: i32 = 3;
pub const MIPI_DCS_PIXEL_FMT_8BIT: i32 = 2;
pub const MIPI_DCS_PIXEL_FMT_3BIT: i32 = 1;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
