// SPDX-License-Identifier: GPL-2.0
// Generated by scripts/atomic/gen-atomic-long.sh
// C header guard and includes omitted; referenced atomic types/functions are external dependencies.

#[cfg(CONFIG_64BIT)]
pub type atomic_long_t = atomic64_t;
#[cfg(not(CONFIG_64BIT))]
pub type atomic_long_t = atomic_t;

// ATOMIC_LONG_INIT and atomic_long_cond_read_* select the corresponding atomic64/atomic forms.

macro_rules! atomic_long_dispatch {
    ($(#[$meta:meta])* fn $name:ident($($arg:ident : $ty:ty),*) -> $ret:ty { $body:tt }) => {
        $(#[$meta])* #[inline(always)] pub unsafe fn $name($($arg: $ty),*) -> $ret $body
    };
}

atomic_long_dispatch! { fn raw_atomic_long_read(v: *const atomic_long_t) -> long { if cfg!(CONFIG_64BIT) { raw_atomic64_read(v) } else { raw_atomic_read(v) } } }
atomic_long_dispatch! { fn raw_atomic_long_read_acquire(v: *const atomic_long_t) -> long { if cfg!(CONFIG_64BIT) { raw_atomic64_read_acquire(v) } else { raw_atomic_read_acquire(v) } } }
atomic_long_dispatch! { fn raw_atomic_long_set(v: *mut atomic_long_t, i: long) -> () { if cfg!(CONFIG_64BIT) { raw_atomic64_set(v, i) } else { raw_atomic_set(v, i) } } }
atomic_long_dispatch! { fn raw_atomic_long_set_release(v: *mut atomic_long_t, i: long) -> () { if cfg!(CONFIG_64BIT) { raw_atomic64_set_release(v, i) } else { raw_atomic_set_release(v, i) } } }

macro_rules! atomic_long_bin_void {
    ($($name:ident => ($a64:ident, $a:ident)),* $(,)?) => { $(
        #[inline(always)] pub unsafe fn $name(i: long, v: *mut atomic_long_t) { if cfg!(CONFIG_64BIT) { $a64(i, v) } else { $a(i, v) } }
    )* };
}
macro_rules! atomic_long_bin_ret {
    ($($name:ident => ($a64:ident, $a:ident)),* $(,)?) => { $(
        #[inline(always)] pub unsafe fn $name(i: long, v: *mut atomic_long_t) -> long { if cfg!(CONFIG_64BIT) { $a64(i, v) } else { $a(i, v) } }
    )* };
}
atomic_long_bin_void! {
 raw_atomic_long_add => (raw_atomic64_add, raw_atomic_add), raw_atomic_long_sub => (raw_atomic64_sub, raw_atomic_sub),
 raw_atomic_long_and => (raw_atomic64_and, raw_atomic_and), raw_atomic_long_andnot => (raw_atomic64_andnot, raw_atomic_andnot),
 raw_atomic_long_or => (raw_atomic64_or, raw_atomic_or), raw_atomic_long_xor => (raw_atomic64_xor, raw_atomic_xor),
}
atomic_long_bin_ret! {
 raw_atomic_long_add_return => (raw_atomic64_add_return, raw_atomic_add_return), raw_atomic_long_add_return_acquire => (raw_atomic64_add_return_acquire, raw_atomic_add_return_acquire), raw_atomic_long_add_return_release => (raw_atomic64_add_return_release, raw_atomic_add_return_release), raw_atomic_long_add_return_relaxed => (raw_atomic64_add_return_relaxed, raw_atomic_add_return_relaxed),
 raw_atomic_long_fetch_add => (raw_atomic64_fetch_add, raw_atomic_fetch_add), raw_atomic_long_fetch_add_acquire => (raw_atomic64_fetch_add_acquire, raw_atomic_fetch_add_acquire), raw_atomic_long_fetch_add_release => (raw_atomic64_fetch_add_release, raw_atomic_fetch_add_release), raw_atomic_long_fetch_add_relaxed => (raw_atomic64_fetch_add_relaxed, raw_atomic_fetch_add_relaxed),
 raw_atomic_long_sub_return => (raw_atomic64_sub_return, raw_atomic_sub_return), raw_atomic_long_sub_return_acquire => (raw_atomic64_sub_return_acquire, raw_atomic_sub_return_acquire), raw_atomic_long_sub_return_release => (raw_atomic64_sub_return_release, raw_atomic_sub_return_release), raw_atomic_long_sub_return_relaxed => (raw_atomic64_sub_return_relaxed, raw_atomic_sub_return_relaxed),
 raw_atomic_long_fetch_sub => (raw_atomic64_fetch_sub, raw_atomic_fetch_sub), raw_atomic_long_fetch_sub_acquire => (raw_atomic64_fetch_sub_acquire, raw_atomic_fetch_sub_acquire), raw_atomic_long_fetch_sub_release => (raw_atomic64_fetch_sub_release, raw_atomic_fetch_sub_release), raw_atomic_long_fetch_sub_relaxed => (raw_atomic64_fetch_sub_relaxed, raw_atomic_fetch_sub_relaxed),
 raw_atomic_long_fetch_and => (raw_atomic64_fetch_and, raw_atomic_fetch_and), raw_atomic_long_fetch_and_acquire => (raw_atomic64_fetch_and_acquire, raw_atomic_fetch_and_acquire), raw_atomic_long_fetch_and_release => (raw_atomic64_fetch_and_release, raw_atomic_fetch_and_release), raw_atomic_long_fetch_and_relaxed => (raw_atomic64_fetch_and_relaxed, raw_atomic_fetch_and_relaxed),
 raw_atomic_long_fetch_andnot => (raw_atomic64_fetch_andnot, raw_atomic_fetch_andnot), raw_atomic_long_fetch_andnot_acquire => (raw_atomic64_fetch_andnot_acquire, raw_atomic_fetch_andnot_acquire), raw_atomic_long_fetch_andnot_release => (raw_atomic64_fetch_andnot_release, raw_atomic_fetch_andnot_release), raw_atomic_long_fetch_andnot_relaxed => (raw_atomic64_fetch_andnot_relaxed, raw_atomic_fetch_andnot_relaxed),
 raw_atomic_long_fetch_or => (raw_atomic64_fetch_or, raw_atomic_fetch_or), raw_atomic_long_fetch_or_acquire => (raw_atomic64_fetch_or_acquire, raw_atomic_fetch_or_acquire), raw_atomic_long_fetch_or_release => (raw_atomic64_fetch_or_release, raw_atomic_fetch_or_release), raw_atomic_long_fetch_or_relaxed => (raw_atomic64_fetch_or_relaxed, raw_atomic_fetch_or_relaxed),
 raw_atomic_long_fetch_xor => (raw_atomic64_fetch_xor, raw_atomic_fetch_xor), raw_atomic_long_fetch_xor_acquire => (raw_atomic64_fetch_xor_acquire, raw_atomic_fetch_xor_acquire), raw_atomic_long_fetch_xor_release => (raw_atomic64_fetch_xor_release, raw_atomic_fetch_xor_release), raw_atomic_long_fetch_xor_relaxed => (raw_atomic64_fetch_xor_relaxed, raw_atomic_fetch_xor_relaxed),
}

// Increment/decrement wrappers retain the exact ordering-specific external calls.
macro_rules! atomic_long_unary {
 ($($name:ident => $a64:ident, $a:ident : $ret:ty),* $(,)?) => { $(#[inline(always)] pub unsafe fn $name(v: *mut atomic_long_t) -> $ret { if cfg!(CONFIG_64BIT) { $a64(v) } else { $a(v) } })* };
}
atomic_long_unary! {
 raw_atomic_long_inc => raw_atomic64_inc, raw_atomic_inc : (), raw_atomic_long_inc_return => raw_atomic64_inc_return, raw_atomic_inc_return : long,
 raw_atomic_long_inc_return_acquire => raw_atomic64_inc_return_acquire, raw_atomic_inc_return_acquire : long, raw_atomic_long_inc_return_release => raw_atomic64_inc_return_release, raw_atomic_inc_return_release : long, raw_atomic_long_inc_return_relaxed => raw_atomic64_inc_return_relaxed, raw_atomic_inc_return_relaxed : long,
 raw_atomic_long_fetch_inc => raw_atomic64_fetch_inc, raw_atomic_fetch_inc : long, raw_atomic_long_fetch_inc_acquire => raw_atomic64_fetch_inc_acquire, raw_atomic_fetch_inc_acquire : long, raw_atomic_long_fetch_inc_release => raw_atomic64_fetch_inc_release, raw_atomic_fetch_inc_release : long, raw_atomic_long_fetch_inc_relaxed => raw_atomic64_fetch_inc_relaxed, raw_atomic_fetch_inc_relaxed : long,
 raw_atomic_long_dec => raw_atomic64_dec, raw_atomic_dec : (), raw_atomic_long_dec_return => raw_atomic64_dec_return, raw_atomic_dec_return : long,
 raw_atomic_long_dec_return_acquire => raw_atomic64_dec_return_acquire, raw_atomic_dec_return_acquire : long, raw_atomic_long_dec_return_release => raw_atomic64_dec_return_release, raw_atomic_dec_return_release : long, raw_atomic_long_dec_return_relaxed => raw_atomic64_dec_return_relaxed, raw_atomic_dec_return_relaxed : long,
 raw_atomic_long_fetch_dec => raw_atomic64_fetch_dec, raw_atomic_fetch_dec : long, raw_atomic_long_fetch_dec_acquire => raw_atomic64_fetch_dec_acquire, raw_atomic_fetch_dec_acquire : long, raw_atomic_long_fetch_dec_release => raw_atomic64_fetch_dec_release, raw_atomic_fetch_dec_release : long, raw_atomic_long_fetch_dec_relaxed => raw_atomic64_fetch_dec_relaxed, raw_atomic_fetch_dec_relaxed : long,
}

// Remaining compare/exchange, test, and conditional-update declarations are external wrappers.
// Their signatures preserve the header's pointer and integer intent.
extern "C" {
    pub fn raw_atomic_long_xchg(v: *mut atomic_long_t, new: long) -> long;
    pub fn raw_atomic_long_xchg_acquire(v: *mut atomic_long_t, new: long) -> long;
    pub fn raw_atomic_long_xchg_release(v: *mut atomic_long_t, new: long) -> long;
    pub fn raw_atomic_long_xchg_relaxed(v: *mut atomic_long_t, new: long) -> long;
    pub fn raw_atomic_long_cmpxchg(v: *mut atomic_long_t, old: long, new: long) -> long;
    pub fn raw_atomic_long_cmpxchg_acquire(v: *mut atomic_long_t, old: long, new: long) -> long;
    pub fn raw_atomic_long_cmpxchg_release(v: *mut atomic_long_t, old: long, new: long) -> long;
    pub fn raw_atomic_long_cmpxchg_relaxed(v: *mut atomic_long_t, old: long, new: long) -> long;
    pub fn raw_atomic_long_try_cmpxchg(v: *mut atomic_long_t, old: *mut long, new: long) -> bool;
    pub fn raw_atomic_long_try_cmpxchg_acquire(v: *mut atomic_long_t, old: *mut long, new: long) -> bool;
    pub fn raw_atomic_long_try_cmpxchg_release(v: *mut atomic_long_t, old: *mut long, new: long) -> bool;
    pub fn raw_atomic_long_try_cmpxchg_relaxed(v: *mut atomic_long_t, old: *mut long, new: long) -> bool;
    pub fn raw_atomic_long_sub_and_test(i: long, v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_dec_and_test(v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_inc_and_test(v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_add_negative(i: long, v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_add_negative_acquire(i: long, v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_add_negative_release(i: long, v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_add_negative_relaxed(i: long, v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_fetch_add_unless(v: *mut atomic_long_t, a: long, u: long) -> long;
    pub fn raw_atomic_long_add_unless(v: *mut atomic_long_t, a: long, u: long) -> bool;
    pub fn raw_atomic_long_inc_not_zero(v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_inc_unless_negative(v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_dec_unless_positive(v: *mut atomic_long_t) -> bool;
    pub fn raw_atomic_long_dec_if_positive(v: *mut atomic_long_t) -> long;
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
