// SPDX-License-Identifier: GPL-2.0

use core::ffi::{c_char, c_int, c_uint, c_void};

// Types and functions supplied by the kernel debugfs, seq_file, and ptdump
// interfaces are declared here as external dependencies.
#[repr(C)]
pub struct seq_file {
    pub private: *mut c_void,
}

#[repr(C)]
pub struct ptdump_info {
    _private: [u8; 0],
}

#[repr(C)]
pub struct file_operations {
    _private: [u8; 0],
}

unsafe extern "C" {
    fn ptdump_walk(m: *mut seq_file, info: *mut ptdump_info);
    fn debugfs_create_file(
        name: *const c_char,
        mode: c_uint,
        parent: *mut c_void,
        data: *mut c_void,
        fops: *const file_operations,
    ) -> *mut c_void;

    // Generated by DEFINE_SHOW_ATTRIBUTE(ptdump).
    static ptdump_fops: file_operations;
}

unsafe extern "C" fn ptdump_show(m: *mut seq_file, _v: *mut c_void) -> c_int {
    let info = (*m).private as *mut ptdump_info;

    ptdump_walk(m, info);
    0
}

// __init: this function is intended for initialization-time use.
pub unsafe extern "C" fn ptdump_debugfs_register(
    info: *mut ptdump_info,
    name: *const c_char,
) {
    debugfs_create_file(
        name,
        0o400,
        core::ptr::null_mut(),
        info as *mut c_void,
        &ptdump_fops,
    );
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
