/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Translated from the kernel RTAS header; required kernel types are external dependencies. */

#[repr(usize)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum rtas_function_index {
    RTAS_FNIDX__CHECK_EXCEPTION, RTAS_FNIDX__DISPLAY_CHARACTER, RTAS_FNIDX__EVENT_SCAN,
    RTAS_FNIDX__FREEZE_TIME_BASE, RTAS_FNIDX__GET_POWER_LEVEL, RTAS_FNIDX__GET_SENSOR_STATE,
    RTAS_FNIDX__GET_TERM_CHAR, RTAS_FNIDX__GET_TIME_OF_DAY, RTAS_FNIDX__IBM_ACTIVATE_FIRMWARE,
    RTAS_FNIDX__IBM_CBE_START_PTCAL, RTAS_FNIDX__IBM_CBE_STOP_PTCAL, RTAS_FNIDX__IBM_CHANGE_MSI,
    RTAS_FNIDX__IBM_CLOSE_ERRINJCT, RTAS_FNIDX__IBM_CONFIGURE_BRIDGE, RTAS_FNIDX__IBM_CONFIGURE_CONNECTOR,
    RTAS_FNIDX__IBM_CONFIGURE_KERNEL_DUMP, RTAS_FNIDX__IBM_CONFIGURE_PE, RTAS_FNIDX__IBM_CREATE_PE_DMA_WINDOW,
    RTAS_FNIDX__IBM_DISPLAY_MESSAGE, RTAS_FNIDX__IBM_ERRINJCT, RTAS_FNIDX__IBM_EXTI2C,
    RTAS_FNIDX__IBM_GET_CONFIG_ADDR_INFO, RTAS_FNIDX__IBM_GET_CONFIG_ADDR_INFO2,
    RTAS_FNIDX__IBM_GET_DYNAMIC_SENSOR_STATE, RTAS_FNIDX__IBM_GET_INDICES, RTAS_FNIDX__IBM_GET_RIO_TOPOLOGY,
    RTAS_FNIDX__IBM_GET_SYSTEM_PARAMETER, RTAS_FNIDX__IBM_GET_VPD, RTAS_FNIDX__IBM_GET_XIVE,
    RTAS_FNIDX__IBM_INT_OFF, RTAS_FNIDX__IBM_INT_ON, RTAS_FNIDX__IBM_IO_QUIESCE_ACK,
    RTAS_FNIDX__IBM_LPAR_PERFTOOLS, RTAS_FNIDX__IBM_MANAGE_FLASH_IMAGE, RTAS_FNIDX__IBM_MANAGE_STORAGE_PRESERVATION,
    RTAS_FNIDX__IBM_NMI_INTERLOCK, RTAS_FNIDX__IBM_NMI_REGISTER, RTAS_FNIDX__IBM_OPEN_ERRINJCT,
    RTAS_FNIDX__IBM_OPEN_SRIOV_ALLOW_UNFREEZE, RTAS_FNIDX__IBM_OPEN_SRIOV_MAP_PE_NUMBER, RTAS_FNIDX__IBM_OS_TERM,
    RTAS_FNIDX__IBM_PARTNER_CONTROL, RTAS_FNIDX__IBM_PHYSICAL_ATTESTATION, RTAS_FNIDX__IBM_PLATFORM_DUMP,
    RTAS_FNIDX__IBM_POWER_OFF_UPS, RTAS_FNIDX__IBM_QUERY_INTERRUPT_SOURCE_NUMBER, RTAS_FNIDX__IBM_QUERY_PE_DMA_WINDOW,
    RTAS_FNIDX__IBM_READ_PCI_CONFIG, RTAS_FNIDX__IBM_READ_SLOT_RESET_STATE, RTAS_FNIDX__IBM_READ_SLOT_RESET_STATE2,
    RTAS_FNIDX__IBM_RECEIVE_HVPIPE_MSG, RTAS_FNIDX__IBM_REMOVE_PE_DMA_WINDOW, RTAS_FNIDX__IBM_RESET_PE_DMA_WINDOW,
    RTAS_FNIDX__IBM_SCAN_LOG_DUMP, RTAS_FNIDX__IBM_SEND_HVPIPE_MSG, RTAS_FNIDX__IBM_SET_DYNAMIC_INDICATOR,
    RTAS_FNIDX__IBM_SET_EEH_OPTION, RTAS_FNIDX__IBM_SET_SLOT_RESET, RTAS_FNIDX__IBM_SET_SYSTEM_PARAMETER,
    RTAS_FNIDX__IBM_SET_XIVE, RTAS_FNIDX__IBM_SLOT_ERROR_DETAIL, RTAS_FNIDX__IBM_SUSPEND_ME,
    RTAS_FNIDX__IBM_TUNE_DMA_PARMS, RTAS_FNIDX__IBM_UPDATE_FLASH_64_AND_REBOOT, RTAS_FNIDX__IBM_UPDATE_NODES,
    RTAS_FNIDX__IBM_UPDATE_PROPERTIES, RTAS_FNIDX__IBM_VALIDATE_FLASH_IMAGE, RTAS_FNIDX__IBM_WRITE_PCI_CONFIG,
    RTAS_FNIDX__NVRAM_FETCH, RTAS_FNIDX__NVRAM_STORE, RTAS_FNIDX__POWER_OFF, RTAS_FNIDX__PUT_TERM_CHAR,
    RTAS_FNIDX__QUERY_CPU_STOPPED_STATE, RTAS_FNIDX__READ_PCI_CONFIG, RTAS_FNIDX__RTAS_LAST_ERROR,
    RTAS_FNIDX__SET_INDICATOR, RTAS_FNIDX__SET_POWER_LEVEL, RTAS_FNIDX__SET_TIME_FOR_POWER_ON,
    RTAS_FNIDX__SET_TIME_OF_DAY, RTAS_FNIDX__START_CPU, RTAS_FNIDX__STOP_SELF, RTAS_FNIDX__SYSTEM_REBOOT,
    RTAS_FNIDX__THAW_TIME_BASE, RTAS_FNIDX__WRITE_PCI_CONFIG,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct rtas_fn_handle_t { pub index: rtas_function_index }
pub const fn rtas_fn_handle(index: rtas_function_index) -> rtas_fn_handle_t { rtas_fn_handle_t { index } }

/* Build-time RTAS function handles. */
macro_rules! rtas_handles { ($($n:ident => $i:ident),* $(,)?) => { $(pub const $n: rtas_fn_handle_t = rtas_fn_handle(rtas_function_index::$i);)* }; }
rtas_handles! {
RTAS_FN_CHECK_EXCEPTION=>RTAS_FNIDX__CHECK_EXCEPTION, RTAS_FN_DISPLAY_CHARACTER=>RTAS_FNIDX__DISPLAY_CHARACTER,
RTAS_FN_EVENT_SCAN=>RTAS_FNIDX__EVENT_SCAN, RTAS_FN_FREEZE_TIME_BASE=>RTAS_FNIDX__FREEZE_TIME_BASE,
RTAS_FN_GET_POWER_LEVEL=>RTAS_FNIDX__GET_POWER_LEVEL, RTAS_FN_GET_SENSOR_STATE=>RTAS_FNIDX__GET_SENSOR_STATE,
RTAS_FN_GET_TERM_CHAR=>RTAS_FNIDX__GET_TERM_CHAR, RTAS_FN_GET_TIME_OF_DAY=>RTAS_FNIDX__GET_TIME_OF_DAY,
RTAS_FN_IBM_ACTIVATE_FIRMWARE=>RTAS_FNIDX__IBM_ACTIVATE_FIRMWARE, RTAS_FN_IBM_CBE_START_PTCAL=>RTAS_FNIDX__IBM_CBE_START_PTCAL,
RTAS_FN_IBM_CBE_STOP_PTCAL=>RTAS_FNIDX__IBM_CBE_STOP_PTCAL, RTAS_FN_IBM_CHANGE_MSI=>RTAS_FNIDX__IBM_CHANGE_MSI,
RTAS_FN_IBM_CLOSE_ERRINJCT=>RTAS_FNIDX__IBM_CLOSE_ERRINJCT, RTAS_FN_IBM_CONFIGURE_BRIDGE=>RTAS_FNIDX__IBM_CONFIGURE_BRIDGE,
RTAS_FN_IBM_CONFIGURE_CONNECTOR=>RTAS_FNIDX__IBM_CONFIGURE_CONNECTOR, RTAS_FN_IBM_CONFIGURE_KERNEL_DUMP=>RTAS_FNIDX__IBM_CONFIGURE_KERNEL_DUMP,
RTAS_FN_IBM_CONFIGURE_PE=>RTAS_FNIDX__IBM_CONFIGURE_PE, RTAS_FN_IBM_CREATE_PE_DMA_WINDOW=>RTAS_FNIDX__IBM_CREATE_PE_DMA_WINDOW,
RTAS_FN_IBM_DISPLAY_MESSAGE=>RTAS_FNIDX__IBM_DISPLAY_MESSAGE, RTAS_FN_IBM_ERRINJCT=>RTAS_FNIDX__IBM_ERRINJCT,
RTAS_FN_IBM_EXTI2C=>RTAS_FNIDX__IBM_EXTI2C, RTAS_FN_IBM_GET_CONFIG_ADDR_INFO=>RTAS_FNIDX__IBM_GET_CONFIG_ADDR_INFO,
RTAS_FN_IBM_GET_CONFIG_ADDR_INFO2=>RTAS_FNIDX__IBM_GET_CONFIG_ADDR_INFO2, RTAS_FN_IBM_GET_DYNAMIC_SENSOR_STATE=>RTAS_FNIDX__IBM_GET_DYNAMIC_SENSOR_STATE,
RTAS_FN_IBM_GET_INDICES=>RTAS_FNIDX__IBM_GET_INDICES, RTAS_FN_IBM_GET_RIO_TOPOLOGY=>RTAS_FNIDX__IBM_GET_RIO_TOPOLOGY,
RTAS_FN_IBM_GET_SYSTEM_PARAMETER=>RTAS_FNIDX__IBM_GET_SYSTEM_PARAMETER, RTAS_FN_IBM_GET_VPD=>RTAS_FNIDX__IBM_GET_VPD,
RTAS_FN_IBM_GET_XIVE=>RTAS_FNIDX__IBM_GET_XIVE, RTAS_FN_IBM_INT_OFF=>RTAS_FNIDX__IBM_INT_OFF, RTAS_FN_IBM_INT_ON=>RTAS_FNIDX__IBM_INT_ON,
RTAS_FN_IBM_IO_QUIESCE_ACK=>RTAS_FNIDX__IBM_IO_QUIESCE_ACK, RTAS_FN_IBM_LPAR_PERFTOOLS=>RTAS_FNIDX__IBM_LPAR_PERFTOOLS,
RTAS_FN_IBM_MANAGE_FLASH_IMAGE=>RTAS_FNIDX__IBM_MANAGE_FLASH_IMAGE, RTAS_FN_IBM_MANAGE_STORAGE_PRESERVATION=>RTAS_FNIDX__IBM_MANAGE_STORAGE_PRESERVATION,
RTAS_FN_IBM_NMI_INTERLOCK=>RTAS_FNIDX__IBM_NMI_INTERLOCK, RTAS_FN_IBM_NMI_REGISTER=>RTAS_FNIDX__IBM_NMI_REGISTER,
RTAS_FN_IBM_OPEN_ERRINJCT=>RTAS_FNIDX__IBM_OPEN_ERRINJCT, RTAS_FN_IBM_OPEN_SRIOV_ALLOW_UNFREEZE=>RTAS_FNIDX__IBM_OPEN_SRIOV_ALLOW_UNFREEZE,
RTAS_FN_IBM_OPEN_SRIOV_MAP_PE_NUMBER=>RTAS_FNIDX__IBM_OPEN_SRIOV_MAP_PE_NUMBER, RTAS_FN_IBM_OS_TERM=>RTAS_FNIDX__IBM_OS_TERM,
RTAS_FN_IBM_PARTNER_CONTROL=>RTAS_FNIDX__IBM_PARTNER_CONTROL, RTAS_FN_IBM_PHYSICAL_ATTESTATION=>RTAS_FNIDX__IBM_PHYSICAL_ATTESTATION,
RTAS_FN_IBM_PLATFORM_DUMP=>RTAS_FNIDX__IBM_PLATFORM_DUMP, RTAS_FN_IBM_POWER_OFF_UPS=>RTAS_FNIDX__IBM_POWER_OFF_UPS,
RTAS_FN_IBM_QUERY_INTERRUPT_SOURCE_NUMBER=>RTAS_FNIDX__IBM_QUERY_INTERRUPT_SOURCE_NUMBER, RTAS_FN_IBM_QUERY_PE_DMA_WINDOW=>RTAS_FNIDX__IBM_QUERY_PE_DMA_WINDOW,
RTAS_FN_IBM_READ_PCI_CONFIG=>RTAS_FNIDX__IBM_READ_PCI_CONFIG, RTAS_FN_IBM_READ_SLOT_RESET_STATE=>RTAS_FNIDX__IBM_READ_SLOT_RESET_STATE,
RTAS_FN_IBM_READ_SLOT_RESET_STATE2=>RTAS_FNIDX__IBM_READ_SLOT_RESET_STATE2, RTAS_FN_IBM_RECEIVE_HVPIPE_MSG=>RTAS_FNIDX__IBM_RECEIVE_HVPIPE_MSG,
RTAS_FN_IBM_REMOVE_PE_DMA_WINDOW=>RTAS_FNIDX__IBM_REMOVE_PE_DMA_WINDOW, RTAS_FN_IBM_RESET_PE_DMA_WINDOW=>RTAS_FNIDX__IBM_RESET_PE_DMA_WINDOW,
RTAS_FN_IBM_SCAN_LOG_DUMP=>RTAS_FNIDX__IBM_SCAN_LOG_DUMP, RTAS_FN_IBM_SEND_HVPIPE_MSG=>RTAS_FNIDX__IBM_SEND_HVPIPE_MSG,
RTAS_FN_IBM_SET_DYNAMIC_INDICATOR=>RTAS_FNIDX__IBM_SET_DYNAMIC_INDICATOR, RTAS_FN_IBM_SET_EEH_OPTION=>RTAS_FNIDX__IBM_SET_EEH_OPTION,
RTAS_FN_IBM_SET_SLOT_RESET=>RTAS_FNIDX__IBM_SET_SLOT_RESET, RTAS_FN_IBM_SET_SYSTEM_PARAMETER=>RTAS_FNIDX__IBM_SET_SYSTEM_PARAMETER,
RTAS_FN_IBM_SET_XIVE=>RTAS_FNIDX__IBM_SET_XIVE, RTAS_FN_IBM_SLOT_ERROR_DETAIL=>RTAS_FNIDX__IBM_SLOT_ERROR_DETAIL,
RTAS_FN_IBM_SUSPEND_ME=>RTAS_FNIDX__IBM_SUSPEND_ME, RTAS_FN_IBM_TUNE_DMA_PARMS=>RTAS_FNIDX__IBM_TUNE_DMA_PARMS,
RTAS_FN_IBM_UPDATE_FLASH_64_AND_REBOOT=>RTAS_FNIDX__IBM_UPDATE_FLASH_64_AND_REBOOT, RTAS_FN_IBM_UPDATE_NODES=>RTAS_FNIDX__IBM_UPDATE_NODES,
RTAS_FN_IBM_UPDATE_PROPERTIES=>RTAS_FNIDX__IBM_UPDATE_PROPERTIES, RTAS_FN_IBM_VALIDATE_FLASH_IMAGE=>RTAS_FNIDX__IBM_VALIDATE_FLASH_IMAGE,
RTAS_FN_IBM_WRITE_PCI_CONFIG=>RTAS_FNIDX__IBM_WRITE_PCI_CONFIG, RTAS_FN_NVRAM_FETCH=>RTAS_FNIDX__NVRAM_FETCH,
RTAS_FN_NVRAM_STORE=>RTAS_FNIDX__NVRAM_STORE, RTAS_FN_POWER_OFF=>RTAS_FNIDX__POWER_OFF, RTAS_FN_PUT_TERM_CHAR=>RTAS_FNIDX__PUT_TERM_CHAR,
RTAS_FN_QUERY_CPU_STOPPED_STATE=>RTAS_FNIDX__QUERY_CPU_STOPPED_STATE, RTAS_FN_READ_PCI_CONFIG=>RTAS_FNIDX__READ_PCI_CONFIG,
RTAS_FN_RTAS_LAST_ERROR=>RTAS_FNIDX__RTAS_LAST_ERROR, RTAS_FN_SET_INDICATOR=>RTAS_FNIDX__SET_INDICATOR,
RTAS_FN_SET_POWER_LEVEL=>RTAS_FNIDX__SET_POWER_LEVEL, RTAS_FN_SET_TIME_FOR_POWER_ON=>RTAS_FNIDX__SET_TIME_FOR_POWER_ON,
RTAS_FN_SET_TIME_OF_DAY=>RTAS_FNIDX__SET_TIME_OF_DAY, RTAS_FN_START_CPU=>RTAS_FNIDX__START_CPU, RTAS_FN_STOP_SELF=>RTAS_FNIDX__STOP_SELF,
RTAS_FN_SYSTEM_REBOOT=>RTAS_FNIDX__SYSTEM_REBOOT, RTAS_FN_THAW_TIME_BASE=>RTAS_FNIDX__THAW_TIME_BASE, RTAS_FN_WRITE_PCI_CONFIG=>RTAS_FNIDX__WRITE_PCI_CONFIG,
}

pub const RTAS_UNKNOWN_SERVICE: i32 = -1;
pub const RTAS_INSTANTIATE_MAX: u64 = 1u64 << 30;
pub const RTAS_USER_REGION_SIZE: usize = 64 * 1024;
pub const RTAS_SUCCESS: i32 = 0; pub const RTAS_HARDWARE_ERROR: i32 = -1; pub const RTAS_BUSY: i32 = -2;
pub const RTAS_INVALID_PARAMETER: i32 = -3; pub const RTAS_FUNC_NOT_SUPPORTED: i32 = -5; pub const RTAS_UNEXPECTED_STATE_CHANGE: i32 = -7;
pub const RTAS_EXTENDED_DELAY_MIN: i32 = 9900; pub const RTAS_EXTENDED_DELAY_MAX: i32 = 9905; pub const RTAS_ML_ISOLATION_ERROR: i32 = -9000;
pub const RTAS_SUSPEND_ABORTED: i32 = 9000; pub const RTAS_NOT_SUSPENDABLE: i32 = -9004; pub const RTAS_THREADS_ACTIVE: i32 = -9005; pub const RTAS_OUTSTANDING_COPROC: i32 = -9006;

pub const RTAS_INTERNAL_ERROR:u32=0x80000000; pub const RTAS_EPOW_WARNING:u32=0x40000000; pub const RTAS_HOTPLUG_EVENTS:u32=0x10000000; pub const RTAS_IO_EVENTS:u32=0x08000000; pub const RTAS_HVPIPE_MSG_EVENTS:u32=0x04000000; pub const RTAS_EVENT_SCAN_ALL_EVENTS:u32=0xffffffff;
pub const RTAS_SEVERITY_FATAL:u8=5; pub const RTAS_SEVERITY_ERROR:u8=4; pub const RTAS_SEVERITY_ERROR_SYNC:u8=3; pub const RTAS_SEVERITY_WARNING:u8=2; pub const RTAS_SEVERITY_EVENT:u8=1; pub const RTAS_SEVERITY_NO_ERROR:u8=0;
pub const RTAS_DISP_FULLY_RECOVERED:u8=0; pub const RTAS_DISP_LIMITED_RECOVERY:u8=1; pub const RTAS_DISP_NOT_RECOVERED:u8=2;
pub const RTAS_INITIATOR_UNKNOWN:u8=0; pub const RTAS_INITIATOR_CPU:u8=1; pub const RTAS_INITIATOR_PCI:u8=2; pub const RTAS_INITIATOR_ISA:u8=3; pub const RTAS_INITIATOR_MEMORY:u8=4; pub const RTAS_INITIATOR_POWERMGM:u8=5;
pub const RTAS_TARGET_UNKNOWN:u8=0; pub const RTAS_TARGET_CPU:u8=1; pub const RTAS_TARGET_PCI:u8=2; pub const RTAS_TARGET_ISA:u8=3; pub const RTAS_TARGET_MEMORY:u8=4; pub const RTAS_TARGET_POWERMGM:u8=5;
pub const RTAS_VECTOR_EXTERNAL_INTERRUPT:u32=0x500;

/* Event types and pSeries section identifiers. */
pub const RTAS_TYPE_RETRY:u8=1; pub const RTAS_TYPE_TCE_ERR:u8=2; pub const RTAS_TYPE_INTERN_DEV_FAIL:u8=3; pub const RTAS_TYPE_TIMEOUT:u8=4; pub const RTAS_TYPE_DATA_PARITY:u8=5; pub const RTAS_TYPE_ADDR_PARITY:u8=6; pub const RTAS_TYPE_CACHE_PARITY:u8=7; pub const RTAS_TYPE_ADDR_INVALID:u8=8; pub const RTAS_TYPE_ECC_UNCORR:u8=9; pub const RTAS_TYPE_ECC_CORR:u8=0xa; pub const RTAS_TYPE_EPOW:u8=0x40; pub const RTAS_TYPE_PLATFORM:u8=0xe0; pub const RTAS_TYPE_IO:u8=0xe1; pub const RTAS_TYPE_INFO:u8=0xe2; pub const RTAS_TYPE_DEALLOC:u8=0xe3; pub const RTAS_TYPE_DUMP:u8=0xe4; pub const RTAS_TYPE_HOTPLUG:u8=0xe5; pub const RTAS_TYPE_HVPIPE:u8=0xe6;
pub const RTAS_TYPE_PMGM_POWER_SW_ON:u8=0x60; pub const RTAS_TYPE_PMGM_POWER_SW_OFF:u8=0x61; pub const RTAS_TYPE_PMGM_LID_OPEN:u8=0x62; pub const RTAS_TYPE_PMGM_LID_CLOSE:u8=0x63; pub const RTAS_TYPE_PMGM_SLEEP_BTN:u8=0x64; pub const RTAS_TYPE_PMGM_WAKE_BTN:u8=0x65; pub const RTAS_TYPE_PMGM_BATTERY_WARN:u8=0x66; pub const RTAS_TYPE_PMGM_BATTERY_CRIT:u8=0x67; pub const RTAS_TYPE_PMGM_SWITCH_TO_BAT:u8=0x68; pub const RTAS_TYPE_PMGM_SWITCH_TO_AC:u8=0x69; pub const RTAS_TYPE_PMGM_KBD_OR_MOUSE:u8=0x6a; pub const RTAS_TYPE_PMGM_ENCLOS_OPEN:u8=0x6b; pub const RTAS_TYPE_PMGM_ENCLOS_CLOSED:u8=0x6c; pub const RTAS_TYPE_PMGM_RING_INDICATE:u8=0x6d; pub const RTAS_TYPE_PMGM_LAN_ATTENTION:u8=0x6e; pub const RTAS_TYPE_PMGM_TIME_ALARM:u8=0x6f; pub const RTAS_TYPE_PMGM_CONFIG_CHANGE:u8=0x70; pub const RTAS_TYPE_PMGM_SERVICE_PROC:u8=0x71; pub const RTAS_TYPE_PRRN:u8=0xa0;
pub const RTAS_V6EXT_LOG_FORMAT_EVENT_LOG:u8=14; pub const RTAS_V6EXT_COMPANY_ID_IBM:u32=('I' as u32)<<24 | ('B' as u32)<<16 | ('M' as u32)<<8;
pub const PSERIES_HP_ELOG_RESOURCE_CPU:u16=1; pub const PSERIES_HP_ELOG_RESOURCE_MEM:u16=2; pub const PSERIES_HP_ELOG_RESOURCE_SLOT:u16=3; pub const PSERIES_HP_ELOG_RESOURCE_PHB:u16=4; pub const PSERIES_HP_ELOG_RESOURCE_PMEM:u16=6; pub const PSERIES_HP_ELOG_RESOURCE_DT:u16=7;
pub const PSERIES_HP_ELOG_ACTION_ADD:u16=1; pub const PSERIES_HP_ELOG_ACTION_REMOVE:u16=2; pub const PSERIES_HP_ELOG_ID_DRC_NAME:u16=1; pub const PSERIES_HP_ELOG_ID_DRC_INDEX:u16=2; pub const PSERIES_HP_ELOG_ID_DRC_COUNT:u16=3; pub const PSERIES_HP_ELOG_ID_DRC_IC:u16=4;
pub const RTAS_DEBUG:&str="RTAS: ";
extern "C" {
    pub static mut rtas_flash_term_hook: Option<unsafe extern "C" fn(i32)>;
    pub static mut rtas: rtas_t;
    pub fn get_pseries_errorlog(log:*mut rtas_error_log, section_id:u16)->*mut pseries_errorlog;
    pub fn rtas_get_sensor(sensor:i32,index:i32,state:*mut i32)->i32; pub fn rtas_get_sensor_fast(sensor:i32,index:i32,state:*mut i32)->i32;
    pub fn rtas_get_power_level(domain:i32,level:*mut i32)->i32; pub fn rtas_set_power_level(domain:i32,level:i32,setlevel:*mut i32)->i32;
    pub fn rtas_indicator_present(token:i32,maxindex:*mut i32)->bool; pub fn rtas_set_indicator(indicator:i32,index:i32,new_value:i32)->i32; pub fn rtas_set_indicator_fast(indicator:i32,index:i32,new_value:i32)->i32;
    pub fn rtas_progress(s:*mut core::ffi::c_char, hex:u16); pub fn rtas_ibm_suspend_me(status:*mut i32)->i32; pub fn rtas_error_rc(rc:i32)->i32;
    pub fn rtas_busy_delay_time(status:i32)->u32; pub fn rtas_busy_delay(status:i32)->bool;
    pub fn early_init_dt_scan_rtas(node:usize,uname:*const core::ffi::c_char,depth:i32,data:*mut core::ffi::c_void)->i32;
    pub fn pSeries_log_error(buf:*mut core::ffi::c_char,err_type:u32,fatal:i32);
    pub static mut rtas_data_buf_lock: spinlock_t; pub static mut rtas_data_buf:[core::ffi::c_char;RTAS_DATA_BUF_SIZE]; pub static mut rtas_rmo_buf:usize;
    pub fn rtas_cancel_event_scan(); pub fn pSeries_coalesce_init(); pub fn rtas_initialize(); pub fn read_24x7_sys_info();
}
/* Kernel-provided declarations retained as opaque external types. */
#[repr(C)] pub struct rtas_t { _private: [u8;0] }
#[repr(C)] pub struct rtas_error_log { pub byte1:u8, pub byte2:u8, pub byte3:u8, pub extended_log_length:u32 }
#[repr(C)] pub struct pseries_errorlog { pub id:u16, pub length:u16 }
#[repr(C)] pub struct spinlock_t { _private:[u8;0] }

extern "C" {
    pub fn rtas_function_token(handle: rtas_fn_handle_t) -> i32;
    pub fn rtas_token(service: *const core::ffi::c_char) -> i32;
    pub fn rtas_call(token:i32, nargs:i32, nret:i32, outputs:*mut i32, ...) -> i32;
    pub fn rtas_power_off(); pub fn rtas_halt() -> !; pub fn rtas_restart(cmd:*mut core::ffi::c_char) -> !;
    pub fn rtas_os_term(s:*mut core::ffi::c_char); pub fn rtas_activate_firmware();
    pub fn rtas_get_error_log_max() -> i32; pub fn rtas_give_timebase(); pub fn rtas_take_timebase();
}
#[inline] pub unsafe fn rtas_function_implemented(h:rtas_fn_handle_t)->bool { rtas_function_token(h)!=RTAS_UNKNOWN_SERVICE }
#[inline] pub const fn rtas_config_addr(busno:i32,devfn:i32,reg:i32)->u32 { (((reg & 0xf00) as u32)<<20)|(((busno&0xff) as u32)<<16)|((devfn as u32)<<8)|((reg&0xff) as u32) }
pub const ERR_FLAG_ALREADY_LOGGED:u32=0; pub const ERR_FLAG_BOOT:u32=1; pub const ERR_TYPE_RTAS_LOG:u32=2; pub const ERR_TYPE_KERNEL_PANIC:u32=4; pub const ERR_TYPE_KERNEL_PANIC_GZ:u32=8; pub const ERR_TYPE_MASK:u32=14;
pub const RTAS_ERROR_LOG_MAX:usize=2048; pub const EVENT_SCAN_ALL_EVENTS:u32=0xf0000000; pub const SURVEILLANCE_TOKEN:i32=9000; pub const LOG_NUMBER:usize=64; pub const LOG_NUMBER_MASK:usize=LOG_NUMBER-1; pub const RTAS_DATA_BUF_SIZE:usize=4096; pub const GLOBAL_INTERRUPT_QUEUE:i32=9005;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
