/* SPDX-License-Identifier: GPL-2.0 */

/*
 * C implementation of Buchi automaton, automatically generated by
 * tools/verification/rvgen from the linear temporal logic specification.
 * For further information, see kernel documentation:
 *   Documentation/trace/rv/linear_temporal_logic.rst
 */

// Dependency supplied by the surrounding kernel translation.

pub const MONITOR_NAME: &str = "wakeup";

#[repr(C)]
#[derive(Copy, Clone)]
pub enum ltl_atom {
    LTL_BLOCK_ON_RT_MUTEX,
    LTL_FUTEX_LOCK_PI,
    LTL_RT,
    LTL_USER_THREAD,
    LTL_WOKEN_BY_LOWER_PRIO,
    LTL_WOKEN_BY_SOFTIRQ,
    LTL_NUM_ATOM,
}

// C static_assert: LTL_NUM_ATOM <= RV_MAX_LTL_ATOM.

unsafe extern "C" {
    fn test_bit(nr: ltl_atom, addr: *const core::ffi::c_ulong) -> bool;
    fn __set_bit(nr: usize, addr: *mut core::ffi::c_ulong);
}

#[repr(C)]
pub struct task_struct {
    _private: [u8; 0],
}

#[repr(C)]
pub struct ltl_monitor {
    pub atoms: *mut core::ffi::c_ulong,
    pub states: *mut core::ffi::c_ulong,
}

pub unsafe fn ltl_atom_str(atom: ltl_atom) -> *const core::ffi::c_char {
    static NAMES: [&[u8]; 6] = [
        b"bl_on_rt_mu\0",
        b"fu_lo_pi\0",
        b"rt\0",
        b"us_th\0",
        b"wo_lo_pr\0",
        b"wo_so\0",
    ];

    NAMES[atom as usize].as_ptr() as *const core::ffi::c_char
}

#[repr(C)]
#[derive(Copy, Clone)]
pub enum ltl_buchi_state {
    S0,
    RV_NUM_BA_STATES,
}

// C static_assert: RV_NUM_BA_STATES <= RV_MAX_BA_STATES.

pub unsafe fn ltl_start(_task: *mut task_struct, mon: *mut ltl_monitor) {
    let woken_by_softirq = test_bit(ltl_atom::LTL_WOKEN_BY_SOFTIRQ, (*mon).atoms);
    let woken_by_lower_prio = test_bit(ltl_atom::LTL_WOKEN_BY_LOWER_PRIO, (*mon).atoms);
    let user_thread = test_bit(ltl_atom::LTL_USER_THREAD, (*mon).atoms);
    let rt = test_bit(ltl_atom::LTL_RT, (*mon).atoms);
    let futex_lock_pi = test_bit(ltl_atom::LTL_FUTEX_LOCK_PI, (*mon).atoms);
    let block_on_rt_mutex = test_bit(ltl_atom::LTL_BLOCK_ON_RT_MUTEX, (*mon).atoms);
    let val9 = block_on_rt_mutex || futex_lock_pi;
    let val6 = !woken_by_softirq;
    let val5 = !woken_by_lower_prio;
    let val8 = val5 && val6;
    let val10 = val8 || val9;
    let val3 = !user_thread;
    let val2 = !rt;
    let val4 = val2 || val3;
    let val11 = val4 || val10;

    if val11 {
        __set_bit(ltl_buchi_state::S0 as usize, (*mon).states);
    }
}

pub unsafe fn ltl_possible_next_states(
    mon: *mut ltl_monitor,
    state: u32,
    next: *mut core::ffi::c_ulong,
) {
    let woken_by_softirq = test_bit(ltl_atom::LTL_WOKEN_BY_SOFTIRQ, (*mon).atoms);
    let woken_by_lower_prio = test_bit(ltl_atom::LTL_WOKEN_BY_LOWER_PRIO, (*mon).atoms);
    let user_thread = test_bit(ltl_atom::LTL_USER_THREAD, (*mon).atoms);
    let rt = test_bit(ltl_atom::LTL_RT, (*mon).atoms);
    let futex_lock_pi = test_bit(ltl_atom::LTL_FUTEX_LOCK_PI, (*mon).atoms);
    let block_on_rt_mutex = test_bit(ltl_atom::LTL_BLOCK_ON_RT_MUTEX, (*mon).atoms);
    let val9 = block_on_rt_mutex || futex_lock_pi;
    let val6 = !woken_by_softirq;
    let val5 = !woken_by_lower_prio;
    let val8 = val5 && val6;
    let val10 = val8 || val9;
    let val3 = !user_thread;
    let val2 = !rt;
    let val4 = val2 || val3;
    let val11 = val4 || val10;

    match state {
        x if x == ltl_buchi_state::S0 as u32 => {
            if val11 {
                __set_bit(ltl_buchi_state::S0 as usize, next);
            }
        }
        _ => {}
    }
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
