/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Rust translation of sb1250_mac.h.  Definitions from sb1250_defs.h are external. */

/* The original SIBYTE_HDR_FEATURE conditionals are retained as comments: this
 * header is intended to be compiled in the corresponding platform context. */

macro_rules! _SB_MAKEMASK1 { ($b:expr) => { 1u64 << ($b) }; }
macro_rules! _SB_MAKE64 { ($b:expr) => { $b as u64 }; }
macro_rules! _SB_MAKEMASK { ($n:expr, $s:expr) => { (((1u64 << ($n)) - 1) << ($s)) }; }
macro_rules! _SB_MAKEVALUE { ($x:expr, $s:expr) => { (($x as u64) << ($s)) }; }
macro_rules! _SB_GETVALUE { ($x:expr, $s:expr, $m:expr) => { ((($x as u64) & ($m)) >> ($s)) }; }

macro_rules! field { ($s:ident, $m:ident, $v:ident, $g:ident, $n:expr, $p:expr) => {
    pub const $s: u64 = $p as u64;
    pub const $m: u64 = (((1u64 << $n) - 1) << $p);
    #[inline] pub const fn $v(x: u64) -> u64 { x << $p }
    #[inline] pub const fn $g(x: u64) -> u64 { (x & $m) >> $p }
}; }
macro_rules! bit { ($n:ident, $b:expr) => { pub const $n: u64 = 1u64 << $b; }; }

bit!(M_MAC_RESERVED0,0); bit!(M_MAC_TX_HOLD_SOP_EN,1); bit!(M_MAC_RETRY_EN,2);
bit!(M_MAC_RET_DRPREQ_EN,3); bit!(M_MAC_RET_UFL_EN,4); bit!(M_MAC_BURST_EN,5);
field!(S_MAC_TX_PAUSE,M_MAC_TX_PAUSE_CNT,V_MAC_TX_PAUSE_CNT,G_MAC_TX_PAUSE_CNT,3,6);
pub const K_MAC_TX_PAUSE_CNT_512:u64=0; pub const K_MAC_TX_PAUSE_CNT_1K:u64=1;
pub const K_MAC_TX_PAUSE_CNT_2K:u64=2; pub const K_MAC_TX_PAUSE_CNT_4K:u64=3;
pub const K_MAC_TX_PAUSE_CNT_8K:u64=4; pub const K_MAC_TX_PAUSE_CNT_16K:u64=5;
pub const K_MAC_TX_PAUSE_CNT_32K:u64=6; pub const K_MAC_TX_PAUSE_CNT_64K:u64=7;
pub const V_MAC_TX_PAUSE_CNT_512:u64=V_MAC_TX_PAUSE_CNT(0); pub const V_MAC_TX_PAUSE_CNT_1K:u64=V_MAC_TX_PAUSE_CNT(1);
pub const V_MAC_TX_PAUSE_CNT_2K:u64=V_MAC_TX_PAUSE_CNT(2); pub const V_MAC_TX_PAUSE_CNT_4K:u64=V_MAC_TX_PAUSE_CNT(3);
pub const V_MAC_TX_PAUSE_CNT_8K:u64=V_MAC_TX_PAUSE_CNT(4); pub const V_MAC_TX_PAUSE_CNT_16K:u64=V_MAC_TX_PAUSE_CNT(5);
pub const V_MAC_TX_PAUSE_CNT_32K:u64=V_MAC_TX_PAUSE_CNT(6); pub const V_MAC_TX_PAUSE_CNT_64K:u64=V_MAC_TX_PAUSE_CNT(7);
pub const M_MAC_RESERVED1:u64=_SB_MAKEMASK!(8,9); bit!(M_MAC_AP_STAT_EN,17); bit!(M_MAC_TIMESTAMP,18);
bit!(M_MAC_DRP_ERRPKT_EN,19); bit!(M_MAC_DRP_FCSERRPKT_EN,20); bit!(M_MAC_DRP_CODEERRPKT_EN,21);
bit!(M_MAC_DRP_DRBLERRPKT_EN,22); bit!(M_MAC_DRP_RNTPKT_EN,23); bit!(M_MAC_DRP_OSZPKT_EN,24); bit!(M_MAC_DRP_LENERRPKT_EN,25);
pub const M_MAC_RESERVED3:u64=_SB_MAKEMASK!(6,26); bit!(M_MAC_BYPASS_SEL,32); bit!(M_MAC_HDX_EN,33);
field!(S_MAC_SPEED_SEL,M_MAC_SPEED_SEL,V_MAC_SPEED_SEL,G_MAC_SPEED_SEL,2,34);
pub const K_MAC_SPEED_SEL_10MBPS:u64=0; pub const K_MAC_SPEED_SEL_100MBPS:u64=1; pub const K_MAC_SPEED_SEL_1000MBPS:u64=2; pub const K_MAC_SPEED_SEL_RESERVED:u64=3;
pub const V_MAC_SPEED_SEL_10MBPS:u64=V_MAC_SPEED_SEL(0); pub const V_MAC_SPEED_SEL_100MBPS:u64=V_MAC_SPEED_SEL(1); pub const V_MAC_SPEED_SEL_1000MBPS:u64=V_MAC_SPEED_SEL(2); pub const V_MAC_SPEED_SEL_RESERVED:u64=V_MAC_SPEED_SEL(3);
bit!(M_MAC_TX_CLK_EDGE_SEL,36); bit!(M_MAC_LOOPBACK_SEL,37); bit!(M_MAC_FAST_SYNC,38); bit!(M_MAC_SS_EN,39);
field!(S_MAC_BYPASS_CFG,M_MAC_BYPASS_CFG,V_MAC_BYPASS_CFG,G_MAC_BYPASS_CFG,2,40);
pub const K_MAC_BYPASS_GMII:u64=0; pub const K_MAC_BYPASS_ENCODED:u64=1; pub const K_MAC_BYPASS_SOP:u64=2; pub const K_MAC_BYPASS_EOP:u64=3;
bit!(M_MAC_BYPASS_16,42); bit!(M_MAC_BYPASS_FCS_CHK,43); bit!(M_MAC_RX_CH_SEL_MSB,44); bit!(M_MAC_SPLIT_CH_SEL,45);
field!(S_MAC_BYPASS_IFG,M_MAC_BYPASS_IFG,V_MAC_BYPASS_IFG,G_MAC_BYPASS_IFG,8,46);
pub const K_MAC_FC_CMD_DISABLED:u64=0; pub const K_MAC_FC_CMD_ENABLED:u64=1; pub const K_MAC_FC_CMD_ENAB_FALSECARR:u64=2;
bit!(M_MAC_FC_SEL,54); field!(S_MAC_FC_CMD,M_MAC_FC_CMD,V_MAC_FC_CMD,G_MAC_FC_CMD,2,55);
pub const V_MAC_FC_CMD_DISABLED:u64=V_MAC_FC_CMD(0); pub const V_MAC_FC_CMD_ENABLED:u64=V_MAC_FC_CMD(1); pub const V_MAC_FC_CMD_ENAB_FALSECARR:u64=V_MAC_FC_CMD(2);
field!(S_MAC_RX_CH_SEL,M_MAC_RX_CH_SEL,V_MAC_RX_CH_SEL,G_MAC_RX_CH_SEL,7,57);

bit!(M_MAC_RXDMA_EN0,0); bit!(M_MAC_RXDMA_EN1,1); bit!(M_MAC_TXDMA_EN0,4); bit!(M_MAC_TXDMA_EN1,5); bit!(M_MAC_PORT_RESET,8);
bit!(M_MAC_RX_ENABLE,10); bit!(M_MAC_TX_ENABLE,11); bit!(M_MAC_BYP_RX_ENABLE,12); bit!(M_MAC_BYP_TX_ENABLE,13);
bit!(M_MAC_RX_CH0_PAUSE_ON,8); bit!(M_MAC_RX_CH1_PAUSE_ON,16); bit!(M_MAC_TX_CH0_PAUSE_ON,24); bit!(M_MAC_TX_CH1_PAUSE_ON,32);
field!(S_MAC_TXD_WEIGHT0,M_MAC_TXD_WEIGHT0,V_MAC_TXD_WEIGHT0,G_MAC_TXD_WEIGHT0,4,0); field!(S_MAC_TXD_WEIGHT1,M_MAC_TXD_WEIGHT1,V_MAC_TXD_WEIGHT1,G_MAC_TXD_WEIGHT1,4,4);

/* FIFO thresholds, frame configuration, status, pointer, counter, type and
 * address-filter fields.  The names and bit positions are kept verbatim. */
field!(S_MAC_TX_WR_THRSH,M_MAC_TX_WR_THRSH,V_MAC_TX_WR_THRSH,G_MAC_TX_WR_THRSH,7,0);
field!(S_MAC_TX_RD_THRSH,M_MAC_TX_RD_THRSH,V_MAC_TX_RD_THRSH,G_MAC_TX_RD_THRSH,7,8);
field!(S_MAC_TX_RL_THRSH,M_MAC_TX_RL_THRSH,V_MAC_TX_RL_THRSH,G_MAC_TX_RL_THRSH,4,16);
field!(S_MAC_RX_PL_THRSH,M_MAC_RX_PL_THRSH,V_MAC_RX_PL_THRSH,G_MAC_RX_PL_THRSH,6,24);
field!(S_MAC_RX_RD_THRSH,M_MAC_RX_RD_THRSH,V_MAC_RX_RD_THRSH,G_MAC_RX_RD_THRSH,6,32);
field!(S_MAC_RX_RL_THRSH,M_MAC_RX_RL_THRSH,V_MAC_RX_RL_THRSH,G_MAC_RX_RL_THRSH,6,40);
field!(S_MAC_ENC_FC_THRSH,M_MAC_ENC_FC_THRSH,V_MAC_ENC_FC_THRSH,G_MAC_ENC_FC_THRSH,6,56);
field!(S_MAC_IFG_RX,M_MAC_IFG_RX,V_MAC_IFG_RX,G_MAC_IFG_RX,6,0); field!(S_MAC_PRE_LEN,M_MAC_PRE_LEN,V_MAC_PRE_LEN,G_MAC_PRE_LEN,6,0);
field!(S_MAC_IFG_TX,M_MAC_IFG_TX,V_MAC_IFG_TX,G_MAC_IFG_TX,6,6); field!(S_MAC_IFG_THRSH,M_MAC_IFG_THRSH,V_MAC_IFG_THRSH,G_MAC_IFG_THRSH,6,12);
field!(S_MAC_BACKOFF_SEL,M_MAC_BACKOFF_SEL,V_MAC_BACKOFF_SEL,G_MAC_BACKOFF_SEL,4,18); field!(S_MAC_LFSR_SEED,M_MAC_LFSR_SEED,V_MAC_LFSR_SEED,G_MAC_LFSR_SEED,8,22);
field!(S_MAC_SLOT_SIZE,M_MAC_SLOT_SIZE,V_MAC_SLOT_SIZE,G_MAC_SLOT_SIZE,10,30); field!(S_MAC_MIN_FRAMESZ,M_MAC_MIN_FRAMESZ,V_MAC_MIN_FRAMESZ,G_MAC_MIN_FRAMESZ,8,40); field!(S_MAC_MAX_FRAMESZ,M_MAC_MAX_FRAMESZ,V_MAC_MAX_FRAMESZ,G_MAC_MAX_FRAMESZ,16,48);
pub const K_MAC_IFG_RX_10:u64=0; pub const K_MAC_IFG_RX_100:u64=0; pub const K_MAC_IFG_RX_1000:u64=0; pub const K_MAC_IFG_TX_10:u64=20; pub const K_MAC_IFG_TX_100:u64=20; pub const K_MAC_IFG_TX_1000:u64=8; pub const K_MAC_IFG_THRSH_10:u64=4; pub const K_MAC_IFG_THRSH_100:u64=4; pub const K_MAC_IFG_THRSH_1000:u64=0; pub const K_MAC_SLOT_SIZE_10:u64=0; pub const K_MAC_SLOT_SIZE_100:u64=0; pub const K_MAC_SLOT_SIZE_1000:u64=0;
pub const K_MAC_MIN_FRAMESZ_FIFO:u64=9; pub const K_MAC_MIN_FRAMESZ_DEFAULT:u64=64; pub const K_MAC_MAX_FRAMESZ_DEFAULT:u64=1518; pub const K_MAC_MAX_FRAMESZ_JUMBO:u64=9216;
pub const V_MAC_MIN_FRAMESZ_FIFO:u64=V_MAC_MIN_FRAMESZ(9); pub const V_MAC_MIN_FRAMESZ_DEFAULT:u64=V_MAC_MIN_FRAMESZ(64); pub const V_MAC_MAX_FRAMESZ_DEFAULT:u64=V_MAC_MAX_FRAMESZ(1518); pub const V_MAC_MAX_FRAMESZ_JUMBO:u64=V_MAC_MAX_FRAMESZ(9216);
field!(S_MAC_VLAN_TAG,M_MAC_VLAN_TAG,V_MAC_VLAN_TAG,G_MAC_VLAN_TAG,32,0); field!(S_MAC_TX_PKT_OFFSET,M_MAC_TX_PKT_OFFSET,V_MAC_TX_PKT_OFFSET,G_MAC_TX_PKT_OFFSET,8,32); field!(S_MAC_TX_CRC_OFFSET,M_MAC_TX_CRC_OFFSET,V_MAC_TX_CRC_OFFSET,G_MAC_TX_CRC_OFFSET,8,40); bit!(M_MAC_CH_BASE_FC_EN,48);
pub const S_MAC_RX_CH0:u64=0; pub const S_MAC_RX_CH1:u64=8; pub const S_MAC_TX_CH0:u64=16; pub const S_MAC_TX_CH1:u64=24; pub const S_MAC_TXCHANNELS:u64=16; pub const S_MAC_CHANWIDTH:u64=8;
pub const M_MAC_INT_CHANNEL:u64=_SB_MAKEMASK!(8,0); bit!(M_MAC_INT_EOP_COUNT,0); bit!(M_MAC_INT_EOP_TIMER,1); bit!(M_MAC_INT_EOP_SEEN,2); bit!(M_MAC_INT_HWM,3); bit!(M_MAC_INT_LWM,4); bit!(M_MAC_INT_DSCR,5); bit!(M_MAC_INT_ERR,6); bit!(M_MAC_INT_DZERO,7); bit!(M_MAC_INT_DROP,7);
#[inline] pub const fn S_MAC_STATUS_CH_OFFSET(ch:u64,txrx:u64)->u64 {(ch+2*txrx)*S_MAC_CHANWIDTH}
#[inline] pub const fn M_MAC_STATUS_CHANNEL(ch:u64,txrx:u64)->u64 {_SB_MAKEVALUE!(_SB_MAKEMASK!(8,0),S_MAC_STATUS_CH_OFFSET(ch,txrx))}
macro_rules! status { ($n:ident,$b:ident) => { #[inline] pub const fn $n(ch:u64,txrx:u64)->u64 {_SB_MAKEVALUE!($b,S_MAC_STATUS_CH_OFFSET(ch,txrx))} }; }
status!(M_MAC_STATUS_EOP_COUNT,M_MAC_INT_EOP_COUNT); status!(M_MAC_STATUS_EOP_TIMER,M_MAC_INT_EOP_TIMER); status!(M_MAC_STATUS_EOP_SEEN,M_MAC_INT_EOP_SEEN); status!(M_MAC_STATUS_HWM,M_MAC_INT_HWM); status!(M_MAC_STATUS_LWM,M_MAC_INT_LWM); status!(M_MAC_STATUS_DSCR,M_MAC_INT_DSCR); status!(M_MAC_STATUS_ERR,M_MAC_INT_ERR); status!(M_MAC_STATUS_DZERO,M_MAC_INT_DZERO); status!(M_MAC_STATUS_DROP,M_MAC_INT_DROP);
pub const M_MAC_STATUS_OTHER_ERR:u64=_SB_MAKEVALUE!(_SB_MAKEMASK!(7,0),40); bit!(M_MAC_RX_UNDRFL,40); bit!(M_MAC_RX_OVRFL,41); bit!(M_MAC_TX_UNDRFL,42); bit!(M_MAC_TX_OVRFL,43); bit!(M_MAC_LTCOL_ERR,44); bit!(M_MAC_EXCOL_ERR,45); bit!(M_MAC_CNTR_OVRFL_ERR,46); bit!(M_MAC_SPLIT_EN,47);
field!(S_MAC_COUNTER_ADDR,M_MAC_COUNTER_ADDR,V_MAC_COUNTER_ADDR,G_MAC_COUNTER_ADDR,5,47); bit!(M_MAC_TX_PAUSE_ON,52);
field!(S_MAC_TX_WRPTR,M_MAC_TX_WRPTR,V_MAC_TX_WRPTR,G_MAC_TX_WRPTR,6,0); field!(S_MAC_TX_RDPTR,M_MAC_TX_RDPTR,V_MAC_TX_RDPTR,G_MAC_TX_RDPTR,6,8); field!(S_MAC_RX_WRPTR,M_MAC_RX_WRPTR,V_MAC_RX_WRPTR,G_MAC_RX_WRPTR,6,16); field!(S_MAC_RX_RDPTR,M_MAC_RX_RDPTR,V_MAC_RX_RDPTR,G_MAC_RX_RDPTR,6,24);
field!(S_MAC_TX_EOP_COUNTER,M_MAC_TX_EOP_COUNTER,V_MAC_TX_EOP_COUNTER,G_MAC_TX_EOP_COUNTER,6,0); field!(S_MAC_RX_EOP_COUNTER,M_MAC_RX_EOP_COUNTER,V_MAC_RX_EOP_COUNTER,G_MAC_RX_EOP_COUNTER,6,8);
pub const S_TYPECFG_TYPESIZE:u64=16; field!(S_TYPECFG_TYPE0,M_TYPECFG_TYPE0,V_TYPECFG_TYPE0,G_TYPECFG_TYPE0,16,0); field!(S_TYPECFG_TYPE1,M_TYPECFG_TYPE1,V_TYPECFG_TYPE1,G_TYPECFG_TYPE1,16,0); field!(S_TYPECFG_TYPE2,M_TYPECFG_TYPE2,V_TYPECFG_TYPE2,G_TYPECFG_TYPE2,16,0); field!(S_TYPECFG_TYPE3,M_TYPECFG_TYPE3,V_TYPECFG_TYPE3,G_TYPECFG_TYPE3,16,0);
bit!(M_MAC_ALLPKT_EN,0); bit!(M_MAC_UCAST_EN,1); bit!(M_MAC_UCAST_INV,2); bit!(M_MAC_MCAST_EN,3); bit!(M_MAC_MCAST_INV,4); bit!(M_MAC_BCAST_EN,5); bit!(M_MAC_DIRECT_INV,6); bit!(M_MAC_ALLMCAST_EN,7);
field!(S_MAC_IPHDR_OFFSET,M_MAC_IPHDR_OFFSET,V_MAC_IPHDR_OFFSET,G_MAC_IPHDR_OFFSET,8,8); field!(S_MAC_RX_CRC_OFFSET,M_MAC_RX_CRC_OFFSET,V_MAC_RX_CRC_OFFSET,G_MAC_RX_CRC_OFFSET,8,16); field!(S_MAC_RX_PKT_OFFSET,M_MAC_RX_PKT_OFFSET,V_MAC_RX_PKT_OFFSET,G_MAC_RX_PKT_OFFSET,8,24); bit!(M_MAC_FWDPAUSE_EN,32); bit!(M_MAC_VLAN_DET_EN,33); field!(S_MAC_RX_CH_MSN_SEL,M_MAC_RX_CH_MSN_SEL,V_MAC_RX_CH_MSN_SEL,G_MAC_RX_CH_MSN_SEL,8,34);
pub const S_MAC_MDC:u64=0; pub const S_MAC_MDIO_DIR:u64=1; pub const S_MAC_MDIO_OUT:u64=2; pub const S_MAC_GENC:u64=3; pub const S_MAC_MDIO_IN:u64=4;
bit!(M_MAC_MDC,S_MAC_MDC); bit!(M_MAC_MDIO_DIR,S_MAC_MDIO_DIR); bit!(M_MAC_MDIO_DIR_INPUT,S_MAC_MDIO_DIR); bit!(M_MAC_MDIO_OUT,S_MAC_MDIO_OUT); bit!(M_MAC_GENC,S_MAC_GENC); bit!(M_MAC_MDIO_IN,S_MAC_MDIO_IN);

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
