/* SPDX-License-Identifier: MIT */
/* Translated from dml2_utils.c. C headers and external symbols are supplied by dependencies. */

pub unsafe fn dml2_util_copy_dml_timing(a: *mut dml_timing_cfg_st, d: usize, s: usize) {
    (*a).HTotal[d]=(*a).HTotal[s]; (*a).VTotal[d]=(*a).VTotal[s]; (*a).HBlankEnd[d]=(*a).HBlankEnd[s]; (*a).VBlankEnd[d]=(*a).VBlankEnd[s];
    (*a).RefreshRate[d]=(*a).RefreshRate[s]; (*a).VFrontPorch[d]=(*a).VFrontPorch[s]; (*a).PixelClock[d]=(*a).PixelClock[s];
    (*a).HActive[d]=(*a).HActive[s]; (*a).VActive[d]=(*a).VActive[s]; (*a).Interlace[d]=(*a).Interlace[s];
    (*a).DRRDisplay[d]=(*a).DRRDisplay[s]; (*a).VBlankNom[d]=(*a).VBlankNom[s];
}

pub unsafe fn dml2_util_copy_dml_plane(a: *mut dml_plane_cfg_st, d: usize, s: usize) {
    (*a).GPUVMMinPageSizeKBytes[d]=(*a).GPUVMMinPageSizeKBytes[s]; (*a).ForceOneRowForFrame[d]=(*a).ForceOneRowForFrame[s];
    (*a).PTEBufferModeOverrideEn[d]=(*a).PTEBufferModeOverrideEn[s]; (*a).PTEBufferMode[d]=(*a).PTEBufferMode[s];
    (*a).ViewportWidth[d]=(*a).ViewportWidth[s]; (*a).ViewportHeight[d]=(*a).ViewportHeight[s]; (*a).ViewportWidthChroma[d]=(*a).ViewportWidthChroma[s]; (*a).ViewportHeightChroma[d]=(*a).ViewportHeightChroma[s];
    (*a).ViewportXStart[d]=(*a).ViewportXStart[s]; (*a).ViewportXStartC[d]=(*a).ViewportXStartC[s]; (*a).ViewportYStart[d]=(*a).ViewportYStart[s]; (*a).ViewportYStartC[d]=(*a).ViewportYStartC[s]; (*a).ViewportStationary[d]=(*a).ViewportStationary[s];
    (*a).ScalerEnabled[d]=(*a).ScalerEnabled[s]; (*a).HRatio[d]=(*a).HRatio[s]; (*a).VRatio[d]=(*a).VRatio[s]; (*a).HRatioChroma[d]=(*a).HRatioChroma[s]; (*a).VRatioChroma[d]=(*a).VRatioChroma[s];
    (*a).HTaps[d]=(*a).HTaps[s]; (*a).VTaps[d]=(*a).VTaps[s]; (*a).HTapsChroma[d]=(*a).HTapsChroma[s]; (*a).VTapsChroma[d]=(*a).VTapsChroma[s]; (*a).LBBitPerPixel[d]=(*a).LBBitPerPixel[s];
    (*a).SourceScan[d]=(*a).SourceScan[s]; (*a).ScalerRecoutWidth[d]=(*a).ScalerRecoutWidth[s];
    (*a).DynamicMetadataEnable[d]=(*a).DynamicMetadataEnable[s]; (*a).DynamicMetadataLinesBeforeActiveRequired[d]=(*a).DynamicMetadataLinesBeforeActiveRequired[s]; (*a).DynamicMetadataTransmittedBytes[d]=(*a).DynamicMetadataTransmittedBytes[s]; (*a).DETSizeOverride[d]=(*a).DETSizeOverride[s];
    (*a).NumberOfCursors[d]=(*a).NumberOfCursors[s]; (*a).CursorWidth[d]=(*a).CursorWidth[s]; (*a).CursorBPP[d]=(*a).CursorBPP[s];
    (*a).UseMALLForStaticScreen[d]=(*a).UseMALLForStaticScreen[s]; (*a).UseMALLForPStateChange[d]=(*a).UseMALLForPStateChange[s]; (*a).BlendingAndTiming[d]=(*a).BlendingAndTiming[s];
}

pub unsafe fn dml2_util_copy_dml_surface(a:*mut dml_surface_cfg_st,d:usize,s:usize){
    (*a).SurfaceTiling[d]=(*a).SurfaceTiling[s]; (*a).SourcePixelFormat[d]=(*a).SourcePixelFormat[s]; (*a).PitchY[d]=(*a).PitchY[s]; (*a).SurfaceWidthY[d]=(*a).SurfaceWidthY[s]; (*a).SurfaceHeightY[d]=(*a).SurfaceHeightY[s]; (*a).PitchC[d]=(*a).PitchC[s]; (*a).SurfaceWidthC[d]=(*a).SurfaceWidthC[s]; (*a).SurfaceHeightC[d]=(*a).SurfaceHeightC[s];
    (*a).DCCEnable[d]=(*a).DCCEnable[s]; (*a).DCCMetaPitchY[d]=(*a).DCCMetaPitchY[s]; (*a).DCCMetaPitchC[d]=(*a).DCCMetaPitchC[s]; (*a).DCCRateLuma[d]=(*a).DCCRateLuma[s]; (*a).DCCRateChroma[d]=(*a).DCCRateChroma[s]; (*a).DCCFractionOfZeroSizeRequestsLuma[d]=(*a).DCCFractionOfZeroSizeRequestsLuma[s]; (*a).DCCFractionOfZeroSizeRequestsChroma[d]=(*a).DCCFractionOfZeroSizeRequestsChroma[s];
}

pub unsafe fn dml2_util_copy_dml_output(a:*mut dml_output_cfg_st,d:usize,s:usize){
    (*a).DSCInputBitPerComponent[d]=(*a).DSCInputBitPerComponent[s]; (*a).OutputFormat[d]=(*a).OutputFormat[s]; (*a).OutputEncoder[d]=(*a).OutputEncoder[s]; (*a).OutputMultistreamId[d]=(*a).OutputMultistreamId[s]; (*a).OutputMultistreamEn[d]=(*a).OutputMultistreamEn[s]; (*a).OutputBpp[d]=(*a).OutputBpp[s]; (*a).PixelClockBackEnd[d]=(*a).PixelClockBackEnd[s]; (*a).DSCEnable[d]=(*a).DSCEnable[s]; (*a).OutputLinkDPLanes[d]=(*a).OutputLinkDPLanes[s]; (*a).OutputLinkDPRate[d]=(*a).OutputLinkDPRate[s]; (*a).ForcedOutputLinkBPP[d]=(*a).ForcedOutputLinkBPP[s]; (*a).AudioSampleRate[d]=(*a).AudioSampleRate[s]; (*a).AudioSampleLayout[d]=(*a).AudioSampleLayout[s];
}

pub unsafe fn dml2_util_get_maximum_odm_combine_for_output(force: bool, encoder: dml_output_encoder_class, dsc: bool) -> u32 { match encoder { dml_dp|dml_edp=>2, dml_dp2p0=>if dsc||force{4}else{2}, dml_hdmi=>1, dml_hdmifrl=>if force{4}else{2}, _=>1 } }

pub unsafe fn is_dp2p0_output_encoder(p:*const pipe_ctx)->bool { if p.is_null()||(*p).stream.is_null(){return false;} ASSERT!((*p).stream_res.hpo_dp_stream_enc==0 || !(*p).link_res.hpo_dp_link_enc.is_null()); (*p).stream_res.hpo_dp_stream_enc!=0 && !(*p).link_res.hpo_dp_link_enc.is_null() && dc_is_dp_signal((*p).stream).signal }

pub unsafe fn is_dtbclk_required(dc:*const dc, c:*mut dc_state)->bool { for i in 0..(*(*dc).res_pool).pipe_count as usize { let p=&(*c).res_ctx.pipe_ctx[i]; if p.stream.is_null(){continue;} if dc_is_hdmi_frl_signal((*p.stream).signal)||is_dp2p0_output_encoder(p){return true;} } false }

pub unsafe fn dml2_copy_clocks_to_dc_state(o:*mut dml2_dcn_clocks,c:*mut dc_state){ (*c).bw_ctx.bw.dcn.clk.dispclk_khz=(*o).dispclk_khz; (*c).bw_ctx.bw.dcn.clk.dcfclk_khz=(*o).dcfclk_khz; (*c).bw_ctx.bw.dcn.clk.dramclk_khz=(*o).uclk_mts/16; (*c).bw_ctx.bw.dcn.clk.fclk_khz=(*o).fclk_khz; (*c).bw_ctx.bw.dcn.clk.phyclk_khz=(*o).phyclk_khz; (*c).bw_ctx.bw.dcn.clk.socclk_khz=(*o).socclk_khz; (*c).bw_ctx.bw.dcn.clk.ref_dtbclk_khz=(*o).ref_dtbclk_khz; (*c).bw_ctx.bw.dcn.clk.p_state_change_support=(*o).p_state_supported; }

pub unsafe fn dml2_helper_find_dml_pipe_idx_by_stream_id(c:*mut dml2_context,id:u32)->i32 { for i in 0..__DML2_WRAPPER_MAX_STREAMS_PLANES__ as usize { if (*c).v20.scratch.dml_to_dc_pipe_mapping.dml_pipe_idx_to_stream_id_valid[i] && (*c).v20.scratch.dml_to_dc_pipe_mapping.dml_pipe_idx_to_stream_id[i]==id{return i as i32;} } -1 }
unsafe fn find_dml_pipe_idx_by_plane_id(c:*mut dml2_context,id:u32)->i32 { for i in 0..__DML2_WRAPPER_MAX_STREAMS_PLANES__ as usize { if (*c).v20.scratch.dml_to_dc_pipe_mapping.dml_pipe_idx_to_plane_id_valid[i]&&(*c).v20.scratch.dml_to_dc_pipe_mapping.dml_pipe_idx_to_plane_id[i]==id{return i as i32;} } -1 }
unsafe fn get_plane_id(d:*mut dml2_context,state:*const dc_state,plane:*const dc_plane_state,sid:u32,pi:u32,out:*mut u32)->bool { if out.is_null(){return false;} for i in 0..(*state).stream_count as usize { if (*(*state).streams[i]).stream_id==sid { for j in 0..(*state).stream_status[i].plane_count as usize { if (*state).stream_status[i].plane_states[j]==plane && (!(*d).v20.scratch.plane_duplicate_exists||j as u32==pi){*out=((i as u32)<<16)|j as u32;return true;} } } } false }

unsafe fn populate_pipe_ctx_dlg_params_from_dml(p:*mut pipe_ctx,m:*mut display_mode_lib_st,idx:dml_uint_t){ let t=&(*(*p).stream).timing; let ha=t.h_addressable+t.h_border_left+t.h_border_right; let va=t.v_addressable+t.v_border_bottom+t.v_border_top; let hs=t.h_total-t.h_front_porch; let vs=t.v_total-t.v_front_porch; let he=hs-t.h_addressable-t.h_border_left-t.h_border_right; let ve=vs-t.v_addressable-t.v_border_top-t.v_border_bottom; (*p).pipe_dlg_param.vstartup_start=dml_get_vstartup_calculated(m,idx); (*p).pipe_dlg_param.vupdate_offset=dml_get_vupdate_offset(m,idx); (*p).pipe_dlg_param.vupdate_width=dml_get_vupdate_width(m,idx); (*p).pipe_dlg_param.vready_offset=dml_get_vready_offset(m,idx); ASSERT!((*p).stream_res.tg.inst<=0xff); (*p).pipe_dlg_param.otg_inst=(*p).stream_res.tg.inst as u8; (*p).pipe_dlg_param.hactive=ha; (*p).pipe_dlg_param.vactive=va; (*p).pipe_dlg_param.htotal=t.h_total; (*p).pipe_dlg_param.vtotal=t.v_total; (*p).pipe_dlg_param.hblank_end=he; (*p).pipe_dlg_param.vblank_end=ve; (*p).pipe_dlg_param.hblank_start=hs; (*p).pipe_dlg_param.vblank_start=vs; (*p).pipe_dlg_param.vfront_porch=t.v_front_porch; (*p).pipe_dlg_param.pixel_rate_mhz=t.pix_clk_100hz as f64/10000.0; (*p).pipe_dlg_param.refresh_rate=((t.pix_clk_100hz*100)/t.h_total)/t.v_total; (*p).pipe_dlg_param.vtotal_max=(*p).stream.adjust.v_total_max; (*p).pipe_dlg_param.vtotal_min=(*p).stream.adjust.v_total_min; (*p).pipe_dlg_param.recout_height=(*p).plane_res.scl_data.recout.height; (*p).pipe_dlg_param.recout_width=(*p).plane_res.scl_data.recout.width; (*p).pipe_dlg_param.full_recout_height=(*p).plane_res.scl_data.recout.height; (*p).pipe_dlg_param.full_recout_width=(*p).plane_res.scl_data.recout.width; }

pub unsafe fn dml2_extract_watermark_set(w:*mut dcn_watermarks,m:*mut display_mode_lib_st){ (*w).urgent_ns=(dml_get_wm_urgent(m)*1000.0) as u32; (*w).cstate_pstate.cstate_enter_plus_exit_ns=(dml_get_wm_stutter_enter_exit(m)*1000.0) as u32; (*w).cstate_pstate.cstate_exit_ns=(dml_get_wm_stutter_exit(m)*1000.0) as u32; (*w).cstate_pstate.pstate_change_ns=(dml_get_wm_dram_clock_change(m)*1000.0) as u32; (*w).pte_meta_urgent_ns=(dml_get_wm_memory_trip(m)*1000.0) as u32; (*w).frac_urg_bw_nom=(dml_get_fraction_of_urgent_bandwidth(m)*1000.0) as u32; (*w).frac_urg_bw_flip=(dml_get_fraction_of_urgent_bandwidth_imm_flip(m)*1000.0) as u32; (*w).urgent_latency_ns=(dml_get_urgent_latency(m)*1000.0) as u32; (*w).cstate_pstate.fclk_pstate_change_ns=(dml_get_wm_fclk_change(m)*1000.0) as u32; (*w).usr_retraining_ns=(dml_get_wm_usr_retraining(m)*1000.0) as u32; (*w).cstate_pstate.cstate_enter_plus_exit_z8_ns=(dml_get_wm_z8_stutter_enter_exit(m)*1000.0) as u32; (*w).cstate_pstate.cstate_exit_z8_ns=(dml_get_wm_z8_stutter(m)*1000.0) as u32; }

pub unsafe fn dml2_calc_max_scaled_time(t:u32,mode:mmhubbub_wbif_mode,u:u32)->u32 { let mut b=if mode==PACKED_444{t/4}else if mode==PACKED_444_FP16{t/8}else{0}; if b==0{b=1;} ((0xb40*b*32)>>6)-u }

pub unsafe fn dml2_initialize_det_scratch(c:*mut dml2_context){for i in 0..MAX_PLANES as usize{(*c).det_helper_scratch.dpps_per_surface[i]=1;}}

pub unsafe fn dml2_is_stereo_timing(s:*const dc_stream_state)->bool { ((*s).view_format==VIEW_3D_FORMAT_SIDE_BY_SIDE||(*s).view_format==VIEW_3D_FORMAT_TOP_AND_BOTTOM)&&((*s).timing.timing_3d_format==TIMING_3D_FORMAT_TOP_AND_BOTTOM||(*s).timing.timing_3d_format==TIMING_3D_FORMAT_SIDE_BY_SIDE) }

pub unsafe fn dml2_calculate_rq_and_dlg_params(dc:*const dc,ctx:*mut dc_state,out:*mut resource_context,in_ctx:*mut dml2_context,pipe_cnt:u32){
    (*ctx).bw_ctx.bw.dcn.clk.dcfclk_deep_sleep_khz=((*in_ctx).v20.dml_core_ctx.mp.DCFCLKDeepSleep*1000.0) as u32; (*ctx).bw_ctx.bw.dcn.clk.dppclk_khz=0;
    (*ctx).bw_ctx.bw.dcn.clk.fclk_p_state_change_support=(*in_ctx).v20.dml_core_ctx.ms.support.FCLKChangeSupport[0]!=dml_fclock_change_unsupported;
    if (*ctx).bw_ctx.bw.dcn.clk.dispclk_khz<(*dc).debug.min_disp_clk_khz{(*ctx).bw_ctx.bw.dcn.clk.dispclk_khz=(*dc).debug.min_disp_clk_khz;}
    (*ctx).bw_ctx.bw.dcn.compbuf_size_kb=(*in_ctx).v20.dml_core_ctx.ip.config_return_buffer_size_in_kbytes;
    for ci in 0..pipe_cnt as usize { let p=&mut (*ctx).res_ctx.pipe_ctx[ci]; if p.stream.is_null(){continue;} let mut id=0; let di=if get_plane_id(in_ctx,ctx,p.plane_state,(*p.stream).stream_id,(*in_ctx).v20.scratch.dml_to_dc_pipe_mapping.dml_pipe_idx_to_plane_index[p.pipe_idx as usize],&mut id){find_dml_pipe_idx_by_plane_id(in_ctx,id)}else{dml2_helper_find_dml_pipe_idx_by_stream_id(in_ctx,(*p.stream).stream_id)}; if di<0||di==0x7fffffff{continue;} let di=di as usize; ASSERT!((*in_ctx).v20.scratch.dml_to_dc_pipe_mapping.dml_pipe_idx_to_stream_id_valid[di]); populate_pipe_ctx_dlg_params_from_dml(p,&mut (*ctx).bw_ctx.dml2.v20.dml_core_ctx,di as dml_uint_t); let mt=dc_state_get_pipe_subvp_type(ctx,p); if mt==SUBVP_PHANTOM{p.det_buffer_size_kb=0;p.unbounded_req=false;}else{p.det_buffer_size_kb=dml_get_det_buffer_size_kbytes(&mut (*ctx).bw_ctx.dml2.v20.dml_core_ctx,di as dml_uint_t);p.unbounded_req=(*in_ctx).v20.dml_core_ctx.ms.UnboundedRequestEnabledThisState;} (*ctx).bw_ctx.bw.dcn.compbuf_size_kb-=p.det_buffer_size_kb; p.plane_res.bw.dppclk_khz=(dml_get_dppclk_calculated(&mut (*ctx).bw_ctx.dml2.v20.dml_core_ctx,di as dml_uint_t)*1000.0) as i32; if (*ctx).bw_ctx.bw.dcn.clk.dppclk_khz<p.plane_res.bw.dppclk_khz{(*ctx).bw_ctx.bw.dcn.clk.dppclk_khz=p.plane_res.bw.dppclk_khz;} (*ctx).res_ctx.pipe_ctx[ci].surface_size_in_mall_bytes=dml_get_surface_size_for_mall(&mut (*ctx).bw_ctx.dml2.v20.dml_core_ctx,di as dml_uint_t); }
    (*ctx).bw_ctx.bw.dcn.clk.bw_dppclk_khz=(*ctx).bw_ctx.bw.dcn.clk.dppclk_khz; (*ctx).bw_ctx.bw.dcn.clk.bw_dispclk_khz=(*ctx).bw_ctx.bw.dcn.clk.dispclk_khz;
}

pub unsafe fn dml2_apply_det_buffer_allocation_policy(c:*mut dml2_context,cfg:*mut dml_display_cfg_st){ let max=c.as_ref().unwrap().config.det_segment_size*c.as_ref().unwrap().config.max_segments_per_hubp; for i in 0..(*cfg).num_surfaces as usize { (*cfg).plane.DETSizeOverride[i]=if (*c).config.override_det_buffer_size_kbytes{max/(*c).config.dcn_pipe_count}else{max/(*c).config.dcn_pipe_count}; } }
pub unsafe fn dml2_verify_det_buffer_configuration(c:*mut dml2_context,state:*mut dc_state,s:*mut dml2_helper_det_policy_scratch)->bool { let mut total=0; for i in 0..MAX_PIPES as usize {let p=&(*state).res_ctx.pipe_ctx[i];if p.stream.is_null(){continue;} let di=dml2_helper_find_dml_pipe_idx_by_stream_id(c,(*p.stream).stream_id);if di>=0{total+=dml_get_det_buffer_size_kbytes(&mut (*c).v20.dml_core_ctx,di as dml_uint_t);}} for i in 0..MAX_PLANES as usize{(*s).dpps_per_surface[i]=(*c).v20.scratch.cur_display_config.hw.DPPPerSurface[i];} total>(*c).config.det_segment_size*(*c).config.max_segments_per_hubp }

pub unsafe fn dml2_extract_writeback_wm(c:*mut dc_state,m:*mut display_mode_lib_st){ let mut n=0;for i in 0..(*c).stream_count as usize{if (*(*c).streams[i]).num_wb_info!=0{n+=1;}}if n==0{return;}for i in 0..__DML_NUM_DMB__ as usize{for j in 0..4{(*c).bw_ctx.bw.dcn.bw_writeback.mcif_wb_arb[i].cli_watermark[j]=(dml_get_wm_writeback_urgent(m)*1000.0) as u32;(*c).bw_ctx.bw.dcn.bw_writeback.mcif_wb_arb[i].pstate_watermark[j]=(dml_get_wm_writeback_dram_clock_change(m)*1000.0) as u32;}let a=&mut (*c).bw_ctx.bw.dcn.bw_writeback.mcif_wb_arb[i];if !(*c).res_ctx.pipe_ctx[i].stream.is_null()&&(*(*c).res_ctx.pipe_ctx[i].stream).phy_pix_clk!=0{a.time_per_pixel=(1000000<<6)/(*(*c).res_ctx.pipe_ctx[i].stream).phy_pix_clk;}a.slice_lines=32;a.arbitration_slice=2;a.max_scaled_time=dml2_calc_max_scaled_time(a.time_per_pixel,PACKED_444_FP16,a.cli_watermark[0]);a.dram_speed_change_duration=(dml_get_wm_writeback_dram_clock_change(m)*1000.0) as u32;}}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
