// SPDX-License-Identifier: GPL-2.0-or-later
/* C translation of integrity/ima/ima_kexec.c. */

use core::ffi::c_void;
use core::mem;
use core::ptr::{self, null_mut};

#[cfg(feature = "CONFIG_IMA_KEXEC")] const IMA_KEXEC_EVENT_LEN: usize = 256;
#[repr(C)] pub struct seq_file { pub buf:*mut u8, pub size:usize, pub read_pos:usize, pub count:usize }
#[repr(C)] pub struct ima_queue_entry { _private:[u8;0] }
#[repr(C)] pub struct ima_kexec_hdr { pub version:u16, pub _pad:u16, pub count:u64, pub buffer_size:u64 }
#[repr(C)] pub struct kimage { pub type_:i32, pub ima_buffer_addr:usize, pub ima_buffer_size:usize, pub ima_buffer:*mut c_void, pub ima_segment_index:usize, pub is_ima_segment_index_set:bool, pub nr_segments:usize }
#[repr(C)] pub struct kexec_buf { pub image:*mut kimage, pub buffer:*mut c_void, pub bufsz:usize, pub memsz:usize, pub buf_align:usize, pub buf_min:usize, pub buf_max:usize, pub top_down:bool, pub mem:usize }
#[repr(C)] pub struct notifier_block { pub notifier_call:unsafe extern "C" fn(*mut notifier_block,usize,*mut c_void)->i32, pub next:*mut notifier_block, pub priority:i32 }
extern "C" { fn vfree(*mut c_void); fn vmalloc(usize)->*mut c_void; fn scnprintf(*mut u8,usize,*const u8,...)->usize; fn pr_err(*const u8,...); fn pr_info(*const u8,...); fn pr_debug(*const u8,...); fn pr_warn(*const u8,...); fn kexec_dprintk(*const u8,...); fn kexec_add_buffer(*mut kexec_buf)->i32; fn kimage_map_segment(*mut kimage,usize)->*mut c_void; fn kimage_unmap_segment(*mut c_void); fn register_reboot_notifier(*mut notifier_block)->i32; fn print_hex_dump_debug(*const u8,i32,i32,i32,*const c_void,usize,bool); fn ima_measurements_show(*mut seq_file,*mut ima_queue_entry); fn ima_get_binary_runtime_size(i32)->usize; fn ima_measure_critical_data(*const u8,*const u8,*const u8,usize,bool,*mut u8,usize); fn ima_restore_measurement_list(usize,*mut c_void)->i32; fn ima_get_kexec_buffer(*mut *mut c_void,*mut usize)->i32; fn ima_free_kexec_buffer(); fn pfn_range_is_mapped(usize,usize)->bool; fn page_is_ram(usize)->bool; fn totalram_pages()->usize; static mut ima_canonical_fmt:bool; static mut ima_num_records:i64; static PAGE_SIZE:usize; static ULONG_MAX:usize; static PAGE_SHIFT:usize; static DUMP_PREFIX_NONE:i32; static KEXEC_TYPE_CRASH:i32; }
#[cfg(feature="CONFIG_IMA_KEXEC")] static mut ima_kexec_update_registered:bool=false;
#[cfg(feature="CONFIG_IMA_KEXEC")] static mut ima_kexec_file:seq_file=seq_file{buf:null_mut(),size:0,read_pos:0,count:0};
#[cfg(feature="CONFIG_IMA_KEXEC")] static mut kexec_segment_size:usize=0;
#[cfg(feature="CONFIG_IMA_KEXEC")] static mut ima_kexec_buffer:*mut c_void=null_mut();
#[cfg(feature="CONFIG_IMA_KEXEC")] unsafe fn ima_free_kexec_file_buf(sf:*mut seq_file){vfree((*sf).buf as *mut c_void);(*sf).buf=null_mut();(*sf).size=0;(*sf).read_pos=0;(*sf).count=0;}
#[cfg(feature="CONFIG_IMA_KEXEC")] pub unsafe fn ima_measure_kexec_event(event_name:*const u8){let mut e=[0u8;IMA_KEXEC_EVENT_LEN];let n=scnprintf(e.as_mut_ptr(),IMA_KEXEC_EVENT_LEN,b"kexec_segment_size=%lu;ima_binary_runtime_size=%lu;ima_runtime_measurements_count=%ld;\0".as_ptr(),kexec_segment_size,ima_get_binary_runtime_size(3),ima_num_records);ima_measure_critical_data(b"ima_kexec\0".as_ptr(),event_name,e.as_ptr(),n,false,null_mut(),0);}
#[cfg(feature="CONFIG_IMA_KEXEC")] unsafe fn ima_alloc_kexec_file_buf(s:usize)->i32{if !ima_kexec_file.buf.is_null()&&ima_kexec_file.size==s{ima_kexec_file.read_pos=0;ima_kexec_file.count=mem::size_of::<ima_kexec_hdr>();ima_measure_kexec_event(b"kexec_load\0".as_ptr());return 0;}ima_free_kexec_file_buf(&mut ima_kexec_file);ima_kexec_file.buf=vmalloc(s)as*mut u8;if ima_kexec_file.buf.is_null(){return -12;}ima_kexec_file.size=s;ima_kexec_file.read_pos=0;ima_kexec_file.count=mem::size_of::<ima_kexec_hdr>();ima_measure_kexec_event(b"kexec_load\0".as_ptr());0}
#[cfg(feature="CONFIG_IMA_KEXEC")] unsafe fn ima_dump_measurement(h:*mut ima_kexec_hdr,q:*mut ima_queue_entry)->i32{if ima_kexec_file.count>=ima_kexec_file.size{return -22;}(*h).count+=1;ima_measurements_show(&mut ima_kexec_file,q);0}
#[cfg(feature="CONFIG_IMA_KEXEC")] unsafe fn ima_dump_measurement_list(bs:*mut usize,b:*mut *mut c_void,_:usize)->i32{if ima_kexec_file.buf.is_null(){pr_err(b"Kexec file buf not allocated\n\0".as_ptr());return -22;}let mut h:ima_kexec_hdr=mem::zeroed();h.version=1;/* list_for_each_entry over staged and normal measurement lists */h.buffer_size=ima_kexec_file.count as u64;if ima_canonical_fmt{h.version=h.version.to_le();h.count=h.count.to_le();h.buffer_size=h.buffer_size.to_le();}ptr::copy_nonoverlapping(&h as*const _ as*const u8,ima_kexec_file.buf,mem::size_of::<ima_kexec_hdr>());print_hex_dump_debug(b"ima dump: \0".as_ptr(),DUMP_PREFIX_NONE,16,1,ima_kexec_file.buf as*const c_void,ima_kexec_file.count.min(100),true);*bs=ima_kexec_file.count;*b=ima_kexec_file.buf as*mut c_void;0}
#[cfg(feature="CONFIG_IMA_KEXEC")] pub unsafe fn ima_add_kexec_buffer(image:*mut kimage){if(*image).type_==KEXEC_TYPE_CRASH{return;}let extra=*PAGE_SIZE/2;let n=ima_get_binary_runtime_size(0)+ima_get_binary_runtime_size(2)+extra;kexec_segment_size=if n>=*ULONG_MAX-*PAGE_SIZE{*ULONG_MAX}else{(n+*PAGE_SIZE-1)&!(*PAGE_SIZE-1)};if kexec_segment_size==*ULONG_MAX||(kexec_segment_size>>*PAGE_SHIFT)>totalram_pages()/2{pr_err(b"Binary measurement list too large.\n\0".as_ptr());return;}if ima_alloc_kexec_file_buf(kexec_segment_size)<0{return;}let mut k=kexec_buf{image,buffer:null_mut(),bufsz:0,memsz:kexec_segment_size,buf_align:*PAGE_SIZE,buf_min:0,buf_max:*ULONG_MAX,top_down:true,mem:0};(*image).is_ima_segment_index_set=false;if kexec_add_buffer(&mut k)!=0{vfree(k.buffer);return;}(*image).ima_buffer_addr=k.mem;(*image).ima_buffer_size=kexec_segment_size;(*image).ima_buffer=k.buffer;(*image).ima_segment_index=(*image).nr_segments-1;(*image).is_ima_segment_index_set=true;kexec_dprintk(b"kexec measurement buffer for the loaded kernel at 0x%lx.\n\0".as_ptr(),k.mem);}
pub unsafe fn ima_load_kexec_buffer(){let mut b=null_mut();let mut s=0;let r=ima_get_kexec_buffer(&mut b,&mut s);match r{0=>{let x=ima_restore_measurement_list(s,b);if x!=0{pr_err(b"Failed to restore the measurement list: %d\n\0".as_ptr(),x);}ima_free_kexec_buffer();},-95=>pr_debug(b"Restoring the measurement list not supported\n\0".as_ptr()),-2=>pr_debug(b"No measurement list to restore\n\0".as_ptr()),_=>pr_debug(b"Error restoring the measurement list: %d\n\0".as_ptr(),r)}}
pub unsafe fn ima_validate_range(p:usize,s:usize)->i32{let e=match p.checked_add(s.wrapping_sub(1)){Some(x)=>x,None=>return -22};let a=p>>*PAGE_SHIFT;let z=e>>*PAGE_SHIFT;if !pfn_range_is_mapped(a,z)&&(!page_is_ram(a)||!page_is_ram(z)){pr_warn(b"IMA: previous kernel measurement buffer %pa (size 0x%zx) lies outside available memory\n\0".as_ptr(),&p,s);return -22;}0}
#[cfg(feature="CONFIG_IMA_KEXEC")] unsafe extern "C" fn ima_update_kexec_buffer(_: *mut notifier_block,_:usize,_:*mut c_void)->i32{if !kexec_in_progress(){return 0;}let mut s=0;let mut b=null_mut();let r=ima_dump_measurement_list(&mut s,&mut b,kexec_segment_size);if s!=0{ptr::copy_nonoverlapping(b as*const u8,ima_kexec_buffer as*mut u8,s);}kimage_unmap_segment(ima_kexec_buffer);ima_kexec_buffer=null_mut();r}
#[cfg(feature="CONFIG_IMA_KEXEC")] unsafe fn kexec_in_progress()->bool{extern "C"{static mut kexec_in_progress:bool} kexec_in_progress}
#[cfg(feature="CONFIG_IMA_KEXEC")] static mut update_buffer_nb:notifier_block=notifier_block{notifier_call:ima_update_kexec_buffer,next:null_mut(),priority:i32::MIN};
#[cfg(feature="CONFIG_IMA_KEXEC")] pub unsafe fn ima_kexec_post_load(image:*mut kimage){if !ima_kexec_buffer.is_null(){kimage_unmap_segment(ima_kexec_buffer);ima_kexec_buffer=null_mut();}if(*image).ima_buffer_addr==0{return;}ima_kexec_buffer=kimage_map_segment(image,(*image).ima_segment_index);if ima_kexec_buffer.is_null(){return;}if !ima_kexec_update_registered{register_reboot_notifier(&mut update_buffer_nb);ima_kexec_update_registered=true;}}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
