#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Boot an x86-64 kernel with an initramfs generated by the Rust host tool."""

import argparse
import os
from pathlib import Path
import selectors
import shlex
import subprocess
import sys
import time


ROOT = Path(__file__).resolve().parents[2]
MARKER = b"LUPOS_RUST_BUILD_BOOT_OK"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", required=True, type=Path,
                        help="kernel output directory containing bzImage and gen_init_cpio")
    parser.add_argument("--qemu", default=os.environ.get("QEMU", "qemu-system-x86_64"),
                        help="QEMU command (defaults to QEMU or qemu-system-x86_64)")
    parser.add_argument("--qemu-data", type=Path, help="optional QEMU firmware directory")
    parser.add_argument("--timeout", type=float, default=60)
    parser.add_argument("--module", type=Path, help="optional uncompressed module to load inside the VM")
    parser.add_argument("--reject-module", type=Path, action="append", default=[],
                        help="module that signature enforcement must reject inside the VM (repeatable)")
    args = parser.parse_args()
    build = args.build.resolve()
    work = build / "rust-boot-test"
    work.mkdir(parents=True, exist_ok=True)
    kernel = build / "arch/x86/boot/bzImage"
    generator = build / "usr/gen_init_cpio"
    for artifact in (kernel, generator):
        if not artifact.is_file():
            parser.error(f"missing build artifact: {artifact}")
    configuration = (build / ".config").read_text().splitlines()
    required = ["CONFIG_MULTIUSER=y"]
    if args.module or args.reject_module:
        required.append("CONFIG_MODULES=y")
    if args.reject_module:
        required.append("CONFIG_MODULE_SIG_FORCE=y")
    for setting in required:
        if setting not in configuration:
            parser.error(f"the requested boot checks require {setting}")
    for artifact in ([args.module] if args.module else []) + args.reject_module:
        if not artifact.is_file():
            parser.error(f"missing module fixture: {artifact}")
        if any(character.isspace() for character in str(artifact.resolve())):
            parser.error("the initramfs manifest requires module paths without whitespace")
    if any(character.isspace() for character in str(work)):
        parser.error("the initramfs manifest requires an output path without whitespace")

    init = work / "init"
    compiler_env = os.environ.copy()
    # Python closes make's jobserver descriptors for subprocesses. The fixture
    # is a standalone compilation, so it must not advertise those descriptors.
    for name in ("MAKEFLAGS", "MFLAGS", "CARGO_MAKEFLAGS"):
        compiler_env.pop(name, None)
    subprocess.run(shlex.split(os.environ.get("HOSTRUSTC", "rustc")) + [
        "--edition=2021", "--target=x86_64-unknown-linux-gnu",
        "-Ctarget-feature=+crt-static", "-Cpanic=abort", "-Cstrip=debuginfo",
        "-O", "-Dwarnings", str(ROOT / "scripts/tests/boot_init.rs"),
        "-o", str(init)], check=True, env=compiler_env)
    fixture = work / "fixture"
    fixture.write_bytes(b"Rust-generated initramfs fixture\n\0with binary data\xff")
    manifest = work / "manifest"
    entries = (
        "dir /dev 0755 0 0\n"
        "nod /dev/console 0600 0 0 c 5 1\n"
        f"file /init {init} 0755 0 0\n"
        f"file /fixture {fixture} 0640 123 456 /hardlink\n"
        "slink /symlink /fixture 0777 0 0\n")
    if args.module:
        entries += f"file /test-module.ko {args.module.resolve()} 0600 0 0\n"
    for index, module in enumerate(args.reject_module):
        entries += f"file /reject-module.{index} {module.resolve()} 0600 0 0\n"
    manifest.write_text(entries)
    archive = work / "initramfs.cpio"
    subprocess.run([str(generator), "-t", "0", "-c", "-o", str(archive),
                    str(manifest)], check=True)

    command = shlex.split(args.qemu) + [
        "-machine", "pc", "-accel", "tcg", "-m", "256M", "-smp", "2",
        "-display", "none", "-serial", "stdio", "-monitor", "none",
        "-nic", "none", "-no-reboot", "-kernel", str(kernel),
        "-initrd", str(archive),
        "-append", "console=ttyS0 rdinit=/init panic=-1 nokaslr"]
    if args.qemu_data:
        command += ["-L", str(args.qemu_data.resolve())]
    log_path = work / "console.log"
    deadline = time.monotonic() + args.timeout
    found = False
    tail = b""
    with log_path.open("wb") as log, selectors.DefaultSelector() as selector:
        process = subprocess.Popen(command, stdout=subprocess.PIPE,
                                   stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL)
        try:
            selector.register(process.stdout, selectors.EVENT_READ)
            while time.monotonic() < deadline:
                ready = selector.select(timeout=min(1, max(0, deadline - time.monotonic())))
                if not ready:
                    if process.poll() is not None:
                        break
                    continue
                data = process.stdout.read1(65536)
                if not data:
                    break
                log.write(data)
                log.flush()
                tail = (tail + data)[-65536:]
                if MARKER in tail:
                    found = True
                    break
        finally:
            if process.poll() is None:
                process.terminate()
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
            process.stdout.close()
    if not found:
        print(tail.decode(errors="replace"), file=sys.stderr)
        raise SystemExit(f"kernel boot check failed; console output: {log_path}")
    print(f"Kernel boot and Rust-generated initramfs checks passed; console: {log_path}")
    if args.module:
        print("Module load passed inside the VM.")
    if args.reject_module:
        print(f"Signature enforcement rejected {len(args.reject_module)} module fixture(s) inside the VM.")


if __name__ == "__main__":
    main()
