/*
 * Copyright 2022 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */


// addressBlock: aid_smuio_smuio_reset_SmuSmuioDec
//SMUIO_MP_RESET_INTR
pub const SMUIO_MP_RESET_INTR__SMUIO_MP_RESET_INTR__SHIFT: u32 = 0x0;
pub const SMUIO_MP_RESET_INTR__SMUIO_MP_RESET_INTR_MASK: u32 = 0x00000001;
//SMUIO_SOC_HALT
pub const SMUIO_SOC_HALT__WDT_FORCE_PWROK_EN__SHIFT: u32 = 0x2;
pub const SMUIO_SOC_HALT__WDT_FORCE_RESETn_EN__SHIFT: u32 = 0x3;
pub const SMUIO_SOC_HALT__WDT_FORCE_PWROK_EN_MASK: u32 = 0x00000004;
pub const SMUIO_SOC_HALT__WDT_FORCE_RESETn_EN_MASK: u32 = 0x00000008;


// addressBlock: aid_smuio_smuio_tsc_SmuSmuioDec
//PWROK_REFCLK_GAP_CYCLES
pub const PWROK_REFCLK_GAP_CYCLES__Pwrok_PreAssertion_clkgap_cycles__SHIFT: u32 = 0x0;
pub const PWROK_REFCLK_GAP_CYCLES__Pwrok_PostAssertion_clkgap_cycles__SHIFT: u32 = 0x8;
pub const PWROK_REFCLK_GAP_CYCLES__Pwrok_PreAssertion_clkgap_cycles_MASK: u32 = 0x000000FF;
pub const PWROK_REFCLK_GAP_CYCLES__Pwrok_PostAssertion_clkgap_cycles_MASK: u32 = 0x0000FF00;
//GOLDEN_TSC_INCREMENT_UPPER
pub const GOLDEN_TSC_INCREMENT_UPPER__GoldenTscIncrementUpper__SHIFT: u32 = 0x0;
pub const GOLDEN_TSC_INCREMENT_UPPER__GoldenTscIncrementUpper_MASK: u32 = 0x00FFFFFF;
//GOLDEN_TSC_INCREMENT_LOWER
pub const GOLDEN_TSC_INCREMENT_LOWER__GoldenTscIncrementLower__SHIFT: u32 = 0x0;
pub const GOLDEN_TSC_INCREMENT_LOWER__GoldenTscIncrementLower_MASK: u32 = 0xFFFFFFFF;
//GOLDEN_TSC_COUNT_UPPER
pub const GOLDEN_TSC_COUNT_UPPER__GoldenTscCountUpper__SHIFT: u32 = 0x0;
pub const GOLDEN_TSC_COUNT_UPPER__GoldenTscCountUpper_MASK: u32 = 0x00FFFFFF;
//GOLDEN_TSC_COUNT_LOWER
pub const GOLDEN_TSC_COUNT_LOWER__GoldenTscCountLower__SHIFT: u32 = 0x0;
pub const GOLDEN_TSC_COUNT_LOWER__GoldenTscCountLower_MASK: u32 = 0xFFFFFFFF;
//SOC_GOLDEN_TSC_SHADOW_UPPER
pub const SOC_GOLDEN_TSC_SHADOW_UPPER__SocGoldenTscShadowUpper__SHIFT: u32 = 0x0;
pub const SOC_GOLDEN_TSC_SHADOW_UPPER__SocGoldenTscShadowUpper_MASK: u32 = 0x00FFFFFF;
//SOC_GOLDEN_TSC_SHADOW_LOWER
pub const SOC_GOLDEN_TSC_SHADOW_LOWER__SocGoldenTscShadowLower__SHIFT: u32 = 0x0;
pub const SOC_GOLDEN_TSC_SHADOW_LOWER__SocGoldenTscShadowLower_MASK: u32 = 0xFFFFFFFF;
//SOC_GAP_PWROK
pub const SOC_GAP_PWROK__soc_gap_pwrok__SHIFT: u32 = 0x0;
pub const SOC_GAP_PWROK__soc_gap_pwrok_MASK: u32 = 0x00000001;


// addressBlock: aid_smuio_smuio_swtimer_SmuSmuioDec
//PWR_VIRT_RESET_REQ
pub const PWR_VIRT_RESET_REQ__VF_FLR__SHIFT: u32 = 0x0;
pub const PWR_VIRT_RESET_REQ__PF_FLR__SHIFT: u32 = 0x1f;
pub const PWR_VIRT_RESET_REQ__VF_FLR_MASK: u32 = 0x7FFFFFFF;
pub const PWR_VIRT_RESET_REQ__PF_FLR_MASK: u32 = 0x80000000;
//PWR_DISP_TIMER_CONTROL
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_COUNT__SHIFT: u32 = 0x0;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_ENABLE__SHIFT: u32 = 0x19;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_DISABLE__SHIFT: u32 = 0x1a;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_MASK__SHIFT: u32 = 0x1b;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_STAT_AK__SHIFT: u32 = 0x1c;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_TYPE__SHIFT: u32 = 0x1d;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_MODE__SHIFT: u32 = 0x1e;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_COUNT_MASK: u32 = 0x01FFFFFF;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_ENABLE_MASK: u32 = 0x02000000;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_DISABLE_MASK: u32 = 0x04000000;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_MASK_MASK: u32 = 0x08000000;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_STAT_AK_MASK: u32 = 0x10000000;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_TYPE_MASK: u32 = 0x20000000;
pub const PWR_DISP_TIMER_CONTROL__DISP_TIMER_INT_MODE_MASK: u32 = 0x40000000;
//PWR_DISP_TIMER_DEBUG
pub const PWR_DISP_TIMER_DEBUG__DISP_TIMER_INT_RUNNING__SHIFT: u32 = 0x0;
pub const PWR_DISP_TIMER_DEBUG__DISP_TIMER_INT_STAT__SHIFT: u32 = 0x1;
pub const PWR_DISP_TIMER_DEBUG__DISP_TIMER_INT__SHIFT: u32 = 0x2;
pub const PWR_DISP_TIMER_DEBUG__DISP_TIMER_RUN_VAL__SHIFT: u32 = 0x7;
pub const PWR_DISP_TIMER_DEBUG__DISP_TIMER_INT_RUNNING_MASK: u32 = 0x00000001;
pub const PWR_DISP_TIMER_DEBUG__DISP_TIMER_INT_STAT_MASK: u32 = 0x00000002;
pub const PWR_DISP_TIMER_DEBUG__DISP_TIMER_INT_MASK: u32 = 0x00000004;
pub const PWR_DISP_TIMER_DEBUG__DISP_TIMER_RUN_VAL_MASK: u32 = 0xFFFFFF80;
//PWR_DISP_TIMER2_CONTROL
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_COUNT__SHIFT: u32 = 0x0;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_ENABLE__SHIFT: u32 = 0x19;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_DISABLE__SHIFT: u32 = 0x1a;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_MASK__SHIFT: u32 = 0x1b;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_STAT_AK__SHIFT: u32 = 0x1c;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_TYPE__SHIFT: u32 = 0x1d;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_MODE__SHIFT: u32 = 0x1e;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_COUNT_MASK: u32 = 0x01FFFFFF;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_ENABLE_MASK: u32 = 0x02000000;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_DISABLE_MASK: u32 = 0x04000000;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_MASK_MASK: u32 = 0x08000000;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_STAT_AK_MASK: u32 = 0x10000000;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_TYPE_MASK: u32 = 0x20000000;
pub const PWR_DISP_TIMER2_CONTROL__DISP_TIMER_INT_MODE_MASK: u32 = 0x40000000;
//PWR_DISP_TIMER2_DEBUG
pub const PWR_DISP_TIMER2_DEBUG__DISP_TIMER_INT_RUNNING__SHIFT: u32 = 0x0;
pub const PWR_DISP_TIMER2_DEBUG__DISP_TIMER_INT_STAT__SHIFT: u32 = 0x1;
pub const PWR_DISP_TIMER2_DEBUG__DISP_TIMER_INT__SHIFT: u32 = 0x2;
pub const PWR_DISP_TIMER2_DEBUG__DISP_TIMER_RUN_VAL__SHIFT: u32 = 0x7;
pub const PWR_DISP_TIMER2_DEBUG__DISP_TIMER_INT_RUNNING_MASK: u32 = 0x00000001;
pub const PWR_DISP_TIMER2_DEBUG__DISP_TIMER_INT_STAT_MASK: u32 = 0x00000002;
pub const PWR_DISP_TIMER2_DEBUG__DISP_TIMER_INT_MASK: u32 = 0x00000004;
pub const PWR_DISP_TIMER2_DEBUG__DISP_TIMER_RUN_VAL_MASK: u32 = 0xFFFFFF80;
//PWR_DISP_TIMER_GLOBAL_CONTROL
pub const PWR_DISP_TIMER_GLOBAL_CONTROL__DISP_TIMER_PULSE_WIDTH__SHIFT: u32 = 0x0;
pub const PWR_DISP_TIMER_GLOBAL_CONTROL__DISP_TIMER_PULSE_EN__SHIFT: u32 = 0xa;
pub const PWR_DISP_TIMER_GLOBAL_CONTROL__DISP_TIMER_PULSE_WIDTH_MASK: u32 = 0x000003FF;
pub const PWR_DISP_TIMER_GLOBAL_CONTROL__DISP_TIMER_PULSE_EN_MASK: u32 = 0x00000400;
//PWR_IH_CONTROL
pub const PWR_IH_CONTROL__MAX_CREDIT__SHIFT: u32 = 0x0;
pub const PWR_IH_CONTROL__DISP_TIMER_TRIGGER_MASK__SHIFT: u32 = 0x5;
pub const PWR_IH_CONTROL__DISP_TIMER2_TRIGGER_MASK__SHIFT: u32 = 0x6;
pub const PWR_IH_CONTROL__PWR_IH_CLK_GATE_EN__SHIFT: u32 = 0x1f;
pub const PWR_IH_CONTROL__MAX_CREDIT_MASK: u32 = 0x0000001F;
pub const PWR_IH_CONTROL__DISP_TIMER_TRIGGER_MASK_MASK: u32 = 0x00000020;
pub const PWR_IH_CONTROL__DISP_TIMER2_TRIGGER_MASK_MASK: u32 = 0x00000040;
pub const PWR_IH_CONTROL__PWR_IH_CLK_GATE_EN_MASK: u32 = 0x80000000;


// addressBlock: aid_smuio_smuio_misc_SmuSmuioDec
//SMUIO_MCM_CONFIG
pub const SMUIO_MCM_CONFIG__DIE_ID__SHIFT: u32 = 0x0;
pub const SMUIO_MCM_CONFIG__PKG_TYPE__SHIFT: u32 = 0x2;
pub const SMUIO_MCM_CONFIG__SOCKET_ID__SHIFT: u32 = 0x8;
pub const SMUIO_MCM_CONFIG__PKG_SUBTYPE__SHIFT: u32 = 0xc;
pub const SMUIO_MCM_CONFIG__CONSOLE_K__SHIFT: u32 = 0x10;
pub const SMUIO_MCM_CONFIG__CONSOLE_A__SHIFT: u32 = 0x11;
pub const SMUIO_MCM_CONFIG__TOPOLOGY_ID__SHIFT: u32 = 0x12;
pub const SMUIO_MCM_CONFIG__DIE_ID_MASK: u32 = 0x00000003;
pub const SMUIO_MCM_CONFIG__PKG_TYPE_MASK: u32 = 0x0000003C;
pub const SMUIO_MCM_CONFIG__SOCKET_ID_MASK: u32 = 0x00000F00;
pub const SMUIO_MCM_CONFIG__PKG_SUBTYPE_MASK: u32 = 0x00001000;
pub const SMUIO_MCM_CONFIG__CONSOLE_K_MASK: u32 = 0x00010000;
pub const SMUIO_MCM_CONFIG__CONSOLE_A_MASK: u32 = 0x00020000;
pub const SMUIO_MCM_CONFIG__TOPOLOGY_ID_MASK: u32 = 0x007C0000;
//IP_DISCOVERY_VERSION
pub const IP_DISCOVERY_VERSION__IP_DISCOVERY_VERSION__SHIFT: u32 = 0x0;
pub const IP_DISCOVERY_VERSION__IP_DISCOVERY_VERSION_MASK: u32 = 0xFFFFFFFF;
//SCRATCH_REGISTER0
pub const SCRATCH_REGISTER0__ScratchPad0__SHIFT: u32 = 0x0;
pub const SCRATCH_REGISTER0__ScratchPad0_MASK: u32 = 0xFFFFFFFF;
//SCRATCH_REGISTER1
pub const SCRATCH_REGISTER1__ScratchPad1__SHIFT: u32 = 0x0;
pub const SCRATCH_REGISTER1__ScratchPad1_MASK: u32 = 0xFFFFFFFF;
//SCRATCH_REGISTER2
pub const SCRATCH_REGISTER2__ScratchPad2__SHIFT: u32 = 0x0;
pub const SCRATCH_REGISTER2__ScratchPad2_MASK: u32 = 0xFFFFFFFF;
//SCRATCH_REGISTER3
pub const SCRATCH_REGISTER3__ScratchPad3__SHIFT: u32 = 0x0;
pub const SCRATCH_REGISTER3__ScratchPad3_MASK: u32 = 0xFFFFFFFF;
//SCRATCH_REGISTER4
pub const SCRATCH_REGISTER4__ScratchPad4__SHIFT: u32 = 0x0;
pub const SCRATCH_REGISTER4__ScratchPad4_MASK: u32 = 0xFFFFFFFF;
//SCRATCH_REGISTER5
pub const SCRATCH_REGISTER5__ScratchPad5__SHIFT: u32 = 0x0;
pub const SCRATCH_REGISTER5__ScratchPad5_MASK: u32 = 0xFFFFFFFF;
//SCRATCH_REGISTER6
pub const SCRATCH_REGISTER6__ScratchPad6__SHIFT: u32 = 0x0;
pub const SCRATCH_REGISTER6__ScratchPad6_MASK: u32 = 0xFFFFFFFF;
//SCRATCH_REGISTER7
pub const SCRATCH_REGISTER7__ScratchPad7__SHIFT: u32 = 0x0;
pub const SCRATCH_REGISTER7__ScratchPad7_MASK: u32 = 0xFFFFFFFF;


// addressBlock: aid_smuio_smuio_gpio_SmuSmuioDec
//SMU_GPIOPAD_SW_INT_STAT
pub const SMU_GPIOPAD_SW_INT_STAT__SW_INT_STAT__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_SW_INT_STAT__SW_INT_STAT_MASK: u32 = 0x00000001;
//SMU_GPIOPAD_MASK
pub const SMU_GPIOPAD_MASK__GPIO_MASK__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_MASK__GPIO_MASK_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_A
pub const SMU_GPIOPAD_A__GPIO_A__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_A__GPIO_A_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_TXIMPSEL
pub const SMU_GPIOPAD_TXIMPSEL__GPIO_TXIMPSEL__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_TXIMPSEL__GPIO_TXIMPSEL_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_EN
pub const SMU_GPIOPAD_EN__GPIO_EN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_EN__GPIO_EN_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_Y
pub const SMU_GPIOPAD_Y__GPIO_Y__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_Y__GPIO_Y_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_RXEN
pub const SMU_GPIOPAD_RXEN__GPIO_RXEN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_RXEN__GPIO_RXEN_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_RCVR_SEL0
pub const SMU_GPIOPAD_RCVR_SEL0__GPIO_RCVR_SEL0__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_RCVR_SEL0__GPIO_RCVR_SEL0_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_RCVR_SEL1
pub const SMU_GPIOPAD_RCVR_SEL1__GPIO_RCVR_SEL1__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_RCVR_SEL1__GPIO_RCVR_SEL1_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_PU_EN
pub const SMU_GPIOPAD_PU_EN__GPIO_PU_EN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_PU_EN__GPIO_PU_EN_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_PD_EN
pub const SMU_GPIOPAD_PD_EN__GPIO_PD_EN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_PD_EN__GPIO_PD_EN_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_PINSTRAPS
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_0__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_1__SHIFT: u32 = 0x1;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_2__SHIFT: u32 = 0x2;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_3__SHIFT: u32 = 0x3;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_4__SHIFT: u32 = 0x4;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_5__SHIFT: u32 = 0x5;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_6__SHIFT: u32 = 0x6;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_7__SHIFT: u32 = 0x7;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_8__SHIFT: u32 = 0x8;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_9__SHIFT: u32 = 0x9;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_10__SHIFT: u32 = 0xa;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_11__SHIFT: u32 = 0xb;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_12__SHIFT: u32 = 0xc;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_13__SHIFT: u32 = 0xd;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_14__SHIFT: u32 = 0xe;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_15__SHIFT: u32 = 0xf;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_16__SHIFT: u32 = 0x10;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_17__SHIFT: u32 = 0x11;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_18__SHIFT: u32 = 0x12;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_19__SHIFT: u32 = 0x13;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_20__SHIFT: u32 = 0x14;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_21__SHIFT: u32 = 0x15;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_22__SHIFT: u32 = 0x16;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_23__SHIFT: u32 = 0x17;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_24__SHIFT: u32 = 0x18;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_25__SHIFT: u32 = 0x19;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_26__SHIFT: u32 = 0x1a;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_27__SHIFT: u32 = 0x1b;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_28__SHIFT: u32 = 0x1c;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_29__SHIFT: u32 = 0x1d;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_30__SHIFT: u32 = 0x1e;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_0_MASK: u32 = 0x00000001;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_1_MASK: u32 = 0x00000002;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_2_MASK: u32 = 0x00000004;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_3_MASK: u32 = 0x00000008;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_4_MASK: u32 = 0x00000010;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_5_MASK: u32 = 0x00000020;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_6_MASK: u32 = 0x00000040;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_7_MASK: u32 = 0x00000080;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_8_MASK: u32 = 0x00000100;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_9_MASK: u32 = 0x00000200;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_10_MASK: u32 = 0x00000400;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_11_MASK: u32 = 0x00000800;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_12_MASK: u32 = 0x00001000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_13_MASK: u32 = 0x00002000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_14_MASK: u32 = 0x00004000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_15_MASK: u32 = 0x00008000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_16_MASK: u32 = 0x00010000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_17_MASK: u32 = 0x00020000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_18_MASK: u32 = 0x00040000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_19_MASK: u32 = 0x00080000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_20_MASK: u32 = 0x00100000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_21_MASK: u32 = 0x00200000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_22_MASK: u32 = 0x00400000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_23_MASK: u32 = 0x00800000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_24_MASK: u32 = 0x01000000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_25_MASK: u32 = 0x02000000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_26_MASK: u32 = 0x04000000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_27_MASK: u32 = 0x08000000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_28_MASK: u32 = 0x10000000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_29_MASK: u32 = 0x20000000;
pub const SMU_GPIOPAD_PINSTRAPS__GPIO_PINSTRAP_30_MASK: u32 = 0x40000000;
//DFT_PINSTRAPS
pub const DFT_PINSTRAPS__DFT_PINSTRAPS__SHIFT: u32 = 0x0;
pub const DFT_PINSTRAPS__DFT_PINSTRAPS_MASK: u32 = 0x000003FF;
//SMU_GPIOPAD_INT_STAT_EN
pub const SMU_GPIOPAD_INT_STAT_EN__GPIO_INT_STAT_EN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_INT_STAT_EN__SW_INITIATED_INT_STAT_EN__SHIFT: u32 = 0x1f;
pub const SMU_GPIOPAD_INT_STAT_EN__GPIO_INT_STAT_EN_MASK: u32 = 0x1FFFFFFF;
pub const SMU_GPIOPAD_INT_STAT_EN__SW_INITIATED_INT_STAT_EN_MASK: u32 = 0x80000000;
//SMU_GPIOPAD_INT_STAT
pub const SMU_GPIOPAD_INT_STAT__GPIO_INT_STAT__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_INT_STAT__SW_INITIATED_INT_STAT__SHIFT: u32 = 0x1f;
pub const SMU_GPIOPAD_INT_STAT__GPIO_INT_STAT_MASK: u32 = 0x1FFFFFFF;
pub const SMU_GPIOPAD_INT_STAT__SW_INITIATED_INT_STAT_MASK: u32 = 0x80000000;
//SMU_GPIOPAD_INT_STAT_AK
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_0__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_1__SHIFT: u32 = 0x1;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_2__SHIFT: u32 = 0x2;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_3__SHIFT: u32 = 0x3;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_4__SHIFT: u32 = 0x4;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_5__SHIFT: u32 = 0x5;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_6__SHIFT: u32 = 0x6;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_7__SHIFT: u32 = 0x7;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_8__SHIFT: u32 = 0x8;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_9__SHIFT: u32 = 0x9;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_10__SHIFT: u32 = 0xa;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_11__SHIFT: u32 = 0xb;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_12__SHIFT: u32 = 0xc;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_13__SHIFT: u32 = 0xd;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_14__SHIFT: u32 = 0xe;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_15__SHIFT: u32 = 0xf;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_16__SHIFT: u32 = 0x10;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_17__SHIFT: u32 = 0x11;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_18__SHIFT: u32 = 0x12;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_19__SHIFT: u32 = 0x13;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_20__SHIFT: u32 = 0x14;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_21__SHIFT: u32 = 0x15;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_22__SHIFT: u32 = 0x16;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_23__SHIFT: u32 = 0x17;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_24__SHIFT: u32 = 0x18;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_25__SHIFT: u32 = 0x19;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_26__SHIFT: u32 = 0x1a;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_27__SHIFT: u32 = 0x1b;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_28__SHIFT: u32 = 0x1c;
pub const SMU_GPIOPAD_INT_STAT_AK__SW_INITIATED_INT_STAT_AK__SHIFT: u32 = 0x1f;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_0_MASK: u32 = 0x00000001;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_1_MASK: u32 = 0x00000002;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_2_MASK: u32 = 0x00000004;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_3_MASK: u32 = 0x00000008;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_4_MASK: u32 = 0x00000010;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_5_MASK: u32 = 0x00000020;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_6_MASK: u32 = 0x00000040;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_7_MASK: u32 = 0x00000080;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_8_MASK: u32 = 0x00000100;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_9_MASK: u32 = 0x00000200;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_10_MASK: u32 = 0x00000400;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_11_MASK: u32 = 0x00000800;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_12_MASK: u32 = 0x00001000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_13_MASK: u32 = 0x00002000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_14_MASK: u32 = 0x00004000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_15_MASK: u32 = 0x00008000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_16_MASK: u32 = 0x00010000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_17_MASK: u32 = 0x00020000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_18_MASK: u32 = 0x00040000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_19_MASK: u32 = 0x00080000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_20_MASK: u32 = 0x00100000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_21_MASK: u32 = 0x00200000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_22_MASK: u32 = 0x00400000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_23_MASK: u32 = 0x00800000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_24_MASK: u32 = 0x01000000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_25_MASK: u32 = 0x02000000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_26_MASK: u32 = 0x04000000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_27_MASK: u32 = 0x08000000;
pub const SMU_GPIOPAD_INT_STAT_AK__GPIO_INT_STAT_AK_28_MASK: u32 = 0x10000000;
pub const SMU_GPIOPAD_INT_STAT_AK__SW_INITIATED_INT_STAT_AK_MASK: u32 = 0x80000000;
//SMU_GPIOPAD_INT_EN
pub const SMU_GPIOPAD_INT_EN__GPIO_INT_EN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_INT_EN__SW_INITIATED_INT_EN__SHIFT: u32 = 0x1f;
pub const SMU_GPIOPAD_INT_EN__GPIO_INT_EN_MASK: u32 = 0x1FFFFFFF;
pub const SMU_GPIOPAD_INT_EN__SW_INITIATED_INT_EN_MASK: u32 = 0x80000000;
//SMU_GPIOPAD_INT_TYPE
pub const SMU_GPIOPAD_INT_TYPE__GPIO_INT_TYPE__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_INT_TYPE__SW_INITIATED_INT_TYPE__SHIFT: u32 = 0x1f;
pub const SMU_GPIOPAD_INT_TYPE__GPIO_INT_TYPE_MASK: u32 = 0x1FFFFFFF;
pub const SMU_GPIOPAD_INT_TYPE__SW_INITIATED_INT_TYPE_MASK: u32 = 0x80000000;
//SMU_GPIOPAD_INT_POLARITY
pub const SMU_GPIOPAD_INT_POLARITY__GPIO_INT_POLARITY__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_INT_POLARITY__SW_INITIATED_INT_POLARITY__SHIFT: u32 = 0x1f;
pub const SMU_GPIOPAD_INT_POLARITY__GPIO_INT_POLARITY_MASK: u32 = 0x1FFFFFFF;
pub const SMU_GPIOPAD_INT_POLARITY__SW_INITIATED_INT_POLARITY_MASK: u32 = 0x80000000;
//SMUIO_PCC_GPIO_SELECT
pub const SMUIO_PCC_GPIO_SELECT__GPIO__SHIFT: u32 = 0x0;
pub const SMUIO_PCC_GPIO_SELECT__GPIO_MASK: u32 = 0xFFFFFFFF;
//SMU_GPIOPAD_S0
pub const SMU_GPIOPAD_S0__GPIO_S0__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_S0__GPIO_S0_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_S1
pub const SMU_GPIOPAD_S1__GPIO_S1__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_S1__GPIO_S1_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_SCHMEN
pub const SMU_GPIOPAD_SCHMEN__GPIO_SCHMEN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_SCHMEN__GPIO_SCHMEN_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_SCL_EN
pub const SMU_GPIOPAD_SCL_EN__GPIO_SCL_EN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_SCL_EN__GPIO_SCL_EN_MASK: u32 = 0x7FFFFFFF;
//SMU_GPIOPAD_SDA_EN
pub const SMU_GPIOPAD_SDA_EN__GPIO_SDA_EN__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_SDA_EN__GPIO_SDA_EN_MASK: u32 = 0x7FFFFFFF;
//SMUIO_GPIO_INT0_SELECT
pub const SMUIO_GPIO_INT0_SELECT__GPIO_INT0_SELECT__SHIFT: u32 = 0x0;
pub const SMUIO_GPIO_INT0_SELECT__GPIO_INT0_SELECT_MASK: u32 = 0xFFFFFFFF;
//SMUIO_GPIO_INT1_SELECT
pub const SMUIO_GPIO_INT1_SELECT__GPIO_INT1_SELECT__SHIFT: u32 = 0x0;
pub const SMUIO_GPIO_INT1_SELECT__GPIO_INT1_SELECT_MASK: u32 = 0xFFFFFFFF;
//SMUIO_GPIO_INT2_SELECT
pub const SMUIO_GPIO_INT2_SELECT__GPIO_INT2_SELECT__SHIFT: u32 = 0x0;
pub const SMUIO_GPIO_INT2_SELECT__GPIO_INT2_SELECT_MASK: u32 = 0xFFFFFFFF;
//SMUIO_GPIO_INT3_SELECT
pub const SMUIO_GPIO_INT3_SELECT__GPIO_INT3_SELECT__SHIFT: u32 = 0x0;
pub const SMUIO_GPIO_INT3_SELECT__GPIO_INT3_SELECT_MASK: u32 = 0xFFFFFFFF;
//SMU_GPIOPAD_MP_INT0_STAT
pub const SMU_GPIOPAD_MP_INT0_STAT__GPIO_MP_INT0_STAT__SHIFT: u32 = 0x0;
pub const SMU_GPIOPAD_MP_INT0_STAT__GPIO_MP_INT0_STAT_MASK: u32 = 0x1FFFFFFF;


// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
