/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef RUST_FILEMAP_NATIVE_PRIMITIVES_H
#define RUST_FILEMAP_NATIVE_PRIMITIVES_H
/* Each boundary below exposes one exact native header/arch/atomic operation.
 * Original filemap.c algorithms are implemented in Rust. Native header
 * algorithms remain native and are explicitly excluded from Rust credit. */
#define RF_RET(type, name, args, expr) \
 type rust_filemap_##name args; type rust_filemap_##name args { return (expr); }
#define RF_VOID(name, args, expr) \
 void rust_filemap_##name args; void rust_filemap_##name args { expr; }
RF_VOID(atomic_set, (atomic_t *a, int v), atomic_set(a,v))
RF_VOID(spin_lock, (spinlock_t *p), spin_lock(p))
RF_VOID(spin_unlock, (spinlock_t *p), spin_unlock(p))
RF_VOID(rcu_read_lock, (void), rcu_read_lock())
RF_VOID(rcu_read_unlock, (void), rcu_read_unlock())
RF_RET(struct address_space *, folio_mapping_field, (const struct folio *f), f->mapping)
RF_RET(pgoff_t, folio_index, (const struct folio *f), f->index)
RF_VOID(folio_set_index, (struct folio *f, pgoff_t i), f->index = i)
RF_RET(atomic_t *, folio_mapcount_ptr, (struct folio *f), &f->_mapcount)
RF_RET(unsigned long, folio_nr_pages, (const struct folio *f), folio_nr_pages(f))
RF_RET(unsigned int, folio_order, (const struct folio *f), folio_order(f))
RF_RET(bool, folio_mapped, (const struct folio *f), folio_mapped(f))
RF_RET(int, folio_mapcount, (const struct folio *f), folio_mapcount(f))
RF_RET(int, folio_ref_count, (const struct folio *f), folio_ref_count(f))
RF_RET(bool, folio_test_locked, (const struct folio *f), folio_test_locked(f))
RF_RET(bool, folio_test_large, (const struct folio *f), folio_test_large(f))
RF_RET(bool, folio_test_hugetlb, (const struct folio *f), folio_test_hugetlb(f))
RF_RET(bool, folio_test_dirty, (const struct folio *f), folio_test_dirty(f))
RF_RET(bool, folio_test_swapbacked, (const struct folio *f), folio_test_swapbacked(f))
RF_RET(bool, folio_test_pmd_mappable, (struct folio *f), folio_test_pmd_mappable(f))
RF_VOID(folio_clear_idle, (struct folio *f), folio_clear_idle(f))
RF_RET(bool, folio_trylock, (struct folio *f), folio_trylock(f))
RF_VOID(folio_put, (struct folio *f), folio_put(f))
RF_VOID(folio_put_refs, (struct folio *f, int n), folio_put_refs(f,n))
RF_VOID(cond_resched, (void), cond_resched())
RF_VOID(lruvec_stat_mod_folio, (struct folio *f, enum node_stat_item i, int n), lruvec_stat_mod_folio(f,i,n))
RF_RET(pg_data_t *, folio_pgdat, (const struct folio *f), folio_pgdat(f))
RF_VOID(folio_set_mapping, (struct folio *f, struct address_space *m), f->mapping = m)
RF_RET(unsigned long *, folio_flags_field, (struct folio *f), &f->flags.f)
RF_RET(unsigned long *, folio_flags, (struct folio *f, unsigned n), folio_flags(f,n))
RF_RET(struct page *, folio_page0, (struct folio *f), &f->page)
RF_RET(struct page *, folio_page, (struct folio *f, unsigned long n), folio_page(f,n))
RF_RET(struct page *, page_nth, (struct page *p, long n), p + n)
RF_RET(struct folio *, page_folio, (struct page *p), page_folio(p))
RF_RET(struct page *, folio_file_page, (struct folio *f, pgoff_t i), folio_file_page(f,i))
RF_RET(size_t, folio_size, (const struct folio *f), folio_size(f))
RF_RET(unsigned int, folio_shift, (const struct folio *f), folio_shift(f))
RF_RET(loff_t, folio_pos, (const struct folio *f), folio_pos(f))
RF_RET(pgoff_t, folio_next_index, (const struct folio *f), folio_next_index(f))
RF_RET(bool, folio_contains, (const struct folio *f, pgoff_t i), folio_contains(f,i))
RF_RET(size_t, offset_in_folio, (const struct folio *f, loff_t p), offset_in_folio(f,p))
RF_VOID(folio_get, (struct folio *f), folio_get(f))
RF_RET(bool, folio_try_get, (struct folio *f), folio_try_get(f))
RF_VOID(folio_ref_add, (struct folio *f, int n), folio_ref_add(f,n))
RF_VOID(folio_ref_sub, (struct folio *f, int n), folio_ref_sub(f,n))
RF_VOID(folio_ref_dec, (struct folio *f), folio_ref_dec(f))
RF_VOID(folio_lock, (struct folio *f), folio_lock(f))
RF_VOID(folio_wait_locked, (struct folio *f), folio_wait_locked(f))
RF_RET(int, folio_wait_locked_killable, (struct folio *f), folio_wait_locked_killable(f))
RF_VOID(folio_wait_writeback, (struct folio *f), folio_wait_writeback(f))
RF_RET(bool, folio_xor_flags_has_waiters, (struct folio *f, unsigned long m), folio_xor_flags_has_waiters(f,m))
RF_RET(bool, folio_needs_release, (struct folio *f), folio_needs_release(f))
RF_RET(bool, folio_test_active, (const struct folio *f), folio_test_active(f))
RF_RET(bool, folio_test_idle, (const struct folio *f), folio_test_idle(f))
RF_RET(bool, folio_test_uptodate, (const struct folio *f), folio_test_uptodate(f))
RF_RET(bool, folio_test_readahead, (const struct folio *f), folio_test_readahead(f))
RF_RET(bool, folio_test_workingset, (const struct folio *f), folio_test_workingset(f))
RF_RET(bool, folio_test_writeback, (const struct folio *f), folio_test_writeback(f))
RF_RET(bool, folio_test_private_2, (const struct folio *f), folio_test_private_2(f))
RF_RET(bool, folio_test_dropbehind, (const struct folio *f), folio_test_dropbehind(f))
RF_RET(bool, folio_test_reclaim, (const struct folio *f), folio_test_reclaim(f))
RF_RET(bool, folio_test_clear_dropbehind, (struct folio *f), folio_test_clear_dropbehind(f))
RF_VOID(__folio_set_locked, (struct folio *f), __folio_set_locked(f))
RF_VOID(__folio_clear_locked, (struct folio *f), __folio_clear_locked(f))
RF_VOID(__folio_set_referenced, (struct folio *f), __folio_set_referenced(f))
RF_VOID(__folio_set_dropbehind, (struct folio *f), __folio_set_dropbehind(f))
RF_VOID(folio_clear_waiters, (struct folio *f), folio_clear_waiters(f))
RF_VOID(folio_set_waiters, (struct folio *f), folio_set_waiters(f))
RF_VOID(folio_clear_reclaim, (struct folio *f), folio_clear_reclaim(f))
RF_VOID(lruvec_stat_add_folio, (struct folio *f, enum node_stat_item i), lruvec_stat_add_folio(f,i))
RF_VOID(lruvec_stat_sub_folio, (struct folio *f, enum node_stat_item i), lruvec_stat_sub_folio(f,i))
RF_VOID(mod_node_page_state, (struct pglist_data *p, enum node_stat_item i, long n), mod_node_page_state(p,i,n))
RF_VOID(folio_batch_init, (struct folio_batch *b), folio_batch_init(b))
RF_RET(unsigned int, folio_batch_count, (const struct folio_batch *b), folio_batch_count(b))
RF_RET(unsigned int, folio_batch_add, (struct folio_batch *b, struct folio *f), folio_batch_add(b,f))
RF_VOID(folio_batch_release, (struct folio_batch *b), folio_batch_release(b))
RF_RET(bool, test_bit, (unsigned long n, const unsigned long *p), test_bit(n,p))
RF_RET(bool, test_and_clear_bit, (unsigned long n, unsigned long *p), test_and_clear_bit(n,p))
RF_RET(bool, test_and_set_bit, (unsigned long n, unsigned long *p), test_and_set_bit(n,p))
RF_VOID(clear_bit, (unsigned long n, unsigned long *p), clear_bit(n,p))
RF_VOID(clear_bit_unlock, (unsigned long n, unsigned long *p), clear_bit_unlock(n,p))
RF_RET(unsigned long, __ffs, (unsigned long n), __ffs(n))
RF_RET(void *, ERR_PTR, (long n), ERR_PTR(n))
RF_RET(bool, IS_ERR, (const void *p), IS_ERR(p))
RF_VOID(spin_lock_irq, (spinlock_t *p), spin_lock_irq(p))
RF_VOID(spin_unlock_irq, (spinlock_t *p), spin_unlock_irq(p))
RF_RET(unsigned long, spin_lock_irqsave, (spinlock_t *p), ({ unsigned long f; spin_lock_irqsave(p,f); f; }))
RF_VOID(spin_unlock_irqrestore, (spinlock_t *p, unsigned long f), spin_unlock_irqrestore(p,f))
RF_VOID(down_write_nested, (struct rw_semaphore *s, int n), down_write_nested(s,n))
RF_RET(struct task_struct *, current, (void), current)
RF_VOID(set_current_state, (int s), set_current_state(s))
RF_RET(int, signal_pending_state, (unsigned int s, struct task_struct *t), signal_pending_state(s,t))
RF_RET(int, fatal_signal_pending, (struct task_struct *t), fatal_signal_pending(t))
RF_RET(bool, in_task, (void), in_task())
RF_RET(bool, need_resched, (void), need_resched())
RF_VOID(cond_resched_rcu, (void), cond_resched_rcu())
RF_VOID(init_waitqueue_head, (wait_queue_head_t *q), init_waitqueue_head(q))
RF_VOID(init_wait, (wait_queue_entry_t *w), init_wait(w))
RF_RET(int, waitqueue_active, (wait_queue_head_t *q), waitqueue_active(q))
RF_VOID(__add_wait_queue_entry_tail, (wait_queue_head_t *q, wait_queue_entry_t *w), __add_wait_queue_entry_tail(q,w))
RF_VOID(__remove_wait_queue, (wait_queue_head_t *q, wait_queue_entry_t *w), __remove_wait_queue(q,w))
RF_RET(bool, wake_page_match, (struct wait_page_queue *q, struct wait_page_key *k), wake_page_match(q,k))
RF_RET(struct wait_page_queue *, wait_page_from_wait, (wait_queue_entry_t *w), container_of(w,struct wait_page_queue,wait))
RF_VOID(wait_flags_store_release, (wait_queue_entry_t *w, unsigned int f), smp_store_release(&w->flags,f))
RF_RET(unsigned int, wait_flags_load_acquire, (wait_queue_entry_t *w), smp_load_acquire(&w->flags))
RF_VOID(list_del_init_careful, (struct list_head *l), list_del_init_careful(l))
RF_RET(u32, hash_ptr, (const void *p, unsigned int b), hash_ptr(p,b))
RF_VOID(delayacct_thrashing_start, (bool *p), delayacct_thrashing_start(p))
RF_VOID(delayacct_thrashing_end, (bool *p), delayacct_thrashing_end(p))
RF_VOID(psi_memstall_enter, (unsigned long *p), psi_memstall_enter(p))
RF_VOID(psi_memstall_leave, (unsigned long *p), psi_memstall_leave(p))
RF_VOID(acct_reclaim_writeback, (struct folio *f), acct_reclaim_writeback(f))
RF_RET(struct xa_state, xa_state, (struct xarray *a, unsigned long i), (struct xa_state) __XA_STATE(a,i,0,0))
RF_RET(struct xa_state, xa_state_order, (struct xarray *a, unsigned long i, unsigned int o), ({ XA_STATE_ORDER(x,a,i,o); x; }))
RF_VOID(mapping_set_update, (struct xa_state *x, struct address_space *m), mapping_set_update(x,m))
RF_VOID(xas_set_order, (struct xa_state *x, unsigned long i, unsigned int o), xas_set_order(x,i,o))
RF_VOID(xas_set_err, (struct xa_state *x, long e), xas_set_err(x,e))
RF_RET(int, xas_error, (const struct xa_state *x), xas_error(x))
RF_VOID(xas_reset, (struct xa_state *x), xas_reset(x))
RF_VOID(xas_set, (struct xa_state *x, unsigned long i), xas_set(x,i))
RF_RET(bool, xas_retry, (struct xa_state *x, const void *p), xas_retry(x,p))
RF_RET(void *, xas_reload, (struct xa_state *x), xas_reload(x))
RF_RET(void *, xas_next, (struct xa_state *x), xas_next(x))
RF_RET(void *, xas_prev, (struct xa_state *x), xas_prev(x))
RF_RET(void *, xas_next_entry, (struct xa_state *x, unsigned long m), xas_next_entry(x,m))
RF_VOID(xas_advance, (struct xa_state *x, unsigned long i), xas_advance(x,i))
RF_RET(int, xas_get_order, (struct xa_state *x), xas_get_order(x))
RF_RET(int, xa_get_order, (struct xarray *x, unsigned long i), xa_get_order(x,i))
RF_VOID(xas_try_split, (struct xa_state *x, void *p, unsigned int o), xas_try_split(x,p,o))
RF_RET(unsigned int, xas_try_split_min_order, (unsigned int o), xas_try_split_min_order(o))
RF_RET(bool, xa_is_value, (const void *p), xa_is_value(p))
RF_RET(bool, xa_is_sibling, (const void *p), xa_is_sibling(p))
RF_VOID(xa_lock_irq, (struct xarray *x), xa_lock_irq(x))
RF_VOID(xa_unlock_irq, (struct xarray *x), xa_unlock_irq(x))
RF_VOID(xas_lock_irq, (struct xa_state *x), xas_lock_irq(x))
RF_VOID(xas_unlock_irq, (struct xa_state *x), xas_unlock_irq(x))
RF_RET(spinlock_t *, inode_lock_ptr, (struct inode *i), &i->i_lock)
RF_RET(struct address_space *, inode_mapping, (struct inode *i), i->i_mapping)
RF_RET(struct super_block *, inode_superblock, (struct inode *i), i->i_sb)
RF_RET(loff_t, inode_maxbytes, (struct inode *i), i->i_sb->s_maxbytes)
RF_RET(unsigned int, inode_blkbits, (struct inode *i), i->i_blkbits)
RF_RET(bool, inode_is_blk, (struct inode *i), S_ISBLK(i->i_mode))
RF_RET(struct file_ra_state *, file_ra, (struct file *f), &f->f_ra)
RF_RET(errseq_t, file_wb_err_read_once, (struct file *f), READ_ONCE(f->f_wb_err))
RF_RET(unsigned short, ra_mmap_miss_read_once, (const struct file_ra_state *r), READ_ONCE(r->mmap_miss))
RF_VOID(ra_mmap_miss_write_once, (struct file_ra_state *r, unsigned short n), WRITE_ONCE(r->mmap_miss,n))
RF_RET(bool, mapping_can_writeback, (struct address_space *m), mapping_can_writeback(m))
RF_RET(bool, mapping_tagged, (const struct address_space *m, xa_mark_t t), mapping_tagged(m,t))
RF_RET(bool, mapping_shrinkable, (const struct address_space *m), mapping_shrinkable(m))
RF_RET(int, mapping_exiting, (const struct address_space *m), mapping_exiting(m))
RF_RET(bool, mapping_large_folio_support, (const struct address_space *m), mapping_large_folio_support(m))
RF_RET(unsigned int, mapping_min_folio_order, (const struct address_space *m), mapping_min_folio_order(m))
RF_RET(unsigned int, mapping_max_folio_order, (const struct address_space *m), mapping_max_folio_order(m))
RF_RET(unsigned long, mapping_min_folio_nrbytes, (const struct address_space *m), mapping_min_folio_nrbytes(m))
RF_RET(size_t, mapping_max_folio_size, (const struct address_space *m), mapping_max_folio_size(m))
RF_RET(pgoff_t, mapping_align_index, (const struct address_space *m, pgoff_t i), mapping_align_index(m,i))
RF_RET(gfp_t, mapping_gfp_mask, (const struct address_space *m), mapping_gfp_mask(m))
RF_RET(gfp_t, mapping_gfp_constraint, (struct address_space *m, gfp_t g), mapping_gfp_constraint(m,g))
RF_RET(int, mapping_writably_mapped, (struct address_space *m), mapping_writably_mapped(m))
RF_RET(bool, shmem_mapping, (struct address_space *m), shmem_mapping(m))
RF_RET(bool, filemap_range_needs_writeback, (struct address_space *m, loff_t s, loff_t e), filemap_range_needs_writeback(m,s,e))
RF_VOID(filemap_invalidate_lock, (struct address_space *m), filemap_invalidate_lock(m))
RF_VOID(filemap_invalidate_unlock, (struct address_space *m), filemap_invalidate_unlock(m))
RF_VOID(filemap_invalidate_lock_shared, (struct address_space *m), filemap_invalidate_lock_shared(m))
RF_VOID(filemap_invalidate_unlock_shared, (struct address_space *m), filemap_invalidate_unlock_shared(m))
RF_RET(int, filemap_invalidate_trylock_shared, (struct address_space *m), filemap_invalidate_trylock_shared(m))
RF_RET(struct folio *, filemap_get_folio, (struct address_space *m, pgoff_t i), filemap_get_folio(m,i))
RF_RET(struct folio *, __filemap_get_folio, (struct address_space *m, pgoff_t i, fgf_t f, gfp_t g), __filemap_get_folio(m,i,f,g))
RF_RET(unsigned int, FGF_GET_ORDER, (fgf_t f), FGF_GET_ORDER(f))
#include "filemap_native_alloc_sites.h"
RF_RET(struct mem_cgroup *, root_mem_cgroup, (void), root_mem_cgroup)
RF_RET(struct mem_cgroup *, set_active_memcg, (struct mem_cgroup *m), set_active_memcg(m))
RF_RET(int, mem_cgroup_charge, (struct folio *f, struct mm_struct *m, gfp_t g), mem_cgroup_charge(f,m,g))
RF_VOID(mem_cgroup_uncharge, (struct folio *f), mem_cgroup_uncharge(f))
RF_VOID(mem_cgroup_replace_folio, (struct folio *o, struct folio *n), mem_cgroup_replace_folio(o,n))
RF_RET(struct bdi_writeback *, inode_to_wb, (struct inode *i), inode_to_wb(i))
RF_RET(struct bdi_writeback *, unlocked_inode_to_wb_begin, (struct inode *i, struct wb_lock_cookie *c), unlocked_inode_to_wb_begin(i,c))
RF_VOID(unlocked_inode_to_wb_end, (struct inode *i, struct wb_lock_cookie *c), unlocked_inode_to_wb_end(i,c))
RF_VOID(wb_stat_mod, (struct bdi_writeback *w, enum wb_stat_item i, long n), wb_stat_mod(w,i,n))
RF_VOID(wbc_attach_fdatawrite_inode, (struct writeback_control *w, struct inode *i), wbc_attach_fdatawrite_inode(w,i))
RF_VOID(wbc_detach_inode, (struct writeback_control *w), wbc_detach_inode(w))
RF_RET(loff_t, i_size_read, (const struct inode *i), i_size_read(i))
RF_VOID(i_size_write, (struct inode *i, loff_t p), i_size_write(i,p))
RF_RET(unsigned int, i_blocksize, (const struct inode *i), i_blocksize(i))
RF_RET(bool, IS_DAX, (struct inode *i), IS_DAX(i))
RF_VOID(inode_lock, (struct inode *i), inode_lock(i))
RF_VOID(inode_unlock, (struct inode *i), inode_unlock(i))
RF_VOID(mark_inode_dirty, (struct inode *i), mark_inode_dirty(i))
RF_VOID(file_accessed, (struct file *f), file_accessed(f))
RF_RET(size_t, iov_iter_count, (const struct iov_iter *i), iov_iter_count(i))
RF_VOID(iov_iter_truncate, (struct iov_iter *i, u64 n), iov_iter_truncate(i,n))
RF_RET(size_t, copy_folio_to_iter, (struct folio *f, size_t o, size_t n, struct iov_iter *i), copy_folio_to_iter(f,o,n,i))
RF_VOID(flush_dcache_folio, (struct folio *f), flush_dcache_folio(f))
RF_VOID(balance_dirty_pages_ratelimited, (struct address_space *m), balance_dirty_pages_ratelimited(m))
RF_RET(unsigned int, memalloc_noio_save, (void), memalloc_noio_save())
RF_VOID(memalloc_noio_restore, (unsigned int f), memalloc_noio_restore(f))
RF_RET(struct readahead_control, readahead_init, (struct file *f, struct file_ra_state *r, struct address_space *m, pgoff_t i), ({ DEFINE_READAHEAD(c,f,r,m,i); c; }))
RF_VOID(readahead_set_dropbehind, (struct readahead_control *r), r->dropbehind = 1)
RF_RET(bool, pipe_is_full, (const struct pipe_inode_info *p), pipe_is_full(p))
RF_RET(struct pipe_buffer *, pipe_head_buf, (struct pipe_inode_info *p), pipe_head_buf(p))
RF_RET(unsigned int, pipe_buf_usage, (const struct pipe_inode_info *p), pipe_buf_usage(p))
RF_RET(unsigned int, pipe_max_usage, (const struct pipe_inode_info *p), p->max_usage)
RF_VOID(pipe_increment_head, (struct pipe_inode_info *p), p->head++)
RF_VOID(init_sync_kiocb, (struct kiocb *i, struct file *f), init_sync_kiocb(i,f))
RF_RET(ssize_t, generic_write_sync, (struct kiocb *i, ssize_t n), generic_write_sync(i,n))
RF_RET(bool, fault_flag_allow_retry_first, (enum fault_flag f), fault_flag_allow_retry_first(f))
RF_VOID(release_fault_lock, (struct vm_fault *v), release_fault_lock(v))
RF_RET(void *, sysctl_zero, (void), SYSCTL_ZERO)
#ifdef CONFIG_SYSCTL
RF_VOID(register_sysctl_init, (const char *p, const struct ctl_table *t, size_t n), __register_sysctl_init(p,t,"filemap_sysctl_table",n))
#else
RF_VOID(register_sysctl_init, (const char *p, const struct ctl_table *t, size_t n), register_sysctl_init(p,t))
#endif
#ifdef CONFIG_NUMA
RF_RET(int, numa_node_id, (void), numa_node_id())
RF_RET(bool, cpuset_do_page_mem_spread, (void), cpuset_do_page_mem_spread())
RF_RET(unsigned int, read_mems_allowed_begin, (void), read_mems_allowed_begin())
RF_RET(bool, read_mems_allowed_retry, (unsigned int c), read_mems_allowed_retry(c))
RF_RET(struct folio *, __folio_alloc_node_noprof, (gfp_t g, unsigned int o, int n), __folio_alloc_node_noprof(g,o,n))
RF_RET(struct folio *, folio_alloc_noprof, (gfp_t g, unsigned int o), folio_alloc_noprof(g,o))
#endif
#ifdef CONFIG_MIGRATION
RF_RET(struct folio *, softleaf_to_folio, (softleaf_t e), softleaf_to_folio(e))
#endif
#ifdef CONFIG_MMU
RF_RET(struct vm_area_struct *, vmf_vma, (const struct vm_fault *v), v->vma)
RF_RET(pgoff_t, vmf_pgoff, (const struct vm_fault *v), v->pgoff)
RF_RET(gfp_t, vmf_gfp_mask, (const struct vm_fault *v), v->gfp_mask)
RF_RET(unsigned long, vmf_address, (const struct vm_fault *v), v->address)
RF_RET(struct file *, vma_file, (const struct vm_area_struct *v), v->vm_file)
RF_RET(struct mm_struct *, vma_mm, (const struct vm_area_struct *v), v->vm_mm)
RF_RET(vm_flags_t, vma_vm_flags, (const struct vm_area_struct *v), v->vm_flags)
RF_RET(unsigned long, vma_start, (const struct vm_area_struct *v), v->vm_start)
RF_RET(pgoff_t, vma_start_pgoff, (const struct vm_area_struct *v), vma_start_pgoff(v))
RF_RET(pgoff_t, vma_end_pgoff, (const struct vm_area_struct *v), vma_end_pgoff(v))
RF_VOID(vma_set_vm_ops, (struct vm_area_struct *v, const struct vm_operations_struct *o), v->vm_ops = o)
RF_RET(bool, vma_is_shared_maywrite, (const struct vm_area_struct *v), vma_is_shared_maywrite(v))
RF_RET(bool, is_shared_maywrite, (const vma_flags_t *f), is_shared_maywrite(f))
RF_RET(unsigned int, exec_folio_order, (void), exec_folio_order())
RF_RET(int, get_order, (unsigned long n), get_order(n))
RF_RET(struct file *, maybe_unlock_mmap_for_io, (struct vm_fault *v, struct file *f), maybe_unlock_mmap_for_io(v,f))
RF_VOID(count_vm_event, (enum vm_event_item i), count_vm_event(i))
RF_VOID(count_memcg_event_mm, (struct mm_struct *m, enum vm_event_item i), count_memcg_event_mm(m,i))
RF_RET(pte_t *, pte_offset_map_ro_nolock, (struct mm_struct *m, pmd_t *p, unsigned long a, spinlock_t **l), pte_offset_map_ro_nolock(m,p,a,l))
RF_RET(pte_t *, pte_offset_map_lock, (struct mm_struct *m, pmd_t *p, unsigned long a, spinlock_t **l), pte_offset_map_lock(m,p,a,l))
RF_RET(pte_t, ptep_get_lockless, (pte_t *p), ptep_get_lockless(p))
RF_RET(pte_t, ptep_get, (pte_t *p), ptep_get(p))
RF_RET(bool, pte_none, (pte_t p), pte_none(p))
RF_RET(int, pmd_none, (pmd_t p), pmd_none(p))
RF_RET(int, pmd_trans_huge, (pmd_t p), pmd_trans_huge(p))
RF_VOID(pte_unmap, (pte_t *p), pte_unmap(p))
RF_VOID(pte_unmap_unlock, (pte_t *p, spinlock_t *l), pte_unmap_unlock(p,l))
RF_RET(bool, vmf_has_prealloc_pte, (struct vm_fault *v), !!v->prealloc_pte)
RF_VOID(pmd_install_vmf, (struct mm_struct *m, struct vm_fault *v), pmd_install(m,v->pmd,&v->prealloc_pte))
RF_RET(bool, PageHWPoison, (struct page *p), PageHWPoison(p))
RF_RET(bool, folio_within_vma, (struct folio *f, struct vm_area_struct *v), folio_within_vma(f,v))
RF_RET(unsigned int, mm_counter_file, (struct folio *f), mm_counter_file(f))
RF_VOID(add_mm_counter, (struct mm_struct *m, int i, long n), add_mm_counter(m,i,n))
RF_VOID(sb_start_pagefault, (struct super_block *s), sb_start_pagefault(s))
RF_VOID(sb_end_pagefault, (struct super_block *s), sb_end_pagefault(s))
#endif
#ifdef CONFIG_CACHESTAT_SYSCALL
RF_RET(struct fd, fdget, (unsigned int n), fdget(n))
RF_VOID(fdput, (struct fd f), fdput(f))
RF_RET(bool, fd_empty, (struct fd f), fd_empty(f))
RF_RET(struct file *, fd_file, (struct fd f), fd_file(f))
RF_RET(unsigned long, copy_from_user, (void *d, const void __user *s, unsigned long n), copy_from_user(d,s,n))
RF_RET(unsigned long, copy_to_user, (void __user *d, const void *s, unsigned long n), copy_to_user(d,s,n))
RF_RET(bool, is_file_hugepages, (struct file *f), is_file_hugepages(f))
RF_VOID(mem_cgroup_flush_stats_ratelimited, (struct mem_cgroup *m), mem_cgroup_flush_stats_ratelimited(m))
#ifdef CONFIG_SWAP
RF_RET(swp_entry_t, radix_to_swp_entry, (void *p), radix_to_swp_entry(p))
RF_RET(bool, softleaf_is_swap, (swp_entry_t e), softleaf_is_swap(e))
#endif
#endif
RF_VOID(trace_mm_filemap_delete_from_page_cache, (struct folio *f), trace_mm_filemap_delete_from_page_cache(f))
RF_VOID(trace_mm_filemap_add_to_page_cache, (struct folio *f), trace_mm_filemap_add_to_page_cache(f))
RF_VOID(trace_filemap_set_wb_err, (struct address_space *m, errseq_t e), trace_filemap_set_wb_err(m,e))
RF_VOID(trace_file_check_and_advance_wb_err, (struct file *f, errseq_t e), trace_file_check_and_advance_wb_err(f,e))
RF_VOID(trace_mm_filemap_get_pages, (struct address_space *m, pgoff_t s, pgoff_t e), trace_mm_filemap_get_pages(m,s,e))
#ifdef CONFIG_MMU
RF_VOID(trace_mm_filemap_fault, (struct address_space *m, pgoff_t i), trace_mm_filemap_fault(m,i))
RF_VOID(trace_mm_filemap_map_pages, (struct address_space *m, pgoff_t s, pgoff_t e), trace_mm_filemap_map_pages(m,s,e))
#endif
RF_RET(struct address_space *, file_mapping, (const struct file *f), f->f_mapping)
RF_RET(spinlock_t *, file_lock_ptr, (struct file *f), &f->f_lock)
RF_RET(errseq_t *, file_wb_err_ptr, (struct file *f), &f->f_wb_err)
RF_RET(fmode_t, file_mode, (const struct file *f), f->f_mode)
RF_RET(struct inode *, mapping_host, (const struct address_space *m), m->host)
RF_RET(const struct address_space_operations *, mapping_aops, (const struct address_space *m), m->a_ops)
RF_RET(struct xarray *, mapping_i_pages, (struct address_space *m), &m->i_pages)
RF_RET(unsigned long *, mapping_nrpages, (struct address_space *m), &m->nrpages)
RF_RET(unsigned long *, mapping_flags, (struct address_space *m), &m->flags)
RF_RET(errseq_t *, mapping_wb_err, (struct address_space *m), &m->wb_err)
RF_RET(struct rw_semaphore *, mapping_invalidate_lock, (struct address_space *m), &m->invalidate_lock)
RF_RET(bool, try_to_free_buffers, (struct folio *f), try_to_free_buffers(f))
RF_RET(bool, file_owner_or_capable, (const struct file *f), file_owner_or_capable(f))

RF_VOID(sysctl_set_procname, (struct ctl_table *t, const char *p), t->procname = p)
RF_VOID(sysctl_set_data, (struct ctl_table *t, void *p), t->data = p)
RF_VOID(sysctl_set_maxlen, (struct ctl_table *t, int n), t->maxlen = n)
RF_VOID(sysctl_set_mode, (struct ctl_table *t, umode_t m), t->mode = m)
RF_VOID(sysctl_set_proc_handler, (struct ctl_table *t, proc_handler *p), t->proc_handler = p)
RF_VOID(sysctl_set_extra1, (struct ctl_table *t, void *p), t->extra1 = p)
#ifdef CONFIG_NUMA
RF_RET(int, cpuset_mem_spread_node, (void), cpuset_mem_spread_node())
#endif

#undef RF_RET
#undef RF_VOID
#endif
