/* Configured header constants; no guessed numeric ABI values. */
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_WRITE = FAULT_FLAG_WRITE;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_MKWRITE = FAULT_FLAG_MKWRITE;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_VMA_LOCK = FAULT_FLAG_VMA_LOCK;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_UNSHARE = FAULT_FLAG_UNSHARE;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_ORIG_PTE_VALID = FAULT_FLAG_ORIG_PTE_VALID;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_TRIED = FAULT_FLAG_TRIED;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_RETRY_NOWAIT = FAULT_FLAG_RETRY_NOWAIT;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_INSTRUCTION = FAULT_FLAG_INSTRUCTION;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_REMOTE = FAULT_FLAG_REMOTE;
static const unsigned int RUST_MEMORY_FAULT_FAULT_FLAG_USER = FAULT_FLAG_USER;
static const unsigned int RUST_MEMORY_FAULT_FOLL_WRITE = FOLL_WRITE;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_SIGBUS = VM_FAULT_SIGBUS;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_ERROR = VM_FAULT_ERROR;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_NOPAGE = VM_FAULT_NOPAGE;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_LOCKED = VM_FAULT_LOCKED;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_COMPLETED = VM_FAULT_COMPLETED;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_RETRY = VM_FAULT_RETRY;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_OOM = VM_FAULT_OOM;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_HWPOISON = VM_FAULT_HWPOISON;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_SIGSEGV = VM_FAULT_SIGSEGV;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_MAJOR = VM_FAULT_MAJOR;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_FALLBACK = VM_FAULT_FALLBACK;
static const unsigned int RUST_MEMORY_FAULT_VM_FAULT_DONE_COW = VM_FAULT_DONE_COW;
static const unsigned long RUST_MEMORY_FAULT_VM_SHARED = VM_SHARED;
static const unsigned long RUST_MEMORY_FAULT_VM_MAYSHARE = VM_MAYSHARE;
static const unsigned long RUST_MEMORY_FAULT_VM_LOCKED = VM_LOCKED;
static const unsigned long RUST_MEMORY_FAULT_VM_WRITE = VM_WRITE;
static const unsigned long RUST_MEMORY_FAULT_VM_MAYWRITE = VM_MAYWRITE;
static const unsigned long RUST_MEMORY_FAULT_VM_DROPPABLE = VM_DROPPABLE;
static const unsigned long RUST_MEMORY_FAULT_VM_IO = VM_IO;
static const unsigned long RUST_MEMORY_FAULT_VM_PFNMAP = VM_PFNMAP;
static const unsigned long RUST_MEMORY_FAULT_VM_UFFD_WP = VM_UFFD_WP;
static const unsigned long RUST_MEMORY_FAULT_VM_UFFD_MISSING = VM_UFFD_MISSING;
static const unsigned long RUST_MEMORY_FAULT_VM_UFFD_RWP = VM_UFFD_RWP;
static const unsigned long RUST_MEMORY_FAULT_PTE_MARKER_POISONED = PTE_MARKER_POISONED;
static const unsigned long RUST_MEMORY_FAULT_PTE_MARKER_GUARD = PTE_MARKER_GUARD;
static const unsigned long RUST_MEMORY_FAULT_PTRS_PER_PTE = PTRS_PER_PTE;
static const unsigned long RUST_MEMORY_FAULT_PUD_MASK = PUD_MASK;
static const unsigned int RUST_MEMORY_FAULT_PGREUSE = PGREUSE;
static const unsigned int RUST_MEMORY_FAULT_PGMAJFAULT = PGMAJFAULT;
static const unsigned int RUST_MEMORY_FAULT_PGFAULT = PGFAULT;
#ifdef CONFIG_NUMA_BALANCING
static const unsigned int RUST_MEMORY_FAULT_NUMA_HINT_FAULTS = NUMA_HINT_FAULTS;
#endif
#ifdef CONFIG_NUMA_BALANCING
static const unsigned int RUST_MEMORY_FAULT_NUMA_HINT_FAULTS_LOCAL = NUMA_HINT_FAULTS_LOCAL;
#endif
static const unsigned int RUST_MEMORY_FAULT_PMD_ORDER = PMD_ORDER;
static const unsigned int RUST_MEMORY_FAULT_PUD_ORDER = PUD_ORDER;
static const unsigned int RUST_MEMORY_FAULT_RMAP_NONE = RMAP_NONE;
static const unsigned int RUST_MEMORY_FAULT_RMAP_EXCLUSIVE = RMAP_EXCLUSIVE;
static const unsigned int RUST_MEMORY_FAULT_MMU_NOTIFY_CLEAR = MMU_NOTIFY_CLEAR;
static const unsigned int RUST_MEMORY_FAULT_TVA_PAGEFAULT = TVA_PAGEFAULT;
static const unsigned int RUST_MEMORY_FAULT_GFP_HIGHUSER_MOVABLE = GFP_HIGHUSER_MOVABLE;
static const unsigned int RUST_MEMORY_FAULT_ZAP_FLAG_DROP_MARKER = ZAP_FLAG_DROP_MARKER;
static const unsigned long RUST_MEMORY_FAULT_SWP_SYNCHRONOUS_IO = SWP_SYNCHRONOUS_IO;
static const unsigned long RUST_MEMORY_FAULT_SWP_STABLE_WRITES = SWP_STABLE_WRITES;
static const int RUST_MEMORY_FAULT_EHWPOISON = EHWPOISON;
static const int RUST_MEMORY_FAULT_EAGAIN = EAGAIN;
static const int RUST_MEMORY_FAULT_EINVAL = EINVAL;
static const int RUST_MEMORY_FAULT_ENOMEM = ENOMEM;
static const int RUST_MEMORY_FAULT_EFAULT = EFAULT;
static const int RUST_MEMORY_FAULT_MM_ANONPAGES = MM_ANONPAGES;
static const int RUST_MEMORY_FAULT_MM_SWAPENTS = MM_SWAPENTS;
static const int RUST_MEMORY_FAULT_NUMA_NO_NODE = NUMA_NO_NODE;
static const int RUST_MEMORY_FAULT_TNF_NO_GROUP = TNF_NO_GROUP;
static const int RUST_MEMORY_FAULT_TNF_SHARED = TNF_SHARED;
static const int RUST_MEMORY_FAULT_TNF_FAULT_LOCAL = TNF_FAULT_LOCAL;
static const int RUST_MEMORY_FAULT_TNF_MIGRATE_FAIL = TNF_MIGRATE_FAIL;
static const int RUST_MEMORY_FAULT_TNF_MIGRATED = TNF_MIGRATED;
static const int RUST_MEMORY_FAULT_LAST_CPUPID_MASK = LAST_CPUPID_MASK;
static const unsigned int RUST_MEMORY_FAULT_PGTABLE_LEVEL_PTE = PGTABLE_LEVEL_PTE;
static const unsigned int RUST_MEMORY_FAULT_PGTABLE_LEVEL_PMD = PGTABLE_LEVEL_PMD;
static const unsigned int RUST_MEMORY_FAULT_PERF_COUNT_SW_PAGE_FAULTS_MAJ = PERF_COUNT_SW_PAGE_FAULTS_MAJ;
static const unsigned int RUST_MEMORY_FAULT_PERF_COUNT_SW_PAGE_FAULTS_MIN = PERF_COUNT_SW_PAGE_FAULTS_MIN;
static const gfp_t RUST_MEMORY_FAULT_GFP_FS = __GFP_FS;
static const gfp_t RUST_MEMORY_FAULT_GFP_IO = __GFP_IO;
static const int RUST_MEMORY_FAULT_LAST_CPUPID_RESET = (1 << LAST_CPUPID_SHIFT) - 1;
#if defined(CONFIG_KSM)
static const unsigned int RUST_MEMORY_FAULT_COW_KSM = COW_KSM;
#endif
#if defined(CONFIG_TRANSPARENT_HUGEPAGE)
static const unsigned int RUST_MEMORY_FAULT_THP_FILE_MAPPED = THP_FILE_MAPPED;
#endif
#if defined(CONFIG_TRANSPARENT_HUGEPAGE)
static const unsigned long RUST_MEMORY_FAULT_HPAGE_PMD_MASK = HPAGE_PMD_MASK;
#endif
#if defined(CONFIG_TRANSPARENT_HUGEPAGE)
static const unsigned int RUST_MEMORY_FAULT_HPAGE_PMD_NR = HPAGE_PMD_NR;
#endif
#if defined(CONFIG_TRANSPARENT_HUGEPAGE)
static const unsigned int RUST_MEMORY_FAULT_MTHP_STAT_ANON_FAULT_FALLBACK_CHARGE = MTHP_STAT_ANON_FAULT_FALLBACK_CHARGE;
#endif
#if defined(CONFIG_TRANSPARENT_HUGEPAGE)
static const unsigned int RUST_MEMORY_FAULT_MTHP_STAT_ANON_FAULT_FALLBACK = MTHP_STAT_ANON_FAULT_FALLBACK;
#endif
static const unsigned int RUST_MEMORY_FAULT_MTHP_STAT_ANON_FAULT_ALLOC = MTHP_STAT_ANON_FAULT_ALLOC;
#if defined(CONFIG_TRANSPARENT_HUGEPAGE) || defined(CONFIG_HUGETLBFS)
static const unsigned int RUST_MEMORY_FAULT_PROCESS_PAGES_NON_PREEMPT_BATCH = PROCESS_PAGES_NON_PREEMPT_BATCH;
#endif
#if defined(CONFIG_TRANSPARENT_HUGEPAGE) || defined(CONFIG_HUGETLBFS)
static const unsigned int RUST_MEMORY_FAULT_MAX_ORDER_NR_PAGES = MAX_ORDER_NR_PAGES;
#endif
#if defined(CONFIG_SPLIT_PTE_PTLOCKS) && ALLOC_SPLIT_PTLOCKS
static const slab_flags_t RUST_MEMORY_FAULT_SLAB_PANIC = SLAB_PANIC;
#endif
