/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef RUST_MEMORY_FAULTS_PRIMITIVES_H
#define RUST_MEMORY_FAULTS_PRIMITIVES_H
/* Explicit architecture/compiler primitives and transitive header-algorithm
 * boundaries. No original memory.c algorithm is implemented or forwarded here.
 * Include after the common RM_RET/RM_VOID definitions. */
#include "memory_faults_constants.h"
#include "memory_faults_diagnostics.h"
RM_VOID(zap_set_skip_cows, (struct zap_details *d, bool v), d->skip_cows = v)
RM_RET(struct address_space *, folio_mapping, (struct folio *f), f->mapping)
RM_RET(pgoff_t, folio_index, (struct folio *f), f->index)
RM_RET(swp_entry_t, folio_swap, (struct folio *f), f->swap)
RM_RET(unsigned long, swap_flags, (struct swap_info_struct *s), data_race(s->flags))
RM_RET(struct mm_struct *, current_mm, (void), current->mm)
RM_VOID(current_maj_flt_inc, (void), current->maj_flt++)
RM_VOID(current_min_flt_inc, (void), current->min_flt++)
RM_VOID(set_current_running, (void), __set_current_state(TASK_RUNNING))
#ifdef CONFIG_LRU_GEN
RM_VOID(current_set_in_lru_fault, (bool v), current->in_lru_fault = v)
#endif
RM_RET(bool, arch_has_hw_pte_young, (void), arch_has_hw_pte_young())
RM_RET(bool, pte_same, (pte_t a, pte_t b), pte_same(a, b))
RM_RET(pte_t, pte_sw_mkyoung, (pte_t p), pte_sw_mkyoung(p))
RM_RET(bool, pte_soft_dirty, (pte_t p), pte_soft_dirty(p))
RM_RET(bool, pte_protnone, (pte_t p), pte_protnone(p))
RM_RET(pte_t, pte_advance_pfn, (pte_t p, unsigned long n), pte_advance_pfn(p, n))
RM_RET(pte_t, pte_move_swp_offset, (pte_t p, long n), pte_move_swp_offset(p, n))
RM_RET(pte_t, ptep_get_lockless, (pte_t *p), ptep_get_lockless(p))
RM_RET(pte_t *, pte_offset_map, (pmd_t *p, unsigned long a), pte_offset_map(p, a))
RM_RET(pte_t, ptep_clear_flush, (struct vm_area_struct *v, unsigned long a, pte_t *p), ptep_clear_flush(v, a, p))
RM_VOID(pte_clear, (struct mm_struct *m, unsigned long a, pte_t *p), pte_clear(m, a, p))
RM_RET(pgprot_t, pte_pgprot, (pte_t p), pte_pgprot(p))
RM_RET(pgprot_t, pmd_pgprot, (pmd_t p), pmd_pgprot(p))
RM_RET(pgprot_t, pud_pgprot, (pud_t p), pud_pgprot(p))
RM_RET(unsigned long, pgprot_val, (pgprot_t p), pgprot_val(p))
RM_RET(bool, pte_needs_soft_dirty_wp, (struct vm_area_struct *v, pte_t p), pte_needs_soft_dirty_wp(v, p))
RM_RET(pte_t, ptep_modify_prot_start, (struct vm_area_struct *v, unsigned long a, pte_t *p), ptep_modify_prot_start(v, a, p))
RM_VOID(ptep_modify_prot_commit, (struct vm_area_struct *v, unsigned long a, pte_t *p, pte_t o, pte_t n), ptep_modify_prot_commit(v, a, p, o, n))
RM_RET(pmd_t, pmdp_get_lockless, (pmd_t *p), pmdp_get_lockless(p))
RM_RET(bool, pmd_write, (pmd_t p), pmd_write(p))
RM_RET(bool, pmd_protnone, (pmd_t p), pmd_protnone(p))
RM_RET(bool, pud_write, (pud_t p), pud_write(p))
RM_RET(bool, pud_trans_unstable, (pud_t *p), pud_trans_unstable(p))
RM_RET(spinlock_t *, pud_lock, (struct mm_struct *m, pud_t *p), pud_lock(m, p))
RM_VOID(update_mmu_cache_range, (struct vm_fault *f, struct vm_area_struct *v, unsigned long a, pte_t *p, unsigned int n), update_mmu_cache_range(f, v, a, p, n))
RM_VOID(update_mmu_tlb, (struct vm_area_struct *v, unsigned long a, pte_t *p), update_mmu_tlb(v, a, p))
RM_VOID(update_mmu_tlb_range, (struct vm_area_struct *v, unsigned long a, pte_t *p, unsigned int n), update_mmu_tlb_range(v, a, p, n))
RM_VOID(update_mmu_cache_pmd, (struct vm_area_struct *v, unsigned long a, pmd_t *p), update_mmu_cache_pmd(v, a, p))
RM_VOID(flush_tlb_fix_spurious_fault, (struct vm_area_struct *v, unsigned long a, pte_t *p), flush_tlb_fix_spurious_fault(v, a, p))
RM_VOID(flush_tlb_fix_spurious_fault_pmd, (struct vm_area_struct *v, unsigned long a, pmd_t *p), flush_tlb_fix_spurious_fault_pmd(v, a, p))
RM_VOID(flush_tlb_page, (struct vm_area_struct *v, unsigned long a), flush_tlb_page(v, a))
RM_VOID(flush_cache_page, (struct vm_area_struct *v, unsigned long a, unsigned long p), flush_cache_page(v, a, p))
RM_VOID(flush_dcache_page, (struct page *p), flush_dcache_page(p))
RM_VOID(flush_icache_pages, (struct vm_area_struct *v, struct page *p, unsigned int n), flush_icache_pages(v, p, n))
RM_VOID(barrier, (void), barrier())
RM_VOID(rcu_read_lock, (void), rcu_read_lock())
RM_VOID(rcu_read_unlock, (void), rcu_read_unlock())
RM_RET(void *, kmap_local_page, (struct page *p), kmap_local_page(p))
RM_RET(void *, kmap_local_folio, (struct folio *f, unsigned long o), kmap_local_folio(f, o))
RM_VOID(kunmap_local, (const void *p), kunmap_local(p))
RM_VOID(pagefault_disable, (void), pagefault_disable())
RM_VOID(pagefault_enable, (void), pagefault_enable())
RM_RET(bool, pagefault_disabled, (void), pagefault_disabled())
RM_RET(unsigned long, copy_from_user_inatomic, (void *d, const void __user *s, unsigned long n), __copy_from_user_inatomic(d, s, n))
RM_RET(unsigned long, copy_from_user, (void *d, const void __user *s, unsigned long n), copy_from_user(d, s, n))
RM_VOID(clear_page, (void *p), clear_page(p))
RM_VOID(copy_to_user_page, (struct vm_area_struct *v, struct page *p, unsigned long a, void *d, const void *s, unsigned long n), copy_to_user_page(v, p, a, d, s, n))
RM_VOID(copy_from_user_page, (struct vm_area_struct *v, struct page *p, unsigned long a, void *d, const void *s, unsigned long n), copy_from_user_page(v, p, a, d, s, n))
RM_VOID(kmsan_copy_page_meta, (struct page *d, struct page *s), kmsan_copy_page_meta(d, s))
RM_VOID(delayacct_wpcopy_start, (void), delayacct_wpcopy_start())
RM_VOID(delayacct_wpcopy_end, (void), delayacct_wpcopy_end())
RM_RET(gfp_t, mapping_gfp_mask, (struct address_space *m), mapping_gfp_mask(m))
RM_RET(bool, is_swapfile, (struct inode *i), IS_SWAPFILE(i))
RM_RET(int, anon_vma_prepare, (struct vm_area_struct *v), __anon_vma_prepare(v))
RM_RET(int, file_update_time, (struct file *f), file_update_time(f))
RM_RET(struct file *, maybe_unlock_mmap_for_io, (struct vm_fault *v, struct file *f), maybe_unlock_mmap_for_io(v, f))
RM_VOID(balance_dirty_pages_ratelimited, (struct address_space *m), balance_dirty_pages_ratelimited(m))
RM_VOID(fput, (struct file *f), fput(f))
RM_RET(bool, is_fsdax_page, (struct page *p), is_fsdax_page(p))
RM_RET(bool, folio_try_get, (struct folio *f), folio_try_get(f))
RM_VOID(folio_lock, (struct folio *f), folio_lock(f))
RM_RET(vm_fault_t, folio_lock_or_retry, (struct folio *f, struct vm_fault *v), folio_lock_or_retry(f, v))
RM_RET(bool, folio_mapped, (struct folio *f), folio_mapped(f))
RM_RET(bool, folio_test_ksm, (struct folio *f), folio_test_ksm(f))
RM_RET(bool, folio_test_lru, (struct folio *f), folio_test_lru(f))
RM_RET(bool, folio_test_swapcache, (struct folio *f), folio_test_swapcache(f))
RM_RET(bool, folio_test_mlocked, (struct folio *f), folio_test_mlocked(f))
RM_RET(bool, folio_test_mappedtodisk, (struct folio *f), folio_test_mappedtodisk(f))
RM_RET(bool, folio_test_uptodate, (struct folio *f), folio_test_uptodate(f))
RM_RET(bool, folio_test_writeback, (struct folio *f), folio_test_writeback(f))
RM_RET(unsigned long, folio_nr_pages, (struct folio *f), folio_nr_pages(f))
RM_RET(unsigned int, folio_order, (struct folio *f), folio_order(f))
RM_RET(unsigned long, folio_page_idx, (struct folio *f, struct page *p), folio_page_idx(f, p))
RM_RET(unsigned long, folio_size, (struct folio *f), folio_size(f))
RM_RET(unsigned long, folio_pfn, (struct folio *f), folio_pfn(f))
RM_RET(pgoff_t, folio_next_index, (struct folio *f), folio_next_index(f))
RM_RET(struct address_space *, folio_raw_mapping, (struct folio *f), folio_raw_mapping(f))
RM_RET(int, folio_xchg_last_cpupid, (struct folio *f, int c), folio_xchg_last_cpupid(f, c))
RM_RET(int, folio_last_cpupid, (struct folio *f), folio_last_cpupid(f))
RM_RET(int, folio_nid, (struct folio *f), folio_nid(f))
RM_RET(bool, folio_use_access_time, (struct folio *f), folio_use_access_time(f))
RM_RET(bool, folio_maybe_mapped_shared, (struct folio *f), folio_maybe_mapped_shared(f))
RM_RET(bool, folio_is_zone_device, (struct folio *f), folio_is_zone_device(f))
RM_RET(struct folio *, pfn_folio, (unsigned long p), pfn_folio(p))
RM_VOID(folio_mark_dirty_lock, (struct folio *f), folio_mark_dirty_lock(f))
RM_VOID(folio_release_kmap, (struct folio *f, void *a), folio_release_kmap(f, a))
RM_VOID(folio_move_anon_rmap, (struct folio *f, struct vm_area_struct *v), folio_move_anon_rmap(f, v))
RM_VOID(folio_add_anon_rmap_ptes, (struct folio *f, struct page *p, int n, struct vm_area_struct *v, unsigned long a, rmap_t r), folio_add_anon_rmap_ptes(f, p, n, v, a, r))
RM_VOID(folio_add_file_rmap_ptes, (struct folio *f, struct page *p, int n, struct vm_area_struct *v), folio_add_file_rmap_ptes(f, p, n, v))
RM_VOID(folio_add_file_rmap_pmd, (struct folio *f, struct page *p, struct vm_area_struct *v), folio_add_file_rmap_pmd(f, p, v))
RM_RET(struct page *, folio_file_page, (struct folio *f, pgoff_t i), folio_file_page(f, i))
RM_RET(bool, folio_matches_swap_entry, (struct folio *f, swp_entry_t e), folio_matches_swap_entry(f, e))
RM_VOID(folio_put_swap, (struct folio *f, struct page *p), folio_put_swap(f, p))
RM_RET(bool, folio_free_swap, (struct folio *f), folio_free_swap(f))
RM_VOID(free_swap_cache, (struct folio *f), free_swap_cache(f))
RM_RET(swp_entry_t, folio_swap_entry, (swp_entry_t e, struct folio *f), folio_swap(e, f))
RM_VOID(arch_swap_restore, (swp_entry_t e, struct folio *f), arch_swap_restore(e, f))
RM_VOID(arch_do_swap_page_nr, (struct mm_struct *m, struct vm_area_struct *v, unsigned long a, pte_t p, pte_t o, int n), arch_do_swap_page_nr(m, v, a, p, o, n))
RM_RET(struct folio *, ksm_might_need_to_copy, (struct folio *f, struct vm_area_struct *v, unsigned long a), ksm_might_need_to_copy(f, v, a))
RM_RET(bool, page_hwpoison, (struct page *p), PageHWPoison(p))
RM_VOID(set_page_anon_exclusive, (struct page *p), SetPageAnonExclusive(p))
RM_RET(struct page *, page_add, (struct page *p, unsigned long n), p + n)
RM_VOID(get_page, (struct page *p), get_page(p))
RM_VOID(put_page, (struct page *p), put_page(p))
RM_RET(bool, trylock_page, (struct page *p), trylock_page(p))
RM_VOID(unlock_page, (struct page *p), unlock_page(p))
RM_RET(struct dev_pagemap *, page_pgmap, (struct page *p), page_pgmap(p))
RM_VOID(lru_add_drain, (void), lru_add_drain())
RM_RET(struct vm_area_struct *, mapping_rmap_tree_iter_first, (struct address_space *m, pgoff_t a, pgoff_t z), mapping_rmap_tree_iter_first(m, a, z))
RM_RET(struct vm_area_struct *, mapping_rmap_tree_iter_next, (struct vm_area_struct *v, pgoff_t a, pgoff_t z), mapping_rmap_tree_iter_next(v, a, z))
RM_RET(pgoff_t, vma_last_pgoff, (struct vm_area_struct *v), vma_last_pgoff(v))
RM_VOID(i_mmap_lock_read, (struct address_space *m), i_mmap_lock_read(m))
RM_VOID(i_mmap_unlock_read, (struct address_space *m), i_mmap_unlock_read(m))
RM_RET(bool, mapping_mapped, (struct address_space *m), mapping_mapped(m))
RM_RET(bool, mapping_evict_folio, (struct address_space *m, struct folio *f), mapping_evict_folio(m, f))
RM_RET(loff_t, i_size_read, (struct inode *i), i_size_read(i))
RM_RET(bool, shmem_mapping, (struct address_space *m), shmem_mapping(m))
RM_VOID(mmu_notifier_range_init_owner, (struct mmu_notifier_range *r, enum mmu_notifier_event e, unsigned int f, struct mm_struct *m, unsigned long a, unsigned long z, void *o), mmu_notifier_range_init_owner(r, e, f, m, a, z, o))
RM_VOID(migration_entry_wait, (struct mm_struct *m, pmd_t *p, unsigned long a), migration_entry_wait(m, p, a))
RM_VOID(softleaf_entry_wait_on_locked, (softleaf_t e, spinlock_t *p), softleaf_entry_wait_on_locked(e, p))
RM_RET(pte_marker, softleaf_to_marker, (softleaf_t e), softleaf_to_marker(e))
RM_RET(struct swap_info_struct *, get_swap_device, (swp_entry_t e), get_swap_device(e))
RM_VOID(put_swap_device, (struct swap_info_struct *s), put_swap_device(s))
RM_RET(struct folio *, swap_cache_get_folio, (swp_entry_t e), swap_cache_get_folio(e))
RM_VOID(swap_cache_del_folio, (struct folio *f), swap_cache_del_folio(f))
RM_VOID(swap_update_readahead, (struct folio *f, struct vm_area_struct *v, unsigned long a), swap_update_readahead(f, v, a))
RM_RET(struct folio *, swapin_sync, (swp_entry_t e, gfp_t g, unsigned long o, struct vm_fault *v, struct mempolicy *m, pgoff_t i), swapin_sync(e, g, o, v, m, i))
RM_RET(struct folio *, swapin_readahead, (swp_entry_t e, gfp_t g, struct vm_fault *v), swapin_readahead(e, g, v))
RM_RET(int, swap_count, (swp_entry_t e), __swap_count(e))
RM_RET(bool, mem_cgroup_swap_full, (struct folio *f), mem_cgroup_swap_full(f))
RM_RET(vm_fault_t, check_stable_address_space, (struct mm_struct *m), check_stable_address_space(m))
RM_RET(bool, is_err_value, (unsigned long v), IS_ERR_VALUE(v))
RM_RET(unsigned long, zero_pfn, (unsigned long a), zero_pfn(a))
RM_RET(bool, userfaultfd_wp_async, (struct vm_area_struct *v), userfaultfd_wp_async(v))
RM_RET(bool, userfaultfd_rwp_async, (struct vm_area_struct *v), userfaultfd_rwp_async(v))
RM_RET(bool, userfaultfd_armed, (struct vm_area_struct *v), userfaultfd_armed(v))
RM_RET(bool, userfaultfd_missing, (struct vm_area_struct *v), userfaultfd_missing(v))
RM_RET(bool, userfaultfd_pte_rwp, (struct vm_area_struct *v, pte_t p), userfaultfd_pte_rwp(v, p))
RM_RET(bool, userfaultfd_huge_pmd_wp, (struct vm_area_struct *v, pmd_t p), userfaultfd_huge_pmd_wp(v, p))
RM_RET(bool, userfaultfd_huge_pmd_rwp, (struct vm_area_struct *v, pmd_t p), userfaultfd_huge_pmd_rwp(v, p))
RM_RET(bool, uffd_disable_fault_around, (struct vm_area_struct *v), uffd_disable_fault_around(v))
RM_RET(vm_fault_t, handle_userfault, (struct vm_fault *v, unsigned long f), handle_userfault(v, f))
RM_VOID(vma_end_read, (struct vm_area_struct *v), vma_end_read(v))
RM_RET(bool, vma_is_accessible, (struct vm_area_struct *v), vma_is_accessible(v))
RM_RET(bool, vma_wants_manual_pte_write_upgrade, (struct vm_area_struct *v), vma_wants_manual_pte_write_upgrade(v))
RM_VOID(vma_set_access_pid_bit, (struct vm_area_struct *v), vma_set_access_pid_bit(v))
RM_RET(int, mpol_misplaced, (struct folio *f, struct vm_fault *v, unsigned long a), mpol_misplaced(f, v, a))
RM_RET(int, numa_node_id, (void), numa_node_id())
RM_RET(int, migrate_misplaced_folio_prepare, (struct folio *f, struct vm_area_struct *v, int n), migrate_misplaced_folio_prepare(f, v, n))
RM_RET(int, migrate_misplaced_folio, (struct folio *f, int n), migrate_misplaced_folio(f, n))
RM_VOID(task_numa_fault, (int c, int n, int p, int f), task_numa_fault(c, n, p, f))
RM_VOID(count_vm_event, (unsigned int e), count_vm_event(e))
RM_VOID(count_vm_numa_event, (unsigned int e), count_vm_numa_event(e))
RM_VOID(count_memcg_event_mm, (struct mm_struct *m, unsigned int e), count_memcg_event_mm(m, e))
RM_VOID(count_mthp_stat, (unsigned int o, unsigned int e), count_mthp_stat(o, e))
#ifdef CONFIG_NUMA_BALANCING
RM_VOID(count_memcg_folio_events, (struct folio *f, unsigned int e, unsigned long n), count_memcg_folio_events(f, e, n))
#endif
RM_VOID(perf_sw_event, (unsigned int e, u64 n, struct pt_regs *r, unsigned long a), perf_sw_event(e, n, r, a))
RM_RET(bool, arch_vma_access_permitted, (struct vm_area_struct *v, bool w, bool x, bool f), arch_vma_access_permitted(v, w, x, f))
RM_VOID(mem_cgroup_enter_user_fault, (void), mem_cgroup_enter_user_fault())
RM_VOID(mem_cgroup_exit_user_fault, (void), mem_cgroup_exit_user_fault())
RM_RET(bool, current_in_memcg_oom, (void), task_in_memcg_oom(current))
RM_RET(bool, mem_cgroup_oom_synchronize, (bool h), mem_cgroup_oom_synchronize(h))
RM_RET(vm_fault_t, hugetlb_fault, (struct mm_struct *m, struct vm_area_struct *v, unsigned long a, unsigned int f), hugetlb_fault(m, v, a, f))
RM_RET(bool, mm_tlb_flush_pending, (struct mm_struct *m), mm_tlb_flush_pending(m))
RM_RET(int, mmap_read_lock_killable, (struct mm_struct *m), mmap_read_lock_killable(m))
RM_VOID(mmap_read_unlock, (struct mm_struct *m), mmap_read_unlock(m))
RM_RET(unsigned long, untagged_addr_remote, (struct mm_struct *m, unsigned long a), untagged_addr_remote(m, a))
RM_RET(struct vm_area_struct *, vma_lookup, (struct mm_struct *m, unsigned long a), vma_lookup(m, a))
RM_RET(struct vm_area_struct *, expand_stack, (struct mm_struct *m, unsigned long a), expand_stack(m, a))
RM_RET(struct page *, get_user_page_vma_remote, (struct mm_struct *m, unsigned long a, unsigned int f, struct vm_area_struct **v), get_user_page_vma_remote(m, a, f, v))
RM_RET(struct mm_struct *, get_task_mm, (struct task_struct *t), get_task_mm(t))
RM_VOID(mmput, (struct mm_struct *m), mmput(m))
RM_RET(ssize_t, strscpy, (char *d, const char *s, size_t n), strscpy(d, s, n))
RM_VOID(print_vma_addr_line, (char *p, struct file *f, unsigned long i, unsigned long s, unsigned long n), printk("%s%pD[%lx,%lx+%lx]", p, f, i, s, n))
RM_VOID(might_sleep, (void), might_sleep())
#if defined(CONFIG_PROVE_LOCKING) || defined(CONFIG_DEBUG_ATOMIC_SLEEP)
RM_VOID(might_sleep_at, (const char *f, int l), __might_sleep(f, l))
RM_VOID(might_lock_read_mmap, (struct mm_struct *m), might_lock_read(&m->mmap_lock))
#endif
#ifdef CONFIG_LOCKDEP
RM_RET(bool, lockdep_i_mmap_held, (struct address_space *m), lockdep_is_held(&m->i_mmap_rwsem))
RM_RET(bool, lockdep_mmap_held, (struct mm_struct *m), lockdep_is_held(&m->mmap_lock))
RM_VOID(lockdep_assert, (bool b), lockdep_assert(b))
#endif
#ifndef __PAGETABLE_P4D_FOLDED
RM_RET(p4d_t *, p4d_alloc_one, (struct mm_struct *m, unsigned long a), p4d_alloc_one(m, a))
RM_VOID(p4d_free, (struct mm_struct *m, p4d_t *p), p4d_free(m, p))
RM_VOID(pgd_populate, (struct mm_struct *m, pgd_t *p, p4d_t *n), pgd_populate(m, p, n))
#endif
#ifndef __PAGETABLE_PUD_FOLDED
RM_RET(pud_t *, pud_alloc_one, (struct mm_struct *m, unsigned long a), pud_alloc_one(m, a))
RM_VOID(pud_free, (struct mm_struct *m, pud_t *p), pud_free(m, p))
RM_VOID(mm_inc_nr_puds, (struct mm_struct *m), mm_inc_nr_puds(m))
RM_VOID(p4d_populate, (struct mm_struct *m, p4d_t *p, pud_t *n), p4d_populate(m, p, n))
#endif
#ifndef __PAGETABLE_PMD_FOLDED
RM_RET(pmd_t *, pmd_alloc_one, (struct mm_struct *m, unsigned long a), pmd_alloc_one(m, a))
RM_VOID(pmd_free, (struct mm_struct *m, pmd_t *p), pmd_free(m, p))
RM_VOID(mm_inc_nr_pmds, (struct mm_struct *m), mm_inc_nr_pmds(m))
RM_VOID(pud_populate, (struct mm_struct *m, pud_t *p, pmd_t *n), pud_populate(m, p, n))
#endif
#ifdef CONFIG_HAVE_IOREMAP_PROT
RM_RET(void *, ioremap_prot, (resource_size_t a, unsigned long n, pgprot_t p), ioremap_prot(a, n, p))
RM_VOID(iounmap, (void *p), iounmap(p))
RM_VOID(memcpy_toio, (void *d, const void *s, size_t n), memcpy_toio(d, s, n))
RM_VOID(memcpy_fromio, (void *d, const void *s, size_t n), memcpy_fromio(d, s, n))
#endif
RM_VOID(hugetlb_vma_lock_read, (struct vm_area_struct *v), hugetlb_vma_lock_read(v))
RM_VOID(hugetlb_vma_unlock_read, (struct vm_area_struct *v), hugetlb_vma_unlock_read(v))
RM_RET(bool, thp_vma_allowable_order, (struct vm_area_struct *v, vm_flags_t f, unsigned long t, unsigned int o), thp_vma_allowable_order(v, f, t, o))
RM_RET(bool, pmd_is_device_private_entry, (pmd_t p), pmd_is_device_private_entry(p))
RM_RET(bool, pmd_is_migration_entry, (pmd_t p), pmd_is_migration_entry(p))
RM_VOID(pmd_migration_entry_wait, (struct mm_struct *m, pmd_t *p), pmd_migration_entry_wait(m, p))
RM_RET(vm_fault_t, do_huge_pmd_device_private, (struct vm_fault *v), do_huge_pmd_device_private(v))
#ifdef CONFIG_TRANSPARENT_HUGEPAGE
RM_RET(bool, folio_mm_ids_shared, (struct folio *f), test_bit(FOLIO_MM_IDS_SHARED_BITNUM, &f->_mm_ids))
RM_RET(unsigned int, folio_mm_id, (struct folio *f, int i), folio_mm_id(f, i))
RM_RET(unsigned int, mm_id, (struct mm_struct *m), m->mm_id)
RM_RET(int, folio_large_mapcount, (struct folio *f), folio_large_mapcount(f))
RM_RET(int, folio_entire_mapcount, (struct folio *f), folio_entire_mapcount(f))
RM_VOID(folio_lock_large_mapcount, (struct folio *f), folio_lock_large_mapcount(f))
RM_VOID(folio_unlock_large_mapcount, (struct folio *f), folio_unlock_large_mapcount(f))
RM_RET(int, highest_order, (unsigned long o), highest_order(o))
RM_RET(int, next_order, (unsigned long *o, int p), next_order(o, p))
RM_RET(unsigned long, thp_vma_allowable_orders, (struct vm_area_struct *v, vm_flags_t f, unsigned long t, unsigned long o), thp_vma_allowable_orders(v, f, t, o))
RM_RET(unsigned long, thp_vma_suitable_orders, (struct vm_area_struct *v, unsigned long a, unsigned long o), thp_vma_suitable_orders(v, a, o))
RM_RET(bool, zswap_never_enabled, (void), zswap_never_enabled())
RM_RET(gfp_t, vma_thp_gfp_mask, (struct vm_area_struct *v), vma_thp_gfp_mask(v))
RM_RET(bool, folio_memcg_alloc_deferred, (struct folio *f), folio_memcg_alloc_deferred(f))
RM_RET(bool, user_alloc_needs_zeroing, (void), user_alloc_needs_zeroing())
RM_RET(bool, thp_disabled_by_hw, (void), thp_disabled_by_hw())
RM_RET(bool, vma_thp_disabled, (struct vm_area_struct *v, vm_flags_t f, bool c), vma_thp_disabled(v, f, c))
RM_RET(bool, thp_vma_suitable_order, (struct vm_area_struct *v, unsigned long a, unsigned int o), thp_vma_suitable_order(v, a, o))
RM_RET(bool, is_pmd_order, (unsigned int o), is_pmd_order(o))
RM_RET(bool, folio_test_has_hwpoisoned, (struct folio *f), folio_test_has_hwpoisoned(f))
RM_RET(bool, arch_needs_pgtable_deposit, (void), arch_needs_pgtable_deposit())
RM_VOID(pgtable_trans_huge_deposit, (struct mm_struct *m, pmd_t *p, pgtable_t t), pgtable_trans_huge_deposit(m, p, t))
RM_RET(pmd_t, folio_mk_pmd, (struct folio *f, pgprot_t p), folio_mk_pmd(f, p))
RM_RET(pmd_t, pmd_mkdirty, (pmd_t p), pmd_mkdirty(p))
RM_RET(pmd_t, maybe_pmd_mkwrite, (pmd_t p, struct vm_area_struct *v), maybe_pmd_mkwrite(p, v))
RM_VOID(set_pmd_at, (struct mm_struct *m, unsigned long a, pmd_t *p, pmd_t e), set_pmd_at(m, a, p, e))
RM_RET(vm_fault_t, do_huge_pmd_anonymous_page, (struct vm_fault *v), do_huge_pmd_anonymous_page(v))
RM_RET(vm_fault_t, do_huge_pmd_wp_page, (struct vm_fault *v), do_huge_pmd_wp_page(v))
RM_RET(vm_fault_t, do_huge_pmd_numa_page, (struct vm_fault *v), do_huge_pmd_numa_page(v))
RM_RET(vm_fault_t, do_huge_pmd_uffd_rwp, (struct vm_fault *v), do_huge_pmd_uffd_rwp(v))
RM_RET(bool, huge_pmd_set_accessed, (struct vm_fault *v), huge_pmd_set_accessed(v))
#ifdef CONFIG_HAVE_ARCH_TRANSPARENT_HUGEPAGE_PUD
RM_VOID(split_huge_pud_unconditional, (struct vm_area_struct *v, pud_t *p, unsigned long a), __split_huge_pud(v, p, a))
RM_VOID(huge_pud_set_accessed, (struct vm_fault *v, pud_t p), huge_pud_set_accessed(v, p))
#endif
#endif
#if defined(CONFIG_TRANSPARENT_HUGEPAGE) || defined(CONFIG_HUGETLBFS)
RM_RET(bool, preempt_model_preemptible, (void), preempt_model_preemptible())
RM_VOID(clear_user_highpages, (struct page *p, unsigned long a, unsigned int n), clear_user_highpages(p, a, n))
#endif
#if defined(CONFIG_SPLIT_PTE_PTLOCKS) && ALLOC_SPLIT_PTLOCKS
RM_RET(struct kmem_cache *, kmem_cache_create, (const char *n, unsigned int s, unsigned int a, slab_flags_t f, void (*c)(void *)), kmem_cache_create(n, s, a, f, c))
RM_RET(void *, kmem_cache_alloc, (struct kmem_cache *c, gfp_t g), kmem_cache_alloc(c, g))
RM_VOID(kmem_cache_free, (struct kmem_cache *c, void *p), kmem_cache_free(c, p))
RM_RET(spinlock_t *, ptdesc_ptl, (struct ptdesc *p), p->ptl)
RM_VOID(ptdesc_set_ptl, (struct ptdesc *p, spinlock_t *l), p->ptl = l)
#endif
#ifdef CONFIG_DEBUG_FS
void rust_memory_fault_around_debugfs_create(void);
#endif
#endif
