// SPDX-License-Identifier: GPL-2.0
// Generated by review/generate-native.js from inventoried native leaves.
use b::rust_migrate___folio_alloc as __folio_alloc;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate___folio_alloc_node as __folio_alloc_node;
use b::rust_migrate___folio_set_swapbacked as __folio_set_swapbacked;
use b::rust_migrate___mod_zone_page_state as __mod_zone_page_state;
use b::rust_migrate___swap_cache_replace_folio as __swap_cache_replace_folio;
use b::rust_migrate_alloc_hugetlb_folio_nodemask as alloc_hugetlb_folio_nodemask;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_arch_make_huge_pte as arch_make_huge_pte;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_atomic_read as atomic_read;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_bh_count as bh_count;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_bh_next as bh_next;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_bh_offset as bh_offset;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_bh_state as bh_state;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_buffer_uptodate as buffer_uptodate;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_bug_active_unevictable as bug_active_unevictable;
use b::rust_migrate_bug_migrate_writeback as bug_migrate_writeback;
#[cfg(all(CONFIG_DEBUG_VM, CONFIG_ARCH_HAS_PMD_SOFTLEAVES))]
use b::rust_migrate_bug_migration_pmd as bug_migration_pmd;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_bug_misplaced_list as bug_misplaced_list;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_bug_move_destination_lock as bug_move_destination_lock;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_bug_move_source_lock as bug_move_source_lock;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_bug_shared_zero_destination as bug_shared_zero_destination;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_bug_unmap_anon_vma as bug_unmap_anon_vma;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_bug_zero_anon as bug_zero_anon;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_bug_zero_locked as bug_zero_locked;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_bug_zero_present as bug_zero_present;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_capable as capable;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_clear_bit_unlock as clear_bit_unlock;
use b::rust_migrate_clear_page_movable_ops_isolated as clear_page_movable_ops_isolated;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_compat_ptr as compat_ptr;
use b::rust_migrate_compound_order as compound_order;
use b::rust_migrate_cond_resched as cond_resched;
use b::rust_migrate_cond_resched_tasks_rcu_qs as cond_resched_tasks_rcu_qs;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_copy_from_user as copy_from_user;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_copy_to_user as copy_to_user;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_count_memcg_events as count_memcg_events;
use b::rust_migrate_count_vm_events as count_vm_events;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_count_vm_numa_events as count_vm_numa_events;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_cpuset_mems_allowed as cpuset_mems_allowed;
use b::rust_migrate_current_flags as current_flags;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_current_task as current_task;
use b::rust_migrate_dec_mm_counter as dec_mm_counter;
use b::rust_migrate_deferred_list_empty_data_race as deferred_list_empty_data_race;
use b::rust_migrate_deferred_split_folio as deferred_split_folio;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_down_read_killable as down_read_killable;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_err_ptr as err_ptr;
use b::rust_migrate_filemap_release_folio as filemap_release_folio;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_find_get_task_by_vpid as find_get_task_by_vpid;
use b::rust_migrate_flush_dcache_folio as flush_dcache_folio;
use b::rust_migrate_folio_add_anon_rmap_pte as folio_add_anon_rmap_pte;
use b::rust_migrate_folio_add_file_rmap_pte as folio_add_file_rmap_pte;
use b::rust_migrate_folio_add_lru as folio_add_lru;
use b::rust_migrate_folio_attach_private as folio_attach_private;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_folio_buffers as folio_buffers;
use b::rust_migrate_folio_clear_active as folio_clear_active;
use b::rust_migrate_folio_clear_dirty as folio_clear_dirty;
use b::rust_migrate_folio_clear_private as folio_clear_private;
use b::rust_migrate_folio_clear_swapcache as folio_clear_swapcache;
use b::rust_migrate_folio_clear_unevictable as folio_clear_unevictable;
use b::rust_migrate_folio_copy_owner as folio_copy_owner;
use b::rust_migrate_folio_deferred_list as folio_deferred_list;
use b::rust_migrate_folio_detach_private as folio_detach_private;
use b::rust_migrate_folio_end_writeback as folio_end_writeback;
use b::rust_migrate_folio_expected_ref_count as folio_expected_ref_count;
use b::rust_migrate_folio_from_lru as folio_from_lru;
use b::rust_migrate_folio_get as folio_get;
use b::rust_migrate_folio_get_anon_vma as folio_get_anon_vma;
use b::rust_migrate_folio_get_nontail_page as folio_get_nontail_page;
use b::rust_migrate_folio_get_private as folio_get_private;
use b::rust_migrate_folio_hstate as folio_hstate;
use b::rust_migrate_folio_index as folio_index;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_folio_is_device_private as folio_is_device_private;
use b::rust_migrate_folio_is_file_lru as folio_is_file_lru;
use b::rust_migrate_folio_is_zone_device as folio_is_zone_device;
use b::rust_migrate_folio_isolate_hugetlb as folio_isolate_hugetlb;
use b::rust_migrate_folio_isolate_lru as folio_isolate_lru;
use b::rust_migrate_folio_lock as folio_lock;
use b::rust_migrate_folio_lru as folio_lru;
use b::rust_migrate_folio_mapped as folio_mapped;
use b::rust_migrate_folio_mapping as folio_mapping;
use b::rust_migrate_folio_mapping_field as folio_mapping_field;
use b::rust_migrate_folio_mark_uptodate as folio_mark_uptodate;
#[cfg(all(any(CONFIG_NUMA_MIGRATION, CONFIG_NUMA_BALANCING)))]
use b::rust_migrate_folio_maybe_mapped_shared as folio_maybe_mapped_shared;
use b::rust_migrate_folio_mc_copy as folio_mc_copy;
use b::rust_migrate_folio_memcg as folio_memcg;
use b::rust_migrate_folio_migrate_info as folio_migrate_info;
use b::rust_migrate_folio_migrate_ksm as folio_migrate_ksm;
use b::rust_migrate_folio_migrate_refs as folio_migrate_refs;
use b::rust_migrate_folio_nid as folio_nid;
use b::rust_migrate_folio_nr_pages as folio_nr_pages;
use b::rust_migrate_folio_order as folio_order;
use b::rust_migrate_folio_page as folio_page;
use b::rust_migrate_folio_pgdat as folio_pgdat;
use b::rust_migrate_folio_put as folio_put;
use b::rust_migrate_folio_putback_hugetlb as folio_putback_hugetlb;
use b::rust_migrate_folio_putback_lru as folio_putback_lru;
use b::rust_migrate_folio_ref_add as folio_ref_add;
use b::rust_migrate_folio_ref_count as folio_ref_count;
use b::rust_migrate_folio_ref_freeze as folio_ref_freeze;
use b::rust_migrate_folio_ref_unfreeze as folio_ref_unfreeze;
use b::rust_migrate_folio_set_active as folio_set_active;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_folio_set_bh as folio_set_bh;
use b::rust_migrate_folio_set_checked as folio_set_checked;
use b::rust_migrate_folio_set_dirty as folio_set_dirty;
use b::rust_migrate_folio_set_idle as folio_set_idle;
use b::rust_migrate_folio_set_index as folio_set_index;
use b::rust_migrate_folio_set_mappedtodisk as folio_set_mappedtodisk;
use b::rust_migrate_folio_set_mapping_field as folio_set_mapping_field;
use b::rust_migrate_folio_set_migrate_info as folio_set_migrate_info;
use b::rust_migrate_folio_set_owner_migrate_reason as folio_set_owner_migrate_reason;
use b::rust_migrate_folio_set_private_field as folio_set_private_field;
use b::rust_migrate_folio_set_readahead as folio_set_readahead;
use b::rust_migrate_folio_set_referenced as folio_set_referenced;
use b::rust_migrate_folio_set_swapcache as folio_set_swapcache;
use b::rust_migrate_folio_set_unevictable as folio_set_unevictable;
use b::rust_migrate_folio_set_workingset as folio_set_workingset;
use b::rust_migrate_folio_set_young as folio_set_young;
use b::rust_migrate_folio_test_anon as folio_test_anon;
use b::rust_migrate_folio_test_checked as folio_test_checked;
use b::rust_migrate_folio_test_clear_active as folio_test_clear_active;
use b::rust_migrate_folio_test_clear_unevictable as folio_test_clear_unevictable;
use b::rust_migrate_folio_test_dirty as folio_test_dirty;
use b::rust_migrate_folio_test_hugetlb as folio_test_hugetlb;
use b::rust_migrate_folio_test_idle as folio_test_idle;
use b::rust_migrate_folio_test_ksm as folio_test_ksm;
use b::rust_migrate_folio_test_large as folio_test_large;
use b::rust_migrate_folio_test_large_rmappable as folio_test_large_rmappable;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_folio_test_locked as folio_test_locked;
use b::rust_migrate_folio_test_mappedtodisk as folio_test_mappedtodisk;
use b::rust_migrate_folio_test_mlocked as folio_test_mlocked;
use b::rust_migrate_folio_test_partially_mapped as folio_test_partially_mapped;
use b::rust_migrate_folio_test_pmd_mappable as folio_test_pmd_mappable;
use b::rust_migrate_folio_test_private as folio_test_private;
use b::rust_migrate_folio_test_readahead as folio_test_readahead;
use b::rust_migrate_folio_test_referenced as folio_test_referenced;
use b::rust_migrate_folio_test_swapbacked as folio_test_swapbacked;
use b::rust_migrate_folio_test_swapcache as folio_test_swapcache;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_folio_test_unevictable as folio_test_unevictable;
use b::rust_migrate_folio_test_uptodate as folio_test_uptodate;
use b::rust_migrate_folio_test_workingset as folio_test_workingset;
use b::rust_migrate_folio_test_writeback as folio_test_writeback;
use b::rust_migrate_folio_test_young as folio_test_young;
use b::rust_migrate_folio_trylock as folio_trylock;
use b::rust_migrate_folio_unlock as folio_unlock;
use b::rust_migrate_folio_unqueue_deferred_split as folio_unqueue_deferred_split;
use b::rust_migrate_folio_vma_walk as folio_vma_walk;
use b::rust_migrate_folio_wait_writeback as folio_wait_writeback;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_folio_walk_end as folio_walk_end;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_folio_walk_start as folio_walk_start;
use b::rust_migrate_folio_xchg_last_cpupid as folio_xchg_last_cpupid;
use b::rust_migrate_folio_zone as folio_zone;
use b::rust_migrate_folio_zonenum as folio_zonenum;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_get_mem_cgroup_from_folio as get_mem_cgroup_from_folio;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_get_task_mm as get_task_mm;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_get_user_compat as get_user_compat;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_get_user_int as get_user_int;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_get_user_pointer as get_user_pointer;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_high_wmark_pages as high_wmark_pages;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_hstate_vma as hstate_vma;
use b::rust_migrate_htlb_allow_alloc_fallback as htlb_allow_alloc_fallback;
use b::rust_migrate_htlb_modify_alloc_mask as htlb_modify_alloc_mask;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_huge_page_shift as huge_page_shift;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_huge_page_size as huge_page_size;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_huge_pte_lockptr as huge_pte_lockptr;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_huge_pte_none as huge_pte_none;
use b::rust_migrate_huge_ptep_get as huge_ptep_get;
use b::rust_migrate_hugepage_migration_supported as hugepage_migration_supported;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_hugetlb_add_anon_rmap as hugetlb_add_anon_rmap;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_hugetlb_add_file_rmap as hugetlb_add_file_rmap;
use b::rust_migrate_hugetlb_folio_mapping_lock_write as hugetlb_folio_mapping_lock_write;
use b::rust_migrate_hugetlb_folio_subpool as hugetlb_folio_subpool;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_hugetlb_vma_assert_locked as hugetlb_vma_assert_locked;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_hugetlb_vma_unlock_read as hugetlb_vma_unlock_read;
use b::rust_migrate_i_mmap_unlock_write as i_mmap_unlock_write;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_in_compat_syscall as in_compat_syscall;
use b::rust_migrate_init_list_head as init_list_head;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_invalidate_bh_lrus as invalidate_bh_lrus;
use b::rust_migrate_is_device_private_page as is_device_private_page;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_is_err as is_err;
use b::rust_migrate_is_highmem_idx as is_highmem_idx;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_is_huge_zero_folio as is_huge_zero_folio;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_is_zero_folio as is_zero_folio;
use b::rust_migrate_list_add as list_add;
use b::rust_migrate_list_add_tail as list_add_tail;
use b::rust_migrate_list_cut_before as list_cut_before;
use b::rust_migrate_list_del as list_del;
use b::rust_migrate_list_empty as list_empty;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_list_is_singular as list_is_singular;
use b::rust_migrate_list_move as list_move;
use b::rust_migrate_list_move_tail as list_move_tail;
use b::rust_migrate_list_splice as list_splice;
use b::rust_migrate_list_splice_init as list_splice_init;
use b::rust_migrate_list_splice_tail as list_splice_tail;
use b::rust_migrate_list_splice_tail_init as list_splice_tail_init;
use b::rust_migrate_local_irq_enable as local_irq_enable;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_lock_buffer as lock_buffer;
use b::rust_migrate_lru_add_drain as lru_add_drain;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_lru_cache_disable as lru_cache_disable;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_lru_cache_enable as lru_cache_enable;
use b::rust_migrate_make_readable_device_private_entry as make_readable_device_private_entry;
use b::rust_migrate_make_writable_device_private_entry as make_writable_device_private_entry;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_managed_zone as managed_zone;
use b::rust_migrate_mapping_can_writeback as mapping_can_writeback;
use b::rust_migrate_mapping_inaccessible as mapping_inaccessible;
use b::rust_migrate_mapping_migrate_folio as mapping_migrate_folio;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_mapping_private_lock as mapping_private_lock;
use b::rust_migrate_mem_cgroup_lruvec as mem_cgroup_lruvec;
use b::rust_migrate_mem_cgroup_migrate as mem_cgroup_migrate;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_mem_cgroup_put as mem_cgroup_put;
use b::rust_migrate_mk_pte as mk_pte;
use b::rust_migrate_mlock_drain_local as mlock_drain_local;
use b::rust_migrate_mm_counter as mm_counter;
use b::rust_migrate_mm_forbids_zeropage as mm_forbids_zeropage;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_mmap_read_lock as mmap_read_lock;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_mmap_read_unlock as mmap_read_unlock;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_mmget as mmget;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_mmput as mmput;
use b::rust_migrate_mod_lruvec_state as mod_lruvec_state;
use b::rust_migrate_mod_mthp_stat as mod_mthp_stat;
use b::rust_migrate_mod_node_page_state as mod_node_page_state;
use b::rust_migrate_move_hugetlb_state as move_hugetlb_state;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_node_data as node_data;
use b::rust_migrate_node_is_toptier as node_is_toptier;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_node_isset as node_isset;
use b::rust_migrate_node_stat_add_folio as node_stat_add_folio;
use b::rust_migrate_node_stat_mod_folio as node_stat_mod_folio;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_node_state as node_state;
use b::rust_migrate_numa_balancing_mode as numa_balancing_mode;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_page_anon as page_anon;
use b::rust_migrate_page_compound as page_compound;
use b::rust_migrate_page_folio as page_folio;
use b::rust_migrate_page_has_movable_ops as page_has_movable_ops;
use b::rust_migrate_page_hwpoison as page_hwpoison;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_page_locked as page_locked;
use b::rust_migrate_page_movable_ops_isolated as page_movable_ops_isolated;
use b::rust_migrate_page_none as page_none;
use b::rust_migrate_page_offline as page_offline;
use b::rust_migrate_page_to_pfn as page_to_pfn;
use b::rust_migrate_page_vma_mapped_walk as page_vma_mapped_walk;
use b::rust_migrate_page_zsmalloc as page_zsmalloc;
use b::rust_migrate_pages_identical as pages_identical;
use b::rust_migrate_pfn_pte as pfn_pte;
use b::rust_migrate_pgalloc_tag_swap as pgalloc_tag_swap;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_pgdat_nr_zones as pgdat_nr_zones;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_pgdat_zone as pgdat_zone;
#[cfg(all(CONFIG_ARCH_HAS_PMD_SOFTLEAVES))]
use b::rust_migrate_pmd_is_migration_entry as pmd_is_migration_entry;
#[cfg(all(CONFIG_ARCH_HAS_PMD_SOFTLEAVES))]
use b::rust_migrate_pmd_lock as pmd_lock;
use b::rust_migrate_pte_clear_soft_dirty as pte_clear_soft_dirty;
use b::rust_migrate_pte_mkdirty as pte_mkdirty;
use b::rust_migrate_pte_mkold as pte_mkold;
use b::rust_migrate_pte_mksoft_dirty as pte_mksoft_dirty;
use b::rust_migrate_pte_mkspecial as pte_mkspecial;
use b::rust_migrate_pte_mkuffd as pte_mkuffd;
use b::rust_migrate_pte_mkwrite as pte_mkwrite;
use b::rust_migrate_pte_modify as pte_modify;
use b::rust_migrate_pte_none as pte_none;
use b::rust_migrate_pte_offset_map_lock as pte_offset_map_lock;
use b::rust_migrate_pte_present as pte_present;
use b::rust_migrate_pte_swp_mksoft_dirty as pte_swp_mksoft_dirty;
use b::rust_migrate_pte_swp_mkuffd as pte_swp_mkuffd;
use b::rust_migrate_pte_swp_soft_dirty as pte_swp_soft_dirty;
use b::rust_migrate_pte_swp_uffd as pte_swp_uffd;
use b::rust_migrate_pte_unmap as pte_unmap;
use b::rust_migrate_pte_val as pte_val;
use b::rust_migrate_pte_write as pte_write;
use b::rust_migrate_ptep_get as ptep_get;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_ptr_err as ptr_err;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_ptrace_may_access as ptrace_may_access;
use b::rust_migrate_put_anon_vma as put_anon_vma;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_put_task_struct as put_task_struct;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_put_user_int as put_user_int;
use b::rust_migrate_rcu_read_lock as rcu_read_lock;
use b::rust_migrate_rcu_read_unlock as rcu_read_unlock;
#[cfg(all(CONFIG_ARCH_HAS_PMD_SOFTLEAVES))]
use b::rust_migrate_remove_migration_pmd as remove_migration_pmd;
use b::rust_migrate_rmap_walk as rmap_walk;
use b::rust_migrate_rmap_walk_locked as rmap_walk_locked;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_security_task_movememory as security_task_movememory;
#[cfg(all(CONFIG_HUGETLB_PAGE))]
use b::rust_migrate_set_huge_pte_at as set_huge_pte_at;
use b::rust_migrate_set_page_movable_ops_isolated as set_page_movable_ops_isolated;
use b::rust_migrate_set_pte_at as set_pte_at;
use b::rust_migrate_softleaf_entry_wait_on_locked as softleaf_entry_wait_on_locked;
#[cfg(all(CONFIG_ARCH_HAS_PMD_SOFTLEAVES))]
use b::rust_migrate_softleaf_from_pmd as softleaf_from_pmd;
use b::rust_migrate_softleaf_from_pte as softleaf_from_pte;
use b::rust_migrate_softleaf_is_migration as softleaf_is_migration;
use b::rust_migrate_softleaf_is_migration_dirty as softleaf_is_migration_dirty;
use b::rust_migrate_softleaf_is_migration_read as softleaf_is_migration_read;
use b::rust_migrate_softleaf_is_migration_write as softleaf_is_migration_write;
use b::rust_migrate_softleaf_is_migration_young as softleaf_is_migration_young;
use b::rust_migrate_softleaf_to_pfn as softleaf_to_pfn;
use b::rust_migrate_softleaf_to_pte as softleaf_to_pte;
use b::rust_migrate_spin_lock as spin_lock;
use b::rust_migrate_spin_unlock as spin_unlock;
use b::rust_migrate_split_folio_to_list as split_folio_to_list;
use b::rust_migrate_swap_cluster_get_and_lock_irq as swap_cluster_get_and_lock_irq;
use b::rust_migrate_swap_cluster_unlock as swap_cluster_unlock;
use b::rust_migrate_swap_cluster_unlock_irq as swap_cluster_unlock_irq;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_task_exec_update_lock as task_exec_update_lock;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_task_mm as task_mm;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_test_and_set_bit_lock as test_and_set_bit_lock;
use b::rust_migrate_thp_migration_supported as thp_migration_supported;
use b::rust_migrate_trace_mm_migrate_pages as trace_mm_migrate_pages;
use b::rust_migrate_trace_mm_migrate_pages_start as trace_mm_migrate_pages_start;
use b::rust_migrate_trace_remove_migration_pte as trace_remove_migration_pte;
use b::rust_migrate_try_to_free_buffers as try_to_free_buffers;
use b::rust_migrate_try_to_migrate as try_to_migrate;
use b::rust_migrate_try_to_unmap_flush as try_to_unmap_flush;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_trylock_buffer as trylock_buffer;
#[cfg(all(CONFIG_BUFFER_HEAD))]
use b::rust_migrate_unlock_buffer as unlock_buffer;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_untagged_addr_remote as untagged_addr_remote;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_up_read as up_read;
use b::rust_migrate_update_mmu_cache as update_mmu_cache;
use b::rust_migrate_userfaultfd_rwp as userfaultfd_rwp;
use b::rust_migrate_vma_flags as vma_flags;
use b::rust_migrate_vma_flags_read_once as vma_flags_read_once;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_vma_lookup as vma_lookup;
#[cfg(all(CONFIG_NUMA_MIGRATION))]
use b::rust_migrate_vma_migratable as vma_migratable;
use b::rust_migrate_vma_mm as vma_mm;
use b::rust_migrate_vma_page_prot as vma_page_prot;
use b::rust_migrate_vma_page_prot_read_once as vma_page_prot_read_once;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_wakeup_kswapd as wakeup_kswapd;
#[cfg(all(CONFIG_DEBUG_VM, CONFIG_BUFFER_HEAD))]
use b::rust_migrate_warn_buffer_migrating as warn_buffer_migrating;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_isolate_driver as warn_isolate_driver;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_isolate_type as warn_isolate_type;
use b::rust_migrate_warn_missing_migrate_folio as warn_missing_migrate_folio;
use b::rust_migrate_warn_missing_movable_ops as warn_missing_movable_ops;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_movable_type as warn_movable_type;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_move_isolated as warn_move_isolated;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_move_type as warn_move_type;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_putback_isolated as warn_putback_isolated;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_putback_type as warn_putback_type;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_sync_batch as warn_sync_batch;
#[cfg(all(CONFIG_DEBUG_VM))]
use b::rust_migrate_warn_zero_device as warn_zero_device;
use b::rust_migrate_xa_state as xa_state;
use b::rust_migrate_xas_lock_irq as xas_lock_irq;
use b::rust_migrate_xas_store as xas_store;
use b::rust_migrate_xas_unlock as xas_unlock;
use b::rust_migrate_xas_unlock_irq as xas_unlock_irq;
use b::rust_migrate_zero_page as zero_page;
use b::rust_migrate_zero_pfn as zero_pfn;
use b::rust_migrate_zone_pgdat as zone_pgdat;
#[cfg(all(CONFIG_NUMA_BALANCING))]
use b::rust_migrate_zone_watermark_ok as zone_watermark_ok;
