/* SPDX-License-Identifier: GPL-2.0 */
#ifndef RUST_RMAP_NATIVE_PRIMITIVES_H
#define RUST_RMAP_NATIVE_PRIMITIVES_H
/* Each leaf below is a single original-header operation or ABI accessor.
 * Header algorithms remain native and are not credited as translated bodies. */
#define RR_RET(type, name, args, expr) \
 type rust_rmap_##name args; type rust_rmap_##name args { return (expr); }
#define RR_VOID(name, args, expr) \
 void rust_rmap_##name args; void rust_rmap_##name args { expr; }
RR_RET(void *, kmem_cache_alloc, (struct kmem_cache *c, gfp_t g), kmem_cache_alloc(c,g))
RR_VOID(kmem_cache_free, (struct kmem_cache *c, void *p), kmem_cache_free(c,p))
RR_RET(struct kmem_cache *, kmem_cache_create, (const char *n, unsigned int s, unsigned int a, slab_flags_t f, void (*ctor)(void *)), kmem_cache_create(n,s,a,f,ctor))
RR_RET(struct kmem_cache *, anon_chain_cache_create, (void), KMEM_CACHE(anon_vma_chain, SLAB_PANIC | SLAB_ACCOUNT))
RR_VOID(atomic_set, (atomic_t *a, int v), atomic_set(a,v))
RR_RET(int, atomic_read, (const atomic_t *a), atomic_read(a))
RR_RET(bool, atomic_inc_not_zero, (atomic_t *a), atomic_inc_not_zero(a))
RR_RET(bool, atomic_dec_and_test, (atomic_t *a), atomic_dec_and_test(a))
RR_RET(bool, atomic_inc_and_test, (atomic_t *a), atomic_inc_and_test(a))
RR_RET(bool, atomic_add_negative, (int n, atomic_t *a), atomic_add_negative(n,a))
RR_RET(int, atomic_add_return_relaxed, (int n, atomic_t *a), atomic_add_return_relaxed(n,a))
RR_RET(int, atomic_sub_return_relaxed, (int n, atomic_t *a), atomic_sub_return_relaxed(n,a))
RR_VOID(atomic_inc, (atomic_t *a), atomic_inc(a))
RR_RET(bool, atomic_try_cmpxchg, (atomic_t *a, int *old, int n), atomic_try_cmpxchg(a,old,n))
RR_RET(int, atomic_cmpxchg, (atomic_t *a, int old, int n), atomic_cmpxchg(a,old,n))
RR_VOID(might_sleep, (void), might_sleep())
RR_RET(bool, rwsem_is_locked, (struct rw_semaphore *s), rwsem_is_locked(s))
RR_VOID(init_rwsem, (struct rw_semaphore *s), init_rwsem(s))
RR_RET(int, down_read_trylock, (struct rw_semaphore *s), down_read_trylock(s))
RR_VOID(up_read, (struct rw_semaphore *s), up_read(s))
RR_VOID(anon_vma_lock_write, (struct anon_vma *a), anon_vma_lock_write(a))
RR_VOID(anon_vma_unlock_write, (struct anon_vma *a), anon_vma_unlock_write(a))
RR_VOID(anon_vma_lock_read, (struct anon_vma *a), anon_vma_lock_read(a))
RR_VOID(anon_vma_unlock_read, (struct anon_vma *a), anon_vma_unlock_read(a))
RR_RET(bool, anon_vma_trylock_read, (struct anon_vma *a), anon_vma_trylock_read(a))
RR_VOID(get_anon_vma, (struct anon_vma *a), get_anon_vma(a))
RR_VOID(put_anon_vma, (struct anon_vma *a), put_anon_vma(a))
RR_VOID(mmap_assert_locked, (struct mm_struct *m), mmap_assert_locked(m))
RR_VOID(mmap_assert_write_locked, (struct mm_struct *m), mmap_assert_write_locked(m))
RR_RET(struct anon_vma *, find_mergeable_anon_vma, (struct vm_area_struct *v), find_mergeable_anon_vma(v))
RR_RET(spinlock_t *, mm_page_table_lock, (struct mm_struct *m), &m->page_table_lock)
RR_VOID(spin_lock, (spinlock_t *p), spin_lock(p))
RR_VOID(spin_unlock, (spinlock_t *p), spin_unlock(p))
RR_VOID(list_add, (struct list_head *n, struct list_head *h), list_add(n,h))
RR_VOID(list_del, (struct list_head *n), list_del(n))
RR_RET(struct anon_vma_chain *, avc_from_same_vma, (struct list_head *n), list_entry(n,struct anon_vma_chain,same_vma))
RR_RET(bool, rb_empty_root, (const struct rb_root *r), RB_EMPTY_ROOT(r))
RR_RET(struct rb_root_cached, rb_root_cached_empty, (void), (RB_ROOT_CACHED))
RR_VOID(anon_rmap_tree_insert, (struct anon_vma_chain *c, struct anon_vma *a), anon_rmap_tree_insert(c,a))
RR_VOID(anon_rmap_tree_remove, (struct anon_vma_chain *c, struct anon_vma *a), anon_rmap_tree_remove(c,a))
RR_RET(struct anon_vma_chain *, anon_rmap_tree_iter_first, (struct anon_vma *a, pgoff_t s, pgoff_t e), anon_rmap_tree_iter_first(a,s,e))
RR_RET(struct anon_vma_chain *, anon_rmap_tree_iter_next, (struct anon_vma_chain *c, pgoff_t s, pgoff_t e), anon_rmap_tree_iter_next(c,s,e))
RR_RET(struct vm_area_struct *, mapping_rmap_tree_iter_first, (struct address_space *m, pgoff_t s, pgoff_t e), mapping_rmap_tree_iter_first(m,s,e))
RR_RET(struct vm_area_struct *, mapping_rmap_tree_iter_next, (struct vm_area_struct *v, pgoff_t s, pgoff_t e), mapping_rmap_tree_iter_next(v,s,e))
RR_VOID(rcu_read_lock, (void), rcu_read_lock())
RR_VOID(rcu_read_unlock, (void), rcu_read_unlock())
RR_RET(struct anon_vma *, anon_root_read_once, (struct anon_vma *a), READ_ONCE(a->root))
RR_RET(struct address_space *, folio_mapping_read_once, (const struct folio *f), READ_ONCE(f->mapping))
RR_RET(struct address_space *, folio_mapping_field, (const struct folio *f), f->mapping)
RR_VOID(folio_mapping_write_once, (struct folio *f, struct address_space *m), WRITE_ONCE(f->mapping,m))
RR_RET(pgoff_t, folio_index, (const struct folio *f), f->index)
RR_VOID(folio_set_index, (struct folio *f, pgoff_t i), f->index = i)
RR_RET(atomic_t *, folio_mapcount_ptr, (struct folio *f), &f->_mapcount)
RR_RET(atomic_t *, folio_nr_pages_mapped_ptr, (struct folio *f), &f->_nr_pages_mapped)
RR_RET(atomic_t *, folio_entire_mapcount_ptr, (struct folio *f), &f->_entire_mapcount)
RR_RET(atomic_t *, folio_large_mapcount_ptr, (struct folio *f), &f->_large_mapcount)
RR_RET(atomic_t *, page_mapcount_ptr, (struct page *p), &p->_mapcount)
RR_RET(struct page *, page_nth, (struct page *p, long i), p + i)
RR_RET(struct page *, folio_page, (struct folio *f, unsigned long i), folio_page(f,i))
RR_RET(unsigned long, folio_pfn, (const struct folio *f), folio_pfn(f))
RR_RET(pgoff_t, folio_pgoff, (struct folio *f), folio_pgoff(f))
RR_RET(unsigned long, folio_nr_pages, (const struct folio *f), folio_nr_pages(f))
RR_RET(unsigned long, folio_large_nr_pages, (const struct folio *f), folio_large_nr_pages(f))
RR_RET(unsigned int, folio_order, (const struct folio *f), folio_order(f))
RR_RET(bool, folio_mapped, (const struct folio *f), folio_mapped(f))
RR_RET(int, folio_mapcount, (const struct folio *f), folio_mapcount(f))
RR_RET(int, folio_entire_mapcount, (const struct folio *f), folio_entire_mapcount(f))
RR_RET(int, folio_ref_count, (const struct folio *f), folio_ref_count(f))
RR_RET(bool, folio_maybe_mapped_shared, (struct folio *f), folio_maybe_mapped_shared(f))
RR_RET(struct anon_vma *, folio_anon_vma, (const struct folio *f), folio_anon_vma(f))
RR_RET(struct address_space *, folio_mapping, (struct folio *f), folio_mapping(f))
RR_RET(void *, folio_raw_mapping, (struct folio *f), folio_raw_mapping(f))
RR_RET(pgoff_t, page_pgoff, (const struct folio *f, const struct page *p), page_pgoff(f,p))
RR_RET(unsigned long, vma_anon_address, (const struct vm_area_struct *v, pgoff_t p, unsigned long n), vma_anon_address(v,p,n))
RR_RET(unsigned long, vma_filebacked_address, (const struct vm_area_struct *v, pgoff_t p, unsigned long n), vma_filebacked_address(v,p,n))
RR_RET(pgoff_t, linear_anon_page_index, (struct vm_area_struct *v, unsigned long a), linear_anon_page_index(v,a))
RR_RET(struct address_space *, file_mapping, (const struct file *f), f->f_mapping)
RR_RET(unsigned long, vma_start, (const struct vm_area_struct *v), v->vm_start)
RR_RET(unsigned long, vma_end, (const struct vm_area_struct *v), v->vm_end)
RR_RET(vm_flags_t, vma_vm_flags, (const struct vm_area_struct *v), v->vm_flags)
RR_RET(vma_flags_t, vma_flags_read, (const struct vm_area_struct *v), v->flags)
RR_RET(bool, vma_test_locked, (const struct vm_area_struct *v), vma_test(v,VMA_LOCKED_BIT))
RR_VOID(vma_flags_set_locked, (vma_flags_t *v), vma_flags_set(v,VMA_LOCKED_BIT))
RR_VOID(vma_flags_clear_locked, (vma_flags_t *v), vma_flags_clear(v,VMA_LOCKED_BIT))
RR_VOID(vma_flags_set_mask, (vma_flags_t *v, vma_flags_t m), vma_flags_set_mask(v,m))
RR_VOID(vma_flags_clear_all, (vma_flags_t *v), vma_flags_clear_all(v))
RR_RET(bool, vma_has_recency, (struct vm_area_struct *v), vma_has_recency(v))
RR_RET(bool, vma_is_temporary_stack, (struct vm_area_struct *v), vma_is_temporary_stack(v))
RR_RET(bool, mm_match_cgroup, (struct mm_struct *m, struct mem_cgroup *c), mm_match_cgroup(m,c))
RR_RET(int, mm_users, (struct mm_struct *m), atomic_read(&m->mm_users))
RR_RET(int, check_stable_address_space, (struct mm_struct *m), check_stable_address_space(m))
RR_RET(bool, folio_test_locked, (const struct folio *f), folio_test_locked(f))
RR_RET(bool, folio_test_anon, (const struct folio *f), folio_test_anon(f))
RR_RET(bool, folio_test_large, (const struct folio *f), folio_test_large(f))
RR_RET(bool, folio_test_ksm, (const struct folio *f), folio_test_ksm(f))
RR_RET(bool, folio_test_hugetlb, (const struct folio *f), folio_test_hugetlb(f))
RR_RET(bool, folio_test_hwpoison, (const struct folio *f), folio_test_hwpoison(f))
RR_RET(bool, folio_test_dirty, (const struct folio *f), folio_test_dirty(f))
RR_RET(bool, folio_test_swapbacked, (const struct folio *f), folio_test_swapbacked(f))
RR_RET(bool, folio_test_swapcache, (const struct folio *f), folio_test_swapcache(f))
RR_RET(bool, folio_test_pmd_mappable, (struct folio *f), folio_test_pmd_mappable(f))
RR_RET(bool, folio_test_partially_mapped, (struct folio *f), folio_test_partially_mapped(f))
RR_RET(bool, folio_test_lazyfree, (struct folio *f), folio_test_lazyfree(f))
RR_RET(bool, folio_is_zone_device, (const struct folio *f), folio_is_zone_device(f))
RR_RET(bool, folio_is_device_private, (const struct folio *f), folio_is_device_private(f))
RR_RET(bool, folio_is_device_coherent, (const struct folio *f), folio_is_device_coherent(f))
RR_VOID(folio_clear_idle, (struct folio *f), folio_clear_idle(f))
RR_RET(bool, folio_test_clear_young, (struct folio *f), folio_test_clear_young(f))
RR_RET(bool, folio_trylock, (struct folio *f), folio_trylock(f))
RR_VOID(folio_unlock, (struct folio *f), folio_unlock(f))
RR_VOID(folio_put, (struct folio *f), folio_put(f))
RR_VOID(folio_put_refs, (struct folio *f, int n), folio_put_refs(f,n))
RR_VOID(folio_mark_dirty, (struct folio *f), folio_mark_dirty(f))
RR_VOID(folio_set_swapbacked, (struct folio *f), folio_set_swapbacked(f))
RR_VOID(__folio_set_swapbacked, (struct folio *f), __folio_set_swapbacked(f))
RR_VOID(folio_clear_hugetlb_restore_reserve, (struct folio *f), folio_clear_hugetlb_restore_reserve(f))
RR_RET(bool, page_anon_exclusive, (struct page *p), PageAnonExclusive(p))
RR_RET(bool, page_hwpoison, (struct page *p), PageHWPoison(p))
RR_VOID(set_page_anon_exclusive, (struct page *p), SetPageAnonExclusive(p))
RR_VOID(mlock_vma_folio, (struct folio *f, struct vm_area_struct *v), mlock_vma_folio(f,v))
RR_VOID(munlock_vma_folio, (struct folio *f, struct vm_area_struct *v), munlock_vma_folio(f,v))
RR_VOID(mlock_drain_local, (void), mlock_drain_local())
RR_RET(bool, i_mmap_trylock_read, (struct address_space *m), i_mmap_trylock_read(m))
RR_VOID(i_mmap_lock_read, (struct address_space *m), i_mmap_lock_read(m))
RR_VOID(i_mmap_unlock_read, (struct address_space *m), i_mmap_unlock_read(m))
RR_VOID(cond_resched, (void), cond_resched())
RR_VOID(rmap_walk_ksm, (struct folio *f, struct rmap_walk_control *w), rmap_walk_ksm(f,w))
RR_RET(pgd_t *, pgd_offset, (struct mm_struct *m, unsigned long a), pgd_offset(m,a))
RR_RET(p4d_t *, p4d_offset, (pgd_t *p, unsigned long a), p4d_offset(p,a))
RR_RET(pud_t *, pud_offset, (p4d_t *p, unsigned long a), pud_offset(p,a))
RR_RET(pmd_t *, pmd_offset, (pud_t *p, unsigned long a), pmd_offset(p,a))
RR_RET(bool, pgd_present, (pgd_t p), pgd_present(p))
RR_RET(bool, p4d_present, (p4d_t p), p4d_present(p))
RR_RET(bool, pud_present, (pud_t p), pud_present(p))
RR_RET(bool, pmd_present, (pmd_t p), pmd_present(p))
RR_RET(bool, pte_present, (pte_t p), pte_present(p))
RR_RET(bool, pte_dirty, (pte_t p), pte_dirty(p))
RR_RET(bool, pte_write, (pte_t p), pte_write(p))
RR_RET(bool, pte_young, (pte_t p), pte_young(p))
RR_RET(bool, pte_unused, (pte_t p), pte_unused(p))
RR_RET(bool, pte_soft_dirty, (pte_t p), pte_soft_dirty(p))
RR_RET(bool, pte_uffd, (pte_t p), pte_uffd(p))
RR_RET(bool, pte_swp_soft_dirty, (pte_t p), pte_swp_soft_dirty(p))
RR_RET(bool, pte_swp_uffd, (pte_t p), pte_swp_uffd(p))
RR_RET(pte_t, pte_wrprotect, (pte_t p), pte_wrprotect(p))
RR_RET(pte_t, pte_mkclean, (pte_t p), pte_mkclean(p))
RR_RET(pte_t, pte_swp_mkexclusive, (pte_t p), pte_swp_mkexclusive(p))
RR_RET(pte_t, pte_swp_mksoft_dirty, (pte_t p), pte_swp_mksoft_dirty(p))
RR_RET(pte_t, pte_swp_mkuffd, (pte_t p), pte_swp_mkuffd(p))
RR_RET(unsigned long, pte_pfn, (pte_t p), pte_pfn(p))
RR_RET(pte_t, ptep_get, (pte_t *p), ptep_get(p))
RR_RET(pmd_t, pmdp_get, (pmd_t *p), pmdp_get(p))
RR_RET(pte_t, ptep_clear_flush, (struct vm_area_struct *v, unsigned long a, pte_t *p), ptep_clear_flush(v,a,p))
RR_RET(pte_t, ptep_get_and_clear, (struct mm_struct *m, unsigned long a, pte_t *p), ptep_get_and_clear(m,a,p))
RR_RET(pte_t, get_and_clear_ptes, (struct mm_struct *m, unsigned long a, pte_t *p, unsigned int n), get_and_clear_ptes(m,a,p,n))
RR_VOID(pte_clear, (struct mm_struct *m, unsigned long a, pte_t *p), pte_clear(m,a,p))
RR_VOID(set_pte_at, (struct mm_struct *m, unsigned long a, pte_t *p, pte_t e), set_pte_at(m,a,p,e))
RR_VOID(set_ptes, (struct mm_struct *m, unsigned long a, pte_t *p, pte_t e, unsigned int n), set_ptes(m,a,p,e,n))
RR_VOID(flush_cache_page, (struct vm_area_struct *v, unsigned long a, unsigned long p), flush_cache_page(v,a,p))
RR_VOID(flush_cache_range, (struct vm_area_struct *v, unsigned long s, unsigned long e), flush_cache_range(v,s,e))
RR_VOID(flush_tlb_range, (struct vm_area_struct *v, unsigned long s, unsigned long e), flush_tlb_range(v,s,e))
RR_RET(unsigned long, pmd_addr_end, (unsigned long a, unsigned long e), pmd_addr_end(a,e))
RR_RET(unsigned int, folio_pte_batch, (struct folio *f, pte_t *p, pte_t e, unsigned int n), folio_pte_batch(f,p,e,n))
RR_RET(unsigned int, folio_pte_batch_flags, (struct folio *f, struct vm_area_struct *v, pte_t *p, pte_t *e, unsigned int n, fpb_t flags), folio_pte_batch_flags(f,v,p,e,n,flags))
RR_VOID(pvmw_set_pgoff_is_anon, (struct page_vma_mapped_walk *w, bool a), w->pgoff_is_anon = a)
RR_RET(bool, page_vma_mapped_walk, (struct page_vma_mapped_walk *w), page_vma_mapped_walk(w))
RR_VOID(page_vma_mapped_walk_done, (struct page_vma_mapped_walk *w), page_vma_mapped_walk_done(w))
RR_VOID(page_vma_mapped_walk_restart, (struct page_vma_mapped_walk *w), page_vma_mapped_walk_restart(w))
RR_RET(unsigned long, vma_address_end, (struct page_vma_mapped_walk *w), vma_address_end(w))
RR_RET(bool, lru_gen_enabled, (void), lru_gen_enabled())
RR_RET(bool, lru_gen_switching, (void), lru_gen_switching())
RR_RET(bool, lru_gen_look_around, (struct page_vma_mapped_walk *w, unsigned int n), lru_gen_look_around(w,n))
RR_RET(int, clear_flush_young_ptes_notify, (struct vm_area_struct *v, unsigned long a, pte_t *p, unsigned int n), clear_flush_young_ptes_notify(v,a,p,n))
#ifdef CONFIG_TRANSPARENT_HUGEPAGE
RR_RET(int, pmdp_clear_flush_young_notify, (struct vm_area_struct *v, unsigned long a, pmd_t *p), pmdp_clear_flush_young_notify(v,a,p))
RR_RET(bool, pmd_dirty, (pmd_t p), pmd_dirty(p))
RR_RET(bool, pmd_write, (pmd_t p), pmd_write(p))
RR_RET(pmd_t, pmdp_invalidate, (struct vm_area_struct *v, unsigned long a, pmd_t *p), pmdp_invalidate(v,a,p))
RR_RET(pmd_t, pmd_wrprotect, (pmd_t p), pmd_wrprotect(p))
RR_RET(pmd_t, pmd_mkclean, (pmd_t p), pmd_mkclean(p))
RR_VOID(set_pmd_at, (struct mm_struct *m, unsigned long a, pmd_t *p, pmd_t e), set_pmd_at(m,a,p,e))
#endif
RR_VOID(mmu_notifier_range_init, (struct mmu_notifier_range *r, enum mmu_notifier_event e, unsigned int f, struct mm_struct *m, unsigned long s, unsigned long end), mmu_notifier_range_init(r,e,f,m,s,end))
RR_VOID(mmu_notifier_invalidate_range_start, (struct mmu_notifier_range *r), mmu_notifier_invalidate_range_start(r))
RR_VOID(mmu_notifier_invalidate_range_end, (struct mmu_notifier_range *r), mmu_notifier_invalidate_range_end(r))
RR_VOID(lruvec_stat_mod_folio, (struct folio *f, enum node_stat_item i, int n), lruvec_stat_mod_folio(f,i,n))
RR_RET(pg_data_t *, folio_pgdat, (const struct folio *f), folio_pgdat(f))
RR_VOID(__mod_node_page_state, (pg_data_t *p, enum node_stat_item i, long n), __mod_node_page_state(p,i,n))
RR_VOID(rmap_sanity_pte, (struct folio *f, struct page *p, int n), __folio_rmap_sanity_checks(f,p,n,PGTABLE_LEVEL_PTE))
#ifdef CONFIG_TRANSPARENT_HUGEPAGE
RR_VOID(rmap_sanity_pmd, (struct folio *f, struct page *p, int n), __folio_rmap_sanity_checks(f,p,n,PGTABLE_LEVEL_PMD))
#ifdef CONFIG_HAVE_ARCH_TRANSPARENT_HUGEPAGE_PUD
RR_VOID(rmap_sanity_pud, (struct folio *f, struct page *p, int n), __folio_rmap_sanity_checks(f,p,n,PGTABLE_LEVEL_PUD))
#endif
#endif
#ifdef CONFIG_NO_PAGE_MAPCOUNT
RR_RET(int, folio_add_return_large_mapcount, (struct folio *f, int n, struct vm_area_struct *v), folio_add_return_large_mapcount(f,n,v))
#endif
#ifdef CONFIG_NO_PAGE_MAPCOUNT
RR_RET(int, folio_inc_return_large_mapcount, (struct folio *f, struct vm_area_struct *v), folio_inc_return_large_mapcount(f,v))
#endif
RR_VOID(folio_add_large_mapcount, (struct folio *f, int n, struct vm_area_struct *v), folio_add_large_mapcount(f,n,v))
RR_VOID(folio_inc_large_mapcount, (struct folio *f, struct vm_area_struct *v), folio_inc_large_mapcount(f,v))
#ifdef CONFIG_NO_PAGE_MAPCOUNT
RR_RET(int, folio_sub_return_large_mapcount, (struct folio *f, int n, struct vm_area_struct *v), folio_sub_return_large_mapcount(f,n,v))
#endif
#ifdef CONFIG_NO_PAGE_MAPCOUNT
RR_RET(int, folio_dec_return_large_mapcount, (struct folio *f, struct vm_area_struct *v), folio_dec_return_large_mapcount(f,v))
#endif
RR_VOID(folio_sub_large_mapcount, (struct folio *f, int n, struct vm_area_struct *v), folio_sub_large_mapcount(f,n,v))
RR_VOID(folio_dec_large_mapcount, (struct folio *f, struct vm_area_struct *v), folio_dec_large_mapcount(f,v))
RR_VOID(folio_set_large_mapcount, (struct folio *f, int n, struct vm_area_struct *v), folio_set_large_mapcount(f,n,v))
RR_VOID(deferred_split_folio, (struct folio *f, bool p), deferred_split_folio(f,p))
RR_VOID(mod_mthp_stat, (int o, enum mthp_stat_item i, int n), mod_mthp_stat(o,i,n))
#ifdef CONFIG_ARCH_WANT_BATCHED_UNMAP_TLB_FLUSH
RR_RET(struct tlbflush_unmap_batch *, current_tlb_ubc, (void), &current->tlb_ubc)
RR_RET(atomic_t *, mm_tlb_flush_batched, (struct mm_struct *m), &m->tlb_flush_batched)
RR_RET(bool, pte_accessible, (struct mm_struct *m, pte_t p), pte_accessible(m,p))
RR_VOID(arch_tlbbatch_flush, (struct arch_tlbflush_unmap_batch *b), arch_tlbbatch_flush(b))
RR_VOID(arch_tlbbatch_add_pending, (struct arch_tlbflush_unmap_batch *b, struct mm_struct *m, unsigned long s, unsigned long e), arch_tlbbatch_add_pending(b,m,s,e))
RR_RET(bool, arch_tlbbatch_should_defer, (struct mm_struct *m), arch_tlbbatch_should_defer(m))
RR_VOID(flush_tlb_mm, (struct mm_struct *m), flush_tlb_mm(m))
RR_VOID(barrier, (void), barrier())
#endif
RR_VOID(smp_mb, (void), smp_mb())
RR_VOID(smp_rmb, (void), smp_rmb())
RR_RET(struct hstate *, hstate_vma, (struct vm_area_struct *v), hstate_vma(v))
RR_RET(unsigned long, huge_page_size, (struct hstate *h), huge_page_size(h))
RR_VOID(adjust_range_if_pmd_sharing_possible, (struct vm_area_struct *v, unsigned long *s, unsigned long *e), adjust_range_if_pmd_sharing_possible(v,s,e))
#ifdef CONFIG_HUGETLB_PAGE
RR_RET(pte_t, huge_ptep_get, (struct mm_struct *m, unsigned long a, pte_t *p), huge_ptep_get(m,a,p))
#endif
RR_RET(pte_t, huge_ptep_clear_flush, (struct vm_area_struct *v, unsigned long a, pte_t *p), huge_ptep_clear_flush(v,a,p))
#ifdef CONFIG_HUGETLB_PAGE
RR_RET(bool, huge_pte_dirty, (pte_t p), huge_pte_dirty(p))
#endif
RR_RET(bool, hugetlb_vma_trylock_write, (struct vm_area_struct *v), hugetlb_vma_trylock_write(v))
RR_VOID(hugetlb_vma_unlock_write, (struct vm_area_struct *v), hugetlb_vma_unlock_write(v))
RR_VOID(tlb_gather_mmu_vma, (struct mmu_gather *t, struct vm_area_struct *v), tlb_gather_mmu_vma(t,v))
RR_VOID(tlb_finish_mmu, (struct mmu_gather *t), tlb_finish_mmu(t))
RR_RET(int, huge_pmd_unshare, (struct mmu_gather *t, struct vm_area_struct *v, unsigned long a, pte_t *p), huge_pmd_unshare(t,v,a,p))
RR_VOID(huge_pmd_unshare_flush, (struct mmu_gather *t, struct vm_area_struct *v), huge_pmd_unshare_flush(t,v))
RR_VOID(hugetlb_count_sub, (long n, struct mm_struct *m), hugetlb_count_sub(n,m))
RR_VOID(set_huge_pte_at, (struct mm_struct *m, unsigned long a, pte_t *p, pte_t e, unsigned long s), set_huge_pte_at(m,a,p,e,s))
RR_VOID(hugetlb_remove_rmap, (struct folio *f), hugetlb_remove_rmap(f))
RR_RET(int, hugetlb_try_share_anon_rmap, (struct folio *f), hugetlb_try_share_anon_rmap(f))
RR_RET(bool, unmap_huge_pmd_locked, (struct vm_area_struct *v, unsigned long a, pmd_t *p, struct folio *f), unmap_huge_pmd_locked(v,a,p,f))
RR_VOID(split_huge_pmd_locked, (struct vm_area_struct *v, unsigned long a, pmd_t *p, bool freeze), split_huge_pmd_locked(v,a,p,freeze))
RR_RET(swp_entry_t, make_hwpoison_entry, (struct page *p), make_hwpoison_entry(p))
RR_RET(swp_entry_t, page_swap_entry, (struct page *p), page_swap_entry(p))
RR_RET(pte_t, swp_entry_to_pte, (swp_entry_t e), swp_entry_to_pte(e))
RR_RET(int, folio_dup_swap, (struct folio *f, struct page *p), folio_dup_swap(f,p))
RR_VOID(folio_put_swap, (struct folio *f, struct page *p), folio_put_swap(f,p))
RR_RET(int, arch_unmap_one, (struct mm_struct *m, struct vm_area_struct *v, unsigned long a, pte_t p), arch_unmap_one(m,v,a,p))
RR_RET(int, folio_try_share_anon_rmap_pte, (struct folio *f, struct page *p), folio_try_share_anon_rmap_pte(f,p))
RR_VOID(mm_prepare_for_swap_entries, (struct mm_struct *m), mm_prepare_for_swap_entries(m))
RR_VOID(add_mm_counter, (struct mm_struct *m, int i, long n), add_mm_counter(m,i,n))
RR_VOID(dec_mm_counter, (struct mm_struct *m, int i), dec_mm_counter(m,i))
RR_VOID(inc_mm_counter, (struct mm_struct *m, int i), inc_mm_counter(m,i))
RR_RET(int, mm_counter, (struct folio *f), mm_counter(f))
RR_RET(int, mm_counter_file, (struct folio *f), mm_counter_file(f))
RR_VOID(update_hiwater_rss, (struct mm_struct *m), update_hiwater_rss(m))
RR_RET(softleaf_t, softleaf_from_pte, (pte_t p), softleaf_from_pte(p))
RR_RET(unsigned long, softleaf_to_pfn, (softleaf_t e), softleaf_to_pfn(e))
RR_RET(bool, softleaf_is_device_private_write, (softleaf_t e), softleaf_is_device_private_write(e))
RR_VOID(cond_install_uffd_wp_ptes, (struct vm_area_struct *v, unsigned long a, pte_t *p, pte_t old, unsigned int n), cond_install_uffd_wp_ptes(v,a,p,old,n))
RR_RET(bool, userfaultfd_armed, (struct vm_area_struct *v), userfaultfd_armed(v))
#ifdef CONFIG_ARCH_HAS_PMD_SOFTLEAVES
RR_RET(unsigned long, pmd_pfn, (pmd_t p), pmd_pfn(p))
RR_RET(softleaf_t, softleaf_from_pmd, (pmd_t p), softleaf_from_pmd(p))
RR_RET(int, set_pmd_migration_entry, (struct page_vma_mapped_walk *w, struct page *p), set_pmd_migration_entry(w,p))
#endif
RR_RET(unsigned long, page_to_pfn, (struct page *p), page_to_pfn(p))
RR_RET(swp_entry_t, make_writable_migration_entry, (unsigned long p), make_writable_migration_entry(p))
RR_RET(swp_entry_t, make_readable_exclusive_migration_entry, (unsigned long p), make_readable_exclusive_migration_entry(p))
RR_RET(swp_entry_t, make_readable_migration_entry, (unsigned long p), make_readable_migration_entry(p))
RR_RET(swp_entry_t, make_migration_entry_young, (swp_entry_t e), make_migration_entry_young(e))
RR_RET(swp_entry_t, make_migration_entry_dirty, (swp_entry_t e), make_migration_entry_dirty(e))
RR_VOID(trace_set_migration_pte, (unsigned long a, pte_t p, unsigned int o), trace_set_migration_pte(a,pte_val(p),o))
#ifdef CONFIG_DEVICE_PRIVATE
RR_RET(struct page *, get_user_page_vma_remote, (struct mm_struct *m, unsigned long a, unsigned int f, struct vm_area_struct **v), get_user_page_vma_remote(m,a,f,v))
RR_RET(bool, is_err, (const void *p), IS_ERR(p))
RR_RET(void *, err_ptr, (long e), ERR_PTR(e))
RR_RET(struct folio *, page_folio, (struct page *p), page_folio(p))
RR_RET(int, folio_lock_killable, (struct folio *f), folio_lock_killable(f))
RR_VOID(mmu_notifier_range_init_owner, (struct mmu_notifier_range *r, enum mmu_notifier_event e, unsigned int f, struct mm_struct *m, unsigned long s, unsigned long end, void *o), mmu_notifier_range_init_owner(r,e,f,m,s,end,o))
RR_RET(struct folio *, folio_walk_start, (struct folio_walk *w, struct vm_area_struct *v, unsigned long a, unsigned int f), folio_walk_start(w,v,a,f))
RR_VOID(folio_walk_end, (struct folio_walk *w, struct vm_area_struct *v), folio_walk_end(w,v))
RR_RET(pte_t, fw_pte, (const struct folio_walk *w), w->pte)
RR_VOID(fw_set_pte, (struct folio_walk *w, pte_t p), w->pte = p)
RR_RET(pte_t *, fw_ptep, (const struct folio_walk *w), w->ptep)
RR_RET(swp_entry_t, make_device_exclusive_entry, (unsigned long p), make_device_exclusive_entry(p))
#endif
#undef RR_RET
#undef RR_VOID
#endif
