/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef RUST_UFFD_NATIVE_PRIMITIVES_H
#define RUST_UFFD_NATIVE_PRIMITIVES_H
#include "userfaultfd_native_includes.h"
/* No original userfaultfd routine is forwarded here. Each named leaf invokes
 * exactly the configured native operation indicated by its final argument.
 * Native-header algorithm dependencies are enumerated in COVERAGE.md. */
#ifdef RUST_UFFD_DEFINE_LEAVES
#define UF_RET(t,n,a,e) t rust_uffd_##n a; t rust_uffd_##n a { return (e); }
#define UF_VOID(n,a,e) void rust_uffd_##n a; void rust_uffd_##n a { e; }
#else
#define UF_RET(t,n,a,e) t rust_uffd_##n a;
#define UF_VOID(n,a,e) void rust_uffd_##n a;
#endif
UF_RET(unsigned long *, vma_start_ptr, (struct vm_area_struct *v), &v->vm_start)
UF_RET(unsigned long *, vma_end_ptr, (struct vm_area_struct *v), &v->vm_end)
UF_RET(const vm_flags_t *, vma_flags_ptr, (struct vm_area_struct *v), &v->vm_flags)
UF_RET(vma_flags_t, vma_native_flags, (struct vm_area_struct *v), v->flags)
/* VM_SPECIAL contains native VMA-mask function calls, so evaluate it at the
 * original function-use boundary instead of in a static initializer. */
UF_RET(vm_flags_t, vm_special_flags, (void), VM_SPECIAL)
UF_RET(struct vm_area_struct *, vmf_vma, (struct vm_fault *f), f->vma)
UF_RET(unsigned long, vmf_address, (struct vm_fault *f), f->address)
UF_RET(unsigned long, vmf_real_address, (struct vm_fault *f), f->real_address)
UF_RET(unsigned int, vmf_flags, (struct vm_fault *f), f->flags)
UF_RET(unsigned long, mm_task_size, (struct mm_struct *m), m->task_size)
UF_RET(struct task_struct *, current, (void), current)
UF_RET(struct mm_struct *, current_mm, (void), current->mm)
UF_RET(unsigned int, current_flags, (void), current->flags)
UF_RET(struct page *, folio_page, (struct folio *f), &f->page)
UF_RET(pgoff_t *, folio_index_ptr, (struct folio *f), &f->index)
UF_RET(swp_entry_t, folio_swap, (struct folio *f), f->swap)
UF_RET(bool, warn_anon_shared, (bool b), WARN_ON_ONCE(b))
UF_RET(bool, warn_move_anon, (bool b), WARN_ON_ONCE(b))
UF_RET(bool, warn_exit_event, (bool b), WARN_ON_ONCE(b))
UF_VOID(warn_range, (bool b), VM_WARN_ONCE(b, "The address range exceeds VMA boundary.\n"))
UF_VOID(warn_unsupported_copy, (void), VM_WARN_ONCE(1, "UFFDIO_COPY for unsupported VMA"))
UF_VOID(warn_unsupported_continue, (void), VM_WARN_ONCE(1, "UFFDIO_CONTINUE for unsupported VMA"))
UF_VOID(warn_unknown_folio_fill, (uffd_flags_t f), VM_WARN_ONCE(1, "Unknown UFFDIO operation, flags: %x", f))
UF_VOID(warn_unknown_pte_fill, (uffd_flags_t f), VM_WARN_ONCE(1, "Unknown UFFDIO operation, flags: %x", f))
UF_RET(struct folio *, vma_alloc_folio, (gfp_t g, int o, struct vm_area_struct *v, unsigned long a), vma_alloc_folio(g,o,v,a))
UF_RET(int, mem_cgroup_charge, (struct folio *f, struct mm_struct *m, gfp_t g), mem_cgroup_charge(f,m,g))
UF_VOID(folio_put, (struct folio *f), folio_put(f))
UF_RET(bool, vma_is_anonymous, (struct vm_area_struct *v), vma_is_anonymous(v))
UF_VOID(mmap_assert_locked, (struct mm_struct *m), mmap_assert_locked(m))
UF_RET(struct vm_area_struct *, vma_lookup, (struct mm_struct *m, unsigned long a), vma_lookup(m,a))
UF_RET(int, anon_vma_prepare, (struct vm_area_struct *v), anon_vma_prepare(v))
UF_VOID(mmap_read_lock, (struct mm_struct *m), mmap_read_lock(m))
UF_VOID(mmap_read_unlock, (struct mm_struct *m), mmap_read_unlock(m))
UF_VOID(mmap_write_lock, (struct mm_struct *m), mmap_write_lock(m))
UF_VOID(mmap_write_unlock, (struct mm_struct *m), mmap_write_unlock(m))
#ifdef CONFIG_PER_VMA_LOCK
UF_VOID(vma_end_read, (struct vm_area_struct *v), vma_end_read(v))
UF_RET(bool, vma_start_read_locked, (struct vm_area_struct *v), vma_start_read_locked(v))
UF_RET(bool, vma_start_read_locked_nested, (struct vm_area_struct *v, int s), vma_start_read_locked_nested(v,s))
UF_RET(struct vm_area_struct *, lock_vma_under_rcu, (struct mm_struct *m, unsigned long a), lock_vma_under_rcu(m,a))
#endif
UF_RET(int, atomic_read, (const atomic_t *p), atomic_read(p))
UF_VOID(atomic_set, (atomic_t *p, int v), atomic_set(p,v))
UF_VOID(atomic_inc, (atomic_t *p), atomic_inc(p))
UF_VOID(atomic_dec, (atomic_t *p), atomic_dec(p))
UF_RET(bool, is_vm_hugetlb_page, (struct vm_area_struct *v), is_vm_hugetlb_page(v))
UF_RET(pgd_t *, pgd_offset, (struct mm_struct *m, unsigned long a), pgd_offset(m,a))
UF_RET(p4d_t *, p4d_alloc, (struct mm_struct *m, pgd_t *p, unsigned long a), p4d_alloc(m,p,a))
UF_RET(pud_t *, pud_alloc, (struct mm_struct *m, p4d_t *p, unsigned long a), pud_alloc(m,p,a))
UF_RET(pmd_t *, pmd_alloc, (struct mm_struct *m, pud_t *p, unsigned long a), pmd_alloc(m,p,a))
UF_RET(pmd_t, pmdp_get_lockless, (pmd_t *p), pmdp_get_lockless(p))
UF_RET(bool, pmd_none, (pmd_t p), pmd_none(p))
UF_RET(bool, pmd_present, (pmd_t p), pmd_present(p))
UF_RET(bool, pmd_leaf, (pmd_t p), pmd_leaf(p))
UF_RET(bool, pmd_bad, (pmd_t p), pmd_bad(p))
UF_RET(pgoff_t, linear_page_index, (struct vm_area_struct *v, unsigned long a), linear_page_index(v,a))
UF_RET(loff_t, i_size_read, (const struct inode *i), i_size_read(i))
UF_RET(struct folio *, page_folio, (struct page *p), page_folio(p))
UF_RET(struct address_space *, folio_mapping, (struct folio *f), folio_mapping(f))
UF_RET(pte_t, mk_pte, (struct page *p, pgprot_t prot), mk_pte(p,prot))
UF_RET(pte_t, pte_mkdirty, (pte_t p), pte_mkdirty(p))
UF_RET(pte_t, pte_mkwrite, (pte_t p, struct vm_area_struct *v), pte_mkwrite(p,v))
UF_RET(pte_t, pte_mkuffd, (pte_t p), pte_mkuffd(p))
UF_RET(pte_t *, pte_offset_map_lock, (struct mm_struct *m, pmd_t *p, unsigned long a, spinlock_t **l), pte_offset_map_lock(m,p,a,l))
UF_RET(pte_t, ptep_get, (pte_t *p), ptep_get(p))
UF_RET(bool, pte_none, (pte_t p), pte_none(p))
UF_RET(bool, pte_is_uffd_marker, (pte_t p), pte_is_uffd_marker(p))
UF_VOID(folio_add_file_rmap_pte, (struct folio *f, struct page *p, struct vm_area_struct *v), folio_add_file_rmap_pte(f,p,v))
UF_VOID(folio_add_lru_vma, (struct folio *f, struct vm_area_struct *v), folio_add_lru_vma(f,v))
UF_VOID(inc_mm_counter, (struct mm_struct *m, int c), inc_mm_counter(m,c))
UF_RET(int, mm_counter, (struct folio *f), mm_counter(f))
UF_VOID(set_pte_at, (struct mm_struct *m, unsigned long a, pte_t *p, pte_t e), set_pte_at(m,a,p,e))
UF_VOID(folio_unlock, (struct folio *f), folio_unlock(f))
UF_VOID(update_mmu_cache, (struct vm_area_struct *v, unsigned long a, pte_t *p), update_mmu_cache(v,a,p))
UF_VOID(pte_unmap_unlock, (pte_t *p, spinlock_t *l), pte_unmap_unlock(p,l))
UF_RET(void *, kmap_local_folio, (struct folio *f, size_t o), kmap_local_folio(f,o))
UF_VOID(kunmap_local, (const void *p), kunmap_local(p))
UF_VOID(pagefault_disable, (void), pagefault_disable())
UF_VOID(pagefault_enable, (void), pagefault_enable())
UF_RET(unsigned long, copy_from_user, (void *d, const void __user *s, unsigned long n), copy_from_user(d,s,n))
UF_RET(unsigned long, copy_to_user, (void __user *d, const void *s, unsigned long n), copy_to_user(d,s,n))
UF_VOID(flush_dcache_folio, (struct folio *f), flush_dcache_folio(f))
UF_RET(vma_flags_t, retry_vma_flags, (struct vm_area_struct *v), vma_flags_and_mask(&v->flags, append_vma_flags(__VMA_UFFD_FLAGS, VMA_SHARED_BIT)))
UF_RET(pgoff_t, vma_start_pgoff, (struct vm_area_struct *v), vma_start_pgoff(v))
UF_RET(struct file *, get_file, (struct file *f), get_file(f))
UF_RET(bool, vma_flags_same_pair, (const vma_flags_t *a, const vma_flags_t *b), vma_flags_same_pair(a,b))
UF_VOID(clear_user_highpage, (struct page *p, unsigned long a), clear_user_highpage(p,a))
UF_VOID(__folio_mark_uptodate, (struct folio *f), __folio_mark_uptodate(f))
UF_RET(bool, mm_forbids_zeropage, (struct mm_struct *m), mm_forbids_zeropage(m))
UF_RET(pte_t, pte_mkspecial, (pte_t p), pte_mkspecial(p))
UF_RET(pte_t, pfn_pte, (unsigned long p, pgprot_t prot), pfn_pte(p,prot))
UF_RET(unsigned long, zero_pfn, (unsigned long a), zero_pfn(a))
UF_RET(struct inode *, file_inode, (struct file *f), file_inode(f))
UF_RET(struct page *, folio_file_page, (struct folio *f, pgoff_t p), folio_file_page(f,p))
UF_RET(bool, PageHWPoison, (struct page *p), PageHWPoison(p))
UF_RET(pte_t, make_pte_marker, (pte_marker p), make_pte_marker(p))
UF_RET(unsigned long, vma_kernel_pagesize, (struct vm_area_struct *v), vma_kernel_pagesize(v))
#ifdef CONFIG_HUGETLB_PAGE
UF_RET(pgoff_t, hugetlb_linear_page_index, (struct vm_area_struct *v, unsigned long a), hugetlb_linear_page_index(v,a))
UF_RET(struct mutex *, hugetlb_fault_mutex, (u32 h), &hugetlb_fault_mutex_table[h])
UF_RET(pte_t, huge_ptep_get, (struct mm_struct *m, unsigned long a, pte_t *p), huge_ptep_get(m,a,p))
UF_RET(bool, huge_pte_none, (pte_t p), huge_pte_none(p))
UF_RET(bool, huge_pte_write, (pte_t p), huge_pte_write(p))
UF_RET(bool, huge_pte_uffd, (pte_t p), huge_pte_uffd(p))
UF_RET(pte_t *, hugetlb_walk, (struct vm_area_struct *v, unsigned long a, unsigned long s), hugetlb_walk(v,a,s))
UF_RET(unsigned long, vma_mmu_pagesize, (struct vm_area_struct *v), vma_mmu_pagesize(v))
#endif
UF_VOID(hugetlb_vma_lock_read, (struct vm_area_struct *v), hugetlb_vma_lock_read(v))
UF_VOID(hugetlb_vma_unlock_read, (struct vm_area_struct *v), hugetlb_vma_unlock_read(v))
UF_VOID(cond_resched, (void), cond_resched())
UF_RET(bool, fatal_signal_pending, (struct task_struct *t), fatal_signal_pending(t))
UF_RET(bool, signal_pending, (struct task_struct *t), signal_pending(t))
UF_VOID(smp_wmb, (void), smp_wmb())
UF_VOID(smp_mb, (void), smp_mb())
UF_RET(bool, vma_wants_manual_pte_write_upgrade, (struct vm_area_struct *v), vma_wants_manual_pte_write_upgrade(v))
UF_VOID(tlb_gather_mmu, (struct mmu_gather *t, struct mm_struct *m), tlb_gather_mmu(t,m))
UF_VOID(tlb_finish_mmu, (struct mmu_gather *t), tlb_finish_mmu(t))
UF_VOID(vma_iter_init, (struct vma_iterator *i, struct mm_struct *m, unsigned long a), vma_iter_init(i,m,a))
UF_RET(struct vm_area_struct *, vma_find, (struct vma_iterator *i, unsigned long e), vma_find(i,e))
UF_VOID(vma_iter_set, (struct vma_iterator *i, unsigned long a), vma_iter_set(i,a))
UF_RET(struct vm_area_struct *, vma_prev, (struct vma_iterator *i), vma_prev(i))
UF_RET(struct vm_area_struct *, vma_next, (struct vma_iterator *i), vma_next(i))
UF_RET(bool, userfaultfd_wp, (struct vm_area_struct *v), userfaultfd_wp(v))
UF_RET(bool, userfaultfd_rwp, (struct vm_area_struct *v), userfaultfd_rwp(v))
UF_RET(bool, userfaultfd_missing, (struct vm_area_struct *v), userfaultfd_missing(v))
UF_RET(bool, userfaultfd_protected, (struct vm_area_struct *v), userfaultfd_protected(v))
UF_VOID(spin_lock, (spinlock_t *l), spin_lock(l))
UF_VOID(spin_lock_nested, (spinlock_t *l, int s), spin_lock_nested(l,s))
UF_VOID(spin_unlock, (spinlock_t *l), spin_unlock(l))
UF_VOID(spin_lock_irq, (spinlock_t *l), spin_lock_irq(l))
UF_VOID(spin_unlock_irq, (spinlock_t *l), spin_unlock_irq(l))
UF_VOID(mutex_lock, (struct mutex *l), mutex_lock(l))
UF_RET(bool, spin_is_locked, (const spinlock_t *l), spin_is_locked(l))
UF_RET(bool, pte_same, (pte_t a, pte_t b), pte_same(a,b))
UF_RET(bool, pmd_same, (pmd_t a, pmd_t b), pmd_same(a,b))
UF_RET(bool, pte_present, (pte_t p), pte_present(p))
UF_RET(bool, is_zero_pfn, (unsigned long p), is_zero_pfn(p))
UF_RET(unsigned long, pte_pfn, (pte_t p), pte_pfn(p))
UF_RET(struct folio *, vm_normal_folio, (struct vm_area_struct *v, unsigned long a, pte_t p), vm_normal_folio(v,a,p))
UF_RET(bool, folio_trylock, (struct folio *f), folio_trylock(f))
UF_RET(bool, PageAnonExclusive, (struct page *p), PageAnonExclusive(p))
UF_RET(bool, folio_test_large, (struct folio *f), folio_test_large(f))
UF_RET(unsigned long, pmd_addr_end, (unsigned long a, unsigned long e), pmd_addr_end(a,e))
UF_VOID(flush_cache_range, (struct vm_area_struct *v, unsigned long a, unsigned long e), flush_cache_range(v,a,e))
UF_RET(bool, folio_maybe_dma_pinned, (struct folio *f), folio_maybe_dma_pinned(f))
UF_VOID(lazy_mmu_mode_enable, (void), lazy_mmu_mode_enable())
UF_VOID(lazy_mmu_mode_disable, (void), lazy_mmu_mode_disable())
UF_RET(pte_t, ptep_get_and_clear, (struct mm_struct *m, unsigned long a, pte_t *p), ptep_get_and_clear(m,a,p))
UF_RET(pgoff_t, linear_anon_page_index, (struct vm_area_struct *v, unsigned long a), linear_anon_page_index(v,a))
UF_RET(pte_t, folio_mk_pte, (struct folio *f, pgprot_t p), folio_mk_pte(f,p))
UF_RET(bool, pgtable_supports_soft_dirty, (void), pgtable_supports_soft_dirty())
UF_RET(pte_t, pte_mksoft_dirty, (pte_t p), pte_mksoft_dirty(p))
UF_RET(bool, pte_dirty, (pte_t p), pte_dirty(p))
UF_RET(pte_t, pte_modify, (pte_t p, pgprot_t g), pte_modify(p,g))
#ifdef CONFIG_ARCH_HAS_PTE_PROTNONE
UF_RET(pgprot_t, page_none, (void), PAGE_NONE)
#endif
UF_VOID(flush_tlb_range, (struct vm_area_struct *v, unsigned long s, unsigned long e), flush_tlb_range(v,s,e))
UF_RET(bool, folio_test_swapcache, (struct folio *f), folio_test_swapcache(f))
UF_RET(bool, swap_cache_has_folio, (swp_entry_t e), swap_cache_has_folio(e))
UF_RET(pte_t, pte_swp_mksoft_dirty, (pte_t p), pte_swp_mksoft_dirty(p))
UF_RET(pte_t, pte_swp_mkuffd, (pte_t p), pte_swp_mkuffd(p))
UF_RET(pte_t, ptep_clear_flush, (struct vm_area_struct *v, unsigned long a, pte_t *p), ptep_clear_flush(v,a,p))
UF_VOID(mmu_notifier_range_init, (struct mmu_notifier_range *r, enum mmu_notifier_event e, unsigned int f, struct mm_struct *m, unsigned long s, unsigned long end), mmu_notifier_range_init(r,e,f,m,s,end))
UF_VOID(mmu_notifier_invalidate_range_start, (struct mmu_notifier_range *r), mmu_notifier_invalidate_range_start(r))
UF_VOID(mmu_notifier_invalidate_range_end, (struct mmu_notifier_range *r), mmu_notifier_invalidate_range_end(r))
UF_RET(pte_t *, pte_offset_map_rw_nolock, (struct mm_struct *m, pmd_t *p, unsigned long a, pmd_t *val, spinlock_t **l), pte_offset_map_rw_nolock(m,p,a,val,l))
UF_RET(bool, pmd_trans_huge, (pmd_t p), pmd_trans_huge(p))
UF_VOID(folio_get, (struct folio *f), folio_get(f))
UF_VOID(folio_lock, (struct folio *f), folio_lock(f))
UF_VOID(pte_unmap, (pte_t *p), pte_unmap(p))
UF_RET(bool, folio_test_anon, (struct folio *f), folio_test_anon(f))
UF_RET(int, split_folio, (struct folio *f), split_folio(f))
UF_RET(softleaf_t, softleaf_from_pte, (pte_t p), softleaf_from_pte(p))
UF_RET(bool, softleaf_is_migration, (softleaf_t e), softleaf_is_migration(e))
UF_RET(bool, softleaf_is_swap, (softleaf_t e), softleaf_is_swap(e))
UF_RET(bool, pte_swp_exclusive, (pte_t p), pte_swp_exclusive(p))
UF_RET(struct swap_info_struct *, get_swap_device, (swp_entry_t e), get_swap_device(e))
UF_VOID(put_swap_device, (struct swap_info_struct *s), put_swap_device(s))
UF_RET(struct folio *, swap_cache_get_folio, (swp_entry_t e), swap_cache_get_folio(e))
UF_RET(unsigned long, pgprot_val, (pgprot_t p), pgprot_val(p))
UF_RET(pmd_t *, mm_find_pmd, (struct mm_struct *m, unsigned long a), mm_find_pmd(m,a))
UF_RET(spinlock_t *, pmd_trans_huge_lock, (pmd_t *p, struct vm_area_struct *v), pmd_trans_huge_lock(p,v))
UF_RET(struct folio *, pmd_folio, (pmd_t p), pmd_folio(p))
UF_RET(bool, is_huge_zero_folio, (struct folio *f), is_huge_zero_folio(f))
UF_VOID(split_huge_pmd, (struct vm_area_struct *v, pmd_t *p, unsigned long a), split_huge_pmd(v,p,a))
UF_RET(int, pte_alloc, (struct mm_struct *m, pmd_t *p), pte_alloc(m,p))
UF_RET(bool, uffd_supports_wp_marker, (void), uffd_supports_wp_marker())
UF_VOID(vm_flags_reset, (struct vm_area_struct *v, vm_flags_t f), vm_flags_reset(v,f))
UF_VOID(vma_start_write, (struct vm_area_struct *v), vma_start_write(v))
UF_VOID(vma_flags_clear_mask, (vma_flags_t *f, vma_flags_t mask), vma_flags_clear_mask(f,mask))
UF_VOID(vma_flags_set_mask, (vma_flags_t *f, vma_flags_t mask), vma_flags_set_mask(f,mask))
UF_RET(vma_flags_t, all_uffd_vma_flags, (void), __VMA_UFFD_FLAGS)
UF_RET(vma_flags_t, legacy_to_vma_flags, (vm_flags_t f), legacy_to_vma_flags(f))
UF_RET(bool, vma_test, (struct vm_area_struct *v, vma_flag_t b), vma_test(v,b))
UF_RET(bool, vma_test_all_mask, (struct vm_area_struct *v, vma_flags_t m), vma_test_all_mask(v,m))
UF_RET(bool, uffd_disable_huge_pmd_share, (struct vm_area_struct *v), uffd_disable_huge_pmd_share(v))
UF_RET(bool, mmget_not_zero, (struct mm_struct *m), mmget_not_zero(m))
UF_RET(unsigned int, read_features, (struct userfaultfd_ctx *c), READ_ONCE(c->features))
UF_VOID(write_features, (struct userfaultfd_ctx *c, unsigned int f), WRITE_ONCE(c->features,f))
UF_RET(unsigned int, cmpxchg_features, (struct userfaultfd_ctx *c, unsigned int old, unsigned int new), cmpxchg(&c->features,old,new))
UF_RET(bool, read_released, (struct userfaultfd_ctx *c), READ_ONCE(c->released))
UF_VOID(write_released, (struct userfaultfd_ctx *c, bool v), WRITE_ONCE(c->released,v))
UF_VOID(write_waken, (struct userfaultfd_wait_queue *q, bool v), WRITE_ONCE(q->waken,v))
UF_RET(unsigned long, msg_address, (const struct uffd_msg *m), m->arg.pagefault.address)
UF_VOID(msg_set_pagefault, (struct uffd_msg *m, unsigned long a, u64 f, int tid), m->arg.pagefault.address=a; m->arg.pagefault.flags=f; m->arg.pagefault.feat.ptid=tid)
UF_RET(struct userfaultfd_ctx *, msg_fork_ctx, (const struct uffd_msg *m), (struct userfaultfd_ctx *)(unsigned long)m->arg.reserved.reserved1)
UF_VOID(msg_set_fork_ctx, (struct uffd_msg *m, struct userfaultfd_ctx *c), m->arg.reserved.reserved1=(unsigned long)c)
UF_VOID(msg_set_fork_fd, (struct uffd_msg *m, int fd), m->arg.fork.ufd=fd)
UF_VOID(msg_set_remap, (struct uffd_msg *m, unsigned long f, unsigned long t, unsigned long l), m->arg.remap.from=f; m->arg.remap.to=t; m->arg.remap.len=l)
UF_VOID(msg_set_remove, (struct uffd_msg *m, unsigned long s, unsigned long e), m->arg.remove.start=s; m->arg.remove.end=e)
UF_VOID(refcount_inc, (refcount_t *p), refcount_inc(p))
UF_RET(bool, refcount_dec_and_test, (refcount_t *p), refcount_dec_and_test(p))
UF_VOID(refcount_set, (refcount_t *p, int v), refcount_set(p,v))
UF_RET(bool, waitqueue_active, (struct wait_queue_head *q), waitqueue_active(q))
UF_VOID(mmdrop, (struct mm_struct *m), mmdrop(m))
UF_VOID(mmgrab, (struct mm_struct *m), mmgrab(m))
UF_RET(int, task_pid_vnr, (struct task_struct *t), task_pid_vnr(t))
UF_VOID(assert_fault_locked, (struct vm_fault *f), assert_fault_locked(f))
UF_RET(bool, pgd_present, (pgd_t p), pgd_present(p))
UF_RET(bool, p4d_present, (p4d_t p), p4d_present(p))
UF_RET(bool, pud_present, (pud_t p), pud_present(p))
UF_RET(p4d_t *, p4d_offset, (pgd_t *p, unsigned long a), p4d_offset(p,a))
UF_RET(pud_t *, pud_offset, (p4d_t *p, unsigned long a), pud_offset(p,a))
UF_RET(pmd_t *, pmd_offset, (pud_t *p, unsigned long a), pmd_offset(p,a))
UF_RET(bool, pmd_write, (pmd_t p), pmd_write(p))
UF_RET(bool, pmd_protnone, (pmd_t p), pmd_protnone(p))
UF_RET(bool, pmd_uffd, (pmd_t p), pmd_uffd(p))
UF_RET(pte_t *, pte_offset_map, (pmd_t *p, unsigned long a), pte_offset_map(p,a))
UF_RET(bool, pte_write, (pte_t p), pte_write(p))
UF_RET(bool, pte_protnone, (pte_t p), pte_protnone(p))
UF_RET(bool, pte_uffd, (pte_t p), pte_uffd(p))
UF_VOID(release_fault_lock, (struct vm_fault *f), release_fault_lock(f))
UF_VOID(init_waitqueue_func_entry, (wait_queue_entry_t *w, wait_queue_func_t f), init_waitqueue_func_entry(w,f))
UF_VOID(init_waitqueue_entry, (wait_queue_entry_t *w, struct task_struct *t), init_waitqueue_entry(w,t))
UF_VOID(declare_waitqueue, (wait_queue_entry_t *w, struct task_struct *t), *w=(wait_queue_entry_t)__WAITQUEUE_INITIALIZER((*w),t))
UF_VOID(__add_wait_queue, (struct wait_queue_head *q, wait_queue_entry_t *w), __add_wait_queue(q,w))
UF_VOID(__remove_wait_queue, (struct wait_queue_head *q, wait_queue_entry_t *w), __remove_wait_queue(q,w))
UF_VOID(set_current_state, (unsigned int s), set_current_state(s))
UF_VOID(__set_current_state, (unsigned int s), __set_current_state(s))
UF_VOID(wake_up_poll, (struct wait_queue_head *q, __poll_t p), wake_up_poll(q,p))
UF_VOID(wake_up_locked, (struct wait_queue_head *q), wake_up_locked(q))
UF_VOID(wake_up_all, (struct wait_queue_head *q), wake_up_all(q))
UF_RET(bool, list_empty_careful, (const struct list_head *h), list_empty_careful(h))
UF_RET(bool, list_empty, (const struct list_head *h), list_empty(h))
UF_VOID(list_init, (struct list_head *h), INIT_LIST_HEAD(h))
UF_VOID(list_add_tail, (struct list_head *n, struct list_head *h), list_add_tail(n,h))
UF_VOID(list_del_init, (struct list_head *h), list_del_init(h))
UF_VOID(list_del, (struct list_head *h), list_del(h))
UF_VOID(list_move, (struct list_head *n, struct list_head *h), list_move(n,h))
UF_RET(void *, kmalloc, (size_t s, gfp_t g), kmalloc(s,g))
UF_RET(void *, kzalloc, (size_t s, gfp_t g), kzalloc(s,g))
UF_RET(void *, kmem_cache_alloc, (struct kmem_cache *s, gfp_t g), kmem_cache_alloc(s,g))
UF_RET(struct kmem_cache *, kmem_cache_create, (const char *n, unsigned int s, unsigned int a, slab_flags_t f, void (*ctor)(void *)), kmem_cache_create(n,s,a,f,ctor))
UF_VOID(migration_entry_wait, (struct mm_struct *m, pmd_t *p, unsigned long a), migration_entry_wait(m,p,a))
UF_VOID(hugetlb_unshare_all_pmds, (struct vm_area_struct *v), hugetlb_unshare_all_pmds(v))
UF_VOID(init_rwsem_fork, (struct rw_semaphore *s), init_rwsem(s))
UF_VOID(init_rwsem_new, (struct rw_semaphore *s), init_rwsem(s))
UF_VOID(lockdep_assert_held, (const spinlock_t *l), lockdep_assert_held(l))
UF_VOID(poll_wait, (struct file *f, struct wait_queue_head *q, poll_table *p), poll_wait(f,q,p))
UF_VOID(write_seqcount_begin, (seqcount_spinlock_t *s), write_seqcount_begin(s))
UF_VOID(write_seqcount_end, (seqcount_spinlock_t *s), write_seqcount_end(s))
UF_RET(unsigned int, read_seqcount_begin, (const seqcount_spinlock_t *s), read_seqcount_begin(s))
UF_RET(bool, read_seqcount_retry, (const seqcount_spinlock_t *s, unsigned int v), read_seqcount_retry(s,v))
UF_RET(size_t, iov_iter_count, (const struct iov_iter *i), iov_iter_count(i))
UF_RET(bool, copy_to_iter_full, (const void *p, size_t n, struct iov_iter *i), copy_to_iter_full(p,n,i))
UF_RET(bool, pgtable_supports_uffd, (void), pgtable_supports_uffd())
UF_RET(bool, vma_is_accessible, (struct vm_area_struct *v), vma_is_accessible(v))
UF_RET(int, put_user_i64, (s64 v, s64 __user *p), put_user(v,p))
UF_RET(int, put_user_u64, (u64 v, u64 __user *p), put_user(v,p))
/* Four original initializer sites have distinct lockdep class keys. */
UF_VOID(init_waitqueue_head_pending, (struct wait_queue_head *q), init_waitqueue_head(q))
UF_VOID(init_waitqueue_head_fault, (struct wait_queue_head *q), init_waitqueue_head(q))
UF_VOID(init_waitqueue_head_event, (struct wait_queue_head *q), init_waitqueue_head(q))
UF_VOID(init_waitqueue_head_fd, (struct wait_queue_head *q), init_waitqueue_head(q))
UF_VOID(seqcount_spinlock_init, (seqcount_spinlock_t *s, spinlock_t *l), seqcount_spinlock_init(s,l))
#ifdef CONFIG_DEBUG_VM
UF_RET(bool, printk_ratelimit, (void), printk_ratelimit())
UF_VOID(debug_missing_allow_retry, (unsigned int f), pr_warn("FAULT_FLAG_ALLOW_RETRY missing %x\n", f))
#endif
#ifdef CONFIG_SYSCTL
void __init rust_uffd_register_sysctl_table(void);
#endif
#include "userfaultfd_native_warnings.h"
#undef UF_RET
#undef UF_VOID
#endif
