/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef VMSCAN_MGLRU_NATIVE_H
#define VMSCAN_MGLRU_NATIVE_H
#ifdef CONFIG_LRU_GEN
struct lru_gen_mm_list *rust_mglru_fallback_mm_list(void);
struct mm_struct *rust_mglru_mm_from_list(struct list_head *p);
struct list_head *rust_mglru_mm_list_ptr(struct mm_struct *mm);
unsigned long *rust_mglru_mm_bitmap_ptr(struct mm_struct *mm);
struct mem_cgroup *rust_mglru_mm_memcg(struct mm_struct *mm);
void rust_mglru_mm_set_memcg(struct mm_struct *mm, struct mem_cgroup *memcg);
struct task_struct *rust_mglru_mm_owner_protected(struct mm_struct *mm);
void rust_mglru_assert_task_alloc_lock(struct task_struct *task);
struct mutex *rust_mglru_state_mutex(void);
unsigned long *rust_mglru_min_ttl_ptr(void);
bool rust_mglru_get_cap(int cap);
void rust_mglru_switch_enable_cpuslocked(void);
void rust_mglru_switch_disable_cpuslocked(void);
void rust_mglru_cap_set_cpuslocked(int cap, bool enabled);
void rust_mglru_cap_set(int cap, bool enabled);
bool rust_mglru_arch_has_hw_pte_young(void);
bool rust_mglru_arch_has_hw_nonleaf_pmd_young(void);
u32 rust_mglru_hash_ptr(void *p, unsigned int bits);
bool rust_mglru_test_bit(int n, const unsigned long *p);
void rust_mglru_set_bit(int n, unsigned long *p);
void rust_mglru___set_bit(int n, unsigned long *p);
void rust_mglru_clear_bit(int n, unsigned long *p);
void rust_mglru_bitmap_zero(unsigned long *p, unsigned int n);
unsigned long rust_mglru_find_next_bit(const unsigned long *p, unsigned long n, unsigned long start);
void rust_mglru_assert_mm_list_lock(struct lru_gen_mm_list *p);
void rust_mglru_assert_lru_lock(struct lruvec *p);
void rust_mglru_assert_ptl(spinlock_t *p);
void rust_mglru_set_mask_bits(unsigned long *p, unsigned long mask, unsigned long bits);
bool rust_mglru_try_cmpxchg_ulong(unsigned long *p, unsigned long *old, unsigned long new);
void rust_mglru_store_release_ulong(unsigned long *p, unsigned long v);
long rust_mglru_read_long(const long *p);
void rust_mglru_write_long(long *p, long v);
u8 rust_mglru_read_byte(const u8 *p);
void rust_mglru_write_byte(u8 *p, u8 v);
unsigned long *rust_mglru_read_filter(unsigned long *const *p);
void rust_mglru_write_filter(unsigned long **p, unsigned long *v);
unsigned long rust_mglru_jiffies(void);
bool rust_mglru_time_is_before_jiffies(unsigned long a);
unsigned int rust_mglru_jiffies_to_msecs(unsigned long a);
unsigned long rust_mglru_msecs_to_jiffies(unsigned int a);
int rust_mglru_fls_long(unsigned long a);
int rust_mglru_first_memory_node(void);
int rust_mglru_next_memory_node(int nid);
int rust_mglru_first_node(void);
int rust_mglru_next_node(int nid);
bool rust_mglru_node_memory(int nid);
unsigned long rust_mglru_vma_start(struct vm_area_struct *v);
unsigned long rust_mglru_vma_end(struct vm_area_struct *v);
bool rust_mglru_vma_locked_or_special(struct vm_area_struct *v);
bool rust_mglru_vma_special(struct vm_area_struct *v);
const vma_flags_t *rust_mglru_vma_flags_ptr(struct vm_area_struct *v);
void rust_mglru_vma_iter_init(struct vma_iterator *vmi, struct mm_struct *mm, unsigned long addr);
struct vm_area_struct *rust_mglru_vma_next(struct vma_iterator *vmi);
unsigned long rust_mglru_pte_pfn(pte_t p);
bool rust_mglru_pte_present(pte_t p);
bool rust_mglru_pte_special(pte_t p);
bool rust_mglru_pte_young(pte_t p);
bool rust_mglru_pte_dirty(pte_t p);
bool rust_mglru_is_zero_pfn(unsigned long pfn);
unsigned long rust_mglru_pmd_pfn(pmd_t p);
bool rust_mglru_pmd_present(pmd_t p);
bool rust_mglru_is_huge_zero_pmd(pmd_t p);
bool rust_mglru_pmd_young(pmd_t p);
bool rust_mglru_pmd_dirty(pmd_t p);
bool rust_mglru_pmd_trans_huge(pmd_t p);
bool rust_mglru_pmd_same(pmd_t a, pmd_t b);
bool rust_mglru_pfn_valid(unsigned long pfn);
struct folio *rust_mglru_pfn_folio(unsigned long pfn);
unsigned int rust_mglru_cache_line_size(void);
pte_t *rust_mglru_pte_offset_map_rw_nolock(struct mm_struct *mm, pmd_t *pmd, unsigned long addr, pmd_t *val, spinlock_t **ptl);
void rust_mglru_pte_unmap(pte_t *p);
void rust_mglru_pte_unmap_unlock(pte_t *p, spinlock_t *ptl);
pmd_t rust_mglru_pmdp_get_lockless(pmd_t *p);
pte_t rust_mglru_ptep_get(pte_t *p);
void rust_mglru_lazy_mmu_mode_enable(void);
void rust_mglru_lazy_mmu_mode_disable(void);
unsigned long rust_mglru_pte_index(unsigned long addr);
unsigned long rust_mglru_pmd_index(unsigned long addr);
unsigned long rust_mglru_pud_index(unsigned long addr);
unsigned int rust_mglru_folio_pte_batch(struct folio *f, pte_t *p, pte_t *v, unsigned int nr);
bool rust_mglru_clear_young_ptes(struct vm_area_struct *vma, unsigned long addr, pte_t *p, unsigned int nr);
bool rust_mglru_pud_leaf(pud_t p);
bool rust_mglru_p4d_leaf(p4d_t p);
bool rust_mglru_pud_present(pud_t p);
pud_t rust_mglru_pudp_get(pud_t *p);
pmd_t *rust_mglru_pmd_offset(pud_t *p, unsigned long addr);
pud_t *rust_mglru_pud_offset(p4d_t *p, unsigned long addr);
spinlock_t *rust_mglru_pmd_lockptr(struct mm_struct *mm, pmd_t *p);
int rust_mglru_pmdp_test_and_clear_young(struct vm_area_struct *vma, unsigned long addr, pmd_t *p);
bool rust_mglru_pmdp_test_and_clear_young_notify(struct vm_area_struct *vma, unsigned long addr, pmd_t *p);
unsigned long rust_mglru_pmd_addr_end(unsigned long addr, unsigned long end);
unsigned long rust_mglru_pud_addr_end(unsigned long addr, unsigned long end);
struct lru_gen_mm_walk *rust_mglru_alloc_mm_walk(void);
unsigned long rust_mglru_spin_lock_irqsave(spinlock_t *lock);
void rust_mglru_spin_unlock_irqrestore(spinlock_t *lock, unsigned long flags);
bool rust_mglru_hlist_nulls_unhashed(const struct hlist_nulls_node *p);
void rust_mglru_hlist_nulls_del_rcu(struct hlist_nulls_node *p);
void rust_mglru_hlist_nulls_del_init_rcu(struct hlist_nulls_node *p);
void rust_mglru_hlist_nulls_add_head_rcu(struct hlist_nulls_node *p, struct hlist_nulls_head *h);
void rust_mglru_hlist_nulls_add_tail_rcu(struct hlist_nulls_node *p, struct hlist_nulls_head *h);
struct hlist_nulls_node *rust_mglru_hlist_first_rcu(const struct hlist_nulls_head *h);
struct hlist_nulls_node *rust_mglru_hlist_next_rcu(struct hlist_nulls_node *p);
bool rust_mglru_is_a_nulls(const struct hlist_nulls_node *p);
unsigned long rust_mglru_get_nulls_value(const struct hlist_nulls_node *p);
struct lru_gen_folio *rust_mglru_lrugen_from_list(struct hlist_nulls_node *p);
struct lruvec *rust_mglru_lruvec_from_lrugen(struct lru_gen_folio *p);
struct folio *rust_mglru_folio_from_lru(struct list_head *p);
int rust_mglru_numa_balancing_mode(void);
unsigned long rust_mglru_wmark_pages(struct zone *zone, int mark);
int rust_mglru_is_file_lru(int lru);
bool rust_mglru_is_active_lru(int lru);
int rust_mglru_tolower(int c);
void *rust_mglru_err_ptr(long err);
bool rust_mglru_is_err_or_null(const void *p);
unsigned long rust_mglru_debugfs_get_aux_num(struct file *file);
unsigned long rust_mglru_copy_from_user(void *dst, const void __user *src, unsigned long len);
int rust_mglru_scan_cmd(const char *cur, char *cmd, u64 *memcg, unsigned int *nid, unsigned long *seq, int *end, char *swap, unsigned long *opt);
void rust_mglru_init_hlist_nulls_head(struct hlist_nulls_head *head, unsigned long val);
void rust_mglru_spin_lock_init(int site, spinlock_t *p);
void rust_mglru_poison_lrugen_list(struct lruvec *v);
void rust_mglru_trace_isolate(int reclaim_idx, int order, unsigned long nr, unsigned long scanned, unsigned long skipped, unsigned long isolated, int lru);
void rust_mglru_trace_shrink_inactive(int nid, unsigned long scanned, unsigned long reclaimed, struct reclaim_stat *stat, int priority, int lru);
void rust_mglru_vmwarn(unsigned int site, bool condition);
bool rust_mglru_warn(unsigned int site, bool condition);
void rust_mglru_folio_warn(unsigned int site, bool condition, struct folio *folio);
const struct mm_walk_ops *rust_mglru_mm_walk_ops(void);
const struct seq_operations *rust_mglru_seq_ops(void);
int rust_mglru_sysfs_create_group(void);
void rust_mglru_report_sysfs_error(void);
void rust_mglru_debugfs_create(bool full);
#endif
#endif
