/* Translated from amdgpu_ucode.h. */
// Dependency intent: amdgpu_socbb.h supplies gpu_info_soc_bounding_box_v1_0.

pub const RS64_FW_UC_START_ADDR_LO: u32 = 0x3000;

#[repr(C)] pub struct common_firmware_header { pub size_bytes:u32, pub header_size_bytes:u32, pub header_version_major:u16, pub header_version_minor:u16, pub ip_version_major:u16, pub ip_version_minor:u16, pub ucode_version:u32, pub ucode_size_bytes:u32, pub ucode_array_offset_bytes:u32, pub crc32:u32 }
#[repr(C)] pub struct mc_firmware_header_v1_0 { pub header:common_firmware_header, pub io_debug_size_bytes:u32, pub io_debug_array_offset_bytes:u32 }
#[repr(C)] pub struct smc_firmware_header_v1_0 { pub header:common_firmware_header, pub ucode_start_addr:u32 }
#[repr(C)] pub struct smc_firmware_header_v2_0 { pub v1_0:smc_firmware_header_v1_0, pub ppt_offset_bytes:u32, pub ppt_size_bytes:u32 }
#[repr(C)] pub struct smc_soft_pptable_entry { pub id:u32, pub ppt_offset_bytes:u32, pub ppt_size_bytes:u32 }
#[repr(C)] pub struct smc_firmware_header_v2_1 { pub v1_0:smc_firmware_header_v1_0, pub pptable_count:u32, pub pptable_entry_offset:u32 }
#[repr(C)] pub struct psp_fw_legacy_bin_desc { pub fw_version:u32, pub offset_bytes:u32, pub size_bytes:u32 }
#[repr(C)] pub struct psp_firmware_header_v1_0 { pub header:common_firmware_header, pub sos:psp_fw_legacy_bin_desc }
#[repr(C)] pub struct psp_firmware_header_v1_1 { pub v1_0:psp_firmware_header_v1_0, pub toc:psp_fw_legacy_bin_desc, pub kdb:psp_fw_legacy_bin_desc }
#[repr(C)] pub struct psp_firmware_header_v1_2 { pub v1_0:psp_firmware_header_v1_0, pub res:psp_fw_legacy_bin_desc, pub kdb:psp_fw_legacy_bin_desc }
#[repr(C)] pub struct psp_firmware_header_v1_3 { pub v1_1:psp_firmware_header_v1_1, pub spl:psp_fw_legacy_bin_desc, pub rl:psp_fw_legacy_bin_desc, pub sys_drv_aux:psp_fw_legacy_bin_desc, pub sos_aux:psp_fw_legacy_bin_desc }
#[repr(C)] pub struct psp_fw_bin_desc { pub fw_type:u32, pub fw_version:u32, pub offset_bytes:u32, pub size_bytes:u32 }
#[repr(u32)] pub enum psp_fw_type { PSP_FW_TYPE_UNKOWN, PSP_FW_TYPE_PSP_SOS, PSP_FW_TYPE_PSP_SYS_DRV, PSP_FW_TYPE_PSP_KDB, PSP_FW_TYPE_PSP_TOC, PSP_FW_TYPE_PSP_SPL, PSP_FW_TYPE_PSP_RL, PSP_FW_TYPE_PSP_SOC_DRV, PSP_FW_TYPE_PSP_INTF_DRV, PSP_FW_TYPE_PSP_DBG_DRV, PSP_FW_TYPE_PSP_RAS_DRV, PSP_FW_TYPE_PSP_IPKEYMGR_DRV, PSP_FW_TYPE_PSP_SPDM_DRV, PSP_FW_TYPE_MAX_INDEX }
#[repr(C)] pub struct psp_firmware_header_v2_0 { pub header:common_firmware_header, pub psp_fw_bin_count:u32, pub psp_fw_bin:[psp_fw_bin_desc;0] }
#[repr(C)] pub struct psp_firmware_header_v2_1 { pub header:common_firmware_header, pub psp_fw_bin_count:u32, pub psp_aux_fw_bin_index:u32, pub psp_fw_bin:[psp_fw_bin_desc;0] }
#[repr(C)] pub struct ta_firmware_header_v1_0 { pub header:common_firmware_header, pub xgmi:psp_fw_legacy_bin_desc, pub ras:psp_fw_legacy_bin_desc, pub hdcp:psp_fw_legacy_bin_desc, pub dtm:psp_fw_legacy_bin_desc, pub securedisplay:psp_fw_legacy_bin_desc }
#[repr(u32)] pub enum ta_fw_type { TA_FW_TYPE_UNKOWN, TA_FW_TYPE_PSP_ASD, TA_FW_TYPE_PSP_XGMI, TA_FW_TYPE_PSP_RAS, TA_FW_TYPE_PSP_HDCP, TA_FW_TYPE_PSP_DTM, TA_FW_TYPE_PSP_RAP, TA_FW_TYPE_PSP_SECUREDISPLAY, TA_FW_TYPE_PSP_XGMI_AUX, TA_FW_TYPE_MAX_INDEX }
#[repr(C)] pub struct ta_firmware_header_v2_0 { pub header:common_firmware_header, pub ta_fw_bin_count:u32, pub ta_fw_bin:[psp_fw_bin_desc;0] }
#[repr(C)] pub struct gfx_firmware_header_v1_0 { pub header:common_firmware_header, pub ucode_feature_version:u32, pub jt_offset:u32, pub jt_size:u32 }
#[repr(C)] pub struct gfx_firmware_header_v2_0 { pub header:common_firmware_header, pub ucode_feature_version:u32, pub ucode_size_bytes:u32, pub ucode_offset_bytes:u32, pub data_size_bytes:u32, pub data_offset_bytes:u32, pub ucode_start_addr_lo:u32, pub ucode_start_addr_hi:u32 }
#[repr(C)] pub struct mes_firmware_header_v1_0 { pub header:common_firmware_header, pub mes_ucode_version:u32, pub mes_ucode_size_bytes:u32, pub mes_ucode_offset_bytes:u32, pub mes_ucode_data_version:u32, pub mes_ucode_data_size_bytes:u32, pub mes_ucode_data_offset_bytes:u32, pub mes_uc_start_addr_lo:u32, pub mes_uc_start_addr_hi:u32, pub mes_data_start_addr_lo:u32, pub mes_data_start_addr_hi:u32 }
#[repr(C)] pub struct rlc_firmware_header_v1_0 { pub header:common_firmware_header, pub ucode_feature_version:u32, pub save_and_restore_offset:u32, pub clear_state_descriptor_offset:u32, pub avail_scratch_ram_locations:u32, pub master_pkt_description_offset:u32 }
#[repr(C)] pub struct rlc_firmware_header_v2_0 { pub header:common_firmware_header, pub ucode_feature_version:u32, pub jt_offset:u32, pub jt_size:u32, pub save_and_restore_offset:u32, pub clear_state_descriptor_offset:u32, pub avail_scratch_ram_locations:u32, pub reg_restore_list_size:u32, pub reg_list_format_start:u32, pub reg_list_format_separate_start:u32, pub starting_offsets_start:u32, pub reg_list_format_size_bytes:u32, pub reg_list_format_array_offset_bytes:u32, pub reg_list_size_bytes:u32, pub reg_list_array_offset_bytes:u32, pub reg_list_format_separate_size_bytes:u32, pub reg_list_format_separate_array_offset_bytes:u32, pub reg_list_separate_size_bytes:u32, pub reg_list_separate_array_offset_bytes:u32 }
#[repr(C)] pub struct rlc_firmware_header_v2_1 { pub v2_0:rlc_firmware_header_v2_0, pub reg_list_format_direct_reg_list_length:u32, pub save_restore_list_cntl_ucode_ver:u32, pub save_restore_list_cntl_feature_ver:u32, pub save_restore_list_cntl_size_bytes:u32, pub save_restore_list_cntl_offset_bytes:u32, pub save_restore_list_gpm_ucode_ver:u32, pub save_restore_list_gpm_feature_ver:u32, pub save_restore_list_gpm_size_bytes:u32, pub save_restore_list_gpm_offset_bytes:u32, pub save_restore_list_srm_ucode_ver:u32, pub save_restore_list_srm_feature_ver:u32, pub save_restore_list_srm_size_bytes:u32, pub save_restore_list_srm_offset_bytes:u32 }
#[repr(C)] pub struct rlc_firmware_header_v2_2 { pub v2_1:rlc_firmware_header_v2_1, pub rlc_iram_ucode_size_bytes:u32, pub rlc_iram_ucode_offset_bytes:u32, pub rlc_dram_ucode_size_bytes:u32, pub rlc_dram_ucode_offset_bytes:u32 }
#[repr(C)] pub struct rlc_firmware_header_v2_3 { pub v2_2:rlc_firmware_header_v2_2, pub rlcp_ucode_version:u32, pub rlcp_ucode_feature_version:u32, pub rlcp_ucode_size_bytes:u32, pub rlcp_ucode_offset_bytes:u32, pub rlcv_ucode_version:u32, pub rlcv_ucode_feature_version:u32, pub rlcv_ucode_size_bytes:u32, pub rlcv_ucode_offset_bytes:u32 }
#[repr(C)] pub struct rlc_firmware_header_v2_4 { pub v2_3:rlc_firmware_header_v2_3, pub global_tap_delays_ucode_size_bytes:u32, pub global_tap_delays_ucode_offset_bytes:u32, pub se0_tap_delays_ucode_size_bytes:u32, pub se0_tap_delays_ucode_offset_bytes:u32, pub se1_tap_delays_ucode_size_bytes:u32, pub se1_tap_delays_ucode_offset_bytes:u32, pub se2_tap_delays_ucode_size_bytes:u32, pub se2_tap_delays_ucode_offset_bytes:u32, pub se3_tap_delays_ucode_size_bytes:u32, pub se3_tap_delays_ucode_offset_bytes:u32 }
#[repr(C)] pub struct rlc_firmware_header_v2_5 { pub v2_2:rlc_firmware_header_v2_2, pub rlc_1_iram_ucode_size_bytes:u32, pub rlc_1_iram_ucode_offset_bytes:u32, pub rlc_1_dram_ucode_size_bytes:u32, pub rlc_1_dram_ucode_offset_bytes:u32 }
#[repr(C)] pub struct sdma_firmware_header_v1_0 { pub header:common_firmware_header, pub ucode_feature_version:u32, pub ucode_change_version:u32, pub jt_offset:u32, pub jt_size:u32 }
#[repr(C)] pub struct sdma_firmware_header_v1_1 { pub v1_0:sdma_firmware_header_v1_0, pub digest_size:u32 }
#[repr(C)] pub struct sdma_firmware_header_v2_0 { pub header:common_firmware_header, pub ucode_feature_version:u32, pub ctx_ucode_size_bytes:u32, pub ctx_jt_offset:u32, pub ctx_jt_size:u32, pub ctl_ucode_offset:u32, pub ctl_ucode_size_bytes:u32, pub ctl_jt_offset:u32, pub ctl_jt_size:u32 }
#[repr(C)] pub struct vpe_firmware_header_v1_0 { pub header:common_firmware_header, pub ucode_feature_version:u32, pub ctx_ucode_size_bytes:u32, pub ctx_jt_offset:u32, pub ctx_jt_size:u32, pub ctl_ucode_offset:u32, pub ctl_ucode_size_bytes:u32, pub ctl_jt_offset:u32, pub ctl_jt_size:u32 }
#[repr(C)] pub struct umsch_mm_firmware_header_v1_0 { pub header:common_firmware_header, pub umsch_mm_ucode_version:u32, pub umsch_mm_ucode_size_bytes:u32, pub umsch_mm_ucode_offset_bytes:u32, pub umsch_mm_ucode_data_version:u32, pub umsch_mm_ucode_data_size_bytes:u32, pub umsch_mm_ucode_data_offset_bytes:u32, pub umsch_mm_irq_start_addr_lo:u32, pub umsch_mm_irq_start_addr_hi:u32, pub umsch_mm_uc_start_addr_lo:u32, pub umsch_mm_uc_start_addr_hi:u32, pub umsch_mm_data_start_addr_lo:u32, pub umsch_mm_data_start_addr_hi:u32 }
#[repr(C)] pub struct sdma_firmware_header_v3_0 { pub header:common_firmware_header, pub ucode_feature_version:u32, pub ucode_offset_bytes:u32, pub ucode_size_bytes:u32 }
#[repr(C)] pub struct gpu_info_firmware_v1_0 { pub gc_num_se:u32, pub gc_num_cu_per_sh:u32, pub gc_num_sh_per_se:u32, pub gc_num_rb_per_se:u32, pub gc_num_tccs:u32, pub gc_num_gprs:u32, pub gc_num_max_gs_thds:u32, pub gc_gs_table_depth:u32, pub gc_gsprim_buff_depth:u32, pub gc_parameter_cache_depth:u32, pub gc_double_offchip_lds_buffer:u32, pub gc_wave_size:u32, pub gc_max_waves_per_simd:u32, pub gc_max_scratch_slots_per_cu:u32, pub gc_lds_size:u32 }
#[repr(C)] pub struct gpu_info_firmware_v1_1 { pub v1_0:gpu_info_firmware_v1_0, pub num_sc_per_sh:u32, pub num_packer_per_sc:u32 }
#[repr(C)] pub struct gpu_info_firmware_v1_2 { pub v1_1:gpu_info_firmware_v1_1, pub soc_bounding_box:gpu_info_soc_bounding_box_v1_0 }
#[repr(C)] pub struct gpu_info_firmware_header_v1_0 { pub header:common_firmware_header, pub version_major:u16, pub version_minor:u16 }
#[repr(C)] pub struct dmcu_firmware_header_v1_0 { pub header:common_firmware_header, pub intv_offset_bytes:u32, pub intv_size_bytes:u32 }
#[repr(C)] pub struct dmcub_firmware_header_v1_0 { pub header:common_firmware_header, pub inst_const_bytes:u32, pub bss_data_bytes:u32 }
#[repr(C)] pub struct imu_firmware_header_v1_0 { pub header:common_firmware_header, pub imu_iram_ucode_size_bytes:u32, pub imu_iram_ucode_offset_bytes:u32, pub imu_dram_ucode_size_bytes:u32, pub imu_dram_ucode_offset_bytes:u32 }

#[repr(C)] pub union amdgpu_firmware_header { pub common:common_firmware_header, pub mc:mc_firmware_header_v1_0, pub smc:smc_firmware_header_v1_0, pub smc_v2_0:smc_firmware_header_v2_0, pub psp:psp_firmware_header_v1_0, pub psp_v1_1:psp_firmware_header_v1_1, pub psp_v1_3:psp_firmware_header_v1_3, pub psp_v2_0:psp_firmware_header_v2_0, pub psp_v2_1:psp_firmware_header_v2_1, pub ta:ta_firmware_header_v1_0, pub ta_v2_0:ta_firmware_header_v2_0, pub gfx:gfx_firmware_header_v1_0, pub gfx_v2_0:gfx_firmware_header_v2_0, pub rlc:rlc_firmware_header_v1_0, pub rlc_v2_0:rlc_firmware_header_v2_0, pub rlc_v2_1:rlc_firmware_header_v2_1, pub rlc_v2_2:rlc_firmware_header_v2_2, pub rlc_v2_3:rlc_firmware_header_v2_3, pub rlc_v2_4:rlc_firmware_header_v2_4, pub rlc_v2_5:rlc_firmware_header_v2_5, pub sdma:sdma_firmware_header_v1_0, pub sdma_v1_1:sdma_firmware_header_v1_1, pub sdma_v2_0:sdma_firmware_header_v2_0, pub sdma_v3_0:sdma_firmware_header_v3_0, pub gpu_info:gpu_info_firmware_header_v1_0, pub dmcu:dmcu_firmware_header_v1_0, pub dmcub:dmcub_firmware_header_v1_0, pub imu:imu_firmware_header_v1_0, pub raw:[u8;0x100] }

#[repr(u32)] pub enum AMDGPU_UCODE_ID { AMDGPU_UCODE_ID_CAP=0, AMDGPU_UCODE_ID_SDMA0, AMDGPU_UCODE_ID_SDMA1, AMDGPU_UCODE_ID_SDMA2, AMDGPU_UCODE_ID_SDMA3, AMDGPU_UCODE_ID_SDMA4, AMDGPU_UCODE_ID_SDMA5, AMDGPU_UCODE_ID_SDMA6, AMDGPU_UCODE_ID_SDMA7, AMDGPU_UCODE_ID_SDMA_UCODE_TH0, AMDGPU_UCODE_ID_SDMA_UCODE_TH1, AMDGPU_UCODE_ID_SDMA_RS64, AMDGPU_UCODE_ID_CP_CE, AMDGPU_UCODE_ID_CP_PFP, AMDGPU_UCODE_ID_CP_ME, AMDGPU_UCODE_ID_CP_RS64_PFP, AMDGPU_UCODE_ID_CP_RS64_ME, AMDGPU_UCODE_ID_CP_RS64_MEC, AMDGPU_UCODE_ID_CP_RS64_PFP_P0_STACK, AMDGPU_UCODE_ID_CP_RS64_PFP_P1_STACK, AMDGPU_UCODE_ID_CP_RS64_ME_P0_STACK, AMDGPU_UCODE_ID_CP_RS64_ME_P1_STACK, AMDGPU_UCODE_ID_CP_RS64_MEC_P0_STACK, AMDGPU_UCODE_ID_CP_RS64_MEC_P1_STACK, AMDGPU_UCODE_ID_CP_RS64_MEC_P2_STACK, AMDGPU_UCODE_ID_CP_RS64_MEC_P3_STACK, AMDGPU_UCODE_ID_CP_MEC1, AMDGPU_UCODE_ID_CP_MEC1_JT, AMDGPU_UCODE_ID_CP_MEC2, AMDGPU_UCODE_ID_CP_MEC2_JT, AMDGPU_UCODE_ID_CP_MES, AMDGPU_UCODE_ID_CP_MES_DATA, AMDGPU_UCODE_ID_CP_MES1, AMDGPU_UCODE_ID_CP_MES1_DATA, AMDGPU_UCODE_ID_IMU_I, AMDGPU_UCODE_ID_IMU_D, AMDGPU_UCODE_ID_GLOBAL_TAP_DELAYS, AMDGPU_UCODE_ID_SE0_TAP_DELAYS, AMDGPU_UCODE_ID_SE1_TAP_DELAYS, AMDGPU_UCODE_ID_SE2_TAP_DELAYS, AMDGPU_UCODE_ID_SE3_TAP_DELAYS, AMDGPU_UCODE_ID_RLC_RESTORE_LIST_CNTL, AMDGPU_UCODE_ID_RLC_RESTORE_LIST_GPM_MEM, AMDGPU_UCODE_ID_RLC_RESTORE_LIST_SRM_MEM, AMDGPU_UCODE_ID_RLC_IRAM, AMDGPU_UCODE_ID_RLC_DRAM, AMDGPU_UCODE_ID_RLC_IRAM_1, AMDGPU_UCODE_ID_RLC_DRAM_1, AMDGPU_UCODE_ID_RLC_P, AMDGPU_UCODE_ID_RLC_V, AMDGPU_UCODE_ID_RLC_G, AMDGPU_UCODE_ID_STORAGE, AMDGPU_UCODE_ID_SMC, AMDGPU_UCODE_ID_PPTABLE, AMDGPU_UCODE_ID_UVD, AMDGPU_UCODE_ID_UVD1, AMDGPU_UCODE_ID_VCE, AMDGPU_UCODE_ID_VCN, AMDGPU_UCODE_ID_VCN1, AMDGPU_UCODE_ID_DMCU_ERAM, AMDGPU_UCODE_ID_DMCU_INTV, AMDGPU_UCODE_ID_VCN0_RAM, AMDGPU_UCODE_ID_VCN1_RAM, AMDGPU_UCODE_ID_DMCUB, AMDGPU_UCODE_ID_VPE_CTX, AMDGPU_UCODE_ID_VPE_CTL, AMDGPU_UCODE_ID_VPE, AMDGPU_UCODE_ID_UMSCH_MM_UCODE, AMDGPU_UCODE_ID_UMSCH_MM_DATA, AMDGPU_UCODE_ID_UMSCH_MM_CMD_BUFFER, AMDGPU_UCODE_ID_P2S_TABLE, AMDGPU_UCODE_ID_JPEG_RAM, AMDGPU_UCODE_ID_ISP, AMDGPU_UCODE_ID_MAXIMUM }
#[repr(u32)] pub enum AMDGPU_UCODE_STATUS { AMDGPU_UCODE_STATUS_INVALID, AMDGPU_UCODE_STATUS_NOT_LOADED, AMDGPU_UCODE_STATUS_LOADED }
#[repr(u32)] pub enum amdgpu_firmware_load_type { AMDGPU_FW_LOAD_DIRECT=0, AMDGPU_FW_LOAD_PSP, AMDGPU_FW_LOAD_SMU, AMDGPU_FW_LOAD_RLC_BACKDOOR_AUTO }
#[repr(u32)] pub enum amdgpu_ucode_required { AMDGPU_UCODE_OPTIONAL, AMDGPU_UCODE_REQUIRED }
pub const AMDGPU_SDMA0_UCODE_LOADED:u32=0x00000001; pub const AMDGPU_SDMA1_UCODE_LOADED:u32=0x00000002; pub const AMDGPU_CPCE_UCODE_LOADED:u32=0x00000004; pub const AMDGPU_CPPFP_UCODE_LOADED:u32=0x00000008; pub const AMDGPU_CPME_UCODE_LOADED:u32=0x00000010; pub const AMDGPU_CPMEC1_UCODE_LOADED:u32=0x00000020; pub const AMDGPU_CPMEC2_UCODE_LOADED:u32=0x00000040; pub const AMDGPU_CPRLC_UCODE_LOADED:u32=0x00000100;

// External types and functions are supplied by other translation units.
extern "C" {
    pub fn amdgpu_ucode_print_mc_hdr(hdr:*const common_firmware_header); pub fn amdgpu_ucode_print_smc_hdr(hdr:*const common_firmware_header); pub fn amdgpu_ucode_print_imu_hdr(hdr:*const common_firmware_header); pub fn amdgpu_ucode_print_gfx_hdr(hdr:*const common_firmware_header); pub fn amdgpu_ucode_print_rlc_hdr(hdr:*const common_firmware_header); pub fn amdgpu_ucode_print_sdma_hdr(hdr:*const common_firmware_header); pub fn amdgpu_ucode_print_psp_hdr(hdr:*const common_firmware_header); pub fn amdgpu_ucode_print_gpu_info_hdr(hdr:*const common_firmware_header);
}

pub const UCODE_MAX_PSP_PACKAGING: usize = (256usize.saturating_sub(core::mem::size_of::<common_firmware_header>()).saturating_sub(4) / core::mem::size_of::<psp_fw_bin_desc>()) * 2;
#[repr(C)] pub struct firmware { _private: [u8;0] }
#[repr(C)] pub struct amdgpu_device { _private: [u8;0] }
#[repr(C)] pub struct amdgpu_bo { _private: [u8;0] }
#[repr(C)] pub struct amdgpu_psp_funcs { _private: [u8;0] }
#[repr(C)] pub struct mutex { _private: [u8;0] }
#[repr(C)] pub struct kicker_device { pub device:u16, pub revision:u8 }
#[repr(C)] pub struct amdgpu_firmware_info { pub ucode_id:AMDGPU_UCODE_ID, pub fw:*const firmware, pub mc_addr:u64, pub kaddr:*mut core::ffi::c_void, pub ucode_size:u32, pub tmr_mc_addr_lo:u32, pub tmr_mc_addr_hi:u32 }
#[repr(C)] pub struct amdgpu_firmware { pub ucode:[amdgpu_firmware_info; AMDGPU_UCODE_ID::AMDGPU_UCODE_ID_MAXIMUM as usize], pub load_type:amdgpu_firmware_load_type, pub fw_buf:*mut amdgpu_bo, pub fw_size:u32, pub max_ucodes:u32, pub funcs:*const amdgpu_psp_funcs, pub rbuf:*mut amdgpu_bo, pub mutex:mutex, pub gpu_info_fw:*const firmware, pub fw_buf_ptr:*mut core::ffi::c_void, pub fw_buf_mc:u64, pub pldm_version:u32 }
extern "C" {
    pub fn amdgpu_ucode_request(adev:*mut amdgpu_device, fw:*mut *const firmware, required:amdgpu_ucode_required, fmt:*const core::ffi::c_char, ...)->i32;
    pub fn amdgpu_ucode_release(fw:*mut *const firmware);
    pub fn amdgpu_ucode_hdr_version(hdr:*mut amdgpu_firmware_header, hdr_major:u16, hdr_minor:u16)->bool;
    pub fn amdgpu_ucode_init_bo(adev:*mut amdgpu_device)->i32; pub fn amdgpu_ucode_create_bo(adev:*mut amdgpu_device)->i32; pub fn amdgpu_ucode_sysfs_init(adev:*mut amdgpu_device)->i32; pub fn amdgpu_ucode_free_bo(adev:*mut amdgpu_device); pub fn amdgpu_ucode_sysfs_fini(adev:*mut amdgpu_device);
    pub fn amdgpu_ucode_get_load_type(adev:*mut amdgpu_device, load_type:i32)->amdgpu_firmware_load_type;
    pub fn amdgpu_ucode_name(ucode_id:AMDGPU_UCODE_ID)->*const core::ffi::c_char;
    pub fn amdgpu_ucode_ip_version_decode(adev:*mut amdgpu_device, block_type:i32, ucode_prefix:*mut core::ffi::c_char, len:i32);
    pub fn amdgpu_is_kicker_fw(adev:*mut amdgpu_device)->bool;
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
