/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright (c) 2024, Qualcomm Innovation Center, Inc. All rights reserved.
 */

/* DISP_CC_0/1 clocks */
pub const MDSS_DISP_CC_MDSS_AHB1_CLK: u32 = 0;
pub const MDSS_DISP_CC_MDSS_AHB_CLK: u32 = 1;
pub const MDSS_DISP_CC_MDSS_AHB_CLK_SRC: u32 = 2;
pub const MDSS_DISP_CC_MDSS_BYTE0_CLK: u32 = 3;
pub const MDSS_DISP_CC_MDSS_BYTE0_CLK_SRC: u32 = 4;
pub const MDSS_DISP_CC_MDSS_BYTE0_DIV_CLK_SRC: u32 = 5;
pub const MDSS_DISP_CC_MDSS_BYTE0_INTF_CLK: u32 = 6;
pub const MDSS_DISP_CC_MDSS_BYTE1_CLK: u32 = 7;
pub const MDSS_DISP_CC_MDSS_BYTE1_CLK_SRC: u32 = 8;
pub const MDSS_DISP_CC_MDSS_BYTE1_DIV_CLK_SRC: u32 = 9;
pub const MDSS_DISP_CC_MDSS_BYTE1_INTF_CLK: u32 = 10;
pub const MDSS_DISP_CC_MDSS_DPTX0_AUX_CLK: u32 = 11;
pub const MDSS_DISP_CC_MDSS_DPTX0_AUX_CLK_SRC: u32 = 12;
pub const MDSS_DISP_CC_MDSS_DPTX0_CRYPTO_CLK: u32 = 13;
pub const MDSS_DISP_CC_MDSS_DPTX0_CRYPTO_CLK_SRC: u32 = 14;
pub const MDSS_DISP_CC_MDSS_DPTX0_LINK_CLK: u32 = 15;
pub const MDSS_DISP_CC_MDSS_DPTX0_LINK_CLK_SRC: u32 = 16;
pub const MDSS_DISP_CC_MDSS_DPTX0_LINK_DIV_CLK_SRC: u32 = 17;
pub const MDSS_DISP_CC_MDSS_DPTX0_LINK_INTF_CLK: u32 = 18;
pub const MDSS_DISP_CC_MDSS_DPTX0_PIXEL0_CLK: u32 = 19;
pub const MDSS_DISP_CC_MDSS_DPTX0_PIXEL0_CLK_SRC: u32 = 20;
pub const MDSS_DISP_CC_MDSS_DPTX0_PIXEL1_CLK: u32 = 21;
pub const MDSS_DISP_CC_MDSS_DPTX0_PIXEL1_CLK_SRC: u32 = 22;
pub const MDSS_DISP_CC_MDSS_DPTX0_PIXEL2_CLK: u32 = 23;
pub const MDSS_DISP_CC_MDSS_DPTX0_PIXEL2_CLK_SRC: u32 = 24;
pub const MDSS_DISP_CC_MDSS_DPTX0_PIXEL3_CLK: u32 = 25;
pub const MDSS_DISP_CC_MDSS_DPTX0_PIXEL3_CLK_SRC: u32 = 26;
pub const MDSS_DISP_CC_MDSS_DPTX0_USB_ROUTER_LINK_INTF_CLK: u32 = 27;
pub const MDSS_DISP_CC_MDSS_DPTX1_AUX_CLK: u32 = 28;
pub const MDSS_DISP_CC_MDSS_DPTX1_AUX_CLK_SRC: u32 = 29;
pub const MDSS_DISP_CC_MDSS_DPTX1_CRYPTO_CLK: u32 = 30;
pub const MDSS_DISP_CC_MDSS_DPTX1_CRYPTO_CLK_SRC: u32 = 31;
pub const MDSS_DISP_CC_MDSS_DPTX1_LINK_CLK: u32 = 32;
pub const MDSS_DISP_CC_MDSS_DPTX1_LINK_CLK_SRC: u32 = 33;
pub const MDSS_DISP_CC_MDSS_DPTX1_LINK_DIV_CLK_SRC: u32 = 34;
pub const MDSS_DISP_CC_MDSS_DPTX1_LINK_INTF_CLK: u32 = 35;
pub const MDSS_DISP_CC_MDSS_DPTX1_PIXEL0_CLK: u32 = 36;
pub const MDSS_DISP_CC_MDSS_DPTX1_PIXEL0_CLK_SRC: u32 = 37;
pub const MDSS_DISP_CC_MDSS_DPTX1_PIXEL1_CLK: u32 = 38;
pub const MDSS_DISP_CC_MDSS_DPTX1_PIXEL1_CLK_SRC: u32 = 39;
pub const MDSS_DISP_CC_MDSS_DPTX1_USB_ROUTER_LINK_INTF_CLK: u32 = 40;
pub const MDSS_DISP_CC_MDSS_ESC0_CLK: u32 = 41;
pub const MDSS_DISP_CC_MDSS_ESC0_CLK_SRC: u32 = 42;
pub const MDSS_DISP_CC_MDSS_ESC1_CLK: u32 = 43;
pub const MDSS_DISP_CC_MDSS_ESC1_CLK_SRC: u32 = 44;
pub const MDSS_DISP_CC_MDSS_MDP1_CLK: u32 = 45;
pub const MDSS_DISP_CC_MDSS_MDP_CLK: u32 = 46;
pub const MDSS_DISP_CC_MDSS_MDP_CLK_SRC: u32 = 47;
pub const MDSS_DISP_CC_MDSS_MDP_LUT1_CLK: u32 = 48;
pub const MDSS_DISP_CC_MDSS_MDP_LUT_CLK: u32 = 49;
pub const MDSS_DISP_CC_MDSS_NON_GDSC_AHB_CLK: u32 = 50;
pub const MDSS_DISP_CC_MDSS_PCLK0_CLK: u32 = 51;
pub const MDSS_DISP_CC_MDSS_PCLK0_CLK_SRC: u32 = 52;
pub const MDSS_DISP_CC_MDSS_PCLK1_CLK: u32 = 53;
pub const MDSS_DISP_CC_MDSS_PCLK1_CLK_SRC: u32 = 54;
pub const MDSS_DISP_CC_MDSS_PLL_LOCK_MONITOR_CLK: u32 = 55;
pub const MDSS_DISP_CC_MDSS_RSCC_AHB_CLK: u32 = 56;
pub const MDSS_DISP_CC_MDSS_RSCC_VSYNC_CLK: u32 = 57;
pub const MDSS_DISP_CC_MDSS_VSYNC1_CLK: u32 = 58;
pub const MDSS_DISP_CC_MDSS_VSYNC_CLK: u32 = 59;
pub const MDSS_DISP_CC_MDSS_VSYNC_CLK_SRC: u32 = 60;
pub const MDSS_DISP_CC_PLL0: u32 = 61;
pub const MDSS_DISP_CC_PLL1: u32 = 62;
pub const MDSS_DISP_CC_SLEEP_CLK: u32 = 63;
pub const MDSS_DISP_CC_SLEEP_CLK_SRC: u32 = 64;
pub const MDSS_DISP_CC_SM_OBS_CLK: u32 = 65;
pub const MDSS_DISP_CC_XO_CLK: u32 = 66;
pub const MDSS_DISP_CC_XO_CLK_SRC: u32 = 67;

/* DISP_CC_0/1 power domains */
pub const MDSS_DISP_CC_MDSS_CORE_GDSC: u32 = 0;
pub const MDSS_DISP_CC_MDSS_CORE_INT2_GDSC: u32 = 1;

/* DISP_CC_0/1 resets */
pub const MDSS_DISP_CC_MDSS_CORE_BCR: u32 = 0;
pub const MDSS_DISP_CC_MDSS_RSCC_BCR: u32 = 1;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
