/* SPDX-License-Identifier: GPL-2.0 */

/*
 * C implementation of Buchi automaton, automatically generated by
 * tools/verification/rvgen from the linear temporal logic specification.
 * For further information, see kernel documentation:
 *   Documentation/trace/rv/linear_temporal_logic.rst
 */

// Dependency intent from: #include <linux/rv.h>

// #define MONITOR_NAME pagefault
pub const MONITOR_NAME: &str = "pagefault";

#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum ltl_atom {
    LTL_PAGEFAULT,
    LTL_RT,
    LTL_NUM_ATOM,
}

// static_assert(LTL_NUM_ATOM <= RV_MAX_LTL_ATOM);

#[allow(non_snake_case)]
unsafe fn ltl_atom_str(atom: ltl_atom) -> *const core::ffi::c_char {
    static NAMES: [&[u8]; 2] = [b"pa\0", b"rt\0"];
    NAMES[atom as usize].as_ptr() as *const core::ffi::c_char
}

#[repr(C)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum ltl_buchi_state {
    S0,
    RV_NUM_BA_STATES,
}

// static_assert(RV_NUM_BA_STATES <= RV_MAX_BA_STATES);

unsafe extern "C" {
    fn test_bit(nr: usize, addr: *const usize) -> bool;
    fn __set_bit(nr: usize, addr: *mut usize);
}

#[allow(non_snake_case)]
unsafe fn ltl_start(task: *mut task_struct, mon: *mut ltl_monitor) {
    let pagefault: bool = test_bit(ltl_atom::LTL_PAGEFAULT as usize, (*mon).atoms as *const _);
    let val3: bool = !pagefault;
    let rt: bool = test_bit(ltl_atom::LTL_RT as usize, (*mon).atoms as *const _);
    let val1: bool = !rt;
    let val4: bool = val1 || val3;

    if val4 {
        __set_bit(ltl_buchi_state::S0 as usize, (*mon).states as *mut _);
    }
}

#[allow(non_snake_case)]
unsafe fn ltl_possible_next_states(
    mon: *mut ltl_monitor,
    state: u32,
    next: *mut usize,
) {
    let pagefault: bool = test_bit(ltl_atom::LTL_PAGEFAULT as usize, (*mon).atoms as *const _);
    let val3: bool = !pagefault;
    let rt: bool = test_bit(ltl_atom::LTL_RT as usize, (*mon).atoms as *const _);
    let val1: bool = !rt;
    let val4: bool = val1 || val3;

    match state {
        x if x == ltl_buchi_state::S0 as u32 => {
            if val4 {
                __set_bit(ltl_buchi_state::S0 as usize, next);
            }
        }
        _ => {}
    }
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
