# SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
# SOURCE-SHA256: 4b909d6469088ee055736d85271ac164e0bb73a1a1ff0c1e403d023278a61877
# REVIEW-CONTEXT: 7290f2d38ef10c1013f60fd60ce3eca79a7031267b1a58d41fd4ee00298f1272
# BUILD-REVIEWER: lupos-build-bash-1
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2004, 2007-2010, 2011-2012 Synopsys, Inc. (www.synopsys.com)
#

# The translated ARC kernel units retain their normal Kbuild object names and
# therefore their archive/link order.  Pin their source prerequisites to the
# Rust companions; scripts/Makefile.build supplies the rustc recipe for the
# resulting %.o targets.
arc_kernel_rust_objects := arcksyms setup irq reset ptrace process devtree \
	signal traps sys troubleshoot stacktrace disasm
arc_kernel_rust_objects += intc-compact intc-arcv2 module smp mcip unwind \
	kprobes unaligned kgdb arc_hostlink perf_event jump_label fpu

$(addprefix $(obj)/,$(addsuffix .o,$(arc_kernel_rust_objects))): \
	$(obj)/%.o: $(obj)/%.rs

obj-y	:= head.o arcksyms.o setup.o irq.o reset.o ptrace.o process.o devtree.o
obj-y	+= signal.o traps.o sys.o troubleshoot.o stacktrace.o disasm.o
obj-y	+= ctx_sw_asm.o

obj-$(CONFIG_ISA_ARCOMPACT)		+= entry-compact.o intc-compact.o
obj-$(CONFIG_ISA_ARCV2)		+= entry-arcv2.o intc-arcv2.o

obj-$(CONFIG_MODULES)			+= arcksyms.o module.o
obj-$(CONFIG_SMP) 			+= smp.o
obj-$(CONFIG_ARC_MCIP)			+= mcip.o
obj-$(CONFIG_ARC_DW2_UNWIND)		+= unwind.o
obj-$(CONFIG_KPROBES)      		+= kprobes.o
obj-$(CONFIG_ARC_EMUL_UNALIGNED) 	+= unaligned.o
obj-$(CONFIG_KGDB)			+= kgdb.o
obj-$(CONFIG_ARC_METAWARE_HLINK)	+= arc_hostlink.o
obj-$(CONFIG_PERF_EVENTS)		+= perf_event.o
obj-$(CONFIG_JUMP_LABEL)		+= jump_label.o

obj-$(CONFIG_ARC_FPU_SAVE_RESTORE)	+= fpu.o
ifdef CONFIG_ISA_ARCOMPACT
CFLAGS_fpu.o   += -mdpfp
endif

always-$(KBUILD_BUILTIN) := vmlinux.lds
