/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by xdrgen. Manual edits will be lost. */
/* XDR specification file: ../../Documentation/sunrpc/xdr/nlm3.x */
/* XDR specification modification time: Mon Jun 29 20:42:29 2026 */

// Dependencies supplied by linux/types.h and linux/sunrpc/xdrgen/_defs.h.

pub const LM_MAXSTRLEN: usize = 1024;
pub const LM_MAXNAMELEN: usize = 1025;
pub const MAXNETOBJ_SZ: usize = 1024;

pub type netobj = [u8; 0];

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum nlm_stats_enum {
    LCK_GRANTED = 0,
    LCK_DENIED = 1,
    LCK_DENIED_NOLOCKS = 2,
    LCK_BLOCKED = 3,
    LCK_DENIED_GRACE_PERIOD = 4,
}

pub type nlm_stats = __be32;

#[repr(C)]
pub struct nlm_stat {
    pub stat: nlm_stats,
}

#[repr(C)]
pub struct nlm_res {
    pub cookie: netobj,
    pub stat: nlm_stat,
}

#[repr(C)]
pub struct nlm_holder {
    pub exclusive: bool,
    pub uppid: s32,
    pub oh: netobj,
    pub l_offset: u32,
    pub l_len: u32,
}

#[repr(C)]
pub union nlm_testrply_u {
    pub holder: nlm_holder,
}

#[repr(C)]
pub struct nlm_testrply {
    pub stat: nlm_stats,
    pub u: nlm_testrply_u,
}

#[repr(C)]
pub struct nlm_testres {
    pub cookie: netobj,
    pub test_stat: nlm_testrply,
}

#[repr(C)]
pub struct nlm_lock {
    pub caller_name: string,
    pub fh: netobj,
    pub oh: netobj,
    pub uppid: s32,
    pub l_offset: u32,
    pub l_len: u32,
}

#[repr(C)]
pub struct nlm_lockargs {
    pub cookie: netobj,
    pub block: bool,
    pub exclusive: bool,
    pub alock: nlm_lock,
    pub reclaim: bool,
    pub state: s32,
}

#[repr(C)]
pub struct nlm_cancargs {
    pub cookie: netobj,
    pub block: bool,
    pub exclusive: bool,
    pub alock: nlm_lock,
}

#[repr(C)]
pub struct nlm_testargs {
    pub cookie: netobj,
    pub exclusive: bool,
    pub alock: nlm_lock,
}

#[repr(C)]
pub struct nlm_unlockargs {
    pub cookie: netobj,
    pub alock: nlm_lock,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum fsh_mode {
    fsm_DN = 0,
    fsm_DR = 1,
    fsm_DW = 2,
    fsm_DRW = 3,
}

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum fsh_access {
    fsa_NONE = 0,
    fsa_R = 1,
    fsa_W = 2,
    fsa_RW = 3,
}

#[repr(C)]
pub struct nlm_share {
    pub caller_name: string,
    pub fh: netobj,
    pub oh: netobj,
    pub mode: fsh_mode,
    pub access: fsh_access,
}

#[repr(C)]
pub struct nlm_shareargs {
    pub cookie: netobj,
    pub share: nlm_share,
    pub reclaim: bool,
}

#[repr(C)]
pub struct nlm_shareres {
    pub cookie: netobj,
    pub stat: nlm_stats,
    pub sequence: s32,
}

#[repr(C)]
pub struct nlm_notify {
    pub name: string,
    pub state: s32,
}

pub const SM_PRIV_SIZE: usize = 16;

#[repr(C)]
pub struct nlm_notifyargs {
    pub notify: nlm_notify,
    pub private: [u8; SM_PRIV_SIZE],
}

pub const NLM_NULL: i32 = 0;
pub const NLM_TEST: i32 = 1;
pub const NLM_LOCK: i32 = 2;
pub const NLM_CANCEL: i32 = 3;
pub const NLM_UNLOCK: i32 = 4;
pub const NLM_GRANTED: i32 = 5;
pub const NLM_TEST_MSG: i32 = 6;
pub const NLM_LOCK_MSG: i32 = 7;
pub const NLM_CANCEL_MSG: i32 = 8;
pub const NLM_UNLOCK_MSG: i32 = 9;
pub const NLM_GRANTED_MSG: i32 = 10;
pub const NLM_TEST_RES: i32 = 11;
pub const NLM_LOCK_RES: i32 = 12;
pub const NLM_CANCEL_RES: i32 = 13;
pub const NLM_UNLOCK_RES: i32 = 14;
pub const NLM_GRANTED_RES: i32 = 15;
pub const NLM_SM_NOTIFY: i32 = 16;
pub const NLM_SHARE: i32 = 20;
pub const NLM_UNSHARE: i32 = 21;
pub const NLM_NM_LOCK: i32 = 22;
pub const NLM_FREE_ALL: i32 = 23;

pub const NLM_PROG: u32 = 100021;

pub const NLM3_netobj_sz: usize = XDR_unsigned_int + XDR_QUADLEN(MAXNETOBJ_SZ);
pub const NLM3_nlm_stats_sz: usize = XDR_int;
pub const NLM3_nlm_stat_sz: usize = NLM3_nlm_stats_sz;
pub const NLM3_nlm_res_sz: usize = NLM3_netobj_sz + NLM3_nlm_stat_sz;
pub const NLM3_nlm_holder_sz: usize = XDR_bool + XDR_int + NLM3_netobj_sz + XDR_unsigned_int + XDR_unsigned_int;
pub const NLM3_nlm_testrply_sz: usize = NLM3_nlm_stats_sz + NLM3_nlm_holder_sz;
pub const NLM3_nlm_testres_sz: usize = NLM3_netobj_sz + NLM3_nlm_testrply_sz;
pub const NLM3_nlm_lock_sz: usize = XDR_unsigned_int + XDR_QUADLEN(LM_MAXSTRLEN) + NLM3_netobj_sz + NLM3_netobj_sz + XDR_int + XDR_unsigned_int + XDR_unsigned_int;
pub const NLM3_nlm_lockargs_sz: usize = NLM3_netobj_sz + XDR_bool + XDR_bool + NLM3_nlm_lock_sz + XDR_bool + XDR_int;
pub const NLM3_nlm_cancargs_sz: usize = NLM3_netobj_sz + XDR_bool + XDR_bool + NLM3_nlm_lock_sz;
pub const NLM3_nlm_testargs_sz: usize = NLM3_netobj_sz + XDR_bool + NLM3_nlm_lock_sz;
pub const NLM3_nlm_unlockargs_sz: usize = NLM3_netobj_sz + NLM3_nlm_lock_sz;
pub const NLM3_fsh_mode_sz: usize = XDR_int;
pub const NLM3_fsh_access_sz: usize = XDR_int;
pub const NLM3_nlm_share_sz: usize = XDR_unsigned_int + XDR_QUADLEN(LM_MAXSTRLEN) + NLM3_netobj_sz + NLM3_netobj_sz + NLM3_fsh_mode_sz + NLM3_fsh_access_sz;
pub const NLM3_nlm_shareargs_sz: usize = NLM3_netobj_sz + NLM3_nlm_share_sz + XDR_bool;
pub const NLM3_nlm_shareres_sz: usize = NLM3_netobj_sz + NLM3_nlm_stats_sz + XDR_int;
pub const NLM3_nlm_notify_sz: usize = XDR_unsigned_int + XDR_QUADLEN(LM_MAXNAMELEN) + XDR_long;
pub const NLM3_nlm_notifyargs_sz: usize = NLM3_nlm_notify_sz + XDR_QUADLEN(SM_PRIV_SIZE);
pub const NLM3_MAX_ARGS_SZ: usize = NLM3_nlm_lockargs_sz;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
