/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by xdrgen. Manual edits will be lost. */
/* XDR specification file: ../../Documentation/sunrpc/xdr/nlm4.x */
/* XDR specification modification time: Mon Jun 29 20:42:29 2026 */

// Translated from linux/sunrpc/xdrgen/nlm4.h.
// Dependencies formerly supplied by <linux/types.h> and
// <linux/sunrpc/xdrgen/_defs.h> remain external to this translation.

pub const LM_MAXSTRLEN: usize = 1024;
pub const LM_MAXNAMELEN: usize = 1025;
pub const MAXNETOBJ_SZ: usize = 1024;

pub type netobj = opaque;

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum fsh4_mode { fsm_DN = 0, fsm_DR = 1, fsm_DW = 2, fsm_DRW = 3 }

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum fsh4_access { fsa_NONE = 0, fsa_R = 1, fsa_W = 2, fsa_RW = 3 }

pub const SM_MAXSTRLEN: usize = 1024;
pub type uint64 = u64;
pub type int64 = i64;
pub type uint32 = u32;
pub type int32 = i32;

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum nlm4_stats_values {
    NLM4_GRANTED = 0, NLM4_DENIED = 1, NLM4_DENIED_NOLOCKS = 2,
    NLM4_BLOCKED = 3, NLM4_DENIED_GRACE_PERIOD = 4, NLM4_DEADLCK = 5,
    NLM4_ROFS = 6, NLM4_STALE_FH = 7, NLM4_FBIG = 8, NLM4_FAILED = 9,
}

pub type nlm4_stats = __be32;

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_holder { pub exclusive: bool, pub svid: int32, pub oh: netobj, pub l_offset: uint64, pub l_len: uint64 }

#[repr(C)]
#[derive(Copy, Clone)]
pub union nlm4_testrply_u { pub holder: nlm4_holder }

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_testrply { pub stat: nlm4_stats, pub u: nlm4_testrply_u }

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_stat { pub stat: nlm4_stats }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_res { pub cookie: netobj, pub stat: nlm4_stat }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_testres { pub cookie: netobj, pub stat: nlm4_testrply }

#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_lock { pub caller_name: string, pub fh: netobj, pub oh: netobj, pub svid: int32, pub l_offset: uint64, pub l_len: uint64 }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_lockargs { pub cookie: netobj, pub block: bool, pub exclusive: bool, pub alock: nlm4_lock, pub reclaim: bool, pub state: int32 }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_cancargs { pub cookie: netobj, pub block: bool, pub exclusive: bool, pub alock: nlm4_lock }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_testargs { pub cookie: netobj, pub exclusive: bool, pub alock: nlm4_lock }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_unlockargs { pub cookie: netobj, pub alock: nlm4_lock }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_share { pub caller_name: string, pub fh: netobj, pub oh: netobj, pub mode: fsh4_mode, pub access: fsh4_access }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_shareargs { pub cookie: netobj, pub share: nlm4_share, pub reclaim: bool }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_shareres { pub cookie: netobj, pub stat: nlm4_stats, pub sequence: int32 }
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_notify { pub name: string, pub state: int32 }
pub const SM_PRIV_SIZE: usize = 16;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nlm4_notifyargs { pub notify: nlm4_notify, pub private: [u8; SM_PRIV_SIZE] }

pub const NLMPROC4_NULL: i32 = 0; pub const NLMPROC4_TEST: i32 = 1; pub const NLMPROC4_LOCK: i32 = 2; pub const NLMPROC4_CANCEL: i32 = 3; pub const NLMPROC4_UNLOCK: i32 = 4; pub const NLMPROC4_GRANTED: i32 = 5; pub const NLMPROC4_TEST_MSG: i32 = 6; pub const NLMPROC4_LOCK_MSG: i32 = 7; pub const NLMPROC4_CANCEL_MSG: i32 = 8; pub const NLMPROC4_UNLOCK_MSG: i32 = 9; pub const NLMPROC4_GRANTED_MSG: i32 = 10; pub const NLMPROC4_TEST_RES: i32 = 11; pub const NLMPROC4_LOCK_RES: i32 = 12; pub const NLMPROC4_CANCEL_RES: i32 = 13; pub const NLMPROC4_UNLOCK_RES: i32 = 14; pub const NLMPROC4_GRANTED_RES: i32 = 15; pub const NLMPROC4_SM_NOTIFY: i32 = 16; pub const NLMPROC4_SHARE: i32 = 20; pub const NLMPROC4_UNSHARE: i32 = 21; pub const NLMPROC4_NM_LOCK: i32 = 22; pub const NLMPROC4_FREE_ALL: i32 = 23;

pub const NLM4_PROG: u32 = 100021;
// XDR size macros retain their original dependency on XDR_* constants and XDR_QUADLEN.
pub const NLM4_netobj_sz: usize = XDR_unsigned_int + XDR_QUADLEN(MAXNETOBJ_SZ);
pub const NLM4_fsh4_mode_sz: usize = XDR_int;
pub const NLM4_fsh4_access_sz: usize = XDR_int;
pub const NLM4_uint64_sz: usize = XDR_unsigned_hyper;
pub const NLM4_int64_sz: usize = XDR_hyper;
pub const NLM4_uint32_sz: usize = XDR_unsigned_long;
pub const NLM4_int32_sz: usize = XDR_long;
pub const NLM4_nlm4_stats_sz: usize = XDR_int;
pub const NLM4_nlm4_holder_sz: usize = XDR_bool + NLM4_int32_sz + NLM4_netobj_sz + NLM4_uint64_sz + NLM4_uint64_sz;
pub const NLM4_nlm4_testrply_sz: usize = NLM4_nlm4_stats_sz + NLM4_nlm4_holder_sz;
pub const NLM4_nlm4_stat_sz: usize = NLM4_nlm4_stats_sz;
pub const NLM4_nlm4_res_sz: usize = NLM4_netobj_sz + NLM4_nlm4_stat_sz;
pub const NLM4_nlm4_testres_sz: usize = NLM4_netobj_sz + NLM4_nlm4_testrply_sz;
pub const NLM4_nlm4_lock_sz: usize = XDR_unsigned_int + XDR_QUADLEN(LM_MAXSTRLEN) + NLM4_netobj_sz + NLM4_netobj_sz + NLM4_int32_sz + NLM4_uint64_sz + NLM4_uint64_sz;
pub const NLM4_nlm4_lockargs_sz: usize = NLM4_netobj_sz + XDR_bool + XDR_bool + NLM4_nlm4_lock_sz + XDR_bool + NLM4_int32_sz;
pub const NLM4_nlm4_cancargs_sz: usize = NLM4_netobj_sz + XDR_bool + XDR_bool + NLM4_nlm4_lock_sz;
pub const NLM4_nlm4_testargs_sz: usize = NLM4_netobj_sz + XDR_bool + NLM4_nlm4_lock_sz;
pub const NLM4_nlm4_unlockargs_sz: usize = NLM4_netobj_sz + NLM4_nlm4_lock_sz;
pub const NLM4_nlm4_share_sz: usize = XDR_unsigned_int + XDR_QUADLEN(LM_MAXSTRLEN) + NLM4_netobj_sz + NLM4_netobj_sz + NLM4_fsh4_mode_sz + NLM4_fsh4_access_sz;
pub const NLM4_nlm4_shareargs_sz: usize = NLM4_netobj_sz + NLM4_nlm4_share_sz + XDR_bool;
pub const NLM4_nlm4_shareres_sz: usize = NLM4_netobj_sz + NLM4_nlm4_stats_sz + NLM4_int32_sz;
pub const NLM4_nlm4_notify_sz: usize = XDR_unsigned_int + XDR_QUADLEN(LM_MAXNAMELEN) + NLM4_int32_sz;
pub const NLM4_nlm4_notifyargs_sz: usize = NLM4_nlm4_notify_sz + XDR_QUADLEN(SM_PRIV_SIZE);
pub const NLM4_MAX_ARGS_SZ: usize = NLM4_nlm4_lockargs_sz;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
