/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * include/asm-parisc/pdc_chassis.h
 *
 * Copyright (C) 2002 Laurent Canet <canetl@esiee.fr>
 * Copyright (C) 2002 Thibaut Varene <varenet@parisc-linux.org>
 *
 * TODO: - handle processor number on SMP systems (Reporting Entity ID)
 *       - handle message ID
 *       - handle timestamps
 */

extern "C" {
    pub fn pdc_chassis_send_status(message: ::core::ffi::c_int) -> ::core::ffi::c_int;
    pub fn parisc_pdc_chassis_init();
}

pub const PDC_CHASSIS_DIRECT_BSTART: u64 = 0;
pub const PDC_CHASSIS_DIRECT_BCOMPLETE: u64 = 1;
pub const PDC_CHASSIS_DIRECT_SHUTDOWN: u64 = 2;
pub const PDC_CHASSIS_DIRECT_PANIC: u64 = 3;
pub const PDC_CHASSIS_DIRECT_HPMC: u64 = 4;
pub const PDC_CHASSIS_DIRECT_LPMC: u64 = 5;
pub const PDC_CHASSIS_DIRECT_DUMP: u64 = 6; // not yet implemented
pub const PDC_CHASSIS_DIRECT_OOPS: u64 = 7; // not yet implemented

pub const fn PDC_CHASSIS_DISP_DATA(v: u64) -> u64 { v << 17 }

pub const PDC_CHASSIS_LED_RUN_OFF: u64 = 0u64 << 4;
pub const PDC_CHASSIS_LED_RUN_FLASH: u64 = 1u64 << 4;
pub const PDC_CHASSIS_LED_RUN_ON: u64 = 2u64 << 4;
pub const PDC_CHASSIS_LED_RUN_NC: u64 = 3u64 << 4;
pub const PDC_CHASSIS_LED_ATTN_OFF: u64 = 0u64 << 6;
pub const PDC_CHASSIS_LED_ATTN_FLASH: u64 = 1u64 << 6;
pub const PDC_CHASSIS_LED_ATTN_NC: u64 = 3u64 << 6; // ATTN ON is invalid
pub const PDC_CHASSIS_LED_FAULT_OFF: u64 = 0u64 << 8;
pub const PDC_CHASSIS_LED_FAULT_FLASH: u64 = 1u64 << 8;
pub const PDC_CHASSIS_LED_FAULT_ON: u64 = 2u64 << 8;
pub const PDC_CHASSIS_LED_FAULT_NC: u64 = 3u64 << 8;
pub const PDC_CHASSIS_LED_VALID: u64 = 1u64 << 10;

pub const PDC_CHASSIS_LSTATE_RUN_NORMAL: u64 = PDC_CHASSIS_LED_RUN_ON | PDC_CHASSIS_LED_ATTN_OFF | PDC_CHASSIS_LED_FAULT_OFF | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_RUN_CRASHREC: u64 = PDC_CHASSIS_LED_RUN_ON | PDC_CHASSIS_LED_ATTN_OFF | PDC_CHASSIS_LED_FAULT_FLASH | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_RUN_SYSINT: u64 = PDC_CHASSIS_LED_RUN_ON | PDC_CHASSIS_LED_ATTN_FLASH | PDC_CHASSIS_LED_FAULT_OFF | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_RUN_NCRIT: u64 = PDC_CHASSIS_LED_RUN_ON | PDC_CHASSIS_LED_ATTN_FLASH | PDC_CHASSIS_LED_FAULT_FLASH | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_NONOS: u64 = PDC_CHASSIS_LED_RUN_FLASH | PDC_CHASSIS_LED_ATTN_OFF | PDC_CHASSIS_LED_FAULT_OFF | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_NONOS_BFAIL: u64 = PDC_CHASSIS_LED_RUN_FLASH | PDC_CHASSIS_LED_ATTN_OFF | PDC_CHASSIS_LED_FAULT_ON | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_NONOS_UNEXP: u64 = PDC_CHASSIS_LED_RUN_FLASH | PDC_CHASSIS_LED_ATTN_OFF | PDC_CHASSIS_LED_FAULT_FLASH | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_NONOS_NCRIT: u64 = PDC_CHASSIS_LED_RUN_FLASH | PDC_CHASSIS_LED_ATTN_FLASH | PDC_CHASSIS_LED_FAULT_OFF | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_BFAIL_NCRIT: u64 = PDC_CHASSIS_LED_RUN_FLASH | PDC_CHASSIS_LED_ATTN_FLASH | PDC_CHASSIS_LED_FAULT_ON | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_UNEXP_NCRIT: u64 = PDC_CHASSIS_LED_RUN_FLASH | PDC_CHASSIS_LED_ATTN_FLASH | PDC_CHASSIS_LED_FAULT_FLASH | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_CANNOT_PDC: u64 = PDC_CHASSIS_LED_RUN_OFF | PDC_CHASSIS_LED_ATTN_OFF | PDC_CHASSIS_LED_FAULT_OFF | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_FATAL_BFAIL: u64 = PDC_CHASSIS_LED_RUN_OFF | PDC_CHASSIS_LED_ATTN_OFF | PDC_CHASSIS_LED_FAULT_ON | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_NOCODE_NCRIT: u64 = PDC_CHASSIS_LED_RUN_OFF | PDC_CHASSIS_LED_ATTN_FLASH | PDC_CHASSIS_LED_FAULT_OFF | PDC_CHASSIS_LED_VALID;
pub const PDC_CHASSIS_LSTATE_FATAL_NCRIT: u64 = PDC_CHASSIS_LED_RUN_OFF | PDC_CHASSIS_LED_ATTN_FLASH | PDC_CHASSIS_LED_FAULT_ON | PDC_CHASSIS_LED_VALID;

pub const PDC_CHASSIS_ALERT_FORWARD: u64 = 0u64 << 36;
pub const PDC_CHASSIS_ALERT_SERPROC: u64 = 1u64 << 36;
pub const PDC_CHASSIS_ALERT_NURGENT: u64 = 2u64 << 36;
pub const PDC_CHASSIS_ALERT_BLOCKED: u64 = 3u64 << 36;
pub const PDC_CHASSIS_ALERT_CONF_CHG: u64 = 4u64 << 36;
pub const PDC_CHASSIS_ALERT_ENV_PB: u64 = 5u64 << 36;
pub const PDC_CHASSIS_ALERT_PENDING: u64 = 6u64 << 36;
pub const PDC_CHASSIS_ALERT_PERF_IMP: u64 = 8u64 << 36;
pub const PDC_CHASSIS_ALERT_FUNC_IMP: u64 = 10u64 << 36;
pub const PDC_CHASSIS_ALERT_SOFT_FAIL: u64 = 12u64 << 36;
pub const PDC_CHASSIS_ALERT_HANG: u64 = 13u64 << 36;
pub const PDC_CHASSIS_ALERT_ENV_FATAL: u64 = 14u64 << 36;
pub const PDC_CHASSIS_ALERT_HW_FATAL: u64 = 15u64 << 36;

pub const PDC_CHASSIS_SRC_NONE: u64 = 0u64 << 28;
pub const PDC_CHASSIS_SRC_PROC: u64 = 1u64 << 28;
pub const PDC_CHASSIS_SRC_PROC_CACHE: u64 = 2u64 << 28;
pub const PDC_CHASSIS_SRC_PDH: u64 = 3u64 << 28;
pub const PDC_CHASSIS_SRC_PWR: u64 = 4u64 << 28;
pub const PDC_CHASSIS_SRC_FAB: u64 = 5u64 << 28;
pub const PDC_CHASSIS_SRC_PLATi: u64 = 6u64 << 28;
pub const PDC_CHASSIS_SRC_MEM: u64 = 7u64 << 28;
pub const PDC_CHASSIS_SRC_IO: u64 = 8u64 << 28;
pub const PDC_CHASSIS_SRC_CELL: u64 = 9u64 << 28;
pub const PDC_CHASSIS_SRC_PD: u64 = 10u64 << 28;
pub const PDC_CHASSIS_SRC_D_PROC: u64 = 1u64 << 24;
pub const PDC_CHASSIS_SRC_ID_UNSPEC: u64 = 0u64 << 16;
pub const PDC_CHASSIS_PB_D_PROC_NONE: u64 = 0u64 << 32;
pub const PDC_CHASSIS_PB_D_PROC_TIMEOUT: u64 = 4u64 << 32;

pub const PDC_CHASSIS_CALL_ACT_HPUX_BL: u64 = 7u64 << 12;
pub const PDC_CHASSIS_CALL_ACT_HPUX_PD: u64 = 8u64 << 12;
pub const PDC_CHASSIS_CALL_ACT_HPUX_EVENT: u64 = 9u64 << 12;
pub const PDC_CHASSIS_CALL_ACT_HPUX_IO: u64 = 10u64 << 12;
pub const PDC_CHASSIS_CALL_ACT_HPUX_PANIC: u64 = 11u64 << 12;
pub const PDC_CHASSIS_CALL_ACT_HPUX_INIT: u64 = 12u64 << 12;
pub const PDC_CHASSIS_CALL_ACT_HPUX_SHUT: u64 = 13u64 << 12;
pub const PDC_CHASSIS_CALL_ACT_HPUX_WARN: u64 = 14u64 << 12;
pub const PDC_CHASSIS_CALL_ACT_HPUX_DU: u64 = 15u64 << 12;
pub const PDC_CHASSIS_ACT_STATUS_UNSPEC: u64 = 0u64;
pub const PDC_CHASSIS_CALL_SACT_UNSPEC: u64 = 0u64 << 4;
pub const PDC_CHASSIS_RET_GENERICOS: u64 = 12u64 << 52;
pub const PDC_CHASSIS_RET_IA64_NT: u64 = 13u64 << 52;
pub const PDC_CHASSIS_RET_HPUX: u64 = 14u64 << 52;
pub const PDC_CHASSIS_RET_DIAG: u64 = 15u64 << 52;
pub const PDC_CHASSIS_REID_UNSPEC: u64 = 0u64 << 44;

pub const PDC_CHASSIS_DT_NONE: u64 = 0u64 << 59;
pub const PDC_CHASSIS_DT_PHYS_ADDR: u64 = 1u64 << 59;
pub const PDC_CHASSIS_DT_DATA_EXPECT: u64 = 2u64 << 59;
pub const PDC_CHASSIS_DT_ACTUAL: u64 = 3u64 << 59;
pub const PDC_CHASSIS_DT_PHYS_LOC: u64 = 4u64 << 59;
pub const PDC_CHASSIS_DT_PHYS_LOC_EXT: u64 = 5u64 << 59;
pub const PDC_CHASSIS_DT_TAG: u64 = 6u64 << 59;
pub const PDC_CHASSIS_DT_SYNDROME: u64 = 7u64 << 59;
pub const PDC_CHASSIS_DT_CODE_ADDR: u64 = 8u64 << 59;
pub const PDC_CHASSIS_DT_ASCII_MSG: u64 = 9u64 << 59;
pub const PDC_CHASSIS_DT_POST: u64 = 10u64 << 59;
pub const PDC_CHASSIS_DT_TIMESTAMP: u64 = 11u64 << 59;
pub const PDC_CHASSIS_DT_DEV_STAT: u64 = 12u64 << 59;
pub const PDC_CHASSIS_DT_DEV_TYPE: u64 = 13u64 << 59;
pub const PDC_CHASSIS_DT_PB_DET: u64 = 14u64 << 59;
pub const PDC_CHASSIS_DT_ACT_LEV: u64 = 15u64 << 59;
pub const PDC_CHASSIS_DT_SER_NUM: u64 = 16u64 << 59;
pub const PDC_CHASSIS_DT_REV_NUM: u64 = 17u64 << 59;
pub const PDC_CHASSIS_DT_INTERRUPT: u64 = 18u64 << 59;
pub const PDC_CHASSIS_DT_TEST_NUM: u64 = 19u64 << 59;
pub const PDC_CHASSIS_DT_STATE_CHG: u64 = 20u64 << 59;
pub const PDC_CHASSIS_DT_PROC_DEALLOC: u64 = 21u64 << 59;
pub const PDC_CHASSIS_DT_RESET: u64 = 30u64 << 59;
pub const PDC_CHASSIS_DT_PA_LEGACY: u64 = 31u64 << 59;

pub const PDC_CHASSIS_SYSTATE_BSTART: u64 = 0;
pub const PDC_CHASSIS_SYSTATE_BCOMP: u64 = 1;
pub const PDC_CHASSIS_SYSTATE_CHANGE: u64 = 2;
pub const PDC_CHASSIS_SYSTATE_LED: u64 = 3;
pub const PDC_CHASSIS_SYSTATE_PANIC: u64 = 9;
pub const PDC_CHASSIS_SYSTATE_DUMP: u64 = 10;
pub const PDC_CHASSIS_SYSTATE_HPMC: u64 = 11;
pub const PDC_CHASSIS_SYSTATE_HALT: u64 = 15;
pub const PDC_CHASSIS_MSG_ID: u64 = 0u64 << 40;
pub const PDC_CHASSIS_EOM_CLEAR: u64 = 0u64 << 43;
pub const PDC_CHASSIS_EOM_SET: u64 = 1u64 << 43;

pub const PDC_CHASSIS_PMSG_BSTART: u64 = PDC_CHASSIS_ALERT_SERPROC | PDC_CHASSIS_SRC_PROC | PDC_CHASSIS_SRC_D_PROC | PDC_CHASSIS_SRC_ID_UNSPEC | PDC_CHASSIS_PB_D_PROC_NONE | PDC_CHASSIS_CALL_ACT_HPUX_INIT | PDC_CHASSIS_ACT_STATUS_UNSPEC | PDC_CHASSIS_CALL_SACT_UNSPEC | PDC_CHASSIS_RET_HPUX | PDC_CHASSIS_REID_UNSPEC | PDC_CHASSIS_DT_STATE_CHG | PDC_CHASSIS_SYSTATE_BSTART | PDC_CHASSIS_MSG_ID | PDC_CHASSIS_EOM_SET;
pub const PDC_CHASSIS_PMSG_BCOMPLETE: u64 = PDC_CHASSIS_ALERT_SERPROC | PDC_CHASSIS_SRC_PROC | PDC_CHASSIS_SRC_D_PROC | PDC_CHASSIS_SRC_ID_UNSPEC | PDC_CHASSIS_PB_D_PROC_NONE | PDC_CHASSIS_CALL_ACT_HPUX_INIT | PDC_CHASSIS_ACT_STATUS_UNSPEC | PDC_CHASSIS_CALL_SACT_UNSPEC | PDC_CHASSIS_RET_HPUX | PDC_CHASSIS_REID_UNSPEC | PDC_CHASSIS_DT_STATE_CHG | PDC_CHASSIS_SYSTATE_BCOMP | PDC_CHASSIS_MSG_ID | PDC_CHASSIS_EOM_SET;
pub const PDC_CHASSIS_PMSG_SHUTDOWN: u64 = PDC_CHASSIS_ALERT_SERPROC | PDC_CHASSIS_SRC_PROC | PDC_CHASSIS_SRC_D_PROC | PDC_CHASSIS_SRC_ID_UNSPEC | PDC_CHASSIS_PB_D_PROC_NONE | PDC_CHASSIS_CALL_ACT_HPUX_SHUT | PDC_CHASSIS_ACT_STATUS_UNSPEC | PDC_CHASSIS_CALL_SACT_UNSPEC | PDC_CHASSIS_RET_HPUX | PDC_CHASSIS_REID_UNSPEC | PDC_CHASSIS_DT_STATE_CHG | PDC_CHASSIS_SYSTATE_HALT | PDC_CHASSIS_MSG_ID | PDC_CHASSIS_EOM_SET;
pub const PDC_CHASSIS_PMSG_PANIC: u64 = PDC_CHASSIS_ALERT_SOFT_FAIL | PDC_CHASSIS_SRC_PROC | PDC_CHASSIS_SRC_D_PROC | PDC_CHASSIS_SRC_ID_UNSPEC | PDC_CHASSIS_PB_D_PROC_NONE | PDC_CHASSIS_CALL_ACT_HPUX_PANIC | PDC_CHASSIS_ACT_STATUS_UNSPEC | PDC_CHASSIS_CALL_SACT_UNSPEC | PDC_CHASSIS_RET_HPUX | PDC_CHASSIS_REID_UNSPEC | PDC_CHASSIS_DT_STATE_CHG | PDC_CHASSIS_SYSTATE_PANIC | PDC_CHASSIS_MSG_ID | PDC_CHASSIS_EOM_SET;
// FIXME: extrapolated data
pub const PDC_CHASSIS_PMSG_HPMC: u64 = PDC_CHASSIS_ALERT_CONF_CHG | PDC_CHASSIS_SRC_PROC | PDC_CHASSIS_SRC_D_PROC | PDC_CHASSIS_SRC_ID_UNSPEC | PDC_CHASSIS_PB_D_PROC_NONE | PDC_CHASSIS_CALL_ACT_HPUX_WARN | PDC_CHASSIS_RET_HPUX | PDC_CHASSIS_DT_STATE_CHG | PDC_CHASSIS_SYSTATE_HPMC | PDC_CHASSIS_MSG_ID | PDC_CHASSIS_EOM_SET;
pub const PDC_CHASSIS_PMSG_LPMC: u64 = PDC_CHASSIS_ALERT_BLOCKED | PDC_CHASSIS_SRC_PROC | PDC_CHASSIS_SRC_D_PROC | PDC_CHASSIS_SRC_ID_UNSPEC | PDC_CHASSIS_PB_D_PROC_NONE | PDC_CHASSIS_CALL_ACT_HPUX_WARN | PDC_CHASSIS_ACT_STATUS_UNSPEC | PDC_CHASSIS_CALL_SACT_UNSPEC | PDC_CHASSIS_RET_HPUX | PDC_CHASSIS_REID_UNSPEC | PDC_CHASSIS_DT_STATE_CHG | PDC_CHASSIS_SYSTATE_CHANGE | PDC_CHASSIS_MSG_ID | PDC_CHASSIS_EOM_SET;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
