/* SPDX-License-Identifier: GPL-2.0 */

// Translated from scsi_tcq.h.
//
// Original dependencies:
//   <linux/blkdev.h>
//   <scsi/scsi_cmnd.h>
//   <scsi/scsi_device.h>
//   <scsi/scsi_host.h>

pub const SCSI_NO_TAG: i32 = -1; /* identify no tag in use */

// CONFIG_BLOCK
/**
 * scsi_host_find_tag - find the tagged command by host
 * @shost:  pointer to scsi_host
 * @tag:    tag
 *
 * Note: for devices using multiple hardware queues tag must have been
 * generated by blk_mq_unique_tag().
 */
pub unsafe fn scsi_host_find_tag(
    shost: *mut Scsi_Host,
    tag: i32,
) -> *mut scsi_cmnd {
    let mut req: *mut request = core::ptr::null_mut();
    let hwq: u16;

    if tag == SCSI_NO_TAG {
        return core::ptr::null_mut();
    }

    hwq = blk_mq_unique_tag_to_hwq(tag);
    if hwq < (*shost).tag_set.nr_hw_queues {
        req = blk_mq_tag_to_rq(
            (*shost).tag_set.tags[hwq as usize],
            blk_mq_unique_tag_to_tag(tag),
        );
    }

    if req.is_null() || !blk_mq_request_started(req) {
        return core::ptr::null_mut();
    }
    blk_mq_rq_to_pdu(req)
}


// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
