/* SPDX-License-Identifier: GPL-2.0 */

/*
 * Each time we reclaim bits for reuse we need to specify another bit
 * that, if present, indicates we have the new incarnation of that
 * feature.  Base case is 1 (first use).
 */
pub const CEPH_FEATURE_INCARNATION_1: u64 = 0u64;
pub const CEPH_FEATURE_INCARNATION_2: u64 = 1u64 << 57; // SERVER_JEWEL
pub const CEPH_FEATURE_INCARNATION_3: u64 = (1u64 << 57) | (1u64 << 28); // SERVER_MIMIC

/* this bit is ignored but still advertised by release *when* */
/* Deprecated and retired feature declarations are represented by their
 * explicitly emitted constants below; retired declarations emit nothing. */

/*
 * test for a feature.  this test is safer than a typical mask against
 * the bit because it ensures that we have the bit AND the marker for
 * the bit's incarnation.  this must be used in any case where the features
 * bits may include an old meaning of the bit.
 */
#[inline]
pub const fn ceph_have_feature(x: u64, mask: u64) -> bool {
    (x & mask) == mask
}

/*
 * Notes on deprecation:
 *
 * A *major* release is a release through which all upgrades must pass
 * (e.g., jewel).  For example, no pre-jewel server will ever talk to
 * a post-jewel server (mon, osd, etc).
 *
 * For feature bits used *only* on the server-side:
 *
 *  - In the first phase we indicate that a feature is DEPRECATED as of
 *    a particular release.  This is the first major release X (say,
 *    jewel) that does not depend on its peers advertising the feature.
 *    That is, it safely assumes its peers all have the feature.  We
 *    indicate this with the DEPRECATED macro.
 *
 *  - In the second phase we stop advertising the bit and call it RETIRED.
 *    This can normally be done in the *next* major release.
 */

/* Feature constants. */
pub const CEPH_FEATURE_UID: u64 = 1u64 << 0;
pub const CEPH_FEATUREMASK_UID: u64 = (1u64 << 0) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_NOSRCADDR: u64 = 1u64 << 1;
pub const CEPH_FEATUREMASK_NOSRCADDR: u64 = (1u64 << 1) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_OBJECTLOCATOR: u64 = 1u64 << 8;
pub const CEPH_FEATUREMASK_OBJECTLOCATOR: u64 = (1u64 << 8) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_SERVER_NAUTILUS: u64 = 1u64 << 2;
pub const CEPH_FEATUREMASK_SERVER_NAUTILUS: u64 = (1u64 << 2) | CEPH_FEATURE_INCARNATION_3;
pub const CEPH_FEATURE_FLOCK: u64 = 1u64 << 3;
pub const CEPH_FEATUREMASK_FLOCK: u64 = (1u64 << 3) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_SUBSCRIBE2: u64 = 1u64 << 4;
pub const CEPH_FEATUREMASK_SUBSCRIBE2: u64 = (1u64 << 4) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_MONNAMES: u64 = 1u64 << 5;
pub const CEPH_FEATUREMASK_MONNAMES: u64 = (1u64 << 5) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_RECONNECT_SEQ: u64 = 1u64 << 6;
pub const CEPH_FEATUREMASK_RECONNECT_SEQ: u64 = (1u64 << 6) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_DIRLAYOUTHASH: u64 = 1u64 << 7;
pub const CEPH_FEATUREMASK_DIRLAYOUTHASH: u64 = (1u64 << 7) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_PGID64: u64 = 1u64 << 9;
pub const CEPH_FEATUREMASK_PGID64: u64 = (1u64 << 9) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_PGPOOL3: u64 = 1u64 << 11;
pub const CEPH_FEATUREMASK_PGPOOL3: u64 = (1u64 << 11) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_OSDENC: u64 = 1u64 << 13;
pub const CEPH_FEATUREMASK_OSDENC: u64 = (1u64 << 13) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_MONENC: u64 = 1u64 << 15;
pub const CEPH_FEATUREMASK_MONENC: u64 = (1u64 << 15) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_SERVER_KRAKEN: u64 = 1u64 << 14;
pub const CEPH_FEATUREMASK_SERVER_KRAKEN: u64 = (1u64 << 14) | CEPH_FEATURE_INCARNATION_2;
pub const CEPH_FEATURE_CRUSH_TUNABLES2: u64 = 1u64 << 25;
pub const CEPH_FEATUREMASK_CRUSH_TUNABLES2: u64 = (1u64 << 25) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_CRUSH_TUNABLES: u64 = 1u64 << 18;
pub const CEPH_FEATUREMASK_CRUSH_TUNABLES: u64 = (1u64 << 18) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_SERVER_LUMINOUS: u64 = 1u64 << 21;
pub const CEPH_FEATUREMASK_SERVER_LUMINOUS: u64 = (1u64 << 21) | CEPH_FEATURE_INCARNATION_2;
pub const CEPH_FEATURE_MSG_AUTH: u64 = 1u64 << 23;
pub const CEPH_FEATUREMASK_MSG_AUTH: u64 = (1u64 << 23) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_RESEND_ON_SPLIT: u64 = 1u64 << 21;
pub const CEPH_FEATUREMASK_RESEND_ON_SPLIT: u64 = (1u64 << 21) | CEPH_FEATURE_INCARNATION_2;
pub const CEPH_FEATURE_RADOS_BACKOFF: u64 = 1u64 << 21;
pub const CEPH_FEATUREMASK_RADOS_BACKOFF: u64 = (1u64 << 21) | CEPH_FEATURE_INCARNATION_2;
pub const CEPH_FEATURE_OSDMAP_PG_UPMAP: u64 = 1u64 << 21;
pub const CEPH_FEATUREMASK_OSDMAP_PG_UPMAP: u64 = (1u64 << 21) | CEPH_FEATURE_INCARNATION_2;
pub const CEPH_FEATURE_CRUSH_CHOOSE_ARGS: u64 = 1u64 << 21;
pub const CEPH_FEATUREMASK_CRUSH_CHOOSE_ARGS: u64 = (1u64 << 21) | CEPH_FEATURE_INCARNATION_2;
pub const CEPH_FEATURE_REPLY_CREATE_INODE: u64 = 1u64 << 27;
pub const CEPH_FEATUREMASK_REPLY_CREATE_INODE: u64 = (1u64 << 27) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_SERVER_MIMIC: u64 = 1u64 << 28;
pub const CEPH_FEATUREMASK_SERVER_MIMIC: u64 = (1u64 << 28) | CEPH_FEATURE_INCARNATION_2;
pub const CEPH_FEATURE_MDSENC: u64 = 1u64 << 29;
pub const CEPH_FEATUREMASK_MDSENC: u64 = (1u64 << 29) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_OSDHASHPSPOOL: u64 = 1u64 << 30;
pub const CEPH_FEATUREMASK_OSDHASHPSPOOL: u64 = (1u64 << 30) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_OSD_CACHEPOOL: u64 = 1u64 << 35;
pub const CEPH_FEATUREMASK_OSD_CACHEPOOL: u64 = (1u64 << 35) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_CRUSH_V2: u64 = 1u64 << 36;
pub const CEPH_FEATUREMASK_CRUSH_V2: u64 = (1u64 << 36) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_EXPORT_PEER: u64 = 1u64 << 37;
pub const CEPH_FEATUREMASK_EXPORT_PEER: u64 = (1u64 << 37) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_OSDMAP_ENC: u64 = 1u64 << 39;
pub const CEPH_FEATUREMASK_OSDMAP_ENC: u64 = (1u64 << 39) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_MDS_INLINE_DATA: u64 = 1u64 << 40;
pub const CEPH_FEATUREMASK_MDS_INLINE_DATA: u64 = (1u64 << 40) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_CRUSH_TUNABLES3: u64 = 1u64 << 41;
pub const CEPH_FEATUREMASK_CRUSH_TUNABLES3: u64 = (1u64 << 41) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_OSD_PRIMARY_AFFINITY: u64 = 1u64 << 41;
pub const CEPH_FEATUREMASK_OSD_PRIMARY_AFFINITY: u64 = (1u64 << 41) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_MSGR_KEEPALIVE2: u64 = 1u64 << 42;
pub const CEPH_FEATUREMASK_MSGR_KEEPALIVE2: u64 = (1u64 << 42) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_OSD_POOLRESEND: u64 = 1u64 << 43;
pub const CEPH_FEATUREMASK_OSD_POOLRESEND: u64 = (1u64 << 43) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_MDS_QUOTA: u64 = 1u64 << 47;
pub const CEPH_FEATUREMASK_MDS_QUOTA: u64 = (1u64 << 47) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_CRUSH_V4: u64 = 1u64 << 48;
pub const CEPH_FEATUREMASK_CRUSH_V4: u64 = (1u64 << 48) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_NEW_OSDOP_ENCODING: u64 = 1u64 << 56;
pub const CEPH_FEATUREMASK_NEW_OSDOP_ENCODING: u64 = (1u64 << 56) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_MON_STATEFUL_SUB: u64 = 1u64 << 57;
pub const CEPH_FEATUREMASK_MON_STATEFUL_SUB: u64 = (1u64 << 57) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_SERVER_JEWEL: u64 = 1u64 << 57;
pub const CEPH_FEATUREMASK_SERVER_JEWEL: u64 = (1u64 << 57) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_CRUSH_TUNABLES5: u64 = 1u64 << 58;
pub const CEPH_FEATUREMASK_CRUSH_TUNABLES5: u64 = (1u64 << 58) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_NEW_OSDOPREPLY_ENCODING: u64 = 1u64 << 58;
pub const CEPH_FEATUREMASK_NEW_OSDOPREPLY_ENCODING: u64 = (1u64 << 58) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_MSG_ADDR2: u64 = 1u64 << 59;
pub const CEPH_FEATUREMASK_MSG_ADDR2: u64 = (1u64 << 59) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_CEPHX_V2: u64 = 1u64 << 61;
pub const CEPH_FEATUREMASK_CEPHX_V2: u64 = (1u64 << 61) | CEPH_FEATURE_INCARNATION_1;
pub const CEPH_FEATURE_RESERVED: u64 = 1u64 << 62;
pub const CEPH_FEATUREMASK_RESERVED: u64 = (1u64 << 62) | CEPH_FEATURE_INCARNATION_1;
pub const DEPRECATED_CEPH_FEATURE_RESERVED_BROKEN: u64 = 1u64 << 63;
pub const DEPRECATED_CEPH_FEATUREMASK_RESERVED_BROKEN: u64 = (1u64 << 63) | CEPH_FEATURE_INCARNATION_1;

/* Features supported. */
pub const CEPH_FEATURES_SUPPORTED_DEFAULT: u64 =
    CEPH_FEATURE_NOSRCADDR | CEPH_FEATURE_SERVER_NAUTILUS |
    CEPH_FEATURE_FLOCK | CEPH_FEATURE_SUBSCRIBE2 | CEPH_FEATURE_MONNAMES |
    CEPH_FEATURE_RECONNECT_SEQ | CEPH_FEATURE_DIRLAYOUTHASH | CEPH_FEATURE_PGID64 |
    CEPH_FEATURE_PGPOOL3 | CEPH_FEATURE_OSDENC | CEPH_FEATURE_MONENC |
    CEPH_FEATURE_CRUSH_TUNABLES | CEPH_FEATURE_SERVER_LUMINOUS |
    CEPH_FEATURE_RESEND_ON_SPLIT | CEPH_FEATURE_RADOS_BACKOFF |
    CEPH_FEATURE_OSDMAP_PG_UPMAP | CEPH_FEATURE_CRUSH_CHOOSE_ARGS |
    CEPH_FEATURE_MSG_AUTH | CEPH_FEATURE_CRUSH_TUNABLES2 |
    CEPH_FEATURE_REPLY_CREATE_INODE | CEPH_FEATURE_SERVER_MIMIC |
    CEPH_FEATURE_MDSENC | CEPH_FEATURE_OSDHASHPSPOOL | CEPH_FEATURE_OSD_CACHEPOOL |
    CEPH_FEATURE_CRUSH_V2 | CEPH_FEATURE_EXPORT_PEER | CEPH_FEATURE_OSDMAP_ENC |
    CEPH_FEATURE_MDS_INLINE_DATA | CEPH_FEATURE_CRUSH_TUNABLES3 |
    CEPH_FEATURE_OSD_PRIMARY_AFFINITY | CEPH_FEATURE_MSGR_KEEPALIVE2 |
    CEPH_FEATURE_OSD_POOLRESEND | CEPH_FEATURE_MDS_QUOTA | CEPH_FEATURE_CRUSH_V4 |
    CEPH_FEATURE_NEW_OSDOP_ENCODING | CEPH_FEATURE_SERVER_JEWEL |
    CEPH_FEATURE_MON_STATEFUL_SUB | CEPH_FEATURE_CRUSH_TUNABLES5 |
    CEPH_FEATURE_NEW_OSDOPREPLY_ENCODING | CEPH_FEATURE_MSG_ADDR2 |
    CEPH_FEATURE_CEPHX_V2;

pub const CEPH_FEATURES_REQUIRED_DEFAULT: u64 = 0;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
