# SPDX-License-Identifier: GPL-2.0-only
# tools/power/acpi/Makefile.rules - ACPI tool Makefile
#
# Copyright (c) 2015, Intel Corporation
#   Author: Lv Zheng <lv.zheng@intel.com>
#

objdir := $(OUTPUT)tools/$(TOOL)/
toolobjs := $(addprefix $(objdir),$(TOOL_OBJS))

HOST_TOOLS_LANG ?= rust
ifneq ($(HOST_TOOLS_LANG),c)
ifneq ($(HOST_TOOLS_LANG),rust)
$(error HOST_TOOLS_LANG must be 'c' or 'rust')
endif
endif

ifneq ($(and $(filter rust,$(HOST_TOOLS_LANG)),$(TOOL_RUST_SOURCE)),)
HOSTRUSTC ?= rustc
KBUILD_HOSTRUSTFLAGS ?= --edition=2021
ifneq ($(filter-out clean uninstall,$(or $(MAKECMDGOALS),all)),)
ifneq ($(CROSS_COMPILE),)
ifeq ($(RUST_TARGET),)
$(error Set RUST_TARGET to the matching Rust triple for CROSS_COMPILE)
endif
endif
ifneq ($(filter --target --target=%,$(KBUILD_HOSTRUSTFLAGS) $(HOSTRUSTFLAGS)),)
$(error Set RUST_TARGET instead of passing --target in Rust flags)
endif
endif
include $(srctree)/../../build/Build.include
quiet = $(if $(filter false,$(V)),quiet_,)
PHONY += FORCE
tool_rust_linker := $(OUTPUT)$(TOOL)-rust-linker
quiet_cmd_tool_linker = LINKER   $@
cmd_tool_linker = mkdir -p $(OUTPUT); printf '%s\n' '\#!/bin/sh' \
	'exec $(call escsq,$(CC) $(CFLAGS)) "$$@" $(call escsq,$(LDFLAGS))' > $@; chmod +x $@

$(tool_rust_linker): FORCE
	$(call if_changed,tool_linker)

quiet_cmd_tool_rust = RUSTC    $(TOOL)
cmd_tool_rust = mkdir -p $(OUTPUT); $(HOSTRUSTC) \
	$(if $(RUST_TARGET),--target=$(RUST_TARGET)) \
	$(KBUILD_HOSTRUSTFLAGS) $(HOSTRUSTFLAGS) \
	$(if $(filter true,$(DEBUG)),-Copt-level=1 -Cdebuginfo=2,-Copt-level=s -Cdebuginfo=0) \
	-Cstrip=none \
	-Clinker=$(abspath $(tool_rust_linker)) --out-dir $(OUTPUT) \
	--emit=dep-info=$(depfile),link=$@ $(TOOL_RUST_SOURCE); $(STRIPCMD) $@

$(OUTPUT)$(TOOL): $(TOOL_RUST_SOURCE) $(tool_rust_linker) FORCE
	$(call if_changed_dep,tool_rust)

-include $(OUTPUT).$(TOOL).cmd $(OUTPUT).$(TOOL)-rust-linker.cmd
else
$(OUTPUT)$(TOOL): $(toolobjs) FORCE
	$(ECHO) "  LD      " $(subst $(OUTPUT),,$@)
	$(QUIET) $(LD) $(CFLAGS) $(toolobjs) $(LDFLAGS) -L$(OUTPUT) -o $@
	$(ECHO) "  STRIP   " $(subst $(OUTPUT),,$@)
	$(QUIET) $(STRIPCMD) $@
ifneq ($(TOOL_RUST_SOURCE),)
	$(QUIET) rm -f $(OUTPUT).$(TOOL).cmd $(OUTPUT).$(TOOL).d
	$(QUIET) rm -f $(OUTPUT)$(TOOL)-rust-linker $(OUTPUT).$(TOOL)-rust-linker.cmd
endif
endif

$(KERNEL_INCLUDE):
	$(ECHO) "  MKDIR   " $(subst $(OUTPUT),,$@)
	$(QUIET) mkdir -p $(KERNEL_INCLUDE)
	$(ECHO) "  CP      " $(subst $(OUTPUT),,$@)
	$(QUIET) cp -rf $(srctree)/../../../include/acpi $(KERNEL_INCLUDE)/

$(objdir)%.o: %.c $(KERNEL_INCLUDE)
	$(ECHO) "  CC      " $(subst $(OUTPUT),,$@)
	$(QUIET) $(MKDIR) -p $(objdir) 2>/dev/null
	$(QUIET) $(CC) -c $(CFLAGS) -o $@ $<

all: $(OUTPUT)$(TOOL)
clean:
	$(ECHO) "  RMOBJ   " $(subst $(OUTPUT),,$(objdir))
	$(QUIET) find $(objdir) \( -not -type d \)\
		 -and \( -name '*~' -o -name '*.[oas]' \)\
		 -type f -print | xargs rm -f
	$(ECHO) "  RM      " $(TOOL)
	$(QUIET) rm -f $(OUTPUT)$(TOOL)
ifneq ($(TOOL_RUST_SOURCE),)
	$(QUIET) rm -f $(OUTPUT).$(TOOL).cmd $(OUTPUT).$(TOOL).d
	$(QUIET) rm -f $(OUTPUT)$(TOOL)-rust-linker $(OUTPUT).$(TOOL)-rust-linker.cmd
endif
	$(ECHO) "  RMINC   " $(subst $(OUTPUT),,$(KERNEL_INCLUDE))
	$(QUIET) rm -rf $(KERNEL_INCLUDE)

install-tools:
	$(ECHO) "  INST    " $(TOOL)
	$(QUIET) $(INSTALL) -d $(DESTDIR)$(sbindir)
	$(QUIET) $(INSTALL_PROGRAM) $(OUTPUT)$(TOOL) $(DESTDIR)$(sbindir)
uninstall-tools:
	$(ECHO) "  UNINST  " $(TOOL)
	$(QUIET) rm -f $(DESTDIR)$(sbindir)/$(TOOL)

install: all install-tools $(EXTRA_INSTALL)
uninstall: uninstall-tools $(EXTRA_UNINSTALL)

.PHONY: FORCE
