// SPDX-License-Identifier: GPL-2.0
//
// Copyright 2020 HabanaLabs, Ltd.
// All Rights Reserved.
//

// Dependencies supplied by the surrounding translation unit:
// gaudi2_masks.h, gaudi2_coresight.h, and gaudi2P.h



/* FUNNEL Offsets - same offsets for all funnels*/
pub const mmFUNNEL_CTRL_REG_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_CTRL_REG - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PRIORITY_CTRL_REG_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PRIORITY_CTRL_REG - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_ITATBDATA0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_ITATBDATA0 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_ITATBCTR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_ITATBCTR2 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_ITATBCTR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_ITATBCTR1 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_ITATBCTR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_ITATBCTR0 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_ITCTRL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_ITCTRL - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_CLAIMSET_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_CLAIMSET - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_CLAIMCLR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_CLAIMCLR - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_LOCKACCESS_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_LOCKACCESS - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_LOCKSTATUS_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_LOCKSTATUS - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_AUTHSTATUS_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_AUTHSTATUS - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_DEVID_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_DEVID - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_DEVTYPE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_DEVTYPE - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PIDR4_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PIDR4 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PERIPHID5_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PERIPHID5 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PERIPHID6_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PERIPHID6 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PERIPHID7_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PERIPHID7 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PIDR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PIDR0 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PIDR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PIDR1 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PIDR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PIDR2 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_PIDR3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_PIDR3 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_CID0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_CID0 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_CID1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_CID1 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_CID2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_CID2 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

pub const mmFUNNEL_CID3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_FUNNEL_CID3 - mmDCORE0_TPC0_EML_FUNNEL_BASE);

/* ETF Offsets - same offsets for all etfs */
pub const mmETF_RSZ_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_RSZ - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_STS_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_STS - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_RRD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_RRD - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_RRP_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_RRP - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_RWP_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_RWP - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_TRG_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_TRG - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_CTL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_CTL - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_RWD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_RWD - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_MODE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_MODE - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_LBUFLEVEL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_LBUFLEVEL - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_CBUFLEVEL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_CBUFLEVEL - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_BUFWM_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_BUFWM - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_FFSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_FFSR - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_FFCR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_FFCR - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PSCR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PSCR - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITATBMDATA0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITATBMDATA0 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITATBMCTR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITATBMCTR2 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITATBMCTR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITATBMCTR1 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITATBMCTR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITATBMCTR0 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITMISCOP0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITMISCOP0 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITTRFLIN_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITTRFLIN - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITATBDATA0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITATBDATA0 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITATBCTR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITATBCTR2 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITATBCTR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITATBCTR1 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITATBCTR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITATBCTR0 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_ITCTRL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_ITCTRL - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_CLAIMSET_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_CLAIMSET - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_CLAIMCLR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_CLAIMCLR - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_LAR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_LAR - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_LSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_LSR - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_AUTHSTATUS_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_AUTHSTATUS - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_DEVID_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_DEVID - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_DEVTYPE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_DEVTYPE - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PERIPHID4_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PERIPHID4 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PERIPHID5_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PERIPHID5 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PERIPHID6_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PERIPHID6 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PERIPHID7_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PERIPHID7 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PERIPHID0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PERIPHID0 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PERIPHID1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PERIPHID1 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PERIPHID2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PERIPHID2 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_PERIPHID3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_PERIPHID3 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_COMPID0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_COMPID0 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_COMPID1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_COMPID1 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_COMPID2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_COMPID2 - mmDCORE0_TPC0_EML_ETF_BASE);

pub const mmETF_COMPID3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_ETF_COMPID3 - mmDCORE0_TPC0_EML_ETF_BASE);


/* STM OFFSETS - same offsets for all stms */
pub const mmSTM_STMDMASTARTR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMDMASTARTR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMDMASTOPR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMDMASTOPR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMDMASTATR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMDMASTATR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMDMACTLR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMDMACTLR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMDMAIDR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMDMAIDR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMHEER_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMHEER - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMHETER_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMHETER - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMHEBSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMHEBSR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMHEMCR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMHEMCR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMHEEXTMUXR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMHEEXTMUXR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMHEMASTR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMHEMASTR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMHEFEAT1R_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMHEFEAT1R - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMHEIDR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMHEIDR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMSPER_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMSPER - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMSPTER_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMSPTER - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMSPSCR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMSPSCR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMSPMSCR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMSPMSCR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMSPOVERRIDER_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMSPOVERRIDER - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMSPMOVERRIDER_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMSPMOVERRIDER - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMSPTRIGCSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMSPTRIGCSR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMTCSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMTCSR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMTSSTIMR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMTSSTIMR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMTSFREQR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMTSFREQR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMSYNCR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMSYNCR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMAUXCR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMAUXCR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMFEAT1R_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMFEAT1R - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMFEAT2R_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMFEAT2R - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMFEAT3R_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMFEAT3R - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMITTRIGGER_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMITTRIGGER - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMITATBDATA0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMITATBDATA0 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMITATBCTR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMITATBCTR2 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMITATBID_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMITATBID - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMITATBCTR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMITATBCTR0 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMITCTRL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMITCTRL - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMCLAIMSET_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMCLAIMSET - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMCLAIMCLR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMCLAIMCLR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMLAR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMLAR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMLSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMLSR - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMAUTHSTATUS_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMAUTHSTATUS - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMDEVARCH_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMDEVARCH - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMDEVID_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMDEVID - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMDEVTYPE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMDEVTYPE - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMPIDR4_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMPIDR4 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMPIDR5_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMPIDR5 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMPIDR6_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMPIDR6 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMPIDR7_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMPIDR7 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMPIDR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMPIDR0 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMPIDR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMPIDR1 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMPIDR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMPIDR2 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMPIDR3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMPIDR3 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMCIDR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMCIDR0 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMCIDR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMCIDR1 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMCIDR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMCIDR2 - mmDCORE0_TPC0_EML_STM_BASE);

pub const mmSTM_STMCIDR3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_STM_STMCIDR3 - mmDCORE0_TPC0_EML_STM_BASE);


/* SPMU OFFSETS - same offsets for all SPMUs */
pub const mmSPMU_PMEVCNTR0_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTR0_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTR1_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTR1_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTR2_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTR2_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTR3_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTR3_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTR4_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTR4_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTR5_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTR5_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCCNTR_L_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCCNTR_L_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCCNTR_H_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCCNTR_H_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMTRC_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMTRC - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_TRC_CTRL_HOST_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_TRC_CTRL_HOST - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_TRC_STAT_HOST_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_TRC_STAT_HOST - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_TRC_EN_HOST_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_TRC_EN_HOST - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVTYPER0_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVTYPER0_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVTYPER1_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVTYPER1_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVTYPER2_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVTYPER2_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVTYPER3_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVTYPER3_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVTYPER4_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVTYPER4_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVTYPER5_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVTYPER5_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMSSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMSSR - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMOVSSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMOVSSR - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCCNTSR_L_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCCNTSR_L - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCCNTSR_H_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCCNTSR_H - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTSR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTSR0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTSR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTSR1 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTSR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTSR2 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTSR3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTSR3 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTSR4_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTSR4 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMEVCNTSR5_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMEVCNTSR5 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMSCR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMSCR - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMSRR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMSRR - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCNTENSET_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCNTENSET_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCNTENCLR_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCNTENCLR_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMINTENSET_EL1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMINTENSET_EL1 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMINTENCLR_EL1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMINTENCLR_EL1 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMOVSCLR_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMOVSCLR_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMSWINC_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMSWINC_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMOVSSET_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMOVSSET_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCFGR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCFGR - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCR_EL0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCR_EL0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMITCTRL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMITCTRL - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCLAIMSET_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCLAIMSET - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCLAIMCLR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCLAIMCLR - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMDEVAFF0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMDEVAFF0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMDEVAFF1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMDEVAFF1 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMLAR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMLAR - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMLSR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMLSR - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMAUTHSTATUS_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMAUTHSTATUS - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMDEVARCH_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMDEVARCH - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMDEVID2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMDEVID2 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMDEVID1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMDEVID1 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMDEVID_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMDEVID - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMDEVTYPE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMDEVTYPE - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMPIDR4_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMPIDR4 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMPIDR5_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMPIDR5 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMPIDR6_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMPIDR6 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMPIDR7_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMPIDR7 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMPIDR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMPIDR0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMPIDR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMPIDR1 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMPIDR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMPIDR2 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMPIDR3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMPIDR3 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCIDR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCIDR0 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCIDR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCIDR1 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCIDR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCIDR2 - mmDCORE0_TPC0_EML_SPMU_BASE);

pub const mmSPMU_PMCIDR3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_SPMU_PMCIDR3 - mmDCORE0_TPC0_EML_SPMU_BASE);


/* BMON OFFSETS - same offsets for all BMONs*/
pub const mmBMON_CR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_CR - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_RESET_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_REG_RESET - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_INT_CLR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_INT_CLR - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_TRIG_TH_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_TRIG_TH - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_S0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_S0 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_S0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_S0 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_E0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_E0 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_E0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_E0 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_S1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_S1 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_S1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_S1 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_E1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_E1 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_E1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_E1 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_S2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_S2 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_S2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_S2 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_E2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_E2 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_E2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_E2 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_S3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_S3 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_S3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_S3 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_E3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_E3 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_E3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_E3 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_REDUCTION_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_REDUCTION - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_IDL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_IDL - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_IDH_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_IDH - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_IDENL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_IDENL - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_IDENH_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_IDENH - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_LATENCY_SMP_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_LATENCY_SMP - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ATTR_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ATTR - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ATTREN_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ATTREN - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_USRENL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_USRENL - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_USRL_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_USRL - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_USRENH_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_USRENH - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_USRH_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_USRH - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_CAPTURE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_CAPTURE - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_RELEASE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_RELEASE - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_WIN_CAPTURE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_WIN_CAPTURE - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_BW_WIN_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_BW_WIN - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_MATCH_CNT_SOD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_MATCH_CNT_SOD - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_MATCH_CNT_WIN_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_MATCH_CNT_WIN - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_CYCCNT_L_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_CYCCNT_L - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_CYCCNT_H_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_CYCCNT_H - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_MAXLAT_SOD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_MAXLAT_SOD - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_MINLAT_SOD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_MINLAT_SOD - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_MAXBW_SOD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_MAXBW_SOD - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_MINBW_SOD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_MINBW_SOD - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_MAXOS_SOD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_MAXOS_SOD - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_MINOS_SOD_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_MINOS_SOD - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRL_SNAPSHOT_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRL_SNAPSHOT - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ADDRH_SNAPSHOT_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ADDRH_SNAPSHOT - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_IDL_SNAPSHOT_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_IDL_SNAPSHOT - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_IDH_SNAPSHOT_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_IDH_SNAPSHOT - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_ATTR_SNAPSHOT_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_ATTR_SNAPSHOT - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_STM_TRC_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_STM_TRC - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_STM_TRC_DROP_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_STM_TRC_DROP - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_DEVARCH_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_DEVARCH - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PMDEVID2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PMDEVID2 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PMDEVID1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PMDEVID1 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PMDEVID_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PMDEVID - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_DEVTYPE_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_DEVTYPE - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PIDR4_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PIDR4 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PIDR5_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PIDR5 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PIDR6_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PIDR6 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PIDR7_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PIDR7 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PIDR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PIDR0 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PIDR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PIDR1 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PIDR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PIDR2 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_PIDR3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_PIDR3 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_CIDR0_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_CIDR0 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_CIDR1_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_CIDR1 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_CIDR2_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_CIDR2 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);

pub const mmBMON_CIDR3_OFFSET: u64 =  (mmDCORE0_TPC0_EML_BUSMON_0_CIDR3 - mmDCORE0_TPC0_EML_BUSMON_0_BASE);


/* Coresight unlock offset */
pub const mmCORESIGHT_UNLOCK_REGISTER_OFFSET: u64 = mmSTM_STMLAR_OFFSET;
pub const mmCORESIGHT_UNLOCK_STATUS_REGISTER_OFFSET: u64 = mmSTM_STMLSR_OFFSET;



// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
