/* SPDX-License-Identifier: GPL-2.0 */

/*
 * Rust translation of the C implementation of Buchi automaton, automatically
 * generated by tools/verification/rvgen from the linear temporal logic
 * specification.
 * For further information, see kernel documentation:
 *   Documentation/trace/rv/linear_temporal_logic.rst
 */

// C dependency intent: #include <linux/rv.h>

pub const MONITOR_NAME: &str = "test_ltl_kunit";

#[repr(C)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ltl_atom {
    LTL_EVENT_A,
    LTL_EVENT_B,
    LTL_NUM_ATOM,
}

// C static_assert intent: LTL_NUM_ATOM <= RV_MAX_LTL_ATOM.

static LTL_ATOM_NAMES: [&[u8]; 2] = [b"ev_a\0", b"ev_b\0"];

pub unsafe fn ltl_atom_str(atom: ltl_atom) -> *const ::core::ffi::c_char {
    LTL_ATOM_NAMES[atom as usize].as_ptr() as *const ::core::ffi::c_char
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ltl_buchi_state {
    S0,
    S1,
    S2,
    S3,
    S4,
    RV_NUM_BA_STATES,
}

// C static_assert intent: RV_NUM_BA_STATES <= RV_MAX_BA_STATES.

#[repr(C)]
pub struct task_struct {
    _private: [u8; 0],
}

#[repr(C)]
pub struct ltl_monitor {
    pub atoms: *mut ::core::ffi::c_ulong,
    pub states: *mut ::core::ffi::c_ulong,
}

unsafe extern "C" {
    pub fn test_bit(
        nr: ::core::ffi::c_ulong,
        addr: *const ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
    pub fn __set_bit(nr: ::core::ffi::c_ulong, addr: *mut ::core::ffi::c_ulong);
}

pub unsafe fn ltl_start(_task: *mut task_struct, mon: *mut ltl_monitor) {
    let event_b: bool = unsafe {
        test_bit(
            ltl_atom::LTL_EVENT_B as ::core::ffi::c_ulong,
            (*mon).atoms as *const ::core::ffi::c_ulong,
        ) != 0
    };
    let event_a: bool = unsafe {
        test_bit(
            ltl_atom::LTL_EVENT_A as ::core::ffi::c_ulong,
            (*mon).atoms as *const ::core::ffi::c_ulong,
        ) != 0
    };
    let val1: bool = !event_a;

    if val1 {
        unsafe {
            __set_bit(
                ltl_buchi_state::S0 as ::core::ffi::c_ulong,
                (*mon).states,
            );
        }
    }
    if true {
        unsafe {
            __set_bit(
                ltl_buchi_state::S1 as ::core::ffi::c_ulong,
                (*mon).states,
            );
        }
    }
    if event_b {
        unsafe {
            __set_bit(
                ltl_buchi_state::S4 as ::core::ffi::c_ulong,
                (*mon).states,
            );
        }
    }
}

pub unsafe fn ltl_possible_next_states(
    mon: *mut ltl_monitor,
    state: ::core::ffi::c_uint,
    next: *mut ::core::ffi::c_ulong,
) {
    let event_b: bool = unsafe {
        test_bit(
            ltl_atom::LTL_EVENT_B as ::core::ffi::c_ulong,
            (*mon).atoms as *const ::core::ffi::c_ulong,
        ) != 0
    };
    let event_a: bool = unsafe {
        test_bit(
            ltl_atom::LTL_EVENT_A as ::core::ffi::c_ulong,
            (*mon).atoms as *const ::core::ffi::c_ulong,
        ) != 0
    };
    let val1: bool = !event_a;

    match state {
        x if x == ltl_buchi_state::S0 as ::core::ffi::c_uint => {
            if val1 {
                unsafe {
                    __set_bit(ltl_buchi_state::S0 as ::core::ffi::c_ulong, next);
                }
            }
            if true {
                unsafe {
                    __set_bit(ltl_buchi_state::S1 as ::core::ffi::c_ulong, next);
                }
            }
            if event_b {
                unsafe {
                    __set_bit(ltl_buchi_state::S4 as ::core::ffi::c_ulong, next);
                }
            }
        }
        x if x == ltl_buchi_state::S1 as ::core::ffi::c_uint => {
            if true {
                unsafe {
                    __set_bit(ltl_buchi_state::S1 as ::core::ffi::c_ulong, next);
                }
            }
            if true && val1 {
                unsafe {
                    __set_bit(ltl_buchi_state::S2 as ::core::ffi::c_ulong, next);
                }
            }
            if event_b && val1 {
                unsafe {
                    __set_bit(ltl_buchi_state::S3 as ::core::ffi::c_ulong, next);
                }
            }
            if event_b {
                unsafe {
                    __set_bit(ltl_buchi_state::S4 as ::core::ffi::c_ulong, next);
                }
            }
        }
        x if x == ltl_buchi_state::S2 as ::core::ffi::c_uint => {
            if true {
                unsafe {
                    __set_bit(ltl_buchi_state::S1 as ::core::ffi::c_ulong, next);
                }
            }
            if true && val1 {
                unsafe {
                    __set_bit(ltl_buchi_state::S2 as ::core::ffi::c_ulong, next);
                }
            }
            if event_b && val1 {
                unsafe {
                    __set_bit(ltl_buchi_state::S3 as ::core::ffi::c_ulong, next);
                }
            }
            if event_b {
                unsafe {
                    __set_bit(ltl_buchi_state::S4 as ::core::ffi::c_ulong, next);
                }
            }
        }
        x if x == ltl_buchi_state::S3 as ::core::ffi::c_uint => {
            if val1 {
                unsafe {
                    __set_bit(ltl_buchi_state::S0 as ::core::ffi::c_ulong, next);
                }
            }
            if true {
                unsafe {
                    __set_bit(ltl_buchi_state::S1 as ::core::ffi::c_ulong, next);
                }
            }
            if event_b {
                unsafe {
                    __set_bit(ltl_buchi_state::S4 as ::core::ffi::c_ulong, next);
                }
            }
        }
        x if x == ltl_buchi_state::S4 as ::core::ffi::c_uint => {
            if val1 {
                unsafe {
                    __set_bit(ltl_buchi_state::S0 as ::core::ffi::c_ulong, next);
                }
            }
            if true {
                unsafe {
                    __set_bit(ltl_buchi_state::S1 as ::core::ffi::c_ulong, next);
                }
            }
            if event_b {
                unsafe {
                    __set_bit(ltl_buchi_state::S4 as ::core::ffi::c_ulong, next);
                }
            }
        }
        _ => {}
    }
}
