// SPDX-License-Identifier: MIT
//
// Copyright 2024 Advanced Micro Devices, Inc.

// Dependencies supplied by other translation units: dsc.h, dsc/dscc_types.h,
// dcn20/dcn20_dsc.h, and drm/display/drm_dsc.h.

macro_rules! TO_DCN401_DSC {
    ($dsc:expr) => { container_of!($dsc, dcn401_dsc, base) };
}

macro_rules! DSC_REG_LIST_SH_MASK_DCN401 {
    ($mask_sh:expr) => {
        DSC_SF!(DSC_TOP0_DSC_TOP_CONTROL, DSC_CLOCK_EN, $mask_sh),
        DSC_SF!(DSC_TOP0_DSC_TOP_CONTROL, DSC_DISPCLK_R_GATE_DIS, $mask_sh),
        DSC_SF!(DSC_TOP0_DSC_TOP_CONTROL, DSC_DSCCLK_R_GATE_DIS, $mask_sh),
        DSC_SF!(DSC_TOP0_DSC_TOP_CONTROL, DSC_FGCG_REP_DIS, $mask_sh),
        DSC_SF!(DSC_TOP0_DSC_DEBUG_CONTROL, DSC_DBG_EN, $mask_sh),
        DSC_SF!(DSC_TOP0_DSC_DEBUG_CONTROL, DSC_TEST_CLOCK_MUX_SEL, $mask_sh),
        DSC_SF!(DSCC0_DSCC_CONFIG0, ICH_RESET_AT_END_OF_LINE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_CONFIG0, NUMBER_OF_SLICES_PER_LINE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_CONFIG0, ALTERNATE_ICH_ENCODING_EN, $mask_sh),
        DSC_SF!(DSCC0_DSCC_CONFIG0, NUMBER_OF_SLICES_IN_VERTICAL_DIRECTION, $mask_sh),
        DSC_SF!(DSCC0_DSCC_CONFIG1, DSCC_RATE_CONTROL_BUFFER_MODEL_SIZE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_STATUS, DSCC_DOUBLE_BUFFER_REG_UPDATE_PENDING, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_CLEAR0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_CLEAR1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_CLEAR2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_CLEAR3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED_INT_EN0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED_INT_EN1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED_INT_EN2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL0, DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED_INT_EN3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_END_OF_FRAME_NOT_REACHED_OCCURRED, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_OVERFLOW_CLEAR0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_OVERFLOW_CLEAR1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_OVERFLOW_CLEAR2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_OVERFLOW_CLEAR3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_UNDERFLOW_CLEAR0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_UNDERFLOW_CLEAR1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_UNDERFLOW_CLEAR2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_OUTPUT_BUFFER_UNDERFLOW_CLEAR3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_STATUS1, DSCC_END_OF_FRAME_NOT_REACHED_CLEAR, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED_INT_EN0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED_INT_EN1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED_INT_EN2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED_INT_EN3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED_INT_EN0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED_INT_EN1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED_INT_EN2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED_INT_EN3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_INTERRUPT_CONTROL1, DSCC_END_OF_FRAME_NOT_REACHED_OCCURRED_INT_EN, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG0, DSC_VERSION_MINOR, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG0, DSC_VERSION_MAJOR, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG0, PPS_IDENTIFIER, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG0, LINEBUF_DEPTH, $mask_sh),
        DSC2_SF!(DSCC0, DSCC_PPS_CONFIG0__BITS_PER_COMPONENT, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG1, BITS_PER_PIXEL, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG1, VBR_ENABLE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG1, SIMPLE_422, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG1, CONVERT_RGB, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG1, BLOCK_PRED_ENABLE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG1, NATIVE_422, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG1, NATIVE_420, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG1, CHUNK_SIZE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG2, PIC_WIDTH, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG2, PIC_HEIGHT, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG3, SLICE_WIDTH, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG3, SLICE_HEIGHT, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG4, INITIAL_XMIT_DELAY, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG4, INITIAL_DEC_DELAY, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG5, INITIAL_SCALE_VALUE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG5, SCALE_INCREMENT_INTERVAL, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG6, SCALE_DECREMENT_INTERVAL, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG6, FIRST_LINE_BPG_OFFSET, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG6, SECOND_LINE_BPG_OFFSET, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG7, NFL_BPG_OFFSET, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG7, SLICE_BPG_OFFSET, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG8, NSL_BPG_OFFSET, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG8, SECOND_LINE_OFFSET_ADJ, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG9, INITIAL_OFFSET, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG9, FINAL_OFFSET, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG10, FLATNESS_MIN_QP, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG10, FLATNESS_MAX_QP, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG10, RC_MODEL_SIZE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG11, RC_EDGE_FACTOR, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG11, RC_QUANT_INCR_LIMIT0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG11, RC_QUANT_INCR_LIMIT1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG11, RC_TGT_OFFSET_LO, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG11, RC_TGT_OFFSET_HI, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG12, RC_BUF_THRESH0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG12, RC_BUF_THRESH1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG12, RC_BUF_THRESH2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG12, RC_BUF_THRESH3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG13, RC_BUF_THRESH4, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG13, RC_BUF_THRESH5, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG13, RC_BUF_THRESH6, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG13, RC_BUF_THRESH7, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG14, RC_BUF_THRESH8, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG14, RC_BUF_THRESH9, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG14, RC_BUF_THRESH10, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG14, RC_BUF_THRESH11, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG15, RC_BUF_THRESH12, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG15, RC_BUF_THRESH13, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG15, RANGE_MIN_QP0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG15, RANGE_MAX_QP0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG15, RANGE_BPG_OFFSET0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG16, RANGE_MIN_QP1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG16, RANGE_MAX_QP1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG16, RANGE_BPG_OFFSET1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG16, RANGE_MIN_QP2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG16, RANGE_MAX_QP2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG16, RANGE_BPG_OFFSET2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG17, RANGE_MIN_QP3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG17, RANGE_MAX_QP3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG17, RANGE_BPG_OFFSET3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG17, RANGE_MIN_QP4, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG17, RANGE_MAX_QP4, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG17, RANGE_BPG_OFFSET4, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG18, RANGE_MIN_QP5, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG18, RANGE_MAX_QP5, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG18, RANGE_BPG_OFFSET5, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG18, RANGE_MIN_QP6, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG18, RANGE_MAX_QP6, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG18, RANGE_BPG_OFFSET6, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG19, RANGE_MIN_QP7, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG19, RANGE_MAX_QP7, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG19, RANGE_BPG_OFFSET7, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG19, RANGE_MIN_QP8, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG19, RANGE_MAX_QP8, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG19, RANGE_BPG_OFFSET8, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG20, RANGE_MIN_QP9, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG20, RANGE_MAX_QP9, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG20, RANGE_BPG_OFFSET9, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG20, RANGE_MIN_QP10, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG20, RANGE_MAX_QP10, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG20, RANGE_BPG_OFFSET10, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG21, RANGE_MIN_QP11, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG21, RANGE_MAX_QP11, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG21, RANGE_BPG_OFFSET11, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG21, RANGE_MIN_QP12, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG21, RANGE_MAX_QP12, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG21, RANGE_BPG_OFFSET12, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG22, RANGE_MIN_QP13, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG22, RANGE_MAX_QP13, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG22, RANGE_BPG_OFFSET13, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG22, RANGE_MIN_QP14, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG22, RANGE_MAX_QP14, $mask_sh),
        DSC_SF!(DSCC0_DSCC_PPS_CONFIG22, RANGE_BPG_OFFSET14, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MEM_POWER_CONTROL0, DSCC_DEFAULT_MEM_LOW_POWER_STATE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MEM_POWER_CONTROL0, DSCC_MEM_PWR_FORCE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MEM_POWER_CONTROL0, DSCC_MEM_PWR_DIS, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MEM_POWER_CONTROL0, DSCC_MEM_PWR_STATE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MEM_POWER_CONTROL1, DSCC_DEFAULT_MEM_LOW_POWER_STATE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MEM_POWER_CONTROL1, DSCC_MEM_PWR_FORCE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MEM_POWER_CONTROL1, DSCC_MEM_PWR_DIS, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MEM_POWER_CONTROL1, DSCC_MEM_PWR_STATE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_R_Y_SQUARED_ERROR_LOWER, DSCC_R_Y_SQUARED_ERROR_LOWER, $mask_sh),
        DSC_SF!(DSCC0_DSCC_R_Y_SQUARED_ERROR_UPPER, DSCC_R_Y_SQUARED_ERROR_UPPER, $mask_sh),
        DSC_SF!(DSCC0_DSCC_G_CB_SQUARED_ERROR_LOWER, DSCC_G_CB_SQUARED_ERROR_LOWER, $mask_sh),
        DSC_SF!(DSCC0_DSCC_G_CB_SQUARED_ERROR_UPPER, DSCC_G_CB_SQUARED_ERROR_UPPER, $mask_sh),
        DSC_SF!(DSCC0_DSCC_B_CR_SQUARED_ERROR_LOWER, DSCC_B_CR_SQUARED_ERROR_LOWER, $mask_sh),
        DSC_SF!(DSCC0_DSCC_B_CR_SQUARED_ERROR_UPPER, DSCC_B_CR_SQUARED_ERROR_UPPER, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MAX_ABS_ERROR0, DSCC_R_Y_MAX_ABS_ERROR, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MAX_ABS_ERROR0, DSCC_G_CB_MAX_ABS_ERROR, $mask_sh),
        DSC_SF!(DSCC0_DSCC_MAX_ABS_ERROR1, DSCC_B_CR_MAX_ABS_ERROR, $mask_sh),
        DSC_SF!(DSCC0_DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL0, DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL1, DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL2, DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL3, DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL0, DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL0, $mask_sh),
        DSC_SF!(DSCC0_DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL1, DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL1, $mask_sh),
        DSC_SF!(DSCC0_DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL2, DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL2, $mask_sh),
        DSC_SF!(DSCC0_DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL3, DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL3, $mask_sh),
        DSC_SF!(DSCC0_DSCC_TEST_DEBUG_BUS_ROTATE, DSCC_TEST_DEBUG_BUS0_ROTATE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_TEST_DEBUG_BUS_ROTATE, DSCC_TEST_DEBUG_BUS1_ROTATE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_TEST_DEBUG_BUS_ROTATE, DSCC_TEST_DEBUG_BUS2_ROTATE, $mask_sh),
        DSC_SF!(DSCC0_DSCC_TEST_DEBUG_BUS_ROTATE, DSCC_TEST_DEBUG_BUS3_ROTATE, $mask_sh),
        DSC_SF!(DSCCIF0_DSCCIF_CONFIG0, INPUT_PIXEL_FORMAT, $mask_sh),
        DSC2_SF!(DSCCIF0, DSCCIF_CONFIG0__BITS_PER_COMPONENT, $mask_sh),
        DSC_SF!(DSCCIF0_DSCCIF_CONFIG0, DOUBLE_BUFFER_REG_UPDATE_PENDING, $mask_sh),
        DSC_SF!(DSCRM0_DSCRM_DSC_FORWARD_CONFIG, DSCRM_DSC_FORWARD_EN, $mask_sh),
        DSC_SF!(DSCRM0_DSCRM_DSC_FORWARD_CONFIG, DSCRM_DSC_OPP_PIPE_SOURCE, $mask_sh),
        DSC_SF!(DSCRM0_DSCRM_DSC_FORWARD_CONFIG, DSCRM_DSC_FORWARD_EN_STATUS, $mask_sh)
    };
}

#[repr(C)]
pub struct dcn401_dsc_registers {
    pub DSC_TOP_CONTROL: u32, pub DSC_DEBUG_CONTROL: u32, pub DSCC_CONFIG0: u32,
    pub DSCC_CONFIG1: u32, pub DSCC_STATUS: u32, pub DSCC_INTERRUPT_CONTROL0: u32,
    pub DSCC_INTERRUPT_CONTROL1: u32, pub DSCC_INTERRUPT_STATUS0: u32,
    pub DSCC_INTERRUPT_STATUS1: u32, pub DSCC_PPS_CONFIG0: u32,
    pub DSCC_PPS_CONFIG1: u32, pub DSCC_PPS_CONFIG2: u32, pub DSCC_PPS_CONFIG3: u32,
    pub DSCC_PPS_CONFIG4: u32, pub DSCC_PPS_CONFIG5: u32, pub DSCC_PPS_CONFIG6: u32,
    pub DSCC_PPS_CONFIG7: u32, pub DSCC_PPS_CONFIG8: u32, pub DSCC_PPS_CONFIG9: u32,
    pub DSCC_PPS_CONFIG10: u32, pub DSCC_PPS_CONFIG11: u32, pub DSCC_PPS_CONFIG12: u32,
    pub DSCC_PPS_CONFIG13: u32, pub DSCC_PPS_CONFIG14: u32, pub DSCC_PPS_CONFIG15: u32,
    pub DSCC_PPS_CONFIG16: u32, pub DSCC_PPS_CONFIG17: u32, pub DSCC_PPS_CONFIG18: u32,
    pub DSCC_PPS_CONFIG19: u32, pub DSCC_PPS_CONFIG20: u32, pub DSCC_PPS_CONFIG21: u32,
    pub DSCC_PPS_CONFIG22: u32, pub DSCC_MEM_POWER_CONTROL0: u32,
    pub DSCC_MEM_POWER_CONTROL1: u32, pub DSCC_R_Y_SQUARED_ERROR_LOWER: u32,
    pub DSCC_R_Y_SQUARED_ERROR_UPPER: u32, pub DSCC_G_CB_SQUARED_ERROR_LOWER: u32,
    pub DSCC_G_CB_SQUARED_ERROR_UPPER: u32, pub DSCC_B_CR_SQUARED_ERROR_LOWER: u32,
    pub DSCC_B_CR_SQUARED_ERROR_UPPER: u32, pub DSCC_MAX_ABS_ERROR0: u32,
    pub DSCC_MAX_ABS_ERROR1: u32, pub DSCC_TEST_DEBUG_BUS_ROTATE: u32,
    pub DSCCIF_CONFIG0: u32, pub DSCRM_DSC_FORWARD_CONFIG: u32,
    pub DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL0: u32,
    pub DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL1: u32,
    pub DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL2: u32,
    pub DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL3: u32,
    pub DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL0: u32,
    pub DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL1: u32,
    pub DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL2: u32,
    pub DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL3: u32,
}

// DSC_FIELD_LIST_DCN20(type) is supplied by the dcn20 dependency.
macro_rules! DSC_FIELD_LIST_DCN401 {
    ($type:ty) => {
        DSC_FIELD_LIST_DCN20!($type);
        $type DSC_FGCG_REP_DIS;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED_INT_EN0;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED_INT_EN1;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED_INT_EN2;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED_INT_EN3;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED0;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED1;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED2;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED3;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED0;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED1;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED2;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED3;
        $type DSCC_END_OF_FRAME_NOT_REACHED_OCCURRED;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_CLEAR0;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_CLEAR1;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_CLEAR2;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_CLEAR3;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_CLEAR0;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_CLEAR1;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_CLEAR2;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_CLEAR3;
        $type DSCC_END_OF_FRAME_NOT_REACHED_CLEAR;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED0;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED1;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED2;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_OCCURRED3;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_CLEAR0;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_CLEAR1;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_CLEAR2;
        $type DSCC_RATE_CONTROL_BUFFER_MODEL_OVERFLOW_CLEAR3;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED_INT_EN0;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED_INT_EN1;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED_INT_EN2;
        $type DSCC_OUTPUT_BUFFER_OVERFLOW_OCCURRED_INT_EN3;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED_INT_EN0;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED_INT_EN1;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED_INT_EN2;
        $type DSCC_OUTPUT_BUFFER_UNDERFLOW_OCCURRED_INT_EN3;
        $type DSCC_END_OF_FRAME_NOT_REACHED_OCCURRED_INT_EN;
        $type DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL0;
        $type DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL1;
        $type DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL2;
        $type DSCC_OUTPUT_BUFFER_MAX_FULLNESS_LEVEL3;
        $type DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL0;
        $type DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL1;
        $type DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL2;
        $type DSCC_RATE_BUFFER_MODEL_MAX_FULLNESS_LEVEL3;
    };
}

#[repr(C)]
pub struct dcn401_dsc_shift { DSC_FIELD_LIST_DCN401!(u8); }

#[repr(C)]
pub struct dcn401_dsc_mask { DSC_FIELD_LIST_DCN401!(u32); }

#[repr(C)]
pub struct dcn401_dsc {
    pub base: display_stream_compressor,
    pub dsc_regs: *const dcn401_dsc_registers,
    pub dsc_shift: *const dcn401_dsc_shift,
    pub dsc_mask: *const dcn401_dsc_mask,
    pub reg_vals: dsc_reg_values,
    pub max_image_width: i32,
}

extern "C" {
    pub fn dsc401_construct(dsc: *mut dcn401_dsc, ctx: *mut dc_context, inst: i32,
        dsc_regs: *const dcn401_dsc_registers, dsc_shift: *const dcn401_dsc_shift,
        dsc_mask: *const dcn401_dsc_mask);
    pub fn dsc401_set_fgcg(dsc401: *mut dcn401_dsc, enable: bool);
    pub fn dsc401_read_state(dsc: *mut display_stream_compressor, s: *mut dcn_dsc_state);
    pub fn dsc401_validate_stream(dsc: *mut display_stream_compressor, dsc_cfg: *const dsc_config) -> bool;
    pub fn dsc401_set_config(dsc: *mut display_stream_compressor, dsc_cfg: *const dsc_config,
        dsc_optc_cfg: *mut dsc_optc_config);
    pub fn dsc401_enable(dsc: *mut display_stream_compressor, opp_pipe: i32);
    pub fn dsc401_disable(dsc: *mut display_stream_compressor);
    pub fn dsc401_disconnect(dsc: *mut display_stream_compressor);
    pub fn dsc401_wait_disconnect_pending_clear(dsc: *mut display_stream_compressor);
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
