/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/


/*
 *****************************************
 *   ARC_FARM_KDMA
 *   (Prototype: DMA_CORE)
 *****************************************
 */

/* ARC_FARM_KDMA_CFG_0 */
pub const ARC_FARM_KDMA_CFG_0_EN_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_CFG_0_EN_MASK: u32 = 0x1;

/* ARC_FARM_KDMA_CFG_1 */
pub const ARC_FARM_KDMA_CFG_1_HALT_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_CFG_1_HALT_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_CFG_1_FLUSH_SHIFT: u32 = 1;
pub const ARC_FARM_KDMA_CFG_1_FLUSH_MASK: u32 = 0x2;

/* ARC_FARM_KDMA_PROT */
pub const ARC_FARM_KDMA_PROT_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_PROT_VAL_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_PROT_ERR_VAL_SHIFT: u32 = 1;
pub const ARC_FARM_KDMA_PROT_ERR_VAL_MASK: u32 = 0x2;

/* ARC_FARM_KDMA_CKG */
pub const ARC_FARM_KDMA_CKG_HBW_RBUF_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_CKG_HBW_RBUF_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_CKG_LBW_RBUF_KDMA_SHIFT: u32 = 1;
pub const ARC_FARM_KDMA_CKG_LBW_RBUF_KDMA_MASK: u32 = 0x2;
pub const ARC_FARM_KDMA_CKG_TE_SHIFT: u32 = 2;
pub const ARC_FARM_KDMA_CKG_TE_MASK: u32 = 0x4;

/* ARC_FARM_KDMA_RD_GLBL */
pub const ARC_FARM_KDMA_RD_GLBL_LBW_VIA_HBW_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_GLBL_LBW_VIA_HBW_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_RD_GLBL_HBW_FORCE_MISS_SHIFT: u32 = 4;
pub const ARC_FARM_KDMA_RD_GLBL_HBW_FORCE_MISS_MASK: u32 = 0x10;
pub const ARC_FARM_KDMA_RD_GLBL_LBW_FORCE_MISS_SHIFT: u32 = 5;
pub const ARC_FARM_KDMA_RD_GLBL_LBW_FORCE_MISS_MASK: u32 = 0x20;

/* ARC_FARM_KDMA_RD_HBW_MAX_OUTSTAND */
pub const ARC_FARM_KDMA_RD_HBW_MAX_OUTSTAND_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_HBW_MAX_OUTSTAND_VAL_MASK: u32 = 0xFFF;

/* ARC_FARM_KDMA_RD_HBW_MAX_SIZE */
pub const ARC_FARM_KDMA_RD_HBW_MAX_SIZE_DATA_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_HBW_MAX_SIZE_DATA_MASK: u32 = 0xFFF;
pub const ARC_FARM_KDMA_RD_HBW_MAX_SIZE_MD_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_RD_HBW_MAX_SIZE_MD_MASK: u32 = 0xFFF0000;

/* ARC_FARM_KDMA_RD_HBW_ARCACHE */
pub const ARC_FARM_KDMA_RD_HBW_ARCACHE_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_HBW_ARCACHE_VAL_MASK: u32 = 0xF;

/* ARC_FARM_KDMA_RD_HBW_INFLIGHTS */
pub const ARC_FARM_KDMA_RD_HBW_INFLIGHTS_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_HBW_INFLIGHTS_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_RD_HBW_RATE_LIM_CFG */
pub const ARC_FARM_KDMA_RD_HBW_RATE_LIM_CFG_TOUT_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_HBW_RATE_LIM_CFG_TOUT_MASK: u32 = 0xFF;
pub const ARC_FARM_KDMA_RD_HBW_RATE_LIM_CFG_SAT_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_RD_HBW_RATE_LIM_CFG_SAT_MASK: u32 = 0xFF0000;
pub const ARC_FARM_KDMA_RD_HBW_RATE_LIM_CFG_EN_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_RD_HBW_RATE_LIM_CFG_EN_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_RD_LBW_MAX_OUTSTAND */
pub const ARC_FARM_KDMA_RD_LBW_MAX_OUTSTAND_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_LBW_MAX_OUTSTAND_VAL_MASK: u32 = 0xFFF;

/* ARC_FARM_KDMA_RD_LBW_MAX_SIZE */
pub const ARC_FARM_KDMA_RD_LBW_MAX_SIZE_DATA_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_LBW_MAX_SIZE_DATA_MASK: u32 = 0xFFF;
pub const ARC_FARM_KDMA_RD_LBW_MAX_SIZE_MD_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_RD_LBW_MAX_SIZE_MD_MASK: u32 = 0xFFF0000;

/* ARC_FARM_KDMA_RD_LBW_ARCACHE */
pub const ARC_FARM_KDMA_RD_LBW_ARCACHE_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_LBW_ARCACHE_VAL_MASK: u32 = 0xF;

/* ARC_FARM_KDMA_RD_LBW_INFLIGHTS */
pub const ARC_FARM_KDMA_RD_LBW_INFLIGHTS_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_LBW_INFLIGHTS_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_RD_LBW_RATE_LIM_CFG */
pub const ARC_FARM_KDMA_RD_LBW_RATE_LIM_CFG_TOUT_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_RD_LBW_RATE_LIM_CFG_TOUT_MASK: u32 = 0xFF;
pub const ARC_FARM_KDMA_RD_LBW_RATE_LIM_CFG_SAT_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_RD_LBW_RATE_LIM_CFG_SAT_MASK: u32 = 0xFF0000;
pub const ARC_FARM_KDMA_RD_LBW_RATE_LIM_CFG_EN_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_RD_LBW_RATE_LIM_CFG_EN_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_WR_HBW_MAX_OUTSTAND */
pub const ARC_FARM_KDMA_WR_HBW_MAX_OUTSTAND_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_HBW_MAX_OUTSTAND_VAL_MASK: u32 = 0xFFFF;

/* ARC_FARM_KDMA_WR_HBW_MAX_AWID */
pub const ARC_FARM_KDMA_WR_HBW_MAX_AWID_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_HBW_MAX_AWID_VAL_MASK: u32 = 0x3FFF;

/* ARC_FARM_KDMA_WR_HBW_AWCACHE */
pub const ARC_FARM_KDMA_WR_HBW_AWCACHE_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_HBW_AWCACHE_VAL_MASK: u32 = 0xF;

/* ARC_FARM_KDMA_WR_HBW_INFLIGHTS */
pub const ARC_FARM_KDMA_WR_HBW_INFLIGHTS_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_HBW_INFLIGHTS_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_WR_HBW_RATE_LIM_CFG */
pub const ARC_FARM_KDMA_WR_HBW_RATE_LIM_CFG_TOUT_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_HBW_RATE_LIM_CFG_TOUT_MASK: u32 = 0xFF;
pub const ARC_FARM_KDMA_WR_HBW_RATE_LIM_CFG_SAT_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_WR_HBW_RATE_LIM_CFG_SAT_MASK: u32 = 0xFF0000;
pub const ARC_FARM_KDMA_WR_HBW_RATE_LIM_CFG_EN_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_WR_HBW_RATE_LIM_CFG_EN_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_WR_LBW_MAX_OUTSTAND */
pub const ARC_FARM_KDMA_WR_LBW_MAX_OUTSTAND_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_LBW_MAX_OUTSTAND_VAL_MASK: u32 = 0xFFFF;

/* ARC_FARM_KDMA_WR_LBW_MAX_AWID */
pub const ARC_FARM_KDMA_WR_LBW_MAX_AWID_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_LBW_MAX_AWID_VAL_MASK: u32 = 0x7F;

/* ARC_FARM_KDMA_WR_LBW_AWCACHE */
pub const ARC_FARM_KDMA_WR_LBW_AWCACHE_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_LBW_AWCACHE_VAL_MASK: u32 = 0xF;

/* ARC_FARM_KDMA_WR_LBW_INFLIGHTS */
pub const ARC_FARM_KDMA_WR_LBW_INFLIGHTS_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_LBW_INFLIGHTS_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_WR_LBW_RATE_LIM_CFG */
pub const ARC_FARM_KDMA_WR_LBW_RATE_LIM_CFG_TOUT_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_LBW_RATE_LIM_CFG_TOUT_MASK: u32 = 0xFF;
pub const ARC_FARM_KDMA_WR_LBW_RATE_LIM_CFG_SAT_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_WR_LBW_RATE_LIM_CFG_SAT_MASK: u32 = 0xFF0000;
pub const ARC_FARM_KDMA_WR_LBW_RATE_LIM_CFG_EN_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_WR_LBW_RATE_LIM_CFG_EN_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_WR_COMP_MAX_OUTSTAND */
pub const ARC_FARM_KDMA_WR_COMP_MAX_OUTSTAND_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_COMP_MAX_OUTSTAND_VAL_MASK: u32 = 0x1F;

/* ARC_FARM_KDMA_WR_COMP_AWUSER */
pub const ARC_FARM_KDMA_WR_COMP_AWUSER_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_WR_COMP_AWUSER_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_ERR_CFG */
pub const ARC_FARM_KDMA_ERR_CFG_ERR_MSG_EN_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_ERR_CFG_ERR_MSG_EN_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_ERR_CFG_STOP_ON_ERR_SHIFT: u32 = 1;
pub const ARC_FARM_KDMA_ERR_CFG_STOP_ON_ERR_MASK: u32 = 0x2;

/* ARC_FARM_KDMA_ERR_CAUSE */
pub const ARC_FARM_KDMA_ERR_CAUSE_HBW_RD_ERR_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_ERR_CAUSE_HBW_RD_ERR_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_ERR_CAUSE_HBW_WR_ERR_SHIFT: u32 = 1;
pub const ARC_FARM_KDMA_ERR_CAUSE_HBW_WR_ERR_MASK: u32 = 0x2;
pub const ARC_FARM_KDMA_ERR_CAUSE_LBW_MSG_WR_ERR_SHIFT: u32 = 2;
pub const ARC_FARM_KDMA_ERR_CAUSE_LBW_MSG_WR_ERR_MASK: u32 = 0x4;
pub const ARC_FARM_KDMA_ERR_CAUSE_DESC_OVF_SHIFT: u32 = 3;
pub const ARC_FARM_KDMA_ERR_CAUSE_DESC_OVF_MASK: u32 = 0x8;
pub const ARC_FARM_KDMA_ERR_CAUSE_LBW_RD_ERR_SHIFT: u32 = 4;
pub const ARC_FARM_KDMA_ERR_CAUSE_LBW_RD_ERR_MASK: u32 = 0x10;
pub const ARC_FARM_KDMA_ERR_CAUSE_LBW_WR_ERR_SHIFT: u32 = 5;
pub const ARC_FARM_KDMA_ERR_CAUSE_LBW_WR_ERR_MASK: u32 = 0x20;
pub const ARC_FARM_KDMA_ERR_CAUSE_TE_DESC_FIFO_OVFL_SHIFT: u32 = 6;
pub const ARC_FARM_KDMA_ERR_CAUSE_TE_DESC_FIFO_OVFL_MASK: u32 = 0x40;
pub const ARC_FARM_KDMA_ERR_CAUSE_LIN_DMA_COMMIT_CFG_ERR_SHIFT: u32 = 7;
pub const ARC_FARM_KDMA_ERR_CAUSE_LIN_DMA_COMMIT_CFG_ERR_MASK: u32 = 0x80;

/* ARC_FARM_KDMA_ERRMSG_ADDR_LO */
pub const ARC_FARM_KDMA_ERRMSG_ADDR_LO_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_ERRMSG_ADDR_LO_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_ERRMSG_ADDR_HI */
pub const ARC_FARM_KDMA_ERRMSG_ADDR_HI_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_ERRMSG_ADDR_HI_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_ERRMSG_WDATA */
pub const ARC_FARM_KDMA_ERRMSG_WDATA_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_ERRMSG_WDATA_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS0 */
pub const ARC_FARM_KDMA_STS0_RD_REQ_CNT_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS0_RD_REQ_CNT_MASK: u32 = 0x7FFF;
pub const ARC_FARM_KDMA_STS0_WR_REQ_CNT_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_STS0_WR_REQ_CNT_MASK: u32 = 0x7FFF0000;
pub const ARC_FARM_KDMA_STS0_BUSY_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_STS0_BUSY_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_STS1 */
pub const ARC_FARM_KDMA_STS1_IS_HALT_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS1_IS_HALT_MASK: u32 = 0x1;

/* ARC_FARM_KDMA_STS_RD_CTX_SEL */
pub const ARC_FARM_KDMA_STS_RD_CTX_SEL_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_RD_CTX_SEL_VAL_MASK: u32 = 0x7;
pub const ARC_FARM_KDMA_STS_RD_CTX_SEL_STRIDE_SHIFT: u32 = 8;
pub const ARC_FARM_KDMA_STS_RD_CTX_SEL_STRIDE_MASK: u32 = 0x100;

/* ARC_FARM_KDMA_STS_RD_CTX_SIZE */
pub const ARC_FARM_KDMA_STS_RD_CTX_SIZE_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_RD_CTX_SIZE_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_RD_CTX_BASE_LO */
pub const ARC_FARM_KDMA_STS_RD_CTX_BASE_LO_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_RD_CTX_BASE_LO_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_RD_CTX_BASE_HI */
pub const ARC_FARM_KDMA_STS_RD_CTX_BASE_HI_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_RD_CTX_BASE_HI_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_RD_CTX_ID */
pub const ARC_FARM_KDMA_STS_RD_CTX_ID_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_RD_CTX_ID_VAL_MASK: u32 = 0xFFFF;

/* ARC_FARM_KDMA_STS_RD_HB_AXI_ADDR_LO */
pub const ARC_FARM_KDMA_STS_RD_HB_AXI_ADDR_LO_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_RD_HB_AXI_ADDR_LO_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_RD_HB_AXI_ADDR_HI */
pub const ARC_FARM_KDMA_STS_RD_HB_AXI_ADDR_HI_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_RD_HB_AXI_ADDR_HI_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_RD_LB_AXI_ADDR */
pub const ARC_FARM_KDMA_STS_RD_LB_AXI_ADDR_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_RD_LB_AXI_ADDR_VAL_MASK: u32 = 0x3FFFFFF;
pub const ARC_FARM_KDMA_STS_RD_LB_AXI_ADDR_RDY_SHIFT: u32 = 30;
pub const ARC_FARM_KDMA_STS_RD_LB_AXI_ADDR_RDY_MASK: u32 = 0x40000000;
pub const ARC_FARM_KDMA_STS_RD_LB_AXI_ADDR_VLD_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_STS_RD_LB_AXI_ADDR_VLD_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_STS_WR_CTX_SEL */
pub const ARC_FARM_KDMA_STS_WR_CTX_SEL_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_WR_CTX_SEL_VAL_MASK: u32 = 0x7;
pub const ARC_FARM_KDMA_STS_WR_CTX_SEL_STRIDE_SHIFT: u32 = 8;
pub const ARC_FARM_KDMA_STS_WR_CTX_SEL_STRIDE_MASK: u32 = 0x100;

/* ARC_FARM_KDMA_STS_WR_CTX_SIZE */
pub const ARC_FARM_KDMA_STS_WR_CTX_SIZE_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_WR_CTX_SIZE_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_WR_CTX_BASE_LO */
pub const ARC_FARM_KDMA_STS_WR_CTX_BASE_LO_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_WR_CTX_BASE_LO_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_WR_CTX_BASE_HI */
pub const ARC_FARM_KDMA_STS_WR_CTX_BASE_HI_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_WR_CTX_BASE_HI_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_WR_CTX_ID */
pub const ARC_FARM_KDMA_STS_WR_CTX_ID_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_WR_CTX_ID_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_LO */
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_LO_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_LO_VAL_MASK: u32 = 0x3FFFF;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_LO_RDY_SHIFT: u32 = 30;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_LO_RDY_MASK: u32 = 0x40000000;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_LO_VLD_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_LO_VLD_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_HI */
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_HI_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_HI_VAL_MASK: u32 = 0x3FFFF;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_HI_RDY_SHIFT: u32 = 30;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_HI_RDY_MASK: u32 = 0x40000000;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_HI_VLD_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_STS_WR_HB_AXI_ADDR_HI_VLD_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_STS_WR_LB_AXI_ADDR */
pub const ARC_FARM_KDMA_STS_WR_LB_AXI_ADDR_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_STS_WR_LB_AXI_ADDR_VAL_MASK: u32 = 0x3FFFFFF;
pub const ARC_FARM_KDMA_STS_WR_LB_AXI_ADDR_RDY_SHIFT: u32 = 30;
pub const ARC_FARM_KDMA_STS_WR_LB_AXI_ADDR_RDY_MASK: u32 = 0x40000000;
pub const ARC_FARM_KDMA_STS_WR_LB_AXI_ADDR_VLD_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_STS_WR_LB_AXI_ADDR_VLD_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_PWRLP_CFG */
pub const ARC_FARM_KDMA_PWRLP_CFG_GLBL_EN_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_PWRLP_CFG_GLBL_EN_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_PWRLP_CFG_CLR_SHIFT: u32 = 4;
pub const ARC_FARM_KDMA_PWRLP_CFG_CLR_MASK: u32 = 0x10;

/* ARC_FARM_KDMA_PWRLP_STS */
pub const ARC_FARM_KDMA_PWRLP_STS_RLVL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_PWRLP_STS_RLVL_MASK: u32 = 0x7F;
pub const ARC_FARM_KDMA_PWRLP_STS_WLVL_SHIFT: u32 = 8;
pub const ARC_FARM_KDMA_PWRLP_STS_WLVL_MASK: u32 = 0x7F00;
pub const ARC_FARM_KDMA_PWRLP_STS_RCNT_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_PWRLP_STS_RCNT_MASK: u32 = 0x7F0000;
pub const ARC_FARM_KDMA_PWRLP_STS_WCNT_SHIFT: u32 = 23;
pub const ARC_FARM_KDMA_PWRLP_STS_WCNT_MASK: u32 = 0x3F800000;
pub const ARC_FARM_KDMA_PWRLP_STS_RFULL_SHIFT: u32 = 30;
pub const ARC_FARM_KDMA_PWRLP_STS_RFULL_MASK: u32 = 0x40000000;
pub const ARC_FARM_KDMA_PWRLP_STS_WFULL_SHIFT: u32 = 31;
pub const ARC_FARM_KDMA_PWRLP_STS_WFULL_MASK: u32 = 0x80000000;

/* ARC_FARM_KDMA_DBG_DESC_CNT */
pub const ARC_FARM_KDMA_DBG_DESC_CNT_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_DBG_DESC_CNT_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_DBG_STS */
pub const ARC_FARM_KDMA_DBG_STS_RD_CTX_FULL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_DBG_STS_RD_CTX_FULL_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_DBG_STS_WR_CTX_FULL_SHIFT: u32 = 1;
pub const ARC_FARM_KDMA_DBG_STS_WR_CTX_FULL_MASK: u32 = 0x2;
pub const ARC_FARM_KDMA_DBG_STS_WR_COMP_FULL_SHIFT: u32 = 2;
pub const ARC_FARM_KDMA_DBG_STS_WR_COMP_FULL_MASK: u32 = 0x4;
pub const ARC_FARM_KDMA_DBG_STS_RD_CTX_EMPTY_SHIFT: u32 = 3;
pub const ARC_FARM_KDMA_DBG_STS_RD_CTX_EMPTY_MASK: u32 = 0x8;
pub const ARC_FARM_KDMA_DBG_STS_WR_CTX_EMPTY_SHIFT: u32 = 4;
pub const ARC_FARM_KDMA_DBG_STS_WR_CTX_EMPTY_MASK: u32 = 0x10;
pub const ARC_FARM_KDMA_DBG_STS_WR_COMP_EMPTY_SHIFT: u32 = 5;
pub const ARC_FARM_KDMA_DBG_STS_WR_COMP_EMPTY_MASK: u32 = 0x20;
pub const ARC_FARM_KDMA_DBG_STS_TE_EMPTY_SHIFT: u32 = 6;
pub const ARC_FARM_KDMA_DBG_STS_TE_EMPTY_MASK: u32 = 0x40;
pub const ARC_FARM_KDMA_DBG_STS_TE_BUSY_SHIFT: u32 = 7;
pub const ARC_FARM_KDMA_DBG_STS_TE_BUSY_MASK: u32 = 0x80;
pub const ARC_FARM_KDMA_DBG_STS_GSKT_EMPTY_SHIFT: u32 = 8;
pub const ARC_FARM_KDMA_DBG_STS_GSKT_EMPTY_MASK: u32 = 0x100;
pub const ARC_FARM_KDMA_DBG_STS_GSKT_FULL_SHIFT: u32 = 9;
pub const ARC_FARM_KDMA_DBG_STS_GSKT_FULL_MASK: u32 = 0x200;
pub const ARC_FARM_KDMA_DBG_STS_RD_AGU_CS_SHIFT: u32 = 10;
pub const ARC_FARM_KDMA_DBG_STS_RD_AGU_CS_MASK: u32 = 0x400;
pub const ARC_FARM_KDMA_DBG_STS_WR_AGU_CS_SHIFT: u32 = 11;
pub const ARC_FARM_KDMA_DBG_STS_WR_AGU_CS_MASK: u32 = 0x800;

/* ARC_FARM_KDMA_DBG_BUF_STS */
pub const ARC_FARM_KDMA_DBG_BUF_STS_HBW_FULLNESS_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_DBG_BUF_STS_HBW_FULLNESS_MASK: u32 = 0xFFF;
pub const ARC_FARM_KDMA_DBG_BUF_STS_LBW_FULLNESS_SHIFT: u32 = 16;
pub const ARC_FARM_KDMA_DBG_BUF_STS_LBW_FULLNESS_MASK: u32 = 0xFFF0000;

/* ARC_FARM_KDMA_DBG_RD_DESC_ID */
pub const ARC_FARM_KDMA_DBG_RD_DESC_ID_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_DBG_RD_DESC_ID_VAL_MASK: u32 = 0xFFFF;

/* ARC_FARM_KDMA_DBG_WR_DESC_ID */
pub const ARC_FARM_KDMA_DBG_WR_DESC_ID_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_DBG_WR_DESC_ID_VAL_MASK: u32 = 0xFFFF;

/* ARC_FARM_KDMA_APB_DMA_LBW_BASE */
pub const ARC_FARM_KDMA_APB_DMA_LBW_BASE_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_APB_DMA_LBW_BASE_VAL_MASK: u32 = 0xFFFF;

/* ARC_FARM_KDMA_APB_MSTR_IF_LBW_BASE */
pub const ARC_FARM_KDMA_APB_MSTR_IF_LBW_BASE_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_APB_MSTR_IF_LBW_BASE_VAL_MASK: u32 = 0xFFFF;

/* ARC_FARM_KDMA_E2E_CRED_ASYNC_CFG */
pub const ARC_FARM_KDMA_E2E_CRED_ASYNC_CFG_Y_X_FORCE_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_E2E_CRED_ASYNC_CFG_Y_X_FORCE_MASK: u32 = 0x1FF;
pub const ARC_FARM_KDMA_E2E_CRED_ASYNC_CFG_FORCE_EN_SHIFT: u32 = 9;
pub const ARC_FARM_KDMA_E2E_CRED_ASYNC_CFG_FORCE_EN_MASK: u32 = 0x200;

/* ARC_FARM_KDMA_DBG_APB_ENABLER */
pub const ARC_FARM_KDMA_DBG_APB_ENABLER_DIS_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_DBG_APB_ENABLER_DIS_MASK: u32 = 0x1;

/* ARC_FARM_KDMA_L2H_CMPR_LO */
pub const ARC_FARM_KDMA_L2H_CMPR_LO_VAL_SHIFT: u32 = 20;
pub const ARC_FARM_KDMA_L2H_CMPR_LO_VAL_MASK: u32 = 0xFFF00000;

/* ARC_FARM_KDMA_L2H_CMPR_HI */
pub const ARC_FARM_KDMA_L2H_CMPR_HI_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_L2H_CMPR_HI_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_L2H_MASK_LO */
pub const ARC_FARM_KDMA_L2H_MASK_LO_VAL_SHIFT: u32 = 20;
pub const ARC_FARM_KDMA_L2H_MASK_LO_VAL_MASK: u32 = 0xFFF00000;

/* ARC_FARM_KDMA_L2H_MASK_HI */
pub const ARC_FARM_KDMA_L2H_MASK_HI_VAL_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_L2H_MASK_HI_VAL_MASK: u32 = 0xFFFFFFFF;

/* ARC_FARM_KDMA_IDLE_IND_MASK */
pub const ARC_FARM_KDMA_IDLE_IND_MASK_DESC_SHIFT: u32 = 0;
pub const ARC_FARM_KDMA_IDLE_IND_MASK_DESC_MASK: u32 = 0x1;
pub const ARC_FARM_KDMA_IDLE_IND_MASK_COMP_SHIFT: u32 = 1;
pub const ARC_FARM_KDMA_IDLE_IND_MASK_COMP_MASK: u32 = 0x2;
pub const ARC_FARM_KDMA_IDLE_IND_MASK_INSTAGE_SHIFT: u32 = 2;
pub const ARC_FARM_KDMA_IDLE_IND_MASK_INSTAGE_MASK: u32 = 0x4;
pub const ARC_FARM_KDMA_IDLE_IND_MASK_CORE_SHIFT: u32 = 3;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
