/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

/*
 *****************************************
 *   DCORE0_SYNC_MNGR_GLBL
 *   (Prototype: SOB_GLBL)
 *****************************************
 */

/* DCORE0_SYNC_MNGR_GLBL_SM_SEI_MASK */
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_MASK_SO_OVERFLOW_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_MASK_SO_OVERFLOW_MASK: u32 = 0x1;
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_MASK_MST_UNALIGN4B_SHIFT: u32 = 1;
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_MASK_MST_UNALIGN4B_MASK: u32 = 0x2;
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_MASK_MST_RSP_ERR_SHIFT: u32 = 2;
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_MASK_MST_RSP_ERR_MASK: u32 = 0x4;

/* DCORE0_SYNC_MNGR_GLBL_SM_SEI_CAUSE */
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_CAUSE_CAUSE_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_CAUSE_CAUSE_MASK: u32 = 0x7;
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_CAUSE_LOG_SHIFT: u32 = 4;
pub const DCORE0_SYNC_MNGR_GLBL_SM_SEI_CAUSE_LOG_MASK: u32 = 0xFFFF0;

/* DCORE0_SYNC_MNGR_GLBL_L2H_CPMR_L */
pub const DCORE0_SYNC_MNGR_GLBL_L2H_CPMR_L_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_L2H_CPMR_L_VAL_MASK: u32 = 0xFFF;

/* DCORE0_SYNC_MNGR_GLBL_L2H_CPMR_H */
pub const DCORE0_SYNC_MNGR_GLBL_L2H_CPMR_H_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_L2H_CPMR_H_VAL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_L2H_MASK_L */
pub const DCORE0_SYNC_MNGR_GLBL_L2H_MASK_L_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_L2H_MASK_L_VAL_MASK: u32 = 0xFFF;

/* DCORE0_SYNC_MNGR_GLBL_L2H_MASK_H */
pub const DCORE0_SYNC_MNGR_GLBL_L2H_MASK_H_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_L2H_MASK_H_VAL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_ASID_SEC */
pub const DCORE0_SYNC_MNGR_GLBL_ASID_SEC_ASID_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_SEC_ASID_MASK: u32 = 0xFFFF;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_SEC_BP_MMU_SHIFT: u32 = 16;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_SEC_BP_MMU_MASK: u32 = 0x10000;

/* DCORE0_SYNC_MNGR_GLBL_ASID_PRIV_ONLY */
pub const DCORE0_SYNC_MNGR_GLBL_ASID_PRIV_ONLY_ASID_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_PRIV_ONLY_ASID_MASK: u32 = 0xFFFF;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_PRIV_ONLY_BP_MMU_SHIFT: u32 = 16;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_PRIV_ONLY_BP_MMU_MASK: u32 = 0x10000;

/* DCORE0_SYNC_MNGR_GLBL_LBW_DELAY */
pub const DCORE0_SYNC_MNGR_GLBL_LBW_DELAY_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_LBW_DELAY_VAL_MASK: u32 = 0xFFFF;
pub const DCORE0_SYNC_MNGR_GLBL_LBW_DELAY_EN_SHIFT: u32 = 16;
pub const DCORE0_SYNC_MNGR_GLBL_LBW_DELAY_EN_MASK: u32 = 0x10000;

/* DCORE0_SYNC_MNGR_GLBL_PI_SIZE */
pub const DCORE0_SYNC_MNGR_GLBL_PI_SIZE_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_PI_SIZE_VAL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_SOB_ONLY */
pub const DCORE0_SYNC_MNGR_GLBL_SOB_ONLY_EN_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_SOB_ONLY_EN_MASK: u32 = 0x1;

/* DCORE0_SYNC_MNGR_GLBL_CQ_INTR */
pub const DCORE0_SYNC_MNGR_GLBL_CQ_INTR_CQ_SEC_INTR_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_INTR_CQ_SEC_INTR_MASK: u32 = 0x1;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_INTR_CQ_SEC_INTR_MASK_SHIFT: u32 = 8;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_INTR_CQ_SEC_INTR_MASK_MASK: u32 = 0x100;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_INTR_CQ_INTR_QUEUE_INDEX_SHIFT: u32 = 16;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_INTR_CQ_INTR_QUEUE_INDEX_MASK: u32 = 0x3F0000;

/* DCORE0_SYNC_MNGR_GLBL_ASID_NONE_SEC_PRIV */
pub const DCORE0_SYNC_MNGR_GLBL_ASID_NONE_SEC_PRIV_ASID_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_NONE_SEC_PRIV_ASID_MASK: u32 = 0xFFFF;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_NONE_SEC_PRIV_BP_MMU_SHIFT: u32 = 16;
pub const DCORE0_SYNC_MNGR_GLBL_ASID_NONE_SEC_PRIV_BP_MMU_MASK: u32 = 0x10000;

/* DCORE0_SYNC_MNGR_GLBL_PI_INC_MODE_SIZE */
pub const DCORE0_SYNC_MNGR_GLBL_PI_INC_MODE_SIZE_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_PI_INC_MODE_SIZE_VAL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_CQ_BASE_ADDR_L */
pub const DCORE0_SYNC_MNGR_GLBL_CQ_BASE_ADDR_L_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_BASE_ADDR_L_VAL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_CQ_BASE_ADDR_H */
pub const DCORE0_SYNC_MNGR_GLBL_CQ_BASE_ADDR_H_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_BASE_ADDR_H_VAL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_CQ_SIZE_LOG2 */
pub const DCORE0_SYNC_MNGR_GLBL_CQ_SIZE_LOG2_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_SIZE_LOG2_VAL_MASK: u32 = 0xFF;

/* DCORE0_SYNC_MNGR_GLBL_CQ_PI */
pub const DCORE0_SYNC_MNGR_GLBL_CQ_PI_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_PI_VAL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_CQ_SEC */
pub const DCORE0_SYNC_MNGR_GLBL_CQ_SEC_SEC_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_SEC_SEC_MASK: u32 = 0x1;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_SEC_PRIV_SHIFT: u32 = 4;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_SEC_PRIV_MASK: u32 = 0x10;

/* DCORE0_SYNC_MNGR_GLBL_LBW_ADDR_L */
pub const DCORE0_SYNC_MNGR_GLBL_LBW_ADDR_L_ADDRL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_LBW_ADDR_L_ADDRL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_LBW_ADDR_H */
pub const DCORE0_SYNC_MNGR_GLBL_LBW_ADDR_H_ADDRH_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_LBW_ADDR_H_ADDRH_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_LBW_DATA */
pub const DCORE0_SYNC_MNGR_GLBL_LBW_DATA_VAL_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_LBW_DATA_VAL_MASK: u32 = 0xFFFFFFFF;

/* DCORE0_SYNC_MNGR_GLBL_CQ_INC_MODE */
pub const DCORE0_SYNC_MNGR_GLBL_CQ_INC_MODE_MODE_SHIFT: u32 = 0;
pub const DCORE0_SYNC_MNGR_GLBL_CQ_INC_MODE_MODE_MASK: u32 = 0x1;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
