/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2020-2023 HabanaLabs, Ltd.
 * All Rights Reserved.
 */

// C header dependencies are supplied by other translated headers.

pub const mmGIC_DISTRIBUTOR__5_GICD_SETSPI_NSR: usize = 0x4800040;
pub const mmDCORE0_TPC0_EML_CFG_DBG_CNT: usize = 0x40000;
pub const SM_OBJS_PROT_BITS_OFFS: usize = 0x14000;

macro_rules! c_offset { ($name:ident, $expr:expr) => { pub const $name: usize = $expr; }; }

c_offset!(DCORE_OFFSET, mmDCORE1_TPC0_QM_BASE - mmDCORE0_TPC0_QM_BASE);
c_offset!(DCORE_EDMA_OFFSET, mmDCORE0_EDMA1_QM_BASE - mmDCORE0_EDMA0_QM_BASE);
c_offset!(DCORE_TPC_OFFSET, mmDCORE0_TPC1_QM_BASE - mmDCORE0_TPC0_QM_BASE);
c_offset!(DCORE_DEC_OFFSET, mmDCORE0_DEC1_VSI_BASE - mmDCORE0_DEC0_VSI_BASE);
c_offset!(DCORE_HMMU_OFFSET, mmDCORE0_HMMU1_MMU_BASE - mmDCORE0_HMMU0_MMU_BASE);
c_offset!(NIC_QM_OFFSET, mmNIC0_QM1_BASE - mmNIC0_QM0_BASE);
c_offset!(PDMA_OFFSET, mmPDMA1_QM_BASE - mmPDMA0_QM_BASE);
c_offset!(ROT_OFFSET, mmROT1_BASE - mmROT0_BASE);
c_offset!(TPC_CFG_BASE_ADDRESS_HIGH_OFFSET, mmDCORE0_TPC0_CFG_CFG_BASE_ADDRESS_HIGH - mmDCORE0_TPC0_CFG_BASE);
c_offset!(TPC_CFG_SM_BASE_ADDRESS_HIGH_OFFSET, mmDCORE0_TPC0_CFG_SM_BASE_ADDRESS_HIGH - mmDCORE0_TPC0_CFG_BASE);
c_offset!(TPC_CFG_STALL_OFFSET, mmDCORE0_TPC0_CFG_TPC_STALL - mmDCORE0_TPC0_CFG_BASE);
c_offset!(TPC_CFG_STALL_ON_ERR_OFFSET, mmDCORE0_TPC0_CFG_STALL_ON_ERR - mmDCORE0_TPC0_CFG_BASE);
c_offset!(TPC_CFG_TPC_INTR_MASK_OFFSET, mmDCORE0_TPC0_CFG_TPC_INTR_MASK - mmDCORE0_TPC0_CFG_BASE);
c_offset!(TPC_CFG_MSS_CONFIG_OFFSET, mmDCORE0_TPC0_CFG_MSS_CONFIG - mmDCORE0_TPC0_CFG_BASE);
c_offset!(TPC_EML_CFG_DBG_CNT_OFFSET, mmDCORE0_TPC0_EML_CFG_DBG_CNT - mmDCORE0_TPC0_EML_CFG_BASE);
c_offset!(EDMA_CORE_CFG_STALL_OFFSET, mmDCORE0_EDMA0_CORE_CFG_1 - mmDCORE0_EDMA0_CORE_BASE);
c_offset!(MME_CTRL_LO_QM_STALL_OFFSET, mmDCORE0_MME_CTRL_LO_QM_STALL - mmDCORE0_MME_CTRL_LO_BASE);
c_offset!(MME_ACC_INTR_MASK_OFFSET, mmDCORE0_MME_ACC_INTR_MASK - mmDCORE0_MME_ACC_BASE);
c_offset!(MME_ACC_WR_AXI_AGG_COUT0_OFFSET, mmDCORE0_MME_ACC_WR_AXI_AGG_COUT0 - mmDCORE0_MME_ACC_BASE);
c_offset!(MME_ACC_WR_AXI_AGG_COUT1_OFFSET, mmDCORE0_MME_ACC_WR_AXI_AGG_COUT1 - mmDCORE0_MME_ACC_BASE);
c_offset!(MME_ACC_AP_LFSR_POLY_OFFSET, mmDCORE0_MME_ACC_AP_LFSR_POLY - mmDCORE0_MME_ACC_BASE);
c_offset!(MME_ACC_AP_LFSR_SEED_SEL_OFFSET, mmDCORE0_MME_ACC_AP_LFSR_SEED_SEL - mmDCORE0_MME_ACC_BASE);
c_offset!(MME_ACC_AP_LFSR_SEED_WDATA_OFFSET, mmDCORE0_MME_ACC_AP_LFSR_SEED_WDATA - mmDCORE0_MME_ACC_BASE);
c_offset!(DMA_CORE_CFG_0_OFFSET, mmARC_FARM_KDMA_CFG_0 - mmARC_FARM_KDMA_BASE);
c_offset!(DMA_CORE_CFG_1_OFFSET, mmARC_FARM_KDMA_CFG_1 - mmARC_FARM_KDMA_BASE);
c_offset!(DMA_CORE_PROT_OFFSET, mmARC_FARM_KDMA_PROT - mmARC_FARM_KDMA_BASE);
c_offset!(DMA_CORE_ERRMSG_ADDR_LO_OFFSET, mmARC_FARM_KDMA_ERRMSG_ADDR_LO - mmARC_FARM_KDMA_BASE);
c_offset!(DMA_CORE_ERRMSG_ADDR_HI_OFFSET, mmARC_FARM_KDMA_ERRMSG_ADDR_HI - mmARC_FARM_KDMA_BASE);
c_offset!(DMA_CORE_ERRMSG_WDATA_OFFSET, mmARC_FARM_KDMA_ERRMSG_WDATA - mmARC_FARM_KDMA_BASE);

// The remaining register offsets are retained as declarative Rust macros so
// their expressions remain dependent on the corresponding generated headers.
macro_rules! ARC_REGION_CFG_OFFSET { ($region:expr) => { mmARC_FARM_ARC0_AUX_ARC_REGION_CFG_0 + ($region * 4) - mmARC_FARM_ARC0_AUX_BASE }; }
macro_rules! MMU_OFFSET { ($reg:expr) => { $reg - mmDCORE0_HMMU0_MMU_BASE }; }
macro_rules! STLB_OFFSET { ($reg:expr) => { $reg - mmDCORE0_HMMU0_STLB_BASE }; }

macro_rules! MMU_BYPASS_OFFSET { () => { MMU_OFFSET!(mmDCORE0_HMMU0_MMU_MMU_BYPASS) }; }
macro_rules! MMU_SPI_SEI_MASK_OFFSET { () => { MMU_OFFSET!(mmDCORE0_HMMU0_MMU_SPI_SEI_MASK) }; }
macro_rules! MMU_SPI_SEI_CAUSE_OFFSET { () => { MMU_OFFSET!(mmDCORE0_HMMU0_MMU_SPI_SEI_CAUSE) }; }
macro_rules! MMU_ENABLE_OFFSET { () => { MMU_OFFSET!(mmDCORE0_HMMU0_MMU_MMU_ENABLE) }; }
macro_rules! MMU_DDR_RANGE_REG_ENABLE { () => { MMU_OFFSET!(mmDCORE0_HMMU0_MMU_DDR_RANGE_REG_ENABLE) }; }
macro_rules! MMU_INTERRUPT_CLR_OFFSET { () => { MMU_OFFSET!(mmDCORE0_HMMU0_MMU_INTERRUPT_CLR) }; }
macro_rules! STLB_BUSY_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_BUSY) }; }
macro_rules! STLB_ASID_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_ASID) }; }
macro_rules! STLB_HOP0_PA43_12_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_HOP0_PA43_12) }; }
macro_rules! STLB_HOP0_PA63_44_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_HOP0_PA63_44) }; }
macro_rules! STLB_HOP_CONFIGURATION_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_HOP_CONFIGURATION) }; }
macro_rules! STLB_INV_ALL_START_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_INV_ALL_START) }; }
macro_rules! STLB_SRAM_INIT_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_SRAM_INIT) }; }
macro_rules! STLB_RANGE_INV_START_LSB_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_RANGE_INV_START_LSB) }; }
macro_rules! STLB_RANGE_INV_START_MSB_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_RANGE_INV_START_MSB) }; }
macro_rules! STLB_RANGE_INV_END_LSB_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_RANGE_INV_END_LSB) }; }
macro_rules! STLB_RANGE_INV_END_MSB_OFFSET { () => { STLB_OFFSET!(mmDCORE0_HMMU0_STLB_RANGE_INV_END_MSB) }; }

/* RTR CTR RAZWI related offsets */
c_offset!(RTR_MSTR_IF_OFFSET, mmDCORE0_RTR0_MSTR_IF_RR_SHRD_HBW_BASE - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(RTR_LBW_MSTR_IF_OFFSET, mmSFT0_LBW_RTR_IF_MSTR_IF_RR_SHRD_HBW_BASE - mmDCORE0_RTR0_CTRL_BASE);

// RAZWI captured address and status offsets.
c_offset!(DEC_RAZWI_HBW_AW_ADDR_HI, mmDCORE0_RTR0_CTRL_DEC_RAZWI_HBW_AW_HI_ADDR - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_HBW_AW_ADDR_LO, mmDCORE0_RTR0_CTRL_DEC_RAZWI_HBW_AW_LO_ADDR - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_HBW_AW_SET, mmDCORE0_RTR0_CTRL_DEC_RAZWI_HBW_AW_SET - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_HBW_AR_ADDR_HI, mmDCORE0_RTR0_CTRL_DEC_RAZWI_HBW_AR_HI_ADDR - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_HBW_AR_ADDR_LO, mmDCORE0_RTR0_CTRL_DEC_RAZWI_HBW_AR_LO_ADDR - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_HBW_AR_SET, mmDCORE0_RTR0_CTRL_DEC_RAZWI_HBW_AR_SET - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_LBW_AW_ADDR, mmDCORE0_RTR0_CTRL_DEC_RAZWI_LBW_AW_ADDR - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_LBW_AW_SET, mmDCORE0_RTR0_CTRL_DEC_RAZWI_HBW_AW_SET - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_LBW_AR_ADDR, mmDCORE0_RTR0_CTRL_DEC_RAZWI_LBW_AR_ADDR - mmDCORE0_RTR0_CTRL_BASE);
c_offset!(DEC_RAZWI_LBW_AR_SET, mmDCORE0_RTR0_CTRL_DEC_RAZWI_LBW_AR_SET - mmDCORE0_RTR0_CTRL_BASE);

c_offset!(BRDG_CTRL_BLOCK_OFFSET, mmDCORE0_VDEC0_BRDG_CTRL_BASE - mmDCORE0_DEC0_CMD_BASE);
c_offset!(SPECIAL_BLOCK_OFFSET, mmDCORE0_VDEC0_BRDG_CTRL_SPECIAL_BASE - mmDCORE0_DEC0_CMD_BASE);
c_offset!(SFT_DCORE_OFFSET, mmSFT1_HBW_RTR_IF0_RTR_CTRL_BASE - mmSFT0_HBW_RTR_IF0_RTR_CTRL_BASE);
c_offset!(SFT_IF_OFFSET, mmSFT0_HBW_RTR_IF1_RTR_CTRL_BASE - mmSFT0_HBW_RTR_IF0_RTR_CTRL_BASE);
c_offset!(BRDG_CTRL_NRM_MSIX_LBW_AWADDR, mmDCORE0_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_AWADDR - mmDCORE0_VDEC0_BRDG_CTRL_BASE);
c_offset!(BRDG_CTRL_NRM_MSIX_LBW_WDATA, mmDCORE0_VDEC0_BRDG_CTRL_NRM_MSIX_LBW_WDATA - mmDCORE0_VDEC0_BRDG_CTRL_BASE);
c_offset!(BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR, mmDCORE0_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_AWADDR - mmDCORE0_VDEC0_BRDG_CTRL_BASE);
c_offset!(BRDG_CTRL_ABNRM_MSIX_LBW_WDATA, mmDCORE0_VDEC0_BRDG_CTRL_ABNRM_MSIX_LBW_WDATA - mmDCORE0_VDEC0_BRDG_CTRL_BASE);

c_offset!(ARC_AUX_DCCM_QUEUE_PUSH_REG_0_OFFSET, mmARC_FARM_ARC0_AUX_DCCM_QUEUE_PUSH_REG_0 - mmARC_FARM_ARC0_AUX_BASE);
c_offset!(MMU_STATIC_MULTI_PAGE_SIZE_OFFSET, mmDCORE0_HMMU0_MMU_STATIC_MULTI_PAGE_SIZE - mmDCORE0_HMMU0_MMU_BASE);
pub const HBM_MC_SPI_TEMP_PIN_CHG_MASK: usize = 1 << 0;
pub const HBM_MC_SPI_THR_ENG_MASK: usize = 1 << 1;
pub const HBM_MC_SPI_THR_DIS_ENG_MASK: usize = 1 << 2;
pub const HBM_MC_SPI_IEEE1500_COMP_MASK: usize = 1 << 3;
pub const HBM_MC_SPI_IEEE1500_PAUSED_MASK: usize = 1 << 4;
c_offset!(ARC_FARM_OFFSET, mmARC_FARM_ARC1_AUX_BASE - mmARC_FARM_ARC0_AUX_BASE);
c_offset!(NIC_OFFSET, mmNIC1_MSTR_IF_RR_SHRD_HBW_BASE - mmNIC0_MSTR_IF_RR_SHRD_HBW_BASE);
c_offset!(NIC_UMR_OFFSET, mmNIC0_UMR0_1_UNSECURE_DOORBELL0_BASE - mmNIC0_UMR0_0_UNSECURE_DOORBELL0_BASE);

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
