/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

/*
 *****************************************
 *   PDMA0_CORE_SPECIAL
 *   (Prototype: SPECIAL_REGS)
 *****************************************
 */

/* PDMA0_CORE_SPECIAL_GLBL_PRIV */
pub const PDMA0_CORE_SPECIAL_GLBL_PRIV_VAL_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_GLBL_PRIV_VAL_MASK: u32 = 0xFFFFFFFF;

/* PDMA0_CORE_SPECIAL_MEM_GW_DATA */
pub const PDMA0_CORE_SPECIAL_MEM_GW_DATA_VAL_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_GW_DATA_VAL_MASK: u32 = 0xFFFFFFFF;

/* PDMA0_CORE_SPECIAL_MEM_GW_REQ */
pub const PDMA0_CORE_SPECIAL_MEM_GW_REQ_ADDR_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_GW_REQ_ADDR_MASK: u32 = 0x3FFFFF;
pub const PDMA0_CORE_SPECIAL_MEM_GW_REQ_MID_SHIFT: u32 = 22;
pub const PDMA0_CORE_SPECIAL_MEM_GW_REQ_MID_MASK: u32 = 0x3FC00000;
pub const PDMA0_CORE_SPECIAL_MEM_GW_REQ_WNR_SHIFT: u32 = 30;
pub const PDMA0_CORE_SPECIAL_MEM_GW_REQ_WNR_MASK: u32 = 0x40000000;
pub const PDMA0_CORE_SPECIAL_MEM_GW_REQ_VLD_SHIFT: u32 = 31;
pub const PDMA0_CORE_SPECIAL_MEM_GW_REQ_VLD_MASK: u32 = 0x80000000;

/* PDMA0_CORE_SPECIAL_MEM_NUMOF */
pub const PDMA0_CORE_SPECIAL_MEM_NUMOF_VAL_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_NUMOF_VAL_MASK: u32 = 0xFF;

/* PDMA0_CORE_SPECIAL_MEM_ECC_SEL */
pub const PDMA0_CORE_SPECIAL_MEM_ECC_SEL_VAL_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_SEL_VAL_MASK: u32 = 0xFF;

/* PDMA0_CORE_SPECIAL_MEM_ECC_CTL */
pub const PDMA0_CORE_SPECIAL_MEM_ECC_CTL_SERR_INJ_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_CTL_SERR_INJ_MASK: u32 = 0x1;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_CTL_DERR_INJ_SHIFT: u32 = 1;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_CTL_DERR_INJ_MASK: u32 = 0x2;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_CTL_SERR_CLR_SHIFT: u32 = 2;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_CTL_SERR_CLR_MASK: u32 = 0x4;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_CTL_DERR_CLR_SHIFT: u32 = 3;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_CTL_DERR_CLR_MASK: u32 = 0x8;

/* PDMA0_CORE_SPECIAL_MEM_ECC_ERR_MASK */
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_MASK_SERR_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_MASK_SERR_MASK: u32 = 0x1;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_MASK_DERR_SHIFT: u32 = 1;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_MASK_DERR_MASK: u32 = 0x2;

/* PDMA0_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK */
pub const PDMA0_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK_SERR_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK_SERR_MASK: u32 = 0x1;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK_DERR_SHIFT: u32 = 1;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_GLBL_ERR_MASK_DERR_MASK: u32 = 0x2;

/* PDMA0_CORE_SPECIAL_MEM_ECC_ERR_STS */
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_STS_SYND_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_STS_SYND_MASK: u32 = 0xFFFF;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_STS_SERR_SHIFT: u32 = 16;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_STS_SERR_MASK: u32 = 0x10000;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_STS_DERR_SHIFT: u32 = 17;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_STS_DERR_MASK: u32 = 0x20000;

/* PDMA0_CORE_SPECIAL_MEM_ECC_ERR_ADDR */
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_ADDR_VAL_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_ECC_ERR_ADDR_VAL_MASK: u32 = 0xFFFF;

/* PDMA0_CORE_SPECIAL_MEM_RM */
pub const PDMA0_CORE_SPECIAL_MEM_RM_VAL_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_MEM_RM_VAL_MASK: u32 = 0x3FFFFFFF;

/* PDMA0_CORE_SPECIAL_GLBL_ERR_MASK */
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_PRIV_RD_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_PRIV_RD_MASK: u32 = 0x1;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_SEC_RD_SHIFT: u32 = 1;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_SEC_RD_MASK: u32 = 0x2;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_UNMAPPED_RD_SHIFT: u32 = 2;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_UNMAPPED_RD_MASK: u32 = 0x4;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_PRIV_WR_SHIFT: u32 = 3;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_PRIV_WR_MASK: u32 = 0x8;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_SEC_WR_SHIFT: u32 = 4;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_SEC_WR_MASK: u32 = 0x10;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_UNMAPPED_WR_SHIFT: u32 = 5;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_APB_UNMAPPED_WR_MASK: u32 = 0x20;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_EXT_SEC_WR_SHIFT: u32 = 16;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_EXT_SEC_WR_MASK: u32 = 0x10000;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_EXT_UNMAPPED_WR_SHIFT: u32 = 17;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_MASK_EXT_UNMAPPED_WR_MASK: u32 = 0x20000;

/* PDMA0_CORE_SPECIAL_GLBL_ERR_ADDR */
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_ADDR_VAL_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_ADDR_VAL_MASK: u32 = 0xFFFFFFFF;

/* PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE */
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_PRIV_RD_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_PRIV_RD_MASK: u32 = 0x1;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_SEC_RD_SHIFT: u32 = 1;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_SEC_RD_MASK: u32 = 0x2;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_UNMAPPED_RD_SHIFT: u32 = 2;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_UNMAPPED_RD_MASK: u32 = 0x4;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_PRIV_WR_SHIFT: u32 = 3;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_PRIV_WR_MASK: u32 = 0x8;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_SEC_WR_SHIFT: u32 = 4;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_SEC_WR_MASK: u32 = 0x10;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_UNMAPPED_WR_SHIFT: u32 = 5;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_APB_UNMAPPED_WR_MASK: u32 = 0x20;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_EXT_SEC_WR_SHIFT: u32 = 16;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_EXT_SEC_WR_MASK: u32 = 0x10000;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_EXT_UNMAPPED_WR_SHIFT: u32 = 17;
pub const PDMA0_CORE_SPECIAL_GLBL_ERR_CAUSE_EXT_UNMAPPED_WR_MASK: u32 = 0x20000;

/* PDMA0_CORE_SPECIAL_GLBL_SPARE */
pub const PDMA0_CORE_SPECIAL_GLBL_SPARE_R_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_GLBL_SPARE_R_MASK: u32 = 0xFFFFFFFF;

/* PDMA0_CORE_SPECIAL_GLBL_SEC */
pub const PDMA0_CORE_SPECIAL_GLBL_SEC_VAL_SHIFT: u32 = 0;
pub const PDMA0_CORE_SPECIAL_GLBL_SEC_VAL_MASK: u32 = 0xFFFFFFFF;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
