/* SPDX-License-Identifier: GPL-2.0
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

/*
 *****************************************
 *   PSOC_ETR
 *   (Prototype: ETR)
 *****************************************
 */

/* PSOC_ETR_RSZ */
pub const PSOC_ETR_RSZ_RSZ_ETR_SHIFT: u32 = 0;
pub const PSOC_ETR_RSZ_RSZ_ETR_MASK: u32 = 0x7FFFFFFF;
/* PSOC_ETR_STS */
pub const PSOC_ETR_STS_FULL_SHIFT: u32 = 0;
pub const PSOC_ETR_STS_FULL_MASK: u32 = 0x1;
pub const PSOC_ETR_STS_TRIGGERED_SHIFT: u32 = 1;
pub const PSOC_ETR_STS_TRIGGERED_MASK: u32 = 0x2;
pub const PSOC_ETR_STS_TMCREADY_SHIFT: u32 = 2;
pub const PSOC_ETR_STS_TMCREADY_MASK: u32 = 0x4;
pub const PSOC_ETR_STS_FTEMPTY_SHIFT: u32 = 3;
pub const PSOC_ETR_STS_FTEMPTY_MASK: u32 = 0x8;
pub const PSOC_ETR_STS_EMPTY_SHIFT: u32 = 4;
pub const PSOC_ETR_STS_EMPTY_MASK: u32 = 0x10;
pub const PSOC_ETR_STS_MEMERR_SHIFT: u32 = 5;
pub const PSOC_ETR_STS_MEMERR_MASK: u32 = 0x20;
/* PSOC_ETR_RRD */
pub const PSOC_ETR_RRD_RRD_SHIFT: u32 = 0;
pub const PSOC_ETR_RRD_RRD_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_RRP */
pub const PSOC_ETR_RRP_RRP_SHIFT: u32 = 0;
pub const PSOC_ETR_RRP_RRP_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_RWP */
pub const PSOC_ETR_RWP_RWP_SHIFT: u32 = 0;
pub const PSOC_ETR_RWP_RWP_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_TRG */
pub const PSOC_ETR_TRG_TRG_SHIFT: u32 = 0;
pub const PSOC_ETR_TRG_TRG_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_CTL */
pub const PSOC_ETR_CTL_TRACECAPTEN_SHIFT: u32 = 0;
pub const PSOC_ETR_CTL_TRACECAPTEN_MASK: u32 = 0x1;
/* PSOC_ETR_RWD */
pub const PSOC_ETR_RWD_RWD_SHIFT: u32 = 0;
pub const PSOC_ETR_RWD_RWD_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_MODE */
pub const PSOC_ETR_MODE_MODE_SHIFT: u32 = 0;
pub const PSOC_ETR_MODE_MODE_MASK: u32 = 0x3;
/* PSOC_ETR_LBUFLEVEL */
pub const PSOC_ETR_LBUFLEVEL_LBUFLEVEL_SHIFT: u32 = 0;
pub const PSOC_ETR_LBUFLEVEL_LBUFLEVEL_MASK: u32 = 0x7FFFFFFF;
/* PSOC_ETR_CBUFLEVEL */
pub const PSOC_ETR_CBUFLEVEL_CBUFLEVEL_SHIFT: u32 = 0;
pub const PSOC_ETR_CBUFLEVEL_CBUFLEVEL_MASK: u32 = 0x7FFFFFFF;
/* PSOC_ETR_BUFWM */
pub const PSOC_ETR_BUFWM_BUFWM_SHIFT: u32 = 0;
pub const PSOC_ETR_BUFWM_BUFWM_MASK: u32 = 0x3FFFFFFF;
/* PSOC_ETR_RRPHI */
pub const PSOC_ETR_RRPHI_RRPHI_SHIFT: u32 = 0;
pub const PSOC_ETR_RRPHI_RRPHI_MASK: u32 = 0xFF;
/* PSOC_ETR_RWPHI */
pub const PSOC_ETR_RWPHI_RWPHI_SHIFT: u32 = 0;
pub const PSOC_ETR_RWPHI_RWPHI_MASK: u32 = 0xFF;
/* PSOC_ETR_AXICTL */
pub const PSOC_ETR_AXICTL_PROTCTRLBIT0_SHIFT: u32 = 0;
pub const PSOC_ETR_AXICTL_PROTCTRLBIT0_MASK: u32 = 0x1;
pub const PSOC_ETR_AXICTL_PROTCTRLBIT1_SHIFT: u32 = 1;
pub const PSOC_ETR_AXICTL_PROTCTRLBIT1_MASK: u32 = 0x2;
pub const PSOC_ETR_AXICTL_CACHECTRLBIT0_SHIFT: u32 = 2;
pub const PSOC_ETR_AXICTL_CACHECTRLBIT0_MASK: u32 = 0x4;
pub const PSOC_ETR_AXICTL_CACHECTRLBIT1_SHIFT: u32 = 3;
pub const PSOC_ETR_AXICTL_CACHECTRLBIT1_MASK: u32 = 0x8;
pub const PSOC_ETR_AXICTL_CACHECTRLBIT2_SHIFT: u32 = 4;
pub const PSOC_ETR_AXICTL_CACHECTRLBIT2_MASK: u32 = 0x10;
pub const PSOC_ETR_AXICTL_CACHECTRLBIT3_SHIFT: u32 = 5;
pub const PSOC_ETR_AXICTL_CACHECTRLBIT3_MASK: u32 = 0x20;
pub const PSOC_ETR_AXICTL_SCATTERGATHERMODE_SHIFT: u32 = 7;
pub const PSOC_ETR_AXICTL_SCATTERGATHERMODE_MASK: u32 = 0x80;
pub const PSOC_ETR_AXICTL_WRBURSTLEN_SHIFT: u32 = 8;
pub const PSOC_ETR_AXICTL_WRBURSTLEN_MASK: u32 = 0xF00;
/* PSOC_ETR_DBALO */
pub const PSOC_ETR_DBALO_BUFADDRLO_SHIFT: u32 = 0;
pub const PSOC_ETR_DBALO_BUFADDRLO_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_DBAHI */
pub const PSOC_ETR_DBAHI_BUFADDRHI_SHIFT: u32 = 0;
pub const PSOC_ETR_DBAHI_BUFADDRHI_MASK: u32 = 0xFF;
/* PSOC_ETR_FFSR */
pub const PSOC_ETR_FFSR_FLINPROG_SHIFT: u32 = 0;
pub const PSOC_ETR_FFSR_FLINPROG_MASK: u32 = 0x1;
pub const PSOC_ETR_FFSR_FTSTOPPED_SHIFT: u32 = 1;
pub const PSOC_ETR_FFSR_FTSTOPPED_MASK: u32 = 0x2;
/* PSOC_ETR_FFCR */
pub const PSOC_ETR_FFCR_ENFT_SHIFT: u32 = 0;
pub const PSOC_ETR_FFCR_ENFT_MASK: u32 = 0x1;
pub const PSOC_ETR_FFCR_ENTI_SHIFT: u32 = 1;
pub const PSOC_ETR_FFCR_ENTI_MASK: u32 = 0x2;
pub const PSOC_ETR_FFCR_FONFLIN_SHIFT: u32 = 4;
pub const PSOC_ETR_FFCR_FONFLIN_MASK: u32 = 0x10;
pub const PSOC_ETR_FFCR_FONTRIGEVT_SHIFT: u32 = 5;
pub const PSOC_ETR_FFCR_FONTRIGEVT_MASK: u32 = 0x20;
pub const PSOC_ETR_FFCR_FLUSHMAN_SHIFT: u32 = 6;
pub const PSOC_ETR_FFCR_FLUSHMAN_MASK: u32 = 0x40;
pub const PSOC_ETR_FFCR_TRIGONTRIGIN_SHIFT: u32 = 8;
pub const PSOC_ETR_FFCR_TRIGONTRIGIN_MASK: u32 = 0x100;
pub const PSOC_ETR_FFCR_TRIGONTRIGEVT_SHIFT: u32 = 9;
pub const PSOC_ETR_FFCR_TRIGONTRIGEVT_MASK: u32 = 0x200;
pub const PSOC_ETR_FFCR_TRIGONFL_SHIFT: u32 = 10;
pub const PSOC_ETR_FFCR_TRIGONFL_MASK: u32 = 0x400;
pub const PSOC_ETR_FFCR_STOPONFL_SHIFT: u32 = 12;
pub const PSOC_ETR_FFCR_STOPONFL_MASK: u32 = 0x1000;
pub const PSOC_ETR_FFCR_STOPONTRIGEVT_SHIFT: u32 = 13;
pub const PSOC_ETR_FFCR_STOPONTRIGEVT_MASK: u32 = 0x2000;
/* PSOC_ETR_PSCR */
pub const PSOC_ETR_PSCR_PSCOUNT_SHIFT: u32 = 0;
pub const PSOC_ETR_PSCR_PSCOUNT_MASK: u32 = 0x1F;
/* PSOC_ETR_ITMISCOP0 */
pub const PSOC_ETR_ITMISCOP0_ACQCOMP_SHIFT: u32 = 0;
pub const PSOC_ETR_ITMISCOP0_ACQCOMP_MASK: u32 = 0x1;
pub const PSOC_ETR_ITMISCOP0_FULL_SHIFT: u32 = 1;
pub const PSOC_ETR_ITMISCOP0_FULL_MASK: u32 = 0x2;
/* PSOC_ETR_ITTRFLIN */
pub const PSOC_ETR_ITTRFLIN_TRIGIN_SHIFT: u32 = 0;
pub const PSOC_ETR_ITTRFLIN_TRIGIN_MASK: u32 = 0x1;
pub const PSOC_ETR_ITTRFLIN_FLUSHIN_SHIFT: u32 = 1;
pub const PSOC_ETR_ITTRFLIN_FLUSHIN_MASK: u32 = 0x2;
/* PSOC_ETR_ITATBDATA0 */
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT0_SHIFT: u32 = 0;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT0_MASK: u32 = 0x1;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT7_SHIFT: u32 = 1;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT7_MASK: u32 = 0x2;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT15_SHIFT: u32 = 2;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT15_MASK: u32 = 0x4;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT23_SHIFT: u32 = 3;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT23_MASK: u32 = 0x8;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT31_SHIFT: u32 = 4;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT31_MASK: u32 = 0x10;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT39_SHIFT: u32 = 5;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT39_MASK: u32 = 0x20;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT47_SHIFT: u32 = 6;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT47_MASK: u32 = 0x40;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT55_SHIFT: u32 = 7;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT55_MASK: u32 = 0x80;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT63_SHIFT: u32 = 8;
pub const PSOC_ETR_ITATBDATA0_ATDATASBIT63_MASK: u32 = 0x100;
/* PSOC_ETR_ITATBCTR2 */
pub const PSOC_ETR_ITATBCTR2_ATREADYS_SHIFT: u32 = 0;
pub const PSOC_ETR_ITATBCTR2_ATREADYS_MASK: u32 = 0x1;
pub const PSOC_ETR_ITATBCTR2_AFVALIDS_SHIFT: u32 = 1;
pub const PSOC_ETR_ITATBCTR2_AFVALIDS_MASK: u32 = 0x2;
pub const PSOC_ETR_ITATBCTR2_SYNCREQS_SHIFT: u32 = 2;
pub const PSOC_ETR_ITATBCTR2_SYNCREQS_MASK: u32 = 0x4;
/* PSOC_ETR_ITATBCTR1 */
pub const PSOC_ETR_ITATBCTR1_ATIDS_SHIFT: u32 = 0;
pub const PSOC_ETR_ITATBCTR1_ATIDS_MASK: u32 = 0x7F;
/* PSOC_ETR_ITATBCTR0 */
pub const PSOC_ETR_ITATBCTR0_ATVALIDS_SHIFT: u32 = 0;
pub const PSOC_ETR_ITATBCTR0_ATVALIDS_MASK: u32 = 0x1;
pub const PSOC_ETR_ITATBCTR0_AFREADYS_SHIFT: u32 = 1;
pub const PSOC_ETR_ITATBCTR0_AFREADYS_MASK: u32 = 0x2;
pub const PSOC_ETR_ITATBCTR0_ATBYTESS_SHIFT: u32 = 8;
pub const PSOC_ETR_ITATBCTR0_ATBYTESS_MASK: u32 = 0x700;
/* PSOC_ETR_ITCTRL */
pub const PSOC_ETR_ITCTRL_INTEGRATION_MODE_SHIFT: u32 = 0;
pub const PSOC_ETR_ITCTRL_INTEGRATION_MODE_MASK: u32 = 0x1;
/* PSOC_ETR_CLAIMSET */
pub const PSOC_ETR_CLAIMSET_CLAIMSET_SHIFT: u32 = 0;
pub const PSOC_ETR_CLAIMSET_CLAIMSET_MASK: u32 = 0xF;
/* PSOC_ETR_CLAIMCLR */
pub const PSOC_ETR_CLAIMCLR_CLAIMCLR_SHIFT: u32 = 0;
pub const PSOC_ETR_CLAIMCLR_CLAIMCLR_MASK: u32 = 0xF;
/* PSOC_ETR_LAR */
pub const PSOC_ETR_LAR_ACCESS_W_SHIFT: u32 = 0;
pub const PSOC_ETR_LAR_ACCESS_W_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_LSR */
pub const PSOC_ETR_LSR_LOCKEXIST_SHIFT: u32 = 0;
pub const PSOC_ETR_LSR_LOCKEXIST_MASK: u32 = 0x1;
pub const PSOC_ETR_LSR_LOCKGRANT_SHIFT: u32 = 1;
pub const PSOC_ETR_LSR_LOCKGRANT_MASK: u32 = 0x2;
pub const PSOC_ETR_LSR_LOCKTYPE_SHIFT: u32 = 2;
pub const PSOC_ETR_LSR_LOCKTYPE_MASK: u32 = 0x4;
/* PSOC_ETR_AUTHSTATUS */
pub const PSOC_ETR_AUTHSTATUS_NSID_SHIFT: u32 = 0;
pub const PSOC_ETR_AUTHSTATUS_NSID_MASK: u32 = 0x3;
pub const PSOC_ETR_AUTHSTATUS_NSNID_SHIFT: u32 = 2;
pub const PSOC_ETR_AUTHSTATUS_NSNID_MASK: u32 = 0xC;
pub const PSOC_ETR_AUTHSTATUS_SID_SHIFT: u32 = 4;
pub const PSOC_ETR_AUTHSTATUS_SID_MASK: u32 = 0x30;
pub const PSOC_ETR_AUTHSTATUS_SNID_SHIFT: u32 = 6;
pub const PSOC_ETR_AUTHSTATUS_SNID_MASK: u32 = 0xC0;
/* PSOC_ETR_DEVID */
pub const PSOC_ETR_DEVID_ATBINPORTCOUNT_SHIFT: u32 = 0;
pub const PSOC_ETR_DEVID_ATBINPORTCOUNT_MASK: u32 = 0x1F;
pub const PSOC_ETR_DEVID_CLKSCHEME_SHIFT: u32 = 5;
pub const PSOC_ETR_DEVID_CLKSCHEME_MASK: u32 = 0x20;
pub const PSOC_ETR_DEVID_CONFIGTYPE_SHIFT: u32 = 6;
pub const PSOC_ETR_DEVID_CONFIGTYPE_MASK: u32 = 0xC0;
pub const PSOC_ETR_DEVID_MEMWIDTH_SHIFT: u32 = 8;
pub const PSOC_ETR_DEVID_MEMWIDTH_MASK: u32 = 0x700;
pub const PSOC_ETR_DEVID_WBUF_DEPTH_SHIFT: u32 = 11;
pub const PSOC_ETR_DEVID_WBUF_DEPTH_MASK: u32 = 0x3800;
/* PSOC_ETR_DEVTYPE */
pub const PSOC_ETR_DEVTYPE_MAJOR_TYPE_SHIFT: u32 = 0;
pub const PSOC_ETR_DEVTYPE_MAJOR_TYPE_MASK: u32 = 0xF;
pub const PSOC_ETR_DEVTYPE_SUB_TYPE_SHIFT: u32 = 4;
pub const PSOC_ETR_DEVTYPE_SUB_TYPE_MASK: u32 = 0xF0;
/* PSOC_ETR_PERIPHID4 */
pub const PSOC_ETR_PERIPHID4_JEP106_CONT_SHIFT: u32 = 0;
pub const PSOC_ETR_PERIPHID4_JEP106_CONT_MASK: u32 = 0xF;
pub const PSOC_ETR_PERIPHID4_FOURKB_COUNT_SHIFT: u32 = 4;
pub const PSOC_ETR_PERIPHID4_FOURKB_COUNT_MASK: u32 = 0xF0;
/* PSOC_ETR_PERIPHID5 */
pub const PSOC_ETR_PERIPHID5_PERIPHID5_SHIFT: u32 = 0;
pub const PSOC_ETR_PERIPHID5_PERIPHID5_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_PERIPHID6 */
pub const PSOC_ETR_PERIPHID6_PERIPHID6_SHIFT: u32 = 0;
pub const PSOC_ETR_PERIPHID6_PERIPHID6_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_PERIPHID7 */
pub const PSOC_ETR_PERIPHID7_PERIPHID7_SHIFT: u32 = 0;
pub const PSOC_ETR_PERIPHID7_PERIPHID7_MASK: u32 = 0xFFFFFFFF;
/* PSOC_ETR_PERIPHID0 */
pub const PSOC_ETR_PERIPHID0_PART_NUMBER_BITS7TO0_SHIFT: u32 = 0;
pub const PSOC_ETR_PERIPHID0_PART_NUMBER_BITS7TO0_MASK: u32 = 0xFF;
/* PSOC_ETR_PERIPHID1 */
pub const PSOC_ETR_PERIPHID1_PART_NUMBER_BITS11TO8_SHIFT: u32 = 0;
pub const PSOC_ETR_PERIPHID1_PART_NUMBER_BITS11TO8_MASK: u32 = 0xF;
pub const PSOC_ETR_PERIPHID1_JEP106_BITS3TO0_SHIFT: u32 = 4;
pub const PSOC_ETR_PERIPHID1_JEP106_BITS3TO0_MASK: u32 = 0xF0;
/* PSOC_ETR_PERIPHID2 */
pub const PSOC_ETR_PERIPHID2_JEP106_BITS6TO4_SHIFT: u32 = 0;
pub const PSOC_ETR_PERIPHID2_JEP106_BITS6TO4_MASK: u32 = 0x7;
pub const PSOC_ETR_PERIPHID2_JEDEC_SHIFT: u32 = 3;
pub const PSOC_ETR_PERIPHID2_JEDEC_MASK: u32 = 0x8;
pub const PSOC_ETR_PERIPHID2_REVISION_SHIFT: u32 = 4;
pub const PSOC_ETR_PERIPHID2_REVISION_MASK: u32 = 0xF0;
/* PSOC_ETR_PERIPHID3 */
pub const PSOC_ETR_PERIPHID3_CUSTOMER_MODIFIED_SHIFT: u32 = 0;
pub const PSOC_ETR_PERIPHID3_CUSTOMER_MODIFIED_MASK: u32 = 0xF;
pub const PSOC_ETR_PERIPHID3_REVAND_SHIFT: u32 = 4;
pub const PSOC_ETR_PERIPHID3_REVAND_MASK: u32 = 0xF0;
/* PSOC_ETR_COMPID0 */
pub const PSOC_ETR_COMPID0_PREAMBLE_SHIFT: u32 = 0;
pub const PSOC_ETR_COMPID0_PREAMBLE_MASK: u32 = 0xFF;
/* PSOC_ETR_COMPID1 */
pub const PSOC_ETR_COMPID1_PREAMBLE_SHIFT: u32 = 0;
pub const PSOC_ETR_COMPID1_PREAMBLE_MASK: u32 = 0xF;
pub const PSOC_ETR_COMPID1_F_CLASS_SHIFT: u32 = 4;
pub const PSOC_ETR_COMPID1_F_CLASS_MASK: u32 = 0xF0;
/* PSOC_ETR_COMPID2 */
pub const PSOC_ETR_COMPID2_PREAMBLE_SHIFT: u32 = 0;
pub const PSOC_ETR_COMPID2_PREAMBLE_MASK: u32 = 0xFF;
/* PSOC_ETR_COMPID3 */
pub const PSOC_ETR_COMPID3_PREAMBLE_SHIFT: u32 = 0;
pub const PSOC_ETR_COMPID3_PREAMBLE_MASK: u32 = 0xFF;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
