// SPDX-License-Identifier: GPL-2.0-only
/*
 * OMAP4 Clock domains framework
 *
 * Copyright (C) 2009-2011 Texas Instruments, Inc.
 * Copyright (C) 2009-2011 Nokia Corporation
 *
 * Abhijit Pagare (abhijitpagare@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 * Paul Walmsley (paul@pwsan.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 */

// Dependencies supplied by the translated kernel headers:
// clockdomain.h, cm1_44xx.h, cm2_44xx.h, cm-regbits-44xx.h, prm44xx.h,
// prcm44xx.h, and prcm_mpu44xx.h.

/* Static Dependencies for OMAP4 Clock Domains */

static mut d2d_wkup_sleep_deps: [clkdm_dep; 9] = [
    clkdm_dep { clkdm_name: b"abe_clkdm\0".as_ptr() }, clkdm_dep { clkdm_name: b"ivahd_clkdm\0".as_ptr() },
    clkdm_dep { clkdm_name: b"l3_1_clkdm\0".as_ptr() }, clkdm_dep { clkdm_name: b"l3_2_clkdm\0".as_ptr() },
    clkdm_dep { clkdm_name: b"l3_emif_clkdm\0".as_ptr() }, clkdm_dep { clkdm_name: b"l3_init_clkdm\0".as_ptr() },
    clkdm_dep { clkdm_name: b"l4_cfg_clkdm\0".as_ptr() }, clkdm_dep { clkdm_name: b"l4_per_clkdm\0".as_ptr() },
    clkdm_dep { clkdm_name: core::ptr::null() },
];

macro_rules! deps { ($name:ident, [$($s:literal),* $(,)?]) => {
    static mut $name: [clkdm_dep; deps!(@n $($s),*) + 1] = [
        $(clkdm_dep { clkdm_name: concat!($s, "\0").as_ptr() },)*
        clkdm_dep { clkdm_name: core::ptr::null() },
    ];
}; (@n $($s:literal),*) => { <[()]>::len(&[$(deps!(@u $s)),*]) }; (@u $s:literal) => { () } }

deps!(ducati_wkup_sleep_deps, ["abe_clkdm", "ivahd_clkdm", "l3_1_clkdm", "l3_2_clkdm", "l3_dss_clkdm", "l3_emif_clkdm", "l3_gfx_clkdm", "l3_init_clkdm", "l4_cfg_clkdm", "l4_per_clkdm", "l4_secure_clkdm", "l4_wkup_clkdm", "tesla_clkdm"]);
deps!(iss_wkup_sleep_deps, ["ivahd_clkdm", "l3_1_clkdm", "l3_emif_clkdm"]);
deps!(ivahd_wkup_sleep_deps, ["l3_1_clkdm", "l3_emif_clkdm"]);
deps!(l3_dma_wkup_sleep_deps, ["abe_clkdm", "ducati_clkdm", "ivahd_clkdm", "l3_1_clkdm", "l3_dss_clkdm", "l3_emif_clkdm", "l3_init_clkdm", "l4_cfg_clkdm", "l4_per_clkdm", "l4_secure_clkdm", "l4_wkup_clkdm"]);
deps!(l3_dss_wkup_sleep_deps, ["ivahd_clkdm", "l3_2_clkdm", "l3_emif_clkdm"]);
deps!(l3_gfx_wkup_sleep_deps, ["ivahd_clkdm", "l3_1_clkdm", "l3_emif_clkdm"]);
deps!(l3_init_wkup_sleep_deps, ["abe_clkdm", "ivahd_clkdm", "l3_emif_clkdm", "l4_cfg_clkdm", "l4_per_clkdm", "l4_secure_clkdm", "l4_wkup_clkdm"]);
deps!(l4_secure_wkup_sleep_deps, ["l3_1_clkdm", "l3_emif_clkdm", "l4_per_clkdm"]);
deps!(mpu_wkup_sleep_deps, ["abe_clkdm", "ducati_clkdm", "ivahd_clkdm", "l3_1_clkdm", "l3_2_clkdm", "l3_dss_clkdm", "l3_emif_clkdm", "l3_gfx_clkdm", "l3_init_clkdm", "l4_cfg_clkdm", "l4_per_clkdm", "l4_secure_clkdm", "l4_wkup_clkdm", "tesla_clkdm"]);
deps!(tesla_wkup_sleep_deps, ["abe_clkdm", "ivahd_clkdm", "l3_1_clkdm", "l3_2_clkdm", "l3_emif_clkdm", "l3_init_clkdm", "l4_cfg_clkdm", "l4_per_clkdm", "l4_wkup_clkdm"]);

/* The following declarations preserve the C clockdomain objects and their
 * externally supplied constants. */

macro_rules! clkdm { ($n:ident, $name:literal, $p:literal, $part:expr, $inst:expr, $offs:expr $(, $field:ident = $val:expr)* $(,)?) => {
    static mut $n: clockdomain = clockdomain {
        name: concat!($name, "\0").as_ptr(), pwrdm: powerdomain { name: concat!($p, "\0").as_ptr() },
        prcm_partition: $part, cm_inst: $inst, clkdm_offs: $offs,
        dep_bit: 0, wkdep_srcs: core::ptr::null_mut(), sleepdep_srcs: core::ptr::null_mut(), flags: 0,
        $($field: $val,)*
    };
}; }

clkdm!(l4_cefuse_44xx_clkdm, "l4_cefuse_clkdm", "cefuse_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CEFUSE_INST, OMAP4430_CM2_CEFUSE_CEFUSE_CDOFFS, flags = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP);
clkdm!(l4_cfg_44xx_clkdm, "l4_cfg_clkdm", "core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CORE_INST, OMAP4430_CM2_CORE_L4CFG_CDOFFS, dep_bit = OMAP4430_L4CFG_STATDEP_SHIFT, flags = CLKDM_CAN_HWSUP);
clkdm!(tesla_44xx_clkdm, "tesla_clkdm", "tesla_pwrdm", OMAP4430_CM1_PARTITION, OMAP4430_CM1_TESLA_INST, OMAP4430_CM1_TESLA_TESLA_CDOFFS, dep_bit = OMAP4430_TESLA_STATDEP_SHIFT, wkdep_srcs = tesla_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = tesla_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_HWSUP_SWSUP);
clkdm!(l3_gfx_44xx_clkdm, "l3_gfx_clkdm", "gfx_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_GFX_INST, OMAP4430_CM2_GFX_GFX_CDOFFS, dep_bit = OMAP4430_GFX_STATDEP_SHIFT, wkdep_srcs = l3_gfx_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = l3_gfx_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_HWSUP_SWSUP);
clkdm!(ivahd_44xx_clkdm, "ivahd_clkdm", "ivahd_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_IVAHD_INST, OMAP4430_CM2_IVAHD_IVAHD_CDOFFS, dep_bit = OMAP4430_IVAHD_STATDEP_SHIFT, wkdep_srcs = ivahd_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = ivahd_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_HWSUP_SWSUP);
clkdm!(l4_secure_44xx_clkdm, "l4_secure_clkdm", "l4per_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_L4PER_INST, OMAP4430_CM2_L4PER_L4SEC_CDOFFS, dep_bit = OMAP4430_L4SEC_STATDEP_SHIFT, wkdep_srcs = l4_secure_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = l4_secure_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_SWSUP);
clkdm!(l4_per_44xx_clkdm, "l4_per_clkdm", "l4per_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_L4PER_INST, OMAP4430_CM2_L4PER_L4PER_CDOFFS, dep_bit = OMAP4430_L4PER_STATDEP_SHIFT, flags = CLKDM_CAN_HWSUP_SWSUP);
clkdm!(abe_44xx_clkdm, "abe_clkdm", "abe_pwrdm", OMAP4430_CM1_PARTITION, OMAP4430_CM1_ABE_INST, OMAP4430_CM1_ABE_ABE_CDOFFS, dep_bit = OMAP4430_ABE_STATDEP_SHIFT, flags = CLKDM_CAN_HWSUP_SWSUP);
clkdm!(l3_instr_44xx_clkdm, "l3_instr_clkdm", "core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CORE_INST, OMAP4430_CM2_CORE_L3INSTR_CDOFFS);
clkdm!(l3_init_44xx_clkdm, "l3_init_clkdm", "l3init_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_L3INIT_INST, OMAP4430_CM2_L3INIT_L3INIT_CDOFFS, dep_bit = OMAP4430_L3INIT_STATDEP_SHIFT, wkdep_srcs = l3_init_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = l3_init_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_HWSUP_SWSUP);
clkdm!(d2d_44xx_clkdm, "d2d_clkdm", "core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CORE_INST, OMAP4430_CM2_CORE_D2D_CDOFFS, wkdep_srcs = d2d_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = d2d_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP);
clkdm!(mpu0_44xx_clkdm, "mpu0_clkdm", "cpu0_pwrdm", OMAP4430_PRCM_MPU_PARTITION, OMAP4430_PRCM_MPU_CPU0_INST, OMAP4430_PRCM_MPU_CPU0_CPU0_CDOFFS, flags = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP);
clkdm!(mpu1_44xx_clkdm, "mpu1_clkdm", "cpu1_pwrdm", OMAP4430_PRCM_MPU_PARTITION, OMAP4430_PRCM_MPU_CPU1_INST, OMAP4430_PRCM_MPU_CPU1_CPU1_CDOFFS, flags = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP);
clkdm!(l3_emif_44xx_clkdm, "l3_emif_clkdm", "core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CORE_INST, OMAP4430_CM2_CORE_MEMIF_CDOFFS, dep_bit = OMAP4430_MEMIF_STATDEP_SHIFT, flags = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP);
clkdm!(l4_ao_44xx_clkdm, "l4_ao_clkdm", "always_on_core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_ALWAYS_ON_INST, OMAP4430_CM2_ALWAYS_ON_ALWON_CDOFFS, flags = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP);
clkdm!(ducati_44xx_clkdm, "ducati_clkdm", "core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CORE_INST, OMAP4430_CM2_CORE_DUCATI_CDOFFS, dep_bit = OMAP4430_DUCATI_STATDEP_SHIFT, wkdep_srcs = ducati_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = ducati_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_HWSUP_SWSUP);
clkdm!(mpu_44xx_clkdm, "mpuss_clkdm", "mpu_pwrdm", OMAP4430_CM1_PARTITION, OMAP4430_CM1_MPU_INST, OMAP4430_CM1_MPU_MPU_CDOFFS, wkdep_srcs = mpu_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = mpu_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP);
clkdm!(l3_2_44xx_clkdm, "l3_2_clkdm", "core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CORE_INST, OMAP4430_CM2_CORE_L3_2_CDOFFS, dep_bit = OMAP4430_L3_2_STATDEP_SHIFT, flags = CLKDM_CAN_HWSUP);
clkdm!(l3_1_44xx_clkdm, "l3_1_clkdm", "core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CORE_INST, OMAP4430_CM2_CORE_L3_1_CDOFFS, dep_bit = OMAP4430_L3_1_STATDEP_SHIFT, flags = CLKDM_CAN_HWSUP);
clkdm!(iss_44xx_clkdm, "iss_clkdm", "cam_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CAM_INST, OMAP4430_CM2_CAM_CAM_CDOFFS, wkdep_srcs = iss_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = iss_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_SWSUP);
clkdm!(l3_dss_44xx_clkdm, "l3_dss_clkdm", "dss_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_DSS_INST, OMAP4430_CM2_DSS_DSS_CDOFFS, dep_bit = OMAP4430_DSS_STATDEP_SHIFT, wkdep_srcs = l3_dss_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = l3_dss_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_HWSUP_SWSUP);
clkdm!(l4_wkup_44xx_clkdm, "l4_wkup_clkdm", "wkup_pwrdm", OMAP4430_PRM_PARTITION, OMAP4430_PRM_WKUP_CM_INST, OMAP4430_PRM_WKUP_CM_WKUP_CDOFFS, dep_bit = OMAP4430_L4WKUP_STATDEP_SHIFT, flags = CLKDM_CAN_HWSUP | CLKDM_ACTIVE_WITH_MPU);
clkdm!(emu_sys_44xx_clkdm, "emu_sys_clkdm", "emu_pwrdm", OMAP4430_PRM_PARTITION, OMAP4430_PRM_EMU_CM_INST, OMAP4430_PRM_EMU_CM_EMU_CDOFFS, flags = CLKDM_CAN_ENABLE_AUTO | CLKDM_CAN_FORCE_WAKEUP | CLKDM_MISSING_IDLE_REPORTING);
clkdm!(l3_dma_44xx_clkdm, "l3_dma_clkdm", "core_pwrdm", OMAP4430_CM2_PARTITION, OMAP4430_CM2_CORE_INST, OMAP4430_CM2_CORE_SDMA_CDOFFS, wkdep_srcs = l3_dma_wkup_sleep_deps.as_mut_ptr(), sleepdep_srcs = l3_dma_wkup_sleep_deps.as_mut_ptr(), flags = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP);

/* As clockdomains are added or removed above, this list must also be changed */
static mut clockdomains_omap44xx: [*mut clockdomain; 25] = [
    &raw mut l4_cefuse_44xx_clkdm, &raw mut l4_cfg_44xx_clkdm, &raw mut tesla_44xx_clkdm,
    &raw mut l3_gfx_44xx_clkdm, &raw mut ivahd_44xx_clkdm, &raw mut l4_secure_44xx_clkdm,
    &raw mut l4_per_44xx_clkdm, &raw mut abe_44xx_clkdm, &raw mut l3_instr_44xx_clkdm,
    &raw mut l3_init_44xx_clkdm, &raw mut d2d_44xx_clkdm, &raw mut mpu0_44xx_clkdm,
    &raw mut mpu1_44xx_clkdm, &raw mut l3_emif_44xx_clkdm, &raw mut l4_ao_44xx_clkdm,
    &raw mut ducati_44xx_clkdm, &raw mut mpu_44xx_clkdm, &raw mut l3_2_44xx_clkdm,
    &raw mut l3_1_44xx_clkdm, &raw mut iss_44xx_clkdm, &raw mut l3_dss_44xx_clkdm,
    &raw mut l4_wkup_44xx_clkdm, &raw mut emu_sys_44xx_clkdm, &raw mut l3_dma_44xx_clkdm,
    core::ptr::null_mut(),
];

pub unsafe fn omap44xx_clockdomains_init() {
    clkdm_register_platform_funcs(&omap4_clkdm_operations);
    clkdm_register_clkdms(clockdomains_omap44xx.as_mut_ptr());
    clkdm_complete_init();
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
