/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * AM33XX Power Management register bits
 *
 * This file is automatically generated from the AM33XX hardware databases.
 * Vaibhav Hiremath <hvaibhav@ti.com>
 *
 * Copyright (C) 2011-2012 Texas Instruments Incorporated - https://www.ti.com/
 */

// Translated from the C header __ARCH_ARM_MACH_OMAP2_CM_REGBITS_33XX_H.

pub const AM33XX_CLKOUT2DIV_SHIFT: u32 = 3;
pub const AM33XX_CLKOUT2DIV_WIDTH: u32 = 3;
pub const AM33XX_CLKOUT2EN_SHIFT: u32 = 7;
pub const AM33XX_CLKOUT2SOURCE_MASK: u32 = 0x7 << 0;
pub const AM33XX_CLKSEL_0_0_SHIFT: u32 = 0;
pub const AM33XX_CLKSEL_0_0_WIDTH: u32 = 1;
pub const AM33XX_CLKSEL_0_0_MASK: u32 = 1 << 0;
pub const AM33XX_CLKSEL_0_1_MASK: u32 = 3 << 0;
pub const AM33XX_CLKSEL_0_2_MASK: u32 = 7 << 0;
pub const AM33XX_CLKSEL_GFX_FCLK_MASK: u32 = 1 << 1;
pub const AM33XX_CLKTRCTRL_SHIFT: u32 = 0;
pub const AM33XX_CLKTRCTRL_MASK: u32 = 0x3 << 0;
pub const AM33XX_DPLL_CLKOUT_DIV_SHIFT: u32 = 0;
pub const AM33XX_DPLL_CLKOUT_DIV_WIDTH: u32 = 5;
pub const AM33XX_DPLL_DIV_MASK: u32 = 0x7f << 0;
pub const AM33XX_DPLL_PER_DIV_MASK: u32 = 0xff << 0;
pub const AM33XX_DPLL_EN_MASK: u32 = 0x7 << 0;
pub const AM33XX_DPLL_MULT_MASK: u32 = 0x7ff << 8;
pub const AM33XX_DPLL_MULT_PERIPH_MASK: u32 = 0xfff << 8;
pub const AM33XX_HSDIVIDER_CLKOUT1_DIV_SHIFT: u32 = 0;
pub const AM33XX_HSDIVIDER_CLKOUT1_DIV_WIDTH: u32 = 5;
pub const AM33XX_HSDIVIDER_CLKOUT2_DIV_SHIFT: u32 = 0;
pub const AM33XX_HSDIVIDER_CLKOUT2_DIV_WIDTH: u32 = 5;
pub const AM33XX_HSDIVIDER_CLKOUT3_DIV_SHIFT: u32 = 0;
pub const AM33XX_HSDIVIDER_CLKOUT3_DIV_WIDTH: u32 = 5;
pub const AM33XX_IDLEST_SHIFT: u32 = 16;
pub const AM33XX_IDLEST_MASK: u32 = 0x3 << 16;
pub const AM33XX_MODULEMODE_SHIFT: u32 = 0;
pub const AM33XX_MODULEMODE_MASK: u32 = 0x3 << 0;
pub const AM33XX_OPTCLK_DEBUG_CLKA_SHIFT: u32 = 30;
pub const AM33XX_OPTFCLKEN_DBGSYSCLK_SHIFT: u32 = 19;
pub const AM33XX_OPTFCLKEN_GPIO0_GDBCLK_SHIFT: u32 = 18;
pub const AM33XX_OPTFCLKEN_GPIO_1_GDBCLK_SHIFT: u32 = 18;
pub const AM33XX_OPTFCLKEN_GPIO_2_GDBCLK_SHIFT: u32 = 18;
pub const AM33XX_OPTFCLKEN_GPIO_3_GDBCLK_SHIFT: u32 = 18;
pub const AM33XX_STM_PMD_CLKDIVSEL_SHIFT: u32 = 27;
pub const AM33XX_STM_PMD_CLKDIVSEL_WIDTH: u32 = 3;
pub const AM33XX_STM_PMD_CLKSEL_SHIFT: u32 = 22;
pub const AM33XX_STM_PMD_CLKSEL_WIDTH: u32 = 2;
pub const AM33XX_ST_DPLL_CLK_MASK: u32 = 1 << 0;
pub const AM33XX_ST_DPLL_CLKDCOLDO_SHIFT: u32 = 8;
pub const AM33XX_TRC_PMD_CLKDIVSEL_SHIFT: u32 = 24;
pub const AM33XX_TRC_PMD_CLKDIVSEL_WIDTH: u32 = 3;
pub const AM33XX_TRC_PMD_CLKSEL_SHIFT: u32 = 20;
pub const AM33XX_TRC_PMD_CLKSEL_WIDTH: u32 = 2;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
