/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * OMAP44xx Clock Management register bits
 *
 * Copyright (C) 2009-2012 Texas Instruments, Inc.
 * Copyright (C) 2009-2010 Nokia Corporation
 *
 * Paul Walmsley (paul@pwsan.com)
 * Rajendra Nayak (rnayak@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 */

pub const OMAP4430_ABE_STATDEP_SHIFT: u32 = 3;
pub const OMAP4430_CLKTRCTRL_SHIFT: u32 = 0;
pub const OMAP4430_CLKTRCTRL_MASK: u32 = 0x3 << 0;
pub const OMAP4430_DSS_STATDEP_SHIFT: u32 = 8;
pub const OMAP4430_DUCATI_STATDEP_SHIFT: u32 = 0;
pub const OMAP4430_GFX_STATDEP_SHIFT: u32 = 10;
pub const OMAP4430_IDLEST_SHIFT: u32 = 16;
pub const OMAP4430_IDLEST_MASK: u32 = 0x3 << 16;
pub const OMAP4430_IVAHD_STATDEP_SHIFT: u32 = 2;
pub const OMAP4430_L3INIT_STATDEP_SHIFT: u32 = 7;
pub const OMAP4430_L3_1_STATDEP_SHIFT: u32 = 5;
pub const OMAP4430_L3_2_STATDEP_SHIFT: u32 = 6;
pub const OMAP4430_L4CFG_STATDEP_SHIFT: u32 = 12;
pub const OMAP4430_L4PER_STATDEP_SHIFT: u32 = 13;
pub const OMAP4430_L4SEC_STATDEP_SHIFT: u32 = 14;
pub const OMAP4430_L4WKUP_STATDEP_SHIFT: u32 = 15;
pub const OMAP4430_MEMIF_STATDEP_SHIFT: u32 = 4;
pub const OMAP4430_MODULEMODE_SHIFT: u32 = 0;
pub const OMAP4430_MODULEMODE_MASK: u32 = 0x3 << 0;
pub const OMAP4430_TESLA_STATDEP_SHIFT: u32 = 1;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
