/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * OMAP54xx PRCM MPU instance offset macros
 *
 * Copyright (C) 2013 Texas Instruments Incorporated - https://www.ti.com
 *
 * Paul Walmsley (paul@pwsan.com)
 * Rajendra Nayak (rnayak@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 */

// Dependencies supplied by `prcm_mpu_44xx_54xx.h` and `common.h` remain
// external to this translation.

pub const OMAP54XX_PRCM_MPU_BASE: u32 = 0x4824_3000;

#[macro_export]
macro_rules! OMAP54XX_PRCM_MPU_REGADDR {
    ($inst:expr, $reg:expr) => {
        OMAP2_L4_IO_ADDRESS!(OMAP54XX_PRCM_MPU_BASE + ($inst) + ($reg))
    };
}

/* PRCM_MPU instances */
pub const OMAP54XX_PRCM_MPU_OCP_SOCKET_INST: u32 = 0x0000;
pub const OMAP54XX_PRCM_MPU_DEVICE_INST: u32 = 0x0200;
pub const OMAP54XX_PRCM_MPU_PRM_C0_INST: u32 = 0x0400;
pub const OMAP54XX_PRCM_MPU_CM_C0_INST: u32 = 0x0600;
pub const OMAP54XX_PRCM_MPU_PRM_C1_INST: u32 = 0x0800;
pub const OMAP54XX_PRCM_MPU_CM_C1_INST: u32 = 0x0a00;

/* PRCM_MPU clockdomain register offsets (from instance start) */
pub const OMAP54XX_PRCM_MPU_CM_C0_CPU0_CDOFFS: u32 = 0x0000;
pub const OMAP54XX_PRCM_MPU_CM_C1_CPU1_CDOFFS: u32 = 0x0000;

/*
 * PRCM_MPU
 *
 * The PRCM_MPU is a local PRCM inside the MPU subsystem. For the PRCM (global)
 * point of view the PRCM_MPU is a single entity. It shares the same
 * programming model as the global PRCM and thus can be assimilate as two new
 * MOD inside the PRCM
 */

/* PRCM_MPU.PRCM_MPU_OCP_SOCKET register offsets */
pub const OMAP54XX_REVISION_PRCM_MPU_OFFSET: u32 = 0x0000;

/* PRCM_MPU.PRCM_MPU_DEVICE register offsets */
pub const OMAP54XX_PRCM_MPU_PRM_RSTST_OFFSET: u32 = 0x0000;
pub const OMAP54XX_PRCM_MPU_PRM_PSCON_COUNT_OFFSET: u32 = 0x0004;
pub const OMAP54XX_PRM_FRAC_INCREMENTER_NUMERATOR_OFFSET: u32 = 0x0010;
pub const OMAP54XX_PRM_FRAC_INCREMENTER_DENUMERATOR_RELOAD_OFFSET: u32 = 0x0014;

/* PRCM_MPU.PRCM_MPU_PRM_C0 register offsets */
pub const OMAP54XX_PM_CPU0_PWRSTCTRL_OFFSET: u32 = 0x0000;
pub const OMAP54XX_PM_CPU0_PWRSTST_OFFSET: u32 = 0x0004;
pub const OMAP54XX_RM_CPU0_CPU0_RSTCTRL_OFFSET: u32 = 0x0010;
pub const OMAP54XX_RM_CPU0_CPU0_RSTST_OFFSET: u32 = 0x0014;
pub const OMAP54XX_RM_CPU0_CPU0_CONTEXT_OFFSET: u32 = 0x0024;

/* PRCM_MPU.PRCM_MPU_CM_C0 register offsets */
pub const OMAP54XX_CM_CPU0_CLKSTCTRL_OFFSET: u32 = 0x0000;
pub const OMAP54XX_CM_CPU0_CPU0_CLKCTRL_OFFSET: u32 = 0x0020;
pub const OMAP54XX_CM_CPU0_CPU0_CLKCTRL: _ = OMAP54XX_PRCM_MPU_REGADDR!(OMAP54XX_PRCM_MPU_CM_C0_INST, 0x0020);

/* PRCM_MPU.PRCM_MPU_PRM_C1 register offsets */
pub const OMAP54XX_PM_CPU1_PWRSTCTRL_OFFSET: u32 = 0x0000;
pub const OMAP54XX_PM_CPU1_PWRSTST_OFFSET: u32 = 0x0004;
pub const OMAP54XX_RM_CPU1_CPU1_RSTCTRL_OFFSET: u32 = 0x0010;
pub const OMAP54XX_RM_CPU1_CPU1_RSTST_OFFSET: u32 = 0x0014;
pub const OMAP54XX_RM_CPU1_CPU1_CONTEXT_OFFSET: u32 = 0x0024;

/* PRCM_MPU.PRCM_MPU_CM_C1 register offsets */
pub const OMAP54XX_CM_CPU1_CLKSTCTRL_OFFSET: u32 = 0x0000;
pub const OMAP54XX_CM_CPU1_CPU1_CLKCTRL_OFFSET: u32 = 0x0020;
pub const OMAP54XX_CM_CPU1_CPU1_CLKCTRL: _ = OMAP54XX_PRCM_MPU_REGADDR!(OMAP54XX_PRCM_MPU_CM_C1_INST, 0x0020);

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
