/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * OMAP44xx and 54xx PRM common functions
 *
 * Copyright (C) 2009-2013 Texas Instruments, Inc.
 * Copyright (C) 2009-2010 Nokia Corporation
 *
 * Paul Walmsley (paul@pwsan.com)
 * Rajendra Nayak (rnayak@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 */

/* Dependency supplied by the surrounding translated code: prcm-common.h. */

/* Function prototypes */
/* C header condition: these declarations are omitted for assembler builds. */
extern "C" {
    /*
     * OMAP4/OMAP5 access functions for voltage controller (VC) and
     * voltage proccessor (VP) in the PRM.
     */
    pub fn omap4_prm_vcvp_read(offset: u8) -> u32;
    pub fn omap4_prm_vcvp_write(val: u32, offset: u8);
    pub fn omap4_prm_vcvp_rmw(mask: u32, bits: u32, offset: u8) -> u32;

    pub fn omap44xx_prm_init(data: *const omap_prcm_init_data) -> i32;
}

/* Opaque declaration corresponding to `struct omap_prcm_init_data`. */
#[repr(C)]
pub struct omap_prcm_init_data {
    _private: [u8; 0],
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
