/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * OMAP44xx SCRM registers and bitfields
 *
 * Copyright (C) 2010 Texas Instruments, Inc.
 *
 * Benoit Cousson (b-cousson@ti.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 */

pub const OMAP4_SCRM_BASE: usize = 0x4a30a000;

/* OMAP2_L4_IO_ADDRESS is supplied by the surrounding translation unit. */
macro_rules! OMAP44XX_SCRM_REGADDR {
    ($reg:expr) => {
        OMAP2_L4_IO_ADDRESS(OMAP4_SCRM_BASE + ($reg))
    };
}

/* Registers offset */
macro_rules! OMAP4_SCRM_CLKSETUPTIME {
    () => {
        OMAP44XX_SCRM_REGADDR!(0x0100)
    };
}

/* CLKSETUPTIME */
pub const OMAP4_DOWNTIME_SHIFT: u32 = 16;
pub const OMAP4_DOWNTIME_MASK: u32 = 0x3f << 16;
pub const OMAP4_SETUPTIME_SHIFT: u32 = 0;
pub const OMAP4_SETUPTIME_MASK: u32 = 0xfff << 0;

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
