/* SPDX-License-Identifier: (GPL-2.0 OR MIT) */
/*
 * Microsemi Ocelot Switch driver
 *
 * Copyright (c) 2017 Microsemi Corporation
 */


pub const HSIO_PLL5G_CFG0: u32 = 0x0000;
pub const HSIO_PLL5G_CFG1: u32 = 0x0004;
pub const HSIO_PLL5G_CFG2: u32 = 0x0008;
pub const HSIO_PLL5G_CFG3: u32 = 0x000c;
pub const HSIO_PLL5G_CFG4: u32 = 0x0010;
pub const HSIO_PLL5G_CFG5: u32 = 0x0014;
pub const HSIO_PLL5G_CFG6: u32 = 0x0018;
pub const HSIO_PLL5G_STATUS0: u32 = 0x001c;
pub const HSIO_PLL5G_STATUS1: u32 = 0x0020;
pub const HSIO_PLL5G_BIST_CFG0: u32 = 0x0024;
pub const HSIO_PLL5G_BIST_CFG1: u32 = 0x0028;
pub const HSIO_PLL5G_BIST_CFG2: u32 = 0x002c;
pub const HSIO_PLL5G_BIST_STAT0: u32 = 0x0030;
pub const HSIO_PLL5G_BIST_STAT1: u32 = 0x0034;
pub const HSIO_RCOMP_CFG0: u32 = 0x0038;
pub const HSIO_RCOMP_STATUS: u32 = 0x003c;
pub const HSIO_SYNC_ETH_CFG: u32 = 0x0040;
pub const HSIO_SYNC_ETH_PLL_CFG: u32 = 0x0048;
pub const HSIO_S1G_DES_CFG: u32 = 0x004c;
pub const HSIO_S1G_IB_CFG: u32 = 0x0050;
pub const HSIO_S1G_OB_CFG: u32 = 0x0054;
pub const HSIO_S1G_SER_CFG: u32 = 0x0058;
pub const HSIO_S1G_COMMON_CFG: u32 = 0x005c;
pub const HSIO_S1G_PLL_CFG: u32 = 0x0060;
pub const HSIO_S1G_PLL_STATUS: u32 = 0x0064;
pub const HSIO_S1G_DFT_CFG0: u32 = 0x0068;
pub const HSIO_S1G_DFT_CFG1: u32 = 0x006c;
pub const HSIO_S1G_DFT_CFG2: u32 = 0x0070;
pub const HSIO_S1G_TP_CFG: u32 = 0x0074;
pub const HSIO_S1G_RC_PLL_BIST_CFG: u32 = 0x0078;
pub const HSIO_S1G_MISC_CFG: u32 = 0x007c;
pub const HSIO_S1G_DFT_STATUS: u32 = 0x0080;
pub const HSIO_S1G_MISC_STATUS: u32 = 0x0084;
pub const HSIO_MCB_S1G_ADDR_CFG: u32 = 0x0088;
pub const HSIO_S6G_DIG_CFG: u32 = 0x008c;
pub const HSIO_S6G_DFT_CFG0: u32 = 0x0090;
pub const HSIO_S6G_DFT_CFG1: u32 = 0x0094;
pub const HSIO_S6G_DFT_CFG2: u32 = 0x0098;
pub const HSIO_S6G_TP_CFG0: u32 = 0x009c;
pub const HSIO_S6G_TP_CFG1: u32 = 0x00a0;
pub const HSIO_S6G_RC_PLL_BIST_CFG: u32 = 0x00a4;
pub const HSIO_S6G_MISC_CFG: u32 = 0x00a8;
pub const HSIO_S6G_OB_ANEG_CFG: u32 = 0x00ac;
pub const HSIO_S6G_DFT_STATUS: u32 = 0x00b0;
pub const HSIO_S6G_ERR_CNT: u32 = 0x00b4;
pub const HSIO_S6G_MISC_STATUS: u32 = 0x00b8;
pub const HSIO_S6G_DES_CFG: u32 = 0x00bc;
pub const HSIO_S6G_IB_CFG: u32 = 0x00c0;
pub const HSIO_S6G_IB_CFG1: u32 = 0x00c4;
pub const HSIO_S6G_IB_CFG2: u32 = 0x00c8;
pub const HSIO_S6G_IB_CFG3: u32 = 0x00cc;
pub const HSIO_S6G_IB_CFG4: u32 = 0x00d0;
pub const HSIO_S6G_IB_CFG5: u32 = 0x00d4;
pub const HSIO_S6G_OB_CFG: u32 = 0x00d8;
pub const HSIO_S6G_OB_CFG1: u32 = 0x00dc;
pub const HSIO_S6G_SER_CFG: u32 = 0x00e0;
pub const HSIO_S6G_COMMON_CFG: u32 = 0x00e4;
pub const HSIO_S6G_PLL_CFG: u32 = 0x00e8;
pub const HSIO_S6G_ACJTAG_CFG: u32 = 0x00ec;
pub const HSIO_S6G_GP_CFG: u32 = 0x00f0;
pub const HSIO_S6G_IB_STATUS0: u32 = 0x00f4;
pub const HSIO_S6G_IB_STATUS1: u32 = 0x00f8;
pub const HSIO_S6G_ACJTAG_STATUS: u32 = 0x00fc;
pub const HSIO_S6G_PLL_STATUS: u32 = 0x0100;
pub const HSIO_S6G_REVID: u32 = 0x0104;
pub const HSIO_MCB_S6G_ADDR_CFG: u32 = 0x0108;
pub const HSIO_HW_CFG: u32 = 0x010c;
pub const HSIO_HW_QSGMII_CFG: u32 = 0x0110;
pub const HSIO_HW_QSGMII_STAT: u32 = 0x0114;
pub const HSIO_CLK_CFG: u32 = 0x0118;
pub const HSIO_TEMP_SENSOR_CTRL: u32 = 0x011c;
pub const HSIO_TEMP_SENSOR_CFG: u32 = 0x0120;
pub const HSIO_TEMP_SENSOR_STAT: u32 = 0x0124;

pub const HSIO_PLL5G_CFG0_ENA_ROT: u32 = BIT(31);
pub const HSIO_PLL5G_CFG0_ENA_LANE: u32 = BIT(30);
pub const HSIO_PLL5G_CFG0_ENA_CLKTREE: u32 = BIT(29);
pub const HSIO_PLL5G_CFG0_DIV4: u32 = BIT(28);
pub const HSIO_PLL5G_CFG0_ENA_LOCK_FINE: u32 = BIT(27);
macro_rules! HSIO_PLL5G_CFG0_SELBGV820 { ($x:expr) => { ((($x) << 23) & GENMASK(26, 23)) }; }
pub const HSIO_PLL5G_CFG0_SELBGV820_M: u32 = GENMASK(26, 23);
macro_rules! HSIO_PLL5G_CFG0_SELBGV820_X { ($x:expr) => { ((($x) & GENMASK(26, 23)) >> 23) }; }
macro_rules! HSIO_PLL5G_CFG0_LOOP_BW_RES { ($x:expr) => { ((($x) << 18) & GENMASK(22, 18)) }; }
pub const HSIO_PLL5G_CFG0_LOOP_BW_RES_M: u32 = GENMASK(22, 18);
macro_rules! HSIO_PLL5G_CFG0_LOOP_BW_RES_X { ($x:expr) => { ((($x) & GENMASK(22, 18)) >> 18) }; }
macro_rules! HSIO_PLL5G_CFG0_SELCPI { ($x:expr) => { ((($x) << 16) & GENMASK(17, 16)) }; }
pub const HSIO_PLL5G_CFG0_SELCPI_M: u32 = GENMASK(17, 16);
macro_rules! HSIO_PLL5G_CFG0_SELCPI_X { ($x:expr) => { ((($x) & GENMASK(17, 16)) >> 16) }; }
pub const HSIO_PLL5G_CFG0_ENA_VCO_CONTRH: u32 = BIT(15);
pub const HSIO_PLL5G_CFG0_ENA_CP1: u32 = BIT(14);
pub const HSIO_PLL5G_CFG0_ENA_VCO_BUF: u32 = BIT(13);
pub const HSIO_PLL5G_CFG0_ENA_BIAS: u32 = BIT(12);
macro_rules! HSIO_PLL5G_CFG0_CPU_CLK_DIV { ($x:expr) => { ((($x) << 6) & GENMASK(11, 6)) }; }
pub const HSIO_PLL5G_CFG0_CPU_CLK_DIV_M: u32 = GENMASK(11, 6);
macro_rules! HSIO_PLL5G_CFG0_CPU_CLK_DIV_X { ($x:expr) => { ((($x) & GENMASK(11, 6)) >> 6) }; }
macro_rules! HSIO_PLL5G_CFG0_CORE_CLK_DIV { ($x:expr) => { (($x) & GENMASK(5, 0)) }; }
pub const HSIO_PLL5G_CFG0_CORE_CLK_DIV_M: u32 = GENMASK(5, 0);

pub const HSIO_PLL5G_CFG1_ENA_DIRECT: u32 = BIT(18);
pub const HSIO_PLL5G_CFG1_ROT_SPEED: u32 = BIT(17);
pub const HSIO_PLL5G_CFG1_ROT_DIR: u32 = BIT(16);
pub const HSIO_PLL5G_CFG1_READBACK_DATA_SEL: u32 = BIT(15);
pub const HSIO_PLL5G_CFG1_RC_ENABLE: u32 = BIT(14);
macro_rules! HSIO_PLL5G_CFG1_RC_CTRL_DATA { ($x:expr) => { ((($x) << 6) & GENMASK(13, 6)) }; }
pub const HSIO_PLL5G_CFG1_RC_CTRL_DATA_M: u32 = GENMASK(13, 6);
macro_rules! HSIO_PLL5G_CFG1_RC_CTRL_DATA_X { ($x:expr) => { ((($x) & GENMASK(13, 6)) >> 6) }; }
pub const HSIO_PLL5G_CFG1_QUARTER_RATE: u32 = BIT(5);
pub const HSIO_PLL5G_CFG1_PWD_TX: u32 = BIT(4);
pub const HSIO_PLL5G_CFG1_PWD_RX: u32 = BIT(3);
pub const HSIO_PLL5G_CFG1_OUT_OF_RANGE_RECAL_ENA: u32 = BIT(2);
pub const HSIO_PLL5G_CFG1_HALF_RATE: u32 = BIT(1);
pub const HSIO_PLL5G_CFG1_FORCE_SET_ENA: u32 = BIT(0);

pub const HSIO_PLL5G_CFG2_ENA_TEST_MODE: u32 = BIT(30);
pub const HSIO_PLL5G_CFG2_ENA_PFD_IN_FLIP: u32 = BIT(29);
pub const HSIO_PLL5G_CFG2_ENA_VCO_NREF_TESTOUT: u32 = BIT(28);
pub const HSIO_PLL5G_CFG2_ENA_FBTESTOUT: u32 = BIT(27);
pub const HSIO_PLL5G_CFG2_ENA_RCPLL: u32 = BIT(26);
pub const HSIO_PLL5G_CFG2_ENA_CP2: u32 = BIT(25);
pub const HSIO_PLL5G_CFG2_ENA_CLK_BYPASS1: u32 = BIT(24);
macro_rules! HSIO_PLL5G_CFG2_AMPC_SEL { ($x:expr) => { ((($x) << 16) & GENMASK(23, 16)) }; }
pub const HSIO_PLL5G_CFG2_AMPC_SEL_M: u32 = GENMASK(23, 16);
macro_rules! HSIO_PLL5G_CFG2_AMPC_SEL_X { ($x:expr) => { ((($x) & GENMASK(23, 16)) >> 16) }; }
pub const HSIO_PLL5G_CFG2_ENA_CLK_BYPASS: u32 = BIT(15);
pub const HSIO_PLL5G_CFG2_PWD_AMPCTRL_N: u32 = BIT(14);
pub const HSIO_PLL5G_CFG2_ENA_AMPCTRL: u32 = BIT(13);
pub const HSIO_PLL5G_CFG2_ENA_AMP_CTRL_FORCE: u32 = BIT(12);
pub const HSIO_PLL5G_CFG2_FRC_FSM_POR: u32 = BIT(11);
pub const HSIO_PLL5G_CFG2_DISABLE_FSM_POR: u32 = BIT(10);
macro_rules! HSIO_PLL5G_CFG2_GAIN_TEST { ($x:expr) => { ((($x) << 5) & GENMASK(9, 5)) }; }
pub const HSIO_PLL5G_CFG2_GAIN_TEST_M: u32 = GENMASK(9, 5);
macro_rules! HSIO_PLL5G_CFG2_GAIN_TEST_X { ($x:expr) => { ((($x) & GENMASK(9, 5)) >> 5) }; }
pub const HSIO_PLL5G_CFG2_EN_RESET_OVERRUN: u32 = BIT(4);
pub const HSIO_PLL5G_CFG2_EN_RESET_LIM_DET: u32 = BIT(3);
pub const HSIO_PLL5G_CFG2_EN_RESET_FRQ_DET: u32 = BIT(2);
pub const HSIO_PLL5G_CFG2_DISABLE_FSM: u32 = BIT(1);
pub const HSIO_PLL5G_CFG2_ENA_GAIN_TEST: u32 = BIT(0);

macro_rules! HSIO_PLL5G_CFG3_TEST_ANA_OUT_SEL { ($x:expr) => { ((($x) << 22) & GENMASK(23, 22)) }; }
pub const HSIO_PLL5G_CFG3_TEST_ANA_OUT_SEL_M: u32 = GENMASK(23, 22);
macro_rules! HSIO_PLL5G_CFG3_TEST_ANA_OUT_SEL_X { ($x:expr) => { ((($x) & GENMASK(23, 22)) >> 22) }; }
macro_rules! HSIO_PLL5G_CFG3_TESTOUT_SEL { ($x:expr) => { ((($x) << 19) & GENMASK(21, 19)) }; }
pub const HSIO_PLL5G_CFG3_TESTOUT_SEL_M: u32 = GENMASK(21, 19);
macro_rules! HSIO_PLL5G_CFG3_TESTOUT_SEL_X { ($x:expr) => { ((($x) & GENMASK(21, 19)) >> 19) }; }
pub const HSIO_PLL5G_CFG3_ENA_ANA_TEST_OUT: u32 = BIT(18);
pub const HSIO_PLL5G_CFG3_ENA_TEST_OUT: u32 = BIT(17);
pub const HSIO_PLL5G_CFG3_SEL_FBDCLK: u32 = BIT(16);
pub const HSIO_PLL5G_CFG3_SEL_CML_CMOS_PFD: u32 = BIT(15);
pub const HSIO_PLL5G_CFG3_RST_FB_N: u32 = BIT(14);
pub const HSIO_PLL5G_CFG3_FORCE_VCO_CONTRH: u32 = BIT(13);
pub const HSIO_PLL5G_CFG3_FORCE_LO: u32 = BIT(12);
pub const HSIO_PLL5G_CFG3_FORCE_HI: u32 = BIT(11);
pub const HSIO_PLL5G_CFG3_FORCE_ENA: u32 = BIT(10);
pub const HSIO_PLL5G_CFG3_FORCE_CP: u32 = BIT(9);
pub const HSIO_PLL5G_CFG3_FBDIVSEL_TST_ENA: u32 = BIT(8);
macro_rules! HSIO_PLL5G_CFG3_FBDIVSEL { ($x:expr) => { (($x) & GENMASK(7, 0)) }; }
pub const HSIO_PLL5G_CFG3_FBDIVSEL_M: u32 = GENMASK(7, 0);

macro_rules! HSIO_PLL5G_CFG4_IB_BIAS_CTRL { ($x:expr) => { ((($x) << 16) & GENMASK(23, 16)) }; }
pub const HSIO_PLL5G_CFG4_IB_BIAS_CTRL_M: u32 = GENMASK(23, 16);
macro_rules! HSIO_PLL5G_CFG4_IB_BIAS_CTRL_X { ($x:expr) => { ((($x) & GENMASK(23, 16)) >> 16) }; }
macro_rules! HSIO_PLL5G_CFG4_IB_CTRL { ($x:expr) => { (($x) & GENMASK(15, 0)) }; }
pub const HSIO_PLL5G_CFG4_IB_CTRL_M: u32 = GENMASK(15, 0);

macro_rules! HSIO_PLL5G_CFG5_OB_BIAS_CTRL { ($x:expr) => { ((($x) << 16) & GENMASK(23, 16)) }; }
pub const HSIO_PLL5G_CFG5_OB_BIAS_CTRL_M: u32 = GENMASK(23, 16);
macro_rules! HSIO_PLL5G_CFG5_OB_BIAS_CTRL_X { ($x:expr) => { ((($x) & GENMASK(23, 16)) >> 16) }; }
macro_rules! HSIO_PLL5G_CFG5_OB_CTRL { ($x:expr) => { (($x) & GENMASK(15, 0)) }; }
pub const HSIO_PLL5G_CFG5_OB_CTRL_M: u32 = GENMASK(15, 0);

pub const HSIO_PLL5G_CFG6_REFCLK_SEL_SRC: u32 = BIT(23);
macro_rules! HSIO_PLL5G_CFG6_REFCLK_SEL { ($x:expr) => { ((($x) << 20) & GENMASK(22, 20)) }; }
pub const HSIO_PLL5G_CFG6_REFCLK_SEL_M: u32 = GENMASK(22, 20);
macro_rules! HSIO_PLL5G_CFG6_REFCLK_SEL_X { ($x:expr) => { ((($x) & GENMASK(22, 20)) >> 20) }; }
pub const HSIO_PLL5G_CFG6_REFCLK_SRC: u32 = BIT(19);
macro_rules! HSIO_PLL5G_CFG6_POR_DEL_SEL { ($x:expr) => { ((($x) << 16) & GENMASK(17, 16)) }; }
pub const HSIO_PLL5G_CFG6_POR_DEL_SEL_M: u32 = GENMASK(17, 16);
macro_rules! HSIO_PLL5G_CFG6_POR_DEL_SEL_X { ($x:expr) => { ((($x) & GENMASK(17, 16)) >> 16) }; }
macro_rules! HSIO_PLL5G_CFG6_DIV125REF_SEL { ($x:expr) => { ((($x) << 8) & GENMASK(15, 8)) }; }
pub const HSIO_PLL5G_CFG6_DIV125REF_SEL_M: u32 = GENMASK(15, 8);
macro_rules! HSIO_PLL5G_CFG6_DIV125REF_SEL_X { ($x:expr) => { ((($x) & GENMASK(15, 8)) >> 8) }; }
pub const HSIO_PLL5G_CFG6_ENA_REFCLKC2: u32 = BIT(7);
pub const HSIO_PLL5G_CFG6_ENA_FBCLKC2: u32 = BIT(6);
macro_rules! HSIO_PLL5G_CFG6_DDR_CLK_DIV { ($x:expr) => { (($x) & GENMASK(5, 0)) }; }
pub const HSIO_PLL5G_CFG6_DDR_CLK_DIV_M: u32 = GENMASK(5, 0);

pub const HSIO_PLL5G_STATUS0_RANGE_LIM: u32 = BIT(12);
pub const HSIO_PLL5G_STATUS0_OUT_OF_RANGE_ERR: u32 = BIT(11);
pub const HSIO_PLL5G_STATUS0_CALIBRATION_ERR: u32 = BIT(10);
pub const HSIO_PLL5G_STATUS0_CALIBRATION_DONE: u32 = BIT(9);
macro_rules! HSIO_PLL5G_STATUS0_READBACK_DATA { ($x:expr) => { ((($x) << 1) & GENMASK(8, 1)) }; }
pub const HSIO_PLL5G_STATUS0_READBACK_DATA_M: u32 = GENMASK(8, 1);
macro_rules! HSIO_PLL5G_STATUS0_READBACK_DATA_X { ($x:expr) => { ((($x) & GENMASK(8, 1)) >> 1) }; }
pub const HSIO_PLL5G_STATUS0_LOCK_STATUS: u32 = BIT(0);

macro_rules! HSIO_PLL5G_STATUS1_SIG_DEL { ($x:expr) => { ((($x) << 21) & GENMASK(28, 21)) }; }
pub const HSIO_PLL5G_STATUS1_SIG_DEL_M: u32 = GENMASK(28, 21);
macro_rules! HSIO_PLL5G_STATUS1_SIG_DEL_X { ($x:expr) => { ((($x) & GENMASK(28, 21)) >> 21) }; }
macro_rules! HSIO_PLL5G_STATUS1_GAIN_STAT { ($x:expr) => { ((($x) << 16) & GENMASK(20, 16)) }; }
pub const HSIO_PLL5G_STATUS1_GAIN_STAT_M: u32 = GENMASK(20, 16);
macro_rules! HSIO_PLL5G_STATUS1_GAIN_STAT_X { ($x:expr) => { ((($x) & GENMASK(20, 16)) >> 16) }; }
macro_rules! HSIO_PLL5G_STATUS1_FBCNT_DIF { ($x:expr) => { ((($x) << 4) & GENMASK(13, 4)) }; }
pub const HSIO_PLL5G_STATUS1_FBCNT_DIF_M: u32 = GENMASK(13, 4);
macro_rules! HSIO_PLL5G_STATUS1_FBCNT_DIF_X { ($x:expr) => { ((($x) & GENMASK(13, 4)) >> 4) }; }
macro_rules! HSIO_PLL5G_STATUS1_FSM_STAT { ($x:expr) => { ((($x) << 1) & GENMASK(3, 1)) }; }
pub const HSIO_PLL5G_STATUS1_FSM_STAT_M: u32 = GENMASK(3, 1);
macro_rules! HSIO_PLL5G_STATUS1_FSM_STAT_X { ($x:expr) => { ((($x) & GENMASK(3, 1)) >> 1) }; }
pub const HSIO_PLL5G_STATUS1_FSM_LOCK: u32 = BIT(0);

pub const HSIO_PLL5G_BIST_CFG0_PLLB_START_BIST: u32 = BIT(31);
pub const HSIO_PLL5G_BIST_CFG0_PLLB_MEAS_MODE: u32 = BIT(30);
macro_rules! HSIO_PLL5G_BIST_CFG0_PLLB_LOCK_REPEAT { ($x:expr) => { ((($x) << 20) & GENMASK(23, 20)) }; }
pub const HSIO_PLL5G_BIST_CFG0_PLLB_LOCK_REPEAT_M: u32 = GENMASK(23, 20);
macro_rules! HSIO_PLL5G_BIST_CFG0_PLLB_LOCK_REPEAT_X { ($x:expr) => { ((($x) & GENMASK(23, 20)) >> 20) }; }
macro_rules! HSIO_PLL5G_BIST_CFG0_PLLB_LOCK_UNCERT { ($x:expr) => { ((($x) << 16) & GENMASK(19, 16)) }; }
pub const HSIO_PLL5G_BIST_CFG0_PLLB_LOCK_UNCERT_M: u32 = GENMASK(19, 16);
macro_rules! HSIO_PLL5G_BIST_CFG0_PLLB_LOCK_UNCERT_X { ($x:expr) => { ((($x) & GENMASK(19, 16)) >> 16) }; }
macro_rules! HSIO_PLL5G_BIST_CFG0_PLLB_DIV_FACTOR_PRE { ($x:expr) => { (($x) & GENMASK(15, 0)) }; }
pub const HSIO_PLL5G_BIST_CFG0_PLLB_DIV_FACTOR_PRE_M: u32 = GENMASK(15, 0);

macro_rules! HSIO_PLL5G_BIST_STAT0_PLLB_FSM_STAT { ($x:expr) => { ((($x) << 4) & GENMASK(7, 4)) }; }
pub const HSIO_PLL5G_BIST_STAT0_PLLB_FSM_STAT_M: u32 = GENMASK(7, 4);
macro_rules! HSIO_PLL5G_BIST_STAT0_PLLB_FSM_STAT_X { ($x:expr) => { ((($x) & GENMASK(7, 4)) >> 4) }; }
pub const HSIO_PLL5G_BIST_STAT0_PLLB_BUSY: u32 = BIT(2);
pub const HSIO_PLL5G_BIST_STAT0_PLLB_DONE_N: u32 = BIT(1);
pub const HSIO_PLL5G_BIST_STAT0_PLLB_FAIL: u32 = BIT(0);

macro_rules! HSIO_PLL5G_BIST_STAT1_PLLB_CNT_OUT { ($x:expr) => { ((($x) << 16) & GENMASK(31, 16)) }; }
pub const HSIO_PLL5G_BIST_STAT1_PLLB_CNT_OUT_M: u32 = GENMASK(31, 16);
macro_rules! HSIO_PLL5G_BIST_STAT1_PLLB_CNT_OUT_X { ($x:expr) => { ((($x) & GENMASK(31, 16)) >> 16) }; }
macro_rules! HSIO_PLL5G_BIST_STAT1_PLLB_CNT_REF_DIFF { ($x:expr) => { (($x) & GENMASK(15, 0)) }; }
pub const HSIO_PLL5G_BIST_STAT1_PLLB_CNT_REF_DIFF_M: u32 = GENMASK(15, 0);

pub const HSIO_RCOMP_CFG0_PWD_ENA: u32 = BIT(13);
pub const HSIO_RCOMP_CFG0_RUN_CAL: u32 = BIT(12);
macro_rules! HSIO_RCOMP_CFG0_SPEED_SEL { ($x:expr) => { ((($x) << 10) & GENMASK(11, 10)) }; }
pub const HSIO_RCOMP_CFG0_SPEED_SEL_M: u32 = GENMASK(11, 10);
macro_rules! HSIO_RCOMP_CFG0_SPEED_SEL_X { ($x:expr) => { ((($x) & GENMASK(11, 10)) >> 10) }; }
macro_rules! HSIO_RCOMP_CFG0_MODE_SEL { ($x:expr) => { ((($x) << 8) & GENMASK(9, 8)) }; }
pub const HSIO_RCOMP_CFG0_MODE_SEL_M: u32 = GENMASK(9, 8);
macro_rules! HSIO_RCOMP_CFG0_MODE_SEL_X { ($x:expr) => { ((($x) & GENMASK(9, 8)) >> 8) }; }
pub const HSIO_RCOMP_CFG0_FORCE_ENA: u32 = BIT(4);
macro_rules! HSIO_RCOMP_CFG0_RCOMP_VAL { ($x:expr) => { (($x) & GENMASK(3, 0)) }; }
pub const HSIO_RCOMP_CFG0_RCOMP_VAL_M: u32 = GENMASK(3, 0);

pub const HSIO_RCOMP_STATUS_BUSY: u32 = BIT(12);
pub const HSIO_RCOMP_STATUS_DELTA_ALERT: u32 = BIT(7);
macro_rules! HSIO_RCOMP_STATUS_RCOMP { ($x:expr) => { (($x) & GENMASK(3, 0)) }; }
pub const HSIO_RCOMP_STATUS_RCOMP_M: u32 = GENMASK(3, 0);

pub const HSIO_SYNC_ETH_CFG_RSZ: u32 = 0x4;

macro_rules! HSIO_SYNC_ETH_CFG_SEL_RECO_CLK_SRC { ($x:expr) => { ((($x) << 4) & GENMASK(7, 4)) }; }
pub const HSIO_SYNC_ETH_CFG_SEL_RECO_CLK_SRC_M: u32 = GENMASK(7, 4);
macro_rules! HSIO_SYNC_ETH_CFG_SEL_RECO_CLK_SRC_X { ($x:expr) => { ((($x) & GENMASK(7, 4)) >> 4) }; }
macro_rules! HSIO_SYNC_ETH_CFG_SEL_RECO_CLK_DIV { ($x:expr) => { ((($x) << 1) & GENMASK(3, 1)) }; }
pub const HSIO_SYNC_ETH_CFG_SEL_RECO_CLK_DIV_M: u32 = GENMASK(3, 1);
macro_rules! HSIO_SYNC_ETH_CFG_SEL_RECO_CLK_DIV_X { ($x:expr) => { ((($x) & GENMASK(3, 1)) >> 1) }; }
pub const HSIO_SYNC_ETH_CFG_RECO_CLK_ENA: u32 = BIT(0);

pub const HSIO_SYNC_ETH_PLL_CFG_PLL_AUTO_SQUELCH_ENA: u32 = BIT(0);

macro_rules! HSIO_S1G_DES_CFG_DES_PHS_CTRL { ($x:expr) => { ((($x) << 13) & GENMASK(16, 13)) }; }
pub const HSIO_S1G_DES_CFG_DES_PHS_CTRL_M: u32 = GENMASK(16, 13);
macro_rules! HSIO_S1G_DES_CFG_DES_PHS_CTRL_X { ($x:expr) => { ((($x) & GENMASK(16, 13)) >> 13) }; }
macro_rules! HSIO_S1G_DES_CFG_DES_CPMD_SEL { ($x:expr) => { ((($x) << 11) & GENMASK(12, 11)) }; }
pub const HSIO_S1G_DES_CFG_DES_CPMD_SEL_M: u32 = GENMASK(12, 11);
macro_rules! HSIO_S1G_DES_CFG_DES_CPMD_SEL_X { ($x:expr) => { ((($x) & GENMASK(12, 11)) >> 11) }; }
macro_rules! HSIO_S1G_DES_CFG_DES_MBTR_CTRL { ($x:expr) => { ((($x) << 8) & GENMASK(10, 8)) }; }
pub const HSIO_S1G_DES_CFG_DES_MBTR_CTRL_M: u32 = GENMASK(10, 8);
macro_rules! HSIO_S1G_DES_CFG_DES_MBTR_CTRL_X { ($x:expr) => { ((($x) & GENMASK(10, 8)) >> 8) }; }
macro_rules! HSIO_S1G_DES_CFG_DES_BW_ANA { ($x:expr) => { ((($x) << 5) & GENMASK(7, 5)) }; }
pub const HSIO_S1G_DES_CFG_DES_BW_ANA_M: u32 = GENMASK(7, 5);
macro_rules! HSIO_S1G_DES_CFG_DES_BW_ANA_X { ($x:expr) => { ((($x) & GENMASK(7, 5)) >> 5) }; }
pub const HSIO_S1G_DES_CFG_DES_SWAP_ANA: u32 = BIT(4);
macro_rules! HSIO_S1G_DES_CFG_DES_BW_HYST { ($x:expr) => { ((($x) << 1) & GENMASK(3, 1)) }; }
pub const HSIO_S1G_DES_CFG_DES_BW_HYST_M: u32 = GENMASK(3, 1);
macro_rules! HSIO_S1G_DES_CFG_DES_BW_HYST_X { ($x:expr) => { ((($x) & GENMASK(3, 1)) >> 1) }; }
pub const HSIO_S1G_DES_CFG_DES_SWAP_HYST: u32 = BIT(0);

pub const HSIO_S1G_IB_CFG_IB_FX100_ENA: u32 = BIT(27);
macro_rules! HSIO_S1G_IB_CFG_ACJTAG_HYST { ($x:expr) => { ((($x) << 24) & GENMASK(26, 24)) }; }
pub const HSIO_S1G_IB_CFG_ACJTAG_HYST_M: u32 = GENMASK(26, 24);
macro_rules! HSIO_S1G_IB_CFG_ACJTAG_HYST_X { ($x:expr) => { ((($x) & GENMASK(26, 24)) >> 24) }; }
macro_rules! HSIO_S1G_IB_CFG_IB_DET_LEV { ($x:expr) => { ((($x) << 19) & GENMASK(21, 19)) }; }
pub const HSIO_S1G_IB_CFG_IB_DET_LEV_M: u32 = GENMASK(21, 19);
macro_rules! HSIO_S1G_IB_CFG_IB_DET_LEV_X { ($x:expr) => { ((($x) & GENMASK(21, 19)) >> 19) }; }
pub const HSIO_S1G_IB_CFG_IB_HYST_LEV: u32 = BIT(14);
pub const HSIO_S1G_IB_CFG_IB_ENA_CMV_TERM: u32 = BIT(13);
pub const HSIO_S1G_IB_CFG_IB_ENA_DC_COUPLING: u32 = BIT(12);
pub const HSIO_S1G_IB_CFG_IB_ENA_DETLEV: u32 = BIT(11);
pub const HSIO_S1G_IB_CFG_IB_ENA_HYST: u32 = BIT(10);
pub const HSIO_S1G_IB_CFG_IB_ENA_OFFSET_COMP: u32 = BIT(9);
macro_rules! HSIO_S1G_IB_CFG_IB_EQ_GAIN { ($x:expr) => { ((($x) << 6) & GENMASK(8, 6)) }; }
pub const HSIO_S1G_IB_CFG_IB_EQ_GAIN_M: u32 = GENMASK(8, 6);
macro_rules! HSIO_S1G_IB_CFG_IB_EQ_GAIN_X { ($x:expr) => { ((($x) & GENMASK(8, 6)) >> 6) }; }
macro_rules! HSIO_S1G_IB_CFG_IB_SEL_CORNER_FREQ { ($x:expr) => { ((($x) << 4) & GENMASK(5, 4)) }; }
pub const HSIO_S1G_IB_CFG_IB_SEL_CORNER_FREQ_M: u32 = GENMASK(5, 4);
macro_rules! HSIO_S1G_IB_CFG_IB_SEL_CORNER_FREQ_X { ($x:expr) => { ((($x) & GENMASK(5, 4)) >> 4) }; }
macro_rules! HSIO_S1G_IB_CFG_IB_RESISTOR_CTRL { ($x:expr) => { (($x) & GENMASK(3, 0)) }; }
pub const HSIO_S1G_IB_CFG_IB_RESISTOR_CTRL_M: u32 = GENMASK(3, 0);

macro_rules! HSIO_S1G_OB_CFG_OB_SLP { ($x:expr) => { ((($x) << 17) & GENMASK(18, 17)) }; }
pub const HSIO_S1G_OB_CFG_OB_SLP_M: u32 = GENMASK(18, 17);
macro_rules! HSIO_S1G_OB_CFG_OB_SLP_X { ($x:expr) => { ((($x) & GENMASK(18, 17)) >> 17) }; }
macro_rules! HSIO_S1G_OB_CFG_OB_AMP_CTRL { ($x:expr) => { ((($x) << 13) & GENMASK(16, 13)) }; }
pub const HSIO_S1G_OB_CFG_OB_AMP_CTRL_M: u32 = GENMASK(16, 13);
macro_rules! HSIO_S1G_OB_CFG_OB_AMP_CTRL_X { ($x:expr) => { ((($x) & GENMASK(16, 13)) >> 13) }; }
macro_rules! HSIO_S1G_OB_CFG_OB_CMM_BIAS_CTRL { ($x:expr) => { ((($x) << 10) & GENMASK(12, 10)) }; }
pub const HSIO_S1G_OB_CFG_OB_CMM_BIAS_CTRL_M: u32 = GENMASK(12, 10);
macro_rules! HSIO_S1G_OB_CFG_OB_CMM_BIAS_CTRL_X { ($x:expr) => { ((($x) & GENMASK(12, 10)) >> 10) }; }
pub const HSIO_S1G_OB_CFG_OB_DIS_VCM_CTRL: u32 = BIT(9);
pub const HSIO_S1G_OB_CFG_OB_EN_MEAS_VREG: u32 = BIT(8);
macro_rules! HSIO_S1G_OB_CFG_OB_VCM_CTRL { ($x:expr) => { ((($x) << 4) & GENMASK(7, 4)) }; }
pub const HSIO_S1G_OB_CFG_OB_VCM_CTRL_M: u32 = GENMASK(7, 4);
macro_rules! HSIO_S1G_OB_CFG_OB_VCM_CTRL_X { ($x:expr) => { ((($x) & GENMASK(7, 4)) >> 4) }; }
macro_rules! HSIO_S1G_OB_CFG_OB_RESISTOR_CTRL { ($x:expr) => { (($x) & GENMASK(3, 0)) }; }
pub const HSIO_S1G_OB_CFG_OB_RESISTOR_CTRL_M: u32 = GENMASK(3, 0);

pub const HSIO_S1G_SER_CFG_SER_IDLE: u32 = BIT(9);
pub const HSIO_S1G_SER_CFG_SER_DEEMPH: u32 = BIT(8);
pub const HSIO_S1G_SER_CFG_SER_CPMD_SEL: u32 = BIT(7);
pub const HSIO_S1G_SER_CFG_SER_SWAP_CPMD: u32 = BIT(6);
macro_rules! HSIO_S1G_SER_CFG_SER_ALISEL { ($x:expr) => { ((($x) << 4) & GENMASK(5, 4)) }; }
pub const HSIO_S1G_SER_CFG_SER_ALISEL_M: u32 = GENMASK(5, 4);
macro_rules! HSIO_S1G_SER_CFG_SER_ALISEL_X { ($x:expr) => { ((($x) & GENMASK(5, 4)) >> 4) }; }
pub const HSIO_S1G_SER_CFG_SER_ENHYS: u32 = BIT(3);
pub const HSIO_S1G_SER_CFG_SER_BIG_WIN: u32 = BIT(2);
pub const HSIO_S1G_SER_CFG_SER_EN_WIN: u32 = BIT(1);
pub const HSIO_S1G_SER_CFG_SER_ENALI: u32 = BIT(0);

pub const HSIO_S1G_COMMON_CFG_SYS_RST: u32 = BIT(31);
pub const HSIO_S1G_COMMON_CFG_SE_AUTO_SQUELCH_ENA: u32 = BIT(21);
pub const HSIO_S1G_COMMON_CFG_ENA_LANE: u32 = BIT(18);
pub const HSIO_S1G_COMMON_CFG_PWD_RX: u32 = BIT(17);
pub const HSIO_S1G_COMMON_CFG_PWD_TX: u32 = BIT(16);
macro_rules! HSIO_S1G_COMMON_CFG_LANE_CTRL { ($x:expr) => { ((($x) << 13) & GENMASK(15, 13)) }; }
pub const HSIO_S1G_COMMON_CFG_LANE_CTRL_M: u32 = GENMASK(15, 13);
macro_rules! HSIO_S1G_COMMON_CFG_LANE_CTRL_X { ($x:expr) => { ((($x) & GENMASK(15, 13)) >> 13) }; }
pub const HSIO_S1G_COMMON_CFG_ENA_DIRECT: u32 = BIT(12);
pub const HSIO_S1G_COMMON_CFG_ENA_ELOOP: u32 = BIT(11);
pub const HSIO_S1G_COMMON_CFG_ENA_FLOOP: u32 = BIT(10);
pub const HSIO_S1G_COMMON_CFG_ENA_ILOOP: u32 = BIT(9);
pub const HSIO_S1G_COMMON_CFG_ENA_PLOOP: u32 = BIT(8);
pub const HSIO_S1G_COMMON_CFG_HRATE: u32 = BIT(7);
pub const HSIO_S1G_COMMON_CFG_IF_MODE: u32 = BIT(0);

pub const HSIO_S1G_PLL_CFG_PLL_ENA_FB_DIV2: u32 = BIT(22);
pub const HSIO_S1G_PLL_CFG_PLL_ENA_RC_DIV2: u32 = BIT(21);
macro_rules! HSIO_S1G_PLL_CFG_PLL_FSM_CTRL_DATA { ($x:expr) => { ((($x) << 8) & GENMASK(15, 8)) }; }
pub const HSIO_S1G_PLL_CFG_PLL_FSM_CTRL_DATA_M: u32 = GENMASK(15, 8);
macro_rules! HSIO_S1G_PLL_CFG_PLL_FSM_CTRL_DATA_X { ($x:expr) => { ((($x) & GENMASK(15, 8)) >> 8) }; }
pub const HSIO_S1G_PLL_CFG_PLL_FSM_ENA: u32 = BIT(7);
pub const HSIO_S1G_PLL_CFG_PLL_FSM_FORCE_SET_ENA: u32 = BIT(6);
pub const HSIO_S1G_PLL_CFG_PLL_FSM_OOR_RECAL_ENA: u32 = BIT(5);
pub const HSIO_S1G_PLL_CFG_PLL_RB_DATA_SEL: u32 = BIT(3);

pub const HSIO_S1G_PLL_STATUS_PLL_CAL_NOT_DONE: u32 = BIT(12);
pub const HSIO_S1G_PLL_STATUS_PLL_CAL_ERR: u32 = BIT(11);
pub const HSIO_S1G_PLL_STATUS_PLL_OUT_OF_RANGE_ERR: u32 = BIT(10);
macro_rules! HSIO_S1G_PLL_STATUS_PLL_RB_DATA { ($x:expr) => { (($x) & GENMASK(7, 0)) }; }
pub const HSIO_S1G_PLL_STATUS_PLL_RB_DATA_M: u32 = GENMASK(7, 0);

pub const HSIO_S1G_DFT_CFG0_LAZYBIT: u32 = BIT(31);
pub const HSIO_S1G_DFT_CFG0_INV_DIS: u32 = BIT(23);
macro_rules! HSIO_S1G_DFT_CFG0_PRBS_SEL { ($x:expr) => { ((($x) << 20) & GENMASK(21, 20)) }; }
pub const HSIO_S1G_DFT_CFG0_PRBS_SEL_M: u32 = GENMASK(21, 20);
macro_rules! HSIO_S1G_DFT_CFG0_PRBS_SEL_X { ($x:expr) => { ((($x) & GENMASK(21, 20)) >> 20) }; }
macro_rules! HSIO_S1G_DFT_CFG0_TEST_MODE { ($x:expr) => { ((($x) << 16) & GENMASK(18, 16)) }; }
pub const HSIO_S1G_DFT_CFG0_TEST_MODE_M: u32 = GENMASK(18, 16);
macro_rules! HSIO_S1G_DFT_CFG0_TEST_MODE_X { ($x:expr) => { ((($x) & GENMASK(18, 16)) >> 16) }; }
pub const HSIO_S1G_DFT_CFG0_RX_PHS_CORR_DIS: u32 = BIT(4);
pub const HSIO_S1G_DFT_CFG0_RX_PDSENS_ENA: u32 = BIT(3);
pub const HSIO_S1G_DFT_CFG0_RX_DFT_ENA: u32 = BIT(2);
pub const HSIO_S1G_DFT_CFG0_TX_DFT_ENA: u32 = BIT(0);

macro_rules! HSIO_S1G_DFT_CFG1_TX_JITTER_AMPL { ($x:expr) => { ((($x) << 8) & GENMASK(17, 8)) }; }
pub const HSIO_S1G_DFT_CFG1_TX_JITTER_AMPL_M: u32 = GENMASK(17, 8);
macro_rules! HSIO_S1G_DFT_CFG1_TX_JITTER_AMPL_X { ($x:expr) => { ((($x) & GENMASK(17, 8)) >> 8) }; }
macro_rules! HSIO_S1G_DFT_CFG1_TX_STEP_FREQ { ($x:expr) => { ((($x) << 4) & GENMASK(7, 4)) }; }
pub const HSIO_S1G_DFT_CFG1_TX_STEP_FREQ_M: u32 = GENMASK(7, 4);
macro_rules! HSIO_S1G_DFT_CFG1_TX_STEP_FREQ_X { ($x:expr) => { ((($x) & GENMASK(7, 4)) >> 4) }; }
pub const HSIO_S1G_DFT_CFG1_TX_JI_ENA: u32 = BIT(3);
pub const HSIO_S1G_DFT_CFG1_TX_WAVEFORM_SEL: u32 = BIT(2);
pub const HSIO_S1G_DFT_CFG1_TX_FREQOFF_DIR: u32 = BIT(1);
pub const HSIO_S1G_DFT_CFG1_TX_FREQOFF_ENA: u32 = BIT(0);

macro_rules! HSIO_S1G_DFT_CFG2_RX_JITTER_AMPL { ($x:expr) => { ((($x) << 8) & GENMASK(17, 8)) }; }
pub const HSIO_S1G_DFT_CFG2_RX_JITTER_AMPL_M: u32 = GENMASK(17, 8);
macro_rules! HSIO_S1G_DFT_CFG2_RX_JITTER_AMPL_X { ($x:expr) => { ((($x) & GENMASK(17, 8)) >> 8) }; }
macro_rules! HSIO_S1G_DFT_CFG2_RX_STEP_FREQ { ($x:expr) => { ((($x) << 4) & GENMASK(7, 4)) }; }
pub const HSIO_S1G_DFT_CFG2_RX_STEP_FREQ_M: u32 = GENMASK(7, 4);
macro_rules! HSIO_S1G_DFT_CFG2_RX_STEP_FREQ_X { ($x:expr) => { ((($x) & GENMASK(7, 4)) >> 4) }; }
pub const HSIO_S1G_DFT_CFG2_RX_JI_ENA: u32 = BIT(3);
pub const HSIO_S1G_DFT_CFG2_RX_WAVEFORM_SEL: u32 = BIT(2);
pub const HSIO_S1G_DFT_CFG2_RX_FREQOFF_DIR: u32 = BIT(1);
pub const HSIO_S1G_DFT_CFG2_RX_FREQOFF_ENA: u32 = BIT(0);

pub const HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_ENA: u32 = BIT(20);
macro_rules! HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_FBS_HIGH { ($x:expr) => { ((($x) << 16) & GENMASK(17, 16)) }; }
pub const HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_FBS_HIGH_M: u32 = GENMASK(17, 16);
macro_rules! HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_FBS_HIGH_X { ($x:expr) => { ((($x) & GENMASK(17, 16)) >> 16) }; }
macro_rules! HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_HIGH { ($x:expr) => { ((($x) << 8) & GENMASK(15, 8)) }; }
pub const HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_HIGH_M: u32 = GENMASK(15, 8);
macro_rules! HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_HIGH_X { ($x:expr) => { ((($x) & GENMASK(15, 8)) >> 8) }; }
macro_rules! HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_LOW { ($x:expr) => { (($x) & GENMASK(7, 0)) }; }
pub const HSIO_S1G_RC_PLL_BIST_CFG_PLL_BIST_LOW_M: u32 = GENMASK(7, 0);

macro_rules! HSIO_S1G_MISC_CFG_DES_100FX_KICK_MODE { ($x:expr) => { ((($x) << 11) & GENMASK(12, 11)) }; }
pub const HSIO_S1G_MISC_CFG_DES_100FX_KICK_MODE_M: u32 = GENMASK(12, 11);
macro_rules! HSIO_S1G_MISC_CFG_DES_100FX_KICK_MODE_X { ($x:expr) => { ((($x) & GENMASK(12, 11)) >> 11) }; }
pub const HSIO_S1G_MISC_CFG_DES_100FX_CPMD_SWAP: u32 = BIT(10);
pub const HSIO_S1G_MISC_CFG_DES_100FX_CPMD_MODE: u32 = BIT(9);
pub const HSIO_S1G_MISC_CFG_DES_100FX_CPMD_ENA: u32 = BIT(8);
pub const HSIO_S1G_MISC_CFG_RX_LPI_MODE_ENA: u32 = BIT(5);
pub const HSIO_S1G_MISC_CFG_TX_LPI_MODE_ENA: u32 = BIT(4);
pub const HSIO_S1G_MISC_CFG_RX_DATA_INV_ENA: u32 = BIT(3);
pub const HSIO_S1G_MISC_CFG_TX_DATA_INV_ENA: u32 = BIT(2);
pub const HSIO_S1G_MISC_CFG_LANE_RST: u32 = BIT(0);

pub const HSIO_S1G_DFT_STATUS_PLL_BIST_NOT_DONE: u32 = BIT(7);
pub const HSIO_S1G_DFT_STATUS_PLL_BIST_FAILED: u32 = BIT(6);
pub const HSIO_S1G_DFT_STATUS_PLL_BIST_TIMEOUT_ERR: u32 = BIT(5);
pub const HSIO_S1G_DFT_STATUS_BIST_ACTIVE: u32 = BIT(3);
pub const HSIO_S1G_DFT_STATUS_BIST_NOSYNC: u32 = BIT(2);
pub const HSIO_S1G_DFT_STATUS_BIST_COMPLETE_N: u32 = BIT(1);
pub const HSIO_S1G_DFT_STATUS_BIST_ERROR: u32 = BIT(0);

pub const HSIO_S1G_MISC_STATUS_DES_100FX_PHASE_SEL: u32 = BIT(0);

pub const HSIO_MCB_S1G_ADDR_CFG_SERDES1G_WR_ONE_SHOT: u32 = BIT(31);
pub const HSIO_MCB_S1G_ADDR_CFG_SERDES1G_RD_ONE_SHOT: u32 = BIT(30);
macro_rules! HSIO_MCB_S1G_ADDR_CFG_SERDES1G_ADDR { ($x:expr) => { (($x) & GENMASK(8, 0)) }; }
pub const HSIO_MCB_S1G_ADDR_CFG_SERDES1G_ADDR_M: u32 = GENMASK(8, 0);

macro_rules! HSIO_S6G_DIG_CFG_GP { ($x:expr) => { ((($x) << 16) & GENMASK(18, 16)) }; }
pub const HSIO_S6G_DIG_CFG_GP_M: u32 = GENMASK(18, 16);
macro_rules! HSIO_S6G_DIG_CFG_GP_X { ($x:expr) => { ((($x) & GENMASK(18, 16)) >> 16) }; }
pub const HSIO_S6G_DIG_CFG_TX_BIT_DOUBLING_MODE_ENA: u32 = BIT(7);
pub const HSIO_S6G_DIG_CFG_SIGDET_TESTMODE: u32 = BIT(6);
macro_rules! HSIO_S6G_DIG_CFG_SIGDET_AST { ($x:expr) => { ((($x) << 3) & GENMASK(5, 3)) }; }
pub const HSIO_S6G_DIG_CFG_SIGDET_AST_M: u32 = GENMASK(5, 3);
macro_rules! HSIO_S6G_DIG_CFG_SIGDET_AST_X { ($x:expr) => { ((($x) & GENMASK(5, 3)) >> 3) }; }
macro_rules! HSIO_S6G_DIG_CFG_SIGDET_DST { ($x:expr) => { (($x) & GENMASK(2, 0)) }; }
pub const HSIO_S6G_DIG_CFG_SIGDET_DST_M: u32 = GENMASK(2, 0);

pub const HSIO_S6G_DFT_CFG0_LAZYBIT: u32 = BIT(31);
pub const HSIO_S6G_DFT_CFG0_INV_DIS: u32 = BIT(23);
macro_rules! HSIO_S6G_DFT_CFG0_PRBS_SEL { ($x:expr) => { ((($x) << 20) & GENMASK(21, 20)) }; }
pub const HSIO_S6G_DFT_CFG0_PRBS_SEL_M: u32 = GENMASK(21, 20);
macro_rules! HSIO_S6G_DFT_CFG0_PRBS_SEL_X { ($x:expr) => { ((($x) & GENMASK(21, 20)) >> 20) }; }
macro_rules! HSIO_S6G_DFT_CFG0_TEST_MODE { ($x:expr) => { ((($x) << 16) & GENMASK(18, 16)) }; }
pub const HSIO_S6G_DFT_CFG0_TEST_MODE_M: u32 = GENMASK(18, 16);
macro_rules! HSIO_S6G_DFT_CFG0_TEST_MODE_X { ($x:expr) => { ((($x) & GENMASK(18, 16)) >> 16) }; }
pub const HSIO_S6G_DFT_CFG0_RX_PHS_CORR_DIS: u32 = BIT(4);
pub const HSIO_S6G_DFT_CFG0_RX_PDSENS_ENA: u32 = BIT(3);
pub const HSIO_S6G_DFT_CFG0_RX_DFT_ENA: u32 = BIT(2);
pub const HSIO_S6G_DFT_CFG0_TX_DFT_ENA: u32 = BIT(0);

macro_rules! HSIO_S6G_DFT_CFG1_TX_JITTER_AMPL { ($x:expr) => { ((($x) << 8) & GENMASK(17, 8)) }; }
pub const HSIO_S6G_DFT_CFG1_TX_JITTER_AMPL_M: u32 = GENMASK(17, 8);
macro_rules! HSIO_S6G_DFT_CFG1_TX_JITTER_AMPL_X { ($x:expr) => { ((($x) & GENMASK(17, 8)) >> 8) }; }
macro_rules! HSIO_S6G_DFT_CFG1_TX_STEP_FREQ { ($x:expr) => { ((($x) << 4) & GENMASK(7, 4)) }; }
pub const HSIO_S6G_DFT_CFG1_TX_STEP_FREQ_M: u32 = GENMASK(7, 4);
macro_rules! HSIO_S6G_DFT_CFG1_TX_STEP_FREQ_X { ($x:expr) => { ((($x) & GENMASK(7, 4)) >> 4) }; }
pub const HSIO_S6G_DFT_CFG1_TX_JI_ENA: u32 = BIT(3);
pub const HSIO_S6G_DFT_CFG1_TX_WAVEFORM_SEL: u32 = BIT(2);
pub const HSIO_S6G_DFT_CFG1_TX_FREQOFF_DIR: u32 = BIT(1);
pub const HSIO_S6G_DFT_CFG1_TX_FREQOFF_ENA: u32 = BIT(0);

macro_rules! HSIO_S6G_DFT_CFG2_RX_JITTER_AMPL { ($x:expr) => { ((($x) << 8) & GENMASK(17, 8)) }; }
pub const HSIO_S6G_DFT_CFG2_RX_JITTER_AMPL_M: u32 = GENMASK(17, 8);
macro_rules! HSIO_S6G_DFT_CFG2_RX_JITTER_AMPL_X { ($x:expr) => { ((($x) & GENMASK(17, 8)) >> 8) }; }
macro_rules! HSIO_S6G_DFT_CFG2_RX_STEP_FREQ { ($x:expr) => { ((($x) << 4) & GENMASK(7, 4)) }; }
pub const HSIO_S6G_DFT_CFG2_RX_STEP_FREQ_M: u32 = GENMASK(7, 4);
macro_rules! HSIO_S6G_DFT_CFG2_RX_STEP_FREQ_X { ($x:expr) => { ((($x) & GENMASK(7, 4)) >> 4) }; }
pub const HSIO_S6G_DFT_CFG2_RX_JI_ENA: u32 = BIT(3);
pub const HSIO_S6G_DFT_CFG2_RX_WAVEFORM_SEL: u32 = BIT(2);
pub const HSIO_S6G_DFT_CFG2_RX_FREQOFF_DIR: u32 = BIT(1);
pub const HSIO_S6G_DFT_CFG2_RX_FREQOFF_ENA: u32 = BIT(0);

pub const HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_ENA: u32 = BIT(20);
macro_rules! HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_FBS_HIGH { ($x:expr) => { ((($x) << 16) & GENMASK(19, 16)) }; }
pub const HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_FBS_HIGH_M: u32 = GENMASK(19, 16);
macro_rules! HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_FBS_HIGH_X { ($x:expr) => { ((($x) & GENMASK(19, 16)) >> 16) }; }
macro_rules! HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_HIGH { ($x:expr) => { ((($x) << 8) & GENMASK(15, 8)) }; }
pub const HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_HIGH_M: u32 = GENMASK(15, 8);
macro_rules! HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_HIGH_X { ($x:expr) => { ((($x) & GENMASK(15, 8)) >> 8) }; }
macro_rules! HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_LOW { ($x:expr) => { (($x) & GENMASK(7, 0)) }; }
pub const HSIO_S6G_RC_PLL_BIST_CFG_PLL_BIST_LOW_M: u32 = GENMASK(7, 0);

macro_rules! HSIO_S6G_MISC_CFG_SEL_RECO_CLK { ($x:expr) => { ((($x) << 13) & GENMASK(14, 13)) }; }
pub const HSIO_S6G_MISC_CFG_SEL_RECO_CLK_M: u32 = GENMASK(14, 13);
macro_rules! HSIO_S6G_MISC_CFG_SEL_RECO_CLK_X { ($x:expr) => { ((($x) & GENMASK(14, 13)) >> 13) }; }
macro_rules! HSIO_S6G_MISC_CFG_DES_100FX_KICK_MODE { ($x:expr) => { ((($x) << 11) & GENMASK(12, 11)) }; }
pub const HSIO_S6G_MISC_CFG_DES_100FX_KICK_MODE_M: u32 = GENMASK(12, 11);
macro_rules! HSIO_S6G_MISC_CFG_DES_100FX_KICK_MODE_X { ($x:expr) => { ((($x) & GENMASK(12, 11)) >> 11) }; }
pub const HSIO_S6G_MISC_CFG_DES_100FX_CPMD_SWAP: u32 = BIT(10);
pub const HSIO_S6G_MISC_CFG_DES_100FX_CPMD_MODE: u32 = BIT(9);
pub const HSIO_S6G_MISC_CFG_DES_100FX_CPMD_ENA: u32 = BIT(8);
pub const HSIO_S6G_MISC_CFG_RX_BUS_FLIP_ENA: u32 = BIT(7);
pub const HSIO_S6G_MISC_CFG_TX_BUS_FLIP_ENA: u32 = BIT(6);
pub const HSIO_S6G_MISC_CFG_RX_LPI_MODE_ENA: u32 = BIT(5);
pub const HSIO_S6G_MISC_CFG_TX_LPI_MODE_ENA: u32 = BIT(4);
pub const HSIO_S6G_MISC_CFG_RX_DATA_INV_ENA: u32 = BIT(3);
pub const HSIO_S6G_MISC_CFG_TX_DATA_INV_ENA: u32 = BIT(2);
pub const HSIO_S6G_MISC_CFG_LANE_RST: u32 = BIT(0);

macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_POST0 { ($x:expr) => { ((($x) << 23) & GENMASK(28, 23)) }; }
pub const HSIO_S6G_OB_ANEG_CFG_AN_OB_POST0_M: u32 = GENMASK(28, 23);
macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_POST0_X { ($x:expr) => { ((($x) & GENMASK(28, 23)) >> 23) }; }
macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_POST1 { ($x:expr) => { ((($x) << 18) & GENMASK(22, 18)) }; }
pub const HSIO_S6G_OB_ANEG_CFG_AN_OB_POST1_M: u32 = GENMASK(22, 18);
macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_POST1_X { ($x:expr) => { ((($x) & GENMASK(22, 18)) >> 18) }; }
macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_PREC { ($x:expr) => { ((($x) << 13) & GENMASK(17, 13)) }; }
pub const HSIO_S6G_OB_ANEG_CFG_AN_OB_PREC_M: u32 = GENMASK(17, 13);
macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_PREC_X { ($x:expr) => { ((($x) & GENMASK(17, 13)) >> 13) }; }
macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_ENA_CAS { ($x:expr) => { ((($x) << 6) & GENMASK(8, 6)) }; }
pub const HSIO_S6G_OB_ANEG_CFG_AN_OB_ENA_CAS_M: u32 = GENMASK(8, 6);
macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_ENA_CAS_X { ($x:expr) => { ((($x) & GENMASK(8, 6)) >> 6) }; }
macro_rules! HSIO_S6G_OB_ANEG_CFG_AN_OB_LEV { ($x:expr) => { (($x) & GENMASK(5, 0)) }; }
pub const HSIO_S6G_OB_ANEG_CFG_AN_OB_LEV_M: u32 = GENMASK(5, 0);

pub const HSIO_S6G_DFT_STATUS_PRBS_SYNC_STAT: u32 = BIT(8);
pub const HSIO_S6G_DFT_STATUS_PLL_BIST_NOT_DONE: u32 = BIT(7);
pub const HSIO_S6G_DFT_STATUS_PLL_BIST_FAILED: u32 = BIT(6);
pub const HSIO_S6G_DFT_STATUS_PLL_BIST_TIMEOUT_ERR: u32 = BIT(5);
pub const HSIO_S6G_DFT_STATUS_BIST_ACTIVE: u32 = BIT(3);
pub const HSIO_S6G_DFT_STATUS_BIST_NOSYNC: u32 = BIT(2);
pub const HSIO_S6G_DFT_STATUS_BIST_COMPLETE_N: u32 = BIT(1);
pub const HSIO_S6G_DFT_STATUS_BIST_ERROR: u32 = BIT(0);

pub const HSIO_S6G_MISC_STATUS_DES_100FX_PHASE_SEL: u32 = BIT(0);

macro_rules! HSIO_S6G_DES_CFG_DES_PHS_CTRL { ($x:expr) => { ((($x) << 13) & GENMASK(16, 13)) }; }
pub const HSIO_S6G_DES_CFG_DES_PHS_CTRL_M: u32 = GENMASK(16, 13);
macro_rules! HSIO_S6G_DES_CFG_DES_PHS_CTRL_X { ($x:expr) => { ((($x) & GENMASK(16, 13)) >> 13) }; }
macro_rules! HSIO_S6G_DES_CFG_DES_MBTR_CTRL { ($x:expr) => { ((($x) << 10) & GENMASK(12, 10)) }; }
pub const HSIO_S6G_DES_CFG_DES_MBTR_CTRL_M: u32 = GENMASK(12, 10);
macro_rules! HSIO_S6G_DES_CFG_DES_MBTR_CTRL_X { ($x:expr) => { ((($x) & GENMASK(12, 10)) >> 10) }; }
macro_rules! HSIO_S6G_DES_CFG_DES_CPMD_SEL { ($x:expr) => { ((($x) << 8) & GENMASK(9, 8)) }; }
pub const HSIO_S6G_DES_CFG_DES_CPMD_SEL_M: u32 = GENMASK(9, 8);
macro_rules! HSIO_S6G_DES_CFG_DES_CPMD_SEL_X { ($x:expr) => { ((($x) & GENMASK(9, 8)) >> 8) }; }
macro_rules! HSIO_S6G_DES_CFG_DES_BW_HYST { ($x:expr) => { ((($x) << 5) & GENMASK(7, 5)) }; }
pub const HSIO_S6G_DES_CFG_DES_BW_HYST_M: u32 = GENMASK(7, 5);
macro_rules! HSIO_S6G_DES_CFG_DES_BW_HYST_X { ($x:expr) => { ((($x) & GENMASK(7, 5)) >> 5) }; }
pub const HSIO_S6G_DES_CFG_DES_SWAP_HYST: u32 = BIT(4);
macro_rules! HSIO_S6G_DES_CFG_DES_BW_ANA { ($x:expr) => { ((($x) << 1) & GENMASK(3, 1)) }; }
pub const HSIO_S6G_DES_CFG_DES_BW_ANA_M: u32 = GENMASK(3, 1);
macro_rules! HSIO_S6G_DES_CFG_DES_BW_ANA_X { ($x:expr) => { ((($x) & GENMASK(3, 1)) >> 1) }; }
pub const HSIO_S6G_DES_CFG_DES_SWAP_ANA: u32 = BIT(0);

macro_rules! HSIO_S6G_IB_CFG_IB_SOFSI { ($x:expr) => { ((($x) << 29) & GENMASK(30, 29)) }; }
pub const HSIO_S6G_IB_CFG_IB_SOFSI_M: u32 = GENMASK(30, 29);
macro_rules! HSIO_S6G_IB_CFG_IB_SOFSI_X { ($x:expr) => { ((($x) & GENMASK(30, 29)) >> 29) }; }
pub const HSIO_S6G_IB_CFG_IB_VBULK_SEL: u32 = BIT(28);
macro_rules! HSIO_S6G_IB_CFG_IB_RTRM_ADJ { ($x:expr) => { ((($x) << 24) & GENMASK(27, 24)) }; }
pub const HSIO_S6G_IB_CFG_IB_RTRM_ADJ_M: u32 = GENMASK(27, 24);
macro_rules! HSIO_S6G_IB_CFG_IB_RTRM_ADJ_X { ($x:expr) => { ((($x) & GENMASK(27, 24)) >> 24) }; }
macro_rules! HSIO_S6G_IB_CFG_IB_ICML_ADJ { ($x:expr) => { ((($x) << 20) & GENMASK(23, 20)) }; }
pub const HSIO_S6G_IB_CFG_IB_ICML_ADJ_M: u32 = GENMASK(23, 20);
macro_rules! HSIO_S6G_IB_CFG_IB_ICML_ADJ_X { ($x:expr) => { ((($x) & GENMASK(23, 20)) >> 20) }; }
macro_rules! HSIO_S6G_IB_CFG_IB_TERM_MODE_SEL { ($x:expr) => { ((($x) << 18) & GENMASK(19, 18)) }; }
pub const HSIO_S6G_IB_CFG_IB_TERM_MODE_SEL_M: u32 = GENMASK(19, 18);
macro_rules! HSIO_S6G_IB_CFG_IB_TERM_MODE_SEL_X { ($x:expr) => { ((($x) & GENMASK(19, 18)) >> 18) }; }
macro_rules! HSIO_S6G_IB_CFG_IB_SIG_DET_CLK_SEL { ($x:expr) => { ((($x) << 15) & GENMASK(17, 15)) }; }
pub const HSIO_S6G_IB_CFG_IB_SIG_DET_CLK_SEL_M: u32 = GENMASK(17, 15);
macro_rules! HSIO_S6G_IB_CFG_IB_SIG_DET_CLK_SEL_X { ($x:expr) => { ((($x) & GENMASK(17, 15)) >> 15) }; }
macro_rules! HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_HP { ($x:expr) => { ((($x) << 13) & GENMASK(14, 13)) }; }
pub const HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_HP_M: u32 = GENMASK(14, 13);
macro_rules! HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_HP_X { ($x:expr) => { ((($x) & GENMASK(14, 13)) >> 13) }; }
macro_rules! HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_MID { ($x:expr) => { ((($x) << 11) & GENMASK(12, 11)) }; }
pub const HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_MID_M: u32 = GENMASK(12, 11);
macro_rules! HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_MID_X { ($x:expr) => { ((($x) & GENMASK(12, 11)) >> 11) }; }
macro_rules! HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_LP { ($x:expr) => { ((($x) << 9) & GENMASK(10, 9)) }; }
pub const HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_LP_M: u32 = GENMASK(10, 9);
macro_rules! HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_LP_X { ($x:expr) => { ((($x) & GENMASK(10, 9)) >> 9) }; }
macro_rules! HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_OFFSET { ($x:expr) => { ((($x) << 7) & GENMASK(8, 7)) }; }
pub const HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_OFFSET_M: u32 = GENMASK(8, 7);
macro_rules! HSIO_S6G_IB_CFG_IB_REG_PAT_SEL_OFFSET_X { ($x:expr) => { ((($x) & GENMASK(8, 7)) >> 7) }; }
pub const HSIO_S6G_IB_CFG_IB_ANA_TEST_ENA: u32 = BIT(6);
pub const HSIO_S6G_IB_CFG_IB_SIG_DET_ENA: u32 = BIT(5);
pub const HSIO_S6G_IB_CFG_IB_CONCUR: u32 = BIT(4);
pub const HSIO_S6G_IB_CFG_IB_CAL_ENA: u32 = BIT(3);
pub const HSIO_S6G_IB_CFG_IB_SAM_ENA: u32 = BIT(2);
pub const HSIO_S6G_IB_CFG_IB_EQZ_ENA: u32 = BIT(1);
pub const HSIO_S6G_IB_CFG_IB_REG_ENA: u32 = BIT(0);

macro_rules! HSIO_S6G_IB_CFG1_IB_TJTAG { ($x:expr) => { ((($x) << 17) & GENMASK(21, 17)) }; }
pub const HSIO_S6G_IB_CFG1_IB_TJTAG_M: u32 = GENMASK(21, 17);
macro_rules! HSIO_S6G_IB_CFG1_IB_TJTAG_X { ($x:expr) => { ((($x) & GENMASK(21, 17)) >> 17) }; }
macro_rules! HSIO_S6G_IB_CFG1_IB_TSDET { ($x:expr) => { ((($x) << 12) & GENMASK(16, 12)) }; }
pub const HSIO_S6G_IB_CFG1_IB_TSDET_M: u32 = GENMASK(16, 12);
macro_rules! HSIO_S6G_IB_CFG1_IB_TSDET_X { ($x:expr) => { ((($x) & GENMASK(16, 12)) >> 12) }; }
macro_rules! HSIO_S6G_IB_CFG1_IB_SCALY { ($x:expr) => { ((($x) << 8) & GENMASK(11, 8)) }; }
pub const HSIO_S6G_IB_CFG1_IB_SCALY_M: u32 = GENMASK(11, 8);
macro_rules! HSIO_S6G_IB_CFG1_IB_SCALY_X { ($x:expr) => { ((($x) & GENMASK(11, 8)) >> 8) }; }
pub const HSIO_S6G_IB_CFG1_IB_FILT_HP: u32 = BIT(7);
pub const HSIO_S6G_IB_CFG1_IB_FILT_MID: u32 = BIT(6);
pub const HSIO_S6G_IB_CFG1_IB_FILT_LP: u32 = BIT(5);
pub const HSIO_S6G_IB_CFG1_IB_FILT_OFFSET: u32 = BIT(4);
pub const HSIO_S6G_IB_CFG1_IB_FRC_HP: u32 = BIT(3);
pub const HSIO_S6G_IB_CFG1_IB_FRC_MID: u32 = BIT(2);
pub const HSIO_S6G_IB_CFG1_IB_FRC_LP: u32 = BIT(1);
pub const HSIO_S6G_IB_CFG1_IB_FRC_OFFSET: u32 = BIT(0);

macro_rules! HSIO_S6G_IB_CFG2_IB_TINFV { ($x:expr) => { ((($x) << 27) & GENMASK(29, 27)) }; }
pub const HSIO_S6G_IB_CFG2_IB_TINFV_M: u32 = GENMASK(29, 27);
macro_rules! HSIO_S6G_IB_CFG2_IB_TINFV_X { ($x:expr) => { ((($x) & GENMASK(29, 27)) >> 27) }; }
macro_rules! HSIO_S6G_IB_CFG2_IB_OINFI { ($x:expr) => { ((($x) << 22) & GENMASK(26, 22)) }; }
pub const HSIO_S6G_IB_CFG2_IB_OINFI_M: u32 = GENMASK(26, 22);
macro_rules! HSIO_S6G_IB_CFG2_IB_OINFI_X { ($x:expr) => { ((($x) & GENMASK(26, 22)) >> 22) }; }
macro_rules! HSIO_S6G_IB_CFG2_IB_TAUX { ($x:expr) => { ((($x) << 19) & GENMASK(21, 19)) }; }
pub const HSIO_S6G_IB_CFG2_IB_TAUX_M: u32 = GENMASK(21, 19);
macro_rules! HSIO_S6G_IB_CFG2_IB_TAUX_X { ($x:expr) => { ((($x) & GENMASK(21, 19)) >> 19) }; }
macro_rules! HSIO_S6G_IB_CFG2_IB_OINFS { ($x:expr) => { ((($x) << 16) & GENMASK(18, 16)) }; }
pub const HSIO_S6G_IB_CFG2_IB_OINFS_M: u32 = GENMASK(18, 16);
macro_rules! HSIO_S6G_IB_CFG2_IB_OINFS_X { ($x:expr) => { ((($x) & GENMASK(18, 16)) >> 16) }; }
macro_rules! HSIO_S6G_IB_CFG2_IB_OCALS { ($x:expr) => { ((($x) << 10) & GENMASK(15, 10)) }; }
pub const HSIO_S6G_IB_CFG2_IB_OCALS_M: u32 = GENMASK(15, 10);
macro_rules! HSIO_S6G_IB_CFG2_IB_OCALS_X { ($x:expr) => { ((($x) & GENMASK(15, 10)) >> 10) }; }
macro_rules! HSIO_S6G_IB_CFG2_IB_TCALV { ($x:expr) => { ((($x) << 5) & GENMASK(9, 5)) }; }
pub const HSIO_S6G_IB_CFG2_IB_TCALV_M: u32 = GENMASK(9, 5);
macro_rules! HSIO_S6G_IB_CFG2_IB_TCALV_X { ($x:expr) => { ((($x) & GENMASK(9, 5)) >> 5) }; }
macro_rules! HSIO_S6G_IB_CFG2_IB_UMAX { ($x:expr) => { ((($x) << 3) & GENMASK(4, 3)) }; }
pub const HSIO_S6G_IB_CFG2_IB_UMAX_M: u32 = GENMASK(4, 3);
macro_rules! HSIO_S6G_IB_CFG2_IB_UMAX_X { ($x:expr) => { ((($x) & GENMASK(4, 3)) >> 3) }; }
macro_rules! HSIO_S6G_IB_CFG2_IB_UREG { ($x:expr) => { (($x) & GENMASK(2, 0)) }; }
pub const HSIO_S6G_IB_CFG2_IB_UREG_M: u32 = GENMASK(2, 0);

macro_rules! HSIO_S6G_IB_CFG3_IB_INI_HP { ($x:expr) => { ((($x) << 18) & GENMASK(23, 18)) }; }
pub const HSIO_S6G_IB_CFG3_IB_INI_HP_M: u32 = GENMASK(23, 18);
macro_rules! HSIO_S6G_IB_CFG3_IB_INI_HP_X { ($x:expr) => { ((($x) & GENMASK(23, 18)) >> 18) }; }
macro_rules! HSIO_S6G_IB_CFG3_IB_INI_MID { ($x:expr) => { ((($x) << 12) & GENMASK(17, 12)) }; }
pub const HSIO_S6G_IB_CFG3_IB_INI_MID_M: u32 = GENMASK(17, 12);
macro_rules! HSIO_S6G_IB_CFG3_IB_INI_MID_X { ($x:expr) => { ((($x) & GENMASK(17, 12)) >> 12) }; }
macro_rules! HSIO_S6G_IB_CFG3_IB_INI_LP { ($x:expr) => { ((($x) << 6) & GENMASK(11, 6)) }; }
pub const HSIO_S6G_IB_CFG3_IB_INI_LP_M: u32 = GENMASK(11, 6);
macro_rules! HSIO_S6G_IB_CFG3_IB_INI_LP_X { ($x:expr) => { ((($x) & GENMASK(11, 6)) >> 6) }; }
macro_rules! HSIO_S6G_IB_CFG3_IB_INI_OFFSET { ($x:expr) => { (($x) & GENMASK(5, 0)) }; }
pub const HSIO_S6G_IB_CFG3_IB_INI_OFFSET_M: u32 = GENMASK(5, 0);

macro_rules! HSIO_S6G_IB_CFG4_IB_MAX_HP { ($x:expr) => { ((($x) << 18) & GENMASK(23, 18)) }; }
pub const HSIO_S6G_IB_CFG4_IB_MAX_HP_M: u32 = GENMASK(23, 18);
macro_rules! HSIO_S6G_IB_CFG4_IB_MAX_HP_X { ($x:expr) => { ((($x) & GENMASK(23, 18)) >> 18) }; }
macro_rules! HSIO_S6G_IB_CFG4_IB_MAX_MID { ($x:expr) => { ((($x) << 12) & GENMASK(17, 12)) }; }
pub const HSIO_S6G_IB_CFG4_IB_MAX_MID_M: u32 = GENMASK(17, 12);
macro_rules! HSIO_S6G_IB_CFG4_IB_MAX_MID_X { ($x:expr) => { ((($x) & GENMASK(17, 12)) >> 12) }; }
macro_rules! HSIO_S6G_IB_CFG4_IB_MAX_LP { ($x:expr) => { ((($x) << 6) & GENMASK(11, 6)) }; }
pub const HSIO_S6G_IB_CFG4_IB_MAX_LP_M: u32 = GENMASK(11, 6);
macro_rules! HSIO_S6G_IB_CFG4_IB_MAX_LP_X { ($x:expr) => { ((($x) & GENMASK(11, 6)) >> 6) }; }
macro_rules! HSIO_S6G_IB_CFG4_IB_MAX_OFFSET { ($x:expr) => { (($x) & GENMASK(5, 0)) }; }
pub const HSIO_S6G_IB_CFG4_IB_MAX_OFFSET_M: u32 = GENMASK(5, 0);

macro_rules! HSIO_S6G_IB_CFG5_IB_MIN_HP { ($x:expr) => { ((($x) << 18) & GENMASK(23, 18)) }; }
pub const HSIO_S6G_IB_CFG5_IB_MIN_HP_M: u32 = GENMASK(23, 18);
macro_rules! HSIO_S6G_IB_CFG5_IB_MIN_HP_X { ($x:expr) => { ((($x) & GENMASK(23, 18)) >> 18) }; }
macro_rules! HSIO_S6G_IB_CFG5_IB_MIN_MID { ($x:expr) => { ((($x) << 12) & GENMASK(17, 12)) }; }
pub const HSIO_S6G_IB_CFG5_IB_MIN_MID_M: u32 = GENMASK(17, 12);
macro_rules! HSIO_S6G_IB_CFG5_IB_MIN_MID_X { ($x:expr) => { ((($x) & GENMASK(17, 12)) >> 12) }; }
macro_rules! HSIO_S6G_IB_CFG5_IB_MIN_LP { ($x:expr) => { ((($x) << 6) & GENMASK(11, 6)) }; }
pub const HSIO_S6G_IB_CFG5_IB_MIN_LP_M: u32 = GENMASK(11, 6);
macro_rules! HSIO_S6G_IB_CFG5_IB_MIN_LP_X { ($x:expr) => { ((($x) & GENMASK(11, 6)) >> 6) }; }
macro_rules! HSIO_S6G_IB_CFG5_IB_MIN_OFFSET { ($x:expr) => { (($x) & GENMASK(5, 0)) }; }
pub const HSIO_S6G_IB_CFG5_IB_MIN_OFFSET_M: u32 = GENMASK(5, 0);

pub const HSIO_S6G_OB_CFG_OB_IDLE: u32 = BIT(31);
pub const HSIO_S6G_OB_CFG_OB_ENA1V_MODE: u32 = BIT(30);
pub const HSIO_S6G_OB_CFG_OB_POL: u32 = BIT(29);
macro_rules! HSIO_S6G_OB_CFG_OB_POST0 { ($x:expr) => { ((($x) << 23) & GENMASK(28, 23)) }; }
pub const HSIO_S6G_OB_CFG_OB_POST0_M: u32 = GENMASK(28, 23);
macro_rules! HSIO_S6G_OB_CFG_OB_POST0_X { ($x:expr) => { ((($x) & GENMASK(28, 23)) >> 23) }; }
macro_rules! HSIO_S6G_OB_CFG_OB_PREC { ($x:expr) => { ((($x) << 18) & GENMASK(22, 18)) }; }
pub const HSIO_S6G_OB_CFG_OB_PREC_M: u32 = GENMASK(22, 18);
macro_rules! HSIO_S6G_OB_CFG_OB_PREC_X { ($x:expr) => { ((($x) & GENMASK(22, 18)) >> 18) }; }
pub const HSIO_S6G_OB_CFG_OB_R_ADJ_MUX: u32 = BIT(17);
pub const HSIO_S6G_OB_CFG_OB_R_ADJ_PDR: u32 = BIT(16);
macro_rules! HSIO_S6G_OB_CFG_OB_POST1 { ($x:expr) => { ((($x) << 11) & GENMASK(15, 11)) }; }
pub const HSIO_S6G_OB_CFG_OB_POST1_M: u32 = GENMASK(15, 11);
macro_rules! HSIO_S6G_OB_CFG_OB_POST1_X { ($x:expr) => { ((($x) & GENMASK(15, 11)) >> 11) }; }
pub const HSIO_S6G_OB_CFG_OB_R_COR: u32 = BIT(10);
pub const HSIO_S6G_OB_CFG_OB_SEL_RCTRL: u32 = BIT(9);
pub const HSIO_S6G_OB_CFG_OB_SR_H: u32 = BIT(8);
macro_rules! HSIO_S6G_OB_CFG_OB_SR { ($x:expr) => { ((($x) << 4) & GENMASK(7, 4)) }; }
pub const HSIO_S6G_OB_CFG_OB_SR_M: u32 = GENMASK(7, 4);
macro_rules! HSIO_S6G_OB_CFG_OB_SR_X { ($x:expr) => { ((($x) & GENMASK(7, 4)) >> 4) }; }
macro_rules! HSIO_S6G_OB_CFG_OB_RESISTOR_CTRL { ($x:expr) => { (($x) & GENMASK(3, 0)) }; }
pub const HSIO_S6G_OB_CFG_OB_RESISTOR_CTRL_M: u32 = GENMASK(3, 0);

macro_rules! HSIO_S6G_OB_CFG1_OB_ENA_CAS { ($x:expr) => { ((($x) << 6) & GENMASK(8, 6)) }; }
pub const HSIO_S6G_OB_CFG1_OB_ENA_CAS_M: u32 = GENMASK(8, 6);
macro_rules! HSIO_S6G_OB_CFG1_OB_ENA_CAS_X { ($x:expr) => { ((($x) & GENMASK(8, 6)) >> 6) }; }
macro_rules! HSIO_S6G_OB_CFG1_OB_LEV { ($x:expr) => { (($x) & GENMASK(5, 0)) }; }
pub const HSIO_S6G_OB_CFG1_OB_LEV_M: u32 = GENMASK(5, 0);

pub const HSIO_S6G_SER_CFG_SER_4TAP_ENA: u32 = BIT(8);
pub const HSIO_S6G_SER_CFG_SER_CPMD_SEL: u32 = BIT(7);
pub const HSIO_S6G_SER_CFG_SER_SWAP_CPMD: u32 = BIT(6);
macro_rules! HSIO_S6G_SER_CFG_SER_ALISEL { ($x:expr) => { ((($x) << 4) & GENMASK(5, 4)) }; }
pub const HSIO_S6G_SER_CFG_SER_ALISEL_M: u32 = GENMASK(5, 4);
macro_rules! HSIO_S6G_SER_CFG_SER_ALISEL_X { ($x:expr) => { ((($x) & GENMASK(5, 4)) >> 4) }; }
pub const HSIO_S6G_SER_CFG_SER_ENHYS: u32 = BIT(3);
pub const HSIO_S6G_SER_CFG_SER_BIG_WIN: u32 = BIT(2);
pub const HSIO_S6G_SER_CFG_SER_EN_WIN: u32 = BIT(1);
pub const HSIO_S6G_SER_CFG_SER_ENALI: u32 = BIT(0);

pub const HSIO_S6G_COMMON_CFG_SYS_RST: u32 = BIT(17);
pub const HSIO_S6G_COMMON_CFG_SE_DIV2_ENA: u32 = BIT(16);
pub const HSIO_S6G_COMMON_CFG_SE_AUTO_SQUELCH_ENA: u32 = BIT(15);
pub const HSIO_S6G_COMMON_CFG_ENA_LANE: u32 = BIT(14);
pub const HSIO_S6G_COMMON_CFG_PWD_RX: u32 = BIT(13);
pub const HSIO_S6G_COMMON_CFG_PWD_TX: u32 = BIT(12);
macro_rules! HSIO_S6G_COMMON_CFG_LANE_CTRL { ($x:expr) => { ((($x) << 9) & GENMASK(11, 9)) }; }
pub const HSIO_S6G_COMMON_CFG_LANE_CTRL_M: u32 = GENMASK(11, 9);
macro_rules! HSIO_S6G_COMMON_CFG_LANE_CTRL_X { ($x:expr) => { ((($x) & GENMASK(11, 9)) >> 9) }; }
pub const HSIO_S6G_COMMON_CFG_ENA_DIRECT: u32 = BIT(8);
pub const HSIO_S6G_COMMON_CFG_ENA_ELOOP: u32 = BIT(7);
pub const HSIO_S6G_COMMON_CFG_ENA_FLOOP: u32 = BIT(6);
pub const HSIO_S6G_COMMON_CFG_ENA_ILOOP: u32 = BIT(5);
pub const HSIO_S6G_COMMON_CFG_ENA_PLOOP: u32 = BIT(4);
pub const HSIO_S6G_COMMON_CFG_HRATE: u32 = BIT(3);
pub const HSIO_S6G_COMMON_CFG_QRATE: u32 = BIT(2);
macro_rules! HSIO_S6G_COMMON_CFG_IF_MODE { ($x:expr) => { (($x) & GENMASK(1, 0)) }; }
pub const HSIO_S6G_COMMON_CFG_IF_MODE_M: u32 = GENMASK(1, 0);

macro_rules! HSIO_S6G_PLL_CFG_PLL_ENA_OFFS { ($x:expr) => { ((($x) << 16) & GENMASK(17, 16)) }; }
pub const HSIO_S6G_PLL_CFG_PLL_ENA_OFFS_M: u32 = GENMASK(17, 16);
macro_rules! HSIO_S6G_PLL_CFG_PLL_ENA_OFFS_X { ($x:expr) => { ((($x) & GENMASK(17, 16)) >> 16) }; }
pub const HSIO_S6G_PLL_CFG_PLL_DIV4: u32 = BIT(15);
pub const HSIO_S6G_PLL_CFG_PLL_ENA_ROT: u32 = BIT(14);
macro_rules! HSIO_S6G_PLL_CFG_PLL_FSM_CTRL_DATA { ($x:expr) => { ((($x) << 6) & GENMASK(13, 6)) }; }
pub const HSIO_S6G_PLL_CFG_PLL_FSM_CTRL_DATA_M: u32 = GENMASK(13, 6);
macro_rules! HSIO_S6G_PLL_CFG_PLL_FSM_CTRL_DATA_X { ($x:expr) => { ((($x) & GENMASK(13, 6)) >> 6) }; }
pub const HSIO_S6G_PLL_CFG_PLL_FSM_ENA: u32 = BIT(5);
pub const HSIO_S6G_PLL_CFG_PLL_FSM_FORCE_SET_ENA: u32 = BIT(4);
pub const HSIO_S6G_PLL_CFG_PLL_FSM_OOR_RECAL_ENA: u32 = BIT(3);
pub const HSIO_S6G_PLL_CFG_PLL_RB_DATA_SEL: u32 = BIT(2);
pub const HSIO_S6G_PLL_CFG_PLL_ROT_DIR: u32 = BIT(1);
pub const HSIO_S6G_PLL_CFG_PLL_ROT_FRQ: u32 = BIT(0);

pub const HSIO_S6G_ACJTAG_CFG_ACJTAG_INIT_DATA_N: u32 = BIT(5);
pub const HSIO_S6G_ACJTAG_CFG_ACJTAG_INIT_DATA_P: u32 = BIT(4);
pub const HSIO_S6G_ACJTAG_CFG_ACJTAG_INIT_CLK: u32 = BIT(3);
pub const HSIO_S6G_ACJTAG_CFG_OB_DIRECT: u32 = BIT(2);
pub const HSIO_S6G_ACJTAG_CFG_ACJTAG_ENA: u32 = BIT(1);
pub const HSIO_S6G_ACJTAG_CFG_JTAG_CTRL_ENA: u32 = BIT(0);

macro_rules! HSIO_S6G_GP_CFG_GP_MSB { ($x:expr) => { ((($x) << 16) & GENMASK(31, 16)) }; }
pub const HSIO_S6G_GP_CFG_GP_MSB_M: u32 = GENMASK(31, 16);
macro_rules! HSIO_S6G_GP_CFG_GP_MSB_X { ($x:expr) => { ((($x) & GENMASK(31, 16)) >> 16) }; }
macro_rules! HSIO_S6G_GP_CFG_GP_LSB { ($x:expr) => { (($x) & GENMASK(15, 0)) }; }
pub const HSIO_S6G_GP_CFG_GP_LSB_M: u32 = GENMASK(15, 0);

pub const HSIO_S6G_IB_STATUS0_IB_CAL_DONE: u32 = BIT(8);
pub const HSIO_S6G_IB_STATUS0_IB_HP_GAIN_ACT: u32 = BIT(7);
pub const HSIO_S6G_IB_STATUS0_IB_MID_GAIN_ACT: u32 = BIT(6);
pub const HSIO_S6G_IB_STATUS0_IB_LP_GAIN_ACT: u32 = BIT(5);
pub const HSIO_S6G_IB_STATUS0_IB_OFFSET_ACT: u32 = BIT(4);
pub const HSIO_S6G_IB_STATUS0_IB_OFFSET_VLD: u32 = BIT(3);
pub const HSIO_S6G_IB_STATUS0_IB_OFFSET_ERR: u32 = BIT(2);
pub const HSIO_S6G_IB_STATUS0_IB_OFFSDIR: u32 = BIT(1);
pub const HSIO_S6G_IB_STATUS0_IB_SIG_DET: u32 = BIT(0);

macro_rules! HSIO_S6G_IB_STATUS1_IB_HP_GAIN_STAT { ($x:expr) => { ((($x) << 18) & GENMASK(23, 18)) }; }
pub const HSIO_S6G_IB_STATUS1_IB_HP_GAIN_STAT_M: u32 = GENMASK(23, 18);
macro_rules! HSIO_S6G_IB_STATUS1_IB_HP_GAIN_STAT_X { ($x:expr) => { ((($x) & GENMASK(23, 18)) >> 18) }; }
macro_rules! HSIO_S6G_IB_STATUS1_IB_MID_GAIN_STAT { ($x:expr) => { ((($x) << 12) & GENMASK(17, 12)) }; }
pub const HSIO_S6G_IB_STATUS1_IB_MID_GAIN_STAT_M: u32 = GENMASK(17, 12);
macro_rules! HSIO_S6G_IB_STATUS1_IB_MID_GAIN_STAT_X { ($x:expr) => { ((($x) & GENMASK(17, 12)) >> 12) }; }
macro_rules! HSIO_S6G_IB_STATUS1_IB_LP_GAIN_STAT { ($x:expr) => { ((($x) << 6) & GENMASK(11, 6)) }; }
pub const HSIO_S6G_IB_STATUS1_IB_LP_GAIN_STAT_M: u32 = GENMASK(11, 6);
macro_rules! HSIO_S6G_IB_STATUS1_IB_LP_GAIN_STAT_X { ($x:expr) => { ((($x) & GENMASK(11, 6)) >> 6) }; }
macro_rules! HSIO_S6G_IB_STATUS1_IB_OFFSET_STAT { ($x:expr) => { (($x) & GENMASK(5, 0)) }; }
pub const HSIO_S6G_IB_STATUS1_IB_OFFSET_STAT_M: u32 = GENMASK(5, 0);

pub const HSIO_S6G_ACJTAG_STATUS_ACJTAG_CAPT_DATA_N: u32 = BIT(2);
pub const HSIO_S6G_ACJTAG_STATUS_ACJTAG_CAPT_DATA_P: u32 = BIT(1);
pub const HSIO_S6G_ACJTAG_STATUS_IB_DIRECT: u32 = BIT(0);

pub const HSIO_S6G_PLL_STATUS_PLL_CAL_NOT_DONE: u32 = BIT(10);
pub const HSIO_S6G_PLL_STATUS_PLL_CAL_ERR: u32 = BIT(9);
pub const HSIO_S6G_PLL_STATUS_PLL_OUT_OF_RANGE_ERR: u32 = BIT(8);
macro_rules! HSIO_S6G_PLL_STATUS_PLL_RB_DATA { ($x:expr) => { (($x) & GENMASK(7, 0)) }; }
pub const HSIO_S6G_PLL_STATUS_PLL_RB_DATA_M: u32 = GENMASK(7, 0);

macro_rules! HSIO_S6G_REVID_SERDES_REV { ($x:expr) => { ((($x) << 26) & GENMASK(31, 26)) }; }
pub const HSIO_S6G_REVID_SERDES_REV_M: u32 = GENMASK(31, 26);
macro_rules! HSIO_S6G_REVID_SERDES_REV_X { ($x:expr) => { ((($x) & GENMASK(31, 26)) >> 26) }; }
macro_rules! HSIO_S6G_REVID_RCPLL_REV { ($x:expr) => { ((($x) << 21) & GENMASK(25, 21)) }; }
pub const HSIO_S6G_REVID_RCPLL_REV_M: u32 = GENMASK(25, 21);
macro_rules! HSIO_S6G_REVID_RCPLL_REV_X { ($x:expr) => { ((($x) & GENMASK(25, 21)) >> 21) }; }
macro_rules! HSIO_S6G_REVID_SER_REV { ($x:expr) => { ((($x) << 16) & GENMASK(20, 16)) }; }
pub const HSIO_S6G_REVID_SER_REV_M: u32 = GENMASK(20, 16);
macro_rules! HSIO_S6G_REVID_SER_REV_X { ($x:expr) => { ((($x) & GENMASK(20, 16)) >> 16) }; }
macro_rules! HSIO_S6G_REVID_DES_REV { ($x:expr) => { ((($x) << 10) & GENMASK(15, 10)) }; }
pub const HSIO_S6G_REVID_DES_REV_M: u32 = GENMASK(15, 10);
macro_rules! HSIO_S6G_REVID_DES_REV_X { ($x:expr) => { ((($x) & GENMASK(15, 10)) >> 10) }; }
macro_rules! HSIO_S6G_REVID_OB_REV { ($x:expr) => { ((($x) << 5) & GENMASK(9, 5)) }; }
pub const HSIO_S6G_REVID_OB_REV_M: u32 = GENMASK(9, 5);
macro_rules! HSIO_S6G_REVID_OB_REV_X { ($x:expr) => { ((($x) & GENMASK(9, 5)) >> 5) }; }
macro_rules! HSIO_S6G_REVID_IB_REV { ($x:expr) => { (($x) & GENMASK(4, 0)) }; }
pub const HSIO_S6G_REVID_IB_REV_M: u32 = GENMASK(4, 0);

pub const HSIO_MCB_S6G_ADDR_CFG_SERDES6G_WR_ONE_SHOT: u32 = BIT(31);
pub const HSIO_MCB_S6G_ADDR_CFG_SERDES6G_RD_ONE_SHOT: u32 = BIT(30);
macro_rules! HSIO_MCB_S6G_ADDR_CFG_SERDES6G_ADDR { ($x:expr) => { (($x) & GENMASK(24, 0)) }; }
pub const HSIO_MCB_S6G_ADDR_CFG_SERDES6G_ADDR_M: u32 = GENMASK(24, 0);

pub const HSIO_HW_CFG_DEV2G5_10_MODE: u32 = BIT(6);
pub const HSIO_HW_CFG_DEV1G_9_MODE: u32 = BIT(5);
pub const HSIO_HW_CFG_DEV1G_6_MODE: u32 = BIT(4);
pub const HSIO_HW_CFG_DEV1G_5_MODE: u32 = BIT(3);
pub const HSIO_HW_CFG_DEV1G_4_MODE: u32 = BIT(2);
pub const HSIO_HW_CFG_PCIE_ENA: u32 = BIT(1);
pub const HSIO_HW_CFG_QSGMII_ENA: u32 = BIT(0);

pub const HSIO_HW_QSGMII_CFG_SHYST_DIS: u32 = BIT(3);
pub const HSIO_HW_QSGMII_CFG_E_DET_ENA: u32 = BIT(2);
pub const HSIO_HW_QSGMII_CFG_USE_I1_ENA: u32 = BIT(1);
pub const HSIO_HW_QSGMII_CFG_FLIP_LANES: u32 = BIT(0);

macro_rules! HSIO_HW_QSGMII_STAT_DELAY_VAR_X200PS { ($x:expr) => { ((($x) << 1) & GENMASK(6, 1)) }; }
pub const HSIO_HW_QSGMII_STAT_DELAY_VAR_X200PS_M: u32 = GENMASK(6, 1);
macro_rules! HSIO_HW_QSGMII_STAT_DELAY_VAR_X200PS_X { ($x:expr) => { ((($x) & GENMASK(6, 1)) >> 1) }; }
pub const HSIO_HW_QSGMII_STAT_SYNC: u32 = BIT(0);

macro_rules! HSIO_CLK_CFG_CLKDIV_PHY { ($x:expr) => { ((($x) << 1) & GENMASK(8, 1)) }; }
pub const HSIO_CLK_CFG_CLKDIV_PHY_M: u32 = GENMASK(8, 1);
macro_rules! HSIO_CLK_CFG_CLKDIV_PHY_X { ($x:expr) => { ((($x) & GENMASK(8, 1)) >> 1) }; }
pub const HSIO_CLK_CFG_CLKDIV_PHY_DIS: u32 = BIT(0);

pub const HSIO_TEMP_SENSOR_CTRL_FORCE_TEMP_RD: u32 = BIT(5);
pub const HSIO_TEMP_SENSOR_CTRL_FORCE_RUN: u32 = BIT(4);
pub const HSIO_TEMP_SENSOR_CTRL_FORCE_NO_RST: u32 = BIT(3);
pub const HSIO_TEMP_SENSOR_CTRL_FORCE_POWER_UP: u32 = BIT(2);
pub const HSIO_TEMP_SENSOR_CTRL_FORCE_CLK: u32 = BIT(1);
pub const HSIO_TEMP_SENSOR_CTRL_SAMPLE_ENA: u32 = BIT(0);

macro_rules! HSIO_TEMP_SENSOR_CFG_RUN_WID { ($x:expr) => { ((($x) << 8) & GENMASK(15, 8)) }; }
pub const HSIO_TEMP_SENSOR_CFG_RUN_WID_M: u32 = GENMASK(15, 8);
macro_rules! HSIO_TEMP_SENSOR_CFG_RUN_WID_X { ($x:expr) => { ((($x) & GENMASK(15, 8)) >> 8) }; }
macro_rules! HSIO_TEMP_SENSOR_CFG_SAMPLE_PER { ($x:expr) => { (($x) & GENMASK(7, 0)) }; }
pub const HSIO_TEMP_SENSOR_CFG_SAMPLE_PER_M: u32 = GENMASK(7, 0);

pub const HSIO_TEMP_SENSOR_STAT_TEMP_VALID: u32 = BIT(8);
macro_rules! HSIO_TEMP_SENSOR_STAT_TEMP { ($x:expr) => { (($x) & GENMASK(7, 0)) }; }
pub const HSIO_TEMP_SENSOR_STAT_TEMP_M: u32 = GENMASK(7, 0);



// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
