// SPDX-License-Identifier: GPL-2.0
// Generated by xdrgen. Manual edits will be lost.
// XDR specification file: ../../Documentation/sunrpc/xdr/nlm4.x

// Translated from nlm4xdr_gen.c. Types and helpers are supplied by the
// corresponding kernel/XDR dependencies.

unsafe fn xdrgen_decode_netobj(xdr: *mut xdr_stream, ptr: *mut netobj) -> bool {
    xdrgen_decode_opaque(xdr, ptr, MAXNETOBJ_SZ)
}
unsafe fn xdrgen_decode_fsh4_mode(xdr: *mut xdr_stream, ptr: *mut fsh4_mode) -> bool {
    let mut val: u32 = 0;
    if xdr_stream_decode_u32(xdr, &mut val) < 0 { return false; }
    match val { fsm_DN | fsm_DR | fsm_DW | fsm_DRW => {}, _ => return false }
    *ptr = val; true
}
unsafe fn xdrgen_decode_fsh4_access(xdr: *mut xdr_stream, ptr: *mut fsh4_access) -> bool {
    let mut val: u32 = 0;
    if xdr_stream_decode_u32(xdr, &mut val) < 0 { return false; }
    match val { fsa_NONE | fsa_R | fsa_W | fsa_RW => {}, _ => return false }
    *ptr = val; true
}
unsafe fn xdrgen_decode_uint64(xdr: *mut xdr_stream, ptr: *mut uint64) -> bool { xdrgen_decode_unsigned_hyper(xdr, ptr) }
unsafe fn xdrgen_decode_int64(xdr: *mut xdr_stream, ptr: *mut int64) -> bool { xdrgen_decode_hyper(xdr, ptr) }
unsafe fn xdrgen_decode_uint32(xdr: *mut xdr_stream, ptr: *mut uint32) -> bool { xdrgen_decode_unsigned_long(xdr, ptr) }
unsafe fn xdrgen_decode_int32(xdr: *mut xdr_stream, ptr: *mut int32) -> bool { xdrgen_decode_long(xdr, ptr) }
unsafe fn xdrgen_decode_nlm4_stats(xdr: *mut xdr_stream, ptr: *mut nlm4_stats) -> bool {
    let mut raw: __be32 = 0; let mut val: u32;
    if xdr_stream_decode_be32(xdr, &mut raw) < 0 { return false; }
    val = be32_to_cpu(raw);
    match val { NLM4_GRANTED | NLM4_DENIED | NLM4_DENIED_NOLOCKS | NLM4_BLOCKED |
        NLM4_DENIED_GRACE_PERIOD | NLM4_DEADLCK | NLM4_ROFS | NLM4_STALE_FH |
        NLM4_FBIG | NLM4_FAILED => {}, _ => return false }
    *ptr = raw; true
}
unsafe fn xdrgen_decode_nlm4_holder(xdr: *mut xdr_stream, ptr: *mut nlm4_holder) -> bool {
    if !xdrgen_decode_bool(xdr, &mut (*ptr).exclusive) { return false; }
    if !xdrgen_decode_int32(xdr, &mut (*ptr).svid) { return false; }
    if !xdrgen_decode_netobj(xdr, &mut (*ptr).oh) { return false; }
    if !xdrgen_decode_uint64(xdr, &mut (*ptr).l_offset) { return false; }
    if !xdrgen_decode_uint64(xdr, &mut (*ptr).l_len) { return false; } true
}
unsafe fn xdrgen_decode_nlm4_testrply(xdr: *mut xdr_stream, ptr: *mut nlm4_testrply) -> bool {
    if !xdrgen_decode_nlm4_stats(xdr, &mut (*ptr).stat) { return false; }
    if (*ptr).stat == __constant_cpu_to_be32(NLM4_DENIED) && !xdrgen_decode_nlm4_holder(xdr, &mut (*ptr).u.holder) { return false; } true
}
unsafe fn xdrgen_decode_nlm4_stat(xdr: *mut xdr_stream, ptr: *mut nlm4_stat) -> bool { xdrgen_decode_nlm4_stats(xdr, &mut (*ptr).stat) }
unsafe fn xdrgen_decode_nlm4_res(xdr: *mut xdr_stream, ptr: *mut nlm4_res) -> bool {
    xdrgen_decode_netobj(xdr, &mut (*ptr).cookie) && xdrgen_decode_nlm4_stat(xdr, &mut (*ptr).stat)
}
unsafe fn xdrgen_decode_nlm4_testres(xdr: *mut xdr_stream, ptr: *mut nlm4_testres) -> bool {
    xdrgen_decode_netobj(xdr, &mut (*ptr).cookie) && xdrgen_decode_nlm4_testrply(xdr, &mut (*ptr).stat)
}
unsafe fn xdrgen_decode_nlm4_lock(xdr: *mut xdr_stream, ptr: *mut nlm4_lock) -> bool {
    if !xdrgen_decode_string(xdr, ptr as *mut string, LM_MAXSTRLEN) { return false; }
    xdrgen_decode_netobj(xdr, &mut (*ptr).fh) && xdrgen_decode_netobj(xdr, &mut (*ptr).oh) &&
        xdrgen_decode_int32(xdr, &mut (*ptr).svid) && xdrgen_decode_uint64(xdr, &mut (*ptr).l_offset) && xdrgen_decode_uint64(xdr, &mut (*ptr).l_len)
}
unsafe fn xdrgen_decode_nlm4_lockargs(xdr: *mut xdr_stream, ptr: *mut nlm4_lockargs) -> bool {
    xdrgen_decode_netobj(xdr, &mut (*ptr).cookie) && xdrgen_decode_bool(xdr, &mut (*ptr).block) && xdrgen_decode_bool(xdr, &mut (*ptr).exclusive) && xdrgen_decode_nlm4_lock(xdr, &mut (*ptr).alock) && xdrgen_decode_bool(xdr, &mut (*ptr).reclaim) && xdrgen_decode_int32(xdr, &mut (*ptr).state)
}
unsafe fn xdrgen_decode_nlm4_cancargs(xdr: *mut xdr_stream, ptr: *mut nlm4_cancargs) -> bool {
    xdrgen_decode_netobj(xdr, &mut (*ptr).cookie) && xdrgen_decode_bool(xdr, &mut (*ptr).block) && xdrgen_decode_bool(xdr, &mut (*ptr).exclusive) && xdrgen_decode_nlm4_lock(xdr, &mut (*ptr).alock)
}
unsafe fn xdrgen_decode_nlm4_testargs(xdr: *mut xdr_stream, ptr: *mut nlm4_testargs) -> bool {
    xdrgen_decode_netobj(xdr, &mut (*ptr).cookie) && xdrgen_decode_bool(xdr, &mut (*ptr).exclusive) && xdrgen_decode_nlm4_lock(xdr, &mut (*ptr).alock)
}
unsafe fn xdrgen_decode_nlm4_unlockargs(xdr: *mut xdr_stream, ptr: *mut nlm4_unlockargs) -> bool {
    xdrgen_decode_netobj(xdr, &mut (*ptr).cookie) && xdrgen_decode_nlm4_lock(xdr, &mut (*ptr).alock)
}
unsafe fn xdrgen_decode_nlm4_share(xdr: *mut xdr_stream, ptr: *mut nlm4_share) -> bool {
    if !xdrgen_decode_string(xdr, ptr as *mut string, LM_MAXSTRLEN) { return false; }
    xdrgen_decode_netobj(xdr, &mut (*ptr).fh) && xdrgen_decode_netobj(xdr, &mut (*ptr).oh) && xdrgen_decode_fsh4_mode(xdr, &mut (*ptr).mode) && xdrgen_decode_fsh4_access(xdr, &mut (*ptr).access)
}
unsafe fn xdrgen_decode_nlm4_shareargs(xdr: *mut xdr_stream, ptr: *mut nlm4_shareargs) -> bool { xdrgen_decode_netobj(xdr, &mut (*ptr).cookie) && xdrgen_decode_nlm4_share(xdr, &mut (*ptr).share) && xdrgen_decode_bool(xdr, &mut (*ptr).reclaim) }
unsafe fn xdrgen_decode_nlm4_shareres(xdr: *mut xdr_stream, ptr: *mut nlm4_shareres) -> bool { xdrgen_decode_netobj(xdr, &mut (*ptr).cookie) && xdrgen_decode_nlm4_stats(xdr, &mut (*ptr).stat) && xdrgen_decode_int32(xdr, &mut (*ptr).sequence) }
unsafe fn xdrgen_decode_nlm4_notify(xdr: *mut xdr_stream, ptr: *mut nlm4_notify) -> bool { xdrgen_decode_string(xdr, ptr as *mut string, LM_MAXNAMELEN) && xdrgen_decode_int32(xdr, &mut (*ptr).state) }
unsafe fn xdrgen_decode_nlm4_notifyargs(xdr: *mut xdr_stream, ptr: *mut nlm4_notifyargs) -> bool { xdrgen_decode_nlm4_notify(xdr, &mut (*ptr).notify) && xdr_stream_decode_opaque_fixed(xdr, (*ptr).private.as_mut_ptr(), SM_PRIV_SIZE) >= 0 }

unsafe fn xdrgen_encode_netobj(xdr: *mut xdr_stream, value: netobj) -> bool { xdr_stream_encode_opaque(xdr, value.data, value.len) >= 0 }
unsafe fn xdrgen_encode_fsh4_mode(xdr: *mut xdr_stream, value: fsh4_mode) -> bool { xdr_stream_encode_u32(xdr, value) == XDR_UNIT }
unsafe fn xdrgen_encode_fsh4_access(xdr: *mut xdr_stream, value: fsh4_access) -> bool { xdr_stream_encode_u32(xdr, value) == XDR_UNIT }
unsafe fn xdrgen_encode_uint64(xdr: *mut xdr_stream, value: uint64) -> bool { xdrgen_encode_unsigned_hyper(xdr, value) }
unsafe fn xdrgen_encode_int64(xdr: *mut xdr_stream, value: int64) -> bool { xdrgen_encode_hyper(xdr, value) }
unsafe fn xdrgen_encode_uint32(xdr: *mut xdr_stream, value: uint32) -> bool { xdrgen_encode_unsigned_long(xdr, value) }
unsafe fn xdrgen_encode_int32(xdr: *mut xdr_stream, value: int32) -> bool { xdrgen_encode_long(xdr, value) }
unsafe fn xdrgen_encode_nlm4_stats(xdr: *mut xdr_stream, value: nlm4_stats) -> bool { xdr_stream_encode_be32(xdr, value) == XDR_UNIT }
unsafe fn xdrgen_encode_nlm4_holder(xdr: *mut xdr_stream, value: *const nlm4_holder) -> bool { xdrgen_encode_bool(xdr, (*value).exclusive) && xdrgen_encode_int32(xdr, (*value).svid) && xdrgen_encode_netobj(xdr, (*value).oh) && xdrgen_encode_uint64(xdr, (*value).l_offset) && xdrgen_encode_uint64(xdr, (*value).l_len) }
unsafe fn xdrgen_encode_nlm4_testrply(xdr: *mut xdr_stream, ptr: *const nlm4_testrply) -> bool { xdrgen_encode_nlm4_stats(xdr, (*ptr).stat) && ((*ptr).stat != __constant_cpu_to_be32(NLM4_DENIED) || xdrgen_encode_nlm4_holder(xdr, &(*ptr).u.holder)) }
unsafe fn xdrgen_encode_nlm4_stat(xdr: *mut xdr_stream, value: *const nlm4_stat) -> bool { xdrgen_encode_nlm4_stats(xdr, (*value).stat) }
unsafe fn xdrgen_encode_nlm4_res(xdr: *mut xdr_stream, value: *const nlm4_res) -> bool { xdrgen_encode_netobj(xdr, (*value).cookie) && xdrgen_encode_nlm4_stat(xdr, &(*value).stat) }
unsafe fn xdrgen_encode_nlm4_testres(xdr: *mut xdr_stream, value: *const nlm4_testres) -> bool { xdrgen_encode_netobj(xdr, (*value).cookie) && xdrgen_encode_nlm4_testrply(xdr, &(*value).stat) }
unsafe fn xdrgen_encode_nlm4_lock(xdr: *mut xdr_stream, value: *const nlm4_lock) -> bool { if (*value).caller_name.len > LM_MAXSTRLEN { return false; } xdr_stream_encode_opaque(xdr, (*value).caller_name.data, (*value).caller_name.len) >= 0 && xdrgen_encode_netobj(xdr, (*value).fh) && xdrgen_encode_netobj(xdr, (*value).oh) && xdrgen_encode_int32(xdr, (*value).svid) && xdrgen_encode_uint64(xdr, (*value).l_offset) && xdrgen_encode_uint64(xdr, (*value).l_len) }
unsafe fn xdrgen_encode_nlm4_lockargs(xdr: *mut xdr_stream, value: *const nlm4_lockargs) -> bool { xdrgen_encode_netobj(xdr, (*value).cookie) && xdrgen_encode_bool(xdr, (*value).block) && xdrgen_encode_bool(xdr, (*value).exclusive) && xdrgen_encode_nlm4_lock(xdr, &(*value).alock) && xdrgen_encode_bool(xdr, (*value).reclaim) && xdrgen_encode_int32(xdr, (*value).state) }
unsafe fn xdrgen_encode_nlm4_cancargs(xdr: *mut xdr_stream, value: *const nlm4_cancargs) -> bool { xdrgen_encode_netobj(xdr, (*value).cookie) && xdrgen_encode_bool(xdr, (*value).block) && xdrgen_encode_bool(xdr, (*value).exclusive) && xdrgen_encode_nlm4_lock(xdr, &(*value).alock) }
unsafe fn xdrgen_encode_nlm4_testargs(xdr: *mut xdr_stream, value: *const nlm4_testargs) -> bool { xdrgen_encode_netobj(xdr, (*value).cookie) && xdrgen_encode_bool(xdr, (*value).exclusive) && xdrgen_encode_nlm4_lock(xdr, &(*value).alock) }
unsafe fn xdrgen_encode_nlm4_unlockargs(xdr: *mut xdr_stream, value: *const nlm4_unlockargs) -> bool { xdrgen_encode_netobj(xdr, (*value).cookie) && xdrgen_encode_nlm4_lock(xdr, &(*value).alock) }
unsafe fn xdrgen_encode_nlm4_share(xdr: *mut xdr_stream, value: *const nlm4_share) -> bool { if (*value).caller_name.len > LM_MAXSTRLEN { return false; } xdr_stream_encode_opaque(xdr, (*value).caller_name.data, (*value).caller_name.len) >= 0 && xdrgen_encode_netobj(xdr, (*value).fh) && xdrgen_encode_netobj(xdr, (*value).oh) && xdrgen_encode_fsh4_mode(xdr, (*value).mode) && xdrgen_encode_fsh4_access(xdr, (*value).access) }
unsafe fn xdrgen_encode_nlm4_shareargs(xdr: *mut xdr_stream, value: *const nlm4_shareargs) -> bool { xdrgen_encode_netobj(xdr, (*value).cookie) && xdrgen_encode_nlm4_share(xdr, &(*value).share) && xdrgen_encode_bool(xdr, (*value).reclaim) }
unsafe fn xdrgen_encode_nlm4_shareres(xdr: *mut xdr_stream, value: *const nlm4_shareres) -> bool { xdrgen_encode_netobj(xdr, (*value).cookie) && xdrgen_encode_nlm4_stats(xdr, (*value).stat) && xdrgen_encode_int32(xdr, (*value).sequence) }
unsafe fn xdrgen_encode_nlm4_notify(xdr: *mut xdr_stream, value: *const nlm4_notify) -> bool { if (*value).name.len > LM_MAXNAMELEN { return false; } xdr_stream_encode_opaque(xdr, (*value).name.data, (*value).name.len) >= 0 && xdrgen_encode_int32(xdr, (*value).state) }
unsafe fn xdrgen_encode_nlm4_notifyargs(xdr: *mut xdr_stream, value: *const nlm4_notifyargs) -> bool { xdrgen_encode_nlm4_notify(xdr, &(*value).notify) && xdr_stream_encode_opaque_fixed(xdr, (*value).private.as_ptr(), SM_PRIV_SIZE) >= 0 }

unsafe fn rq_argp<T>(rqstp: *mut svc_rqst) -> *mut T { (*rqstp).rq_argp as *mut T }
unsafe fn rq_resp<T>(rqstp: *mut svc_rqst) -> *mut T { (*rqstp).rq_resp as *mut T }
pub unsafe fn nlm4_svc_decode_nlm4_testargs(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_testargs(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_decode_nlm4_lockargs(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_lockargs(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_decode_nlm4_cancargs(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_cancargs(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_decode_nlm4_unlockargs(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_unlockargs(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_decode_nlm4_testres(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_testres(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_decode_nlm4_res(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_res(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_decode_nlm4_notifyargs(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_notifyargs(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_decode_nlm4_shareargs(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_shareargs(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_decode_nlm4_notify(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_decode_nlm4_notify(x, rq_argp(r)) }
pub unsafe fn nlm4_svc_encode_nlm4_testres(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_encode_nlm4_testres(x, rq_resp(r)) }
pub unsafe fn nlm4_svc_encode_nlm4_res(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_encode_nlm4_res(x, rq_resp(r)) }
pub unsafe fn nlm4_svc_encode_nlm4_shareres(r: *mut svc_rqst, x: *mut xdr_stream) -> bool { xdrgen_encode_nlm4_shareres(x, rq_resp(r)) }

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
