/* SPDX-License-Identifier: GPL-2.0-or-later */

// C header guard omitted; this file is intended to be included by the
// surrounding translation unit.

#[macro_export]
macro_rules! DEFINE_DROP_REASON {
    ($fn:ident, $fne:ident) => {
        $fn!(NOT_SPECIFIED); $fn!(NO_SOCKET); $fn!(SOCKET_CLOSE);
        $fn!(SOCKET_FILTER); $fn!(SOCKET_RCVBUFF); $fn!(UNIX_DISCONNECT);
        $fn!(UNIX_SKIP_OOB); $fn!(PKT_TOO_SMALL); $fn!(TCP_CSUM);
        $fn!(UDP_CSUM); $fn!(NETFILTER_DROP); $fn!(OTHERHOST);
        $fn!(IP_CSUM); $fn!(IP_INHDR); $fn!(IP_RPFILTER);
        $fn!(UNICAST_IN_L2_MULTICAST); $fn!(XFRM_POLICY); $fn!(IP_NOPROTO);
        $fn!(PROTO_MEM); $fn!(TCP_AUTH_HDR); $fn!(TCP_MD5NOTFOUND);
        $fn!(TCP_MD5UNEXPECTED); $fn!(TCP_MD5FAILURE); $fn!(TCP_AONOTFOUND);
        $fn!(TCP_AOUNEXPECTED); $fn!(TCP_AOKEYNOTFOUND); $fn!(TCP_AOFAILURE);
        $fn!(SOCKET_BACKLOG); $fn!(TCP_FLAGS); $fn!(TCP_ABORT_ON_DATA);
        $fn!(TCP_ZEROWINDOW); $fn!(TCP_OLD_DATA); $fn!(TCP_OVERWINDOW);
        $fn!(TCP_OFOMERGE); $fn!(TCP_RFC7323_PAWS); $fn!(TCP_RFC7323_PAWS_ACK);
        $fn!(TCP_RFC7323_TW_PAWS); $fn!(TCP_RFC7323_TSECR);
        $fn!(TCP_LISTEN_OVERFLOW); $fn!(TCP_OLD_SEQUENCE);
        $fn!(TCP_INVALID_SEQUENCE); $fn!(TCP_INVALID_END_SEQUENCE);
        $fn!(TCP_INVALID_ACK_SEQUENCE); $fn!(TCP_RESET); $fn!(TCP_INVALID_SYN);
        $fn!(TCP_CLOSE); $fn!(TCP_FASTOPEN); $fn!(TCP_OLD_ACK);
        $fn!(TCP_TOO_OLD_ACK); $fn!(TCP_ACK_UNSENT_DATA);
        $fn!(TCP_OFO_QUEUE_PRUNE); $fn!(TCP_OFO_DROP); $fn!(IP_OUTNOROUTES);
        $fn!(BPF_CGROUP_EGRESS); $fn!(IPV6DISABLED); $fn!(NEIGH_CREATEFAIL);
        $fn!(NEIGH_FAILED); $fn!(NEIGH_QUEUEFULL); $fn!(NEIGH_DEAD);
        $fn!(NEIGH_HH_FILLFAIL); $fn!(TC_EGRESS); $fn!(SECURITY_HOOK);
        $fn!(QDISC_DROP); $fn!(QDISC_BURST_DROP); $fn!(CPU_BACKLOG);
        $fn!(MACVLAN_BROADCAST_BACKLOG); $fn!(IPVLAN_MULTICAST_BACKLOG);
        $fn!(XDP); $fn!(TC_INGRESS); $fn!(UNHANDLED_PROTO); $fn!(SKB_CSUM);
        $fn!(SKB_GSO_SEG); $fn!(SKB_BAD_GSO); $fn!(SKB_UCOPY_FAULT);
        $fn!(DEV_HDR); $fn!(DEV_READY); $fn!(FULL_RING); $fn!(NOMEM);
        $fn!(HDR_TRUNC); $fn!(TAP_FILTER); $fn!(TAP_TXFILTER);
        $fn!(ICMP_CSUM); $fn!(INVALID_PROTO); $fn!(IP_INADDRERRORS);
        $fn!(IP_INNOROUTES); $fn!(IP_LOCAL_SOURCE); $fn!(IP_INVALID_SOURCE);
        $fn!(IP_LOCALNET); $fn!(IP_INVALID_DEST); $fn!(PKT_TOO_BIG);
        $fn!(DUP_FRAG); $fn!(FRAG_REASM_TIMEOUT); $fn!(FRAG_TOO_FAR);
        $fn!(TCP_MINTTL); $fn!(IPV6_BAD_EXTHDR); $fn!(IPV6_TOO_MANY_EXTHDRS);
        $fn!(IPV6_NDISC_FRAG); $fn!(IPV6_NDISC_HOP_LIMIT);
        $fn!(IPV6_NDISC_BAD_CODE); $fn!(IPV6_NDISC_BAD_OPTIONS);
        $fn!(IPV6_NDISC_NS_OTHERHOST); $fn!(QUEUE_PURGE); $fn!(TC_COOKIE_ERROR);
        $fn!(PACKET_SOCK_ERROR); $fn!(TC_CHAIN_NOTFOUND);
        $fn!(TC_RECLASSIFY_LOOP); $fn!(VXLAN_INVALID_HDR);
        $fn!(VXLAN_VNI_NOT_FOUND); $fn!(MAC_INVALID_SOURCE);
        $fn!(VXLAN_ENTRY_EXISTS); $fn!(NO_TX_TARGET); $fn!(IP_TUNNEL_ECN);
        $fn!(TUNNEL_TXINFO); $fn!(LOCAL_MAC); $fn!(ARP_PVLAN_DISABLE);
        $fn!(MAC_IEEE_MAC_CONTROL); $fn!(BRIDGE_INGRESS_STP_STATE);
        $fn!(CAN_RX_INVALID_FRAME); $fn!(CANFD_RX_INVALID_FRAME);
        $fn!(CANXL_RX_INVALID_FRAME); $fn!(PFMEMALLOC); $fn!(PSP_INPUT);
        $fn!(PSP_OUTPUT); $fn!(RECURSION_LIMIT); $fne!(MAX);
    };
}

#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum skb_drop_reason {
    SKB_NOT_DROPPED_YET = 0,
    SKB_CONSUMED,
    SKB_DROP_REASON_NOT_SPECIFIED,
    SKB_DROP_REASON_NO_SOCKET,
    SKB_DROP_REASON_SOCKET_CLOSE,
    SKB_DROP_REASON_SOCKET_FILTER,
    SKB_DROP_REASON_SOCKET_RCVBUFF,
    SKB_DROP_REASON_UNIX_DISCONNECT,
    SKB_DROP_REASON_UNIX_SKIP_OOB,
    SKB_DROP_REASON_PKT_TOO_SMALL,
    SKB_DROP_REASON_TCP_CSUM,
    SKB_DROP_REASON_UDP_CSUM,
    SKB_DROP_REASON_NETFILTER_DROP,
    SKB_DROP_REASON_OTHERHOST,
    SKB_DROP_REASON_IP_CSUM,
    SKB_DROP_REASON_IP_INHDR,
    SKB_DROP_REASON_IP_RPFILTER,
    SKB_DROP_REASON_UNICAST_IN_L2_MULTICAST,
    SKB_DROP_REASON_XFRM_POLICY,
    SKB_DROP_REASON_IP_NOPROTO,
    SKB_DROP_REASON_PROTO_MEM,
    SKB_DROP_REASON_TCP_AUTH_HDR,
    SKB_DROP_REASON_TCP_MD5NOTFOUND,
    SKB_DROP_REASON_TCP_MD5UNEXPECTED,
    SKB_DROP_REASON_TCP_MD5FAILURE,
    SKB_DROP_REASON_TCP_AONOTFOUND,
    SKB_DROP_REASON_TCP_AOUNEXPECTED,
    SKB_DROP_REASON_TCP_AOKEYNOTFOUND,
    SKB_DROP_REASON_TCP_AOFAILURE,
    SKB_DROP_REASON_SOCKET_BACKLOG,
    SKB_DROP_REASON_TCP_FLAGS,
    SKB_DROP_REASON_TCP_ABORT_ON_DATA,
    SKB_DROP_REASON_TCP_ZEROWINDOW,
    SKB_DROP_REASON_TCP_OLD_DATA,
    SKB_DROP_REASON_TCP_OVERWINDOW,
    SKB_DROP_REASON_TCP_OFOMERGE,
    SKB_DROP_REASON_TCP_RFC7323_PAWS,
    SKB_DROP_REASON_TCP_RFC7323_PAWS_ACK,
    SKB_DROP_REASON_TCP_RFC7323_TW_PAWS,
    SKB_DROP_REASON_TCP_RFC7323_TSECR,
    SKB_DROP_REASON_TCP_LISTEN_OVERFLOW,
    SKB_DROP_REASON_TCP_OLD_SEQUENCE,
    SKB_DROP_REASON_TCP_INVALID_SEQUENCE,
    SKB_DROP_REASON_TCP_INVALID_END_SEQUENCE,
    SKB_DROP_REASON_TCP_INVALID_ACK_SEQUENCE,
    SKB_DROP_REASON_TCP_RESET,
    SKB_DROP_REASON_TCP_INVALID_SYN,
    SKB_DROP_REASON_TCP_CLOSE,
    SKB_DROP_REASON_TCP_FASTOPEN,
    SKB_DROP_REASON_TCP_OLD_ACK,
    SKB_DROP_REASON_TCP_TOO_OLD_ACK,
    SKB_DROP_REASON_TCP_ACK_UNSENT_DATA,
    SKB_DROP_REASON_TCP_OFO_QUEUE_PRUNE,
    SKB_DROP_REASON_TCP_OFO_DROP,
    SKB_DROP_REASON_IP_OUTNOROUTES,
    SKB_DROP_REASON_BPF_CGROUP_EGRESS,
    SKB_DROP_REASON_IPV6DISABLED,
    SKB_DROP_REASON_NEIGH_CREATEFAIL,
    SKB_DROP_REASON_NEIGH_FAILED,
    SKB_DROP_REASON_NEIGH_QUEUEFULL,
    SKB_DROP_REASON_NEIGH_DEAD,
    SKB_DROP_REASON_NEIGH_HH_FILLFAIL,
    SKB_DROP_REASON_TC_EGRESS,
    SKB_DROP_REASON_SECURITY_HOOK,
    SKB_DROP_REASON_QDISC_DROP,
    SKB_DROP_REASON_QDISC_BURST_DROP,
    SKB_DROP_REASON_CPU_BACKLOG,
    SKB_DROP_REASON_MACVLAN_BROADCAST_BACKLOG,
    SKB_DROP_REASON_IPVLAN_MULTICAST_BACKLOG,
    SKB_DROP_REASON_XDP,
    SKB_DROP_REASON_TC_INGRESS,
    SKB_DROP_REASON_UNHANDLED_PROTO,
    SKB_DROP_REASON_SKB_CSUM,
    SKB_DROP_REASON_SKB_GSO_SEG,
    SKB_DROP_REASON_SKB_BAD_GSO,
    SKB_DROP_REASON_SKB_UCOPY_FAULT,
    SKB_DROP_REASON_DEV_HDR,
    SKB_DROP_REASON_DEV_READY,
    SKB_DROP_REASON_FULL_RING,
    SKB_DROP_REASON_NOMEM,
    SKB_DROP_REASON_HDR_TRUNC,
    SKB_DROP_REASON_TAP_FILTER,
    SKB_DROP_REASON_TAP_TXFILTER,
    SKB_DROP_REASON_ICMP_CSUM,
    SKB_DROP_REASON_INVALID_PROTO,
    SKB_DROP_REASON_IP_INADDRERRORS,
    SKB_DROP_REASON_IP_INNOROUTES,
    SKB_DROP_REASON_IP_LOCAL_SOURCE,
    SKB_DROP_REASON_IP_INVALID_SOURCE,
    SKB_DROP_REASON_IP_LOCALNET,
    SKB_DROP_REASON_IP_INVALID_DEST,
    SKB_DROP_REASON_PKT_TOO_BIG,
    SKB_DROP_REASON_DUP_FRAG,
    SKB_DROP_REASON_FRAG_REASM_TIMEOUT,
    SKB_DROP_REASON_FRAG_TOO_FAR,
    SKB_DROP_REASON_TCP_MINTTL,
    SKB_DROP_REASON_IPV6_BAD_EXTHDR,
    SKB_DROP_REASON_IPV6_TOO_MANY_EXTHDRS,
    SKB_DROP_REASON_IPV6_NDISC_FRAG,
    SKB_DROP_REASON_IPV6_NDISC_HOP_LIMIT,
    SKB_DROP_REASON_IPV6_NDISC_BAD_CODE,
    SKB_DROP_REASON_IPV6_NDISC_BAD_OPTIONS,
    SKB_DROP_REASON_IPV6_NDISC_NS_OTHERHOST,
    SKB_DROP_REASON_QUEUE_PURGE,
    SKB_DROP_REASON_TC_COOKIE_ERROR,
    SKB_DROP_REASON_PACKET_SOCK_ERROR,
    SKB_DROP_REASON_TC_CHAIN_NOTFOUND,
    SKB_DROP_REASON_TC_RECLASSIFY_LOOP,
    SKB_DROP_REASON_VXLAN_INVALID_HDR,
    SKB_DROP_REASON_VXLAN_VNI_NOT_FOUND,
    SKB_DROP_REASON_MAC_INVALID_SOURCE,
    SKB_DROP_REASON_VXLAN_ENTRY_EXISTS,
    SKB_DROP_REASON_NO_TX_TARGET,
    SKB_DROP_REASON_IP_TUNNEL_ECN,
    SKB_DROP_REASON_TUNNEL_TXINFO,
    SKB_DROP_REASON_LOCAL_MAC,
    SKB_DROP_REASON_ARP_PVLAN_DISABLE,
    SKB_DROP_REASON_MAC_IEEE_MAC_CONTROL,
    SKB_DROP_REASON_BRIDGE_INGRESS_STP_STATE,
    SKB_DROP_REASON_CAN_RX_INVALID_FRAME,
    SKB_DROP_REASON_CANFD_RX_INVALID_FRAME,
    SKB_DROP_REASON_CANXL_RX_INVALID_FRAME,
    SKB_DROP_REASON_PFMEMALLOC,
    SKB_DROP_REASON_PSP_INPUT,
    SKB_DROP_REASON_PSP_OUTPUT,
    SKB_DROP_REASON_RECURSION_LIMIT,
    SKB_DROP_REASON_MAX,
    SKB_DROP_REASON_SUBSYS_MASK = 0xffff0000,
}

pub const SKB_DROP_REASON_SUBSYS_SHIFT: u32 = 16;

#[macro_export]
macro_rules! SKB_DR_INIT { ($name:ident, $reason:ident) => {
    let mut $name: $crate::skb_drop_reason = $crate::skb_drop_reason::SKB_DROP_REASON_$reason;
}; }
#[macro_export]
macro_rules! SKB_DR { ($name:ident) => { SKB_DR_INIT!($name, NOT_SPECIFIED); }; }
#[macro_export]
macro_rules! SKB_DR_SET { ($name:ident, $reason:ident) => {
    $name = $crate::skb_drop_reason::SKB_DROP_REASON_$reason;
}; }
#[macro_export]
macro_rules! SKB_DR_OR { ($name:ident, $reason:ident) => {
    if $name == $crate::skb_drop_reason::SKB_DROP_REASON_NOT_SPECIFIED ||
       $name == $crate::skb_drop_reason::SKB_NOT_DROPPED_YET {
        SKB_DR_SET!($name, $reason);
    }
}; }

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
