/* SPDX-License-Identifier: GPL-2.0 */

/*
 * Rust translation of the C implementation of Buchi automaton, automatically
 * generated by tools/verification/rvgen from the linear temporal logic
 * specification.
 *
 * Original dependency intent: #include <linux/rv.h>
 */

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use core::ffi::{c_char, c_uint, c_ulong};

pub const MONITOR_NAME: &str = "test_bak_kunit";

#[repr(C)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ltl_atom {
    LTL_EVENT_A,
    LTL_EVENT_B,
    LTL_NUM_ATOM,
}

/* C static_assert intent: LTL_NUM_ATOM <= RV_MAX_LTL_ATOM. */

#[repr(C)]
pub struct task_struct {
    _private: [u8; 0],
}

#[repr(C)]
pub struct ltl_monitor {
    pub atoms: *mut c_ulong,
    pub states: *mut c_ulong,
}

unsafe extern "C" {
    fn test_bit(nr: c_ulong, addr: *const c_ulong) -> bool;
    fn __set_bit(nr: c_ulong, addr: *mut c_ulong);
}

static LTL_ATOM_NAME_EV_A: &[u8] = b"ev_a\0";
static LTL_ATOM_NAME_EV_B: &[u8] = b"ev_b\0";

static ltl_atom_names: [*const c_char; 2] = [
    LTL_ATOM_NAME_EV_A.as_ptr() as *const c_char,
    LTL_ATOM_NAME_EV_B.as_ptr() as *const c_char,
];

unsafe fn ltl_atom_str(atom: ltl_atom) -> *const c_char {
    *ltl_atom_names.get_unchecked(atom as usize)
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ltl_buchi_state {
    S0,
    S1,
    S2,
    S3,
    S4,
    RV_NUM_BA_STATES,
}

/* C static_assert intent: RV_NUM_BA_STATES <= RV_MAX_BA_STATES. */

unsafe fn ltl_start(_task: *mut task_struct, mon: *mut ltl_monitor) {
    let event_b: bool = test_bit(ltl_atom::LTL_EVENT_B as c_ulong, (*mon).atoms);
    let event_a: bool = test_bit(ltl_atom::LTL_EVENT_A as c_ulong, (*mon).atoms);
    let val1: bool = !event_a;

    if val1 {
        __set_bit(ltl_buchi_state::S0 as c_ulong, (*mon).states);
    }
    if true {
        __set_bit(ltl_buchi_state::S1 as c_ulong, (*mon).states);
    }
    if event_b {
        __set_bit(ltl_buchi_state::S4 as c_ulong, (*mon).states);
    }
}

unsafe fn ltl_possible_next_states(
    mon: *mut ltl_monitor,
    state: c_uint,
    next: *mut c_ulong,
) {
    let event_b: bool = test_bit(ltl_atom::LTL_EVENT_B as c_ulong, (*mon).atoms);
    let event_a: bool = test_bit(ltl_atom::LTL_EVENT_A as c_ulong, (*mon).atoms);
    let val1: bool = !event_a;

    match state {
        x if x == ltl_buchi_state::S0 as c_uint => {
            if val1 {
                __set_bit(ltl_buchi_state::S0 as c_ulong, next);
            }
            if true {
                __set_bit(ltl_buchi_state::S1 as c_ulong, next);
            }
            if event_b {
                __set_bit(ltl_buchi_state::S4 as c_ulong, next);
            }
        }
        x if x == ltl_buchi_state::S1 as c_uint => {
            if true {
                __set_bit(ltl_buchi_state::S1 as c_ulong, next);
            }
            if true && val1 {
                __set_bit(ltl_buchi_state::S2 as c_ulong, next);
            }
            if event_b && val1 {
                __set_bit(ltl_buchi_state::S3 as c_ulong, next);
            }
            if event_b {
                __set_bit(ltl_buchi_state::S4 as c_ulong, next);
            }
        }
        x if x == ltl_buchi_state::S2 as c_uint => {
            if true {
                __set_bit(ltl_buchi_state::S1 as c_ulong, next);
            }
            if true && val1 {
                __set_bit(ltl_buchi_state::S2 as c_ulong, next);
            }
            if event_b && val1 {
                __set_bit(ltl_buchi_state::S3 as c_ulong, next);
            }
            if event_b {
                __set_bit(ltl_buchi_state::S4 as c_ulong, next);
            }
        }
        x if x == ltl_buchi_state::S3 as c_uint => {
            if val1 {
                __set_bit(ltl_buchi_state::S0 as c_ulong, next);
            }
            if true {
                __set_bit(ltl_buchi_state::S1 as c_ulong, next);
            }
            if event_b {
                __set_bit(ltl_buchi_state::S4 as c_ulong, next);
            }
        }
        x if x == ltl_buchi_state::S4 as c_uint => {
            if val1 {
                __set_bit(ltl_buchi_state::S0 as c_ulong, next);
            }
            if true {
                __set_bit(ltl_buchi_state::S1 as c_ulong, next);
            }
            if event_b {
                __set_bit(ltl_buchi_state::S4 as c_ulong, next);
            }
        }
        _ => {}
    }
}

// SOURCE-COMMIT: 08dbfad3f5040f5bdb6c529da20d6d4e81fefd72
