/*
 * Copyright 2012-15 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * Authors: AMD
 */

// Dependency: drm/display/drm_dp_helper.h

pub const DP_SINK_HW_REVISION_START: u32 = 0x409;
/* Panel Replay */
pub const DP_PANEL_REPLAY_CAPABILITY_SUPPORT: u32 = 0x0b0;
pub const DP_PANEL_REPLAY_CAPABILITY: u32 = 0x0b1;
pub const DP_PR_SU_X_GRANULARITY_LOW: u32 = 0x0b2;
pub const DP_PR_SU_X_GRANULARITY_HIGH: u32 = 0x0b3;
pub const DP_PR_SU_Y_GRANULARITY: u32 = 0x0b4;
pub const DP_PR_SU_Y_GRANULARITY_EXTENDED_CAP_LOW: u32 = 0x0b5;
pub const DP_PR_SU_Y_GRANULARITY_EXTENDED_CAP_HIGH: u32 = 0x0b6;
pub const DP_PANEL_REPLAY_ENABLE_AND_CONFIGURATION_1: u32 = 0x1b0;
pub const DP_PANEL_REPLAY_ENABLE: u32 = 1 << 0;
pub const DP_PANEL_REPLAY_ENABLE_AND_CONFIGURATION_2: u32 = 0x1b1;
pub const DP_PR_ERROR_STATUS: u32 = 0x2020; /* DP 2.0 */
pub const DP_PR_REPLAY_SINK_STATUS: u32 = 0x2022;
pub const DP_PR_LINK_CRC_ERROR: u32 = 1 << 0;
pub const DP_PR_RFB_STORAGE_ERROR: u32 = 1 << 1;
pub const DP_PR_VSC_SDP_UNCORRECTABLE_ERROR: u32 = 1 << 2; /* eDP 1.4 */
pub const DP_PR_ASSDP_MISSING_ERROR: u32 = 1 << 3; /* eDP 1.5 */

#[repr(i32)]
pub enum dpcd_revision { DPCD_REV_10 = 0x10, DPCD_REV_11 = 0x11, DPCD_REV_12 = 0x12, DPCD_REV_13 = 0x13, DPCD_REV_14 = 0x14 }
#[repr(i32)]
pub enum dpcd_downstream_port_type { DOWNSTREAM_DP = 0, DOWNSTREAM_VGA, DOWNSTREAM_DVI_HDMI_DP_PLUS_PLUS, DOWNSTREAM_NONDDC }
#[repr(i32)]
pub enum dpcd_link_test_patterns { LINK_TEST_PATTERN_NONE = 0, LINK_TEST_PATTERN_COLOR_RAMP, LINK_TEST_PATTERN_VERTICAL_BARS, LINK_TEST_PATTERN_COLOR_SQUARES }
#[repr(i32)]
pub enum dpcd_test_color_format { TEST_COLOR_FORMAT_RGB = 0, TEST_COLOR_FORMAT_YCBCR422, TEST_COLOR_FORMAT_YCBCR444 }
#[repr(i32)]
pub enum dpcd_test_bit_depth { TEST_BIT_DEPTH_6 = 0, TEST_BIT_DEPTH_8, TEST_BIT_DEPTH_10, TEST_BIT_DEPTH_12, TEST_BIT_DEPTH_16 }

/* PHY (encoder) test patterns
The order of test patterns follows DPCD register PHY_TEST_PATTERN (0x248)
*/
#[repr(i32)]
pub enum dpcd_phy_test_patterns {
    PHY_TEST_PATTERN_NONE = 0, PHY_TEST_PATTERN_D10_2, PHY_TEST_PATTERN_SYMBOL_ERROR,
    PHY_TEST_PATTERN_PRBS7, PHY_TEST_PATTERN_80BIT_CUSTOM, PHY_TEST_PATTERN_CP2520_1,
    PHY_TEST_PATTERN_CP2520_2, PHY_TEST_PATTERN_CP2520_3,
    PHY_TEST_PATTERN_128b_132b_TPS1 = 0x8, PHY_TEST_PATTERN_128b_132b_TPS2 = 0x10,
    PHY_TEST_PATTERN_PRBS9 = 0x18, PHY_TEST_PATTERN_PRBS11 = 0x20,
    PHY_TEST_PATTERN_PRBS15 = 0x28, PHY_TEST_PATTERN_PRBS23 = 0x30,
    PHY_TEST_PATTERN_PRBS31 = 0x38, PHY_TEST_PATTERN_264BIT_CUSTOM = 0x40,
    PHY_TEST_PATTERN_SQUARE = 0x48, PHY_TEST_PATTERN_SQUARE_PRESHOOT_DISABLED = 0x49,
    PHY_TEST_PATTERN_SQUARE_DEEMPHASIS_DISABLED = 0x4A,
    PHY_TEST_PATTERN_SQUARE_PRESHOOT_DEEMPHASIS_DISABLED = 0x4B,
}
#[repr(i32)]
pub enum dpcd_test_dyn_range { TEST_DYN_RANGE_VESA = 0, TEST_DYN_RANGE_CEA }
#[repr(i32)]
pub enum dpcd_audio_test_pattern { AUDIO_TEST_PATTERN_OPERATOR_DEFINED = 0, AUDIO_TEST_PATTERN_SAWTOOTH }
#[repr(i32)]
pub enum dpcd_audio_sampling_rate { AUDIO_SAMPLING_RATE_32KHZ = 0, AUDIO_SAMPLING_RATE_44_1KHZ, AUDIO_SAMPLING_RATE_48KHZ, AUDIO_SAMPLING_RATE_88_2KHZ, AUDIO_SAMPLING_RATE_96KHZ, AUDIO_SAMPLING_RATE_176_4KHZ, AUDIO_SAMPLING_RATE_192KHZ }
#[repr(i32)]
pub enum dpcd_audio_channels { AUDIO_CHANNELS_1 = 0, AUDIO_CHANNELS_2, AUDIO_CHANNELS_3, AUDIO_CHANNELS_4, AUDIO_CHANNELS_5, AUDIO_CHANNELS_6, AUDIO_CHANNELS_7, AUDIO_CHANNELS_8, AUDIO_CHANNELS_COUNT }
#[repr(i32)]
pub enum dpcd_audio_test_pattern_periods { DPCD_AUDIO_TEST_PATTERN_PERIOD_NOTUSED = 0, DPCD_AUDIO_TEST_PATTERN_PERIOD_3, DPCD_AUDIO_TEST_PATTERN_PERIOD_6, DPCD_AUDIO_TEST_PATTERN_PERIOD_12, DPCD_AUDIO_TEST_PATTERN_PERIOD_24, DPCD_AUDIO_TEST_PATTERN_PERIOD_48, DPCD_AUDIO_TEST_PATTERN_PERIOD_96, DPCD_AUDIO_TEST_PATTERN_PERIOD_192, DPCD_AUDIO_TEST_PATTERN_PERIOD_384, DPCD_AUDIO_TEST_PATTERN_PERIOD_768, DPCD_AUDIO_TEST_PATTERN_PERIOD_1536 }

/* This enum is for programming DPCD TRAINING_PATTERN_SET */
#[repr(i32)]
pub enum dpcd_training_patterns { DPCD_TRAINING_PATTERN_VIDEOIDLE = 0, DPCD_TRAINING_PATTERN_1, DPCD_TRAINING_PATTERN_2, DPCD_TRAINING_PATTERN_3, DPCD_TRAINING_PATTERN_4 = 7, DPCD_128b_132b_TPS1 = 1, DPCD_128b_132b_TPS2 = 2, DPCD_128b_132b_TPS2_CDS = 3 }

/* This enum is for use with PsrSinkPsrStatus.bits.sinkSelfRefreshStatus
It defines the possible PSR states. */
#[repr(i32)]
pub enum dpcd_psr_sink_states { PSR_SINK_STATE_INACTIVE = 0, PSR_SINK_STATE_ACTIVE_CAPTURE_DISPLAY_ON_SOURCE_TIMING = 1, PSR_SINK_STATE_ACTIVE_DISPLAY_FROM_SINK_RFB = 2, PSR_SINK_STATE_ACTIVE_CAPTURE_DISPLAY_ON_SINK_TIMING = 3, PSR_SINK_STATE_ACTIVE_CAPTURE_TIMING_RESYNC = 4, PSR_SINK_STATE_SINK_INTERNAL_ERROR = 7 }

pub const DP_SOURCE_SEQUENCE: u32 = 0x30C;
pub const DP_SOURCE_TABLE_REVISION: u32 = 0x310;
pub const DP_SOURCE_PAYLOAD_SIZE: u32 = 0x311;
pub const DP_SOURCE_SINK_CAP: u32 = 0x317;
pub const DP_SOURCE_BACKLIGHT_LEVEL: u32 = 0x320;
pub const DP_SOURCE_BACKLIGHT_CURRENT_PEAK: u32 = 0x326;
pub const DP_SOURCE_BACKLIGHT_CONTROL: u32 = 0x32E;
pub const DP_SOURCE_BACKLIGHT_ENABLE: u32 = 0x32F;
pub const DP_SINK_DRR_GRANULARITY: u32 = 0x33B;
pub const DP_SOURCE_MINIMUM_HBLANK_SUPPORTED: u32 = 0x340;
pub const DP_SINK_PR_REPLAY_STATUS: u32 = 0x378;
pub const DP_SINK_PR_PIXEL_DEVIATION_PER_LINE: u32 = 0x379;
pub const DP_SINK_PR_MAX_NUMBER_OF_DEVIATION_LINE: u32 = 0x37A;
pub const DP_SINK_EMISSION_RATE: u32 = 0x37E;
pub const DP_SINK_PR_FRAME_SKIP_COUNT: u32 = 0x337;
/* Remove once drm_dp_helper.h is updated upstream */
pub const DP_TOTAL_LTTPR_CNT: u32 = 0xF000A; /* 2.1 */

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
