// SPDX-License-Identifier: GPL-2.0+
/*
 *  comedi/drivers/ni_routing/ni_device_routes/pxie-6535.rs
 *  List of valid routes for specific NI boards.
 *
 *  COMEDI - Linux Control and Measurement Device Interface
 *  Copyright (C) 2016 Spencer E. Olson <olsonse@umich.edu>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 */

// The contents of this file are generated using the tools in
// comedi/drivers/ni_routing/tools.
// External declarations and macros are supplied by the corresponding Rust dependencies.

pub static mut ni_pxie_6535_device_routes: ni_device_routes = ni_device_routes {
    device: "pxie-6535",
    routes: &[
        ni_route_set { dest: NI_PFI(0), src: &[NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: NI_PFI(1), src: &[NI_PFI(0),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: NI_PFI(2), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: NI_PFI(3), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: NI_PFI(4), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),TRIGGER_LINE(7),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_SampleClock,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: NI_PFI(5), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),TRIGGER_LINE(7),NI_DI_SampleClock,NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: TRIGGER_LINE(0), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: TRIGGER_LINE(1), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: TRIGGER_LINE(2), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: TRIGGER_LINE(3), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: TRIGGER_LINE(4), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: TRIGGER_LINE(5), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: TRIGGER_LINE(6), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: TRIGGER_LINE(7), src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),NI_DI_StartTrigger,NI_DI_ReferenceTrigger,NI_DI_InputBufferFull,NI_DI_ReadyForStartEvent,NI_DI_ReadyForTransferEventBurst,NI_DI_ReadyForTransferEventPipelined,NI_DO_SampleClock,NI_DO_StartTrigger,NI_DO_OutputBufferFull,NI_DO_DataActiveEvent,NI_DO_ReadyForStartEvent,NI_DO_ReadyForTransferEvent,NI_ChangeDetectionEvent,0] },
        ni_route_set { dest: NI_DI_SampleClock, src: &[NI_PFI(5),TRIGGER_LINE(7),0] },
        ni_route_set { dest: NI_DI_StartTrigger, src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),0] },
        ni_route_set { dest: NI_DI_ReferenceTrigger, src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),0] },
        ni_route_set { dest: NI_DI_PauseTrigger, src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),0] },
        ni_route_set { dest: NI_DO_SampleClock, src: &[NI_PFI(4),TRIGGER_LINE(7),0] },
        ni_route_set { dest: NI_DO_StartTrigger, src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),0] },
        ni_route_set { dest: NI_DO_PauseTrigger, src: &[NI_PFI(0),NI_PFI(1),NI_PFI(2),NI_PFI(3),NI_PFI(4),NI_PFI(5),TRIGGER_LINE(0),TRIGGER_LINE(1),TRIGGER_LINE(2),TRIGGER_LINE(3),TRIGGER_LINE(4),TRIGGER_LINE(5),TRIGGER_LINE(6),0] },
        ni_route_set { dest: 0, src: &[] },
    ],
};

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
