/* SPDX-License-Identifier: MIT */
/*
 * Copyright 2022 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * Authors: AMD
 */

// Dependency preserved from: dcn31/dcn31_dccg.h

macro_rules! DCCG_SFII {
    ($block:ident, $reg_name:ident, $field_prefix:ident, $field_name:ident, $inst:expr, $post_fix:ident) => {
        .$field_prefix##_ $field_name[$inst] = $block##_ $inst##_ $reg_name##__##$field_prefix##_ $inst##_ $field_name##$post_fix
    };
}

macro_rules! DCCG_REG_LIST_DCN314 {
    () => {
        SR!(DPPCLK_DTO_CTRL), DCCG_SRII!(DTO_PARAM, DPPCLK, 0), DCCG_SRII!(DTO_PARAM, DPPCLK, 1),
        DCCG_SRII!(DTO_PARAM, DPPCLK, 2), DCCG_SRII!(DTO_PARAM, DPPCLK, 3),
        DCCG_SRII!(CLOCK_CNTL, HDMICHARCLK, 0), SR!(PHYASYMCLK_CLOCK_CNTL), SR!(PHYBSYMCLK_CLOCK_CNTL),
        SR!(PHYCSYMCLK_CLOCK_CNTL), SR!(PHYDSYMCLK_CLOCK_CNTL), SR!(PHYESYMCLK_CLOCK_CNTL),
        SR!(DPSTREAMCLK_CNTL), SR!(HDMISTREAMCLK_CNTL), SR!(SYMCLK32_SE_CNTL), SR!(SYMCLK32_LE_CNTL),
        DCCG_SRII!(PIXEL_RATE_CNTL, OTG, 0), DCCG_SRII!(PIXEL_RATE_CNTL, OTG, 1),
        DCCG_SRII!(PIXEL_RATE_CNTL, OTG, 2), DCCG_SRII!(PIXEL_RATE_CNTL, OTG, 3),
        DCCG_SRII!(MODULO, DTBCLK_DTO, 0), DCCG_SRII!(MODULO, DTBCLK_DTO, 1),
        DCCG_SRII!(MODULO, DTBCLK_DTO, 2), DCCG_SRII!(MODULO, DTBCLK_DTO, 3),
        DCCG_SRII!(PHASE, DTBCLK_DTO, 0), DCCG_SRII!(PHASE, DTBCLK_DTO, 1),
        DCCG_SRII!(PHASE, DTBCLK_DTO, 2), DCCG_SRII!(PHASE, DTBCLK_DTO, 3),
        SR!(DCCG_AUDIO_DTBCLK_DTO_MODULO), SR!(DCCG_AUDIO_DTBCLK_DTO_PHASE), SR!(DCCG_AUDIO_DTO_SOURCE),
        SR!(DENTIST_DISPCLK_CNTL), SR!(DSCCLK0_DTO_PARAM), SR!(DSCCLK1_DTO_PARAM), SR!(DSCCLK2_DTO_PARAM),
        SR!(DSCCLK3_DTO_PARAM), SR!(DSCCLK_DTO_CTRL), SR!(DCCG_GATE_DISABLE_CNTL), SR!(DCCG_GATE_DISABLE_CNTL2),
        SR!(DCCG_GATE_DISABLE_CNTL3), SR!(HDMISTREAMCLK0_DTO_PARAM), SR!(OTG_PIXEL_RATE_DIV), SR!(DTBCLK_P_CNTL),
        SR!(DC_MEM_GLOBAL_PWR_REQ_CNTL), SR!(MICROSECOND_TIME_BASE_DIV)
    };
}

// The following register-field lists are retained as token macros; their
// constituent SR/SFI/SF helpers are supplied by the dependent header.
macro_rules! DCCG_MASK_SH_LIST_DCN314_COMMON { ($mask_sh:ident) => {
    DCCG_SFI!(DPPCLK_DTO_CTRL, DTO_DB_EN, DPPCLK, 0, $mask_sh), DCCG_SFI!(DPPCLK_DTO_CTRL, DTO_DB_EN, DPPCLK, 1, $mask_sh),
    DCCG_SFI!(DPPCLK_DTO_CTRL, DTO_DB_EN, DPPCLK, 2, $mask_sh), DCCG_SFI!(DPPCLK_DTO_CTRL, DTO_DB_EN, DPPCLK, 3, $mask_sh),
    DCCG_SF!(DPPCLK0_DTO_PARAM, DPPCLK0_DTO_PHASE, $mask_sh), DCCG_SF!(DPPCLK0_DTO_PARAM, DPPCLK0_DTO_MODULO, $mask_sh),
    DCCG_SF!(HDMICHARCLK0_CLOCK_CNTL, HDMICHARCLK0_EN, $mask_sh), DCCG_SF!(HDMICHARCLK0_CLOCK_CNTL, HDMICHARCLK0_SRC_SEL, $mask_sh),
    DCCG_SF!(DPSTREAMCLK_CNTL, DPSTREAMCLK0_EN, $mask_sh), DCCG_SF!(DPSTREAMCLK_CNTL, DPSTREAMCLK1_EN, $mask_sh),
    DCCG_SF!(DPSTREAMCLK_CNTL, DPSTREAMCLK2_EN, $mask_sh), DCCG_SF!(DPSTREAMCLK_CNTL, DPSTREAMCLK3_EN, $mask_sh),
    DCCG_SF!(DPSTREAMCLK_CNTL, DPSTREAMCLK0_SRC_SEL, $mask_sh), DCCG_SF!(DPSTREAMCLK_CNTL, DPSTREAMCLK1_SRC_SEL, $mask_sh),
    DCCG_SF!(DPSTREAMCLK_CNTL, DPSTREAMCLK2_SRC_SEL, $mask_sh), DCCG_SF!(DPSTREAMCLK_CNTL, DPSTREAMCLK3_SRC_SEL, $mask_sh),
    DCCG_SF!(HDMISTREAMCLK_CNTL, HDMISTREAMCLK0_EN, $mask_sh), DCCG_SF!(HDMISTREAMCLK_CNTL, HDMISTREAMCLK0_SRC_SEL, $mask_sh),
    DCCG_SF!(SYMCLK32_SE_CNTL, SYMCLK32_SE0_SRC_SEL, $mask_sh), DCCG_SF!(SYMCLK32_SE_CNTL, SYMCLK32_SE1_SRC_SEL, $mask_sh),
    DCCG_SF!(SYMCLK32_SE_CNTL, SYMCLK32_SE2_SRC_SEL, $mask_sh), DCCG_SF!(SYMCLK32_SE_CNTL, SYMCLK32_SE3_SRC_SEL, $mask_sh),
    DCCG_SF!(SYMCLK32_SE_CNTL, SYMCLK32_SE0_EN, $mask_sh), DCCG_SF!(SYMCLK32_SE_CNTL, SYMCLK32_SE1_EN, $mask_sh),
    DCCG_SF!(SYMCLK32_SE_CNTL, SYMCLK32_SE2_EN, $mask_sh), DCCG_SF!(SYMCLK32_SE_CNTL, SYMCLK32_SE3_EN, $mask_sh),
    DCCG_SF!(SYMCLK32_LE_CNTL, SYMCLK32_LE0_SRC_SEL, $mask_sh), DCCG_SF!(SYMCLK32_LE_CNTL, SYMCLK32_LE1_SRC_SEL, $mask_sh),
    DCCG_SF!(SYMCLK32_LE_CNTL, SYMCLK32_LE0_EN, $mask_sh), DCCG_SF!(SYMCLK32_LE_CNTL, SYMCLK32_LE1_EN, $mask_sh),
    DCCG_SF!(HDMISTREAMCLK0_DTO_PARAM, HDMISTREAMCLK0_DTO_PHASE, $mask_sh), DCCG_SF!(HDMISTREAMCLK0_DTO_PARAM, HDMISTREAMCLK0_DTO_MODULO, $mask_sh)
}; }

// Remaining macro entries are preserved verbatim in a token-oriented Rust macro.
macro_rules! DCCG_MASK_SH_LIST_DCN314 { ($mask_sh:ident) => {
    DCCG_MASK_SH_LIST_DCN314_COMMON!($mask_sh),
    DCCG_SFI!(DPPCLK_DTO_CTRL, DTO_ENABLE, DPPCLK, 0, $mask_sh), DCCG_SFI!(DPPCLK_DTO_CTRL, DTO_ENABLE, DPPCLK, 1, $mask_sh),
    DCCG_SFI!(DPPCLK_DTO_CTRL, DTO_ENABLE, DPPCLK, 2, $mask_sh), DCCG_SFI!(DPPCLK_DTO_CTRL, DTO_ENABLE, DPPCLK, 3, $mask_sh),
    DCCG_SF!(PHYASYMCLK_CLOCK_CNTL, PHYASYMCLK_FORCE_EN, $mask_sh), DCCG_SF!(PHYASYMCLK_CLOCK_CNTL, PHYASYMCLK_FORCE_SRC_SEL, $mask_sh),
    DCCG_SF!(PHYBSYMCLK_CLOCK_CNTL, PHYBSYMCLK_FORCE_EN, $mask_sh), DCCG_SF!(PHYBSYMCLK_CLOCK_CNTL, PHYBSYMCLK_FORCE_SRC_SEL, $mask_sh),
    DCCG_SF!(PHYCSYMCLK_CLOCK_CNTL, PHYCSYMCLK_FORCE_EN, $mask_sh), DCCG_SF!(PHYCSYMCLK_CLOCK_CNTL, PHYCSYMCLK_FORCE_SRC_SEL, $mask_sh),
    DCCG_SF!(PHYDSYMCLK_CLOCK_CNTL, PHYDSYMCLK_FORCE_EN, $mask_sh), DCCG_SF!(PHYDSYMCLK_CLOCK_CNTL, PHYDSYMCLK_FORCE_SRC_SEL, $mask_sh),
    DCCG_SF!(PHYESYMCLK_CLOCK_CNTL, PHYESYMCLK_FORCE_EN, $mask_sh), DCCG_SF!(PHYESYMCLK_CLOCK_CNTL, PHYESYMCLK_FORCE_SRC_SEL, $mask_sh),
    DCCG_SF!(HDMISTREAMCLK_CNTL, HDMISTREAMCLK0_DTO_FORCE_DIS, $mask_sh), DCCG_SF!(DSCCLK_DTO_CTRL, DSCCLK0_DTO_ENABLE, $mask_sh),
    DCCG_SF!(DSCCLK_DTO_CTRL, DSCCLK1_DTO_ENABLE, $mask_sh), DCCG_SF!(DSCCLK_DTO_CTRL, DSCCLK2_DTO_ENABLE, $mask_sh),
    DCCG_SF!(DSCCLK_DTO_CTRL, DSCCLK3_DTO_ENABLE, $mask_sh), DCCG_SF!(DCCG_GATE_DISABLE_CNTL2, PHYASYMCLK_GATE_DISABLE, $mask_sh),
    DCCG_SF!(DCCG_GATE_DISABLE_CNTL2, PHYBSYMCLK_GATE_DISABLE, $mask_sh), DCCG_SF!(DCCG_GATE_DISABLE_CNTL2, PHYCSYMCLK_GATE_DISABLE, $mask_sh),
    DCCG_SF!(DCCG_GATE_DISABLE_CNTL2, PHYDSYMCLK_GATE_DISABLE, $mask_sh), DCCG_SF!(DCCG_GATE_DISABLE_CNTL2, PHYESYMCLK_GATE_DISABLE, $mask_sh),
    DCCG_SF!(HDMISTREAMCLK0_DTO_PARAM, HDMISTREAMCLK0_DTO_MODULO, $mask_sh), DCCG_SF!(DENTIST_DISPCLK_CNTL, DENTIST_DISPCLK_RDIVIDER, $mask_sh),
    DCCG_SF!(DENTIST_DISPCLK_CNTL, DENTIST_DISPCLK_WDIVIDER, $mask_sh)
}; }

extern "C" {
    pub fn dccg314_create(ctx: *mut dc_context, regs: *const dccg_registers, dccg_shift: *const dccg_shift, dccg_mask: *const dccg_mask) -> *mut dccg;
    pub fn dccg314_set_dpstreamclk(dccg: *mut dccg, src: enum_streamclk_source, otg_inst: i32, dp_hpo_inst: i32);
}

// SOURCE-COMMIT: d482bb509b7d065808de40ce78b5bca39f40b783
